tokio-rs/tokio

examples/chat.rs, examples/compress.rs, examples/connect.rs, examples/echo-threads.rs, examples/echo.rs, examples/proxy.rs, examples/sink.rs, examples/tinydb.rs, examples/tinyhttp.rs, examples/udp-codec.rs, src/lib.rs, src/net/tcp.rs, src/reactor/mod.rs, tests/line-frames.rs
In accordance with tokio-rs/tokio-rfcs#3, the executor functionality of
Tokio is being removed and will be relocated into futures-rs as a
"current thread" executor.
This PR removes task execution from the code base. As a temporary
mesure, all examples and tests are switched to using CpuPool.
Depends on #19.
=> Remove executor from reactor.

Cargo.toml, src/lib.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs
This is an initial implementation making `Handle: Send + Sync`. It uses
a `RwLock` to coordinate access to the underlying state storage. An
implementation without the lock is left to later.
This pass also leaves a lot of dead code that can be removed in later
commits.
This is inspired by #34
=> Make Handle `Send + Sync`.

src/net/tcp.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs
No need for oneshot shenanigans as now we'll always have the `Handle` available
to us regardless of what thread we're on to associate a new socket
This PR is based on https://github.com/tokio-rs/tokio/pull/49, only the last commit needs to be reviewed.
=> Remove `TcpListener::pending_accept` field

src/net/tcp.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs
This is no longer needed now that the public-facing `CoreId` has been removed
This PR is based on https://github.com/tokio-rs/tokio/pull/50, only the last commit needs to be reviewed.
=> Remove `NEXT_LOOP_ID` 

examples/echo-threads.rs, examples/tinyhttp.rs, src/net/tcp.rs, src/net/udp/mod.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs
This commit renames the various constructors of networking types to have a
`_std` suffix instead of a smorgasboard of other suffixes, canonicalizing on
`_std` as the suffix for constructors which take the libstd corresponding types.
This PR is based on https://github.com/tokio-rs/tokio/pull/51, only the last commit needs to be reviewed.
=> Rename networking constructors with `_std` 

examples/echo-threads.rs, examples/tinyhttp.rs, src/net/tcp.rs, src/net/udp/mod.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs, tests/drop-core.rs
This commit is targeted at solving tokio-rs/tokio-core#12 and incorporates the
solution from tokio-rs/tokio-core#17. Namely the `need_read` and `need_write`
functions on `PollEvented` now return an error when the connected reactor has
gone away and the task cannot be blocked. This will typically naturally
translate to errors being returned by various connected I/O objects and should
help tear down the world in a clean-ish fashion.
This PR is based on https://github.com/tokio-rs/tokio/pull/52, only the last commit needs to be reviewed.
=> Change `need_read` and `need_write` to return an error 

Cargo.toml, examples/echo-threads.rs, examples/tinyhttp.rs, src/net/tcp.rs, src/net/udp/mod.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs, tests/drop-core.rs
This should allow configuration over what reactor accepted streams go on to by
giving back a libstd-bound object that can then be used later in conjunction
with `TcpStream::from_std`.
This PR is based on https://github.com/tokio-rs/tokio/pull/53, only the last commit needs to be reviewed.
=> Add TcpListener::accept_std as a method 

Cargo.toml, examples/echo-threads.rs, examples/tinyhttp.rs, src/net/tcp.rs, src/net/udp/mod.rs, src/reactor/io_token.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs, tests/drop-core.rs
This commit changes the `PollEvented::deregister` signature from
fn deregister(self, handle: &Handle) -> io::Result<()>
to
fn deregister(&self) -> io::Result<()>
Now that the handles are `Send` and `Sync` there's no longer any need to pass it
in (it's already stored in the `PollEvented` itself). Additionally this switches
to `&self` instead of `self` to allow reclamation of the internal resources if
necessary.
This PR is based on https://github.com/tokio-rs/tokio/pull/54, only the last commit needs to be reviewed.
=> Tweak the `PollEvented::deregister` signature 

examples/chat.rs, examples/compress.rs, examples/connect.rs, examples/echo-threads.rs, examples/echo-udp.rs, examples/echo.rs, examples/hello.rs, examples/proxy.rs, examples/sink.rs, examples/tinydb.rs, examples/tinyhttp.rs, examples/udp-codec.rs, src/lib.rs, src/reactor/mod.rs, tests/buffered.rs, tests/chain.rs, tests/echo.rs, tests/limit.rs, tests/line-frames.rs, tests/pipe-hup.rs, tests/stream-buffered.rs, tests/tcp.rs, tests/udp.rs
This commit removes the `Reactor::run` method which has previously been used to
execute futures and turn the reactor at the same time. The tests/examples made
heavy usage of this method but they have now all temporarily moved to `wait()`
until the futures dependency is upgraded. In the meantime this'll allow us to
further trim down the `Reactor` APIs to their final state.
This PR is based on https://github.com/tokio-rs/tokio/pull/57, only the last commit needs to be reviewed.
=> Remove the `Reactor::run` method

src/reactor/global.rs, src/reactor/mod.rs, tests/wakeup.rs
This method is intended to be used to wake up the reactor from a remote thread
if necessary, forcing it to return from a blocked call of `turn` or otherwise
prevent the next call to `turn` to from blocking.
This PR is based on https://github.com/tokio-rs/tokio/pull/58, only the last commit needs to be reviewed.
=> Add a `Handle::wakeup` method 

examples/chat.rs, examples/compress.rs, examples/connect.rs, examples/echo-threads.rs, examples/echo-udp.rs, examples/echo.rs, examples/hello.rs, examples/proxy.rs, examples/sink.rs, examples/tinydb.rs, examples/udp-codec.rs, src/lib.rs, src/net/tcp.rs, src/net/udp/mod.rs, tests/buffered.rs, tests/chain.rs, tests/drop-core.rs, tests/echo.rs, tests/global.rs, tests/limit.rs, tests/line-frames.rs, tests/stream-buffered.rs, tests/tcp.rs, tests/udp.rs
This commit removes the `Handle` argument from the following constructors
* `TcpListener::bind`
* `TcpStream::connect`
* `UdpSocket::bind`
The `Handle` argument remains on the various `*_std` constructors as they're
more low-level, but this otherwise is intended to set forth a precedent of by
default not taking `Handle` arguments and instead relying on the global
`Handle::default` return value when necesary.
This PR is based on https://github.com/tokio-rs/tokio/pull/60, only the last commit needs to be reviewed.
=> Remove `Handle` argument from I/O constructors 

src/reactor/mod.rs
This is mostly just future-proofing, the type doesn't actually do anything right
now.
This PR is based on https://github.com/tokio-rs/tokio/pull/59, only the last commit needs to be reviewed.
=> Return a `Turn` type from the `turn` method 

src/reactor/mod.rs
Eventually mio won't provide an indexable interface, so switch over to using the
iterator-based interface for now.
=> Use an events iterator rather than indexing

examples/connect.rs, examples/udp-codec.rs, src/lib.rs, src/net/udp/frame.rs, src/net/udp/mod.rs, tests/udp.rs
Change the signature of UdpCodec::encode
Now it is:
```
fn encode(&mut self, msg: Self::Out, buf: &mut Vec<u8>)
-> Result<SocketAddr, Self::Error>;
```
Closes https://github.com/tokio-rs/tokio/issues/79
=> Fix UdpCodec::encode

Cargo.toml, src/reactor/mod.rs
I've often found this to be quite useful when debugging why event loops are
stuck or some other bug looks to be in play.
=> Add debug logs for how long dispatch takes

Cargo.toml, src/net/tcp.rs, tests/drop-core.rs
This has been deprecated in mio.
=> Remove &addr arg from TcpListener::from_std

src/net/udp/mod.rs, tests/udp.rs
All other fns take `&SocketAddr`.
=> Update send_dgram function signature.

src/net/tcp.rs
These fns were deprecated / missing on the std equivalent types.
=> Remove only_v6 from TCP types

examples/chat.rs, examples/compress.rs, examples/echo-threads.rs, examples/echo.rs, examples/hello.rs, examples/proxy.rs, examples/sink.rs, examples/tinydb.rs, src/lib.rs, src/net/tcp.rs, tests/buffered.rs, tests/chain.rs, tests/echo.rs, tests/global.rs, tests/limit.rs, tests/line-frames.rs, tests/stream-buffered.rs, tests/tcp.rs
std's `Incoming` iterator yields `TcpStream` instances. This patch
updates the `Incoming` future to match this signature.
This changes the yielded value from `(TcpStream, SocketAddr)` ->
`TcpStream`.
=> Change `net::Incoming` signature to match std.

src/net/udp/mod.rs
These fns are not included on std's UdpSocket.
=> Remove UDP only_v6 accessors.

src/reactor/mod.rs
This allows some token space to be used internally. Also, Mio 0.7 will
be limiting the token space some as well.
Mio: https://github.com/carllerche/mio/issues/788
Closes #42
=> Limit the max number of registered resources

Cargo.toml, examples/chat.rs, examples/compress.rs, examples/connect.rs, examples/echo-threads.rs, examples/echo-udp.rs, examples/echo.rs, examples/hello.rs, examples/proxy.rs, examples/sink.rs, examples/tinydb.rs, examples/tinyhttp.rs, examples/udp-codec.rs, tests/buffered.rs, tests/chain.rs, tests/drop-core.rs, tests/echo.rs, tests/global.rs, tests/limit.rs, tests/line-frames.rs, tests/pipe-hup.rs, tests/stream-buffered.rs, tests/tcp.rs, tests/udp.rs
This patch also updates tests and examples to remove deprecated API
usage.
=> Track futures tokio-reform branch

tokio-io/src/shutdown.rs
fix issue https://github.com/tokio-rs/tokio/issues/100
=> fix: struct shoutdown ignore Async::NotReady

examples/connect.rs, examples/udp-codec.rs, src/net/mod.rs, src/net/udp/frame.rs, src/net/udp/mod.rs, tests/udp.rs
Instead, use `UdpFramed::new` to create a framed wrapper around the UDP
socket.
=> Remove `framed` fn from `UdpSocket`

Cargo.toml
Tokio depends on the latest Mio point release, so update Cargo.toml to
reflect this.
=> Update the required Mio point release.

src/executor/current_thread.rs
This function could not be called from a public setting in the first
place due to the argument types being private.
=> Remove fn that was never intended to be pub

src/executor/current_thread/mod.rs, src/executor/current_thread/scheduler.rs, tests/current_thread.rs
CurrentThread::turn uses a turn count strategy to allow `turn` to not
run infinitely. Currently, there is a bug where spawned tasks will not
get executed in calls to `turn`.
This patch fixes the bug by correctly setting the turn count for newly
spawned tasks.
=> Fix bug with CurrentThread::turn

tokio-io/src/length_delimited.rs, tokio-io/tests/length_delimited.rs
This method is useful when reading from a operating system service.
=> length_delimited: add a native_endian builder method

src/executor/current_thread/scheduler.rs, src/reactor/mod.rs, tests/current_thread.rs
The logic that enables `CurrentThread::turn` to avoid unbounded
iteration was incorrect. It was possible for unfortunate timing to
result in a dead lock.
This patch provides a fix as well as a test.
=> Fix race condition in CurrentThread.

src/executor/current_thread/mod.rs, src/executor/current_thread/scheduler.rs, tests/current_thread.rs
Currently, the thread-local tracking the current thread executor is not
set when a task is dropped. This means that one cannot spawn a new
future from within the drop implementation of another future.
This patch adds support for this by setting the thread-local before
releasing a task.
This implementation is a bit messy. It probably could be cleaned up, but
this is being put off in favor of trying a more comprehensive
reorganization once the current thread executor is feature complete.
=> Support current_thread::spawn from task drop

src/atomic_task.rs, src/lib.rs, src/net/tcp.rs, src/net/udp/mod.rs, src/reactor/background.rs, src/reactor/mod.rs, src/reactor/poll_evented.rs, src/reactor/poll_evented2.rs, src/reactor/registration.rs, tests/global.rs
This patch makes a significant change to how I/O resources bind to a
reactor. Currently, an I/O resource (TCP, UDP, PollEvented) will bind
itself with a reactor upon creation.
First, some history.
Originally, tokio-core required that I/O resources be explicitly
associated with a reactor upon creation by passing in a `&Handle`. Tokio
reform introduced a default reactor. If I/O resources do not specify a
reactor upon creation, then the default reactor is used.
However, futures tend to favor being lazy. Creating a future should do
no work, instead it is defining a computation to be performed once the
future is executed. Binding an I/O resource with a reactor on creation
goes against this pattern.
This patch fixes this by allowing I/O resources to lazily bind to a
reactor. An explicit …
=> I/O resources lazily bind to reactor.

Cargo.toml, README.md, src/lib.rs, src/reactor/mod.rs, src/reactor/poll_evented2.rs, src/reactor/registration.rs, tokio-io/src/async_read.rs, tokio-io/src/async_write.rs
This patch updates the documentation for a number of APIs. It also
introduces a prelude module and an io facade module, re-exporting types
from tokio-io.
=> Add `io` facade and update `reactor` docs

tokio-io/src/async_read.rs, tokio-io/src/async_write.rs, tokio-io/src/framed_write.rs, tokio-io/src/io/copy.rs, tokio-io/src/io/flush.rs, tokio-io/src/io/read.rs, tokio-io/src/io/read_exact.rs, tokio-io/src/io/write_all.rs, tokio-io/src/length_delimited.rs
This removes the need for the `try_nb` macro as well as bring the traits
closer in line with the planed 0.2 iteration.
=> Add AsyncRead::poll_read, AsyncWrite::poll_write.

src/executor/mod.rs, tests/global.rs
Currently, `tokio::spawn` matched the `spawn` function from futures 0.2.
However, this adds additional ergonomic overhead and removes the ability
to spawn from a drop fn. See rust-lang-nursery/futures-rs#830.
This patch switches the behavior to access the thread-local variable
referencing the default executor directly in the `spawn` function.
=> Tweak the `tokio::spawn` function

examples/echo-udp.rs, src/lib.rs, src/net/tcp.rs, src/net/udp/frame.rs, src/net/udp/mod.rs, tests/udp.rs
Tokio is moving away from using `WouldBlock`, instead favoring
`Async::NotReady`.
This patch updates the TCP and UDP types, deprecating any function that
returns `WouldBlock` and adding a poll_ prefixed equivalent.
=> Switch TCP/UDP fns to poll_ -> Poll<...> style

src/net/tcp/incoming.rs, src/net/tcp/listener.rs, src/net/tcp/mod.rs, src/net/tcp/stream.rs
- Incoming -> src/net/tcp/incoming.rs
- TcpListener -> src/net/tcp/listener.rs
- TcpStream, ConnectFuture -> src/net/tcp/stream.rs
=> Split net::tcp code into files

tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs
Since [coco is deprecated](https://github.com/stjepang/coco), I'd like to propose to switch to [crossbeam-deque](https://github.com/crossbeam-rs/crossbeam-deque) for the underlying work-stealing deque.
The performance is slightly degraded in a benchmark I did on a Linux machine w/ 4 cores, but I think the numbers look generally fine:
```
name                                control ns/iter  variable ns/iter  diff ns/iter  diff %  speedup
connect_churn::multi_threads        212,195,085      215,857,713          3,662,628   1.73%   x 0.98
connect_churn::one_thread           11,274,537       11,393,499             118,962   1.06%   x 0.99
connect_churn::two_threads          217,590,666      214,175,311         -3,415,355  -1.57%   x 1.02
futures_channel_latency             6,247 …
```
=> Replace coco with crossbeam

.travis.yml, benches/latency.rs, benches/mio-ops.rs, benches/tcp.rs, tokio-threadpool/benches/basic.rs, tokio-threadpool/benches/depth.rs
Some of the benchhmarks were broken and/or using deprecated APIs. This
patch updates the benches and requires them all to compile without
warnings in order to pass CI.
=> Fix benches

src/reactor/poll_evented.rs, tokio-reactor/src/lib.rs, tokio-reactor/src/poll_evented.rs, tokio-reactor/src/registration.rs
Mio will be requiring `deregister` to be called explicitly in order to
guarantee that Poll releases any state associated with the I/O resource.
See carllerche/mio#753.
This patch adds an explicit `deregister` function to `Registration` and
updates `PollEvented` to call this function on drop.
`Registration::deregister` is also called on `PollEvented::into_inner`.
Closes #168
=> Explicitly deregister I/O resources on drop

CHANGELOG.md, Cargo.toml, src/lib.rs, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/src/lib.rs, tokio-io/CHANGELOG.md, tokio-io/Cargo.toml, tokio-io/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs
This also bumps tokio-io to v0.1.6 and prepares for the initial release
of tokio-executor, tokio-reactor, and tokio-threadpool.
=> Bump tokio to v0.1.2

src/executor/current_thread/mod.rs
This patch fixes a bug where `CurrentThread::turn` is expected to block
even if the executor is idle.
The `turn` API is the low level interface for callers to interact with
the `Sleep` instance used by the `CurrentThread` instance. As such, a
call to `turn` is expected to call `sleep` once if the executor did not
perform any work.
=> CurrentThread::turn should block on idle.

tokio-reactor/Cargo.toml
With 0.6.13 it doesn't compile:
no method named `as_usize` found for type `mio::Ready` in the current scope
=> tokio-reactor: bump mio to 0.6.14

tests/line-frames.rs, tokio-threadpool/benches/basic.rs
`tests/line-frames.rs` used `futures-cpupool`, but now Tokio has its own thread pool!  I just replaced the uses of `futures-cpupool` with those of `tokio-threadpool`.
related: #211
=> Remove uses of futures_cpupool

examples/udp-codec.rs
Seems we previously used the `LineCodec` for this example but changed it to `BytesCodec` and forgot to change the doc comment.
=> Update comment in udp-codec example

tokio-threadpool/src/task.rs, tokio-threadpool/tests/threadpool.rs
If a future panics from within the context of a thread pool, the pool
should not be impacted. To do this, polling the future is wrapped with a
catch_unwind. Extra care is taken to ensure that `thread::panicking()`
is set from within the future's drop handle.
Fixes #209
=> Handle futures that panic on a threadpool

src/reactor/poll_evented.rs
This PR allows tokio (4d514b7eb3a3bb6173b6f2c66dda7851e79739b4) to compile on FreeBSD again. Prior to this change the following error was encountered:
```
error[E0425]: cannot find function `hup` in this scope
--> src/reactor/poll_evented.rs:443:9
|
443 |         hup() | UnixReady::aio() | UnixReady::lio()
|         ^^^ not found in this scope
```
This is  on FreeBSD 11.1-RELEASE-p6, rustc 1.24.0.
I had a hard time working out where this `hup` function was supposed to be coming from. I came up with the following changes, which compile and the test suite passes. I fully admit I haven't studied the code enough to really know what is supposed to be happening though. Additionally I haven't tested the DragonflyBSD change but assume it's also in the same camp. Further review appreciated.
=> Fix build on FreeBSD

.travis.yml, Cargo.toml, futures2/Cargo.toml, futures2/src/lib.rs, src/executor/current_thread/mod.rs, src/executor/mod.rs, src/lib.rs, src/net/tcp/incoming.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/runtime.rs, tests/current_thread.rs, tokio-executor/Cargo.toml, tokio-executor/src/enter.rs, tokio-executor/src/global.rs, tokio-executor/src/lib.rs, tokio-io/Cargo.toml, tokio-reactor/Cargo.toml, tokio-reactor/src/atomic_task.rs, tokio-reactor/src/background.rs, tokio-reactor/src/lib.rs, tokio-reactor/src/poll_evented.rs, tokio-reactor/src/registration.rs, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-threadpool/src/task.rs, tokio-threadpool/tests/threadpool.rs
I realized that, at least for the reactor (but I think throughout), it's possible to just simultaneously support both versions of the futures crate.
Here is a proof of concept showing how this is done for the reactor. Note that the `futures2` crate here is a hack until an actual release candidate is published to crates.io. This compiles for me locally.
=> Simultaneous futures compat

examples/tinyhttp.rs
For example, the original code uses the old cache in the following case.
```
first time:
now         = Sun, 07 Sep 2014 00:17:29 GMT
next_update = Sun, 07 Sep 2014 00:17:30 GMT
cache       = Sun, 07 Sep 2014 00:17:29 GMT
```
```
next time:
now         = Sun, 07 Sep 2014 00:17:30 GMT
next_update = Sun, 07 Sep 2014 00:17:30 GMT
cache       = Sun, 07 Sep 2014 00:17:29 GMT <- wrong!
should be Sun, 07 Sep 2014 00:17:30 GMT 
```
I sent a pull request for rapidoid too.
https://github.com/rapidoid/rapidoid/pull/159
=> Fix condition for updating the current date buffer

src/executor/mod.rs, src/lib.rs, tests/echo2.rs, tests/global2.rs, tests/tcp2.rs, tokio-tcp/src/stream.rs
This PR ports the applicable top-level tests to futures 0.2 for testing the `unstable-futures` feature. It also adds a couple of missing futures 0.2 APIs.
=> Add top-level tests for futures 0.2 integration

.travis.yml, futures2/Cargo.toml, tests/echo2.rs, tests/global2.rs, tests/tcp2.rs, tokio-threadpool/tests/threadpool.rs
Fixes test breakage, and also *locks* the version to `beta` so that this kind of breakage won't happen again.
=> Update to futures 0.2.0-beta

.travis.yml, tests/global.rs, tokio-reactor/src/atomic_task.rs, tokio-reactor/src/background.rs, tokio-reactor/src/lib.rs, tokio-reactor/src/poll_evented.rs, tokio-reactor/src/registration.rs, tokio-threadpool/src/lib.rs, tokio-threadpool/src/task.rs, tokio-threadpool/tests/threadpool.rs
This PR fixes some race conditions.
* The copied implementation of `AtomicTask` is fixed (see #881).
* Spurious notifications caused by reusing a token do not happen anymore.
The spurious notifications issue because on OS X `write` cannot be called until kqueue returns a notification.
=> Fix race condition related bugs

tokio-tcp/src/listener.rs
I think the (lack of) error handling inside the stream itself might surprise people (it did surprise me). Is it OK to add a little warning that care needs to be taken? Is it OK to „advertise“ another crate in there?
=> Docs: warn about errors from TcpListener::incoming

tokio-reactor/src/poll_evented.rs
Renamed `read_readiness` -> `write_readiness` in *write* methods.
This typo actually caused an issue #238, because instead of clearing `ready to write` flag a `ready to read` flag has been cleared, effectively providing constant spurious wakeups.
Resolves #238
=> [Somehow severe] Fix a typo in tokio_reactor::PollEvented

.travis.yml
Disable unstable-futures tests as they tend to hang (most likely due to #254).
Relates to #251
=> Disable future 0.2 tests

tokio-reactor/Cargo.toml, tokio-tcp/Cargo.toml, tokio-threadpool/Cargo.toml, tokio-udp/Cargo.toml
As mentioned in #251, this fixes the flag propagation for the `unstable-futures` feature.
=> fix unstable-futures feature flag propagation

tokio-io/Cargo.toml, tokio-threadpool/Cargo.toml
I'm working on minimal version installer for cargo, turns out some dependencies are out of date:
```
cargo build -Z minimal-versions
Compiling libc v0.1.0
error: expected identifier, found `"std"`
--> /home/klausi/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.0/rust/src/liblibc/lib.rs:76:46
|
76 | #[cfg(feature = "cargo-build")] extern crate "std" as core;
|                                              ^^^^^ expected identifier
error: aborting due to previous error
error: Could not compile `libc`.
Compiling bytes v0.4.0                                                       
error[E0432]: unresolved import `bytes::buf::Chain`
--> tokio-io/src/length_delimited.rs:4:5
|
4 | use bytes::buf::Chain;
|     ^^^^^^^^^^^^^^^^^ no `Chain` in `buf`
```
Updating log to 0.4 as in the other …
=> fix(cargo): Bump dependencies so that Tokio compiles with minimal versions

src/timer.rs, tests/timer.rs, tokio-timer/src/deadline.rs, tokio-timer/src/delay.rs, tokio-timer/src/interval.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs, tokio-timer/src/timer/registration.rs, tokio-timer/tests/delay.rs, tokio-timer/tests/hammer.rs
This patch renames `Sleep` from tokio-timer and the tokio facade to
`Delay`. Given that the future does not actually put anything to sleep,
the `Delay` name feels more appropriate.
Fixes #263
=> Rename `Sleep` to `Delay`

CHANGELOG.md, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md
This also bumps:
* tokio-executor to v0.1.2
* tokio-threadpool to v0.1.2
* tokio-timer to v0.2.0
=> Bump version to v0.1.5

Cargo.toml
the id is taken from README.md
=> Fix Appveyor badge on crates.io page

.appveyor.yml
Add target `i686-pc-windows-msvc` for win builds to configure CI to catch errors for 32-bit builds. See https://github.com/tokio-rs/tokio/pull/274.
https://ci.appveyor.com/project/carllerche/tokio/build/1.0.456/job/shryotsk1bl8955p#L145
=> Build both x86 and x64 on Windows

src/lib.rs, src/timer.rs
Re-export ReadHalf/WriteHalf from the io module.
Otherwise, using the return type of AsyncRead::split requires an explicit import of tokio_io.
Re-export Error from the timer module.
DeadlineError already is exported, Error should also be.
=> re-export io::{ReadHalf/WriteHalf} timer::Error

tokio-threadpool/Cargo.toml
```rust
Running `/usr/bin/rustc --crate-name tokio_threadpool src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=e95cb707bdea30f8 -C extra-filename=-e95cb707bdea30f8 --out-dir /builddir/build/BUILD/tokio-threadpool-0.1.2/target/release/deps -L dependency=/builddir/build/BUILD/tokio-threadpool-0.1.2/target/release/deps --extern log=/builddir/build/BUILD/tokio-threadpool-0.1.2/target/release/deps/liblog-fa14a88080f9a687.rlib --extern futures=/builddir/build/BUILD/tokio-threadpool-0.1.2/target/release/deps/libfutures-610eb0fdded3070f.rlib --extern tokio_executor=/builddir/build/BUILD/tokio-threadpool-0.1.2/target/release/deps/libtokio_executor-62542ea0b6879923.rlib --extern crossbeam_deque=/builddir/build/BUILD/tokio-threadpool-0.1.2/target/r …
```
=> threadpool: bump minimal version of executor

Cargo.toml
Update tokio-timer version to 0.2.1 to fix the compile errors on 32bit systems.
See #274 for reference
=> Update tokio-timer version Cargo.toml

tokio-threadpool/src/notifier.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/sender.rs, tokio-threadpool/src/task.rs, tokio-threadpool/src/task/mod.rs, tokio-threadpool/src/task/queue.rs, tokio-threadpool/src/task/state.rs, tokio-threadpool/src/worker/entry.rs, tokio-threadpool/src/worker/mod.rs
This switches `Task` from a homegrown `Arc` implementation to using the implementation provided by `std`.
Besides this, the PR also splits up the file into sub files.
=> Refactor threadpool task types

tokio-threadpool/tests/threadpool.rs
--> tokio-threadpool/tests/threadpool.rs:257:13
|
257 |         let mut pool = Builder::new()
|             ^^^^^^^^
|
= note: #[warn(unused_mut)] on by default
=> Fix warning: variable does not need to be mutable

.travis.yml, ci/tsan, tokio-threadpool/Cargo.toml, tokio-threadpool/benches/blocking.rs, tokio-threadpool/src/blocking.rs, tokio-threadpool/src/builder.rs, tokio-threadpool/src/config.rs, tokio-threadpool/src/lib.rs, tokio-threadpool/src/notifier.rs, tokio-threadpool/src/park/default_park.rs, tokio-threadpool/src/pool/backup.rs, tokio-threadpool/src/pool/backup_stack.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/shutdown.rs, tokio-threadpool/src/task/blocking.rs, tokio-threadpool/src/task/blocking_state.rs, tokio-threadpool/src/task/mod.rs, tokio-threadpool/src/task/queue.rs, tokio-threadpool/src/task/state.rs, tokio-threadpool/src/worker/entry.rs, tokio-threadpool/src/worker/mod.rs, tokio-threadpool/src/worker/stack.rs, tokio-threadpool/src/worker/state.rs, tokio-threadpool/tests/blocking.rs, tokio-threadpool/tests/hammer.rs, tokio-threadpool/tests/threadpool.rs
This patch adds a `blocking` to `tokio-threadpool`. This function serves as a
way to annotate sections of code that will perform blocking operations. This
informs the thread pool that an additional thread needs to be spawned to
replace the current thread, which will no longer be able to process the work
queue.
By default, the Tokio thread pool expects that tasks will only run for short
periods at a time before yielding back to the thread pool. This is the basic
premise of cooperative multitasking.
However, it is common to want to perform a blocking operation while
processing an asynchronous computation. Examples of blocking operation
include:
* Performing synchronous file operations (reading and writing).
* Blocking on acquiring a mutex.
* Performing a CPU bound computation, like …
=> Threadpool blocking

src/executor/current_thread/mod.rs, tokio-io/Cargo.toml
Similar to `Timer` nested `Park` instances should be made accessible.
Also fix broken `bytes` dependency in `tokio-io` from #324 (my `Cargo.lock` had `bytes-0.4.6` and failed to build).
=>  current_thread: make underlying `Park` instance accessible 

Cargo.toml, tokio-executor/Cargo.toml, tokio-reactor/Cargo.toml, tokio-tcp/Cargo.toml, tokio-threadpool/Cargo.toml, tokio-udp/Cargo.toml
Currently, the state of the futures2 integration is pretty broken. This
patch removes the feature flag, preventing users from trying to use it.
In the future, it can be brought back when the implementation is fixed.
=> Remove `futures2` feature from Cargo.toml files

tokio-fs/src/file/mod.rs
I noticed that the link in `modules` section of https://tokio-rs.github.io/tokio/tokio_fs/ is broken.
=> Fixed broken link in tokio-fs documentation

tokio-reactor/src/lib.rs, tokio-reactor/src/poll_evented.rs, tokio-reactor/src/registration.rs
Currently, not specifying a `Handle` is different than using
`Handle::default()`. This is because `Handle::default()` will
immediately bind to the reactor for the current context vs. not
specifying a `Handle`, which binds to a reactor when it is polled.
This patch changes the `Handle::default()` behavior, bringing it inline
with actual defaults.
`Handle::current()` still immediately binds to the current reactor.
Fixes #307
=> Handle::default() should lazily bind to reactor.

tokio-timer/src/lib.rs
The naming of the function is meant to be similar to `thread::sleep` because it behaves similarly in async code.
```rust
async fn periodic() {
loop {
await!(timer::sleep(Duration::from_millis(1000)));
}
}
```
=> timer: add sleep free function

src/runtime/mod.rs
Fix `Runtime::new`s doc link to `tokio::run`.
It was broken because it was using square brackets instead of parenthesis.
=> Fix Runtime::new's doc link to tokio::run

examples/README.md, examples/manual-runtime.rs, examples/single-threaded.rs
People ask about this quite often. And I think it is easier than the multi-threaded setup, so it might be a good step to understanding how the things work together.
I plan on writing some documentation describing it for the tokio.rs website.
=> Include a ~~single-threaded~~ manually built runtime example

src/lib.rs, src/runtime/mod.rs, tests/runtime.rs
A new take on #328 in which the provided future is spawned on the runtime, and a `oneshot` channel is used to communicate the result back.
=> Implement Runtime::block_on using oneshot

tokio-fs/src/lib.rs
The `blocking_err` fn is used by tokio-fs `blocking_io` and `would_block` for many more I/O operations than just `tokio-fs::File::open`, so make the error more generic.
This is intentionally a minimal, one line fix. Alternatively could use exact same error message as BlockingError ([/tokio-threadpool/src/blocking.rs#L161](https://github.com/tokio-rs/tokio/blob/master/tokio-threadpool/src/blocking.rs#L161)):
``` rust
> "`blocking` annotation used from outside the context of a thread pool"
```
…made potentially nicer via an `impl From<BlockingError> for io::Error`?
=> Fix description of BlockingError as io::Error

src/clock.rs, src/lib.rs, src/runtime/builder.rs, src/runtime/current_thread/builder.rs, src/runtime/current_thread/mod.rs, src/runtime/current_thread/runtime.rs, tests/clock.rs, tokio-timer/src/clock/clock.rs, tokio-timer/src/clock/mod.rs, tokio-timer/src/clock/now.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/mod.rs, tokio-timer/src/timer/now.rs, tokio-timer/tests/clock.rs, tokio-timer/tests/support/mod.rs
Currently, the timer uses a `Now` trait to abstract the source of time.
This allows time to be mocked out. However, the current implementation
has a number of limitations as represented by #288 and #296.
The main issues are that `Now` requires `&mut self` which prevents a
value from being easily used in a concurrent environment. Also, when
wanting to write code that is abstract over the source of time, generics
get out of hand.
This patch provides an alternate solution. A new type, `Clock` is
provided which defaults to `Instant::now` as the source of time, but
allows configuring the actual source using a new iteration of the `Now`
trait. This time, `Now` is `Send + Sync + 'static`. Internally, `Clock`
stores the now value in an `Arc<Now>` value, which introduces dynamism
and allows …
=> Another attempt at abstracting `Instant::now`

CHANGELOG.md, Cargo.toml, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/src/lib.rs
This also bumps the versions of:
* tokio-threadpool
* tokio-timer
=> Bump version to v0.1.7

Cargo.toml
This will be added again later once types are re-exported.
=> Remove `tokio-codec` dependency from `tokio`

src/executor/mod.rs
=> Duplicated word in documentation.

tests/reactor.rs, tokio-reactor/src/atomic_task.rs, tokio-reactor/src/lib.rs
There is a deadlock that can occur when the concurrent runtime shuts
down. This patch adds a test and fix.
Fixes #401.
=> Fix a deadlock that can happen when shutting down

src/fs.rs, tokio-fs/src/file/mod.rs, tokio-fs/src/file/open.rs, tokio-fs/src/file/open_options.rs, tokio-fs/src/lib.rs
Adds an OpenOptionsExt::open_async method that wraps OpenOptions::open
just like the rest of tokio-fs.
Documentation for File has been updated to mention OpenOptions and
OpenOptionsExt::open_async similarly to the documentation for
std::fs::File, so that people know it's available.
=> Support std::fs::OpenOptions in tokio-fs

examples/chat.rs
=> Comment typo

tokio-threadpool/src/lib.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/worker/entry.rs, tokio-threadpool/src/worker/mod.rs
This patch adds some additional comments to the thread pool implementation.
=> Add some thread pool docs

.travis.yml
This PR enables backtraces when running tests and disables tsan for the thread pool.
The thread sanitizer was generating too many false positives. Once #329 lands, then it can
be re-enabled.
=> Enable backtraces in CI

tokio-fs/src/lib.rs, tokio-fs/tests/file.rs
Questions:
* is it worth exposing this as `poll_metadata`?
* could this use `impl Future` to avoid exposing the concrete return type?
=> Add tokio_fs::metadata

tokio-fs/src/file/mod.rs, tokio-fs/src/file/seek.rs, tokio-fs/tests/file.rs
Should this use `impl Future`?
cc @shepmaster, since this is related to #385 wrt. the return tuple order and the error message duplication.
=> Add tokio_fs::File::seek

tokio-current-thread/src/lib.rs, tokio-executor/src/enter.rs
Fixes #410
Test:
```
#[test]
fn test_current_thread_error() {
tokio::run(future::lazy(move || {
let to_spawn = future::ok::<(), ()>(());
::tokio::executor::current_thread::block_on_all(to_spawn).unwrap();
Ok(())
}));
}
```
Output:
```
thread 'tokio-runtime-worker-0' panicked at 'failed to start `current_thread::Runtime`: EnterError { reason: "attempted to run an executor while another executor is already running" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
=> Add a verbose error message for EnterError

tokio-threadpool/src/blocking.rs
Add a verbose error message for EnterError while trying to run tokio_threadpool::blocking on a current_thread::Runtime
Links: #432
Test:
```diff
diff --git a/tests/runtime.rs b/tests/runtime.rs
index 06ada9c..c943568 100644
--- a/tests/runtime.rs
+++ b/tests/runtime.rs
@@ -1,4 +1,5 @@
extern crate tokio;
+extern crate tokio_threadpool;
extern crate env_logger;
extern crate futures;
@@ -49,6 +50,18 @@ fn create_client_server_future() -> Box<Future<Item=(), Error=()> + Send> {
}
#[test]
+fn current_thread_blocking() {
+    let _ = env_logger::init();
+
+    let mut runtime = tokio::runtime::current_thread::Runtime::new().unwrap();
+
+    runtime.block_on(lazy(|| {
+        tokio_threadpool::blocking(|| {
+        })
+    })).unwrap();
+}
+
+#[test]
fn runtime_tokio_run() {
let _ = …
```
=> Add a verbose error message for BlockingError

tokio-threadpool/src/lib.rs, tokio-threadpool/src/worker/mod.rs
`WorkerId` is returned by a public function, but it's private to the crate. Let's make it public.
=> Make WorkerId public

tokio-threadpool/src/builder.rs, tokio-threadpool/src/park/default_park.rs, tokio-threadpool/src/worker/mod.rs
When unparking a worker thread, we do the following steps:
1. Try transitioning IDLE -> NOTIFY.
2. Lock the mutex.
3. Try transitioning SLEEP -> NOTIFY and wakeup on success.
The problem occurs if the thread transitions from SLEEP to IDLE between steps 1 and 2. In that case, step 3 will fail to transition and simply return from `unpark`.
This PR changes the step 3 so that we *always* transition to NOTIFY, no matter what the previous state was.
The park/unpark mechanism in `std::thread` works somewhat similarly. In step 3, it attempts to CAS from SLEEP to NOTIFY, but jumps back to step 1 if the previous state was IDLE. See [here](https://github.com/rust-lang/rust/blob/6e5e63a48c3be7de2faf914c2a9e194ff7cede9e/src/libstd/thread/mod.rs#L1066). I've decided to unconditionally move to state …
=> Fix a race in thread wakeup

tokio-executor/src/global.rs
This is a simple addition that will provide more accurate result for `DefaultExecutor::status()`.
Previously the method used the default implementation that simply returns `Ok(())`.
=> Implement status() for DefaultExecutor

tokio-threadpool/src/pool/mod.rs
Using a custom XorShift implementation instead of `rand::XorShiftRng` improves benchmark results quite a bit:
```
name                    before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
threadpool::spawn_many  5,310,562       4,613,372          -697,190  -13.13%   x 1.15
threadpool::yield_many  11,949,297      11,979,006           29,709    0.25%   x 1.00
```
For simplicity, I've also deleted `next_thread_id` and replaced it with a call to `rand::random::<u32>()` for generating seeds.
=> Replace XorShiftRng with a custom RNG

.travis.yml
Currently, 1.27 is the latest released Rust version.
This is in preparation to bump the crossbeam dependency to 0.4.
cc/ @seanmonstar @stjepang
=> Bump minimum supported Rust to 1.25.

tokio-uds/src/datagram.rs
I'm working on upgrading something from tokio-uds 0.1 and ran into this issue while working on adding back some other features.
This change mimics what seems to happen in UdpSocket: https://github.com/tokio-rs/tokio/blob/24d99c029eff5d5b82aff567f1ad5ede8a8c2576/tokio-udp/src/socket.rs#L227
=> return NotReady when recv_from wouldblock in uds

tokio-threadpool/Cargo.toml
Fixes `cargo doc` warnings like:
```
warning: `[1]` cannot be resolved, ignoring it...
--> /home/humbug/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/prng/isaac.rs:29:61
|
29 | /// A random number generator that uses the ISAAC algorithm[1].
|                                                             ^ cannot be resolved, ignoring
```
=> Update rand dep from 0.4 to 0.5

src/runtime/current_thread/mod.rs, tests/runtime.rs
Adds a free-standing fn in `runtime::current_thread` that starts a `current_thread::Runtime` and blocks on the provided future (and any spawned futures).
Resolves the concerns with #393.
=> Add free block_on_all in current thread Runtime

tokio-executor/src/global.rs, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/task/queue.rs, tokio-threadpool/src/worker/entry.rs
This PR adds padding to fields commonly shared among multiple thread in order to avoid false sharing.
Benchmark results:
```
name                    before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
threadpool::spawn_many  4,651,455       4,140,478          -510,977  -10.99%   x 1.12
threadpool::yield_many  11,908,059      11,805,160         -102,899   -0.86%   x 1.01
```
=> Pad fields to cacheline size to avoid false sharing

README.md, src/executor/mod.rs, src/lib.rs, src/runtime/current_thread/mod.rs, src/timer.rs, src/util/mod.rs, tokio-executor/src/lib.rs, tokio-executor/src/park.rs, tokio-fs/src/file/mod.rs, tokio-io/src/codec/mod.rs, tokio-threadpool/src/lib.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs
I started this general branch of rustdoc improvements as part of the effort to document for #339.  A description of blocking in the runtime module warrants a summary of the feature and links to greater detail. In particular, 014229f promotes your (@carllerche) recent documentation of tokio-threadpool to rustdoc so I can reference it.
=> General rustdoc improvements

tokio-timer/src/interval.rs
I occasionally forget that `at` stands for when to fire first time, rather than start counting.
Having such shortcut would be convenient for user (especially for lazy one like me)
=> Add Interval::new_interval shortcut for a better usability

ci/tsan
The `Weak` type might have been moved?
Found by #501.
=> Fix Weak tsan whitelist

tokio-uds/src/ucred.rs
It requires FreeBSD 12.0 or later.  Also, fix a spelling mistake in a
comment.
=> Ignore tokio-uds's test_socket_pair on FreeBSD.

tokio-executor/src/park.rs
The thread wakeup mechanism is basically the same in tokio-executor and tokio-threadpool, so this PR just applies bugfix #459 to tokio-executor.
=> Apply bugfix #459 to tokio-executor

tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/src/lib.rs, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/src/lib.rs, tokio-fs/CHANGELOG.md, tokio-fs/Cargo.toml, tokio-fs/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/src/lib.rs, tokio-tcp/CHANGELOG.md, tokio-tcp/Cargo.toml, tokio-tcp/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/src/lib.rs
* tokio-current-thread 0.1.1
* tokio-executor 0.1.3
* tokio-fs 0.1.3
* tokio-reactor 0.1.3
* tokio-tcp 0.1.1
* tokio-timer 0.2.5
This may want to wait until https://github.com/rust-lang-nursery/futures-rs/issues/1170 is inspected as it might relate to https://github.com/tokio-rs/tokio/pull/459.
=> Bump subcrate versions

tokio-tcp/src/stream.rs, tokio-udp/src/socket.rs
Fixes #516. This adds the methods `UdpSocket::poll_read_ready` and `UdpSocket::poll_write_ready`.
=> Udp socket readiness methods

tokio-threadpool/README.md
The current tokio-threadpool [README](https://github.com/tokio-rs/tokio/tree/703f07ca177218b60170e250416e8d4ed7e73e01/tokio-threadpool#examples) example is wrong, needs to be fixed.
=> fix tokio threadpool readme examples

src/executor/mod.rs, src/reactor/mod.rs, tokio-reactor/src/poll_evented.rs
Very minor fixes for 3 more links broken recently. Might be worth suggesting that people run `cargo doc` if they are making changes to rustdoc.
This is another dependency for resolving #437.
=> Fix more rustdoc links

tokio-threadpool/Cargo.toml, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/task/queue.rs, tokio-threadpool/src/worker/entry.rs
On current master, with #468 merged, there are both crossbeam-utils 0.4 and 0.5 in the dependencies:
``` text
crossbeam-utils v0.4.1
└── tokio-threadpool v0.1.5 
│   [...]
crossbeam-utils v0.5.0
├── crossbeam-deque v0.5.2
│   └── tokio-threadpool v0.1.5 
│       [...]
└── crossbeam-epoch v0.5.2
└── crossbeam-deque v0.5.2 (*)
```
This updates the dependency in tokio-threadpool so its back to one crossbeam-utils.
@stjepang anything to be concerned about or report with this update?
=> Update to crossbeam-utils 0.5.0, fix imports

tokio-tls/CHANGELOG.md, tokio-tls/Cargo.toml, tokio-tls/src/lib.rs
This prepares the crate for release.
=> Bump tokio-tls to v0.2.0

tokio-threadpool/Cargo.toml, tokio-threadpool/src/worker/entry.rs, tokio-threadpool/src/worker/mod.rs
Use the new `Stealer::steal_many` method in `crossbeam-deque` that steals multiple tasks from another worker at a time.
In addition to that, the number of calls to `thread::yield_now` is reduced, which was the main culprit for the recently reported slowdowns by @tobz.
Benchmarks:
```
name                    before ns/iter  after ns/iter  diff ns/iter  diff %  speedup
threadpool::spawn_many  3,568,671       3,594,856            26,185   0.73%   x 0.99
threadpool::yield_many  12,021,606      11,546,606         -475,000  -3.95%   x 1.04
```
Some wins are due to spinning, and some are due to `steal_many`.
@tobz, can you verify that this PR fixes the performance losses on your machine?
=> Steal multiple tasks from another worker at a time

Cargo.toml, tests/buffered.rs, tests/clock.rs, tests/global.rs, tests/line-frames.rs, tests/pipe-hup.rs, tests/runtime.rs, tests/timer.rs, tokio-fs/Cargo.toml, tokio-fs/tests/file.rs, tokio-tcp/Cargo.toml, tokio-tcp/tests/echo.rs, tokio-tcp/tests/stream-buffered.rs, tokio-tcp/tests/tcp.rs, tokio-threadpool/Cargo.toml, tokio-threadpool/tests/blocking.rs, tokio-threadpool/tests/threadpool.rs, tokio-timer/Cargo.toml, tokio-tls/Cargo.toml, tokio-tls/tests/bad.rs, tokio-tls/tests/google.rs, tokio-tls/tests/smoke.rs, tokio-udp/Cargo.toml, tokio-udp/tests/udp.rs, tokio-uds/Cargo.toml, tokio-uds/tests/stream.rs
`env_logger::init()` now panics if it's already initialised.
All the tests passed on Linux.
=> Routine dependencies update

tokio-codec/tests/codecs.rs
The `lines_encoder` test is a copy/paste of `bytes_encoder` and not
testing the LinesCodec encoding at all. This updates the test to do
simple validations of the LinesCodec encoding.
=> Update `lines_encoder` test to use LinesCodec

Cargo.toml, src/lib.rs, src/net.rs
This is the start of the work to expose `tokio_uds` like `tokio_tcp` and `tokio_udp`. Just like in the std lib the export is only effective for unix systems.
There is to some points to discuss:
- I choose to follow the 3-letters convention with `uds` is that ok?
- Should there be more symbol exported (e.g. `SendDgram`, `RecvDgram`)? If so how to handle name conflict?
- I couldn't find how to handle the plateform-specific documentation.
=> expose tokio_uds from the root crate

tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs, tokio-timer/src/timer/registration.rs, tokio-timer/tests/delay.rs
This patch implements `Default` for `tokio_timer::Handle`. It returns a
`Handle` instance that is not bound to a specific timer. Instead, it
will use the timer for the current execution context. This is the same
strategy used by `tokio_reactor::Handle`.
Fixes #547
=> Implement `Default` for `tokio_timer::Handle`

tokio-timer/Cargo.toml, tokio-timer/src/delay.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs, tokio-timer/src/timer/registration.rs
This tweaks the struct layout / details regarding how a `Delay` instance
is linked to a driver (timer instance). Instead of lazily allocating the
`Entry` (node shared between `Delay` and the timer), `Entry` is
allocated immediately when `Delay` is created. This allows using the
entry store data used by `Delay`.
This is in anticipation of further timer improvements that would
otherwise require the size of `Delay` to grow further. Since an
allocation is already made, the idea is to shrink the size of the
`Delay` struct.
=> timer: Reduce size of `Delay` struct

src/timer.rs, src/util/future.rs, tokio-timer/src/deadline.rs, tokio-timer/src/delay.rs, tokio-timer/src/lib.rs, tokio-timer/src/timeout.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/registration.rs, tokio-timer/tests/timeout.rs
This patch introduces `Timeout`. This new type allows setting a timeout
both using a duration and an instant. Given this overlap with
`Deadline`, `Deadline` is deprecated.
In addition to supporting future timeouts, the `Timeout` combinator is
able to provide timeout functionality to streams. It does this by
applying a duration based timeout to each item being yielded.
The main reason for introducing `Timeout` is that a deadline approach
does not work with streams. Since `Timeout` needed to be introduced
anyway, keeping `Deadline` around does not make sense.
=> Introduce `Timeout` and deprecate `Deadline`.

CHANGELOG.md, Cargo.toml, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/src/lib.rs, tokio-io/CHANGELOG.md, tokio-io/Cargo.toml, tokio-io/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/src/lib.rs, tokio-udp/CHANGELOG.md, tokio-udp/Cargo.toml, tokio-udp/src/lib.rs
This also bumps a number of sub crates:
* tokio-executor (0.1.3)
* tokio-io (0.1.8)
* tokio-reactor (0.1.4)
* tokio-threadpool (0.1.6)
* tokio-timer (0.2.6)
* tokio-udp (0.1.2)
=> Bump version to v0.1.8

src/executor/mod.rs, src/runtime/current_thread/mod.rs
Reexport it inside the tokio::runtime::current_thread, as the original
place (tokio::executor::current_thread) is hidden from documentation and
users need some way to spawn non-Send futures.
=> Reexport tokio-current-thread::spawn

src/net.rs
This is the continuation of #526. I applied the same pattern than before.
To signify deprecation I had to use type aliases since it not possible to deprecate a re-export for now (see https://github.com/rust-lang/rust/issues/30827 for details).
I also split the documentation in the different modules. Documentation wording isn't really my forte so feel free to suggest enhancements on this side.
Last thing I made the `unix` module present but empty on non-unix systems. I'm not sure this is the best idea but it allows completeness on all systems.
=> Rework tokio_tcp and tokio_udp re-exports in tokio::net

Cargo.toml
`ConnectFuture` seems not to be exported in `0.2.0` of `tokio-uds` making it incompatible. This PR bumps the version to `0.2.1`.
The futures crate has this in its CI which detected this:
```
cargo update -Zminimal-versions
cargo test --all --all-features
```
=> Fix tokio-uds version

.travis.yml, README.md
A recent release of the `parking_lot` crate broke compatibility with
Rust 1.25. To resolve this without pinning the dependency on an 0._x_
version, (or releasing a new crate version of Tokio) we are  ncrementing
the minimum supported Rust version to 1.26, in accordance with the
policy described in the `.travis.yml` file. In addition, the policy is
now documented in the README.
=> Bump minimum supported version & document support policy

CONTRIBUTING.md, Cargo.toml, tokio-timer/src/timeout.rs
We would like contributors to be able to help out with documentation tests
Add some notes in the guide on how to write tests.
=> guide: add a testing section to the contributing guide

README.md
The **License** section and **Contributing** section should be sequential.
Move the rust version section up.
=> readme: fix section ordering

src/length_delimited.rs, src/lib.rs, tests/length_delimited.rs
The current `tokio::codec::length_delimited` module provides its own
`Framed`, `FramedRead`, and `FramedWrite` types which provide the same
functionality as the types of the same name in the `codec` module.
However, it's not currently possible to use the `codec::Framed{Read, Write}`
types with the length-delimited codec; instead, the separate
types in the `length_delimited` module must be used.
This branch unifies `length_delimited` with the rest of `tokio::codec`,
by replacing the private `length_delimited::Decoder` type with a public
`length_delimited::Codec` that implements both `codec::Encoder` and
`codec::Decoder`. It may now be used with the `Framed`, `FramedRead`,
and `FramedWrite` types in `tokio_codec`. This branch also updates the
API documentation and tests to reflect these …
=> Refactor `codec::length_delimited`

tokio-threadpool/src/thread_pool.rs
`tokio_threadpool::ThreadPool::spawn` has no return value.
Add `ThreadPool::spawn_handle` which calls `futures::sync::oneshot::spawn` to return a future represents the return value.
=> Add ThreadPool::spawn_handle

tests/length_delimited.rs, tokio-io/src/length_delimited.rs, tokio-io/tests/length_delimited.rs
There is currently an issue in the deprecated
`length_delimited::FramedWrite` implementation in the `tokio-io` crate:
when the underlying writer returns `Ok(0)` (indicating that it can no
longer accept any additional bytes), the `FramedWrite` continues to loop
rather than returning a `WriteZero` error. This issue does _not_ exist
in the `FramedWrite` type added to `tokio::codec::length_delimited` in
#575, as this is just a type alias for the `codec::FramedWrite` type
with a length-delimited `Encoder`, and the issue does not exist there.
This branch adds tests for this issue to the tests for both versions of
`length_delimited`, and fixes the (deprecated)
`tokio::io::length_delimited::FramedWrite` type so that both tests pass.
Since the new `tokio::codec::length_delimited::FramedWrite` …
=> Fix non-terminating loop in `tokio_io::length_delimited::FramedWrite`

tokio-async-await/Cargo.toml
`tokio-async-await` fails to build if there is no other package that depends on tokio 0.1.8, because it uses 0.1.7 of tokio. tokio-async-await trys to export "all" items from tokio explicitly, includes `tokio::codec`. But tokio 0.1.7 doesn't export that item.
https://github.com/tokio-rs/tokio/blob/tokio-0.1.7/src/lib.rs
Simply upgrade the minimum version in `Cargo.toml`.
=> [tokio-async-await] Fix minimum version to export tokio::codec module

tokio-io/src/async_read.rs, tokio-io/src/async_write.rs
Documentation of AsyncRead and AsyncWrite do not reflect current API, referencing `Err(e) if e.kind() == ErrorKind::WouldBlock` as a way of identifying incomplete async work. The current implementation uses the `Async` enum in the `Ok` variant of `Result` rather than a special Error type to identify incomplete async work.
Updated documentation to reflect the current API.
=> Update documentation for AsyncRead and AsyncWrite

src/util/future.rs
Using 0 as a timeout value can be useful for things that should not be `Pending`.
This problem is already solved, but is missing documentation for it -- doing this here, as well as adding a test to ensure it doesn't change :)
=> Document that timeout-ed futures will be polled at least once

tokio-async-await/src/async_await/compat/backward.rs, tokio-async-await/src/async_await/compat/forward.rs, tokio-async-await/src/async_await/io/flush.rs, tokio-async-await/src/async_await/io/read.rs, tokio-async-await/src/async_await/io/read_exact.rs, tokio-async-await/src/async_await/io/write.rs, tokio-async-await/src/async_await/io/write_all.rs, tokio-async-await/src/async_await/sink/send.rs, tokio-async-await/src/async_await/stream/next.rs
rust-lang/rust#53227 moved the PinTypes on nightly to a contained package. In order to get tokio async/await to compile on nightly, the paths have to be updated.
The types were simply renamed, similar to rust-lang-nursery/futures-rs#1233 / rust-lang-nursery/futures-rs#1231
=> Use new path for importing PinMut/PinBox. Ref: rust-lang/rust#53227

tokio-async-await/Cargo.toml, tokio-async-await/src/lib.rs
Release tokio-async-await v0.1.2.
=> async-await: bump version to v0.1.2

tokio-threadpool/src/lib.rs
`thread_pool::ThreadPool::spawn_handle` is public but its return value type `thread_pool::SpawnHandle` is private.
pub use `thread_pool::SpawnHandle` at lib.rs
=> Expose thread_pool::SpawnHandle

tokio-reactor/src/sharded_rwlock.rs
@jonhoo reported a panic in the call to `LocalKey::with`, which occurs when the reactor is dropped in the middle of TLS teardown.
Change the call to `LocalKey::try_with` and handle the case when the thread-local value has already been destroyed.
=> reactor: use LocalKey::try_with in sharded RW lock

tokio-codec/src/lines_codec.rs, tokio-codec/tests/codecs.rs
Currently, there is a potential denial of service vulnerability in the
`lines` codec. Since there is no bound on the buffer that holds data
before it is split into a new line, an attacker could send an unbounded
amount of data without sending a `\n` character. 
This branch adds a `set_decode_max_line_length` function on `LinesCodec`
that configures a limit on the maximum number of bytes per line. When
the limit is reached, the buffer will be broken into a new "line"
regardless of the presence of a newline character. It was also necessary
to add some special-case logic to avoid creating an empty line when the
length limit is reached at the character immediately _before_ a `\r` or
`\n` character.
Additionally, this branch adds new tests for this function, including a
test for changing the …
=> Add max line length to `LinesCodec`

.appveyor.yml, .travis.yml
Since the CI runs all tests for all tokio crates, it is possible that a
sporadic failure in one crate can mask failures/successes of other
crates' tests.
Using the `--no-fail-fast` flag instructs cargo to run *all* tests
before failing the build. This will allow checking to see if any
relevant test cases still pass even if an unrelated test has failed.
=> ci: Run `cargo test` with the --no-fail-fast flag

tokio-async-await/Cargo.toml, tokio-async-await/src/lib.rs
tokio-async-await does not build with the current nightly compiler.
Update the futures preview deps to alpha 6 and prepare a 0.1.3 release (will require a cargo publish).
=> async-await: update deps in tokio-async-await

tokio-async-await/Cargo.toml, tokio-async-await/src/lib.rs
Fix #624 (`tokio-async-await` tests didn't compile).
1. Import the main tokio crate as `tokio_main`.
2. Remove an unnecessary `#[macro_export]`
=> Fix tokio-async-await tests compile errors

src/executor/mod.rs
The module is already deprecated. It should also be hidden from the docs.
Added `#[doc(hidden)]`.
Fixes: #643
=> Add `#[doc(hidden)]` to deprecated tokio-threadpool reexports

src/runtime/mod.rs, tests/runtime.rs, tokio-executor/src/enter.rs
The documentation for `tokio::run` states that:
> This function panics if called from the context of an executor.
However, this is not currently the case --- `tokio::run` can be called
from inside a future itself passed to `tokio::run`, which will lead to
all other currently executing futures on that executor starving. See
#504 for details.
This branch adds a `block_on` method to `tokio_executor::Enter`, which
internally functions equivalently to `Future::wait`, but requires an 
`Enter`. It then changes `tokio::run` to use `Enter::block_on` rather
than `tokio::wait`, so that a nested call to `tokio::run` will also 
attempt to `enter` and panic as expected. It also adds a test ensuring
that this works as expected.
Fixes: #504
=> Make `tokio::run` panic if called from inside `tokio::run`

tokio-timer/src/timeout.rs, tokio-timer/tests/timeout.rs
Timeout stream returns elapsed error after first element's timeout. This fixes that and makes sure that idle stream returns error periodically
=> Reset stream timeout after every elapse

src/runtime/builder.rs
Currently, the concurrent Runtime is configured by passing in a
threadpool builder. This is problematic for two reasons:
1. It exposes `tokio-threadpool` as part of the `tokio` public API,
preventing `tokio` from transparently bumping the version used
internally. 
2. All the options on the threadpool builder cannot be
maintained. There are some that the Runtime must set, overwriting
previously set values.
This branch makes the following changes:
1. Hide and deprecate `threadpool_builder`.
2. Add `core_threads` representing `pool_size` on the threadpool builder.
3. Add `blocking_threads` representing `max_blocking` on the threadpool builder.
4. Add `name_prefix`, mirroring the same fn on the threadpool builder.
5. Add `stack_size`, mirroring the same fn on the threadpool builder.
Fixes: …
=> Deprecate and replace Runtime::threadpool_builder

.appveyor.yml
Currently, the `RUST_BACKTRACE` environment variable is set to `1` on
Travis CI builds:
https://github.com/tokio-rs/tokio/blob/0ca973a7ebc5b8a29beac1ccb6c73ef26ddcbf22/.travis.yml#L49
However, it's not set on AppVeyor. This can make debugging
Windows-specific CI failures challenging for developers on other
operating systems.
This branch sets `RUST_BACKTRACE=1` on AppVeyor. Hopefully I got the
Windows CMD syntax right.
=> Set RUST_BACKTRACE=1 on AppVeyor

src/runtime/current_thread/mod.rs
It seems like there's no way to spawn !Send futures from inside a future spawned on current_thread::runtime.
Reexport TaskExecutor from tokio_current_thread.
=> Reexport TaskExecutor from tokio_current_thread

tests/timer.rs, tokio-timer/tests/deadline.rs
Currently, running `cargo test` gives a deprecation warning on both stable and nightly:
```
warning: use of deprecated item 'tokio::util::FutureExt::deadline': use `timeout` instead
--> tests/timer.rs:85:14
|
85 |             .deadline(when)
|              ^^^^^^^^
|
= note: #[warn(deprecated)] on by default
```
Just do what the error message says: use `timeout()` instead.
=> fix deprecation warning in test for FutureExt::deadline()

ci/tsan, tokio-threadpool/src/task/queue.rs
We need to drain the queue when dropping, or else those `Arc<Task>`s
will be leaked.
This seems to fix #542.
=> threadpool: impl Drop for Queue

tokio-io/Cargo.toml, tokio-io/src/split.rs
These facades were passing back `Err(io::Error::WouldBlock)` when the internal `BiLock` couldn't be acquired, which does not fit the intended behavior.
Simply change the logic to return `Ok(Async::NotReady)` instead.
Fixes #654
=> io: ensure ReadHalf/WriteHalf do not return WouldBlock directly

tokio-async-await/examples/src/hyper.rs
This patch adds reading the hyper body in the async/await example.
This was made possible by a recent change in nightly. However, an even more recent change broke everything, so you gotta make sure to find the right nightly to try this :)
I tested w/ `nightly-2018-09-17`.
=> async-await: streaming hyper body example

examples/tinydb.rs
=> tinydb: Update doc to reflect change from `RefCell` to `Mutex`

CHANGELOG.md, Cargo.toml, src/lib.rs, tokio-async-await/Cargo.toml, tokio-async-await/src/lib.rs, tokio-codec/CHANGELOG.md, tokio-codec/Cargo.toml, tokio-codec/src/lib.rs, tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/src/lib.rs, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/src/lib.rs, tokio-io/CHANGELOG.md, tokio-io/Cargo.toml, tokio-io/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/src/lib.rs, tokio-tcp/CHANGELOG.md, tokio-tcp/Cargo.toml, tokio-tcp/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/src/lib.rs
Bump version to v0.1.9
This also includes bumps to subcrates.
* tokio-async-await (0.1.4)
* tokio-codec (0.1.1)
* tokio-current-thread (0.1.2)
* tokio-executor (0.1.5)
* tokio-io (0.1.9)
* tokio-reactor (0.1.6)
* tokio-tcp (0.1.2)
* tokio-threadpool (0.1.7)
* tokio-timer (0.2.7)
=> Release crates

CHANGELOG.md, Cargo.toml, src/lib.rs, tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/src/lib.rs
Some minimal versions were not correctly updated.
Also updates:
* tokio-current-thread (v0.1.3).
=> Bump version to v0.1.10, fixing minimal versions

tokio-uds/src/stream.rs
When `read_buf` noticed a `WouldBlock`, it was wrongly clearing the **write** readiness.
=> fix UnixStream::read_buf to clear read (not write) readiness

CHANGELOG.md, Cargo.toml, src/lib.rs
This fixes the dependency on `tokio-async-await` to not be scoped to
unix platforms.
Fixes #673
=> Bump version to v0.1.11

src/runtime/builder.rs
This was overlooked when delegating the rest of the threadpool builder
methods from Runtime's builder.
=> Expose keep_alive on the Runtime builder

tokio-io/src/async_read.rs, tokio-io/src/async_write.rs
This fixes a few documentation errors for the `AsyncRead` and `AsyncWrite` traits.
=> io: fix minor documentation errors for Async{Read,Write}

Cargo.toml, tokio-reactor/Cargo.toml, tokio-reactor/benches/basic.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/sender.rs
Once an IO handle gets assigned to a reactor, it stays assigned to it forever. A handle is assigned to a reactor the first time it is polled.
Now that every worker thread in `tokio-threadpool` drives its own reactor, we'd like to distribute the IO work among reactors as equally as possible. This is only possible if each newly spawned task is polled the first time on a random worker.
Currently, when spawning a new task inside threadpool, it always goes into the local worker's queue. If a task spawns a bunch of child IO tasks, that means a disproportionate number of them will be polled the first time by the current worker thread. Work stealing doesn't help much in this case - it turns out a lot of tasks will be polled before other worker threads get a chance to steal them, thus skewing the …
=> threadpool: spawn new tasks onto a random worker

src/codec/length_delimited.rs, tests/length_delimited.rs
Fixes: #681 
Currently, a potential panic exists in `LengthDelimitedCodec::encode`.
Writing the length field to the `dst` buffer can exceed the buffer
capacity, as `BufMut::put_uint_{le,be}` doesn't reserve more capacity. 
This branch adds a check that there's sufficient remaining buffer
capacity to hold the length field, and resizes the buffer to hold the
length field if there is no capacity left.
I've also added a test that reproduces the issue. The test panics on
master, but passes after making this change.
=> codec: Fix panic in `LengthDelimitedCodec::encode`

tokio-threadpool/src/builder.rs, tokio-threadpool/src/worker/mod.rs, tokio-threadpool/tests/threadpool.rs
Now that each worker thread drives its own reactor, reactors have to be driven until the threadpool shuts down. We mustn't use the `keep_alive` setting to shut down a worker thread if it doesn't receive an event from the reactor for a certain duration of time.
Just ignore the `keep_alive` setting when parking in `Worker::sleep`.
=> threadpool: worker threads shouldn't respect keep_alive

tokio-fs/src/file/metadata.rs
Documentation says the future resolves to `(Metadata, File)` but it's actually `(File, Metadata)`.
=> fs: fix minor documentation error for MetadataFuture

tokio-uds/src/ucred.rs
`test_socket_pair()` is ignored as `getpeereid()` does not work with sockets created by `socketpair()` on NetBSD.
I did not add new test for this, hope it is OK.
tokio-uds cannot be built on NetBSD due to the following error.
```
$ cargo build
Compiling tokio-uds v0.2.2 (file:///work/rust/tokio/tokio-uds)
error[E0425]: cannot find function `get_peer_cred` in module `ucred`
--> tokio-uds/src/stream.rs:116:16
|
116 |         ucred::get_peer_cred(self)                                                                               
|                ^^^^^^^^^^^^^ not found in `ucre
```
`target_os = "netbsd"` is added as well as other BSD OS's.
=> uds: add NetBSD support

tokio-signal/CHANGELOG.md, tokio-signal/Cargo.toml
A release of `tokio-signal` never made it out after migrating to this repo, as well as with the `signal-hook` integration changes.
* Bump the `tokio-signal` version to `0.2.6` to prepare for a new release (will release on Monday, assuming this PR has landed)
* Also rewrote the `tokio-signal` `CHANGELOG.md` to better match the rest of the `tokio` project
=> signal: Bump version to 0.2.6

CHANGELOG.md, Cargo.toml, src/lib.rs, tokio-fs/CHANGELOG.md, tokio-fs/Cargo.toml, tokio-fs/src/lib.rs, tokio-io/CHANGELOG.md, tokio-io/Cargo.toml, tokio-io/src/lib.rs, tokio-signal/Cargo.toml, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-uds/CHANGELOG.md, tokio-uds/Cargo.toml, tokio-uds/src/lib.rs
Also bumps the following sub-crates:
* tokio-fs (0.1.4)
* tokio-io (0.1.10)
* tokio-signal (0.2.6)
* tokio-threadpool (0.1.8)
* tokio-uds (0.2.3)
=> Bump version to 0.1.12

tokio-reactor/src/lib.rs
In using Tokio, I have noticed that `tokio_reactor` logs a lot of a single message at the debug level that isn't particularly useful. I would personally expect this log message to be at the `trace` level, based on my experience with other crates in the Rust ecosystem.
Would there be any opposition to reducing this to a `trace`?
Sample (contiguous) output from a real application:
```
DEBUG 2018-10-31T19:16:25Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-10-31T19:16:25Z: tokio_reactor: loop process - 0 events, 0.000s
DEBUG 2018-10-31T19:16:25Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-10-31T19:16:25Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-10-31T19:16:25Z: tokio_reactor: loop process - 0 events, 0.000s
DEBUG 2018-10-31T19:16:25Z: …
```
=> Reduce log level of loop process

ci/tsan
The last few builds have been failing due to thread sanitizer errors.
See https://github.com/rust-lang/rust/pull/54806#issuecomment-436193353 for why this is happening.
This PR adds a rule to the tsan suppresions list.
=> fix tsan errors

tokio-timer/src/delay_queue.rs
Improves API ergonomics with minimal forwards-compatibility hazard.
=> Derive Clone for delay_queue::Key

tokio-reactor/Cargo.toml, tokio-threadpool/Cargo.toml, tokio-timer/Cargo.toml
tokio depends on an out of date version of crossbeam-utils, which results in multiple versions of that package being linked in binaries which use other popular libraries.
Bump the version; there's no API changes and tests still pass.
=> Bumped crossbeam-utils version

tokio-fs/tests/file.rs
Use sample_iter() instead.
`gen_ascii_chars()` has been deprecated since [rand 0.5.0](https://github.com/rust-random/rand/blob/22d6607651d8f813ad04de9e748a1d1221953f64/CHANGELOG.md#050---2018-05-21).
Use `sample_iter()` instead.
=> fs: gen_ascii_chars has been deprecated

tokio-fs/Cargo.toml, tokio-fs/tests/dir.rs
As a part of #704, this change adds a few tests around directory-related
functions.
> The tokio-fs crate has limited automated tests. This is not a good situation and should be fixed.
This change adds a few tests around tokio-fs's directory-related functions. Since this is my first commit, I'd like to focus on the small, specific area first.
=> fs: Add tests for directory-related functions (#704)

tokio-uds/src/ucred.rs
When building for `x86_64-sun-solaris` (Originally to get `reqwest` to work), I got a build error about `get_peer_cred` not being implemented.
The full error message:
```
[root@localhost hello]# cross build --target x86_64-sun-solaris
Compiling hello v0.1.0 (/project)
Compiling tokio-uds v0.2.3
error[E0425]: cannot find function `get_peer_cred` in module `ucred`
--> /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-uds-0.2.3/src/stream.rs:116:16
|
116 |         ucred::get_peer_cred(self)
|                ^^^^^^^^^^^^^ not found in `ucred`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0425`.
```
I implemented the needed function for the solaris target. It is partially based on …
=> uds: added solaris support in the `ucred` module

tokio-udp/src/recv_dgram.rs
Add ~~methods `RecvDgram::into_inner` and~~ `RecvDgram::into_parts` to allow deconstructing a `RecvDgram` future in case it can not be driven to completion.
If the `RecvDgram` future can not be driven to completion, it may become necessary to get back the `UdpSocket` and buffer, which is currently not possible. Since UDP is unreliable, it is advisable to use timeouts when receiving datagrams. After a timeout, one would probably retry sending and receiving, which requires the socket, however since it cannot be pulled out of `RecvDgram` again, `RecvDgram` is virtually impossible to use together with timeouts.
With ~~`into_inner` and~~ `into_parts` the socket and buffer can be retrieved by consuming the future. This allows to continue using those values.
=>  udp: add `into_parts` to `RecvDgram`

tokio-fs/tests/dir.rs, tokio-fs/tests/file.rs, tokio-fs/tests/link.rs, tokio-fs/tests/pool/mod.rs
Fixes #704.
Same as #724, this change adds more tests around tokio-fs
The structure follows the previous request. I added link.rs for hard_link.rs, read_link.rs and symlink_metadata.rs
=> fs: add more tests

tokio-uds/src/datagram.rs, tokio-uds/src/stream.rs
The documentation of `UnixStream` and `UnixDatagram` seemed not to be updated with API changes.
Changed comment for `pair` with hint to default handle (as done on other comments. The `pair` methods got renamed but not the doc of `peer_cred`.
=> uds: minor doc fix in UnixStream and UnixDatagram

tokio-fs/Cargo.toml, tokio-threadpool/Cargo.toml, tokio-timer/Cargo.toml
Bumps the `rand` dependency that several tokio crates have to the latest version.
=> Bumped rand dependency to 0.6

tokio-signal/CHANGELOG.md, tokio-signal/src/unix.rs
Several internal performance improvements to `tokio-signal`:
* Optimize out an extra channel allocation
* Lift the artificial `!Sync` restriction on `unix::Signal`
* Avoid extraneous wake ups whenever any `unix::Signal` channel disconnects
=> signal: miscellaneous tweaks and improvements

src/runtime/builder.rs
A quick fix to the **Examples** section of the docs for `tokio::runtime::Builder` so that the example provided no longer uses deprecated methods but instead uses the latest, up-to-date API.
=> Fix docs for tokio::runtime::Builder to no longer use deprecated methods

tokio-async-await/README.md
#661 updated async-await examples with new way of depending on async tokio with await support. This PR does the same for the example shown in the README file
=> Fix async await README example

src/runtime/builder.rs, tests/runtime.rs
This new function is called by tokio around each thread that is started.
This functionality is useful, when the user needs to setup certain
conditions for each new thread.
Hey, I require to setup each thread that is started by tokio. In my case I want to call to Java and that requires that a thread is attached to the JVM. By using the new `around_thread` function, I'm able to setup each thread easily.
Added a function to `runtime::Builder`. The function accepts a closure that will be given another closure that represents the thread. The outer closure is required to call the inner closure, otherwise the thread would not do any work.
=> Expose `after_start` and `before_stop` in `runtime::Builder`

tokio-io/tests/length_delimited.rs
This file is testing deprecated code, so it should be permitted to
access deprecated code.
Fixes #731
=> io: allow deprecated code in length_delimited test

.travis.yml
Currently, the "normal" Rust nightly entry in the build matrix is not allowed to fail, and we've seen a large uptick in recent failures due to nightly that are completely unrelated to the PRs where it fails.  
We've added an environment variable to the "normal" nightly entry which should allow it to match the existing `allow_failures` stanza.
=> Allow nightly builds to fail.

src/util/stream.rs, tokio-timer/src/lib.rs, tokio-timer/src/throttle.rs, tokio-timer/tests/throttle.rs
Second combinator implementing https://github.com/tokio-rs/tokio/pull/732#issuecomment-434719438.
I'm not really sure on the design of this one (especially since errors of the underlying stream will be delayed as well, but I assume this is a necessary evil since you'd want to use this to slow down things like `stream::repeat(_)` that produce items at unbounded speeds), so I'm eager on your feedback.
You might notice I added two extensions to `Stream`, one that enforces a given delay, and another one that enforces a rate of items (and calculates the required delay from that). Not sure if both are necessary, but I felt they fit quite nicely.
=> Implement throttle combinator

.appveyor.yml
Occasionally, `tokio-tls` tests on AppVeyor (CI platform for running on Windows) fail with a `The buffers supplied to a function was too small` error.  Searching points to a bug deep within the Windows `SChannel` framework itself (which `tokio-tls` uses due to being based on `native-tls` which prefers OS-native SSL/TLS libraries) that was only fixed in Windows 10/Windows Server 2016:
https://github.com/dotnet/corefx/issues/31611#issuecomment-410792235
https://github.com/dotnet/corefx/issues/7812#issuecomment-305848835
I believe we should able to avoid to avoid these spurious failures by running all Windows builds on Server 2016.  Unfortunately, due to the spurious nature of the bug, we can't really test this easily.. but we can ensure that we're at least running on Server 2016 which …
=> Try and force Windows Server 2016 for AppVeyor builds.

tokio-current-thread/src/lib.rs, tokio-current-thread/tests/current_thread.rs
When spawning using `Handle` while on the executor, tasks were being
double counted. This prevented the number of active tasks to reach zero,
thus preventing the executor from shutting down.
This changes `spawn` to check if being called from the executor
**before** incrementing the number of active tasks.
Fixes #760
=> current-thread: fix shutdown on idle

tokio-uds/Cargo.toml, tokio-uds/src/datagram.rs, tokio-uds/src/frame.rs, tokio-uds/src/lib.rs, tokio-uds/tests/datagram.rs
Note: this contains #452 
@carllerche in https://github.com/tokio-rs/tokio-uds/pull/37 you had said "Remove framed implementation. The style of implementing framed changed, so the old impl is removed until a new one can be written." Hopefully that's still the reason the impl doesn't exist.
`tokio-uds/src/frame.rs` was mostly copied from `tokio-udp/src/frame.rs` with a few types changed to match with what `UnixDatagram` requires.
=> implement UnixDatagramFramed

src/runtime/mod.rs, tokio-threadpool/src/builder.rs, tokio-threadpool/src/notifier.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/sender.rs, tokio-threadpool/src/shutdown.rs, tokio-threadpool/src/thread_pool.rs, tokio-threadpool/src/worker/mod.rs, tokio-threadpool/tests/blocking.rs
`inner` is a fitting name for variables of type named `Inner`, but in other cases I find them confusing - sometimes `inner` refers to a `Pool`, sometimes to a `Sender`. I renamed a bunch of variables named `inner` to be more descriptive.
This PR is the first step in an effort of splitting https://github.com/tokio-rs/tokio/pull/722#issuecomment-439552671 into multiple PRs.
=> threadpool: rename inner to something more descriptive

CHANGELOG.md, Cargo.toml, src/lib.rs, tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/src/lib.rs, tokio-signal/CHANGELOG.md, tokio-signal/Cargo.toml, tokio-signal/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/src/lib.rs, tokio-udp/CHANGELOG.md, tokio-udp/Cargo.toml, tokio-udp/src/lib.rs, tokio-uds/CHANGELOG.md, tokio-uds/Cargo.toml, tokio-uds/src/lib.rs
This also bumps the following sub crate versions:
* tokio-current-thread (0.1.4)
* tokio-reactor (0.1.7)
* tokio-signal (0.2.7)
* tokio-threadpool (0.1.9)
* tokio-timer (0.2.8)
* tokio-udp (0.1.3)
* tokio-uds (0.2.4)
=> Bump version to v0.1.13

src/net.rs
Re-export `UnixDatagram` and `UnixDatagramFramed` from `tokio::net` for consistency with `UnixListener`, `UnixStream`, `UdpSocket`, and `UdpFramed`.
Also export the recently added `UnixDatagramFramed` from `tokio::net::unix` as the rest of the `tokio_uds` crate.
=> Re-export UnixDatagram and UnixDatagramFramed from tokio::net

tokio-tls/src/lib.rs
The underlying types are Clone, so these should be as well. It's common to configure a single connector and use it throughout an application, so being able to clone it is quite convenient.
=> Make TlsConnector and TlsAcceptor Clone

tokio-reactor/Cargo.toml
Updates reactor parking_lot crate dependency to 0.7.0.  This latest version of parking_lot (and parking_lot_core, lock_api) has minimum rustc 1.24, which is less than tokio's current 1.26, so no problem there.
cc: @Amanieu
I've been waiting/watching for rand* crate duplicates and shim dependencies to go away, and this new parking_lot update removes the last old rand dep, which looked like this (via `cargo tree -d`):
``` txt
rand_core v0.2.2
└── rand v0.5.5
└── parking_lot_core v0.3.1
└── parking_lot v0.6.4
└── tokio-reactor v0.1.7 
```
=> reactor: update to parking_lot 0.7

tokio-tcp/Cargo.toml, tokio-tcp/src/listener.rs, tokio-tcp/src/stream.rs
Request by the Networking Working Group to help document tokio. 
https://github.com/rust-lang-nursery/wg-net/issues/54
Adding doc tests and usage examples to the public methods
of `TcpListener` and `TcpStream`. The documented methods are:
- tokio-tcp/src/listener.rs#bind
- tokio-tcp/src/listener.rs#accept
- tokio-tcp/src/listener.rs#poll_accept
- tokio-tcp/src/listener.rs#accept_std
- tokio-tcp/src/listener.rs#poll_accept_std
- tokio-tcp/src/listener.rs#from_std
- tokio-tcp/src/listener.rs#local_addr
- tokio-tcp/src/listener.rs#incoming
- tokio-tcp/src/listener.rs#ttl
- tokio-tcp/src/listener.rs#set_ttl
- tokio-tcp/src/stream.rs#connect
- tokio-tcp/src/stream.rs#from_std
- tokio-tcp/src/stream.rs#poll_read_ready
- tokio-tcp/src/stream.rs#poll_write_ready
- …
=> tcp: add usage examples to TcpListener and TcpStream

examples/tinyhttp.rs
It looks like there is a stray reference to tokio-core. This patch removes it.
=> examples: remove reference to tokio-core

tokio-uds/src/datagram.rs
The `UnixDatagram` send methods are broken in terms of returning `Error` in the `Wouldblock` case.
Add missing return. Furthermore align the `UnixDatagram` `send` and `recv` methods to the way it is done in TcpStream.
Fixes: #779
=> Fix uds UnixDatagram send and recv methods in WouldBlock case

tokio-fs/src/file/mod.rs
Motivation
--
Part of [this](https://github.com/rust-lang-nursery/wg-net/issues/54) networking working group issue.
Solution
--
Add doctests to public methods of the `tokio::fs::File` struct.
- file::File
- file::File::from_std
- file::File::create
- file::File::into_std
- file::File::metadata
- file::File::open
- file::File::poll_metadata
- file::File::poll_seek
- file::File::poll_set_len
- file::File::poll_set_permissions
- file::File::poll_sync_all
- file::File::poll_sync_data
- file::File::poll_try_clone
- file::File::seek
=> fs: added usage examples/doctests to File

tokio-threadpool/src/blocking.rs
As seen in issue #618, experienced engineers get confused by the current documentation of `blocking`, because it blocks the whole task, not just a single future. While cleverer people than me are working on a more general solution, let's improve the documentation slightly to help out current users.
Make the lack of a new thread explicit in the documentation, and point users of this function towards already existing mechanisms for creating new tasks if they need them. This is just a stop-gap while issue #629 is being worked on.
=> Improve the documentation of `blocking`

tokio-threadpool/src/worker/mod.rs
This is a hotfix for #726. The semaphore used for allocating permits to call `blocking()` could run into a deadlock, as explained in [this comment](https://github.com/tokio-rs/tokio/issues/726#issuecomment-443097442).
Call `consume_blocking_allocation()` when running the task rather than *before* running the task.
=> threadpool: fix semaphore deadlock

tokio-io/src/codec/decoder.rs
`decode` returns `Result<Option>`, but in the documentation it is said that it returns `None`. This PR fixes that.
=> Minor change in documentation of Decoder::decode

src/codec/length_delimited.rs, tokio-io/src/codec/mod.rs, tokio-timer/src/timeout.rs
`cargo +nightly doc` fails with a lot of errors
Fix broken links in docs
https://github.com/tokio-rs/tokio/issues/437
Please do not delete the branch until https://github.com/rust-lang/rust/issues/56693 is resolved
=> Fix warnings for cargo +nightly doc

.travis.yml
`cargo +nightly doc` Works
Do not allow failures in Travis on nightly to build docs
Closes https://github.com/tokio-rs/tokio/issues/437
=> Finally ALLOW_FAILURES=false in travis for cargo +nightly doc

tokio-threadpool/Cargo.toml, tokio-threadpool/src/builder.rs, tokio-threadpool/src/lib.rs, tokio-threadpool/src/pool/mod.rs, tokio-threadpool/src/sender.rs, tokio-threadpool/src/shutdown.rs, tokio-threadpool/src/task/mod.rs, tokio-threadpool/src/task/queue.rs, tokio-threadpool/src/worker/entry.rs, tokio-threadpool/src/worker/mod.rs
A performance regression was reported in https://github.com/tokio-rs/tokio/issues/750. The problem is that a task inserted into an inbound queue is stuck there until its worker moves it into its main task queue. While a task is in the inbound queue, no other worker can steal it. This manifests as a spike in latency between spawning and completing the task.
We take inspiration from Go's task scheduler. Go has a SPMC queue for every worker and a single global MPMC queue. In this PR we use a similar strategy. Now we have a global MPMC queue where newly spawned tasks get inserted. Every worker occasionally steals tasks from the global queue and moves them into its own queue. This way every runnable task is always ready to be taken by any worker.
Note that spawning a new task results in the …
=> threadpool: introduce a global task queue

tokio-executor/src/park.rs
It should be possible to use `Arc<dyn Unpark>` where `Unpark` is required, similar to how `Box<dyn Unpark>` is supported now.
Add `impl Unpark for Arc<Unpark>` that forwards to the wrapped value's implementation.
=> executor: impl Unpark for Arc<Unpark>

tokio-reactor/src/lib.rs
The side effects of calling `Handle::current()` from outside of a
runtime could be very surprising, since it would start up a background
reactor.
Discussed in https://github.com/hyperium/hyper/issues/1736.
=> tokio-reactor: deprecates `Handle::current()`

tokio-async-await/README.md, tokio-async-await/src/compat/backward.rs, tokio-async-await/src/lib.rs
#813 
Box::pinned has been renamed to Box::pin. Meanwhile, the pin feature no longer requires an attribute to enable.
Change `Box::pinned(...)` to `Box::pin(...)`, and remove pin feature attribute.
=> Stablize pin feature

examples/chat-combinator-current-thread.rs
Single-threaded chat combinator example. Spawns tasks locally to current_thread executor.
Provides single-threaded chat solution on top of char-combinator example. The setup differs a bit from earlier Tokio core + handle setup, therefore seen as a worthy example.
The solution is exactly the same as char-combinator example, except `Arc<Mutex<>>` is replaced by more lightweight `Rc<RefCell<>>` combination and the task is spawned locally with `TaskExecutor::current().spawn_local()`. It is good to notice that Runtime Handle cannot be used to spawn a task here.
=> Single-threaded chat combinator example.

src/runtime/current_thread/runtime.rs, tokio-timer/src/throttle.rs
#817
Error::cause is deprecated in Rust 1.33, but Error::source, which replaces it, has been stabilized in Rust 1.30 ([the minimum version of tokio is Rust 1.26](https://github.com/tokio-rs/tokio/blob/master/.travis.yml#L15))..
Allow Error::cause until the minimum supported version of tokio is Rust 1.30.
When the minimum support version of tokio reaches Rust 1.30, replace Error::cause with Error::source.
=> Allow deprecated Error::cause

tokio-threadpool/src/pool/backup.rs
The unused lint on nightly has discovered a new unused fn.
=> threadpool: remove unused fn

.travis.yml
The commented out lines are no longer relevant and will not be brought
back.
=> travis: remove commented out code.

src/runtime/mod.rs
In 85f85225, `#[doc(hidden)]` was added to the deprecated re-export of `tokio-threadpool` in the `executor` module. This broke the doc link to `ThreadPool` in the `Runtime` module. This fixes the link by pointing it to the docs.rs for `tokio-threadpool`.
=> docs: fix link to ThreadPool

.travis.yml
Tests may require newer versions of Rust. This patch changes CI to only
perform `cargo check --all` when using the minimum supported Rust
version.
=> travis: limit min rust version to cargo check

tokio-threadpool/src/pool/mod.rs
It is possible that spawning a worker thread fails due to resource exhaustion on the machine. See #809 for details. In that case, we're logging a warning and continuing execution, but we should make it a harder error instead.
If thread spawning fails, log an `error!` and panic.
Closes #809
=> threadpool: panic if a worker thread cannot be spawned

tokio-executor/src/park.rs, tokio-tcp/src/stream.rs
`TcpStream::clone()` creates a copy of a TCP stream that may be accidentally tied to a different reactor than the original. See [here](https://github.com/tokio-rs/tokio/issues/774#issuecomment-442632537) for a reproducible bug and [here](https://github.com/tokio-rs/tokio/issues/774#issuecomment-443519689) for a more elaborate explanation.
Deprecate `TcpStream::try_clone()` and nudge users towards `TcpStream::split()` instead.
Closes #774.
=> tcp: deprecate `TcpStream::try_clone()`

src/util/stream.rs, tokio-timer/src/debounce.rs, tokio-timer/src/lib.rs, tokio-timer/tests/debounce.rs
Supersedes #732, I changed the branch name for better clarity. Original description below.
----
Coming back to rust-lang-nursery/futures-rs#210, I was now able to start integrating these combinators within tokio, thanks to the new runtime.
The code is still untested, documentation needs to be improved (you are really impressive with this, as a non-native speaker I sometimes have trouble finding the right words ;)), and I'd like to add at least one more combinator (throttle / sample that will slow down the source streams but periodically return items for e. g. better user experience), but I figured its probably better to notify you guys earlier than later.
I'm very eager on feedback on the implementation (specifically the big, nested match blocks). If it can be done more clearly / simpler …
=> Implement stream debounce combinator

Cargo.toml
I updated to `tokio = "0.1.14"` in a directory that already had tokio dependencies installed, and the compiler started to error that `WorkerId::to_usize` did not exist.
=> Update tokio-threadpool minimum version for tokio crate

tokio-timer/src/timer/mod.rs
=> docs: fixed links to tokio_timer::clock::Now

tokio-timer/src/delay_queue.rs
=> docs: missing links in tokio-timer::delay_queue

tokio-timer/src/delay_queue.rs, tokio-timer/tests/queue.rs
The `DelayQueue::reset_at` function checks if the deadline of the
queue's current delay is equal to the deadline of the entry being reset
in order to determine whether to reset the delay. However, this is not
always correct: the delay is constructed based on a deadline returned by
calling `poll_at` on the queue's timer wheel, _not_ based directly on
the deadline of any entry in the queue. Since `poll_at` may return the
time the wheel next shifts down, if this is before the nearest deadline,
the queue's delay may be lower than the deadline on _any_ of its
entries.
This branch changes the test for when the deadline should be reset to
check if the value of `self.wheel.poll_at` is not equal to the current
deadline. If this is true, it resets the delay.
I've added tests based on the repro …
=> timer: Fix DelayQueue delay reset logic

src/codec/length_delimited.rs
Following on from https://github.com/tokio-rs/tokio/issues/657
Fixing doc test to use ? with Result instead of unwrap() just to (hopefully) show better practice.
@liranringel had mentioned that the examples needed updating but that doc tests were still to do. I checked all the remaining tests and this was the only one left that could do with a change, albeit a minor improvement.
Simply changing unwrap() to use ? operator and change function signature to return Result which would be more idiomatic for someone coming to copy this code for their own use.
This hopefully lets us close out https://github.com/tokio-rs/tokio/issues/657
=> docs: updating use ? & Result instead of unwrap

tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/tests/mpsc.rs
`#[derive(Clone)]` on a type `struct Foo<T>` adds an impl that requires that `T: Clone`:
```rust
impl<T: Clone> Clone for Foo<T>
```
which is unfortunate in the case of senders, because we don't want to require that the items being sent are `Clone` for the channel sender to be `Clone`. This PR adds an explicit `impl Clone` for the bounded and unbounded sender types which does not have the `T: Clone` bound.
Note that this is _also_ an issue with `#[derive(Debug)]`, but that one is harder to work around as `chan::Tx` _also_ has `#[derive(Debug)]`, as does `chan::Chan`, so we'd have to add explicit impls for all of them to make progress.
=> Explicit impl Clone for tx to avoid T: Clone

tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/chan.rs, tokio-sync/src/mpsc/list.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/tests/mpsc.rs
Following from https://github.com/tokio-rs/tokio/pull/865, this PR removes `#[derive(Debug)]` on `mpsc` sender and receiver types in favor of explicit `impl fmt::Debug` blocks that don't have a `T: fmt::Debug` bound.
=> Remove T: Debug flag on mpsc Debug impls

tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/tests/mpsc.rs
When you call `try_send` on a channel and the call fails, it often matters to the caller _why_ the call failed. For unbounded senders, we know that it must be because the receiver went away, whereas for bounded channels it may either be because the receiver went away or because there was no available capacity. This PR explicitly calls out in the docs that errors on `UnboundedSender::try_send` can only occur if the channel receiver has gone away, and adds `was_closed` and `was_full` methods to the error returned by `BoundedSender::try_send` so the caller can figure out which of the two error cases they're in.
=> Make reason for try_send errors clearer

src/lib.rs, src/util/enumerate.rs, src/util/mod.rs, src/util/stream.rs, tokio-timer/tests/enumerate.rs
Motivation is to provide an enumarete combinator, much like in Iterator. The issue for that can be found here: https://github.com/tokio-rs/tokio/issues/741
Simply provided `Stream::enumerate` on `StreamExt`
Since this is my first PR any kind of feedback will be greatly appreaciated :)
=> Add enumerate combinator to Stream

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs, tokio-sync/CHANGELOG.md, tokio-sync/Cargo.toml, tokio-sync/README.md, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/README.md, tokio-timer/src/lib.rs
Also bumps:
- tokio-sync (0.1.0)
- tokio-threadpool (0.1.11)
- tokio-timer (0.2.9)
=> Bump Tokio to v0.1.15.

tokio-sync/src/mpsc/bounded.rs, tokio-sync/tests/mpsc.rs
Disallow a bounded channel from having a 0 size.
Add an assert as per Carl's suggestion
=> bounded channel can not have 0 size

.cirrus.yml, .travis.yml
Previously it was built, but not tested, on Travis.
Issue #285
=> Test FreeBSD on cirrus-ci.com

tokio-fs/src/stdin.rs
Also see the discussion on issue #589.
By making this restriction explicit in the documentation, hopefully people will not attempt to use `tokio-fs::stdin` for tasks it is not suited for.
=> Add a warning regarding the use of `Stdin` handles

tokio-reactor/src/lib.rs
`ATOMIC_BOOL_INIT` is deprecated since 1.34 because the const fn `AtomicUsize::new` is now preferred. As `deny(warnings)` is set, tokio fails to build on latest nightly.
Changing `ATOMIC_BOOL_INIT` to `AtomicUsize::new(0)` fixes it.
`AtomicUsize::new` in a constant expression does not work before 1.24.0.
=> reactor: replace ATOMIC_USIZE_INIT with AtomicUsize::new(0)

tokio-trace/src/lib.rs, tokio-trace/tests/macros.rs
Trailing commas are optional when fields are included, and when fields
are delimited from the format string for the message.
Before these would error:
```
event!(tokio_trace::Level::DEBUG, foo = 3, bar = 3,);
event!(tokio_trace::Level::DEBUG, { foo = 2, bar = 78, }, "baz");
```
Now they do not. Tests have been extended.
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
=> tokio-trace: Extend macros to allow trailing commas

tokio-trace/src/lib.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/span.rs
Add the ability to define a target and log level for
individual spans.
`level: ...` must be included since both `$lvl` and `$name` are `expr`.
The macro tests and documentation tests have been extended.
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
=> tokio-trace: Extend `span!` rules

tokio-sync/benches/mpsc.rs, tokio-sync/benches/oneshot.rs, tokio-sync/src/mpsc/chan.rs, tokio-sync/src/task/atomic_task.rs, tokio-sync/tests/atomic_task.rs
This adds some more benchmarks to allow better measuring all parts of the channels, and then with the benchmarks guiding, improves performance of polls when the task would already notify the current.
On my machine:
Before:
```
test legacy::bounded_rx_not_ready      ... bench:         137 ns/iter(+/- 31)
test legacy::bounded_tx_poll_not_ready ... bench:         122 ns/iter(+/- 70)
test legacy::unbounded_rx_not_ready    ... bench:         136 ns/iter(+/- 14)
test legacy::unbounded_rx_not_ready_x5 ... bench:         473 ns/iter(+/- 24)
test tokio::bounded_rx_not_ready       ... bench:         121 ns/iter(+/- 3)
test tokio::bounded_tx_poll_not_ready  ... bench:         127 ns/iter(+/- 1)
test tokio::unbounded_rx_not_ready     ... bench:         149 ns/iter(+/- 2)
test …
```
=> tokio-sync: AtomicTask performance improved if task is current

tokio-current-thread/src/lib.rs, tokio-executor/src/global.rs, tokio-reactor/src/lib.rs, tokio-timer/src/clock/clock.rs, tokio-timer/src/timer/handle.rs
[rust-lang/rust#57882](https://github.com/rust-lang/rust/pull/57882) is modifying the `unused_doc_comments` lint to fire on mistakenly documented macro expansions. Note that these doc comments are not currently used, since they are eliminated when the macro is expanded. A crater run detected that this crate will break due to this change, likely because of the use of `deny(unused_doc_comments)` or `deny(warnings)`.
While this kind of breakage is allowed under Rust's stability guarantees, I am opening PRs to affected crates to reduce the impact.
This PR protects your crate from future breakage by moving the offending doc comments to the items they are intended to document, inside the macro invocations.
=> move doc comments inside macro invocations

tokio-sync/src/mpsc/chan.rs, tokio-sync/src/semaphore.rs, tokio-sync/tests/fuzz_semaphore.rs, tokio-sync/tests/mpsc.rs
This patch fixes Semaphore by adding a missing code path to the release
routine that handles the case where the waiter's node is queued in the
sempahore but has not yet been assigned the permit.
This fix is used by mpsc to handle the case when the Sender has called
`poll_ready` and is dropped before the permit is acquired.
Fixes #900
=> sync: fix mpsc/sempahore when releasing permits

tokio-reactor/src/lib.rs
I have a use case for a larger system on an embedded target that has a large body of C code running on a single thread multiplexed with libevent.  We are using a mix of Rust and C code and would like to be able to use Rust with tokio on the same thread as the single-threaded libevent reactor in order to avoid potential concurrency problems with the C code being called from a different thread of execution.
Looking at the problem, there are a few ways that the problem could be solved:
1. Implement a tokio reactor that maps into libevent rather then mio::Poll
2. Implement a libevent backend that uses tokio rather than epoll, kqeueue, select, etc.
3. (Assuming unix only) used nested epoll or kqueue file descriptors in order to allow for IO notifications on the foreign, parked reactor to …
=> tokio-reactor: impl AsRawFd for Reactor

tokio-fs/src/file/clone.rs, tokio-fs/src/file/mod.rs, tokio-fs/tests/file.rs
As explained in https://github.com/tokio-rs/tokio/issues/848, there's no existing future for cloning a file, and using something like `future::poll_fn` doesn't work since that would require moving the file.
Create a future that returns a tuple of files, or the original file and the error if there's an error during cloning.
Closes #848.
=> Add CloneFuture for File::try_clone

tokio-sync/src/oneshot.rs, tokio-sync/tests/fuzz_oneshot.rs, tokio-sync/tests/oneshot.rs
When changing tasks in oneshot, the previous `Task` would get leaked because `ManuallyDrop::drop` was never called.
=> sync: drop old tasks in oneshot

src/util/stream.rs
The `throttle` was not mentioned in the summary block but is listed as a method for the trait. This PR updates the top-level summary to include it.
=> util: Include throttle in summary of tokio::util::StreamExt

.travis.yml, tokio-async-await/README.md, tokio-async-await/src/compat/backward.rs, tokio-async-await/src/compat/forward.rs, tokio-async-await/src/io/flush.rs, tokio-async-await/src/io/read.rs, tokio-async-await/src/io/read_exact.rs, tokio-async-await/src/io/write.rs, tokio-async-await/src/io/write_all.rs, tokio-async-await/src/lib.rs, tokio-async-await/src/sink/mod.rs, tokio-async-await/src/sink/send.rs, tokio-async-await/src/stream/mod.rs, tokio-async-await/src/stream/next.rs
future/task API updated in rust-lang/rust#57992.
Rewrites the noop_waker with items from the new API and replaces LocalWaker with Waker.
This also bumps the minimum required version of tokio-async-await to 1.34.0-nightly.
Fixes: #908
=> async-await: update to new future/task API

src/sync.rs, tokio-sync/Cargo.toml, tokio-sync/src/lib.rs, tokio-sync/src/watch.rs, tokio-sync/tests/watch.rs
A single-producer, multi-consumer channel that only retains the *last* sent value. Values are broadcasted out.
This channel is useful for watching for changes to a value from multiple points in the code base (for example, changes to a configuration value).
=> tokio::sync::watch: A broadcast channel that only tracks the most recently sent value.

tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/tests/errors.rs
`RecvError` and `UnboundedRecvError` were missing the implementations.
=> sync: impl `Error` for mpsc error types

tokio-sync/CHANGELOG.md, tokio-sync/Cargo.toml, tokio-sync/README.md, tokio-sync/src/lib.rs
- `Watch`, a single value broadcast channel (#922).
- `std::error::Error` implementation for more `mpsc` types (#937).
=> Bump tokio-sync version to v0.1.3

azure-pipelines.yml, src/async_await.rs, tokio-async-await/src/lib.rs
Rust 2015 no longer supports the `async fn` syntax. However, we cannot update to Rust 2018
and remain backwards compatible.
To work around this, `async fn` is removed in favor of manually implementing futures.
Supersedes #935
=> async-await: fix build for latest nightly

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs, tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/README.md, tokio-current-thread/src/lib.rs, tokio-fs/CHANGELOG.md, tokio-fs/Cargo.toml, tokio-fs/README.md, tokio-fs/src/lib.rs, tokio-io/CHANGELOG.md, tokio-io/Cargo.toml, tokio-io/README.md, tokio-io/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/README.md, tokio-reactor/src/lib.rs, tokio-sync/Cargo.toml, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs
Also bumps:
* tokio-current-thread (0.1.5)
* tokio-fs (0.1.6)
* tokio-io (0.1.12)
* tokio-reactor (0.1.9)
* tokio-threadpool (0.1.12)
=> Bump Tokio to 0.1.16.

tokio-tcp/src/stream.rs
I began using rust nightly, and started getting errors with my code that uses `TcpStream::try_clone`. I was confused by the error message: it told me `split` was deprecated, but I think it meant to say `try_clone` is deprecated. I think this is just a simple typo fix.
Update the error message to reference `try_clone` instead of `split`. Updated my code to use `Framed::into_inner` to get at the underlying stream inside my `Framed` object.
=> Fix TcpStream::try_clone error message

tokio-trace/tests/support/subscriber.rs, tokio-trace/tokio-trace-core/src/subscriber.rs
This branch adds a 'static bound to the `Subscriber` trait, to enable
adding downcasting-based APIs to `Subscriber` later in a
backwards-compatible way.
This isn alternative to PR #950 that punts the actual implementation of
the downcasting API to a future version.
Signed-off-by: Eliza WEisman <eliza@buoyant.io>
=> trace-core: Add `'static` bound to `Subscriber`

tokio-trace/benches/subscriber.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/tests/support/field.rs, tokio-trace/tests/support/subscriber.rs, tokio-trace/tokio-trace-core/src/dispatcher.rs, tokio-trace/tokio-trace-core/src/event.rs, tokio-trace/tokio-trace-core/src/field.rs, tokio-trace/tokio-trace-core/src/span.rs, tokio-trace/tokio-trace-core/src/subscriber.rs
This branch changes the `Subscriber::record` method to take a new
arguments struct, `span::Record`. The `field::Record` trait was renamed
to `field::Visit` to prevent name conflicts.
In addition, the `ValueSet::is_empty`, `ValueSet::contains`, and
`ValueSet::record` methods were made crate-private, as they are exposed
on the `Attributes` and `Record` types. 
Signed-off-by: Eliza Weisman <elzia@buoyant.io>
=> trace: Add arguments struct to `subscriber::Record`

tokio-trace/src/lib.rs, tokio-trace/tokio-trace-core/src/subscriber.rs
This branch adds a handful of improvements to the `tokio-trace` and
`tokio-trace-core` API docs, mostly based on suggestions from #957.
Closes #957
=> trace: Minor documentation improvements

tokio-trace/tokio-trace-core/src/dispatcher.rs
PR #973 changed the `tokio_trace_core::span::Id::from_u64` function to
require that the provided `u64` be greater than zero. However, I had
forgotten that the implementation of `Subscriber` for the `NoSubscriber`
type (which is used when no default subscriber is set) always returned
`span::Id::from_u64(0)` from its `new_span` method. In combination with
the assert added in #973, this means that every time a span is hit when
no subscriber is set, `tokio-trace-core` will panic.
This branch fixes the panics by having `NoSubscriber` construct span IDs
using a different (arbitrarily chosen) non-zero constant.
=> trace-core: Fix `NoSubscriber` causing panics

tokio-sync/src/oneshot.rs, tokio-sync/src/watch.rs, tokio-sync/tests/errors.rs
Implementation of `std::error::Error` for `oneshot` and `watch`.
Refs: #937
=> sync: impl `Error` for oneshot and watch error types

Cargo.toml, src/lib.rs, src/runtime/threadpool/builder.rs
One of the biggest pain points in the current `tokio-trace` API is that
the subscriber context must be propagated manually. For example, if a
user `tokio::spawn`s a future, the spawning thread's subscriber will not
be propagated to the worker thread the spawned future actually executes
on. 
Users can currently get around this one of two ways:
- Instrument the future with a span:
```rust
use tokio_trace_futures::Instrument;
let fut = do_stuff()
.instrument(span!("do stuff"));
tokio::spawn(Box::new(fut));
```
Since entering a span sets the dispatcher to that span's dispatcher
while inside the span, this will both propagate the dispatcher
context and create a span for the future. However, if the span is
disabled, then the dispatcher will not be set, which can lead to
surprising and …
=> tokio: Enable trace subscriber propagation in the runtime

tokio-sync/src/mpsc/chan.rs, tokio-sync/src/mpsc/list.rs, tokio-sync/tests/mpsc.rs
I'm not sure the best way to add a test that `Block` is actually dropped, since it's an internal type...
=> sync: free chan Blocks when Chan is dropped

tokio-sync/benches/mpsc.rs
Since the mpsc channel allocates in blocks, there is a cost worth remembering in sending a single large message. However, sending many also shows the benefits of reclaiming the blocks!
=> sync: add mpsc benchmarks of small, medium, and large message types

tokio-trace/benches/subscriber.rs, tokio-trace/src/span.rs, tokio-trace/tests/span.rs
This branch makes the following changes to `tokio-trace`'s `Span` type:
* **Remove manual close API from spans**
In practice, there wasn't really a use-case for this, and it 
complicates the implementation a bit. We can always add it back later.
* **Remove generic lifetime from `Span`**
Again, there wasn't actually a use-case for spans with metadata that
doesn't live for the static lifetime, and it made using `Span`s in 
other types somewhat inconvenient. It's also possible to implement an
alternative API for non-static spans on top of the `tokio-trace-core`
primitives.
=> trace:  Span API polish

tokio-current-thread/CHANGELOG.md, tokio-current-thread/Cargo.toml, tokio-current-thread/README.md, tokio-current-thread/src/lib.rs, tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/README.md, tokio-executor/src/lib.rs, tokio-signal/CHANGELOG.md, tokio-signal/Cargo.toml, tokio-signal/README.md, tokio-signal/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/lib.rs
Also bumps:
- tokio-signal (0.2.8)
- tokio-current-thread (0.1.6)
- tokio-executor (0.1.7)
- tokio-threadpool (0.1.13)
=> Bump Tokio version to v0.1.18

tokio-trace/tokio-trace-core/src/dispatcher.rs, tokio-trace/tokio-trace-core/src/subscriber.rs
In order to implement "out of band" `Subscriber` APIs in third-party
subscriber implementations (see [this comment]) users may want to 
downcast the current `Dispatch` to a concrete subscriber type.
For example, in a library for integrating `tokio-trace` with a fancy new
(hypothetical) distributed tracing technology "ElizaTracing", which uses
256-bit span IDs, we might expect to see a function like this:
```rust
pub fn correlate(tt: tokio_trace::span::Id, et: elizatracing::SpanId) {
tokio_trace::dispatcher::with(|c| {
if let Some(s) = c.downcast_ref::<elizatracing::Subscriber>() {
s.do_elizatracing_correlation_magic(tt, et);
}
}); 
}
```
This allows users to correlate `tokio-trace` IDs with IDs in the
distributed tracing system without having to pass a special handle to
the subscriber …
=> trace-core: Add  overrideable downcasting to `Subscriber`s

Cargo.toml, azure-pipelines.yml, tokio-trace/Cargo.toml, tokio-trace/src/level_filters.rs, tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/test_static_max_level_features/Cargo.toml, tokio-trace/test_static_max_level_features/main.rs, tokio-trace/test_static_max_level_features/tests/test.rs
`tokio-trace` should have static verbosity level filtering, like the `log` crate. The static max verbosity level should be controlled at compile time with a set of features. It should be possible to set a separate max level for release and debug mode builds.
https://github.com/tokio-rs/tokio/issues/959
We can do this fairly similarly to how the `log` crate does it: `tokio-trace` should export a constant whose value is set based on the static max level feature flags. Then, we can add an if statement to the `span!` and `event!` macros, like
=> Trace static level filtering

tokio/LICENSE
Since tokio was moved into its own directory, crates.io doesn't have LICENSE file.
https://github.com/tokio-rs/tokio/issues/1004
=> Add license to tokio

tokio-buf/src/util/from.rs, tokio-buf/src/util/mod.rs, tokio-buf/tests/buf_stream_ext.rs
This makes `my_buf_stream.collect()` work with `Bytes` as a target.
=> buf: implement FromBufStream for Bytes

tokio-trace/tokio-trace-core/src/field.rs, tokio-trace/tokio-trace-core/src/metadata.rs
This branch improves the `fmt::Debug` implementation for `Metadata`,
and adds `fmt::Display` implementations for `FieldSet` and `ValueSet`.
When formatting a `Metadata`, only present fields are formatted --- if
optional fields, such as the file, line number, and module path are
`None`, they will be excluded. In addition, `Metadata` now formats its
`FieldSet` using `FieldSet`'s `fmt::Display` implementation, which is a
bit less noisy. Finally, the `Debug` output for `Metadata` now includes
the callsite that the metadata originates from.
The intention behind these changes is to make the output from failed
tests somewhat easier to interpret, as well as to make the `Debug` 
output from user-defined types containing a `Span` or `Metadata`
less noisy.
Signed-off-by: Eliza Weisman …
=> trace-core: Add slightly more useful debug impls

tokio-trace/src/span.rs
This branch modifies the `tokio_trace::Span` API functions that take
span IDs (the `Span::child_of` constructor, and the `Span::follows_from`
method) so that more types bearing a span ID can be passed as an
argument. Span IDs may now be passed directly without requiring them to
be passed as `Some(id)`. This should make the API slightly more
ergonomic.
Also, it changes the `Span::field` method to take an `AsField` rather
than a `Borrow<str>`.
=> trace: Make Span API functions taking IDs a little more flexible

tokio-signal/CHANGELOG.md, tokio-signal/Cargo.toml, tokio-signal/examples/ctrl-c.rs, tokio-signal/src/windows.rs
As noted in #999 the Windows implementation of `tokio-signal` panics when used with a lazily initialized reactor due to earlier assumptions that the initialization was done on-task.
* Use `Handle::default` over `Handle::current` for consistent semantics across APIs
* Make all `windows::Event` constructors lazily invoke `global_init` so
they can be safely constructed off-task
* Don't assume the reactor is alive and event registration will be done
when calling `global_init`
* Add regression tests on Windows
=> signal: refactor Windows registrations to be lazy

tokio-io/src/_tokio_codec/framed_read.rs, tokio-io/src/_tokio_codec/framed_write.rs, tokio-io/src/codec/decoder.rs, tokio-io/src/framed_read.rs, tokio-io/src/framed_write.rs, tokio-io/src/length_delimited.rs, tokio-signal/src/unix.rs, tokio-signal/src/windows.rs, tokio-tcp/src/stream.rs, tokio-tls/tests/smoke.rs, tokio-udp/src/frame.rs, tokio-uds/src/frame.rs, tokio-uds/src/stream.rs, tokio/examples/proxy.rs, tokio/src/codec/length_delimited.rs
https://doc.rust-lang.org/std/macro.try.html
> The ? operator was added to replace try! and should be used instead. Furthermore, try is a reserved word in Rust 2018, so if you must use it, you will need to use the raw-identifier syntax: r#try.
Replace try! macro with ? operator.
=> Replace try! macro with ? operator

tokio-trace/benches/no_subscriber.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/src/span.rs, tokio-trace/test-log-support/tests/log_no_trace.rs, tokio-trace/test_static_max_level_features/tests/test.rs, tokio-trace/tests/event.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/span.rs, tokio-trace/tests/subscriber.rs
Was determined that having the span! macro default to the TRACE level is probably not ideal (see discussion on #952).
closes #1013 
remove default trace level and make log lvl mandatory on span! macro, and add the respective 
`trace_span!`, `debug_span!`, `info_span!`, `warn_span!` and `error_span!` macros that behave as span! macro, but with defined log levels
I think this is it, also removed some captures that were repeated, and some testcases that also seemed repeated after adding the mandatory log level, but please review it, if more tests or examples are needed happy to provide (tried to find a way to get the generated macros log level, but didn't find one, if there is a way i can add tests to assert that the generated macro has the matching log level ).
thanks
=> - remove default trace level and make log lvl mandatory on span! macro

tokio-trace/benches/subscriber.rs
This branch fixes the `tokio-trace` Subscriber benchmarks panicking due
to constructing spans with ID 0. They will now use an arbitrary constant
instead.
=> trace: Fix subscriber benchmarks panicking

tokio-trace/src/macros.rs, tokio-trace/tests/event.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/span.rs
In order to support conventions that add namespacing to `tokio-trace`
field names, it's necessary to accept at least one type of separator
character. Currently, the `tokio-trace` macros only accept valid Rust
identifiers, so there is no clear separator character for namespaced
conventions. See also #1018.
This branch changes the single `ident` fragment matcher for field names
to match *one or more* `ident` fragments separated by `.` characters.
The resulting key is still exposed to `tokio-trace-core` as a string
constant created by stringifying the dotted expression. However, if
`tokio-trace-core` were later to adopt a first class notion of
hierarchical field keys, we would be able to track that change in
`tokio-trace` as an implementation detail.
Closes #1018.
Closes #1022. …
=> trace: Allow field names to be separated by `.`s

tokio-trace/benches/subscriber.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/src/span.rs, tokio-trace/tests/span.rs, tokio-trace/tests/subscriber.rs
The `Span::enter` function previously required an `&mut` reference to
enter a span. This is a relic of an earlier design where span closure
logic was determined by dropping an inner span component, and is no
longer strictly necessary.
Requiring `&mut self` to enter a span leads to awkward patterns in cases
when a user wishes to enter a span and then call methods on the span
(such as recording field values). For example, we cannot say
```rust
let mut span = span!("foo", bar);
span.enter(|| {
span.record("bar" &false);
});
```
since the span is mutably borrowed by `enter`. Instead, we must clone
the span, like so:
```rust
let mut span = span!("foo", bar);
span.clone().enter(|| {
span.record("bar" &false);
});
```
Having to clone the span is somewhat less ergonomic, and it has
performance …
=> trace: Change `Span::enter` and `record` to take `&self`

tokio-trace/examples/counters.rs
tokio-trace counter example was panicking due to returning 0 as the first Span Id
start ID's with 1 instead
=> trace: fix counters example, Span IDs must be greater than zero.

tokio/examples/README.md, tokio/examples/blocking.rs
Documentation states that futures should return as fast and possible and should not perform heavy computation, but the solution for heavy computation is not listed. There is no example of blocking environment yet.
New example showing the use of blocking environment is added.
=> add example of blocking environment

tokio-trace/src/macros.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/support/event.rs, tokio-trace/tests/support/field.rs, tokio-trace/tests/support/span.rs, tokio-trace/tokio-trace-core/src/field.rs, tokio-trace/tokio-trace-core/src/lib.rs, tokio-trace/tokio-trace-core/src/metadata.rs, tokio-trace/tokio-trace-core/tests/macros.rs
To ease the implementation of `Subscriber::register_callsite`, a field
should be added to `Metadata` to indicate if this callsite is an event or
a span.
A new struct, `Kind`, is added to the `metadata` module in
`tokio-trace-core`, and a `Kind` field is added to the `Metadata`
struct. Macros which construct `metadata` now require a `Kind`.
`Kind` is represented as a struct with a private inner enum to allow new
`Kind`s to be added without breaking changes. However, the _addition_ of
the kind field _is_ a breaking change. While this could be done in a
backward-compatible way, it would permit the construction of metadata
with unknown kinds, and since the next `tokio-trace-core` release will
be a breaking change, I opted to make the breaking change instead.
New API tests for the `callsite!` …
=> trace-core: Introduce callsite classification in metadata

azure-pipelines.yml, tokio-async-await/README.md, tokio-async-await/src/compat/backward.rs
`futures_api` updated in https://github.com/rust-lang/rust/pull/59733.
cc https://github.com/tokio-rs/tokio/issues/1042
=> async-await: update to new futures_api

tokio-async-await/examples/Cargo.toml, tokio-async-await/src/io/mod.rs, tokio-async-await/src/stream/mod.rs
Some examples in async-await fail to compile (even if updated to the new API by https://github.com/tokio-rs/tokio/pull/1049).
* Fix crate path in `Cargo.toml` of examples
* Add `edition2018` to examples in the documentation to make it compiled on Rust 2018
* Fix an example in the documentation
=> async-await: fix examples

tokio-trace/tests/subscriber.rs, tokio-trace/tokio-trace-core/src/dispatcher.rs
This branch changes `dispatcher::get_default` to unset the thread's
current dispatcher while the reference to it is held by the closure.
This prevents infinite loops if the subscriber calls code paths which
emit events or construct spans. 
Note that this also means that nested calls to `get_default` inside of a
`get_default` closure will recieve a `None` dispatcher rather than the
"actual" dispatcher. However, it was necessary to unset the default in
`get_default` rather than in dispatch methods such as `Dispatch::enter`,
as when those functions are called, the current state has already been
borrowed.
This introduces a little more overhead into span creation and events.
Before:
```
Running target/release/deps/no_subscriber-09f0b39a00181a97
running 5 tests
test bench_1_atomic_load …
```
=> trace-core: Dispatchers unset themselves

tokio-trace/tokio-trace-core/CHANGELOG.md, tokio-trace/tokio-trace-core/Cargo.toml, tokio-trace/tokio-trace-core/README.md, tokio-trace/tokio-trace-core/src/lib.rs
This branch prepares `tokio-trace-core` to release version 0.2. It
updates the changelog, including a note on breaking changes; and bumps
the docs.rs version linked in Cargo.toml & in the README.
=> trace-core: prepare for 0.2 release

tokio-threadpool/Cargo.toml, tokio-threadpool/src/builder.rs, tokio-threadpool/src/config.rs, tokio-threadpool/src/task/mod.rs, tokio-threadpool/tests/threadpool.rs
tokio-threadpool currently catches panics that happen inside the thread pool. This can cause silent failures. 
This patch adds a feature `no_catch_panic` to tokio-threadpool to `resume_unwind()` after the catch happens. This does not actually forward the panics back to `tokio::run()`, that will be left for later work.
Ref https://github.com/tokio-rs/tokio/issues/495
https://github.com/tokio-rs/tokio/issues/209
https://github.com/denoland/deno/issues/1311
https://github.com/denoland/deno/issues/2097
=> threadpool: add panic_handler

tokio-trace/CHANGELOG.md, tokio-trace/Cargo.toml, tokio-trace/README.md, tokio-trace/src/field.rs, tokio-trace/src/level_filters.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
This branch prepares `tokio-trace` for an 0.1 release on crates.io.
It also makes some last minute documentation improvements 
(including fixing broken links in RustDoc).
=> trace: prepare tokio-trace for release

README.md, azure-pipelines.yml, tokio-async-await/Cargo.toml, tokio-async-await/src/lib.rs, tokio-buf/CHANGELOG.md, tokio-buf/Cargo.toml, tokio-buf/README.md, tokio-buf/src/lib.rs, tokio-sync/CHANGELOG.md, tokio-sync/Cargo.toml, tokio-sync/README.md, tokio-sync/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs, tokio/Cargo.toml, tokio/README.md, tokio/src/lib.rs
This also bumps:
- tokio-async-await (0.1.7)
- tokio-buf (0.1.1)
- tokio-sync (0.1.5)
- tokio-threadpool (0.1.14)
=> Bump `tokio` to 0.1.19.

tokio/Cargo.toml
It is needed for lock functionality which tokio now uses.
=> tokio: Bump min version of tokio-sync

tokio/src/runtime/threadpool/builder.rs
Exposes the `panic_handler` landed in #1052 to runtime users.
=> Forward panic_handler to tokio::runtime::Builder

tokio-tcp/src/listener.rs
This does not remove all cases of using a fixed port in doc tests, but
removing some should reduce the likelihood of spurious failures.
=> tcp: fix some tests that spuriously fail

README.md
The URL for the licence badge points to the wrong place.
Point the URL to the correct place.
Remove the -MIT from the end of the current file name.
=> Fix an error in the mit-url in the README.md

tokio-signal/Cargo.toml, tokio-signal/src/unix.rs
The signal-hook library got split into lower-level and higher-level
parts. The tokio-signal uses only API from the lower-level one, so it
can depend on it directly.
The only effect of this change is smaller amount of compiled (and
unused) code during compilation. There's no change in the code actually used.
=> signal: Smaller dependency

tokio-timer/src/timeout.rs, tokio-timer/src/timer/handle.rs, tokio-timer/tests/hammer.rs
Deadline was deprecated a while ago and replaced with Timeout, but the
methods on Handle got missed.
Fixes #1071
=> timer: Replace Handle::deadline with Handle::timeout

tokio-test/src/lib.rs, tokio-test/src/macros.rs
Callers may not always have `futures` available at the root of the
crate. Re-exporting dependencies makes them available to the macro at a
deterministic location.
=> test: re-export macro dependencies

README.md, azure-pipelines.yml, ci/azure-test-nightly.yml, tokio-macros/Cargo.toml, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/README.md, tokio-timer/src/lib.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
The `async-await-preview` feature is removed as 0.1 will no longer track
Rust nightly.
This also bumps:
- tokio-timer (0.2.11).
=> Release tokio v0.1.20, tokio-timer v0.2.21, and remove async-await-preview feature.

tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/tests/event.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/span.rs
In `tokio-trace`, field values may be recorded as either a subset of
Rust primitive types or as `fmt::Display` and `fmt::Debug`
implementations. Currently, `tokio-trace` provides the `field::display`
and `field::debug` functions which wrap a type with a type that
implements `Value` using the wrapped type's `fmt::Display` or
`fmt::Debug` implementation. However, importing and using these
functions adds unnecessary boilerplate. 
In #1081, @jonhoo suggested adding shorthand syntax to the macros,
similar to that used by the `slog` crate, as a solution for the
wordiness of the current API.
This branch adds `?` and `%` sigils to field values in the span and
event macros, which expand to the `field::debug` and `field::display`
wrappers, respectively. The shorthand sigils may be used in any …
=> trace: Add shorthand for `field::display` and `field::debug`

ci/azure-cross-compile.yml, tokio-tcp/Cargo.toml, tokio-tcp/tests/tcp.rs
This updates tests to track a fix applied in Mio. Previously, Mio
incorrectly fired HUP events. This was due to Mio mapping `RDHUP` to
HUP. The test is updated to correctly generate a HUP event.
Additionally, HUP events will be removed from all platforms except for
Linux. This is caused by the inability to reliably map kqueue events to
the epoll HUP behavior.
=> Fix TCP poll_hup test

tokio-trace/README.md, tokio-trace/benches/subscriber.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/src/span.rs, tokio-trace/test-log-support/tests/log_no_trace.rs, tokio-trace/tests/filter_caching_is_lexically_scoped.rs, tokio-trace/tests/filters_are_not_reevaluated_for_the_same_span.rs, tokio-trace/tests/filters_are_reevaluated_for_different_call_sites.rs, tokio-trace/tests/span.rs
Currently, the primary way to use a span is to use `.enter` and pass a
closure to be executed under the span. While that is convenient in many
settings, it also comes with two decently inconvenient drawbacks:
- It breaks control flow statements like `return`, `?`, `break`, and
`continue`
- It require re-indenting a potentially large chunk of code if you wish
it to appear under a span
This branch adds a new `enter_scoped` function to `tokio_trace::Span`
that allows entering a span until a scope guard is dropped, as in:
```rust
let guard = span.enter_scoped();
// code here is within the span
drop(guard);
// code here is no longer within the span
```
Internally, the `enter` function (which was already implemented using
a package-private scope guard) was reimplemented on top of …
=> trace: Change `Span::enter` to return a guard, add `Span::in_scope`

tokio-executor/CHANGELOG.md, tokio-executor/src/enter.rs
These APIs have never been used.
=> executor: remove unnecessary APIs from `Enter`.

tokio-sync/src/lock.rs
I am using `Lock` so that I can get `Sync` for a sendable type. It appears that
the `Sync` impl is missing for `Lock` though, so the underlying `UnsafeCell`'s
`!Sync` is causing an issue.
I have added a `Sync` impl for `Lock`. The only bound required is `T: Send`,
which is the same for the `Send` impl for `Lock`.
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
=> sync: Add Sync impl for Lock

Cargo.toml, tokio-tcp/Cargo.toml, tokio-tcp/src/incoming.rs, tokio-tcp/src/lib.rs, tokio-tcp/src/listener.rs, tokio-tcp/src/stream.rs
- Removes several deprecated functions.
- Hides `ConnectFuture` as just an `impl Future`.
- Exposes `TcpListener::incoming()` optionally via the cargo feature `incoming`.
And doesn't fix any of the tests, because I'm tired...
=> Refactor tokio-tcp to use std::future

Cargo.toml, tokio-timer/Cargo.toml, tokio-timer/src/delay.rs, tokio-timer/src/delay_queue.rs, tokio-timer/src/interval.rs, tokio-timer/src/lib.rs, tokio-timer/src/throttle.rs, tokio-timer/src/timeout.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/registration.rs
- Removes `Error` from `Delay` and `Interval` (see #1133 for rationale).
- Changes `Timeout` to return `Result<T::Output, Elapsed>`.
- Puts all the types that need `Stream` behind cargo features.
- Has some ugly unsafe to do pin projection 😭 
Doesn't include tests or docs, contributions welcome!
=> Refactor tokio-timer to use std::future

tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/test-log-support/tests/log_no_trace.rs, tokio-trace/tests/macros.rs, tokio-trace/tests/span.rs
A common pattern in `tokio-trace` is to use the value of a local
variable as a field on a span or event. Currently, this requires code
like:
```rust
info!(foo = foo);
```
which is not particularly ergonomic given how commonly this occurs.
Struct initializers support a shorthand syntax for fields where the name
of the field is the same as a local variable, and `tokio-trace` should
as well.
This branch adds support for syntax like
```rust
let foo = ...;
info!(foo);
```
and 
```rust
let foo = Foo {
bar: ...,
...
};
info!(foo.bar)
```
to the `tokio-trace` span and event macros. This syntax also works with
the `Debug` and `Display` field shorthand.
The span macros previously used a field name with no value to indicate 
an uninitialized field. A new issue, #1138, has been opened for finding a …
=> trace: Add shorthand syntax for local fields

tokio/src/runtime/threadpool/mod.rs
Since spawn is implemented at struct ThreadPool, there is no need to call into its Sender.
=> Use ThreadPool's impl of spawn

tokio-tls/examples/download-rust-lang.rs, tokio-tls/tests/bad.rs, tokio-tls/tests/google.rs, tokio-tls/tests/smoke.rs, tokio/src/runtime/threadpool/mod.rs, tokio/tests/clock.rs, tokio/tests/global.rs, tokio/tests/runtime.rs
The runtime is inherently multi-threaded, so it's going to have to deal
with synchronization when submitting new tasks anyway. This allows a
runtime to be shared by multiple threads more easily when e.g. building
a blocking facade over a tokio-based API.
This simply changes `&mut self` to `&self` for these methods. All of the inner glue worked with shared references already.
=> Make threadpool::Runtime methods take &self

tokio/Cargo.toml
The dependency was not removed from `Cargo.toml` when the deprecated
code was removed. `tokio` no longer depends directly on `mio`. Instead,
sub crates depend on `mio` and `tokio` re-exports relevant types from
these sub crates.
=> Remove `mio` dependency from `tokio`

tokio-trace/src/span.rs, tokio-trace/tokio-trace-core/src/span.rs
While we're making breaking changes to `tokio-trace`, it would be good
to get rid of the `AsId` trait. The goal of span functions that are
generic over `Span`/`Id` can be achieved without the unnecessary
complexity of defining a new trait. This would also make the API added
to `tokio_trace_core::Event` in #1109 more consistent with the
`tokio-trace::Span` API.
This branch removes `AsId` from `tokio-trace` and replaces its uses with
`impl Into<Option<&'a Id>>`. Implementations of `Into<Option<&'a Id>>`
have been added for `tokio_trace::Span`.
This is _technically_ a breaking API change, as it changes function
signatures. However, the existing macro syntax still works as-is, and
the tests which pass `&Id`, `&Span`, and `&Option<Id>` to the span
macros all still compile after this change. …
=> trace: Remove the `AsId` trait

tokio-timer/src/delay_queue.rs
```rust
#[derive(Default)] // To derive Default
struct Cache {
entries: HashMap<CacheKey, (Value, delay_queue::Key)>,
expirations: DelayQueue<CacheKey>,
}
```
Implement `Default` for `tokio_timer::DelayQueue`.
=> Implement Default for tokio_timer::DelayQueue

tokio/src/runtime/threadpool/mod.rs
#1153 
When the provided future in `block_on` or `block_on_all` panics, the sending part of the oneshot channel get's dropped and the `unreachable` macro is triggered.
Replace the `unreachable` macro with a regular `panic` with an error message.
=> fix #1153: unreachable in block_on_all

tokio-trace/src/macros.rs, tokio-trace/tests/span.rs, tokio-trace/tests/support/subscriber.rs
Currently, when the `trace_span!`, `debug_span!`, `info_span!`,
`warn_span!`, and `error_span!` macros are invoked with an explicit
parent, a name, and zero or more fields (no target), the macros don't
pass along the explicitly provided parent when expanding to the `span!`
macro. This is likely due to an oversight on my part.
This branch fixes these macros by adding the parent into the `span!`
macro expansion. I've also added a test to catch regressions
Shoutout to @jonhoo for catching this one!
=> trace: fix level_span macros not propagating parents

tokio-trace/Cargo.toml, tokio-trace/README.md, tokio-trace/benches/subscriber.rs, tokio-trace/src/lib.rs, tokio-trace/src/subscriber.rs, tokio-trace/tokio-trace-core/src/dispatcher.rs
I was just trying to use tokio-trace for a greenfield project, but I was frustrated to discover that I couldn't really use it easily.
I was using the [`runtime`](https://docs.rs/runtime/0.3.0-alpha.4/runtime/) crate, which transparently spawns a thread pool executor for futures. In that thread pool, there's no way to set a tokio-trace subscriber for the duration of each thread, since you don't control the thread initialization. You *might* be able to wrap every future you spawn with a subscriber call, but that's a lot of work.
I was also confused because the documentation said that setting a subscriber in the main thread would use that subscriber for the rest of the program. That isn't the case, though -- the subscriber will be used only on the main thread, and not on worker threads, etc. …
=> trace: Add program-wide default dispatcher

tokio-trace/src/macros.rs
PR #1103 accidentally changed the log level for the `debug!` and `debug_span!` macros to use the `INFO` level instead of the `DEBUG` level. This PR corrects this regression back to the intended behavior.
I changed the instances of `INFO` back to `DEBUG` in the places where it was accidentally changed in #1103.
=> trace: fix debug and debug_span macro regression from #1103

tokio-executor/src/enter.rs, tokio-executor/src/lib.rs, tokio-threadpool/Cargo.toml, tokio-threadpool/src/blocking.rs, tokio-threadpool/src/lib.rs, tokio-threadpool/tests/blocking.rs
Inside a `threadpool::blocking` call, a user may wish to block on a different executor.
=> Add executor::exit, allowing other executors inside threadpool::blocking

tokio-trace/Cargo.toml, tokio-trace/benches/no_subscriber.rs, tokio-trace/benches/subscriber.rs
Extracted from #1152
This makes it possible to run benchmarks on stable + gives more statistical reliability.
=> trace: Switch benchmarks to criterion

tokio-trace/src/lib.rs, tokio-trace/src/macros.rs, tokio-trace/src/span.rs, tokio-trace/tests/span.rs, tokio-trace/tokio-trace-core/src/metadata.rs
Currently, some parts of the `tokio-trace` documentation is unclear, and
some concepts are not described adequately. In addition, the
organization of the docs can be improved and made less redundant. For
example, the lib-level documentation has examples of the shorthand
syntax for fields that is repeated in the span macro's documentation.
This could be changed so that the lib and module-level documentation
provides an _overview_ and the individual items go into greater detail.
This branch reorganizes the documentation and adds better explanations
of some concepts that were previously unclear. In particular, I've
added:
- examples of setting metadata and overriding span parents in the 
macros
- an explanation of what targets are,
- added an explanation of the span follows-from …
=> trace: Improve documentation

tokio-signal/Cargo.toml, tokio-signal/src/lib.rs, tokio-signal/src/registry.rs, tokio-signal/src/unix.rs, tokio-signal/src/windows.rs
Today the Unix and Windows implementations have similar yet differing
implementations of hooking into OS events and propagating them to any
listening futures. This makes it difficult to test and debug reports as
half the code only runs on one particular platform. Not to mention that
bugs potentially need to be fixed twice in two different places.
Rather than re-implement the same behavior two
different ways, we should factor out any commonality into a shared
module and keep the Unix/Windows modules focused solely on OS
integrations.
This change introduces the `registry` module which handles creating and
initializing a global map of signals/events and their registered
listeners. Each OS specific module is expected to implement the OS hooks
which delegate to invoking the registry module's …
=> signal: factor out event delivery into its own module to share between Unix and Windows

tokio-trace/Cargo.toml, tokio-trace/src/macros.rs, tokio-trace/tests/macros.rs, tokio-trace/tokio-trace-core/src/event.rs, tokio-trace/tokio-trace-core/src/lib.rs, tokio-trace/tokio-trace-core/src/parent.rs, tokio-trace/tokio-trace-core/src/span.rs
Closes #1100
As mentioned in #1100  it makes sense to be able to set the parents of events explicitly.
For that to happen the Parent type is extracted from span.rs  and a `parent` field is added to Event. Additionally the appropriate macros arms are added with corresponding tests as described in #1100
=> trace: Allow setting event parents explicitly

Cargo.toml, azure-pipelines.yml, ci/azure-test-stable.yml, tokio-macros/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs
Includes minor fixes and a very basic example.
Fixes #1183 
Refs: #1185
=> macros: re-export `main` macro from `tokio`

tokio-tcp/src/listener.rs, tokio-tcp/src/stream.rs, tokio-udp/src/socket.rs, tokio-uds/src/listener.rs, tokio-uds/src/stream.rs
It is sometime desired to convert `tokio::net::TcpStream` and other i/o stuff into their std counterparts. As #856 mentions, there is currently no easy way to perform that. I'd actually say there is no way at all, since one needs to somehow "deregister" the socket from the executor before converting it to an std socket via e.g. `AsRawFd`/`FromRawFd`/`mem::forget` magic.
I understand that mio doesn't provide implementations for `AsRawSocket` and such windows-specific traits, hence it's impossible to have a cross-platform `into_std` method *yet*, but it is possible to enable at least unix users to manually convert the respective i/o primitives into their std counterparts by providing an `into_inner` method for them that returns the `mio`'s wrappers, which, in turn, already do implement …
=> Add `into_mio` methods for various i/o wrappers

azure-pipelines.yml, ci/azure-rustfmt.yml, tokio-io/src/async_write.rs, tokio-io/tests/async_read.rs, tokio-sync/src/mpsc/bounded.rs, tokio-tcp/src/listener.rs, tokio-tcp/src/stream.rs, tokio-test/tests/macros.rs, tokio-timer/src/delay.rs, tokio-timer/src/lib.rs, tokio-timer/src/throttle.rs, tokio-timer/src/timeout.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/handle.rs, tokio/src/io/async_read_ext.rs, tokio/src/io/async_write_ext.rs, tokio/src/io/mod.rs, tokio/src/io/read_exact.rs, tokio/src/net.rs, tokio/tests/io_copy.rs, tokio/tests/io_read.rs, tokio/tests/io_read_exact.rs
The rustfmt CI task was disabled. This brings it back.
=> chore: format code and enable rustfmt CI task

Cargo.toml, azure-pipelines.yml, tokio-codec/Cargo.toml, tokio-codec/src/bytes_codec.rs, tokio-codec/src/decoder.rs, tokio-codec/src/encoder.rs, tokio-codec/src/framed.rs, tokio-codec/src/framed_read.rs, tokio-codec/src/framed_write.rs, tokio-codec/src/lib.rs, tokio-codec/src/lines_codec.rs, tokio-codec/src/macros.rs, tokio-codec/tests/codecs.rs, tokio-codec/tests/framed.rs, tokio-codec/tests/framed_read.rs, tokio-codec/tests/framed_write.rs
Strategy was to
* copy the old codec code that was temporarily being stashed in `tokio-io`
* modify all the type signatures to use Pin, as literal a translation as possible
* fix up the tests likewise
This is intended just to get things compiling and passing tests. Beyond that there is surely lots of refactoring that can be done to make things more idiomatic. The docs are unchanged.
Closes #1189
=> Update tokio-codec to use std-future

azure-pipelines.yml, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs
Enables `tokio-macros` and re-exports it to root crate.
Also adds extra macro `runtime` that allows to choose type of runtime.
Also disabled `main` macros in tests because it wouldn't compile otherwise
As async is not stable yet, all examples will have enabled feature, should be removed once async fn is stable
Latest nightly compiler has troubles running tests with `main` as identifier of attribute due to compilation error. Rustc issue https://github.com/rust-lang/rust/issues/62127
=> Allow to configure type of runtime in main macro

tokio-macros/src/lib.rs, tokio-sync/Cargo.toml, tokio-sync/src/lib.rs, tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/src/oneshot.rs, tokio-sync/tests/fuzz_mpsc.rs, tokio-sync/tests/fuzz_oneshot.rs, tokio-sync/tests/mpsc.rs, tokio-sync/tests/oneshot.rs
Adds:
- oneshot::Sender::close
- mpsc::Receiver::recv
- mpsc::Sender::send
Also renames `poll_next` to `poll_recv`.
Refs: #1210
=> sync: add async APIs to oneshot and mpsc

tokio-sync/src/oneshot.rs, tokio-sync/tests/fuzz_oneshot.rs, tokio-sync/tests/oneshot.rs
The action of `Sender::poll_close` is to check if the receiver has been closed, not to try to close the sender itself. So change to `poll_closed`.
=> sync: change oneshot poll_close to poll_closed

tokio-tcp/Cargo.toml, tokio-tcp/src/lib.rs, tokio-tcp/src/split.rs, tokio-tcp/src/stream.rs, tokio-tcp/tests/split.rs, tokio/src/net.rs
A specialized split is implemented for `TcpStream`(close #174, related: #1108).
Compared to the generic `AsyncRead::split`, the specialized split gives handles (halves) that are faster and smaller, because they do not use locks.
The write half handle properly implements the shutdown operation, by shutting down the underlying stream in the "write" direction (close #852).
The handles also implement `AsRef<TcpStream>`, allowing access to methods of the `TcpStream` that takes `&self`: to get local and peer addresses, to get/set various socket options, to shutdown the socket, etc. (Close #852 even if write half shutdown does not call stream shutdown.)
Other IO resources should have similar specialized split support as well.
=> TcpSocket specialized split

tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/prelude.rs, tokio/src/runtime/current_thread/builder.rs, tokio/src/runtime/current_thread/runtime.rs, tokio/src/timer.rs, tokio/src/util/future.rs, tokio/src/util/mod.rs, tokio/src/util/stream.rs, tokio/tests/timer.rs
This also brings back the timer tests in the tokio crate.
=> tokio: re-enable timer in runtimes

azure-pipelines.yml, ci/azure-test-stable.yml
For each cross product of a crate and it's features, the CI is running all tests for all crates.
Scope each test invocation to a specific crate's directory, so only its tests run.
=> ci: scope each tests/examples invocation to a specific crate

tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/README.md, tokio-executor/src/lib.rs, tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/lib.rs
This bumps the minor version for `threadpool` and `executor` for #1155, and `tokio` itself for #1223.
=> Bump 0.1 versions for latest changes

.cirrus.yml
The FreeBSD CI generates docs for all dependent crates.
Pass in `--no-deps` to `cargo doc` to speed up the run
=> ci: don't generate docs for deps on FreeBSD

CONTRIBUTING.md, bin/publish, bin/release
Currently, the process for releasing a new version of a Tokio crate is
somewhat complex, and is not well-documented. To make it easier for
contributors to release minor versions more frequently, there should be
documentation describing this process.
This branch adds a section to `CONTRIBUTING.md` describing how to
release a new version of a Tokio crate. The steps are based on those
described by @carllerche in an offline conversation.
I've also added a quick shell script to actually publish new crate 
versions. This should make it harder to make mistakes when 
publishing.
=> add release documentation to CONTRIBUTING.md

tokio-buf/src/never.rs, tokio-buf/src/util/from.rs, tokio-buf/src/util/iter.rs, tokio-current-thread/src/lib.rs, tokio-executor/src/enter.rs, tokio-executor/src/error.rs, tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/src/oneshot.rs, tokio-sync/src/semaphore.rs, tokio-sync/src/watch.rs, tokio-threadpool/src/blocking.rs, tokio-threadpool/src/park/default_park.rs, tokio-timer/src/deadline.rs, tokio-timer/src/error.rs, tokio/src/codec/length_delimited.rs, tokio/src/runtime/current_thread/runtime.rs
Removes:
- deprecated implementations of std::error::Error::{cause, description}, since they are deprecated and we do not have to keep BC in a new 0.2 release.
- calls to those deprecated methods, since they are problematic.
References #1206
=> Remove usage of deprecated std::error::Error methods (#1206)

tokio-signal/examples/ctrl-c.rs
Fixes: #1248
Quoting #1248:
> The `ctrl-c` example in `tokio-signal` mentions a bug about using `cargo run`. However, this bug has been solved: https://github.com/rust-lang/rustup.rs/pull/1242.
Just remove the corresponding line.
=> signal: update instructions in Ctrl-C example

tokio-timer/src/delay.rs, tokio-timer/src/timer/handle.rs, tokio-timer/tests/hammer.rs
The old implementation didn't work for Timeout<Stream>, since the method
took a deadline rather than a timeout.
`timeout` now takes a `Duration` rather than `Instant`, and plumbs things through so that the inner Delay will be reset appropriately. This is a breaking change, so it shouldn't be backported to 1.x
=> Fix Handle::timeout

tokio-current-thread/Cargo.toml, tokio-current-thread/src/lib.rs, tokio-current-thread/tests/current_thread.rs
The `dyn future::Executor` for the threadpool is `Sync` ([`tokio_threadpool::Sender`](https://docs.rs/tokio-threadpool/0.1.14/tokio_threadpool/struct.Sender.html)), but the executor for the current-thread is not ([`tokio_current_thread::Handle`](https://docs.rs/tokio/0.1.21/tokio/runtime/current_thread/struct.Handle.html)).
To use the two executors interchangeably it would better if they would both be `Sync`.
There are two non-Sync items in the `Handle` struct:
- sender: current `mpsc::Sender` could be replaced with `crossbeam_channel::Sender`
- shut_down: `Cell<bool>` could be replaced with `Arc<atomic::AtomicBool>`
Is this a good idea?
=> Make `tokio_current_thread::Handle` Sync

tokio-udp/src/lib.rs, tokio-udp/src/recv.rs, tokio-udp/src/recv_from.rs, tokio-udp/src/send.rs, tokio-udp/src/send_to.rs, tokio-udp/src/socket.rs, tokio-udp/src/split.rs, tokio-udp/tests/udp.rs, tokio/src/net.rs
The UDP counterpart of #1217.
A specialized split is implemented for `UdpSocket`, making it possible to receive and send on the socket concurrently, even from two different tasks.
There are no `AsyncRead` or `AsyncWrite` like traits for `UdpSocket`. So the halves have receive or send methods same with the socket. The methods return the same future types with their `UdpSocket` equivalents.
=> UdpSocket split support

tokio-signal/examples/ctrl-c.rs, tokio-signal/examples/sighup-example.rs, tokio-signal/src/ctrl_c.rs, tokio-signal/src/lib.rs, tokio-signal/src/registry.rs, tokio-signal/src/unix.rs, tokio-signal/src/windows.rs, tokio-signal/tests/drop_multi_loop.rs, tokio-signal/tests/drop_then_get_a_signal.rs, tokio-signal/tests/dropping_does_not_deregister_other_instances.rs, tokio-signal/tests/multi_loop.rs, tokio-signal/tests/notify_both.rs, tokio-signal/tests/simple.rs
Polishing the API to remove the inherent `ctrl_c` and `ctrl_c_with_handle` functions as per #1243 
* Add a new `CtrlC` struct which will represent a stream of SIGINT
signals on Unix or the CTRL_C event on Windows
* `CtrlC` implements `Stream<Output = ()>` rather than `IoSteam` as
previously
=> signal: Replace `ctrl_c` with a `CtrlC` struct

tokio/src/io/async_write_ext.rs, tokio/src/io/mod.rs, tokio/src/io/write_all.rs, tokio/tests/io_write_all.rs
An async equivalent to io::Write::write_all
=> tokio: add AsyncWriteExt::write_all

tokio/src/io/async_read_ext.rs, tokio/src/io/mod.rs, tokio/src/io/read_to_end.rs, tokio/tests/io_read_to_end.rs
An async equivalent to io::Read::read_to_end
=> tokio: add AsyncReadExt::read_to_end

tokio-signal/src/unix.rs, tokio-signal/src/windows.rs, tokio-tls/tests/smoke.rs
`std::sync::ONCE_INIT` will be deprecated in Rust 1.38 (https://github.com/rust-lang/rust/pull/61757).
The alternative (`Once::new()`) seems to have stabilized at the same time as `AtomicUsize::new()` (https://github.com/rust-lang/rust/issues/61746#issuecomment-501077898).
=> Remove usage of deprecated ONCE_INIT

tokio/Cargo.toml
The tokio-uds crate has been previously updated to std::future. This
commit enables the re-export in the tokio facade crate.
=> tokio: re-export tokio-uds

tokio/Cargo.toml, tokio/src/net.rs
An earlier PR (#1282) re-exported the version from crates.io and not git
master.
=> tokio: re-export correct tokio-uds version

tokio-reactor/Cargo.toml
To keep compact dependency graphs by using the latest versions of things
Use the latest version of parking_lot :-)
=> reactor: bump parking_lot dependency

tokio-fs/Cargo.toml, tokio-threadpool/Cargo.toml, tokio-timer/Cargo.toml
`rand` has removed some dependencies in version 0.7: https://github.com/rust-random/rand/blob/master/CHANGELOG.md#070---2019-06-28
=> chore: update rand dependency to 0.7

tokio/Cargo.toml, tokio/examples/udp-codec.rs
I've updated the udp-codec example to use the new async-await feature set and to use await wherever possible.
I wasn't able to use `Framed` with `BytesCodec` due to changes to `UdpSocket` not having an `AsyncWrite` or `AsyncRead` implementation. I have reproduced the original ping-ponging behavior of the original example using the `send` and `recv` functions just using `UdpSocket` by itself.
Maybe this example should be renamed?
=> update udp-codec example

tokio-io/src/async_buf_read.rs, tokio-io/src/lib.rs, tokio/Cargo.toml, tokio/src/io/async_buf_read_ext.rs, tokio/src/io/lines.rs, tokio/src/io/mod.rs, tokio/src/io/read_line.rs, tokio/src/io/read_until.rs, tokio/tests/io_lines.rs, tokio/tests/io_read_line.rs, tokio/tests/io_read_until.rs
This adds the following items:
* Add AsyncBufRead - An async equivalent to io::BufRead
* Add AsyncBufReadExt::read_until - An async equivalent to io::BufRead::read_until
* Add AsyncBufReadExt::read_line - An async equivalent to io::BufRead::read_line
* Add AsyncBufReadExt::lines - An async equivalent to io::BufRead::lines
The implementations are almost identical to the ones I added in futures-rs (https://github.com/rust-lang-nursery/futures-rs/pull/1552, https://github.com/rust-lang-nursery/futures-rs/pull/1556, https://github.com/rust-lang-nursery/futures-rs/pull/1585).
cc #1203
r? @carllerche
=> tokio,io: add AsyncBufRead trait and AsyncBufReadExt::{read_until, read_line, lines}

tokio-fs/Cargo.toml, tokio-fs/tests/dir.rs, tokio-fs/tests/link.rs
In particular because it pulls in old rand duplicates. Replace use with `tempfile::tempdir()` which has been available since _tempfile_ 3.0.0.
The deprecated _tempdir_ crate dev  dependency was previously removed (for tokio-fs and others) in 31f71ded (#533) but was reintroduced here in 9153067d (#724).
=> fs: replace deprecated tempdir crate use in tests

Cargo.toml, tokio-tls/Cargo.toml, tokio-tls/examples/download-rust-lang.rs, tokio-tls/src/lib.rs, tokio-tls/tests/bad.rs, tokio-tls/tests/google.rs, tokio-tls/tests/smoke.rs
updates tokio-tls to std::futures.
first time porting 0.1 futures to 0.3, not sure if I followed the the right approach, but only way I managed to implement `Asyncread` `AsyncWrite` and `Future` was to bound `S` as Unpin. 
update:
fixing tests and adding `cargo test -p tokio-tls` to the ci
closes #1194
=> tokio-tls: update to std-future

tokio-tcp/src/split.rs, tokio-tcp/src/stream.rs
See here for a longer motivation:
https://github.com/rust-lang-nursery/futures-rs/issues/1727
The TLDR is that I think a "split_mut" method on types implementing traits like `AsyncRead` could open up the possibility of the AsyncRead/AsyncWrite trait methods returning "normal-ish" futures, and eventually allow the methods on these traits to be implemented using async functions
Note: this is more useful than it might appear, because the Pin API allows the ownership of a TcpStream, *and* non-static borrows of that TcpStream to be bundled into a future without any lifetime bounds of its own.
=> Implement "split_mut" for TcpStream

tokio-sync/src/oneshot.rs, tokio-uds/src/ucred.rs
[`MaybeUninit`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html) is stable in rust 1.36 and `std::mem::uninitialized` will be [deprecated](https://doc.rust-lang.org/nightly/std/mem/fn.uninitialized.html) in 1.38. Tokio v0.2 is targeting at least rust 1.36 and probably 1.38 or newer, so usage of `uninitialized` should be replaced with `MaybeUninit`.
Changes:
* In `tokio-uds/src/ucred.rs`: this is a straightforward change following the [out pointer pattern](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#out-pointers).
* In `tokio-sync/src/oneshot.rs`: `ManuallyDrop` is replaced with `MaybeUninit`. This is recommended in the doc of [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html). I also made some small refactoring to abstract the pointer to …
=> Replace (some) std::mem::uninitialized usage with MaybeUninit

tokio-timer/src/timeout.rs
That converts `Elpased` into `ErrorKind::TimedOut`.
=> timer: impl Into<std::io::Error> for Elpased

tokio-timer/src/timeout.rs
Just recognized that implementing `Into` doesn't imply `From`, and I actually can implement `From` here.
The `?` operator seems only look for `From`, not `Into`.
=> timer: change Into to From trait for Elpased

tokio/src/io/async_read_ext.rs, tokio/src/io/mod.rs, tokio/src/io/read_to_string.rs, tokio/tests/io_read_to_string.rs
An async equivalent to io::Read::read_to_string
cc #1203
Refs: https://github.com/rust-lang-nursery/futures-rs/pull/1721
=> tokio: add AsyncReadExt::read_to_string

tokio-threadpool/Cargo.toml, tokio-threadpool/src/pool/mod.rs
Minimizing dependencies to reduce build size and time for typical tokio applications.
In _parking_lot_ 0.9.0 (upgraded here recently in #1298) the _rand_ dependency was replaced entirely with its own private Xorshift PRNG, used for its fairness mechanism.
The _tokio-threadpool_ also has its own Xorshift PRNG for "fair" work stealing, introduced in #466 as a performance improvement. However the _rand_ dependency was kept, its use limited to producing the initial seeds for the thread local Xorshift PRNGs.  This is currently the only existing non-dev dependency on _rand_, direct or transitive, in tokio.  As mentioned, _parking_lot_ no longer depends on _rand_, and tempfile (_rand_ dep) is also only a dev dependency.
This PR changes the seed generation to piggyback on libstd's mechanism for …
=> Remove last non-dev dependency on rand crate

tokio/src/runtime/threadpool/background.rs, tokio/src/runtime/threadpool/builder.rs, tokio/src/runtime/threadpool/mod.rs, tokio/tests/runtime_threaded.rs
Removes the `Send` requirement to futures passed to `Runtime::block_on`.
Previously, `block_on` was implemented by sending the future to a
runtime thread. In order to do this, the future must be Send.
The reason why the future is sent to the pool is because we cannot
guarantee, while off the pool, that a reactor / timer thread is running.
This is due to a limitation in the current version of tokio-threadpool.
There is a plan to fix this (#1177), but the proper fix is non trivial.
In order to unblock APIs that require this, this patch updates the
runtime to spawn an always running thread containing a reactor and
timer. All calls to `block_on` will use that reactor and timer.
Refs #1073, #1305.
=> tokio: remove `Send + 'static` requirement from `block_on`

tokio-threadpool/src/worker/mod.rs, tokio-tls/tests/smoke.rs
Related: https://github.com/rust-lang/rust/pull/34456, #1317
=> chore: use ptr::{null, null_mut} instead of 0 as *{const, mut}

tokio-codec/src/framed.rs, tokio-codec/src/framed_read.rs, tokio-codec/src/framed_write.rs, tokio-current-thread/src/lib.rs, tokio-current-thread/src/scheduler.rs, tokio-fs/src/create_dir.rs, tokio-fs/src/create_dir_all.rs, tokio-fs/src/hard_link.rs, tokio-fs/src/os/unix.rs, tokio-fs/src/os/windows/symlink_dir.rs, tokio-fs/src/os/windows/symlink_file.rs, tokio-fs/src/read_dir.rs, tokio-fs/src/read_link.rs, tokio-fs/src/remove_dir.rs, tokio-fs/src/remove_file.rs, tokio-fs/src/rename.rs, tokio-fs/src/set_permissions.rs, tokio-reactor/src/lib.rs, tokio-signal/src/unix.rs, tokio-sync/src/watch.rs, tokio-tcp/src/stream.rs, tokio-threadpool/src/task/blocking.rs, tokio-timer/src/throttle.rs, tokio-udp/src/socket.rs, tokio/benches/tcp.rs, tokio/examples/echo-udp.rs
rustfmt provides a convenient way to do this: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_field_init_shorthand
=> chore: remove redundant field names in struct literals

tokio-signal/CHANGELOG.md, tokio-signal/src/ctrl_c.rs, tokio-signal/src/lib.rs, tokio-signal/src/windows.rs
* Add a new `windows::CtrlBreak` struct which wil represent a stream of
CTRL_BREAK_EVENT signals on Windows systems
* The `windows::Event` type is no longer publicly accessible and is
replaced by using `CtrlC` or `windows::CtrlBreak`.
* This is a **breaking change**
* Refs #1243
=> signal: replace `windows::Event` with `windows::CtrlBreak`

tokio-signal/CHANGELOG.md, tokio-signal/examples/multiple.rs, tokio-signal/examples/sighup-example.rs, tokio-signal/src/unix.rs, tokio-signal/tests/twice.rs
* This simplifies the API surface by returning () instead of the signal
number that was used during registration. This also more closely mirrors
the cross-platform `CtrlC` event stream API
* This is a **breaking change**
* Refs #1243
=> signal: change unix::Signal to return () instead of signum

tokio-process/CHANGELOG.md, tokio-process/Cargo.toml, tokio-process/LICENSE, tokio-process/README.md, tokio-process/src/bin/cat.rs, tokio-process/src/bin/exit.rs, tokio-process/src/kill.rs, tokio-process/src/lib.rs, tokio-process/src/unix/mod.rs, tokio-process/src/unix/orphan.rs, tokio-process/src/unix/reap.rs, tokio-process/src/windows.rs, tokio-process/tests/issue_42.rs, tokio-process/tests/smoke.rs, tokio-process/tests/stdio.rs, tokio-process/tests/support/mod.rs
This pulls in the `tokio-process` code and history from https://github.com/alexcrichton/tokio-process
The following steps from #1319 have been performed:
- flatten past `tokio-process` history (preserve authors but remove merge commits, prefix commit names with `process:`)
- rewrite any references to issues/PRs in the old repo
- update LICENSE to match the Tokio project
- update Cargo.toml references
- update CHANGELOG
- update README
- run cargo fmt
- update to 2018 edition
- remove unneeded files (.travis.yml/appveyor.yml etc)
- move crate to its own directory
Note CI has not yet been enabled, I didn't want to mix pulling in old code with new changes. That can be followed up in a separate PR.
@carllerche after reviewing this, could you please perform a fast forward (current commit is …
=> process: pull in tokio-process code and history

tokio-macros/src/lib.rs
Just in case adds compile error if user try to supply `test` attribute, as it would lead to confusing output in `cargo test`
I made such mistake myself actually, so thought it would be nice to throw error to notify user
=> macros: Detect double test attribute

tokio-fs/src/file/mod.rs, tokio-tcp/src/listener.rs, tokio-tcp/src/stream.rs, tokio-udp/src/socket.rs, tokio-uds/src/datagram.rs, tokio-uds/src/listener.rs, tokio-uds/src/stream.rs
This adds the following TryFrom/From implementations:
* `TryFrom<net::TcpListener> for TcpListener`
* `TryFrom<net::TcpStream> for TcpStream`
* `TryFrom<net::UdpSocket> for UdpSocket`
* `TryFrom<net::UnixDatagram> for UnixDatagram`
* `TryFrom<net::UnixListener> for UnixListener`
* `TryFrom<net::UnixStream> for UnixStream`
* `TryFrom<UnixDatagram> for mio_uds::UnixDatagram`
* `TryFrom<File> for io::File`
* `From<io::File> for File`
Closes https://github.com/tokio-rs/tokio/issues/707
Related: https://github.com/tokio-rs/tokio/pull/1158
=> Add some TryFrom/From implementations

tokio/Cargo.toml
That makes `UnixListener::incoming` available  through `tokio`.
=> tokio: include async-trait feature for uds

tokio/examples/chat.rs
I've updated the chat example to use the new async-await feature set and to use await wherever possible. 
Some changes still need to be made:
=> Update chat example

tokio-process/src/unix/mod.rs, tokio-process/src/unix/reap.rs, tokio-process/tests/stdio.rs, tokio-signal/CHANGELOG.md, tokio-signal/examples/ctrl-c.rs, tokio-signal/examples/multiple.rs, tokio-signal/examples/sighup-example.rs, tokio-signal/src/ctrl_c.rs, tokio-signal/src/lib.rs, tokio-signal/src/unix.rs, tokio-signal/src/windows.rs, tokio-signal/tests/drop_multi_loop.rs, tokio-signal/tests/drop_then_get_a_signal.rs, tokio-signal/tests/dropping_does_not_deregister_other_instances.rs, tokio-signal/tests/multi_loop.rs, tokio-signal/tests/notify_both.rs, tokio-signal/tests/simple.rs, tokio-signal/tests/twice.rs
The constructors for various `tokio-signal` types return a lazy future which initializes the respective type before yielding it, which makes it awkward to work with the results directly.
* Eagerly initialize inner types, as the restrictions which originally required lazy initialization are no longer present.
* Using `#[tokio::main]`/`#[tokio::test]` will also avoid any issues with initializing futures off-task, so this change should be safe
Refs #1243
=> signal: Change constructors to return a result instead of lazy future

tokio/src/io/async_write_ext.rs, tokio/src/io/flush.rs, tokio/src/io/mod.rs, tokio/src/io/write.rs
This should add the last io helper for https://github.com/tokio-rs/tokio/issues/1203
=> io: Add `AsyncWriteExt::flush`

tokio-io/Cargo.toml, tokio-io/src/io/async_buf_read_ext.rs, tokio-io/src/io/async_read_ext.rs, tokio-io/src/io/async_write_ext.rs, tokio-io/src/io/copy.rs, tokio-io/src/io/flush.rs, tokio-io/src/io/lines.rs, tokio-io/src/io/mod.rs, tokio-io/src/io/read.rs, tokio-io/src/io/read_exact.rs, tokio-io/src/io/read_line.rs, tokio-io/src/io/read_to_end.rs, tokio-io/src/io/read_to_string.rs, tokio-io/src/io/read_until.rs, tokio-io/src/io/write.rs, tokio-io/src/io/write_all.rs, tokio-io/src/lib.rs, tokio-io/tests/copy.rs, tokio-io/tests/lines.rs, tokio-io/tests/read.rs, tokio-io/tests/read_exact.rs, tokio-io/tests/read_line.rs, tokio-io/tests/read_to_end.rs, tokio-io/tests/read_to_string.rs, tokio-io/tests/read_until.rs, tokio-io/tests/write.rs, tokio-io/tests/write_all.rs, tokio/Cargo.toml, tokio/src/io.rs
=> io: Move io helpers back into `tokio-io`

azure-pipelines.yml, tokio-io/Cargo.toml, tokio/Cargo.toml
Sub-crates should require opting into features. This will make it harder to include more than needed.
The facade crate (`tokio`) will pull in all the features by default.
=> io: remove `util` from default features

tokio-buf/src/lib.rs, tokio-codec/src/encoder.rs, tokio-codec/src/lib.rs, tokio-current-thread/src/lib.rs, tokio-executor/Cargo.toml, tokio-executor/src/executor.rs, tokio-executor/src/global.rs, tokio-executor/src/lib.rs, tokio-executor/src/park.rs, tokio-executor/src/typed.rs, tokio-fs/src/file/mod.rs
Updates API documentation for
- tokio-buf
- tokio-codec
- tokio-current-thread
- tokio-executor
=> docs: update API documentation for some crates

tokio-codec/src/framed.rs, tokio-codec/src/framed_write.rs
* `AsyncBufRead for FramedWrite2<T>`
* `BufRead for FramedWrite2<T>`
* `AsyncBufRead for Fuse<T, U>`
* `BufRead for Fuse<T, U>`
cc https://github.com/tokio-rs/tokio/issues/1256
=> codec: add AsyncBufRead/BufRead implementations

tokio-reactor/src/lib.rs, tokio-sync/Cargo.toml, tokio-sync/src/lib.rs, tokio-sync/src/lock.rs, tokio-sync/src/mpsc/bounded.rs, tokio-sync/src/mpsc/unbounded.rs, tokio-sync/src/oneshot.rs, tokio-sync/src/watch.rs, tokio-sync/tests/atomic_waker.rs, tokio-sync/tests/fuzz_atomic_waker.rs, tokio-sync/tests/fuzz_mpsc.rs, tokio-sync/tests/fuzz_semaphore.rs, tokio-sync/tests/lock.rs, tokio-sync/tests/watch.rs, tokio-test/src/task.rs, tokio-threadpool/src/shutdown.rs, tokio-timer/src/timer/entry.rs, tokio/examples/chat.rs, tokio/src/sync.rs
- Remove `poll_*` fns from some of the sync types.
- Move `AtomicWaker` and `Lock` to the root of the `sync` crate.
=> sync: polish and update API doc examples

tokio-process/Cargo.toml, tokio-process/src/lib.rs, tokio-process/src/unix/mod.rs, tokio-process/src/unix/orphan.rs, tokio-process/src/unix/reap.rs, tokio-process/src/windows.rs, tokio-process/tests/issue_42.rs, tokio-process/tests/smoke.rs, tokio-process/tests/stdio.rs, tokio-process/tests/support/mod.rs
* Denied all warnings in tests, and denied rust_2018_idioms violations
* Bumped the crate version and set publish = false
* Pruned dependencies:
- Only pull in tokio-sync on windows where it is used
- Removed unused dev-dependencies
* Switch to Async{Read, Write} traits from tokio-io rather than
futures-io
* Use #[tokio::test] where possible
* Removed deprecated items
* Fix all doc examples
Refs #1371
=> process: Misc polish

tokio-executor/Cargo.toml
Follow up to #1402. The code was removed, but the dependency was left.
=> executor: remove unused dependency

tokio-macros/src/lib.rs
Fixes #1341
There is no point in support function that takes arguments, so let's have easy way
=> macros: Error on function with arguments

tokio-macros/src/lib.rs
https://github.com/dtolnay/syn/issues/575
Using [`syn::Error::new_spanned`](https://docs.rs/syn/0.15.43/syn/struct.Error.html#method.new_spanned).
=> macros: improve error massages

tokio-uds/src/lib.rs, tokio-uds/src/split.rs, tokio-uds/src/stream.rs, tokio-uds/tests/split.rs, tokio/src/net.rs
This mirrors split API available in TcpStream.
=> uds: implement split and split_mut for UnixStream

tokio-signal/Cargo.toml, tokio-signal/src/registry.rs, tokio-signal/src/windows.rs
* Windows guarantees handler routines are always invoked in a new thread
(https://docs.microsoft.com/en-us/windows/console/handlerroutine), so we
don't need to use the handler-wake-another-driver technique used in the
Unix implementation
* By broadcasting the event notifications from the handler, we no longer
need the Driver task to be spawned, which fixes the starvation issue if
the executor which runs the Driver task goes away
* Also changed the behavior so that the default event handler runs if
all listeners for CTRL_{C, BREAK} events go away
Fixes #1000
=> Remove driver task for Windows event implementation

tokio-process/src/unix/mod.rs, tokio-signal/examples/multiple.rs, tokio-signal/examples/sighup-example.rs, tokio-signal/src/lib.rs, tokio-signal/src/unix.rs, tokio-signal/tests/drop_multi_loop.rs, tokio-signal/tests/drop_then_get_a_signal.rs, tokio-signal/tests/dropping_does_not_deregister_other_instances.rs, tokio-signal/tests/multi_loop.rs, tokio-signal/tests/notify_both.rs, tokio-signal/tests/simple.rs, tokio-signal/tests/support.rs, tokio-signal/tests/twice.rs
* This avoids having consumers import libc for common signals, and it
improves discoverability since users need not be aware that libc
contains all supported constants
* I had originally considered using a public enum, but given that `#[non_exaustive]` is not yet stable, I opted for a private enum with public constructors to give us maximum flexibility for adding new convenience constructors without technically breaking changes
* We also allow for an escape hatch via `from_raw` which allows for users to specify platform-specific signals (or any other signals which may or may not be a good idea to capture) without forcing us to support those definitions publicly
Refs #1243 
cc @carllerche in case you have any API related feedback
=> signal: Add SignalKind for registering signals more easily

tokio-test/Cargo.toml, tokio-test/src/lib.rs, tokio-test/tests/block_on.rs
Closes #1328 
- Promote `tokio` to a non-dev dependency of `tokio-test`
- Add a `block_on` function in `tokio-test` that creates a current thread `Runtime` and runs the provided future to completion with `Runtime::block_on`.
=> Add a block_on function to tokio-test

tokio-executor/src/enter.rs, tokio-executor/src/lib.rs, tokio-threadpool/src/blocking.rs, tokio-threadpool/tests/blocking.rs
Add `executor::exit`, allowing other executors inside threadpool::blocking
Blocking on a different executor inside `threadpool::blocking` doesn't work in Tokio `0.2.0-alpha.1` in contrast to `v0.1.x`. See example: https://gist.github.com/Eliah-Lakhin/9514b4798a2aed84615dbde807dbafa5
Patch `v0.2.x` with a fix from `v0.1.x`: https://github.com/tokio-rs/tokio/pull/1155
=> executor, threadpool: Patches v0.2.0 with a fix from #1155

tokio-io/Cargo.toml, tokio-io/src/io/buf_reader.rs, tokio-io/src/io/buf_writer.rs, tokio-io/src/io/mod.rs, tokio-io/src/lib.rs, tokio/src/io.rs
Closes #1437
Refs: https://github.com/rust-lang-nursery/futures-rs/pull/1573, https://github.com/rust-lang-nursery/futures-rs/pull/1608
=> io: add async BufReader/BufWriter

tokio-net/src/lib.rs, tokio-test/src/clock.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs, tokio-tls/tests/smoke.rs, tokio/src/runtime/current_thread/runtime.rs, tokio/src/runtime/threadpool/builder.rs, tokio/src/runtime/threadpool/mod.rs, tokio/tests/reactor.rs
Replaces `tokio_reactor::with_default` and `tokio_timer::with_default` with methods that return guard.
There are two more similar methods, but they are not one time, and instead restore to previous value (allowing to create stack of executors/clocks)
Due to that implementing guard would mean extra access to TLS for them, I'm not sure if it is desirable in this case
=> Refactoring one time TLS setters

tokio-process/src/unix/mod.rs, tokio-signal/examples/multiple.rs, tokio-signal/examples/sighup-example.rs, tokio-signal/src/lib.rs, tokio-signal/src/unix.rs, tokio-signal/tests/drop_multi_loop.rs, tokio-signal/tests/drop_then_get_a_signal.rs, tokio-signal/tests/dropping_does_not_deregister_other_instances.rs, tokio-signal/tests/multi_loop.rs, tokio-signal/tests/notify_both.rs, tokio-signal/tests/simple.rs, tokio-signal/tests/twice.rs
* This renames the SignalKind constructors to be a bit more readable
instead of using the signal names themselves
* I did not go as far as naming the methods based on what the signal does/represents (some signals alike `alarm` are kinda obvious, but `pipe` isn't as much), but bikeshedding is welcome
Refs #1243
=> signal: rename SignalKind methods

tokio-sync/src/oneshot.rs
Since `tokio_sync::oneshot` makes a `CausalCell::with_mut()` mutable
access in the `Inner::drop()`, we must use the instrumented
`loom::sync::Arc`.
To be clear, there is no issue with the underlying `tokio_sync::oneshot`.
This change just fixes the test so that it no longer reports a false negative
test output.
Uncovered by carllerche/loom#42
=> sync: fix fuzz_oneshot test by using instrumented `loom::sync::Arc`

tokio-process/src/lib.rs, tokio-process/tests/issue_42.rs, tokio-process/tests/smoke.rs, tokio-process/tests/stdio.rs, tokio-process/tests/support/mod.rs
https://github.com/tokio-rs/tokio/issues/1371 suggested to rewrite `CommandExt` in a way similar to `tokio-fs` (wrap the `std` struct and expose only asynchronous functions). I started rewriting Command in such a way.
Documentation and doctests are not updated yet, I just transformed the minimum amount of code to make tests pass. Please let me know if it's OK and if I shall continue :)
Refs: #1371
=> tokio-process: change CommandExt to a fully asynchronous Command struct

tokio-buf/Cargo.toml, tokio-codec/Cargo.toml, tokio-executor/Cargo.toml, tokio-fs/Cargo.toml, tokio-io/Cargo.toml, tokio-macros/Cargo.toml, tokio-net/Cargo.toml, tokio-process/Cargo.toml, tokio-sync/Cargo.toml, tokio-test/Cargo.toml, tokio-timer/Cargo.toml, tokio-tls/Cargo.toml, tokio/Cargo.toml
=> docs: add docs.rs metadata to build with all features

tokio-net/src/driver/mod.rs
Subj, I forgot that reactor module is private in `tokio-net` so actually now `set_default` returns private type
=> Make default reactor guard public

tokio-net/src/signal/ctrl_c.rs, tokio-net/src/signal/mod.rs, tokio-net/src/signal/unix.rs, tokio-net/src/signal/windows.rs, tokio-net/tests/signal_drop_multi_loop.rs, tokio-net/tests/signal_drop_then_get_a_signal.rs, tokio-net/tests/signal_dropping_does_not_deregister_other_instances.rs, tokio-net/tests/signal_multi_loop.rs, tokio-net/tests/signal_notify_both.rs, tokio-net/tests/signal_simple.rs, tokio-net/tests/signal_support/mod.rs, tokio-net/tests/signal_twice.rs, tokio-process/src/lib.rs, tokio-process/src/unix/mod.rs, tokio-process/src/windows.rs
* Also removed any `*_with_handle` related methods in favor of always
using the default reactor
Refs #1243
=> signal: remove `new()` constructors in favor of free functions

tokio-timer/src/delay.rs, tokio-timer/src/interval.rs
Implement `FusedStream` and `FusedFuture` for `Interval` and `Delay`.
To make `Delay` and `Interval` easy to use with the [`futures::select!`](https://docs.rs/futures-preview/0.3.0-alpha.18/futures/macro.select.html) macro.
These traits are required for use with `select!` to prevent completed futures from being polled in potentially invalid states. While this can be worked around by [`fusing`](https://docs.rs/futures-preview/0.3.0-alpha.18/futures/future/trait.FutureExt.html#method.fuse) them, all though this makes it harder to use methods associated with them - like if you'd want to reset a delay.
`Delay` is terminated if it is elapsed, and `Interval` simply returns `false` because it never terminates.
=> Implement FusedStream and FusedFuture for Interval and Delay

tokio-test/src/clock.rs, tokio-test/tests/block_on.rs, tokio-test/tests/clock.rs, tokio-timer/src/delay.rs, tokio-timer/src/lib.rs, tokio-timer/tests/delay.rs, tokio/src/timer.rs, tokio/tests/clock.rs, tokio/tests/runtime_current_thread.rs, tokio/tests/runtime_threaded.rs, tokio/tests/timer.rs
This PR adds a simple delay shortcut to avoid writing `Delay::new` everywhere.
I noticed that the `sleep` shortcut defined above my addition is not used anywhere in the repository,  should I at least use it in tests (i.e. `delay(now() + n)` -> `sleep(n)`)?
Suggested by: #1261
=> timer: introduce delay function shortcut

tokio-udp/src/frame.rs, tokio-udp/tests/udp.rs
Should (fix) #1443 in the v0.1.x branch.
`UdpFramed` now attempts to continue decoding past the first discrete item if there is more data in the read buffer. I added a test for this that sends a packet with 3 lines and tests for the successful decoding of each item in turn.
=> v0.1.x: Fix `UdpFramed` with regards to `Decode`

tokio-io/src/io/async_read_ext.rs, tokio-io/src/io/chain.rs, tokio-io/src/io/mod.rs, tokio-io/src/io/take.rs, tokio-io/tests/chain.rs, tokio-io/tests/take.rs
cc #1256
Refs:
* https://github.com/rust-lang-nursery/futures-rs/pull/1788
* https://github.com/rust-lang-nursery/futures-rs/pull/1810
=> io: add AsyncReadExt::{chain, take}

tokio-net/src/tcp/stream.rs, tokio-net/tests/tcp_shutdown.rs
Previously, `poll_shutdown` (and thus `AsyncWriteExt::shutdown`) on `TcpStream` did nothing. This PR makes it actually shut down the send side of the TCP connection so that the other side receives EOF.
=> Shut down TCP write when asked to shut down

tokio-executor/src/blocking.rs
Update the blocking threadpool so that threads that are idle for KEEP_ALIVE seconds without any queued work will be shutdown. As of now, KEEP_ALIVE does nothing of consequence and threads that are spawned into the pool will never be shutdown during runtime.
=> Update the blocking threadpool so that threads that are idle are shut down.

README.md
Hi,
I wanted to compile the example from the README but it had compile errors.
My pull request contains the version that does indeed compile with the current
nightly compiler and tokio version 0.2.0-alpha.4.
Cheers
=> Fix compile error in README with latest nightly and tokio version

tokio-timer/src/lib.rs, tokio/src/timer.rs
Expose convenience function for `Duration`-based waiting
Renames `sleep` to `delay_for` for consistency and reexports from `tokio::timer`. Additionally, the docs are tweaked to mention "sleep" for better discoverability. We considered standardizing on the `sleep` name instead, but `Sleep` as a type makes for an awkward noun.
=> timer: Rename `sleep` to `delay_for`, reexport from tokio

tokio-udp/src/frame.rs, tokio-udp/tests/udp.rs
This fixes two things:
- Repeated decodes now just use decode_eof reference the workaround we needed https://github.com/timberio/vector/blob/master/src/sources/udp.rs#L104 this now avoids this usage and makes LinesCodec work as expected.
- It reverts the change implemented that caused https://github.com/tokio-rs/tokio/issues/1510 by providing the old implementation and a new constructor that will allow you to enable the fix for repeated decodes.
=> udp: Fix UdpFramed decode

tokio-test/src/macros.rs, tokio-test/tests/macros.rs
#Motivation
Fixes #1511 
There were two issues at work in issue 1511
First, formatting arguments were not accepted because the macro was attempting to match on comma-separated token trees when it should have been just matching on one-or-more token trees.
Second, some of the uses of `format_args!` were being bound to a local name and then passed to panic for formatting.  This caused an error message that "temporary value dropped while borrowed". The fix for this was just inlining the `format_args!` usage into the place where the args were being formatted.
I also took the opportunity to fix the broken integration tests for these macros and expand it to include coverage of using the formatting arguments.
Finally, I brought the expansion of `assert_ready_eq` into line with the other two …
=> Test fix assert format args

tokio-net/src/process/mod.rs
As discussed in #1371, this adds methods to `tokio_process::Command` equivalent to those in `std::os::{unix,windows}::process::CommandExt`.
=> Add platform-specific methods to Command

tokio-net/src/process/mod.rs
This allows the usage of `std::os::{unix,windows}::process::CommandExt`, which can't be implemented on `tokio_process::Command` since their methods have `&mut StdCommand` return types.
=> tokio-process: Implement From<StdCommand> for Command

tokio-net/src/process/mod.rs, tokio-net/tests/process_stdio.rs
Omit intermediate `Future` types/wrappers in favor of async functions. We can always bring back a named type in a backwards compatible manner if we decide
Refs #1400
=> process: omit several future types in favor of async/await

tokio-tls/src/lib.rs
Previously, it was impossible to access the underlying stream through a `tokio_tls::TlsStream`.
This patch adds `get_ref` and `get_mut` on `TlsStream` which return references to the underlying stream.
=> Add get_ref and get_mut

tokio-tls/src/lib.rs
Fixes: #1546
Signed-off-by: Kirill Mironov <vetrokm@gmail.com>
Newest rust nightly has this rust-lang/rust#64292 pull request merged, which broke compilation of some crates, including tokio-tls.
Make the closure own the values instead of borrowing them
=> tls: fix new temporary lifetime rustc error [E0597]

tokio-buf/src/lib.rs, tokio-codec/src/lib.rs, tokio-executor/src/lib.rs, tokio-fs/src/lib.rs, tokio-fs/src/read_dir.rs, tokio-fs/src/read_link.rs, tokio-fs/src/remove_dir.rs, tokio-fs/src/rename.rs, tokio-io/src/lib.rs, tokio-macros/src/lib.rs, tokio-net/src/lib.rs, tokio-net/src/process/mod.rs, tokio-sync/src/lib.rs, tokio-test/src/lib.rs, tokio-timer/src/lib.rs, tokio-tls/src/lib.rs, tokio/src/lib.rs
#Motivation
Continuing the work started in #1474 to transition all the intra-doc links in the documentation from hard-coded arbitrary urls to using rustdoc item link resolution.
Also related to #1473.
=> WIP: Fix docs links

tokio-fs/src/blocking.rs
This is for fixing bug #1527, this patch propagates AsyncWrite flushes to the wrapped IO layers.
A boolean is added to keep track of flushing status and poll_flush was rewritten in the style of poll_write to keep track of the extra state.
=> Propagate AsyncWrite flushes to lower IO layers for stdout / stderr.

tokio-sync/src/mpsc/block.rs
^
Notes: I've looked at the compiled code and it seems that both produce the same code. (https://godbolt.org/z/S98o3F). It's also noticeable that there is a memcpy which copies stack data to box's heap space, which seems rather useless, but I guess this is a limitation within llvm/rust.
=> sync: replace deprecated mem::uninitialized usage with MaybeUninit

azure-pipelines.yml, ci/azure-cross-compile.yml, tokio-timer/src/atomic.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/entry.rs, tokio-timer/src/timer/mod.rs
Fixes https://github.com/tokio-rs/tokio/pull/1421#issuecomment-527911780
Reverts part of #1421.
=> timer: use our own AtomicU64 on targets with target_has_atomic less than 64

tokio-executor/benches/blocking.rs, tokio-executor/benches/threadpool.rs, tokio-executor/benches/threadpool_depth.rs, tokio-sync/benches/mpsc.rs, tokio-sync/benches/oneshot.rs, tokio/benches/latency.rs, tokio/benches/mio-ops.rs, tokio/benches/tcp.rs
This adds a broken feature to benchmarks that have not been updated yet.
=> Add broken feature to old benchmarks

tokio-buf/src/lib.rs, tokio-codec/src/length_delimited.rs, tokio-codec/src/lib.rs, tokio-executor/src/executor.rs, tokio-executor/src/lib.rs, tokio-executor/src/threadpool/blocking.rs, tokio-executor/src/typed.rs, tokio-fs/src/lib.rs, tokio-io/src/lib.rs, tokio-macros/src/lib.rs, tokio-net/src/driver/mod.rs, tokio-net/src/lib.rs, tokio-net/src/tcp/listener.rs, tokio-net/src/tcp/stream.rs, tokio-net/src/util/poll_evented.rs, tokio-sync/src/lib.rs, tokio-sync/src/watch.rs, tokio-test/src/lib.rs, tokio-test/src/macros.rs, tokio-timer/src/lib.rs, tokio-timer/src/timeout.rs, tokio-tls/src/lib.rs, tokio/src/executor.rs, tokio/src/lib.rs, tokio/src/runtime/current_thread/mod.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/threadpool/builder.rs, tokio/src/runtime/threadpool/mod.rs, tokio/src/runtime/threadpool/task_executor.rs, tokio/src/timer.rs
Denies all warnings except `dead_code` and `unused_variables`.
cc #1086
Refs: https://github.com/rust-lang-nursery/futures-rs/pull/1672
=> chore: deny warnings for doc tests

tokio-sync/src/lib.rs, tokio-sync/src/mutex.rs, tokio-sync/tests/mutex.rs, tokio/examples/chat.rs, tokio/src/sync.rs
This renames `Lock` to `Mutex`, and brings the API more in line with `std::sync::Mutex`. In partcular, locking now only takes `&self`, with the expectation that you place the `Mutex` in an `Arc` (or something similar) to share it between threads.
Fixes #1544.
Part of #1210.
=> sync: Make Lock more similar to std::sync::Mutex

tokio-executor/src/blocking.rs
I hit a problem that after 10 seconds idle, no blocking tasks would
run anymore as all blocking threads exited and the Pool was convinced
that there were still runners available.
Nowhere in the code is num_th decremented. Please make sure the num_idle decrement is correct at that point in the code.
=> Decrement thread count on thread exit.

tokio-timer/src/interval.rs, tokio-timer/src/lib.rs, tokio/tests/clock.rs
`delay_for` should be usable with a mocked clock.
Call the (potentially) mocked clock.
=> fix: delay_for should use tokio_timer::clock::now

tokio/src/sync.rs
=> Export sync::Barrier from tokio::sync

tokio/Cargo.toml, tokio/src/net.rs
Fixes: #1559
Signed-off-by: Kirill Mironov <vetrokm@gmail.com>
Currently to use process feature you need to depend on tokio-net explicitly, instead of using main tokio crate.
add `process` feature to main tokio crate that includes `io` and `tokio-net/process` features
=> tokio: add process feature

ci/azure-cross-compile.yml, tokio-timer/src/atomic.rs
This enables using tokio on Raspberry Pi and other similar devices
Use a locked 64 bit integer instead.
=> 32 bit ARM only has 32 bit atomics.

tokio-macros/Cargo.toml, tokio-macros/src/lib.rs
cc #1257
Currently `#[tokio::main]` only checks that the first element in the path is multi_thread or single_thread.
Refs: 
* https://docs.rs/syn/1.0.5/syn/struct.Path.html#method.get_ident
* https://github.com/dtolnay/syn/pull/696
=> macros: fix handling of arguments of #[tokio::main] attribute

tokio-io/Cargo.toml, tokio-io/src/io/buf_reader.rs, tokio-io/src/io/buf_stream.rs, tokio-io/src/io/buf_writer.rs, tokio-io/src/io/chain.rs, tokio-io/src/io/copy.rs, tokio-io/src/io/flush.rs, tokio-io/src/io/lines.rs, tokio-io/src/io/mod.rs, tokio-io/src/io/read.rs, tokio-io/src/io/read_exact.rs, tokio-io/src/io/read_line.rs, tokio-io/src/io/read_to_end.rs, tokio-io/src/io/read_to_string.rs, tokio-io/src/io/read_until.rs, tokio-io/src/io/shutdown.rs, tokio-io/src/io/take.rs, tokio-io/src/io/write.rs, tokio-io/src/io/write_all.rs, tokio-io/src/lib.rs
Based on #1586 (First 2 commits are the same as #1586)
This removes most pin-projection related `unsafe` code: https://github.com/tokio-rs/tokio/commit/16b06e3bc1405f64b6dfb38aab2589fcabd579f7
And removes manual `Unpin` implementations and add tests to check that `Unpin` requirement does not change accidentally. see commit message for more: https://github.com/tokio-rs/tokio/commit/7ad962db620ea896755fec9d93fe3a68c02b0159
=> io: remove unsafe pin-projections and remove manual Unpin implementations

tokio-macros/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/runtime/mod.rs
To allow smaller builds using tokio, it would be useful to allow exposing the current-thread runtime without enabling so many features as `rt-full` does.
- Adds a minimum `rt-current-thread` optional feature that exports
`tokio::runtime::current_thread`.
- Adds a `macros` optional feature to enable the `#[tokio::main]` and
`#[tokio::test]` attributes.
- Adjusts `#[tokio::main]` macro to select a runtime "automatically" if
a specific strategy isn't specified. Allows using the macro with only
the rt-current-thread feature.
=> tokio: add `rt-current-thread` optional feature

tokio-io/src/io/buf_stream.rs
`BufReader` and `BufWriter` have methods for this.
=> io: add get_*/into_inner methods to BufStream

tokio-fs/src/file.rs
The doc comment of `tokio::fs::File::sync_data` refers to `poll_sync_all` which has been modified to `sync_all`.
For reference, the old `poll_sync_all` in 0.1.x: https://github.com/tokio-rs/tokio/blob/59fb5b9a7d89ee84389b8f8a039e874ef8971dbd/tokio-fs/src/file/mod.rs#L269
Update the doc comment to reflect the change of the function name.
=> fs: Update the doc comment of File::sync_data

tokio-sync/src/task/atomic_waker.rs
The algorithm backing `AtomicWaker` effectively uses a spin lock backed
by notifying & yielding the current task. This adds a `spin_lock_hint`
annotation to cover this case.
While, in practice, the omission of `spin_lock_hint` would not cause
problems, there are platforms that do not handle spin locks very well
and could enter a deadlock in pathological cases.
This fixes CI.
=> sync: add `spin_loop_hint` to atomic waker

ci/patch.toml, tokio-codec/Cargo.toml, tokio-executor/Cargo.toml, tokio-fs/Cargo.toml, tokio-io/Cargo.toml, tokio-net/Cargo.toml, tokio-sync/Cargo.toml, tokio-test/Cargo.toml, tokio-timer/Cargo.toml, tokio-tls/Cargo.toml, tokio/Cargo.toml
~~Depends on https://github.com/carllerche/loom/pull/70.~~
Blocked on https://github.com/carllerche/loom/pull/71 and the next release of loom.
=> chore: update futures-preview to 0.3.0-alpha.19

tokio-io/src/io/buf_reader.rs, tokio-io/src/io/buf_stream.rs, tokio-io/src/io/buf_writer.rs
This can be useful in cases where you want to share a common type between an arm that uses `BufStream::new` and one that manually creates the `BufReader` and `BufWriter` using `with_capacity`.
=> Create BufStream from a BufReader + BufWriter

tokio-fs/examples/std-echo.rs
https://github.com/rust-lang/rust/issues/64477 means that `foo(format!(...)).await` is broken. https://github.com/rust-lang/rust/pull/64856 fixes it, but hasn't landed yet (and may never). See https://github.com/rust-lang/rust/issues/64477#issuecomment-534669068 for a detailed explanation.
=> Fix rust-lang/rust#64477 & rust-lang/rust#64856

build-tests/tests/fail/macros_invalid_input.rs, build-tests/tests/fail/macros_invalid_input.stderr, tokio-macros/src/lib.rs
Removes restriction on arguments in non-`main` functions
We don't really return future, so lifetime should not be concern
P.s. these build tests are utter shite
=> macros: Allow arguments in non-main functions

tokio/src/prelude.rs
Trivial change as suggested by @taiki-e.
=> This fixes #1593 by making "use as _" linked in the documentation.

build-tests/tests/fail/macros_invalid_input.stderr, tokio-macros/src/lib.rs
In the past, it was not possible to choose to use the multi-threaded
tokio `Runtime` in tests, which meant that any test that transitively
used `executor::threadpool::blocking` would fail with
```
'blocking' annotation used from outside the context of a thread pool
```
This patch adds a runtime annotation attribute to `#[tokio::test]` just
like `#[tokio::main]` has, which lets users opt in to the threadpool
runtime over `current_thread` (the default).
=> Allow selecting runtime in tokio::test attr

tokio-net/src/tcp/mod.rs, tokio/src/net.rs
With tokio `0.2.0-alpha.5`, We can't use the `Incoming` stream type in our types, because it's not exported. For the same reason, it can't be viewed [in the documentation](https://docs.rs/tokio/0.2.0-alpha.5/tokio/net/struct.TcpListener.html#method.incoming) (also dead link [here](https://docs.rs/tokio/0.2.0-alpha.5/tokio/net/tcp/index.html)).
`pub use` the `Incoming` in the `tcp` module.
Not sure about tests. Does it make sense to make a test for this?
=> Fix: tokio_net::tcp::incoming::Incoming type not exported

ci/azure-cross-compile.yml, tokio-timer/src/atomic.rs
As mentioned in https://github.com/tokio-rs/tokio/pull/1581#discussion_r331846074, it seems [`arm-unknown-linux-gnueabi` has `AtomicU64`](https://github.com/rust-lang/rust/blob/4ac4809ccf5f77083ae7155dcc83e921341c2614/src/librustc_target/spec/arm_unknown_linux_gnueabi.rs#L5).
Among `target_arch = "arm"` targets supported by cross, the following targets have `target_has_atomic` less than 64:
* [arm-linux-androideabi](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/arm_linux_androideabi.rs#L7)
* [armv5te-unknown-linux-musleabi](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/armv5te_unknown_linux_musleabi.rs#L23)
* [thumbv7em-none-eabi](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/thumbv7em_none_eabi.rs#L28)
* …
=> timer: test arm on targets with target_has_atomic less than 64

tokio-io/src/io/copy.rs, tokio-io/src/io/empty.rs, tokio-io/src/io/mod.rs, tokio-io/src/io/repeat.rs, tokio-io/src/io/sink.rs, tokio-io/src/lib.rs, tokio/src/io.rs
The standard library's `io` module has small utilities such as `repeat`,
`empty`, and `sink`, which return `Read` and `Write` implementations.
These can come in handy in some circiumstances. `tokio::io` has no
equivalents that implement `AsyncRead`/`AsyncWrite`.
This commit adds `repeat`, `empty`, and `sink` helpers to `tokio::io`.
=> io: add missing utility functions

tokio-executor/src/blocking.rs
A counter is now used to prevent surprises with spurious notifications. 
Jobs are now run at a single spot in the code. State transitions are now clearer and they now avoid spawning threads uselessly.
Fixes tokio-rs/tokio#1542
=> Accurate idle thread tracking for the blocking pool

tokio-io/src/io/async_buf_read_ext.rs, tokio-io/src/io/mod.rs, tokio-io/src/io/split.rs
`AsyncBufReadExt` currently lacks an async version of `std::io`'s 
`BufRead::split` method.
This branch adds a `split` method to `AsyncBufReadExt`, analogous to
`std::io::BufRead::split`.
=> io: add `AsyncBufReadExt::split`

tokio-sync/src/oneshot.rs
When polling the task, the current waker is saved to the oneshot state.
When the handle is migrated to a new task and polled again, the waker
must be swaped from the old waker to the new waker. In some cases, there
is a potential for the old waker to leak.
This bug was caught by loom with the recently added memory leak
detection.
=> sync: fix mem leak in oneshot on task migration

azure-pipelines.yml, tokio-net/tests/process_issue_42.rs, tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/net.rs, tokio/src/process.rs, tokio/src/signal.rs
Currently, the `signal` and `process` functionality is rexported in the main `tokio` crate under `tokio::net` since the actual implementations live in the `tokio_net` crate. However, this is causing some confusion for where to find the imports as reported in #1563
We instead reexport the public types directly under `tokio::{signal, process}` to make discovery easier.
=> tokio: move `signal` and `process` reexports to crate root

tokio-timer/src/delay.rs
Following a discussion on Discord
`is_terminated` must return `false` until the future has been polled at least once to make sure that the associated block in select is called even after the delay has elapsed.
You use `Delay` in a `select!` by [fusing it](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/future/trait.FutureExt.html#method.fuse):
```rust
let delay = tokio::timer::delay(/* ... */);
let delay = delay.fuse();
select! {
_ = delay => {
/* work here */
}
}
```
=> Remove incorrect FusedFuture impl on Delay

build-tests/tests/fail/macros_invalid_input.rs, build-tests/tests/fail/macros_invalid_input.stderr, tokio-macros/src/lib.rs
As discussed in #1620, the attribute names for `#[tokio::main]` and `#[tokio::test]` aren't great. Specifically, they both use `single_thread` and `multi_thread`, as opposed to names that match the runtime names: `current_thread` and `threadpool`. This PR changes the former to the latter.
Fixes #1627.
=> macros: Use more consistent runtime names

tokio/src/runtime/mod.rs
Documentation references the old helper function `runtime::run`, which has been removed, as mentioned on #1536.
I've updated to reference on the runtime module to mention the new `tokio::main` attribute macro.
=> Update runtime doc regarding `runtime::run` function helper

tokio-net/src/driver/mod.rs, tokio-net/src/driver/reactor.rs, tokio-net/src/driver/registration.rs, tokio-net/src/process/unix/mod.rs, tokio-net/src/process/windows.rs, tokio-net/src/signal/unix.rs, tokio-net/src/tcp/listener.rs, tokio-net/src/tcp/stream.rs, tokio-net/src/udp/socket.rs, tokio-net/src/uds/datagram.rs, tokio-net/src/uds/listener.rs, tokio-net/src/uds/stream.rs, tokio-net/src/uds/ucred.rs, tokio-net/src/util/poll_evented.rs, tokio-net/tests/bind_resource.rs, tokio-net/tests/process_issue_42.rs, tokio-net/tests/signal_drop_multi_loop.rs, tokio-net/tests/signal_multi_loop.rs, tokio/tests/drop-core.rs
The `tokio_net` resources can be created outside of a runtime due to how tokio
has been used with futures to date. For example, this allows a `TcpStream` to be
created, and later passed into a runtime:
```
let stream = TcpStream::connect(...).and_then(|socket| {
// do something
});
tokio::run(stream);
```
In order to support this functionality, the reactor was lazily bound to the
resource on the first call to `poll_read_ready`/`poll_write_ready`. This
required a lot of additional complexity in the binding logic to support.
With the tokio 0.2 common case, this is no longer necessary and can be removed.
All resources are expected to be created from within a runtime, and should panic
if not done so.
Closes #1168
The `tokio_net` crate now assumes there to be a `CURRENT_REACTOR` set on the …
=> net: Eagerly bind resources to reactors

tokio/src/fs/create_dir.rs, tokio/src/fs/create_dir_all.rs, tokio/src/fs/file.rs, tokio/src/fs/hard_link.rs, tokio/src/fs/metadata.rs, tokio/src/fs/open_options.rs, tokio/src/fs/os/unix/symlink.rs, tokio/src/fs/os/windows/symlink_dir.rs, tokio/src/fs/os/windows/symlink_file.rs, tokio/src/fs/read.rs, tokio/src/fs/read_dir.rs, tokio/src/fs/read_link.rs, tokio/src/fs/read_to_string.rs, tokio/src/fs/remove_dir.rs, tokio/src/fs/remove_dir_all.rs, tokio/src/fs/remove_file.rs, tokio/src/fs/rename.rs, tokio/src/fs/set_permissions.rs, tokio/src/fs/symlink_metadata.rs, tokio/src/fs/write.rs, tokio/src/runtime/current_thread/runtime.rs, tokio/src/runtime/threadpool/builder.rs, tokio/src/runtime/threadpool/mod.rs, tokio/src/timer/clock/mod.rs
There is a lot of code like the following:
```rust
pub async fn open<P>(&self, path: P) -> io::Result<File>
where
P: AsRef<Path>,
{
```
Downsides:
* `P` is likely never specified by the caller
* `path: P` does not convey much. The reader has to move their eyes to two other places to see it's a local generic and which bounds it has
* It takes four lines of code.
Since quite a while back we have argument position `impl Trait` that can be used for situations like this. However, changing from a generic to `impl Trait` is technically breaking. So any such changes has to be made before `tokio 0.2` is released.
For cases like the above I changed it to
```rust
pub async fn open(&self, path: impl AsRef<Path>) -> io::Result<File> {
```
Single line of code, and it's very easy to see what type `path` …
=> argument position impl trait instead of generic where appropriate

tokio-executor/src/thread_pool/tests/loom_pool.rs
This adds an extra spawned task during the thread-pool shutdown loom
test. This results in additional cases being tested, primarily tasks
being stolen.
=> thread-pool: test additional shutdown cases

tokio-sync/src/watch.rs, tokio/src/fs/read_dir.rs, tokio/src/process/mod.rs
Continuing the work started in #1474 to transition all the intra-doc links in the documentation from hard-coded arbitrary urls to using rustdoc item link resolution.
Also related to #1473 and #1523.
=> Fix docs links: Redux

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs
I need this to implement SMTP pipelining checks. I mostly need to
flush my send buffer when the read buffer is empty before waiting for
the next command.
Accessors are added on Framed and FramedRead.
=> Allow non-destructive access to the read buffer.

tokio/Cargo.toml, tokio/tests/rt_current_thread.rs, tokio/tests/rt_thread_pool.rs
Most dev dependendencies are unused now that examples are moved into a
separate crate.
=> chore: prune dev-dependencies

.cirrus.yml, ci/azure-install-rust.yml
install only the components we need.
https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#profiles
> * The minimal profile includes as few components as possible to get a working compiler (rustc, rust-std, and cargo). It's recommended to use this component on Windows systems if you don't use local documentation, and in CI.
> * The default profile includes all the components previously installed by default (rustc, rust-std, cargo, and rust-docs) plus rustfmt and clippy. This profile will be used by rustup by default, and it's the one recommended for general use.
> * The complete profile includes all the components available through rustup, including miri and IDE integration tools (rls and rust-analysis).
=> ci: install minimal profile by default

tokio-test/Cargo.toml, tokio-test/src/macros.rs, tokio-test/src/task.rs, tokio-util/tests/framed_read.rs, tokio-util/tests/framed_write.rs, tokio-util/tests/length_delimited.rs, tokio/tests/io_async_read.rs, tokio/tests/sync_atomic_waker.rs, tokio/tests/sync_mpsc.rs, tokio/tests/sync_oneshot.rs, tokio/tests/sync_semaphore.rs, tokio/tests/timer_delay.rs, tokio/tests/timer_interval.rs, tokio/tests/timer_queue.rs, tokio/tests/timer_throttle.rs, tokio/tests/timer_timeout.rs
Delete `MockTask` in favor of `task::spawn`. Both are functionally
equivalent.
=> test: unify MockTask and task::spawn

tokio/src/runtime/current_thread/mod.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/thread_pool/pool.rs, tokio/src/runtime/thread_pool/shutdown.rs, tokio/src/runtime/thread_pool/worker.rs
`enter` is now internal, so we can avoid the `Result` and
`Error `implementation. This also moves the runtime-in-runtime
panic to a single location where a more detailed error message
can be used.
=> simplify enter

tokio-executor/src/global.rs, tokio-executor/src/lib.rs, tokio-reactor/src/lib.rs, tokio-timer/src/clock/clock.rs, tokio-timer/src/clock/mod.rs, tokio-timer/src/timer/handle.rs, tokio-timer/src/timer/mod.rs
This commit adds `set_default` drop guard style APIs for setting the
default reactor, executor, and timer. These are similar to the APIs used
in `tokio` 0.2
In addition to having potentially better ergonomics than the
`with_default` closure APIs, the drop-guard based APIs will be helpful
in rewriting the `tokio-compat` crate to wrap the existing tokio 0.2
runtime, rather than constructing its own runtime.
Because the runtime does not expose an `around_worker` API, it cannot
currently be used with the 0.1 `with_default` method of setting the
reactor, timer, and executor. This means that tokio-compat must
duplicate a lot of existing code from `tokio` to construct the runtime,
which is unfortunate (and has the potential to introduce errors). On the
other hand, we can use the drop guard APIs …
=> [0.1.x] add `set_default` to 0.1 executor, timer, and reactor

tokio/src/timer/mod.rs
It is a more common use case that is to simply cause a delay for an amount of time.
I think it is more appropriate to show off `delay_for` in the example rather than `delay` that is useful only for less common use cases.
=> timer: have example use delay_for instead of delay

.cirrus.yml, azure-pipelines.yml, ci/azure-clippy.yml, rust-toolchain
Rust 1.39 has been released: https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html
=> chore: update CI config to test on stable

tokio-tls/tests/smoke.rs
macOS 10.15 introduced new requirements for certificates to be trusted:
https://support.apple.com/en-us/HT210176
tls smoke.rs tests are failing on latest macOS.
Add extendedKeyUsage to the certificate generated in tests.
=> tls: fix test certificate to work on macOS 10.15

tokio-threadpool/src/blocking/global.rs, tokio-threadpool/src/blocking/mod.rs, tokio-threadpool/src/lib.rs
The initial version of `tokio-compat`'s compatibility runtime added in
#1663 doesn't support the calls to `tokio_threadpool` 0.1's `blocking`.
This is because (unlike the timer, executor, and reactor), there's no
way to override the global `blocking` functionality in
`tokio-threadpool`.
As discussed [here][1], this branch adds APIs to the v0.1.x version of
`tokio-threadpool` that allow overriding the behavior used by calls to
`blocking`. The threadpool crate now exposes `blocking::set_default` and
`blocking::with_default` functions, like `executor`, `timer`, and
`reactor`. This will allow `tokio-compat` to override calls to 0.1's
`blocking` to use the new `tokio` 0.2 blocking APIs.
Unlike the similar APIs in `executor`, `timer`, and `reactor`, the hooks
for overriding blocking behaviour …
=> v0.1.x: allow overriding blocking behavior

tokio/src/net/addr.rs
adding impls the same as [std](https://doc.rust-lang.org/nightly/std/net/trait.ToSocketAddrs.html#implementors).
=> net: add more impls for ToSocketAddrs

tokio-util/Cargo.toml, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio/Cargo.toml, tokio/src/future/try_join.rs, tokio/src/io/util/buf_reader.rs, tokio/src/io/util/buf_stream.rs, tokio/src/io/util/buf_writer.rs, tokio/src/io/util/chain.rs, tokio/src/io/util/take.rs
https://github.com/tokio-rs/tokio/pull/1774#discussion_r347024921
=> Migrate from pin-project to pin-project-lite

tokio/src/sync/watch.rs
There are limitations with `async/await` (no GAT) requiring the value to
be cloned on receive. The `poll` based API is not currently exposed.
This makes the `Clone` requirement explicit.
=> sync: require `T: Clone` for watch channels.

tokio-test/tests/block_on.rs, tokio/src/time/delay.rs, tokio/src/time/delay_queue.rs, tokio/src/time/driver/entry.rs, tokio/src/time/driver/handle.rs, tokio/src/time/driver/registration.rs, tokio/src/time/tests/mod.rs, tokio/src/time/tests/test_delay.rs
Similar to #1666, it is no longer necessary to lazily register delays with the
executions default timer. All delays are expected to be created from within a
runtime, and should panic if not done so.
`tokio::time` now assumes there to be a `CURRENT_TIMER` set when creating a
delay; this can be assumed if called within a tokio runtime. If there is no
current timer, the application will panic with a "no current timer" message.
Similar to #1666, `HandlePriv` can probably be removed, but this mainly prepares
for 0.2 API changes. Because it is not in the public API, this can be done in a
following change.
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
=> time: Eagerly bind delays to timer

examples/Cargo.toml, tokio-test/Cargo.toml, tokio-tls/src/lib.rs, tokio-util/Cargo.toml, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/length_delimited.rs, tokio-util/src/codec/lines_codec.rs, tokio-util/src/udp/frame.rs, tokio-util/tests/codecs.rs, tokio-util/tests/framed.rs, tokio-util/tests/framed_read.rs, tokio-util/tests/framed_write.rs, tokio-util/tests/udp.rs, tokio/Cargo.toml, tokio/src/io/async_read.rs, tokio/src/io/util/buf_reader.rs, tokio/src/io/util/buf_stream.rs, tokio/src/io/util/buf_writer.rs, tokio/src/io/util/read_to_end.rs, tokio/src/io/util/take.rs, tokio/src/net/tcp/split.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/unix/split.rs, tokio/src/net/unix/stream.rs, tokio/tests/io_async_read.rs
Tokio will track changes to bytes until 0.5 is released.
I wasn't sure what to do w/ the traits. I updated `prepare_uninitialized_buffer` to take `&mut [MaybeUninit<u8>]` :shrug:
=> chore: update `bytes` dependency to git master

tokio/src/task/join.rs, tokio/src/task/mod.rs
The new `tokio::task` module is pretty lacking in API docs. 
This branch adds new API docs to the `task` module, including:
* Module-level docs with a summary of the differences between 
tasks and threads
* Examples of how to use the `task` APIs in the module-level docs
* More docs for `yield_now`
* More docs and examples for `JoinHandle`, based on the 
`std::thread::JoinHandle` API docs.
This branch contains commits cherry-picked from #1794 
=> improve `tokio::task` API documentation

tokio/src/io/mod.rs, tokio/tests/io_split.rs
=> io: flatten `split` module

tokio/src/io/mod.rs
The `tokio::io` module's docs are fairly sparse and not particularly up
to date. They ought to be improved before release.
This branch adds new module-level docs to `tokio::io`. The new docs are
largely inspired by `std::io`'s documentation, and highlight the
similarities and differences between `tokio::io` and `std::io`.
=> docs: refresh `tokio::io` API docs

tokio/src/runtime/mod.rs, tokio/src/task/mod.rs
The `tokio::runtime` module's docs need to be updated to
track recent changes.
This branch updates and expands the `runtime` docs.
=> docs: update and expand the `tokio::runtime` API docs

tokio/src/lib.rs
Tokio's crate-level docs are currently pretty sparse, and in some cases
reference old names for APIs. Before 0.2 is released, they could use a
fresh coat of paint.
This branch reworks and expands the `lib.rs` docs. In particular, I've
added a new "A Tour of Tokio" section, inspired by the [standard
library's similarly-named section][std]. This section lists all of
`tokio`'s public modules, and summarizes their major APIs. It also lists
the feature flags necessary to enable those APIs.
[std]: https://doc.rust-lang.org/std/index.html#a-tour-of-the-rust-standard-library
=> docs: expand and update crate-level docs

azure-pipelines.yml, ci/azure-check-features.yml, ci/azure-check-minrust.yml, ci/azure-test-stable.yml
Workaround for https://github.com/taiki-e/cargo-hack/issues/15
`-Z avoid-dev-deps` (tracking-issue: https://github.com/rust-lang/cargo/issues/5133) is an unstable feature of cargo that has almost the same effect as cargo-hack's `--no-dev-deps`. However, unlike `--no-dev-deps`, the manifest file is not edited. 
FWIW: 
`-Z avoid-dev-deps` works well with `cargo check/build/run`, but not with `cargo publish`.
On the other hand, `--no-dev-deps` doesn't work well with `cargo install`.
=> ci: use -Z avoid-dev-deps in features check instead of --no-dev-deps

Cargo.toml, azure-pipelines.yml, ci/azure-test-build.yml, tests-build/Cargo.toml, tests-build/README.md, tests-build/src/lib.rs, tests-build/tests/fail/macros_invalid_input.rs, tests-build/tests/fail/macros_invalid_input.stderr, tests-build/tests/macros.rs
This directory was deleted when `cargo hack` was introduced, however
there were some tests that were still useful (macro failure output).
Also, additional build tests will be added over time
=> ci: bring back build tests

tokio/src/process/mod.rs, tokio/tests/process_issue_42.rs, tokio/tests/process_kill_on_drop.rs
* This updates the tokio `Command` and `Child` behavior to match that of
the stdlib: spawned processes will *not* be automatically killed when
the handle is dropped
- Unlike the stdlib, any dropped (unix) processes may be reaped by tokio
behind-the-scenes after they exit and if new processes are awaited,
which mitigates the risks of piling up unreaped zombie unix processes
* A `Command::kill_on_drop` method is added to allow the caller to
control whether the spawned child should be killed when the handle is
dropped. By default, this value is `false`.
* The `Child::forget` method has been removed, as it is superseded by
`Command::kill_on_drop`
Fixes #1771
=> process: do not kill spawned processes on drop

README.md
I was told by contributors that the `master` branch was no longer affected by performance issues and that it was faster than `0.1`. Thus the notice should be removed.
=> tokio: remove performance regression notice

examples/proxy.rs, tokio/src/io/async_read.rs, tokio/src/io/mod.rs, tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/prelude.rs, tokio/tests/buffered.rs, tokio/tests/io_copy.rs, tokio/tests/tcp_echo.rs, tokio/tests/tcp_shutdown.rs
Adds method level documentation for `AsyncReadExt`, `AsyncWriteExt`..
=> docs: improve tokio::io API documentation

tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/net/addr.rs, tokio/src/net/mod.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/mod.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/mod.rs, tokio/src/net/udp/socket.rs, tokio/src/net/unix/datagram.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/mod.rs, tokio/src/net/unix/stream.rs, tokio/src/sync/watch.rs, tokio/tests/uds_datagram.rs, tokio/tests/uds_stream.rs
Also makes the `tokio::net::{tcp, udp, unix}` modules only for "utility"
types. The primary types are in `tokio::net` directly.
=> doc: add more doc_cfg annotations

README.md, tokio/README.md
=> remove updating note from readme

tokio/Cargo.toml
tokio-uds 0.2.4 has the `UnixDatagramFramed` which is reexported here
and tokio-threadpool 0.1.16 uses a new enough rand that compiles with
modern toolchains.
---
Link #1656 but for the 0.1 branch. See that PR for the motivation and such.
=> v0.1.x: tokio: bump minimum versions

tokio/src/time/mod.rs
reexport Elapsed from tokio::time, needed for timeout error result in timeout usage.
=> reexport Elapsed from tokio::time

tokio/src/fs/file.rs, tokio/tests/support/mock_file.rs
This provides the ability to get the raw OS handle for a `File`. The
`Into*` variant cannot be provided as `File` needs to maintain ownership
of the `File`. The actual handle may have been moved to a background
thread.
=> fs: impl AsRawFd / AsRawHandle for File

tokio/src/net/tcp/listener.rs, tokio/src/net/unix/listener.rs
This fixes the API docs for both `TcpListener::incoming` and
`UnixListener::incoming`. The function now takes `&mut self` instead of
`self`. Adds an example for both function.
=> doc: fix and improve `incoming()` API doc

tokio/src/runtime/global.rs
If runtime doesn't have task scheduler,`tokio::spawn` from context of this runtime will produce panic `must be called from the context of Tokio runtime`, which is unclear, because it's actually done from the context of runtime. New panic message specifies that runtime should have task scheduler in order to execute spawned tasks.
Changed runtime panic message. Closes #1837.
=> Specify that runtime should have task scheduler

tokio/src/runtime/builder.rs
Current `rutime::Builder` example builds `Runtime` with `num_threads`, `thread_name`, `thread_stack_size` but without `threaded_scheduler()` call, so it's useless. I wrote a [comment](https://github.com/tokio-rs/tokio/pull/1839#issuecomment-559195075) in previous PR : 
> Also there's still a thing that can confuse people - calling num_threads() on Builder without call of threaded_scheduler in fact does nothing.
> Maybe it's a good idea to make debug assertion for this case or warning at least?
> Because when I write code like
> 
> ```rust
> let rt = tokio::runtime::Builder::new().num_threads(4).build().unwrap(); 
> ```
>  I don't expect that num_threads is useless unless threaded_scheduler method is called.
Now it's even missed in docs examples, so I think ordinary users will face this …
=> Fixed `runtime::Builder` example

README.md, tokio-util/src/codec/decoder.rs, tokio/README.md, tokio/src/fs/mod.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs, tokio/src/io/util/async_read_ext.rs, tokio/src/lib.rs, tokio/src/net/mod.rs, tokio/src/net/tcp/stream.rs, tokio/src/park/thread.rs, tokio/src/runtime/mod.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/task/blocking.rs, tokio/src/task/harness.rs, tokio/src/task/spawn.rs, tokio/src/time/delay_queue.rs, tokio/src/time/driver/mod.rs, tokio/src/util/slab/tests/loom_slab.rs
Fix documentation to improve readability.
Fixed links and unnecessary spaces.
=> doc: Documentation fixes

tokio/src/runtime/current_thread/runtime.rs
The `CurrentThread` runtime's `Handle` is different than the `CurrentThread` executor's `Handle`. This causes interoperability issues with custom runtimes that build on the `CurrentThread` executor.
Actix-rt offers a concrete example of the issue: [`System::run_in_executor`](https://docs.rs/actix-rt/0.2.6/actix_rt/struct.System.html#method.run_in_executor) requires a `CurrentThread` executor handle - the change in this PR allows a `CurrentThread` runtime to be used here.
This PR adds `fn into_inner(self)` on the runtime `Handle` that consumes it and returns the underlying `CurrentThread` executor's `Handle`.
=> v0.1.x: Expose CurrentThread runtime's executor handle

tokio/src/net/unix/ucred.rs
Fixes an incorrect import.
In order to run the test suite successfully on illumos I had to modify
- generator-rs => Xudong-Huang/generator-rs/pull/16
- mio-uds => Not yet fixed (we don't appear to have a way to set `FIOCLEX` on the fds in question)
However, once I patched those via `[patchs.crates-io]` in the workspace the test suite runs to completion with:
`test result: ok. 129 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out`
=> Fix ucred for illumos/solaris

tokio-executor/CHANGELOG.md, tokio-executor/Cargo.toml, tokio-executor/README.md, tokio-executor/src/global.rs, tokio-executor/src/lib.rs, tokio-reactor/CHANGELOG.md, tokio-reactor/Cargo.toml, tokio-reactor/README.md, tokio-reactor/src/lib.rs, tokio-timer/CHANGELOG.md, tokio-timer/Cargo.toml, tokio-timer/README.md, tokio-timer/src/clock/clock.rs, tokio-timer/src/lib.rs, tokio-timer/src/timer/handle.rs
- `set_default`, which functions like `with_default` but returns a drop
guard (#1725)
- Add `executor::set_default` which behaves like `with_default` but returns a
drop guard (#1725).
- `timer::set_default`, which functions like `timer::with_default`, but
returns a drop guard (#1725).
- `clock::set_default`, which functions like `clock::with_default`, but
returns a drop guard (#1725).
=> v0.1.x: prepare to release new reactor, executor, and timer

tokio/src/task/local.rs
It turns out that the `Scheduler::release` method on `LocalSet`'s
`Scheduler` *is* called, when the  `Scheduler` is dropped with tasks
still running. Currently, that method is `unreachable!`, which means
that dropping a `LocalSet` with tasks running will panic.
This commit fixes the panic, by pushing released tasks to
`pending_drop`. This is the same as `BasicScheduler`.
I've also added a test that reproduces the panic. The test fails
against master.
Fixes #1842
=> task: fix panic when dropping `LocalSet`

tokio/src/fs/file.rs
In version 0.1 there was File::into_std method that destructured
tokio_fs::File into std::fs:File. That method was lacking in
version 0.2.
Fixes: #1852
=> fs: add File::into_std and File::try_into_std methods

tokio/src/runtime/builder.rs
=> docs: Mention features for basic_scheduler, threaded_scheduler

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/global.rs, tokio/tests/fs.rs, tokio/tests/rt_common.rs, tokio/tests/task_blocking.rs
The "global executor" thread-local is to track where to spawn new tasks,
**not** which scheduler is active on the current thread. This fixes a
bug with scheduling tasks on the basic_scheduler by tracking the
currently active basic_scheduler with a dedicated thread-local variable.
Fixes: #1851
=> rt: fix `basic_scheduler` notification bug

ci/azure-loom.yml, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
Steps taken:
- Path dependencies have been removed, no changes have been made to those crates since the last release
- Ran `bin/publish --dry-run tokio 0.2.2`
- Nothing else to do here, the other `tokio-*` crates have not had any other releases
- No breaking changes present
=> chore: prepare v0.2.2 release

tokio/src/sync/mpsc/bounded.rs
Includes more description, lists errors, and examples.
Closes #1579
=> doc: expand `mpsc::Sender::send` API documentation

tokio/src/io/util/async_buf_read_ext.rs
Remove "old" docs that were left over during a rewrite, add examples and
additional details.
=> doc: improve AsyncBufReadExt API documentation

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/read_int.rs, tokio/src/io/util/write_int.rs
Provide convenience methods for encoding and decoding big-endian numbers
on top of asynchronous I/O streams. Only primitive types are provided
(24 and 48 bit numbers are omitted).
In general, using these methods won't be the fastest way to do
encoding/decoding with asynchronous byte streams, but they help to get
simple things working fast.
=> io: read/write big-endian numbers

tokio/tests/process_issue_42.rs
The process_issue_42 test has been updated/refactored multiple times since its existence, and was a bit hard to follow (and potentially racy when running in the CI).
This change rewrites the test to be more straightforward, and using the current APIs. The outcome is largely the same as before, except the test iterations are performed in parallel, and we do not enforce dropping the runtime (which used to be a source of bugs in the distant past).
=> process: rewrite and simplify the issue_42 test

tokio/src/sync/oneshot.rs
`oneshot::Receiver::try_recv` does not provide any information as to the
reason **why** receiving failed. The two cases are that the channel is
empty or that the channel closed.
`TryRecvError` is changed to be an enum of those two cases. This is
backwards compatible as `TryRecvError` was an opaque struct.
This also expands on `oneshot` API documentation, adding details and
examples.
Closes #1872
cc @bIgBV
=> sync: expand oneshot docs and `TryRecvError`

tokio/src/runtime/blocking/pool.rs, tokio/tests/rt_common.rs
The task handle needs to be shutdown explicitly and not dropped.
Closes #1853
=> blocking: fix `spawn_blocking` after shutdown

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/read_buf.rs, tokio/src/io/util/write.rs, tokio/src/io/util/write_buf.rs
Adds `read_buf` and `write_buf` which work with `T: BufMut` and `T: Buf`
respectively. This adds an easy API for using the buffer traits provided
by `bytes.
=> io: add async fns for reading / writing bufs

tokio/src/task/local.rs
Currently, `tokio::task::LocalSet`'s `block_on` method requires the
future to live for the 'static lifetime. However, this bound is not
required — the future is wrapped in a `LocalFuture`, and then passed
into `Runtime::block_on`, which does _not_ require a `'static` future.
This came up while updating `tokio-compat` to work with version 0.2. To
mimic the behavior of `tokio` 0.1's `current_thread::Runtime::run`, we
want to be able to have a runtime block on the `recv` future from an
mpsc channel indicating when the runtime is idle. To support `!Send`
futures, as the old `current_thread::Runtime` did, we must do so inside
of a `LocalSet`. However, with the current bounds, we cannot await an
`mpsc::Receiver`'s `recv` future inside the `LocalSet::block_on` call.
This branch removes the …
=> task: relax 'static bound in `LocalSet::block_on`

tokio/tests/fs_file.rs
Add unit tests for `tokio::File::AsRaw{Fd,Handle}` for Unix and Windows.
Supersedes #1640.
=> Add unit tests for tokio::File::AsRaw{Fd,Handle} for Unix and Windows.

tokio/src/task/mod.rs
Fixes a very minor spelling mistake in the docs for Task module.
=> Fixing minor spelling mistake in task docs

tokio/src/task/error.rs, tokio/src/task/harness.rs
This is a fix for #1883.
Box and Mutex add overhead but they work and since it's not happy path, I figured they should suffice.
=> Make JoinError Sync

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/mod.rs, tokio/src/task/local.rs, tokio/src/task/mod.rs, tokio/src/task/queue.rs
There's currently an issue in `task::LocalSet` where dropping the local
set can result in an infinite loop if a task running in the local set is
notified from outside the local set (e.g. by a timer). This was reported
in issue #1885.
This issue exists because the `Drop` impl for `task::local::Scheduler`
does not drain the queue of tasks notified externally, the way the basic
scheduler does. Instead, only the local queue is drained, leaving some
tasks in place. Since these tasks are never removed, the loop that
continues trying to cancel tasks until the owned task list is totally
empty continues infinitely.
I think this issue was due to the `Drop` impl being written before a
remote queue was added to the local scheduler, and the need to close the
remote queue as well was overlooked.
This …
=> task: fix infinite loop when dropping a `LocalSet`

tokio-threadpool/CHANGELOG.md, tokio-threadpool/Cargo.toml, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs
- Internal APIs for overriding blocking behavior (#1752)
=> v0.1.x: prepare to release tokio-threadpool 0.1.17

tokio/src/time/driver/entry.rs, tokio/src/time/driver/handle.rs, tokio/src/time/driver/mod.rs
#1800 removed the lazy binding of `Delay`s to timers. With the removal of the
logic required for that, `HandlePriv` is no longer needed. This PR removes the
use of `HandlePriv`.
A `TODO` was also removed that would panic if when registering a new `Delay`
the current timer handle was full. That has been fixed to now immediately
transition that `Delay` to an error state that can be handled in a similar way
to other error states.
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
=> time: Remove `HandlePriv`

tokio/src/task/local.rs
Currently, a `LocalSet` does not notify the `LocalFuture` again at the
end of a tick. This means that if we didn't poll every task in the run
queue during that tick (e.g. there are more than 61 tasks enqueued),
those tasks will not be polled.
This commit fixes this issue by changing `local::Scheduler::tick` to
return whether or not the local future needs to be notified again, and
waking the task if so. I've also added a test that reproduces this.
Thanks @carllerche for figuring this out!
Fixes #1899
Fixes #1900
=> task: fix `LocalSet` failing to poll all local futures

tokio/src/process/mod.rs
Hovering on `spawn()` with rust-analyzer showed me weird markdown.
Fix it.
=> Close markdown

tokio/src/net/tcp/listener.rs
The `process_socket` is hidden from the user which makes the example
fail to compile if copied by the reader.
=> doc: fix TcpListener example to compile

tokio/src/sync/mutex.rs, tokio/tests/sync_mutex.rs
It is possible to leave a mutex in a locked state even if no future exists holding the lock.
- create Mutex
- lock Mutex
- try to lock mutex in another future that is aborted (e.g. via timeout)
- unlock Mutex
- locking the mutex again fails
I think this should be considered a critical issue as it can be exploited as shown in issue #1898 when using hyper and aborting requests.
=> Fix issue #1898 - Permit::release() must be called when Mutex::lock() is aborted even if it is in the Waiting state

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
=> chore: prepare v0.2.4 release

tokio/src/sync/mutex.rs
When porting code from `std::sync::Mutex` to `tokio::sync::Mutex` I noticed that the `lock()` method does not return a result anymore.
After a quick discussion in the #tokio-users discord channel, @sfackler confirmed that this mutex implementation does not poison the mutex on panic. That's probably a good default choice, but should be documented.
I added a note about the panic behavior to the `Mutex` rustdocs.
=> sync::Mutex: Add note about the absence of poisoning

tokio/src/sync/mutex.rs
Fix typo introduced in #1933 and noticed by @cynecx :slightly_smiling_face:
=> sync::Mutex: Fix typo in documentation

tokio/src/task/spawn.rs
`task::spawn` docs say tasks passed to spawn must implement `!Send` when it should be `Send`
=> fix spawn function documentation

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/error.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/mutex.rs, tokio/tests/sync_mpsc.rs, tokio/tests/sync_mutex.rs
- `Mutex::try_lock` is missing
- `Receiver::try_recv` is missing
- `UnboundedReceiver::try_recv` is missing
This makes it (a) impossible to use tokio mutexes and channels in sync code and (b) implement async code that should try to lock/recv and not block.
- Add `Mutex::try_lock` + unit test
- Add `Receiver::try_recv` + unit test
- Add `UnboundedReceiver::try_recv` + unit test
Most of the doc strings were taken 1:1 from `std` and and just adopted to match tokio naming conventions. If this is a problem I can rephrase them in my own words. I think it should be no problem though as the `std` is dual licensed under MIT and Apache License.
=> Add Mutex::try_lock and (Unbounded)Receiver::try_recv

tokio/src/fs/file.rs, tokio/src/io/async_seek.rs, tokio/src/io/mod.rs, tokio/src/io/seek.rs, tokio/src/io/util/async_seek_ext.rs, tokio/src/io/util/mod.rs, tokio/src/prelude.rs
We want to have a trait for seeking, since there's more than one object you might want to seek. This PR implements it for `File` and `Cursor`, and there are clients with their own seekable objects.
This is a tweaked version of <https://github.com/tokio-rs/tokio/pull/1641>, with the code changed to use two functions instead of one, as requested in <https://github.com/tokio-rs/tokio/pull/1641#issuecomment-541333091>.
The purpose behind using two functions is, essentially, to make the interface less fragile. If `start_seek` returns Pending, then that means nothing has happened yet. Otherwise, it has. This rule, that Pending means no side effects, is a common convention throughout Tokio's low-level API.
The function that retrieves the result, `poll_complete`, is the same way.
cc #1256
Closes …
=> io: add AsyncSeek trait

README.md, tokio/README.md, tokio/src/lib.rs
The example in `tokio/README.md` is outdated
Keep the examples in sync in `README.md`, `tokio/README.md` and `tokio/lib.rs`.
Closes: #1919
=> Fix the outdated example in tokio/README.md

tokio-util/tests/framed_read.rs
`bytes` added a warning when using a fn that resulted in a useless clone.
=> chore: fix warning in tokio-util tests

tokio/Cargo.toml, tokio/src/net/tcp/split.rs, tokio/src/net/tcp/stream.rs
While we still use a version of `mio` that uses `iovec` instead of `IoSlice`, we can support `writev` by converting the `IoSlice` into `IoVec`s.
=> Re-enable writev support in TcpStreams

tokio/src/time/mod.rs, tokio/src/time/throttle.rs, tokio/tests/time_throttle.rs
This PR upgrades the throttle combinator to use pin-project-lite and reintroduces it with API akin to `timeout`.
=> Fix and reintroduce Throttle combinator

tokio/src/runtime/basic_scheduler.rs, tokio/src/task/local.rs, tokio/src/task/queue.rs, tokio/tests/rt_basic.rs, tokio/tests/task_local_set.rs
Calls to tasks should not be nested. Currently, while a task is being
executed and the runtime is shutting down, a call to wake() can result
in the wake target to be dropped. This, in turn, results in the drop
handler being called.
If the user holds a ref cell borrow, a mutex guard, or any such value,
dropping the task inline can result in a deadlock.
The fix is to permit tasks to be scheduled during the shutdown process
and dropping the tasks once they are popped from the queue.
Fixes #1929, #1886
This only fixes single threaded schedulers. I have net yet reproduced the bug in
the threaded scheduler but will continue to explore.
=> rt: avoid dropping a task in calls to wake()

tokio/src/time/delay_queue.rs
8a7e57786a5dca139f5b4261685e22991ded0859 deleted `impl Stream for DelayQueue`. It also said
>   Since the `Stream` implementation is optional, types that are logically
>   streams provide `async fn next_*` functions to obtain the next value.
>   Avoiding the `next()` name prevents fn conflicts with `StreamExt::next()`.
However, `DelayQueue` only provided `poll_expired`, which makes `DelayQueue` almost unusable in `async` contexts.
This PR implements `Stream` on `DelayQueue` behind the feature flag `stream`, which is only a few characters away from the origin implementation that existed before 8a7e57786a5dca139f5b4261685e22991ded0859.
---
If a test is useful for this contribution, or any changes are needed, please let me know. I'm unsure what kind of test to implement for this, so a …
=> impl Stream for DelayQueue

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/tests/loom_blocking.rs, tokio/src/runtime/tests/mod.rs
The blocking task queue was not explicitly drained as part of the
blocking pool shutdown logic. It was originally assumed that the
contents of the queue would be dropped when the blocking pool structure
is dropped. However, tasks must be explictly shutdown, so we must drain
the queue can call `shutdown` on each task.
Fixes #1970, #1946
=> rt: fix blocking pool shutdown logic

tokio/src/runtime/blocking/mod.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/tests/loom_blocking.rs, tokio/src/runtime/thread_pool/tests/loom_pool.rs, tokio/tests/rt_threaded.rs
User might want to configure cap on blocking pool
Add option to runtime and propagate it to blocking pool, upon creating it.
Changes to configuration:
- Max thread num - specifies limit on threads, spawned by runtime
- Core thread num - number of active threads, always in use by runtime.
Blocking threads will be `max - core`
=> Introduce configuration options to control core and max threads

tokio/src/sync/mutex.rs
As there is currently only one variant, make the error type an opaque
struct.
cc @bikeshedder
=> sync: encapsulate TryLockError variants

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
Also includes:
- `tokio-macros` v0.2.1
=> chore: prepare v0.2.5 release

examples/connect.rs
example had a run function which was spawned from main function with a  oneshot channel to await it's end, due to #1356. 
Since #1356 has been addressed, that is no longed needed
removed run function and moved it's code into the main function, also removed implementation of a bytes coded in favor of `tokio_util::codec::BytesCodec`
=> update connect example

ci/azure-clippy.yml, tokio/src/fs/file.rs
This fixes an API compatibility regression when `AsyncSeek` was added.
Fixes: #1989
=> fs: add deprecated fs::File::seek fn

tokio/src/stream/filter.rs, tokio/src/stream/filter_map.rs, tokio/src/stream/mod.rs
This PR adds `StreamExt::filter` and `StreamExt::filter_map` which allow filtering and mapping items yielded by the wrapped stream.
Unlike the version in #1962 combinators presented here accept *synchronous* predicates which do immediate check upon receiving items from inner stream. The necessity and design of versions for asynchronous predicate is a subject of a further discussion.
=> Stream filtering facilities

tokio/src/stream/mod.rs, tokio/src/stream/try_next.rs
This PR adds `StreamExt::try_next` combinator that allows for easy usage of try operator while iterating upon fallible streams. The key difference between `futures-rs` implementation and this one is that we are going to have this method as a part of the main stream extensions, not separate `TryStreamExt`.
=> Implement StreamExt::try_next

tokio/src/sync/broadcast.rs, tokio/tests/sync_broadcast.rs
The broadcast `Receiver` doesn't have a `Stream` impl.
Implement `Stream` for `broadcast::Receiver`
=> Implement `Stream` for broadcast::Receiver

tokio/src/time/delay_queue.rs
Some commits for unimplemented things in the `DelayQueue`.
Sometimes it's useful to keep track of how many items we still have in the queue.
~~I'm not sure that this is a correct implementation, cfr #1754, and I'll gladly change the commit to reflect any other needed change.~~ Change removed
=> DelayQueue::len

tokio/src/fs/canonicalize.rs, tokio/src/fs/create_dir.rs, tokio/src/fs/create_dir_all.rs, tokio/src/fs/file.rs, tokio/src/fs/hard_link.rs, tokio/src/fs/metadata.rs, tokio/src/fs/mod.rs, tokio/src/fs/open_options.rs, tokio/src/fs/os/unix/symlink.rs, tokio/src/fs/os/windows/symlink_dir.rs, tokio/src/fs/os/windows/symlink_file.rs, tokio/src/fs/read.rs, tokio/src/fs/remove_file.rs, tokio/src/io/stderr.rs, tokio/src/io/util/copy.rs, tokio/src/net/mod.rs, tokio/src/park/mod.rs, tokio/src/park/thread.rs, tokio/src/process/mod.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/mod.rs, tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/mod.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/time/driver/mod.rs, tokio/src/time/mod.rs
Switch to rustdoc path links instead of relative HTML links.
This also fills out `tokio::fs` API documentation.
Work towards #1473
=> doc: fill out `fs` and remove html links

tokio/src/park/mod.rs, tokio/src/park/thread.rs, tokio/src/runtime/blocking/shutdown.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/thread_pool/mod.rs, tokio/tests/rt_common.rs
Storing a `Runtime` value in a thread-local resulted in a panic due to
the inability to access the parker.
This fixes the bug by skipping parking if it fails. In general, there
isn't much that we can do besides not parking.
=> rt: fix storing Runtime in thread-local

tokio/src/stream/mod.rs, tokio/src/stream/take.rs
This PR introduces `StreamExt::take` combinator with an interface similar to the classic sync `Iterator::take` from `core`.
=> Add StreamExt::take

tokio/src/stream/filter.rs, tokio/src/stream/filter_map.rs, tokio/src/stream/map.rs, tokio/src/stream/mod.rs, tokio/src/stream/next.rs, tokio/src/stream/take.rs, tokio/src/stream/take_while.rs, tokio/src/stream/try_next.rs, tokio/src/time/tests/mock_clock.rs
This PR introduces `StreamExt::take_while` combinator which takes a predicate which inspects every yielded item and, when returns false, terminates the stream early.
Also this PR removes trait bounds for other combinator structs' constructors as they are essentially duplicates of those of `StreamExt` combinators and `Stream` impls.
=> Add StreamExt::take_while, other tweaks incl. clippy

tokio-macros/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs
This PR contains general refactoring of `#[tokio::main]` and `#[tokio::test]` macros along with additional `core_threads` and `max_threads` knobs.
Note: `core_threads` knob sets the runtime to `threaded` or `basic` depending on the value. Current `threaded_scheduler` and `basic_scheduler` knobs are only retained for compatibility with existing code and are overridden if `core_threads` is set.
=> Refactor proc macros, add more knobs

tokio/src/stream/mod.rs
This is a follow up to #2035 as suggested in post-merge review comments.
=> stream: correct trait bounds for all

tokio/src/sync/broadcast.rs
Update documentation to match implementation.
Remove incorrect references to cloning `Receiver` structs. Also mention that `Sender` and `Receiver` are both `Send` and `Sync`. Before, the documentation only mentioned that `Sender` is `Sync`. Both structs have the `Sync` marker trait. It seemed useful to mention that both structs are also `Send` in the same place.
Fixes: #2032
=> tokio: remove documentation stating `Receiver` is clone-able.

tokio/src/io/split.rs, tokio/src/net/unix/ucred.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/mod.rs, tokio/src/sync/mpsc/error.rs, tokio/src/sync/oneshot.rs, tokio/src/sync/semaphore_ll.rs, tokio/src/sync/watch.rs, tokio/tests/rt_common.rs, tokio/tests/sync_errors.rs
It was a long time ago one had to write `::std` to make rustc recognize the path. Now just `std` works fine. It's both shorter and easier to read.
=> use just std instead of ::std in paths

tests-integration/tests/process_stdio.rs, tokio/src/process/mod.rs, tokio/tests/process_kill_on_drop.rs
The current strategy of accessing `Child` stdio handles via accessors does not allow for mutably borrowing over multiple stdio handles.
Deprecate stdio accessors in favor of public fields. The `Child` struct still has a private member, so we can add additional fields without breaking changes
Fixes #2009
=> process: deprecate Child stdio accessors in favor of pub fields

tokio/src/task/harness.rs, tokio/src/task/tests/task.rs, tokio/src/task/waker.rs
The `Waker::will_wake` compares both a data pointer and a vtable to
decide if wakers are equivalent. To avoid false negatives during
comparison, use the same vtable for a waker stored in `WakerRef`.
=> share vtable between waker and waker ref

tokio/src/task/queue.rs, tokio/tests/rt_basic.rs
I'm hoping this fixes https://github.com/seanmonstar/reqwest/issues/746
=> Fix basic_scheduler deadlock when waking during drop

tokio/src/io/async_buf_read.rs, tokio/src/io/async_seek.rs, tokio/src/io/async_write.rs, tokio/src/io/split.rs, tokio/src/io/stderr.rs, tokio/src/io/stdin.rs, tokio/src/io/stdout.rs, tokio/src/io/util/async_buf_read_ext.rs, tokio/src/io/util/copy.rs, tokio/src/io/util/empty.rs, tokio/src/io/util/repeat.rs, tokio/src/io/util/sink.rs
This PR adds a whole lot of links to the `tokio::io` module, adds examples to stdout and stderr, and refactors some of the examples on the top-level functions.
=> Documentation improvements for tokio::io

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
Brings back old macro implementations and updates the version of
tokio-macros that tokio depends on.
=> macros: fix breaking changes

tokio/src/fs/file.rs, tokio/src/io/seek.rs, tokio/src/io/util/async_seek_ext.rs
This is the case with `Cursor`, for example.
EDIT: This is also the case with `File` if it is not already busy.
=> io: fix 'Seek::poll' when the underlying 'AsyncRead::start_seek' call immediately returns Ready.

tokio/src/runtime/thread_pool/worker.rs, tokio/tests/rt_basic.rs, tokio/tests/rt_common.rs
Previously, if an IO event was received during the runtime shutdown
process, it was possible to enter a deadlock. This was due to the
scheduler shutdown logic not expecting tasks to get scheduled once the
worker was in the shutdown process.
This patch fixes the deadlock by checking the queues for new tasks after
each call to park. If a new task is received, it is forcefully shutdown.
Fixes #2061
=> rt: fix threaded scheduler shutdown deadlock

tokio/src/runtime/thread_pool/queue/global.rs, tokio/src/runtime/thread_pool/tests/loom_pool.rs
Previously, when the threaded scheduler was in the shutdown process, it
would hold a lock while dropping in-flight tasks. If those tasks
included a drop handler that attempted to wake a second task, the wake
operation would attempt to acquire a lock held by the scheduler. This
results in a deadlock.
Dropping the lock before dropping tasks resolves the problem.
Fixes #2046
=> rt: fix shutdown deadlock in threaded scheduler

tokio/src/signal/unix.rs
Minor errors in document
This PR fixes a typo and a reference to the archived repository.
=> docs: fix typo and issue reference

tokio/src/task/state.rs
Previously acquire operations reading a value written by a successful
CAS in `drop_join_handle_fast` did not synchronize with it. The CAS
wasn't guaranteed to happen before the task deallocation, and so
created a data race between the two.
Use release success ordering to ensure synchronization.
=> use release ordering in `drop_join_handle_fast`

tokio/src/runtime/mod.rs
With the rt-threaded feature flag we create a threaded scheduler by
default. The documentation had a copy-and-paste error from the section
about the basic scheduler.
=> fix documentation about created runtimes in tokio::runtime

tokio/src/stream/fuse.rs, tokio/src/stream/mod.rs, tokio/tests/stream_fuse.rs
Provides an async equivalent to `Iterator::fuse`.
=> stream: add `StreamExt::fuse`

tokio/src/sync/rwlock.rs
Having these two convenience traits implemented for RwLock like they are for Mutex is useful.
=> sync: Implement From<T> and Default where T: Default for RwLock

tokio-codec/README.md, tokio-executor/README.md, tokio-fs/README.md, tokio-reactor/README.md, tokio-signal/README.md, tokio-sync/README.md, tokio-tcp/README.md, tokio-threadpool/README.md, tokio-timer/README.md, tokio-udp/README.md, tokio-uds/README.md
Add deprecation notices to `0.1.x` crates who's functionality is now owned by the main `tokio` crate.
=> Add deprecation notices for outdated crates (#2036)

tokio/src/stream/merge.rs, tokio/src/stream/mod.rs, tokio/tests/stream_merge.rs
Provides an equivalent to stream `select()` from futures-rs. `merge`
best describes the operation (vs. `select`). `futures-rs` named the
operation "select" for historical reasons and did not rename it back to
`merge` in 0.3. The operation is most commonly named `merge` else where
as well (e.g. ReactiveX).
=> stream: add `StreamExt::merge`

tokio/src/stream/empty.rs, tokio/src/stream/mod.rs, tokio/src/stream/pending.rs, tokio/tests/stream_empty.rs, tokio/tests/stream_pending.rs
`stream::empty()` is the asynchronous equivalent to
`std::iter::empty()`. `pending()` provides a stream that never becomes
ready.
=> stream: add `empty()` and `pending()`

tokio/src/stream/mod.rs, tokio/src/stream/once.rs, tokio/tests/stream_once.rs
An async equivalent to `iter::once`
=> stream: add stream::once

tokio-process/CHANGELOG.md, tokio-process/Cargo.toml, tokio-process/LICENSE, tokio-process/README.md, tokio-process/src/bin/cat.rs, tokio-process/src/bin/exit.rs, tokio-process/src/kill.rs, tokio-process/src/lib.rs, tokio-process/src/unix/mod.rs, tokio-process/src/unix/orphan.rs, tokio-process/src/unix/reap.rs, tokio-process/src/windows.rs, tokio-process/tests/issue_42.rs, tokio-process/tests/smoke.rs, tokio-process/tests/stdio.rs, tokio-process/tests/support/mod.rs
This re-incorporates `tokio-process` as it was a included before by @ipetkov, with a deprecation warning added by me as per #2036.
This does include an edition bump for `0.2.4`, which we might want to revert unless we want to bump the minor version of `tokio-process` (or maybe an edition bump is fine?). I personally wouldn't mind bumping the minor version, but if anyone else objects I'll add the revert to this PR.
=> Merge tokio-process into v0.1.x

tokio/src/io/util/buf_stream.rs
This is a bad bound, as per #2064 and #2106.
Relaxing this bound might in theory have unintended side effects that would warrant a major release (like in certain blanket impls), but since this makes `BufStream` practically unusable that might not matter.
=> io: Drop AsyncBufRead bound on BufStream impl (fixes #2064, #2106)

tokio/src/net/addr.rs, tokio/src/stream/collect.rs, tokio/src/stream/mod.rs, tokio/tests/stream_collect.rs
Provides an asynchronous equivalent to `Iterator::collect()`. A sealed
`FromStream` trait is added. Stabilization is pending Rust supporting
`async` trait fns.
=> stream: add `StreamExt::collect()`

Cargo.toml, azure-pipelines.yml, tokio-process/src/windows.rs
The `v0.1.x` branch doesn't have it's CI configured to build and test the `tokio-process` crate.
Add `tokio-process` to the list of crates to build
=> v0.1.x: ci: test `tokio-process`

tokio-buf/README.md, tokio-buf/src/lib.rs, tokio-codec/README.md, tokio-codec/src/lib.rs, tokio-current-thread/README.md, tokio-current-thread/src/lib.rs, tokio-io/README.md, tokio-io/src/lib.rs, tokio-reactor/README.md, tokio-reactor/src/lib.rs, tokio-signal/README.md, tokio-signal/src/lib.rs, tokio-sync/README.md, tokio-sync/src/lib.rs, tokio-tcp/README.md, tokio-tcp/src/lib.rs, tokio-threadpool/README.md, tokio-threadpool/src/lib.rs, tokio-timer/README.md, tokio-timer/src/lib.rs, tokio-udp/README.md, tokio-udp/src/lib.rs, tokio-uds/README.md, tokio-uds/src/lib.rs
`tokio-buf` and `tokio-current-thread` appear to have straight up been deprecated. It would be nice to add a notice on what to use instead for current thread (`futures::executor::block_on` is an alternative), but I'm not sure what to do.
Using the basic scheduler works, but is somewhat awkard:
```rust
let mut rt = tokio::runtime::Builder::new().basic_scheduler().enable_all().build()?;
let set = tokio::task::LocalSet::new();
let result = set.block_on(&mut rt, /* future */);
```
=> More deprecation notices (relates #2036)

ci/azure-clippy.yml, tokio/src/stream/collect.rs, tokio/tests/stream_collect.rs
A follow up to #2110. I don't know why but this lint only popped up in VS code after the last PR got merged.
I also dropped the special instructions from Azure pipeline definitions since we use targeted whitelisting anyway.
=> chore: minor fixes

tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs
There is currently no way to conditonnally determine whether `tokio::spawn` will succeed.
Since this is a niche situation, I went for putting a method on the lower-level component.
=> runtime: add Handle::try_current

tokio/src/task/mod.rs, tokio/src/task/yield_now.rs
Based on a [URLO thread](https://users.rust-lang.org/t/blocking-permit/36865/7) and discord conversation with @hawkw and @Matthias247, I learned a great deal about what `tokio::task::yield_now` does, noticing that the rustdoc for that method can be improved.
rustdoc-o
=> Yield now docs

tokio/src/io/util/buf_stream.rs
Currently it's not possible to configure the buffer size when creating a `BufStream`.
I'm using `BufStream` to wrap a `TcpStream` and having to`tokio::io::split` it and pass each half to `BufReader::with_capacity` and `BufWriter::with_capacity` seems sub-optimal.
This PR adds a `BufStream::with_capacity` method that takes as input both the capacity of the read buffer and the capacity of the write buffer.
Not sure if this is the best API, but it seemed more flexible than having a single capacity as input.
=> io: add `BufStream::with_capacity`

tokio/src/io/split.rs, tokio/tests/io_split.rs
This PR adds a `stream_id` function to `io::split::ReadHalf` and `io::split::WriteHalf`. The stream ID can be used to test if halfs belong to the same stream before calling `unsplit`. Additionally, the ID implements `Eq`, `Ord` and `Hash`, so it can be used as a key in associative containers.
My direct motivation for this is that I want to remove the write half from a container when the read half is closed in a server application with independent read and write loops.
=> Add a method to test if split streams come from the same stream.

tokio/Cargo.toml
It looks like the `generator` crate is not compiling on windows. This crate
is only used as part of `loom`. For now, restrict `loom` to non-windows
platforms.
=> chore: only depend on loom when not windows

tokio/src/io/async_read.rs, tokio/tests/io_read.rs
`AsyncRead` is safe to implement but can be implemented so that it
reports that it read more bytes than it actually did. `poll_read_buf` on
the other hand implicitly trusts that the returned length is actually
correct which makes it possible to advance the buffer past what has
actually been initialized.
An alternative fix could be to avoid the panic and instead advance by
`n.min(b.len())`
=> fix: Prevent undefined behaviour from malicious AsyncRead impl

azure-pipelines.yml, ci/azure-test-integration.yml, tests-integration/Cargo.toml, tests-integration/src/lib.rs, tests-integration/tests/macros_main.rs, tests-integration/tests/process_stdio.rs, tokio-macros/src/entry.rs, tokio-macros/src/lib.rs, tokio/src/lib.rs
The Tokio runtime provides a "shell" runtime when `rt-core` is not
available. This shell runtime is enough to support `#[tokio::main`] and
`#[tokio::test].
A previous change disabled these two attr macros when `rt-core` was not
selected. This patch fixes this by re-enabling the `main` and `test`
attr macros without `rt-core` and adds some integration tests to prevent
future regressions.
While I was in here, I also moved the entry point macros from `lib.rs` to
`entry.rs`. This will add space for future proc macros.
=> macros: fix `#[tokio::main]` without rt-core

tokio/src/io/split.rs, tokio/tests/io_split.rs
=> io: Clean up split check

tokio/src/sync/mpsc/error.rs, tokio/src/sync/oneshot.rs
Similar to [`tokio::sync::broadcast::TryRecvError`](https://github.com/tokio-rs/tokio/blob/1475448bdfa5f0bed35abb6e3d5620a22cc27f53/tokio/src/sync/broadcast.rs#L229-L230), it will be useful if we derive `PartialEq` for other non-parametrized error types.
This PR will allow us to check inequality of `try_recv` results like below:
```rust
let (_tx, mut rx) = mpsc::channel::<()>(1);
if rx.try_recv() != Err(mpsc::error::TryRecvError::Closed) {
...
}
```
just derive `PartialEq` for `mpsc::error::TryRecvError` and `oneshot::TryRecvError`.
=> sync: derive PartialEq for error enums

tokio/src/runtime/thread_pool/worker.rs, tokio/src/task/blocking.rs
This is a very small change to enhance the documentation of `tokio::task::block_in_place` with a Note, and also a change to the error message when the runtime panics because unable to run `tokio::task::block_in_place` from a not spawned task.
The previous error message was slightly misleading when stating that the error was due to being unable to call `tokio::task::block_in_place` because not running on the Tokio runtime.
=> Enhance documentation of tokio::task::block_in_place

tokio-macros/src/entry.rs
The attributes were accidentally copied to a sub module file.
=> macros: remove unused attributes

tokio/src/lib.rs
Replace website link in tokio documentation 
Previous website link in documentation was broken
Replacement of link
=> docs: fix link to website

tokio/src/net/tcp/split.rs, tokio/src/net/tcp/stream.rs, tokio/tests/tcp_split.rs
Closes #2136
The `&mut self` requirements for `TcpStream` methods ensure that there are at
most two tasks using the stream--one for reading and one for writing.
`TcpStream::split` allows two separate tasks to hold a reference to a single
`TcpStream`. `TcpStream::{peek,poll_peek}` only poll for read readiness, and
therefore are safe to use with a `ReadHalf`.
Instead of duplicating `TcpStream::poll_peek`, a private method is now used by
both `poll_peek` methods that uses the fact that only a `&TcpStream` is
required.
Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>
=> net: Add `ReadHalf::{peek,poll_peak}`

tests-integration/Cargo.toml, tests-integration/tests/macros_select.rs, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio-macros/src/select.rs, tokio/src/future/mod.rs, tokio/src/future/poll_fn.rs, tokio/src/lib.rs, tokio/src/macros/mod.rs, tokio/src/macros/select.rs, tokio/src/macros/support.rs, tokio/src/util/mod.rs, tokio/src/util/rand.rs, tokio/tests/macros_select.rs
The `select!` operation is a key operation when writing asynchronous Rust. Up until now, the `futures` crate provided the main implementation. This PR adds a new `select!` implementation that improves on the version from `futures` in a few ways:
- Avoids needing `FusedFuture`.
- Implemented as a hybrid declarative / proc macro, avoiding `proc-macro-hack`.
The original `select!` macro requires that provided futures implement a special trait: [`FusedFuture`](https://docs.rs/futures/latest/futures/future/trait.FusedFuture.html). Unfortunately, futures returned by `async fn` do not implement `FusedFuture`, leading to the requirement of having to call `.fuse()` on futures before calling `select!`. The `FuseFuture` requirement exists to support using `select!` from within a loop.
The `select!` …
=> Provide `select!` macro

tokio/src/macros/mod.rs
Noticed this when I was building something which only used `rt-core`. The select macro was available but failed to compile since it depends on things from `support`.
This prevents that issue by only exporting select in case `macros` are enabled.
=> Don't export select unless macros is enabled

tokio/src/future/maybe_done.rs, tokio/src/future/mod.rs, tokio/src/macros/join.rs, tokio/src/macros/mod.rs, tokio/src/macros/select.rs, tokio/src/macros/support.rs, tokio/tests/macros_join.rs
Provides a `join!` macro that supports concurrently driving multiple
futures on the same task and await the completion of all futures.
Similar to #2152, this macro is implemented as a declarative macro and
recurses only once per branch.
=> future: provide join! macro

tests-integration/tests/macros_pin.rs, tokio/src/macros/mod.rs, tokio/src/macros/pin.rs, tokio/src/macros/support.rs
Used for stack pinning and based on `pin_mut!` from the pin-util crate.
Pinning is used often when working with stream operators and the select!
macro. Given the small size of `pin!` it makes more sense to include a
version than re-export one from a separate crate or require the user to
depend on `pin-util` themselves.
=> macros: add pin! macro

tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/loom/std/mod.rs, tokio/src/loom/std/sync/pl_wrappers.rs
This is a second attempt at #2130, as discussed on discord.
* The _parking_lot_ crate's `Mutex` and `Condvar` still best _libstd_ in benchmarks.  
* From Amanieu/parking_lot#119 (and linked rust-lang PR), it does not appear (AFAICT) that replacing libstd's current implementations with _parking_lot_ inspired types is particularly close to being accepted. (When that does happen and in MSRV, this PR should be easy enough to revert.)
With a non-default, not included in "full" *parking_lot* feature enabled, new `Mutex` and `Condvar` adapter types are included which bridge the parking_lot types to the std::sync interface.  Note that for compatibility, the adapters return types in the form `Result<_, *LockError>` but never actually error, because _parking_lot_ does not have poisoning. To quote …
=> parking_lot Mutex/Condvar via feature gate (take 2)

tokio/src/runtime/thread_pool/tests/loom_pool.rs
This was an attempt to reproduce the issue in #2119.
Sadly, it does not, but seems worthwhile to add anyway.
=> Test block_in_place followed by Pending

tokio/src/io/driver/mod.rs, tokio/src/time/driver/handle.rs, tokio/src/time/error.rs, tokio/tests/no_rt.rs
This PR replaces #1789
I want to preface this by saying I'm not entirely sure if these error messages are exactly accurate but I wanted to take a crack at it. 
---
Providing a more actionable error message when tokio expects to be within a runtime. Fixes #1713 
New error messages:
When there is no timer:
```
the timer is shutdown, this code must be executed from within a tokio runtime
```
When there is no reactor:
```
there is no reactor running, this code must be executed from within a tokio runtime
```
---
I'm not in love with the "this code must be executed from within a tokio runtime", not sure what the best wording there is, would love some pointers :) I'm also not sure if it's entirely accurate to say "tokio runtime" as perhaps some other runtime could be used instead.
=> fix: improves panic messages when there is no reactor/timer

tokio/src/sync/oneshot.rs
The `std` version of `RecvError` also impls these traits.
=> sync: impl equality traits for oneshot::RecvError

tokio/src/stream/mod.rs, tokio/src/stream/timeout.rs, tokio/src/time/timeout.rs, tokio/tests/stream_timeout.rs
Adds a per-item timeout to `Stream`
=> stream: add StreamExt::timeout()
