tokio-rs/tokio

tokio/src/future/maybe_done.rs, tokio/src/macros/join.rs, tokio/src/macros/mod.rs, tokio/src/macros/try_join.rs, tokio/tests/macros_join.rs, tokio/tests/macros_try_join.rs
Provides a `try_join!` macro that supports concurrently driving multiple
`Result` futures on the same task and await the completion of all the
futures as `Ok` or the **first** `Err` future.
Refs #2158, #2152
=> future: provide try_join! macro

tests-integration/tests/macros_main.rs, tokio-macros/src/entry.rs
Fixes #2176.
The solution is pretty straightforward:
Instead of `#vis fn #name(#inputs) #ret {` just writing `#vis #sig` works magic.
I also included a test.
=> macros: fix skipping generics on #[tokio::main]

azure-pipelines.yml, tokio-macros/src/lib.rs, tokio/src/time/driver/atomic_stack.rs, tokio/src/time/driver/entry.rs, tokio/src/time/wheel/level.rs
This requires fixing a few warnings.
=> chore: bump nightly version used in CI

azure-pipelines.yml, tokio/src/sync/mod.rs, tokio/src/sync/watch.rs
This includes some expected use cases for the various sync primitives.
=> docs: write sync mod API docs

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
Also bumps:
- tokio-macros: v0.2.4
=> chore: prepare v0.2.11 release

tokio/src/time/wheel/mod.rs, tokio/tests/time_delay.rs
There is an out of bounds error when attempting to set a delay of `MAX_DURATION` - 1 ms
```
delay_for(Duration::from_millis(MAX_DURATION - 1)).await;
=> panicked at 'index out of bounds: the len is 6 but the index is 6
```
The easiest way out seems to be to change `MAX_DURATION` to `MAX_DURATION - 1`.
=> fix timer out of bounds error

tokio/src/stream/pending.rs
Seems like a wrong function was used for this example.
I got a bit confused when I actually hit the unreachable block.
=> Fix pending example

CODE_OF_CONDUCT.md, CONTRIBUTING.md
May want to change the email address - I put in the one I found on @carllerche's Github page 😄
=> Improve discoverability of Code of Conduct

tokio-util/Cargo.toml, tokio-util/src/cfg.rs, tokio-util/src/compat.rs, tokio-util/src/lib.rs
This PR adds a compatibility layer with conversions between the
`tokio::io` and `futures-io` versions of the `AsyncRead` and
`AsyncWrite` traits.
I initially opened this PR against `tokio-compat`, but we decided that
a compatibility layer for current versions of the `tokio` and
`futures-io` crates (rather than for compatibility with legacy code)
ought to go in `tokio-util` instead. See:
https://github.com/tokio-rs/tokio-compat/pull/2#issuecomment-551310953
This is based on code originally written by @Nemo157 as part of the
`futures-tokio-compat` crate, and is contributed on behalf of the
original author:
https://github.com/Nemo157/futures-tokio-compat/issues/2#issuecomment-544118866
Closes tokio-rs/tokio-compat#2
Co-authored-by: Wim Looman <wim@nemo157.com>
Signed-off-by: Eliza Weisman …
=> util: add futures-io/tokio::io compatibility layer

tokio/src/macros/join.rs, tokio/src/macros/mod.rs, tokio/src/macros/select.rs, tokio/src/macros/try_join.rs
The `macros` feature flag was ommitted despite the fact that these
macros require the feature flag to function. The macros are now scoped
by the `macros` feature flag.
This is *not* a breaking change due to the fact that the macros were
broken without the `macros` feature flag in the first place.
=> macros: correctly feature gate join/try_join

tokio/src/park/thread.rs, tokio/src/runtime/blocking/mod.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/blocking/shutdown.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/mod.rs, tokio/tests/rt_common.rs
Provides an API for forcing a runtime to shutdown even if there are
still running tasks.
Fixes #1923
=> rt: add `Runtime::shutdown_timeout`

tokio/src/sync/watch.rs
The size of `watch::Receiver` was 4 words, when it could be smaller.
This reduces the `mem::size_of::<watch::Receiver>()` from 4 words to 2.
- The `id` is now the pointer of the `Arc<WatchInner>`.
- The `ver` is moved into the `WatchInner`.
=> sync: reduce memory size of watch::Receiver

tokio/src/sync/mod.rs
The "`broadcast` channel" link in the `sync` mod documentation was missing the closing `]`.
=> Fix broadcast link in sync documentation

tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/length_delimited.rs
Found two places by grepping for `split_to`
=> perf: Use advance over split_to when we don't need the data

tokio/src/stream/mod.rs, tokio/src/stream/stream_map.rs, tokio/src/util/mod.rs, tokio/src/util/rand.rs, tokio/tests/stream_stream_map.rs
`StreamMap` is similar to `StreamExt::merge` in that it combines source
streams into a single merged stream that yields values in the order that
they arrive from the source streams. However, `StreamMap` has a lot more
flexibility in usage patterns.
`StreamMap` can:
- Merge an arbitrary number of streams.
- Track which source stream the value was received from.
- Handle inserting and removing streams from the set of managed streams
at any point during iteration.
All source streams held by `StreamMap` are indexed using a key. This key
is included with the value when a source stream yields a value. The key
is also used to remove the stream from the `StreamMap` before the stream
has completed streaming.
Because the `StreamMap` API moves streams during runtime, both streams
and keys must be …
=> stream: provide `StreamMap` utility

tokio/src/time/timeout.rs
While the module documentation explains that a timed out future (as
created through the tokio::time::timeout function) is canceled, the
functions actual documentation doesn't mention that at all. This change
adds this relevant information to the documentation.
=> time: Add comment about cancelation of timed out futures

tokio-util/src/codec/bytes_codec.rs, tokio-util/src/codec/decoder.rs, tokio-util/src/codec/encoder.rs, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/lines_codec.rs, tokio-util/src/codec/mod.rs
I was made aware that the doc on `Framed` mentioned a `split` function without saying where to find it. I thought I would fix it, and added some additional links in other places too.
=> Documentation improvements to tokio-util/codec

tokio/src/stream/mod.rs, tokio/src/stream/skip_while.rs
This PR introduces `StreamExt::skip_while` as described in #2104. `skip_while` is an async version of `Iterator::skip_while` and will ignore the elements from the underlying stream until the predicate resolves `false`.
=> stream: add StreamExt::skip_while

tokio/src/runtime/blocking/mod.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/thread_pool/tests/loom_pool.rs, tokio/src/runtime/thread_pool/worker.rs
Here's roughly what happens:
- A worker has tasks in its local queue
- The worker gets given away due to `block_in_place` (using `spawn_blocking`)
- The blocking pool is shut down
- The given-away worker is dropped, rather than run
- The worker's `shutdown` method is never run
=> Add a test for #2119 and failing state assertion

tokio-tcp/README.md, tokio-tcp/src/lib.rs, tokio-udp/README.md, tokio-udp/src/lib.rs, tokio-uds/README.md, tokio-uds/src/lib.rs
Messed up some of the links. Besides, they should be linking to `tokio::net` rather than something like `tokio::net::tcp` because that is where the user facing types live, like `TcpListener` and `TcpStream`.
CC: @LucioFranco (sorry!)
=> Fix broken links to tokio::net

README.md
The current link to tokio.rs/docs 404's.  This change redirects the "guides" link to the docs overview (which may be what was intended).
I'm not a fan of links that 404 in documentation.  I have forked the repo, issued a pull request and live in hope that it is pulled.
If the link that I have suggested is not the correct link, feel free to close this pull request and provide the correct url.   Back and forth for something this simple is not required.
Thank you.
=> Correct link to the guide on tokio.rs

tokio-macros/src/lib.rs
thx for all your hard work on this crate!! been really fantastic using it
the spelling of `enviornment ` is wrong
i fixed the spelling
=> Fix doc comment spelling in lib.rs

tokio/src/io/driver/mod.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/util/bit.rs, tokio/tests/rt_basic.rs, tokio/tests/tcp_accept.rs
See #2222.
This adds a test that replicates the issue (the I/O one; the channel one does not exhibit the issue). It then also introduces a fix by removing the (in theory) extraneous call to `wake()` in `io::Driver::register`.
=> Test and avoid replicate unnecessary polling over I/O futures

tokio/src/net/unix/stream.rs, tokio/tests/uds_stream.rs
This brings `UnixStream::poll_shutdown` in line with `TcpStream::poll_shutdown`.
=> UnixStream::poll_shutdown is not a no-op

tokio/src/sync/mutex.rs
Add `Mutex::into_inner` method that consumes mutex
and return underlying value.
I'm not sure what to test here, so I didn't add any tests.
Fixes #2211
There are cases when you need to get ownership over the underlying value.
Also, both [`std::sync::Mutex`][stdm] and [`futures::sync::Mutex`][fm] have the methods `into_inner` that allow you to consume the mutex and get the owned value from it.
[stdm]: https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.into_inner
[fm]: https://docs.rs/futures/0.3.1/futures/lock/struct.Mutex.html#method.into_inner
Add `into_inner` method for `sync::Mutex`  that simply calls `into_inner` on inner `UnsafeCell`
=> Add `Mutex::into_inner` method

tokio/src/time/instant.rs
The added derived traits mirror the traits of std::time::Instant. As
tokio::time::Instant is just a wrapper around std::time::Instant, it
should also derive all the traits std::time::Instant derives.
tokio::time::Instant is just a wrapper around std::time::Instant, as such it should
behave just like std::time::Instant. That should include what kind of
traits it derives.
Just added the same derived traits as std::time::Instant
=> Added Ord and Hash as derived traits for tokio::time::Instant

tokio/src/sync/rwlock.rs
Currently, the documentation for `tokio::sync::RwLock` states that it
has an unspecified priority policy dependent on the operating system.
This is incorrect: Tokio's `RwLock` is fairly queued. The incorrect
documentation appears to have been copied from the `std::sync::RwLock`
docs, for which this *is* the case.
In addition, the `tokio::sync::RwLock` docs refer to tasks waiting to
acquire a lock as "blocking". Again, this is because these docs were 
copied from the `std::sync::RwLock` docs. In the past, the use of the 
term "blocking" to refer to causing a task to yield [has caused confusion
for users][1].
[1]: https://github.com/tokio-rs/doc-push/issues/85#issuecomment-582070279
This PR corrects the documentation to describe the actual priority
policy.
In addition, it changes the …
=> sync: improve RwLock API docs

tokio/src/sync/mod.rs
Reading the `sync` documentation, I found a small spelling error.
I fixed the error.
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> sync: fixed a small typo in sync docs

README.md
The link to the contributing guide in the tokio sub crate's README.md was
referencing a non-existent file. This updates the link to reference
the repo root's CONTRIBUTING.md file.
Fixes: #2266
There was a broken link to the CONTRIBUTING.md file in the sub crate `tokio/`'s README.md file.
This approach simply updates the link to point at the CONTRIBUTING.md file in the repo root. An alternative solution is to symlink the repo root's CONTRIBUTING.md file in the `tokio/` sub crate.
=> tokio: fix broken 'contributing guide' link in README.md

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/error.rs
I want to be able to `send` with a timeout, using `crate::time::timeout` with `send` does not let me get the value I passed to it back.
I've implemented a `send_timeout` similar to the one in `crossbeam::channel`.
=> mpsc: add `Sender::send_timeout`

tokio/src/io/driver/mod.rs, tokio/src/io/driver/platform.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs, tokio/tests/process_issue_2174.rs
#2174
On epoll platforms, the read end of a pipe closing is signaled to the write end
through the `EPOLLERR` event [[1](http://man7.org/linux/man-pages/man2/epoll_ctl.2.html)]. If readiness is not registered for this
event, it will silently pass through `epoll_wait` calls.
Additionally, this specific case that `EPOLLERR` is triggered leaves the write
end of the pipe (parent process) waiting for a wakeup that never occurs.
Similar to the `HUP` event on Unix platforms, errors are now always masked
through registrations so that both read and write ends of a connection are made
aware of errors.
In cases where pipes are used and the read end closes, write ends that are
waiting for a wakeup are properly notified and try to write again. This allows
a client to observe `BrokenPipe` and go through …
=> process: Wake up read and write on `EPOLLERR`

tokio/src/macros/pin.rs, tokio/tests/macros_pin.rs
Allows combining assignment to a binding and pinning it.
Extracted from: https://github.com/tokio-rs/tokio/pull/2210#discussion_r374382058
=> macros: add assignment form to pin!

tokio/src/net/tcp/listener.rs, tokio/src/net/unix/listener.rs
The Incoming types currently don't take ownership of the listener, but
in most cases, users who want to use the Listener as a stream will only
want to use the stream from that point on. So, implement Stream directly
on the Listener types.
Implement Stream for the Listener types (copy from `Incoming` implementation)
Unresolved question: The two `Incoming` types serve no purpose now and could be removed, but this would break existing code.
=> Implement Stream for Listener types

tokio-macros/src/lib.rs, tokio/src/lib.rs
Attempted fix for #2075, see also [#2075 (comment)](https://github.com/tokio-rs/tokio/issues/2075#issuecomment-583122347).
This tries to work within the 0.2 approach of using `doc(cfg(feature = "…"))` by adding an additional `doc(cfg)` to ensure the `macros` feature requirement is included in rustdoc.
Then it adds some plain-english rustdoc to the descriptions of test and main macro options to explain the feature dependencies on those. There was previously some mixup with what macros these options (and associated usage examples) were applied, so that is also fixed here.
To test this locally, one can use the following:
``` bash
RUSTDOCFLAGS="--cfg docsrs" cargo doc --no-deps --open --all-features
```
Note that this results in the following rustdoc generated output on these macros:
> This …
=> Macros doc(cfg) workarounds

tokio/src/time/delay_queue.rs, tokio/tests/time_delay_queue.rs
If an entry is inserted in the queue before the next deadline, the
DelayQueue needs to update the Delay tracking the next time to poll.
If there is an existing Delay, reset that rather than replacing it as if
it's already been polled the task will be waiting for a notification
before it will poll again, and dropping the Delay means that that
notification will never be performed.
In certain cases DelayQueue may not wake the appropriate task if it is modified after it's already been polled.  This PR covers the case where an entry is being inserted before the current deadline.
When changing the deadline, if there's an existing Delay then update that rather than creating a new one as creating a new delay throws away the task registration.
=> Make DelayQueue wake the task at the right time after insert

tokio/src/sync/notify.rs, tokio/src/util/linked_list.rs
Allow storing the intrusive linked-list pointers in an arbitrary
location in the node. This is in preparation for using the linked list
in the scheduler.
In order to make using the intrusive linked list more flexible, a trait
is introduced to abstract mapping an entry to raw pointers and the next
/ prev pointers. This also pushes more unsafety onto the user.
=> sync: refactor intrusive linked list

tokio/src/runtime/builder.rs
It can be pretty confusing when the `core_threads` example does not call `threaded_scheduler`, since actually building such a runtime results in panics if you try to spawn something on it:
```rust
async fn a() {}
fn main() {
let mut rt = runtime::Builder::new()
.core_threads(4)
.build()
.unwrap();
rt.spawn(a()); // panic
rt.block_on(a());
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=866b3af344b0d6aad170ac9cbc9d57ed)
=> runtime: Add threaded_scheduler to examples

tokio/src/macros/pin.rs, tokio/tests/macros_pin.rs
A new assignment form of `pin!` macro introduced in v0.2.12 causes 'unresolved import' in this code.
```rust
fn main() {
tokio::pin! {
let x = 0;
}
}
```
The macro uses `crate` instead of `$crate`. This PR fixes this incorrect usage.
=> Fix unresolved import in pin!

tokio/src/macros/select.rs
Make documentation consistent.
Add missing tick marks and consistently use exclamation point.
=> macros: fix select! documentation formatting

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs
`FramedRead` users may want to set it's internal buffer size to minimize the chances of it being reallocated. 
In a variety of cases, it is possible to make a good guess on the frame size. Let this be configured instead of sticking with `framed_read::INITIAL_CAPACITY` of `8k`.
Relates to #2156.
=> codec: Add `Framed::with_capacity`

examples/Cargo.toml, examples/chat.rs, examples/tinydb.rs, examples/tinyhttp.rs, tokio-tls/Cargo.toml, tokio-util/CHANGELOG.md, tokio-util/Cargo.toml, tokio-util/src/codec/bytes_codec.rs, tokio-util/src/codec/decoder.rs, tokio-util/src/codec/encoder.rs, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/length_delimited.rs, tokio-util/src/codec/lines_codec.rs, tokio-util/src/udp/frame.rs, tokio-util/tests/codecs.rs, tokio-util/tests/framed.rs, tokio-util/tests/framed_write.rs, tokio-util/tests/udp.rs
Since the encoded item is to be encoded into a given `BytesMut`, taking ownership is not necessary here.
=> codec: change Encoder to take &Item

tokio/tests/fs_copy.rs
Some of the tests generate files called `foo.txt` and `bar.txt`, these should not get checked in.
I kept almost checking in `foo.txt` and `bar.txt` by mistake.
Add them to `.gitignore`
=> Add foo.txt and bar.txt to .gitignore

tokio/src/sync/broadcast.rs
https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_lock
Binding the tail's lock keeps it acquired until `notify_all` is called
=> Keep lock until sender notified

CONTRIBUTING.md
Currently you have to look inside the ci directory to find the commands, which does not lend itself very well to discoverability for new users. I personally found it difficult to find some of these, and I'm [not the only one][1].
You can view the rendered markdown [here][2].
[1]: https://github.com/tokio-rs/tokio/pull/1921#issuecomment-593762708
[2]: https://github.com/Darksonn/tokio/blob/document-ci-commands/CONTRIBUTING.md#cargo-commands
=> Document common cargo commands

tokio/src/coop.rs, tokio/src/io/registration.rs, tokio/src/lib.rs, tokio/src/process/mod.rs, tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/blocking/task.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/shell.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/task/join.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mutex.rs, tokio/src/sync/oneshot.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs, tokio/src/time/driver/registration.rs
A single call to `poll` on a top-level task may potentially do a lot of work before it returns `Poll::Pending`. If a task runs for a long period of time without yielding back to the executor, it can starve other tasks waiting on that executor to execute them, or drive underlying resources. See for example https://github.com/rust-lang/futures-rs/issues/2047, https://github.com/rust-lang/futures-rs/issues/1957, and https://github.com/rust-lang/futures-rs/issues/869. Since Rust does not have a runtime, it is difficult to forcibly preempt a long-running task. 
Consider a future like this one:
```rust
async fn drop_all<I: Stream>(input: I) {
while let Some(_) = input.next().await {}
}
```
It may look harmless, but consider what happens under heavy load if the input stream is _always_ ready. If …
=> Add cooperative task yielding

tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/task/spawn.rs
This PR was prompted by having encountered a few cases of people not noticing that [`Runtime::handle`][1] can be cloned, and therefore not realizing it could be moved to another thread.
[1]: https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Runtime.html#method.handle
=> runtime: update the documentation around Handle

tokio/src/sync/rwlock.rs, tokio/tests/sync_rwlock.rs
Add RwLock::into_inner method that consumes the lock and returns
the wrapped value.
Fixes: #2320
=> Add RwLock::into_inner method

tokio-util/Cargo.toml
tokio-util uses tokio::stream::StreamExt, which was not introduced until
tokio v0.2.5. The current dependency specification is incorrect, and
breaks with cargo update -Z minimal-versions.
This is preventing h2 from upgrading to tokio-util 0.3
=> tokio-util: fix minimum supported version of tokio

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml, tokio-util/src/lib.rs
@LucioFranco, as promised in #2326. I modeled this off of #2296—let me know if something looks off!
=> util: Prepare `0.3.1` release

tests-integration/Cargo.toml, tests-integration/tests/rt_shell.rs, tokio/src/runtime/shell.rs, tokio/src/util/mod.rs
Since the original shell runtime was implemented, utilities have been
added to encapsulate `unsafe`. The shell runtime is now able to use
those utilities and not include its own `unsafe` code.
=> rt: remove `unsafe` from shell runtime.

tokio/src/io/stderr.rs, tokio/src/io/stdin.rs, tokio/src/io/stdout.rs
fixes: #2311
provides an implementation of AsRawFd and AsRawHandle for Stdin, Stdout and Stderr to match the std counterpart behavior.
It is sometimes necessary to manipulate stdio as raw file descriptors, to set attributes for example. 
The Std* is wrapped in an Option in a  Blocking, which makes it impossible to take it out in a non blocking way. I implemented it the same way Async-std did it, and retrieve another instance of std::io::Std*, and use it to retrieve an new RawFd.
=> tokio-io: impl asRawFd/AsRawHandle for stdio

tokio/src/time/clock.rs, tokio/src/time/driver/mod.rs, tokio/src/time/tests/test_delay.rs, tokio/tests/test_clock.rs
The resume function was breaking the guarantee that Instants should
never be less than any previously measured Instants when created.
Altered the pause and resume function such that they will not break this
guarantee. After resume, the time should continue from where it left
off.
Created test to prove that the advanced function still works as
expected.
Added additional tests for the pause/advance/resume functions.
Updated documentation.
The `tokio::time::resume()` function was breaking the following guarantee: "Instants are always guaranteed to be no less than any previously measured instant when created".
This happened because after pausing via `tokio::time::pause()` and then advancing via
`tokio::time::advance()` the time might have advanced by much more than what the real time was. …
=> time can be paused and resumed repeatedly

tokio/src/stream/iter.rs, tokio/tests/stream_iter.rs
`stream::iter()` should yield every so often and participate in the `coop` functionality. However, I'm not sure if it should consume budget on **every** iteration.
Another option would be to consume budget every ~25 steps... but that would require adding state to the stream. Yet another strategy would be to make consuming budget be **weighted**. So `stream::iter` would consume 1 unit every iteration but reading data would consume much more (1 unit per n bytes? not sure)
=> stream: iter() should yield every so often.

tokio/src/time/delay_queue.rs, tokio/tests/time_delay_queue.rs
Fixes #1700 
Previously, inserting a new item into a `DelayQueue` after a value expired would result in all items in the queue to be postponed until the inserted item was ready. This was due to a delay keeping track of when the next item expires wasn't being updated correctly when a value was extracted from the wheel. 
This PR makes sure that when a item expires, the `DelayQueue` updates the delay until the next item expires accordingly.
=> time: fix DelayQueue rewriting delay on insert after Poll::Ready

tokio/src/time/driver/tests/mod.rs
Fixes a test from a PR that was written before the recent loom upgrade.
A change in the details how loom executes models resulted in the test to
start failing. The fix is to reduce the number of iterations performed
by the test.
=> timer: fix loom test

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/tests/loom_semaphore_batch.rs, tokio/src/util/linked_list.rs
When cancelling futures which are waiting to acquire semaphore permits,
there is a possible dangling pointer if notified futures are dropped
after the notified wakers have been split into a separate list. Because
these futures' wait queue nodes are no longer in the main list guarded
by the lock, their `Drop` impls will complete immediately, and they may
be dropped while still in the list of tasks to notify.
This branch fixes this by notifying futures inside the lock, as a
stop-gap solution. In the future, we should try to find a way to notify
tasks outside the lock without introducing the potential for node
pointers to dangle.
=> sync: fix possible dangling pointer in semaphore

tokio/src/sync/notify.rs
A link was broken due to a typo.
=> Fix link in Notify

tokio/src/coop.rs, tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/queue.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/task/local.rs, tokio/tests/rt_common.rs
The work-stealing scheduler includes an optimization where each worker
includes a single slot to store the **last** scheduled task. Tasks in
scheduled task is executed next. This speeds up and reduces latency with
message passing patterns.
Previously, this optimization was susceptible to starving other tasks in
certain cases. If two tasks ping-ping between each other without ever
yielding, the worker would never execute other tasks.
An early PR (#2160) introduced a form of pre-emption. Each task is
allocated a per-poll operation budget. Tokio resources will return ready
until the budget is depleted, at which point, Tokio resources will
always return `Pending`.
This patch leverages the operation budget to limit the LIFO scheduler
optimization. When executing tasks from the LIFO slot, the …
=> rt: cap fifo scheduler slot to avoid starvation

tokio/src/runtime/queue.rs, tokio/tests/rt_common.rs
The new queue uses `u8` to track offsets. Cursors are expected to wrap.
An operation was performed with `+` instead of `wrapping_add`. This was
not _obviously_ issue before as it is difficult to wrap a `usize` on
64bit platforms, but wrapping a `u8` is trivial.
The fix is to use `wrapping_add` instead of `+`. A new test is added
that catches the issue.
Fixes #2361
=> rt: fix queue regression

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/tests/sync_mpsc.rs
Fixes #898.
Basically #898. Also needed for https://github.com/tower-rs/tower/issues/408.
Since `poll_ready` takes up one of the finite number of slots in a bounded channel, callers need to send an item shortly after `poll_ready` succeeds. If they do not, idle senders may take up all the slots of the channel, and prevent active senders from getting any requests through. Consider this code that forwards from one channel to another:
```rust
loop {
ready!(tx.poll_ready(cx))?;
if let Some(item) = ready!(rx.poll_recv(cx)) {
tx.try_send(item)?;
} else {
break;
}
}
```
If many such forwarders exist, and they all forward into a single (cloned) `Sender`, then any number of forwarders may be waiting for `rx.poll_recv` at the same time. While they do, they are effectively each reducing the channel's …
=> sync: Add disarm to mpsc::Sender

tokio-util/src/codec/length_delimited.rs, tokio-util/tests/length_delimited.rs
There is a gap in (simple) examples for Builder::num_skip() that shows how to
move past unused bytes between the length and payload.
I had the same question when starting to use LengthDelimitedCodec as a bug:
https://github.com/tokio-rs/tokio/issues/2331
More documentation examples and a test (in case people look there like I did).
=> util: documentation example for LengthDelimitedCodec

tokio-test/src/io.rs, tokio-test/tests/io.rs
Enable testing of edge cases caused by io errors.
Needed to test edge cases caused by tcp ConnectionReset events in another project built upon tokio.
Having the ability to simulate it using the `tokio-test` library solved the issue. 
Added `read_error()` and `write_error()` to both the `io::Builder` and `Handle` structs.
As the Vector of actions is being processed, the given error is returned. Note that `Arc` is being used so that `Action` remains `Clone` and can keep the current API.
=> test: Added read_error() and write_error()

tokio/src/fs/copy.rs, tokio/tests/fs_copy.rs
File permissions are not properly copied by `fs::copy`.
This change ensures permissions are copied for new and existing files, as well
as adds a test.
Closes #2341
=> fs: Copy file permissions

tokio/CHANGELOG.md
- sync: fix a regression where `Mutex`, `Semaphore`, and `RwLock` futures no
longer implement `Sync` (#2375)
- fs: fix `fs::copy` not copying file permissions (#2354)
- time: added `deadline` method to `delay_queue::Expired` (#2300)
- io: added `StreamReader` (#2052) 
=> chore: prepare tokio 0.2.16 release

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/unbounded.rs
Small doc fix.
I was reading the doc at `UnboundedSender::send()` and even though it's probably more or less obvious why it could fail, I thought it would be better to have it stated explicitly...
=> doc: Add error explanation for UnboundedSender::send()

tokio/Cargo.toml, tokio/src/loom/std/atomic_u16.rs, tokio/src/loom/std/atomic_u32.rs, tokio/src/loom/std/atomic_u8.rs, tokio/src/loom/std/mod.rs, tokio/src/runtime/queue.rs, tokio/src/runtime/tests/loom_queue.rs, tokio/src/runtime/tests/queue.rs
Fixes a couple bugs in the work-stealing queue introduced as
part of #2315. First, the cursor needs to be able to represent more
values than the size of the buffer. This is to be able to track if
`tail` is ahead of `head` or if they are identical. This bug resulted in
the "overflow" path being taken before the buffer was full.
The second bug can happen when a queue is being stolen from concurrently
with stealing into. In this case, it is possible for buffer slots to be
overwritten before they are released by the stealer. This is harder to
happen in practice due to the first bug preventing the queue from
filling up 100%, but could still happen. It triggered an assertion in
`steal_into`. This bug slipped through due to a bug in loom not
correctly catching the case. The loom bug is fixed as …
=> rt: fix bug in work-stealing queue

tokio/src/loom/std/mod.rs
Some reasons to prefer logical count as the default:
- Chips reporting many logical CPUs vs physical, such as via
hyperthreading, probably know better than us about the workload the CPUs
can handle.
- The logical count (`num_cpus::get()`) takes into consideration
schedular affinity, and cgroups CPU quota, in case the user wants to
limit the amount of CPUs a process can use.
Closes #2269
=> Use logical CPUs instead of physical by default

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- rt: bug in work-stealing queue (#2387)
=> chore: prepare to release 0.2.17

tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs, tokio/src/net/unix/stream.rs, tokio/src/sync/mpsc/error.rs
The streams documentation referred to module-level `split` doc which is no longer there.
Please let me know if you think these links should actually lead to more detailed documentation somewhere and I will add it.
Thanks!
=> docs: fix incorrect documentation links & formatting

tokio-util/src/codec/length_delimited.rs, tokio/src/coop.rs, tokio/src/fs/read_dir.rs, tokio/src/io/mod.rs, tokio/src/io/poll_evented.rs, tokio/src/io/stdin.rs, tokio/src/io/util/empty.rs, tokio/src/io/util/repeat.rs, tokio/src/net/tcp/stream.rs, tokio/src/runtime/context.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/thread_pool/mod.rs, tokio/src/sync/mutex.rs, tokio/src/sync/oneshot.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/watch.rs, tokio/src/task/local.rs, tokio/src/task/task_local.rs, tokio/src/time/delay_queue.rs, tokio/src/time/timeout.rs
Included changes
- all simple references like `<type>.<name>.html` for these types
- enum
- fn
- struct
- trait
- type
- simple references for methods, like struct.DelayQueue.html#method.poll
Refs: #1473
Make doc's links more resistant.
Delagates doc's links resolution to [`rustdoc`](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md).
=> docs: replace some html links with rustdoc paths

tokio/src/task/local.rs, tokio/tests/async_send_sync.rs
If anyone knows of any other types that should be non-send or non-sync, please comment below so I can add them to the test. We can add Send+Sync types later.
Closes #2397.
=> task: make LocalSet non-Send

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- task: `LocalSet` was incorrectly marked as `Send` (#2398)
- io: correctly report `WriteZero` failure in `write_int` (#2334)
=> chore: prepare to release 0.2.18

.cirrus.yml
Probably due to the old image: https://github.com/cirruslabs/cirrus-ci-docs/issues/625
=> ci: fix FreeBSD CI

tokio/src/net/tcp/listener.rs, tokio/src/runtime/mod.rs, tokio/src/task/local.rs, tokio/src/time/delay_queue.rs
Also, the link for `driver` is removed because `driver` is now `pub(crate)`, so can't be used in docs.
Make doc's links more resistant.
Delagates doc's links resolution to [`rustdoc`](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md).
Refs: #1473
=> doc: fix a few broken links by using rustdoc

tokio/src/runtime/enter.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/task/blocking.rs, tokio/tests/task_blocking.rs
This enables nested calls to `block_in_place` by removing an overly aggressive `debug_assert`.
It is a precursor to what would be needed for #2327.
=> Support nested block_in_place

tokio-macros/CHANGELOG.md, tokio-tls/CHANGELOG.md, tokio-util/CHANGELOG.md, tokio/CHANGELOG.md
Viewing PRs from the change logs requires copying & pasting the number to get to it.
Allow to simply click on the PR number to view the corresponding changes made.
=> Link PRs in CHANGELOG files

tokio/src/lib.rs
This PR makes it easier to find information about blocking code in Tokio's documentation. It also makes something show up when ctrl-F ing for "CPU".
=> doc: mention CPU-bound code lib.rs

tokio/src/task/task_local.rs
Ensure the visibility modifier is propagated static when constructing a `task_local!`.
=> task: Ensure the visibility modifier is propagated when constructing a task local

tokio/src/sync/mod.rs, tokio/src/sync/semaphore.rs, tokio/tests/sync_semaphore_owned.rs
This implements the suggestion in @hawkw's comment on [#1998][1].
[1]: https://github.com/tokio-rs/tokio/issues/1998#issuecomment-616695722
=> sync: add owned semaphore permit

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/blocking/shutdown.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/shell.rs, tokio/src/runtime/thread_pool/mod.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/task/local.rs, tokio/tests/task_blocking.rs
This enables `block_in_place` to be used in more contexts. Specifically,
it allows you to block whenever you are off the tokio runtime (like if
you are not using tokio, are in a `spawn_blocking` closure, etc.), and
in the threaded scheduler's `block_on`. Blocking in `LocalSet` and the
basic scheduler's` block_on` is still disallowed.
Fixes #2327.
Fixes #2393.
=> Be more principled about when blocking is ok

tokio-util/src/codec/length_delimited.rs, tokio/src/io/poll_evented.rs, tokio/src/runtime/mod.rs, tokio/src/task/task_local.rs
Replaces relative links by rusdoc link resolution when possible to have a compile error when links cannot be resolved.
Fix invalid links to AsyncRead and AsyncWrite in tokio-util.
Fix link to tokio::main in Runtime::new().
=> Remove relative link when possible and fix invalid links

tokio-test/src/task.rs
`tokio_test::task::Spawn` is `Unpin`, so unsafe `map_unchecked_mut` is not needed.
=> test: remove unnecessary unsafe code

tokio/Cargo.toml, tokio/src/io/util/read_to_string.rs, tokio/tests/read_to_string.rs
We can do everything needed with only safe code.
=> Remove `unsafe` from ReadToString

tokio/src/sync/mod.rs, tokio/src/sync/mutex.rs
Mutex module doc is not showing, doc is using inner doc comments, but the `Mutex` mod is private
this PR makes it visible again by switching the inner doc comments with outer doc comments. 
This Pr also adds examples to Mutex's methods
=> show mutex module doc, add method examples

tokio/src/io/async_write.rs
=> doc: fix a typo in the document

tokio/src/task/blocking.rs
The initial spawn_blocking documentation was unclear. This PR attempts to fix that.
Fixes #2143
Wrote a simpler documentation since the initial blocking documentation was unclear.
=> doc: improves spawn_blocking documentation

tokio/src/stream/chain.rs, tokio/src/stream/merge.rs, tokio/src/stream/mod.rs, tokio/tests/stream_chain.rs, tokio/tests/stream_merge.rs
Currently, `Merge` and `Chain` streams incorrectly handle overflows: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2f99c2f8f392d0fd068c050da7092cf3
This PR changes both places to use new `merge_size_hints` function that handles overflow (I believe :) ) properly.
=> Fix panics in Merge and Chain size hints

tokio/src/io/async_buf_read.rs, tokio/src/io/async_read.rs, tokio/src/io/async_seek.rs, tokio/src/io/async_write.rs, tokio/src/net/unix/listener.rs
Rustfmt has changed its mind on how some macros should be formatted.
See also rust-lang/rustfmt#4140.
=> io: update rustfmt changes

tokio/src/fs/file.rs, tokio/src/io/util/async_seek_ext.rs, tokio/src/net/tcp/split.rs, tokio/src/net/tcp/split_owned.rs, tokio/src/net/tcp/stream.rs
I have quite commonly seen users get confused about where the methods on extension traits are defined. This PR adds a whole bunch of links, making the documentation more connected.
Additionally it has a commit that addresses #2307.
=> Make it easier to discover extension traits

tokio/src/macros/cfg.rs, tokio/src/park/mod.rs, tokio/src/park/thread.rs, tokio/src/runtime/enter.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/tests/rt_common.rs
Adds the `Handle::block_on`, which is useful in synchronous contexts that only have shared access to the runtime, such as entry methods in a dynamic library.
I'm not confident in the implementation here, it's based on some guidance from @carllerche on discord, but I don't understand it myself.  Basic tests are provided, happy to add more with guidance.
=> Add Handle::block_on method

tokio/src/sync/broadcast.rs, tokio/tests/sync_broadcast.rs
Broadcast uses a ring buffer to store values sent to the channel. In order to
deal with slow receivers, the oldest values are overwritten with new values
once the buffer wraps. A receiver should be able to calculate how many values
it has missed.
Additionally, when the broadcast closes, a final value of `None` is sent to
the channel. If the buffer has wrapped, this value overwrites the oldest
value.
This is an issue mainly in a single capacity broadcast when a value is sent
and then the sender is dropped. The original value is immediately overwritten
with `None` meaning that receivers assume they have lagged behind.
Closes #2425
A value of `None` is no longer sent to the channel when the final sender has
been dropped. This solves the single capacity broadcast case by completely
removing …
=> sync: fix slow receivers in broadcast

tokio/src/runtime/builder.rs, tokio/tests/rt_threaded.rs
Previously, the function picking the default number of threads for the
threaded runtime did not factor in `max_threads`. Instead, it only used
the value returned by `num_cpus`. However, if `num_cpus` returns a value
greater than `max_threads`, then the function would panic.
This patch fixes the function by limiting the default number of threads
by `max_threads`.
Fixes #2452
=> rt: fix default thread number logic

tokio/src/runtime/task/harness.rs
Minor nit. We can make use of `std::mem::forget` to avoid running the Drop implementation instead of keeping track of it ourselves.
=> runtime: mem::forget instead of keeping track of dropped state

tokio/src/time/driver/entry.rs, tokio/tests/time_delay.rs, tokio/tests/time_delay_queue.rs
If a Delay has been polled then the task that polled it may be waiting
for a notification.  If the delay gets reset to a time in the past, then
it immediately becomes elapsed, so should notify the relevant task.
Under certain conditions `DelayQueue` may update the current deadline to be in the past.  The delay would immediately transition to elapsed, but wouldn't notify the appropriate task so the scheduler would never re-poll it.  
When resetting the time on a `Delay`, if the `Entry` is transitioning into `ELAPSED` state call the waker to wake any registered task.
=> Notify task when resetting a Delay to a time in the past

SECURITY.md
Build on the great security work already being done in the tokio-rs ecosystem!
This PR adds an initial security policy based on email discussions with @carllerche, @hawkw and co. Note that it may be necessary to update the project's Github Issue Template to the [new version](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) so that the "Report a Security Issue" link appears on the Github Issues workflow ([example](https://github.com/bytecodealliance/wasmtime)). It is not clear from the documentation.
=> Add initial security policy

tokio/src/io/util/lines.rs
Related issue #2433
Provides a convenient method to obtain the underlying reader of `Lines`.
Implemented `get_mut`, `get_ref` and `into_inner`. I simply took the implementation from other similar stuffs I see in the code base. Let me know if these are wrong.
=> Added `get_mut`, `get_ref` and `into_inner` for Lines.

tokio/src/macros/scoped_tls.rs
Do not export the `scoped_thread_local` macro outside of the Tokio
crate. This is not considered a breaking change as the macro never
worked if used from outside of the crate due to the generated code
referencing crate-private types.
=> macros: `scoped_thread_local` should be private

tokio/src/coop.rs, tokio/src/macros/cfg.rs, tokio/src/task/local.rs, tokio/tests/task_local_set.rs
Currently, an issue exists where a `LocalSet` has a single cooperative
task budget that's shared across all futures spawned on the `LocalSet`
_and_ by any future passed to `LocalSet::run_until` or
`LocalSet::block_on`. Because these methods will poll the `run_until`
future before polling spawned tasks, it is possible for that task to
_always_ deterministically starve the entire `LocalSet` so that no local
tasks can proceed. When the completion of that future _itself_ depends
on other tasks on the `LocalSet`, this will then result in a deadlock,
as in issue #2460.
A detailed description of why this is the case, taken from [this 
comment][1]:
`LocalSet` wraps each time a local task is run in `budget`:
https://github.com/tokio-rs/tokio/blob/947045b9445f15fb9314ba0892efa2251076ae73/tokio/src/t …
=> task: fix LocalSet having a single shared task budget

tokio/src/sync/mpsc/mod.rs
The implementation of the Sink trait was removed in 8a7e5778.
Fixes: #2464
Refs: #2389
Remove the reference to the `Sink` trait in [tokio/src/sync/mpsc/mod.rs](https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/mpsc/mod.rs).
=> doc: remove reference to the Sink trait in the MPSC documentation

ci/azure-check-features.yml, ci/azure-loom.yml, ci/azure-test-stable.yml, tokio/src/macros/cfg.rs, tokio/src/sync/cancellation_token.rs, tokio/src/sync/mod.rs, tokio/src/sync/tests/loom_cancellation_token.rs, tokio/tests/async_send_sync.rs, tokio/tests/sync_cancellation_token.rs
In preparation of work on `CancellationToken` internals, the tests are
moved into `tests/` and are updated to not depend on internals.
=> sync: move CancellationToken tests

tokio-tls/CHANGELOG.md, tokio-tls/Cargo.toml, tokio-tls/README.md, tokio-tls/src/lib.rs
=> tls: Deprecate in favor of `tokio-native-tls`

tokio/src/coop.rs, tokio/src/macros/cfg.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs, tokio/src/task/local.rs
Simplifies coop implementation. Prunes unused code, create a `Budget`
type to track the current budget.
=> rt: simplify coop implementation

tokio/src/runtime/blocking/mod.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/blocking/schedule.rs, tokio/src/runtime/blocking/task.rs, tokio/src/runtime/handle.rs
This follows a similar pattern to `Handle::spawn` to add the blocking spawn capabilities to `Handle`. I took a fairly direct approach to changing the visibilities within the blocking modules to get this to work out, and I would understand if you'd rather have things locked down some more. Please let me know if there are any changes you'd like to see there.
We have an app with multiple runtimes, so we prefer to perform operations explicitly with handles rather than using the `tokio::task::*` spawn operators. However, handles don't currently offer an API to spawn a blocking computation.
Adapts the implementation of `task::spawn_blocking` to use the blocking spawner that's already in the handle, guarded by `cfg(blocking)`.
=> Add Handle::spawn_blocking method

tokio/src/coop.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/tests/rt_threaded.rs
In some cases, when a call to `block_in_place` completes, the runtime is
reinstated on the thread. In this case, the task budget must also be set
in order to avoid starving other tasks on the worker.
=> rt: set task budget after block_in_place call

tokio/src/sync/mod.rs
As described in #2489, the section on [watch in the tokio::sync module-level docs](https://docs.rs/tokio/0.2.20/tokio/sync/index.html#watch-channel) has some broken links in 0.2.20.
Update the links in [tokio/src/sync/mpsc/mod.rs](https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/mod.rs).
Fixes: #2489
=> docs: fix links in `tokio::sync`

CONTRIBUTING.md
Added GitHub-style link fragments to the `[Commit Squashing]`
sections of CONTRIBUTING.md
Fixes: #2506
Just noticed this, thought it could use a tidy up.
Checked the link fragments on GitHub and added them to the docs.
=> added link fragments to contribution documentation

tokio/src/stream/mod.rs
I noticed a mistake in `StreamExt`, method `filter_map` docs. It says:
```
... if it resolves to None then the next value will be produced.
```
and I think it should say
```
... if it resolves to None then the next value will be skipped.
```
I reworded the sentence.
=> stream: add missing "not" in filter_map docs

tokio/src/io/driver/mod.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs
Add additional methods to allow PollEvented to be created with an appropriate
`mio::Ready` state so that it can be properly registered with the reactor.
Fixes #2413
=> Error Creating PollEvented for RawFd #2413

tokio/src/io/poll_evented.rs
To address #2429 
In io/poll_evented.rs, `poll_read_ready` and `poll_write_ready` shall not be called concurrently because it will mess up mio's internal state.
Add doc comments warning about this.
=> io: Add doc warning about concurrently calling poll_read/write_ready

tokio/src/net/unix/ucred.rs
Although very similar in many regards, illumos and Solaris have been
diverging since the end of OpenSolaris.  With the addition of illumos as
a Rust target, it must be wired into the same interfaces which it was
consuming when running under the 'solaris' target.
With the addition of the [illumos target](https://github.com/rust-lang/rust/issues/55553) and subsequent to various dependencies (like [mio](https://github.com/tokio-rs/mio/pull/1294)), it would be nice for Tokio to be supported on illumos.
Since `ucred` functions the same on illumos as it does on Solaris, they can share that logic.
=> add support for illumos target

tokio-macros/src/entry.rs, tokio/tests/macros_test.rs
`tokio::test` and related macros now use the absolute path `::core::prelude::v1::test` to refer to the built-in `test` macro.
This absolute path was introduced in rust-lang/rust#62086.
The following example currently fails due to shadowing of the `test` macro ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a66dc80aa7ed4665f714f2f651d3f421)):
```rust
use tokio::test;
#[test]
async fn mytest() { }
```
```
Compiling playground v0.0.1 (/playground)
error: the async keyword is missing from the function declaration
--> src/lib.rs:4:7
|
4 | async fn mytest() { }
|       ^^
error: the async keyword is missing from the function declaration
--> src/lib.rs:4:7
|
4 | async fn mytest() { }
|       ^^
```
=> macros: Disambiguate the built-in #[test] attribute in macro expansion.

CONTRIBUTING.md, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_impl.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/mod.rs
The current implementation of `Framed` is fragmented across `Framed`, `FramedRead`, and `FramedWrite` (among more internal types), raising the bar for contributions, and making for perplexing documentation:
> This method is called by **[`FramedRead`]** whenever bytes are ready to be
> parsed. The provided buffer of bytes is what's been read so far, and
> this instance of `Decode` can determine whether an entire frame is in
> the buffer and is ready to be returned.
>
> If an entire frame is available, then this instance will remove those
> bytes from the buffer provided and return them as a decoded
> frame. Note that removing bytes from the provided buffer doesn't always
> necessarily copy the bytes, so this should be an efficient operation in
> most circumstances.
>
> If the bytes look …
=> WIP: Rewrite of codec::Framed

tokio/src/time/throttle.rs
I was building the docs and got the following documentation warning:
```
warning: unknown attribute `norun`. Did you mean `no_run`?
--> tokio/src/time/throttle.rs:13:1
|
13 | / /// Slows down a stream by enforcing a delay between items.
14 | | /// They will be produced not more often than the specified interval.
15 | | ///
16 | | /// # Example
...  |
31 | | /// # }
32 | | /// ```
| |_______^
|
= help: the code block will either not be tested if not marked as a rust one or will be run (which you might not want)
```
=> Change norun to no_run

tokio-test/src/io.rs, tokio-util/src/codec/mod.rs, tokio/src/io/mod.rs, tokio/src/process/mod.rs, tokio/src/stream/empty.rs, tokio/src/stream/iter.rs, tokio/src/stream/once.rs, tokio/src/stream/pending.rs, tokio/src/sync/mod.rs, tokio/src/sync/semaphore_ll.rs
This is my attempt at improving the documentation and visibilty of the codec module.
I think directly mentioning that it converts between AsyncRead/AsyncWrite and Sink/Stream in the module description is a little clearer at least.
I also added a section to the `tokio::io` module describing what `codec` is used for.
Fixes #2475
=> docs: improve discoverability of tokio_util::codec module

tokio/src/runtime/handle.rs
This is a small PR adding some docs to `Handle::current()`. 
I never realized that `Handle::current()` had to be called outside of threads created using `std::thread::spawn`. Through some trial and error I figured out that you need to call it on a thread managed by tokio and then move the handle into the new thread you create. This was despite all of the docs clearly doing this properly. My changes try to make this more explicit so hopefully other people don't run into the same problems I had.
Please feel free to nitpick my wording (preferably using [GitHub suggestions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request)). This is my first time contributing docs to tokio. :)
=> Clarifying that Handle::current must be called on a thread managed by tokio

tokio/src/lib.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/semaphore.rs, tokio/src/sync/semaphore_ll.rs
Fix the document.
Add the ```MAX_PERMITS``` link
Example:
```rust
/// Adds `n` new permits to the semaphore.
///
/// `n` must less than [`MAX_PERMITS`]
///
/// [`MAX_PERMITS`]: Semaphore::MAX_PERMITS
pub fn add_permits(&self, n: usize) {
self.ll_sem.release(n);
}
````
=> Fix add_permits document

tokio-util/src/codec/framed.rs
Adds a method to retrieve a mutable reference to the Framed stream's read buffer.
This makes it possible to e.g. externally clear the buffer to prevent the codec from
parsing stale data.
Allow write access to the Framed's read buffer so it can be altered externally.
This is demonstrated in [tokio-modbus](https://github.com/slowtec/tokio-modbus/issues/60) where the codec tries to detect a data frame and gets confused by malformed data. Clearing the read buffer before sending a modbus request effectively bypasses the problem.
There are other ways to solve this, but getting a mutable reference to the buffer is by far the most performant and obvious.
Add the `read_buffer_mut` method.
=> util: Add Framed::read_buffer_mut()

tokio-macros/src/lib.rs
Adds a note to the documentation of the `tokio::main` and the `tokio::test` macros that renaming the 0.2 version of this crate will break these macros.
There's more discussion in the comments on #2312.
proc macros are unhygienic and since these macros emit calls to `tokio` APIs, if the user renames the tokio crate in their Cargo.toml, these macros break with a less than excellent error message.
Since there's no technical solution that doesn't require user intervention, just documenting the issue seems best.
=> tokio-macros: add documentation about re-naming the tokio dependency

tokio/src/fs/dir_builder.rs, tokio/src/fs/mod.rs, tokio/src/fs/os/unix/dir_builder_ext.rs, tokio/src/fs/os/unix/mod.rs, tokio/src/macros/cfg.rs, tokio/tests/fs_dir.rs
`tokio` doesn't have an asynchronous version of `std::fs::DirBuilder` yet.
This PR adds support for `std::fs::DirBuilder` and implementation for the `std::os::unix::fs::DirBuilderExt` trait.
The initial idea was to implement  a thin wrapper  around an internally
held `std::fs::DirBuilder` instance.  This, however, didn't work due to
`std::fs::DirBuilder` not having Copy/Clone traits implemented, which
was necessary for constructing an instance to move-capture it into a
closure.
Instead,  we have mirrored the `std::fs::DirBuilder` configuration by  storing
the `recursive` and (unix-only) `mode`  parameters locally,  which were then
used to construct the `std::fs::DirBuilder` instance on-the-fly.
The (unix-only) `DirBuilderExt` trait  has  been  implemented  in-place
within the …
=> fs: add support for DirBuilder and DirBuilderExt

tokio/src/coop.rs, tokio/src/io/registration.rs, tokio/src/process/mod.rs, tokio/src/runtime/task/join.rs, tokio/src/stream/iter.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/oneshot.rs, tokio/src/time/driver/registration.rs
This patch updates the coop logic so that the budget is only decremented if a future makes progress (that is, if it returns `Ready`). This is realized by restoring the budget to its former value after `poll_proceed` _unless_ the caller indicates that it made progress.
The thinking here is that we always want tasks to make progress when we poll them. With the way things were, if a task polled 128 resources that could make no progress, and just returned `Pending`, then a 129th resource that _could_ make progress would not be polled. Worse yet, this could manifest as a deadlock, if the first 128 resources were all _waiting_ for the 129th resource, since it would _never_ be polled.
The downside of this change is that `Pending` resources now do not take up any part of the budget, even though …
=> coop: Undo budget decrement on Pending

.github/workflows/test_tokio.yml
Templates aren't directly a feature in Github Actions, so I'm not going to attempt to parameterize the jobs the same way right now. Also, the `on:` conditions are so that the CI will fire on this PR while I'm developing it, the commented out version below is the correct final condition.
=> Start migrating CI to Github Actions

tokio/src/io/util/lines.rs, tokio/src/io/util/read_line.rs, tokio/src/io/util/read_until.rs, tokio/src/io/util/split.rs, tokio/tests/io_read_line.rs, tokio/tests/io_read_until.rs
The changes in this PR are inspired by #2384. Note that the documentation specifies different behaviour on error for these methods than in the linked PR, namely that extra data should _not_ be discarded on error.
Fixes: #2532
=> io: fix panic in read_line

tokio/src/net/tcp/stream.rs
This took me a bit to catch on to this behaviour because I didn't really think there was any reason to investigate the individual documentation of each half. As someone dealing with TCP streams directly for first time (without previous experience from other languages) this caught me by surprise
Added a note about the write half's drop behaviour to `into_split` itself
=> Added a note about into_split's drop

tokio/src/io/async_buf_read.rs
It was out of date so I just copy/pasted the text from AsyncRead and adjusted it.
=> Update AsyncBufRead's doc comment

azure-pipelines.yml, tokio/src/io/async_read.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/udp/socket.rs, tokio/src/net/udp/split.rs, tokio/src/process/mod.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/mod.rs, tokio/src/time/delay_queue.rs
Make doc's links more resistant.
Delagates doc's links resolution to [`rustdoc`](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md).
Refs: #1473
=> docs: replace method links with intra-links

ci/azure-clippy.yml, tokio/src/sync/tests/semaphore_batch.rs, tokio/tests/macros_join.rs, tokio/tests/macros_select.rs, tokio/tests/macros_try_join.rs, tokio/tests/sync_mutex_owned.rs, tokio/tests/time_delay_queue.rs
First commit allows `blacklisted_name`.
Second commit fixes all other warnings .
Third commit updates CI config so that clippy will check tests too.
=> Fix all clippy lints in tests

tokio-util/src/codec/length_delimited.rs, tokio/src/coop.rs, tokio/src/fs/remove_dir_all.rs, tokio/src/fs/set_permissions.rs, tokio/src/fs/symlink_metadata.rs, tokio/src/io/mod.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs, tokio/src/macros/pin.rs, tokio/src/net/udp/split.rs, tokio/src/signal/unix.rs, tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs, tokio/src/task/blocking.rs, tokio/src/task/local.rs, tokio/src/task/task_local.rs, tokio/src/time/delay_queue.rs
Make doc's links more resistant.
Delegates doc's links resolution to [`rustdoc`](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md).
Refs: #1473
=> docs: use intra-links in the docs

tokio/README.md
fix the link of contributing guide in tokio/README(https://github.com/tokio-rs/tokio/blob/master/tokio/README.md)
just replace the link with the right one
=> docs: fix the link of contributing guide

.cirrus.yml, ci/azure-test-stable.yml
Backport #2403 
Addresses https://github.com/tokio-rs/tokio/pull/2563#issuecomment-634945770
=> ci: fix ci failure on v0.1.x

tokio/src/net/addr.rs
Addresses https://github.com/tokio-rs/tokio/pull/1760#discussion_r379120864
=> net: impl ToSocketAddrs for &[SocketAddr]

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/read_buf.rs, tokio/src/io/util/write_buf.rs
https://github.com/tokio-rs/tokio/blob/1636910f0a6bdb2084362be6b4daea70bcdceebc/tokio/src/io/util/write_buf.rs#L37-L41
This is a `Pin<&mut Type>` to `Pin<Field>` projection and is unsound if `W` is not `Unpin` (*you can move `W` after `WriteBuf` dropped*):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4740885e4bdb8169e6e5e335fca72d6
The correct projection is `Pin<&mut Type>` to `Pin<&mut Field>`. In `WriteBuf`, it is `Pin<&mut WriteBuf<'_, W, B>>` to `Pin<&mut &mut W>`, and it needs to add `W: Unpin` bounds to convert `Pin<&mut &mut W>` to `Pin<&mut W>`.
Add `Self: Unpin` bounds to `AsyncReadExt::read_buf` and  `AsyncWriteExt::write_buf`.
This changes the public API, but I don't think there is any other way to fix this.
=> io: fix unsound pin projection in read_buf and write_buf

tokio-test/src/task.rs, tokio/src/runtime/blocking/task.rs, tokio/src/runtime/enter.rs, tokio/src/time/timeout.rs, tokio/tests/rt_basic.rs, tokio/tests/tcp_accept.rs
=> Reduce pin related unsafe code

tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs
=> sync: allow unsized types in Mutex and RwLock

tokio/src/macros/select.rs
The documentation of the select! macro contained a typo "provded" instead of "provided"
Hello! This is a small PR that only fixes one typo in the `select!` macro documentation. I skipped the later fields of the PR template because this appear self-explanatory to me.
=> doc: typo in select.rs

tokio/src/time/delay.rs, tokio/src/time/interval.rs, tokio/src/time/mod.rs
To add an `interval` example to the time module, add also add examples to the `interval` and `delay_for` functions. (#2494).
- Add an example using `interval` to the time module
- Add the same example to the `interval` function
- Copy the `delay_for` example in the module to the `delay_for` function
- Fix the comment for the `delay_for` example in the module
Refs: #2494
=> time: add an example using `interval` to the time module

tokio/src/sync/mpsc/mod.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/oneshot.rs
I keep seeing people being confused about the unbounded `send` method not being async, and thinking that our channels are actually blocking. I hope that this snippet improves on this.
=> sync: elaborate on unbounded send not being async

tokio/src/sync/mpsc/mod.rs
This is the continuation of #2600.
=> Channel documentation update

tokio/src/io/util/async_read_ext.rs
This paragraph from `std::io::Read::read_ext()` applies to
*implementors* of `Read`. Since `AsyncReadExt` can't and shouldn't be
implemented outside of this crate, this documentation is unnecessary.
=> docs: Remove inapplicable paragraph from 'AsyncReadExt::read_ext()'.

tokio/src/io/mod.rs
Previously, tokio-io mod.rs doc said that `BufWriter` gets flushed on
drop.
Fixes: #2484 
Rendered:
=> docs: Fix inconsistency in BufWriter behaviour description

tokio/src/sync/oneshot.rs
Tiny fix in documentation for `tokio::sync::oneshot::Receiver::close`. Used the recommendation from #2601
=> doc: fixes link for tokio::sync::oneshot::Receiver::close (close #2601)

tokio-uds/src/ucred.rs
First, let me begin by saying I understand that the v0.1 series of tokio is deprecated.  Unfortunately it's still seeing somewhat wide usage in the ecosystem, including in RLS in the official Rust toolchain:
```
$ cargo tree -i -p tokio-uds 
tokio-uds v0.2.6
├── parity-tokio-ipc v0.2.0
│   ├── jsonrpc-client-transports v14.0.5
│   │   └── jsonrpc-core-client v14.0.5
│   │       └── rls-ipc v0.1.0 (/ws/crossrust/work/rust/src/tools/rls/rls-ipc)
│   │           ├── rls v1.41.0 (/ws/crossrust/work/rust/src/tools/rls)
│   │           └── rls-rustc v0.6.0 (/ws/crossrust/work/rust/src/tools/rls/rls-rustc)
│   │               └── rls v1.41.0 (/ws/crossrust/work/rust/src/tools/rls) (*)
│   └── jsonrpc-ipc-server v14.0.3
│       └── rls-ipc v0.1.0 (/ws/crossrust/work/rust/src/tools/rls/rls-ipc) …
```
=> uds: illumos can build using existing Solaris support

tokio-uds/CHANGELOG.md, tokio-uds/Cargo.toml, tokio-uds/README.md, tokio-uds/src/lib.rs
This release includes just #2563.
=> chore: prepare tokio-uds v0.2.7 release

tokio/src/io/util/copy.rs
Improve stack usage. The code was creating a temporary large array of bytes on the stack only for it to be moved to the heap via Box::new. 
[This Godbolt example](https://godbolt.org/z/x-YymL) demonstrates the problem and the solution.
This PR is a small change that fixes the problem by allocating the buffer directly on the heap via a Vec.
=> io: allocate large buffer directly on heap

tokio/src/time/clock.rs
This was changed in #2059. This had me extremely confused for some time
as my timeouts fired immediately, without allowing the wrapped future that were
waiting on IO to actually run long enough to finish.
I am not sure about the exact wording here but it should at least say that time is not actually paused. Deprecating "pause" and giving it a more accurate name
may be a good idea as well.
```rust
async fn timeout_advances() {
time::pause();
timeout(ms(1), async {
// Change to 1 and the this future resolve, 2 or
// more and the timeout resolves
for _ in 0..2 {
tokio::task::yield_now().await
}
})
.await
.unwrap();
}
```
=> fix: Update the docs of "pause" to state that time will still advance

examples/proxy.rs
On proxy exemple, if a connection is close from one side, one side stay open, a thread keep infinitly pending. 
Fix : #2406 
Close writer after copying totalité of reader
=> Close pending connection on proxy exemple 

tokio/src/net/tcp/split_owned.rs, tokio/src/net/tcp/stream.rs, tokio/tests/rt_common.rs, tokio/tests/tcp_into_split.rs
Trying to see if windows CI can be fixed.
=> chore: fix windows CI

tokio/src/net/addr.rs, tokio/src/stream/collect.rs, tokio/src/stream/mod.rs
Simple typo fix of "Rust language" instead of "Rust langague" in several files.
=> doc: fix typo from "Rust langague" to "Rust language"

examples/Cargo.toml, examples/chat.rs, tokio/Cargo.toml, tokio/src/macros/cfg.rs, tokio/src/task/blocking.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs, tokio/src/util/mod.rs, tokio/src/util/trace.rs
When debugging asynchronous systems, it can be very valuable to inspect
what tasks are currently active (see #2510). The [`tracing` crate] and
related libraries provide an interface for Rust libraries and
applications to emit and consume structured, contextual, and async-aware
diagnostic information. Because this diagnostic information is
structured and machine-readable, it is a better fit for the
task-tracking use case than textual logging — `tracing` spans can be
consumed to generate metrics ranging from a simple counter of active
tasks to histograms of poll durations, idle durations, and total task
lifetimes. This information is potentially valuable to both Tokio users
*and* to maintainers.
Additionally, `tracing` is maintained by the Tokio project and is
becoming widely adopted by …
=> task: add Tracing instrumentation to spawned tasks

tokio/src/runtime/thread_pool/worker.rs, tokio/tests/task_blocking.rs
A fast path in block_on_place was failing to call exit() in the case where we
were in a block_on call.
Fixes: #2639
Often synchronous library APIs can be implemented in terms of a private tokio runtime. While it would be preferable to structure calls into these libraries as async calls, this isn't always possible, and so it should be possible to enter a blocking context using `block_in_place` and then `block_on` a different runtime. This works on spawned tasks, but fails in `block_on` calls due to a bug in `block_in_place`.
This ensures that `exit` is called from within `block_on` contexts, allowing us to enter a different runtime.
=> Allow block_on inside block_in_place inside block_on

tokio-util/src/codec/framed.rs
Our minimum supported Rust version does not allow switching to `#[non_exhaustive]`.
=> Fix new manual_non_exhaustive clippy lint

tokio/src/time/driver/entry.rs
Applying a suggestion from #2617 to make the sentence more clear.
=> Slight change in inner attribute of Entry struct

tokio/src/sync/watch.rs
We are not returning the old value. I suppose this was once indented and this is a leftover.
Some Cleanup
Remove the comment
=> Remove misleading comment in `sync::watch::Sender::broadcast`

tokio/src/io/util/buf_reader.rs
For some yet unknown reason using the default on a wrapped `Bufreader<TcpStream>`
causes the hyper server to sometimes fail to send the entire body in the
response.
This fixes that problem for us and ensures that hyper has a chance to
use vectored IO (making it a good change regardless of the mentioned
bug)
=> fix: Forward poll_write_buf on BufReader

tokio/src/future/ready.rs, tokio/src/io/util/flush.rs, tokio/src/io/util/read_buf.rs, tokio/src/io/util/read_exact.rs, tokio/src/io/util/shutdown.rs, tokio/src/runtime/context.rs, tokio/src/time/driver/mod.rs
While many fixes were straightforward, I can be mistaken in some places.
Now `cargo +nightly doc --open --document-private-items --all-features` should work
Fixes #2537
=> Update doc comments

tokio/src/runtime/blocking/shutdown.rs, tokio/src/runtime/mod.rs, tokio/tests/task_blocking.rs
Dropping a runtime normally involves waiting for any outstanding blocking tasks
to complete. When this drop happens in an asynchronous context, we previously
would issue a cryptic panic due to trying to block in an asynchronous context.
This change improves the panic message, and adds a `shutdown_now()` function
which can be used to shutdown a runtime without blocking at all, as an out for
cases where this really is necessary.
=> provide a way to drop a runtime in an async context

CONTRIBUTING.md, README.md, tokio/README.md
I had a read-through of the readme and contributing files. I changed a bunch of links, and a few wording things.
I also changed the text regarding the minimum supported rust version to match what we test in our CI. @carllerche can you confirm if this change is correct?
=> doc: update links in README.md and CONTRIBUTING.md

.github/workflows/audit.yml, .github/workflows/pr-audit.yml, .github/workflows/rust-audit.yml
This continues the work started in #2516, adding two workflows to run `cargo audit` on the code and report these failures in a variety of useful ways. The intent is that the closer the code being audited is to being run in production, the louder these checks will complain. In order of increasing severity:
- A "manual" `cargo audit` check is run on each pr and push event containing changes to any `Cargo.toml` in the workspace.  This check only fails the job in order to mark a Pull Request as failing.
- Every day at 02:00 UTC the master branch is audited using the [`actions-rs/audit-check`] action.  When this check fails it will create an issue on github detailing the issue.
[`actions-rs/audit-check`]: /action-rs/audit-check
- On every push to the master branch that contains changes to any …
=> Add audit check

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/rwlock.rs
I'm planning to use permits to limit peak memory usage, and for that `u16` is very limiting.
I don't know if a small type is critical for performance here, so just in case I've opted for `u32` instead of `usize`.
Related to #2605 #2598
=> Support larger number of permits

tokio/src/io/mod.rs, tokio/src/io/util/mem.rs, tokio/src/io/util/mod.rs, tokio/tests/io_mem_stream.rs
`DuplexStream` provides a bidirectional type that can be used to simulate IO, but over an in-process piece of memory.
I've seen implementations of this rewritten over and over in codebases. They are frequently used in testing situations, where something like `tokio_test::io` wouldn't work (not trying to assert exact read and write calls, but just join a client and server in a single process).
=> tokio: introduce io::Duplex

tokio/src/io/mod.rs
Previously this needed `io-util` feature, but it doesn't seem to need this limitation.
It also re-exports `SeekFrom` needed to implement `AsyncSeek`.
=> io: always reexport std::io types needed to implement async io traits

tokio/src/net/unix/datagram.rs, tokio/src/net/unix/mod.rs, tokio/tests/uds_datagram.rs
fix issue https://github.com/tokio-rs/tokio/issues/2551 
this pr can be closed if this is merged. https://github.com/tokio-rs/tokio/pull/1757
=> net: introduce split on UnixDatagram

README.md, tokio/README.md
Tackling #2626
Adds a mention to the feature flag list available in the docs.
=> Reference the docs in the README with regards to the feature flags

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/net/mod.rs, tokio/src/net/tcp/split.rs, tokio/src/net/tcp/split_owned.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/split.rs, tokio/src/net/unix/datagram/mod.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/datagram/split.rs, tokio/src/net/unix/datagram/split_owned.rs, tokio/src/net/unix/mod.rs, tokio/src/net/unix/split.rs, tokio/src/net/unix/split_owned.rs, tokio/src/net/unix/stream.rs, tokio/src/sync/broadcast.rs
This also has various doc changes. I believe that this should resolve all split-related issues besides udp's owned split being named wrong, which is a breaking change.
=> Ensure that unix sockets have both split and into_split

.github/workflows/ci.yml
This makes it a bit easier to block a PR from landing without CI
passing.
=> chore: add ci job that depends on all tests

tokio/src/time/interval.rs
=> time: fix incorrect argument name in doc

.github/workflows/ci.yml
(Suggested by @seanmonstar) `cargo fmt` doesn't work (see rust-lang/rustfmt#4078), so CI invokes `rustfmt --check --edition 2018 $(find . -name '*.rs' -print)` instead. Users won't necessarily know this, and may run `cargo fmt` and wonder why it doesn't work.
This PR adds a message indicating the correct command to run.
=> Add a message on how to fix rustfmt errors.

tokio/src/runtime/thread_pool/worker.rs, tokio/tests/task_blocking.rs
Previously, we would fail to reset the coop budget in this case, making
it so that `coop::poll_proceed` would perpetually yield `Poll::Pending`
in nested executers even when run in `block_in_place`.
This is also a further improvement on #2645.
=> Reset coop budget when blocking in block_on

tokio/src/sync/batch_semaphore.rs
=> sync: show correct permits on debug mode

.github/workflows/ci.yml
As 0.3 is a breaking change, the minimum supported Rust version can be
changed.
=> chore: bump MSRV to 1.45

tokio/src/fs/file.rs
Issues like #2760 have come up a few times now although there isn't any problem.
A simple comment to explain why `poll_shutdown` isn't flushing.
=> file: Add comment

tokio/src/sync/mpsc/block.rs, tokio/src/sync/mpsc/list.rs
We don't usually use multi line imports.
=> chore: reformat some imports for consistency

tokio-test/src/io.rs, tokio-test/tests/io.rs
Ensures that no data is left to be read or written when Mock is dropped.
Fixes: #2693, #1847
=> test: implement Drop for Mock to panic w/ unconsumed data

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/builder.rs
=> add thread_name_fn method to runtime::Builder, close #1907.

tokio/src/sync/notify.rs
There is a typo in the documentation for `Notify`.
The typo has been corrected.
=> fix typo in Notify documentation

tokio/src/sync/rwlock.rs
I've introduced `MappedRwLockReadGuard` and `MappedRwLockWriteGuard`, which are produced by the relevant `map` and `try_map` methods.
Generally, this mimics the way `MappedRwLock*Guard`s are implemented in `parking_lot`. By storing a raw pointer in the guards themselves referencing the mapped data and maintaining type invariants through `PhantomData`. I didn't try to think too much about this, so if someone has objections I'd love to hear them.
I've also dropped the internal use of `ReleasingPermit`, since it made the guards unecessarily large. The number of permits that need to be released are already known by the guards themselves, and is instead governed directly in the relevant `Drop` impls.  This has the benefit of making the guards as small as possible, for the non-mapped variants …
=> sync: Implement map methods of parking_lot fame

tokio-macros/src/lib.rs, tokio-test/src/lib.rs, tokio/src/lib.rs, tokio/src/time/delay_queue.rs
Fixes: #2787
```
-#![deny(intra_doc_link_resolution_failure)]
+#![deny(broken_intra_doc_links)]
DelayQueue::poll is called DelayQueue::poll_expired
```
=> Docs delay queue

tokio/src/fs/file.rs, tokio/tests/support/mock_file.rs
These traits make it simpler to create instances from the raw OS primitives.
Defer to the trait implementations in `std` and convert from the resulting `std::fs::File`.
=> Implement `FromRawFd` & `FromRawHandle` for `File`

tokio/src/sync/barrier.rs, tokio/src/sync/mod.rs, tokio/src/sync/watch.rs, tokio/tests/sync_watch.rs
Fixes: #2172
- rename broadcast() to send() for watch channel
- watch channel .recv() returns T
=> Watch channel breaking changes

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/tests/task.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/notify.rs, tokio/src/task/local.rs, tokio/src/util/linked_list.rs
Reference: https://github.com/tokio-rs/tokio/pull/2790#discussion_r475769343
The current internal `LinkedList` had an implementation unsuitable for a const-fn constructor due to a generic constraint requiring `feature(const_fn)` which is nightly-only and we'd like to avoid that.
Applied here is a solution proposed by @hawkw in the referenced comment above that allows `LinkedList::const_new` to exist without the need of `feature(const_fn)`
The `LinkedList` definition expanded from a single generic parameter `T` to `L, T` and an unconstrained impl allowed `LinkedList::const_new` to be allowed by the compiler and now we have to explicitly specify the `Link::Target` in the second generic parameter `T`
=> Apply alternate `LinkedList` suggested solution.

tokio/src/io/read_buf.rs, tokio/src/io/util/take.rs
There was a [comment](https://github.com/tokio-rs/tokio/pull/2758#discussion_r469594718) indicating that extracing some login into `ReadBuf::take` is a good idea. 
=> io: add `ReadBuf::take`

tokio-macros/src/lib.rs, tokio/src/lib.rs, tokio/src/runtime/mod.rs
Resolves #2785
In the current form, user may (falsely) assume that `tokio::main` is the preferred way to build a Runtime, while it actually a sugar targeting *simple* cases.
Phrasing in docs are refined to highlight the fact that building a `Runtime` manually is perfectly OK if functionality of `tokio::main` macro is not sufficient.
=> Improve runtime customization docs

tokio/src/fs/file.rs, tokio/tests/async_send_sync.rs
Since `File` implementes `AsyncSeek`, there is no need to expose a `seek` function
Remove `File::seek`
Fixes: #1993
=> fs: remove `File::seek`

tokio/src/time/driver/handle.rs
Added in Handle::current() a detailed explanation on when the function
panics.
Fixes: #2696
=> tokio: document missing timer panics

tokio/src/runtime/task/join.rs
Added a note to `JoinHandle` docs to provide more context to the generic param `T`. 
Closes #2816.
=> Mention on JoinHandle that the generic parameter is the return type

tests-integration/tests/process_stdio.rs, tokio/Cargo.toml, tokio/src/process/mod.rs, tokio/src/process/unix/mod.rs, tokio/src/process/unix/reap.rs, tokio/src/process/windows.rs, tokio/tests/process_issue_2174.rs, tokio/tests/process_issue_42.rs, tokio/tests/process_smoke.rs
The `tokio::process::Child` type implements `Future` directly which makes it awkward to use, especially when coming from the synchronous version from the standard library. For example, it is impossible to check the status of the command from outside of async contexts.
* Remove the `Future` impl on `Child` in favor of an async `.wait()` method, which mirrors the stdlib API
* Add a `.try_wait()` method similar to the stdlib one. This API will not register for wake ups and is safe to invoke from non-async code
* Both of these methods are "fused" in the sense that repeatedly calling them will always yield the same exit code once the child process has been reaped
* I have changed the `Child::id` method to return an `Option<u32>` to better note that once a child has been reaped, it may not be …
=> process: remove Future impl on Child

tokio/src/sync/notify.rs, tokio/src/sync/tests/loom_notify.rs, tokio/tests/sync_notify.rs
closes https://github.com/tokio-rs/tokio/issues/2813
=> sync: rename `Notify::notify()` -> `notify_one()`

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/builder.rs
Adds a keep_alive attribute in the builder that can be
customized only for the BlockingPool
Fixes: #2585
=> runtime: add custom keep_alive functionality

tokio/src/process/mod.rs, tokio/tests/process_issue_2174.rs
* Calling `child.kill()` but forgetting to call `child.wait().await` or `child.try_wait()` afterwards can lead to zombie processes on Unix platforms
* This changes the `Child::kill` to be an async method which awaits the
child after sending a kill signal.
* A `start_kill` method was also added on `Child` which only sends the
kill signal to the child process. This allows for kill signals to be
sent even outside of async contexts.
cc @Darksonn if you have any thoughts around this beyond what we already discussed!
=> process: make `Child::kill` async

tokio-util/src/either.rs, tokio-util/src/lib.rs
Resolves #1987
`Either` type is rather convenient and may be useful for the broad audience.
Implementation is based on the existing third-party crate: [tokio-either](https://crates.io/crates/tokio-either).
A few more traits were implemented for `Either` type (`std::future::Future` among others), and also boiler-plate code was encapsulated into a single macro.
=> Implement either type

tokio/src/runtime/task/join.rs
This is a WIP PR for implementing a simple form of cancellation, as [mentioned here](https://github.com/tokio-rs/tokio/issues/1819#issuecomment-561796700). Since work on [structured concurrency](#1879) is underway this might not be necessary, but I'm setting this up so that others can have a look and provide input.
While related to structured concurrency it does not replace it. It is only a low-level primitive necessary to perform some best-effort graceful shutdown (#1819) over spawned tasks.
Note that this **does not** allow for graceful termination of tasks spawned with `spawn_blocking` that are actively blocking, which includes most [`File` operations](https://docs.rs/tokio/latest/tokio/fs/struct.File.html).
Warning: Naming is provisional, and certain assumptions around task shutdown …
=> WIP: implement cancellation and raw handles

tokio/src/stream/mod.rs
The module docs for stream were a bit more minimal compared to other modules. This aims to fill in information on some common usage and use-cases where the solution may rely on other crates in the ecosystem or not be intuitive for newcomers.
=> Docs: Module level docs for tokio::stream

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/mod.rs, tokio/src/sync/mpsc/unbounded.rs
I was trying to implement an algorithm that depends on having minimal buffering using a bounded mpsc channel and was moved to find out whether a buffer size of zero was permissible. There is an assertion in the code, but it seems worthy of inclusion in the documentation as well.
Added a note to the documentation on the minimum buffer size being 1.
=> docs: mpsc::bounded minimum buffer size

tokio/src/sync/rwlock.rs
The asynchronous `sync::RwLock` currently provides no way to atomically downgrade a write guard into a read guard, forcing a pattern of dropping the write guard and reacquiring a read guard to achieve a downgrade. In addition to being non-atomic, this makes it easy to accidentally induce a deadlock by forgetting to drop an existing read guard before attempting to acquire a write guard--this is particularly tricky and non-obvious when shadowing the name of the old read guard.
This implements an atomic downgrade operation by taking ownership of a write guard, releasing all but one of the permits it holds, and returning a read guard holding the remaining permit.
=> Write guard to read guard downgrading for sync::RwLock

tokio/src/loom/std/atomic_u16.rs, tokio/src/loom/std/atomic_u32.rs, tokio/src/loom/std/atomic_u8.rs, tokio/src/loom/std/unsafe_cell.rs, tokio/src/sync/notify.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs
Referring to the types in `tokio::sync`.
Also add `const` to `new` for the remaining atomic integers in `src/loom` (except for 64bit which is impossible) and to `UnsafeCell`.
Builds upon previous work in #2790.
Closes #2756.
This PR adds `const_new` to `sync::Notify`, `sync::RwLock`, and `sync::Semaphore`, in addition to the previously added one for `sync::Mutex` as they can all be reasonably be used in `static` variables and this saves the need for (and overhead of) something like `lazy_static` in the case that `parking_lot` already is used internally anyways.
Also, upon encountering the problem of missing `const` for `AtomicU8` in `src/loom` (used in `Notify`), I decided (also for consistency) to add `const` to all the constructors for the remaining types in that directory, whereas …
=> Add const constructors to `RwLock`, `Notify`, and `Semaphore`.

tokio/src/sync/broadcast.rs, tokio/src/sync/mod.rs, tokio/src/sync/semaphore.rs, tokio/src/sync/semaphore_ll.rs
Fixed some typos in sync module.
Fixes  #2781
=> doc: fix some typos

tokio/src/io/seek.rs, tokio/src/io/util/async_seek_ext.rs
[`AsyncSeekExt` requires `io-util` feature](https://github.com/tokio-rs/tokio/blob/207320dbbbacb4e7c8c12f6e94f5e78eb0f055a5/tokio/src/io/mod.rs#L227-L239
), but [doesn't display on docs](https://docs.rs/tokio/0.2.22/tokio/io/index.html#traits).
=> io: fix doc-cfg on AsyncSeekExt

tokio/src/sync/mpsc/chan.rs, tokio/src/sync/semaphore_ll.rs, tokio/tests/sync_mpsc.rs
When the mpsc channel receiver closes the channel, receiving should
return `None` once all in-progress sends have completed. When a sender
reserves capacity, this prevents the receiver from fully shutting down.
Previously, when the sender, after reserving capacity, dropped without
sending a message, the receiver was not notified. This results in
blocking the shutdown process until all sender handles drop.
This patch adds a receiver notification when the channel is both closed
and all outstanding sends have completed.
=> sync: fix missing notification during mpsc close

tokio/src/sync/notify.rs, tokio/src/sync/tests/loom_watch.rs, tokio/src/sync/watch.rs
After chatting with @hawkw I decided to try and tackle #2800. They pointed me to a[ bit of code](https://github.com/tokio-rs/tokio/pull/2814#discussion_r483794400) that might be useful when learning about how the `Notify` type works. I decided to play with loom and see how it works by writing a few tests. Then came around a problem with the `Watch` type. The current loom smoke test for `Watch` exercises only one receiver. Changing the test to have more than one will result in a panic: 
```
running 1 test
test sync::tests::loom_watch::smoke ... thread 'main' panicked at 'assertion failed: !res.is_ready()', tokio/src/sync/watch.rs:258:13
stack backtrace:
0: std::panicking::begin_panic
at /Users/zaharidichev/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/p …
```
=> sync: Remove readiness assertion in `watch::Receiver::changed()

.github/workflows/ci.yml, tokio/src/runtime/builder.rs, tokio/src/runtime/tests/loom_pool.rs, tokio/src/util/bit.rs
https://github.com/tokio-rs/tokio/pull/2858#discussion_r492979753
Seems `RUSTFLAGS: --cfg tokio_unstable` overwriting global `RUSTFLAGS`.
=> ci: deny warnings on '--cfg tokio_unstable' tests

tokio/src/macros/select.rs, tokio/tests/macros_select.rs
=> macros: add #[allow(unused_mut)] to select!

tokio/src/io/mod.rs, tokio/src/io/stderr.rs, tokio/src/io/stdio_common.rs, tokio/src/io/stdout.rs, tokio/tests/io_std.rs
Should fix #2380 (But not tested on a Windows yet)
Wrap `Blocking` in Stdout and Stderr in a specall wrapper, which is completely transparent on Linux and intercepts `write`s on Windows:
1) If input buffer is larger that MAX_BUF, we shrink to to MAX_BUF.
2) If input buffer now has incomplete char at the end, we shrink it too.
It should work, because in general it is ok for `AsyncWrite::write` to write less bytes than requested.
I don't think I can add test for it, because on CI stdout is not handle to console, so no panic can occur.
=> Fix stdout and stderr buffering on windows

tokio/src/io/stdio_common.rs
The PRs #2734 and #2859 broke master when merged together, even though they both built successfully when compiled separately.
=> io: move #[cfg(not(loom))] to fix warning

tokio/src/net/tcp/listener.rs, tokio/src/net/unix/listener.rs
This makes it consistent with `TcpListener::poll_accept` and other
public poll methods the library provides. This particular method is
useful for writing generic code that accepts connections since async
functions can't easily be used with traits. It is possible to
generically accept connections with `Incoming`, however, this doesn't
return the incoming `SocketAddr`.
=> Change `UnixListener::poll_accept` to public

tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs
- Consistency with [stdlib's API](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.get_mut);
- Useful to avoid unnecessary locking.
Add that API
=> Add `get_mut()` for `Mutex` & `RwLock`

tokio/src/io/mod.rs, tokio/src/stream/mod.rs, tokio/src/time/mod.rs
Probably easier to understand. #2873 
before: https://docs.rs/tokio/0.2.22/tokio/io/index.html#structs
after:
=> docs: use #[doc(no_inline)] on re-exports

tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/runtime/context.rs, tokio/src/runtime/driver.rs, tokio/src/signal/windows.rs, tokio/src/sync/mod.rs
* This change will still internally compile any `signal` resources
required when `process` is enabled on unix systems, but it will not
publicly turn on the cargo feature
Fixes #2862
=> process: do not publicly turn on `signal` when enabled

.github/workflows/ci.yml, tokio/Cargo.toml, tokio/src/io/driver/scheduled_io.rs, tokio/src/macros/cfg.rs
Starts the work of removing our "internal" build flags from being public to Cargo.
Refs #2869
=> chore: remove internal io-readiness cargo feature

.github/workflows/ci.yml, tokio/Cargo.toml, tokio/src/loom/std/mod.rs, tokio/src/macros/cfg.rs, tokio/src/runtime/builder.rs
Completes the work of removing our "internal" build flags from being public to Cargo.
Fixes #2869
=> chore: remove internal io-driver cargo feature

tokio/src/io/driver/scheduled_io.rs, tokio/src/io/util/mem.rs, tokio/src/loom/mocked.rs, tokio/src/loom/std/mod.rs, tokio/src/loom/std/mutex.rs, tokio/src/loom/std/parking_lot.rs, tokio/src/park/thread.rs, tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/park.rs, tokio/src/runtime/queue.rs, tokio/src/runtime/thread_pool/idle.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/notify.rs, tokio/src/util/slab.rs
As tokio does not rely on poisoning, we can
avoid always unwrapping when locking by handling
the `PoisonError` in the Mutex shim.
Provide a wrapper around std::sync::Mutex that uses
`PoisonError::into_inner` to ignore the poisoning aspects
of the std api.
Fix #2867
=> chore: handle std `Mutex` poisoning in a shim

tokio/src/sync/mod.rs, tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/tests/loom_mpsc.rs
Adding closed future, makes it possible to select over closed and some other work, so that the task is woken when the channel is closed and can proactively cancel itself.
Added a mpsc::Sender::closed future that will become ready when the receiver is closed
=> sync: add `mpsc::Sender::closed` future

tokio/src/io/driver/scheduled_io.rs, tokio/tests/udp.rs
In the `readiness` future, before inserting a waiter into the list, the current socket readiness is eagerly checked. However, it would return as a `ReadyEvent` the entire socket readiness, instead of just the interest desired from `readiness(interest)`. This would result in the later call to `clear_readiness(event)` removing all of it.
Closes #2886
=> Fix readiness future eagerly consuming entire socket readiness

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs
Closes #2469 
I should note that I looked at mpsc internals first time, so I can be wrong / selected wrong implementation path.
I discovered that both Sender kinds (bounded and Unbounded) implement on top of `tokio::sync::mpsc::Chan`, which in turn uses `Semaphore` trait. I added new method `is_closed` to this trait. I was able to implement it properly for unbounded implementation.
However, I didn't find beautiful way to check if `semaphore_ll` is closed, so I implemented hack (we try to acquire new permit and immediately release it back). While it is inefficient and probably ugly, from the user side it should work OK (for example, it does not mess Sender internal state and it does not take mutable reference to sender).
=> sync: Add `is_closed` method to mpsc senders

tokio-test/src/task.rs
Fix a spelling error in the documentation.
Fixes: #2754
=> test: fix spelling error in documentation

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/oneshot.rs
```
warning: manual implementation of an assign operation
--> tokio/src/sync/batch_semaphore.rs:136:9
|
136 |         permits = permits & Self::MAX_PERMITS;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `permits &= Self::MAX_PERMITS`
|
= note: `#[warn(clippy::assign_op_pattern)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assign_op_pattern
```
=> Fix new clippy warning

tokio/src/fs/read_dir.rs, tokio/src/io/util/lines.rs, tokio/src/io/util/split.rs, tokio/src/macros/scoped_tls.rs, tokio/src/net/tcp/stream.rs, tokio/src/sync/oneshot.rs, tokio/src/sync/tests/loom_oneshot.rs, tokio/src/time/interval.rs, tokio/tests/sync_oneshot.rs, tokio/tests/time_interval.rs
This PR makes many `#[doc(hidden)]` apis private. The remaining `#[doc(hidden)]` apis are either necessary due to e.g. macros, or covered by #2900 or #2898.
Some of the APIs should probably be considered more closely:
1. `TcpStream::connect_std` By experience answering questions, this is something I'd like to have.
2. `oneshot::Sender::poll_closed` Oneshot channels are not intrusive and would not make much sense? Consider keeping?
3. `Interval::poll_tick` Unsure whether intrusive makes sense.
The other changes were either on non-public items or had a readily available alternative in the `Stream` impl that just calls the hidden method.
Please voice your opinions about the three listed APIs below.
=> Make #[doc(hidden)] apis private

tokio/Cargo.toml, tokio/src/io/driver/mod.rs, tokio/src/io/driver/ready.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/io/poll_evented.rs, tokio/src/io/registration.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/mod.rs, tokio/src/net/unix/socketaddr.rs, tokio/src/net/unix/stream.rs, tokio/src/process/unix/mod.rs, tokio/src/process/windows.rs, tokio/src/signal/unix.rs, tokio/src/signal/unix/driver.rs, tokio/tests/uds_datagram.rs
This also makes Mio an implementation detail, removing it from the
public API.
This is based on #1767.
=> io: update to Mio 0.7

tokio/src/fs/os/unix/dir_builder_ext.rs, tokio/src/fs/os/unix/open_options_ext.rs
We don't expect users to implement these extension traits. See also https://github.com/tokio-rs/tokio/pull/2515#issuecomment-626640636.
=> fs: seal OpenOptionsExt and DirBuilderExt

tokio/src/io/stdio_common.rs
(I hope i did not messed up during rebasing)
Performance is cool.
Fixes #2863
Propose algorithm that shrinks text buffers efficiently (now only 32 instead of 16*1024 bytes are checked for utf8)
=> Optimize writing large buffers to windows stdio

tokio/src/sync/broadcast.rs, tokio/tests/sync_broadcast.rs
This PR performs breaking changes to the broadcast channel. Additionally it moves around some functions to make them appear in the right order in the documentation. It may be easier to read the changes one commit at the time.
Fixes: #2261
=> Broadcast channel breaking changes

tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs
mio 0.7 implements `AsRawSocket` (https://github.com/tokio-rs/mio/commit/d077a1e940ad0204b26be7b5612e1e7bf13c2d03), so tokio 0.3 should probably be able to implements `AsRawSocket`.
Closes #2138
Related: #502, #806
=> net: implement AsRawSocket on Windows

tokio/src/io/seek.rs, tokio/src/io/util/async_seek_ext.rs, tokio/src/io/util/flush.rs, tokio/src/io/util/read.rs, tokio/src/io/util/read_exact.rs, tokio/src/io/util/read_int.rs, tokio/src/io/util/read_line.rs, tokio/src/io/util/read_to_end.rs, tokio/src/io/util/read_to_string.rs, tokio/src/io/util/read_until.rs, tokio/src/io/util/shutdown.rs, tokio/src/io/util/write.rs, tokio/src/io/util/write_all.rs, tokio/src/io/util/write_int.rs, tokio/src/stream/all.rs, tokio/src/stream/any.rs, tokio/src/stream/collect.rs, tokio/src/stream/fold.rs, tokio/src/stream/mod.rs, tokio/src/stream/next.rs, tokio/src/stream/try_next.rs
As described in https://github.com/tokio-rs/tokio/pull/2538#issuecomment-654272701, currently, these methods are not `!Unpin`, so switching to async trait methods is a breaking change.
Make these future `!Unpin` for compatibility with async trait methods. This can implement this by adding a *pinned* `PhantomPinned` field, [as described in the pin-project documentation](https://docs.rs/pin-project/0.4.26/pin_project/attr.pin_project.html#unpin).
Related: #2723, #2259
=> Make futures returned by extension traits !Unpin

tokio-util/Cargo.toml, tokio-util/src/lib.rs, tokio-util/src/time/delay_queue.rs, tokio-util/src/time/mod.rs, tokio-util/src/time/wheel/level.rs, tokio-util/src/time/wheel/mod.rs, tokio-util/src/time/wheel/stack.rs, tokio-util/tests/time_delay_queue.rs, tokio/Cargo.toml, tokio/src/time/mod.rs
This change is intended to do the minimum to unblock 0.3; as such, for now, we
duplicate the internal `time::wheel` structures in tokio-util, rather than trying
to refactor things at this stage.
=> time: Move DelayQueue to tokio-util

tokio/src/macros/cfg.rs, tokio/src/process/mod.rs, tokio/src/process/unix/driver.rs, tokio/src/process/unix/mod.rs, tokio/src/process/unix/orphan.rs, tokio/src/process/unix/reap.rs, tokio/src/runtime/driver.rs, tokio/src/signal/unix.rs, tokio/src/signal/unix/driver.rs
* Dropping/canceling child processes cannot be done cleanly since we can neither afford to perform a blocking `wait` call in the destructor, nor do we have something like async-destructors to perform the clean up for us
* Although the `kill_on_drop` flag will terminate the child process on drop, there is no guarantee that the caller will call `child.await` which will leave a zombie process floating around and can lead to exhaustion of the pid space
* We do try to clean up orphaned processes on a best-effort-basis, as long as additional child processes are being spawned/polled, but this isn't good enough since enough zombie processes can accumulate through one way or another
* Introduce a `ProcessDriver` (only on Unix platforms) which will reap the orphaned processes spawned by tokio, …
=> process: add ProcessDriver to handle orphan reaping

tokio/src/net/udp/socket.rs
I always found the udp docs a little lackluster, after using them extensively for some time I thought it might be nice to flesh it out a bit. I asked in the tokio-docs discord and others seemed open to it, so here they are! Would love to hear your thoughts
A few small code examples similar to the way the tcp section is set up, with an explanation of the different ways to use `UdpSocket`.
~~I had a full larger example with `split` but found that it's been removed for `UdpSocket` in master, I hope that's temporary, if not is there anything I can do to get similar functionality back? i.e. being able to `send_to`/`recv_from` concurrently~~
~~In writing an example using the new way to share `UdpSocket` concurrently (post-`split`) I think I found a bug~~ this bug was fixed #2886
=> docs: More docs for UdpSocket

tokio/src/fs/open_options.rs, tokio/src/fs/os/unix/dir_entry_ext.rs, tokio/src/fs/os/unix/mod.rs, tokio/src/fs/os/unix/open_options_ext.rs, tokio/src/fs/read_dir.rs
Closes #2912
Refs: [std's `DirEntryExt`](https://doc.rust-lang.org/nightly/std/os/unix/fs/trait.DirEntryExt.html)
=> fs: switch to our own DirEntryExt trait

tokio-util/src/either.rs, tokio/src/fs/file.rs, tokio/src/io/async_seek.rs, tokio/src/io/seek.rs
To remove the Poll from `start_seek` and rely on `poll_ready` instead
Fix: #1994
=> io: remove `Poll` from the `AsyncSeek::start_seek` return value

tokio/src/fs/open_options.rs, tokio/src/fs/os/windows/mod.rs, tokio/src/fs/os/windows/open_options_ext.rs
Refs: [std's windows `OpenOptionsExt`](https://doc.rust-lang.org/nightly/std/os/windows/fs/trait.OpenOptionsExt.html)
=> fs: add os::windows::OpenOptionsExt

tokio-test/src/io.rs, tokio-test/tests/block_on.rs, tokio-util/src/time/delay_queue.rs, tokio/src/lib.rs, tokio/src/macros/select.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/stream/throttle.rs, tokio/src/stream/timeout.rs, tokio/src/sync/mod.rs, tokio/src/time/clock.rs, tokio/src/time/driver/entry.rs, tokio/src/time/driver/mod.rs, tokio/src/time/error.rs, tokio/src/time/interval.rs, tokio/src/time/mod.rs, tokio/src/time/sleep.rs, tokio/src/time/tests/mod.rs, tokio/src/time/tests/test_sleep.rs, tokio/src/time/timeout.rs, tokio/src/time/wheel/mod.rs, tokio/tests/macros_select.rs, tokio/tests/rt_common.rs, tokio/tests/stream_timeout.rs, tokio/tests/time_sleep.rs
Most usages of, and references to `delay` and `Delay` are also removed from docs, tests and comments, except for places where I believe it makes sense to keep referring to  instances of `Sleep` as `delays`.
Examples of this are `time::Interval`, `time::Timeout` and `stream::Throttle`. `DelayQueue` also remains mostly unchanged.  
follow-up to #2826, part of #2928
=> time: rename `Delay` future to `Sleep`

tokio/src/sync/broadcast.rs, tokio/src/sync/tests/loom_broadcast.rs, tokio/tests/sync_broadcast.rs
Refs: #2928
This also adds missing `{Display, Error}` impls for `broadcast::error::SendError`.
=> sync: move broadcast error types into broadcast::error module

tokio/src/net/unix/ucred.rs, tokio/tests/uds_cred.rs
=> net: make UCred fields private

tokio/src/lib.rs
=> chore: remove use of doc_alias feature

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/tests/loom_mpsc.rs
Changes `UnboundedSender::closed` and `Sender::closed` to not take `self` as `mut`
Refs: #2928
=> sync: change chan `closed(&mut self)` to `closed(&self)`

tokio-test/src/io.rs, tokio-util/src/compat.rs, tokio-util/src/io/stream_reader.rs, tokio-util/tests/framed_read.rs, tokio-util/tests/io_reader_stream.rs, tokio-util/tests/length_delimited.rs, tokio/src/io/async_read.rs, tokio/src/io/blocking.rs, tokio/src/io/poll_evented.rs, tokio/src/io/read_buf.rs, tokio/src/io/util/buf_reader.rs, tokio/src/io/util/mem.rs, tokio/src/io/util/repeat.rs, tokio/src/io/util/take.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/unix/stream.rs, tokio/tests/io_copy.rs, tokio/tests/io_read.rs, tokio/tests/io_split.rs
This changes `ReadBuf::add_filled` to `ReadBuf::advance` and
`ReadBuf::append` to `ReadBuf::put_slice`. This is just a
mechanical change.
Closes #2769
=> io: Rename `ReadBuf` methods

tokio-util/src/time/delay_queue.rs, tokio/src/stream/timeout.rs, tokio/src/time/driver/atomic_stack.rs, tokio/src/time/driver/entry.rs, tokio/src/time/driver/mod.rs, tokio/src/time/error.rs, tokio/src/time/mod.rs, tokio/src/time/sleep.rs, tokio/src/time/timeout.rs, tokio/src/time/wheel/mod.rs
=> time: move error types into `time::error`

benches/signal.rs, benches/sync_semaphore.rs, tokio/src/runtime/builder.rs
=> rt: `worker_threads` must be non-zero

tokio/src/runtime/driver.rs, tokio/src/util/linked_list.rs
* rt: optimize usage of either when creating a runtime::Driver
* chore: fix unused warning for LinkedList::last on Windows
Fixes #2916
=> chore: refactor runtime driver useage of `Either` and cfgs

tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/net/addr.rs, tokio/src/net/lookup_host.rs, tokio/src/net/mod.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs
This combines the `dns` and `net` feature flags. Previously, `dns` was
included as part of `net`. Given that is is rare that one would want
`dns` without `net`, DNS is now entirely gated w/ `net`.
The `parking_lot` feature is included as part of `full`.
Some misc docs are tweaked to reflect feature flag changes.
=> meta: combine `net` and `dns`, use `parking_lot`

tokio/src/process/mod.rs
Update the `process` docs to explain how we handle orphaned/dropped child processes
Refs #2685
Refs #2841
=> process: update docs regarding zombie processes

tokio-util/src/context.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/context.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/tests/loom_blocking.rs, tokio/src/signal/windows.rs, tokio/tests/io_driver.rs, tokio/tests/io_driver_drop.rs, tokio/tests/rt_common.rs
A RAII guard pattern is more flexible than taking a closure.
=> rt: switch `enter` to an RAII guard

tokio/src/runtime/builder.rs, tokio/src/runtime/mod.rs
This PR updates the runtime module docs to the changes made in `0.3`
release of tokio.
Closes #2720
=> rt: Update docs for `0.3` changes

.github/workflows/ci.yml
This branch no longer actively developed. Most commits to this branch are backporting and should not be blocked by clippy.
=> v0.2.x: disable clippy check

.github/workflows/ci.yml
clippy does not consider our MSRV. And sometimes add new lints and block unrelated PR.
As discussed in discord, these issues should be workaround by running clippy on MSRV.
=> ci: run clippy on MSRV

tokio-macros/src/entry.rs, tokio-util/Cargo.toml, tokio-util/src/cfg.rs, tokio-util/src/context.rs, tokio-util/src/lib.rs, tokio-util/tests/context.rs, tokio/src/lib.rs, tokio/tests/macros_select.rs, tokio/tests/rt_common.rs, tokio/tests/stream_stream_map.rs, tokio/tests/sync_broadcast.rs, tokio/tests/time_delay_queue.rs
Back porting https://github.com/tokio-rs/tokio/pull/2791 to `v0.2.x`
Co-authored-by: Lucio Franco <luciofranco14@gmail.com>
=> util: Add `TokioContext` future (#2791)

tokio-macros/CHANGELOG.md, tokio-test/CHANGELOG.md, tokio-util/CHANGELOG.md, tokio/CHANGELOG.md, tokio/Cargo.toml
=> chore: prepare for v0.3.0 release

tokio/src/io/async_read.rs
Documentation incorrectly mentions `Ok(n)` which is fixed here. Also adds a hint (twice) informing the reader how to check for EOF since it might be non-obvious.
=> Update documentation of AsyncRead to reflect use of ReadBuf

tokio/src/io/async_read.rs, tokio/src/runtime/builder.rs
=> Fix doc typos

tokio/src/net/udp/socket.rs
Following up on a previous PR that added docs for `UdpSocket`, I just noticed when viewed in the web UI the first paragraph didn't look right, made a few tweaks to fix that up
=> docs: fix typos on UdpSocket

tokio/src/sync/broadcast.rs, tokio/src/sync/tests/loom_broadcast.rs
Implement `Clone` for the `broadcast::Receiver` type using the same code as is used in `broadcast::Sender::subscribe`.  
I'm working on an API where I need a channel with the "multiple consumer" ability that the broadcast channel has, but I don't need multiple producers. I can't use a watch channel because I would like to at least know when messages have been missed.  Because the producer is singular it makes sense for my API to only expose the broadcast Receiver. However, since the only way to create new Receivers right now is by having a Sender handle, this doesn't work.
On looking at the code it seemed like implementing `Clone` for the Receiver would be pretty trivial, and it makes the API substantially more flexible, especially for my usage.
I simply copied and pasted the code used in …
=> sync: implement Clone for broadcast::Receiver

tokio-util/src/io/mod.rs, tokio-util/src/io/poll_read_buf.rs, tokio-util/src/io/read_buf.rs
While working to migrate a project to `0.3.0` I found uses of the now deprecated `poll_read_buf` API that needed to be migrated. This turned out to be nontrivial for types implementing `BufMut` which does not immediately provide an API to access an underlying contiguous buffer like [Chain](https://docs.rs/bytes/0.5.6/bytes/buf/ext/struct.Chain.html).
This adds a shim for it which provides the old API to ease migrations to `0.3.0`. The naming and shape of the API is preliminary and I'll happily move and rename it to whatever is appropriate if it warrants inclusion. At the very least I'm putting it here in the hope so that people who are currently migrating might find it. It might also be a good idea to provide it as a library function since the generic implementation involves a sprinkle of …
=> Add a poll_read_buf shim to tokio-util to mimic now deprecated AsyncRead API

tokio/src/runtime/mod.rs
[Current-Thread Scheduler] docs say `rt-core` but it should be`rt`.
[Current-Thread Scheduler]: https://docs.rs/tokio/0.3.0/tokio/runtime/index.html#current-thread-scheduler
=> docs: fix typo in runtime module documentation

tokio/src/runtime/mod.rs
This allows writing
```
rt.spawn_blocking(f);
```
instead of
```
let _enter = rt.enter();
tokio::task::spawn_blocking(f);
```
=> tokio: add Runtime::spawn_blocking

tokio/src/runtime/mod.rs
These are inside an `cfg_rt!` block, so have no effect.
=> runtime: remove unneeded #[cfg(feature = "rt")]

tokio/src/net/tcp/listener.rs
Docs: TcpListener::from_std does no longer put the socket in nonblocking mode by itself.
Other things in this part seemed outdated as well so the second commit removes those. There is no `addr` argument or `Handle::tcp_listen` as far as I can tell. I also stole the line from mio that the socket is not set to nonblocking mode.
Fixes #3001
=> Docs: Adjust TcpListener::from_std documentation to match behavior

tokio/src/fs/file.rs, tokio/tests/fs_file.rs
Fixes: #2950
file should be flushed on shutdown.
call `poll_flush` on shutdown
=> fs: flush on shutdown

tokio/src/sync/semaphore.rs
Remove an unnecessary `Arc::clone` in `Semaphore::acquire_owned` and `Semaphore::try_acquire_owned`
=> sync: remove extra clone in `Semaphore::[try_]acquire_owned()`

tokio/Cargo.toml, tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/read_buf.rs, tokio/src/io/util/read_to_end.rs, tokio/src/io/util/write_buf.rs, tokio/tests/io_read.rs, tokio/tests/io_read_buf.rs, tokio/tests/io_write_buf.rs
Brings back `read_buf` from 0.2. This will be stabilized as part of 1.0.
I need to add tests still.
=> io: add `AsyncReadExt::read_buf`

.github/workflows/ci.yml, tokio/src/util/slab.rs
An off-by-one bug results in freeing the incorrect page.
Fixes: #3014
=> net: fix use-after-free in slab compaction

tokio/src/sync/broadcast.rs, tokio/src/sync/tests/loom_broadcast.rs
The `Receiver` handle maintains a position in the broadcast channel for
itself. Cloning implies copying the state of the value. Intuitively,
cloning a `broadcast::Receiver` would return a new receiver with an
identical position. However, the current implementation returns a new
`Receiver` positioned at the tail of the channel.
This behavior subtlety is why `new_subscriber()` is used to create
`Receiver` handles. An alternate API should consider the position issue.
Because we need a bug-fix release, this API change is reverted now until
the issues can be discussed.
Refs: #2933
=> sync: revert Clone impl for broadcast::Receiver

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
Fix the use-after-free.
Depends on #3020
=> chore: prepare v0.3.1 release

tokio/src/net/udp/socket.rs, tokio/tests/udp.rs
As discussed in #2830 the first step to getting `UdpFramed` back is the poll functions. I've added these back, following the new style.
I could have just re-enabled `UdpFramed` on this PR too, but I thought we might take the opportunity to discuss any changes that we may want to make to that. In it's current state it still requires a split-like API to do concurrent send/recv
=> tokio: Add back poll_* for udp

tokio/Cargo.toml, tokio/src/io/async_fd.rs, tokio/src/io/driver/mod.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/io/mod.rs, tokio/src/lib.rs, tokio/src/loom/std/mod.rs, tokio/src/loom/std/parking_lot.rs, tokio/tests/io_async_fd.rs
This adds AsyncFd, a unix-only structure to allow for read/writability states
to be monitored for arbitrary file descriptors.
Issue: #2728
See #2728 for the motivation for this change.
This introduces a new `AsyncFd` type which can be used to monitor arbitrary file descriptors for readability and writability. I've chosen not to expose a `poll_*` API as callers can emulate such an API on their own (an example is given in the rustdocs). I've also avoided exposing specific `Ready`/`Interest`-like types (this could be added in the future in a backwards-compatible way).
I'm a little bit uncomfortable with how the cfg-macros work out here - I had to touch quite a few places to add the `async-fd` feature flag. That feels like a refactor for another PR however.
=> io: Add AsyncFd

tokio/src/sync/rwlock.rs, tokio/src/sync/tests/loom_rwlock.rs, tokio/src/sync/tests/mod.rs
Currently when `RwLockWriteGuard::downgrade` the `MAX_READS - 1`
permits are added to the semaphore. When `RwLockWriteGuard::drop`
gets invoked however another `MAX_READS` permits are added. This
results in releasing more permits that were actually aquired when
downgrading a write to a read lock. 
This is why we need to call
`mem::forget` on the `RwLockWriteGuard` in order to avoid
invoking the destructor.
Additionally doc test for `downgrade` was not correct as it can hang in the situation where after downgrading all available permits are assigned to the waiting writer before the additional reader gets the change to obtain a permit.
Fixes: #2941
=> sync: add mem::forget to RwLockWriteGuard::downgrade.

tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs
Fixes: #3007
Some of the docs for `from_std` methods are outdated.
Update and unify docs.
=> docs: update docs for `from_std` functions

tokio-macros/src/entry.rs, tokio-macros/src/lib.rs
The macro argument `max_threads`  was removed by #2876 but is still mentioned in an error message and `test_rt` docs.
=> docs: remove `max_threads` mentions in tokio-macros

README.md, tokio/README.md
MSRV is 1.45.2 for CI but readme says 1.39
closes: #3047
=> readme: update the MSRV to 1.45

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs
- fix incorrect docs regarding `max_threads` option (#3038)
=> Prepare tokio-macros 0.3.1

tokio/src/sync/oneshot.rs
The documentation currently uses `futures::select!`. Change it to use `tokio::select!` and also remove a race-condition in the example.
=> Update oneshot::Receiver::closed() docs to use tokio::select!

tokio/src/net/tcp/listener.rs, tokio/src/net/udp/socket.rs
Fixes: #3034
net2 is deprecated
change mention of net2 to socket2
=> net: change mention of net2

examples/Cargo.toml, tokio-util/Cargo.toml, tokio-util/src/codec/framed_impl.rs, tokio-util/src/io/mod.rs, tokio-util/src/io/poll_read_buf.rs, tokio-util/src/io/read_buf.rs, tokio-util/src/io/reader_stream.rs, tokio-util/src/lib.rs, tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/read_buf.rs, tokio/tests/io_read_buf.rs
This reverts commit fe2b9976755407b85c82b5cdee9d8c5e16e3d6c6.
We are avoiding adding `poll_read_buf` to `tokio` itself for **now**. The patch is reverted now in order to not block the v0.3.2 release (#3059).
=> Revert "util: upgrade tokio-util to bytes 0.6 (#3052)"

tokio/Cargo.toml
Signed-off-by: Tom Kaitchuck <Tom.Kaitchuck@gmail.com>
`fnv` is not actually used.
Remove the dependency.
=> Remove unused dependency on Fnv

tokio/src/runtime/mod.rs
I assume this is a documentation mistake. It doesn't panic if "not called from async context".
=> Runtime::block_on should NOT be called from async context

examples/Cargo.toml, tokio-util/Cargo.toml, tokio-util/src/lib.rs
Copies the implementation of poll_read_buf() from tokio::io::util::read_buf.
=> util: update to bytes 0.6

tokio/src/net/unix/ucred.rs
Fixed: #2632
Provided pid as Option<libc::pid_t> so solaris and macos does not break.
=> add pid to tokio::net::unix::UCred

tokio-util/CHANGELOG.md, tokio-util/src/codec/framed_impl.rs, tokio-util/src/io/mod.rs, tokio-util/src/io/read_buf.rs, tokio-util/src/io/reader_stream.rs, tokio-util/src/lib.rs
This was accidentally removed in #3064.
=> util: add back public poll_read_buf() function

tokio/Cargo.toml, tokio/build.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/task/blocking.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs, tokio/src/util/trace.rs
Currently, the per-task `tracing` spans generated by tokio's `tracing`
feature flag include the `std::any::type_name` of the future that was
spawned. When future combinators and/or libraries like Tower are in use,
these future names can get _quite_ long. Furthermore, when formatting
the `tracing` spans with their parent spans as context, any other task
spans in the span context where the future was spawned from can _also_
include extremely long future names.
In some cases, this can result in extremely high memory use just to
store the future names. For example, in Linkerd, when we enable
`tokio=trace` to enable the task spans, there's a spawned task whose
future name is _232990 characters long_. A proxy with only 14 spawned
tasks generates a task list that's over 690 KB. Enabling task …
=> tracing: replace future names with spawn locations in task spans

tokio/CHANGELOG.md
The behavior of the `from_std` changes was a consequence of the upgrade to mio 0.7, but was not mentioned in the changelog. Since many people have been bitten by this, I think it makes sense to add it to the changelog.
I used #2893 as the PR as it is the update of mio.
=> doc: add from_std change to CHANGELOG

tokio/src/net/tcp/socket.rs
Recently updated mio tcp sockets with getter/setter for `SO_REUSEPORT` and also added `TcpSocket::get_localaddr` and `TcpSocket::get_reuseaddr`.
This PR is just to make it available for tokio `TcpSocket`
=> net: Add get/set reuseport and get_localaddr/reuseaddr for TcpSocket

tokio/src/stream/stream_map.rs
Right now `StreamMap` implements `Default` only if both the stream and the key do too. This doesn't make sense, but is enforced because of deriving. This PR replaces this with manual `Default` implementation that is an alias for `StreamMap::new`.
=> StreamMap: fix Default bound

tokio-util/src/time/delay_queue.rs
In tokio 0.3, `DelayQueue` is moved to tokio-util. However, stream flag is forgotten to expose.
```
[features]
default = []
full = ["codec", "compat", "io", "time"]
compat = ["futures-io",]
codec = ["tokio/stream"]
time = ["tokio/time","slab"]
io = []
rt = ["tokio/rt"]
[dependencies]
```
Then it is not possible to unlock `Stream` impl for `DelayQueue`.
```rust
#[cfg(feature = "stream")]
impl<T> futures_core::Stream for DelayQueue<T> {
```
This PR removes stream feature lock from `DelayQueue`. As future_cores is linked with tokio-util by default there is no reason to hide the impl by a feature flag.
=> util: remove stream feature flag from DelayQueue

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/thread_pool/mod.rs
- make the `Handle` type public
- make `Runtime::spawn` and `Runtime::spawn_blocking` just thin wrappers around new public methods from `Handle`
- introduce `handleEnterGuard` to bring back `Handle::enter` (not sure if it's the right call here)
- didn't bring back `Handle::block_on` (not sure if that's something we want, feels less trivial to do, and maybe not that useful)
- brought back `Handle::current` and `Handle::try_current`
Fixes #2965
=> rt: bring back a public Handle type

tokio/src/runtime/blocking/pool.rs
This removes the last slab dependency by replacing the current slab-based
JoinHandle tracking with one based on HashMap instead.
Cleaning up dependencies
Slab was only used to track JoinHandles to ensure that all threads are fully cleaned up before returning from `shutdown` (this, in turn, is intended to avoid valgrind false-positives). Since this path isn't particularly performance-critical, this change replaces this use case with a HashMap instead.
=> runtime: Remove last slab dependency

tokio/src/net/unix/ucred.rs
This PR adds the PID to the `UCred` reported by `get_peer_cred()` for Solaris and Illumos.
Additionally, it removes manual `extern "C" { ... }` and just calls definitions from `libc`.
=> Report PID in UCred for Solaris and Illumos.

tokio/src/io/async_fd.rs, tokio/tests/io_async_fd.rs
=> async_fd: make into_inner() deregister the fd

tokio/Cargo.toml
nix 0.18 -> 0.19
proptest 0.9 -> 0.10
(Note: both are dev-deps)
=> chore: update proptest and nix

tokio/src/sync/semaphore.rs
Fixes: #1550
Add support for acquiring multiple permits on the `Sempahore` public api.
I changed the permits field type from `u16` to `u32`  on `Semaphore` and `OwnedSemaphorePermit` to match the `batch_semaphore` lower level implementation which was introduced with #2607. 
I added `acquire_many` and `try_acquire_many` methods to the `Semaphore` to add multiple permit acquisition functionality. I believe that these new methods have test coverage by the existing `batch_semaphore` tests.
=> tokio-sync: add acquire_many and try_acquire_many methods to Sempahore

tokio/src/io/async_fd.rs, tokio/src/io/driver/mod.rs, tokio/src/io/mod.rs, tokio/src/io/registration.rs, tokio/tests/io_async_fd.rs
Removes some code duplication between `AsyncFd` and `Registration`.
The `AsyncFd::readiness()` fn will now return `Err` when the runtime is dropped. This lines up w/ socket types.
I also reordered some code in `async_fd.rs` to match the style used elsewhere (structs at the top, impls after).
=> io: update AsyncFd to use Registration

.github/workflows/ci.yml, tokio/Cargo.toml
Some small cleanup items are apparent after merge of #2951
Delete a now incorrect comment in Cargo.toml, and remove a now redundant CI test step.
=> Minor cleanup of parking_lot feature, now in full

tokio/src/io/async_fd.rs, tokio/src/io/driver/interest.rs, tokio/src/io/driver/mod.rs, tokio/src/io/driver/ready.rs, tokio/src/io/driver/registration.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/io/mod.rs, tokio/src/io/poll_evented.rs, tokio/src/macros/cfg.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs, tokio/src/process/mod.rs, tokio/src/process/unix/mod.rs, tokio/src/signal/unix/driver.rs
* Removes duplicated code by moving it to `Registration`.
* impl `Deref` for `PollEvented` to avoid `get_ref()`.
* Avoid extra waker clones in I/O driver.
* Add `Interest` wrapper around `mio::Interest`.
To make this work, `process` had to move away from using the `std` process types as they do not implement `Read` / `Write` for &ChildStdin (etc...).
=> io: driver internal cleanup

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs
- disambiguate the built-in `#[test]` attribute in macro expansion (#2503)
- warn about renaming the Tokio dependency (#2521)
- various documentation changes (#2683, #2697)
=> chore: prepare tokio-macros v0.2.6

.github/workflows/ci.yml, tokio/Cargo.toml
This checks that crates compile with the minimum allowed version of each dependency.
=> ci: minimal version check

.github/workflows/ci.yml, tokio-util/Cargo.toml, tokio/Cargo.toml
This checks that crates compile with the minimum allowed version of each dependency.
Backport of #3131
=> ci: minimal version check (v0.2.x)

tokio/src/io/driver/interest.rs, tokio/src/io/driver/mod.rs, tokio/src/io/driver/ready.rs, tokio/src/io/driver/registration.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/io/mod.rs, tokio/src/macros/cfg.rs, tokio/src/net/tcp/stream.rs, tokio/src/signal/unix/driver.rs, tokio/tests/tcp_stream.rs
Adds function to await for readiness on the TcpStream and non-blocking read/write functions.
`async fn TcpStream::ready(Interest)` waits for socket readiness satisfying **any** of the specified interest. There are also two shorthand functions, `readable()` and `writable()`.
Once the stream is in a ready state, the caller may perform non-blocking operations on it using `try_read()` and `try_write()`. These function return `WouldBlock` if the stream is not, in fact, ready.
The await readiness function are similar to `AsyncFd`, but do not require a guard. The guard in `AsyncFd` protect against a potential race between receiving the readiness notification and clearing it. The guard is needed as Tokio does not control the operations. With `TcpStream`, the `try_read()` and `try_write()` …
=> net: add TcpStream::ready and non-blocking ops

tokio/src/net/tcp/socket.rs
This adds the missing `net` feature flag in the generated API
documentation.
=> net: add missing doc cfg on TcpSocket

tokio-util/Cargo.toml, tokio/Cargo.toml
This release added support for enum, but all enums that require pin-projection used in tokio/tokio-util have tuple variants and are also public APIs. So, unfortunately, we cannot use pin-project-lite for these enums.
=> chore: update pin-project-lite to 0.2.0

tokio/Cargo.toml, tokio/src/net/tcp/socket.rs
This commit adds `set_{send, recv}_buffer_size` methods to `TcpSocket`
for setting the size of the TCP send and receive buffers, and 
`{send, recv}_buffer_size` methods for returning the current value. These
just call into similar methods on `mio`'s `TcpSocket` type, which were 
added in tokio-rs/mio#1384.
Refs: #3082
=> net: Add send/recv buf size methods to `TcpSocket`

tokio/src/sync/mpsc/chan.rs, tokio/src/sync/notify.rs, tokio/src/sync/tests/loom_notify.rs, tokio/src/sync/watch.rs, tokio/tests/sync_notify.rs
Previously in order for the consumer to
register interest, in a notification triggered by
`notify_waiters`, the `Notified` future had to be
polled. This introduced friction when using the api
as the future had to be pinned before polled.
This change introduces a counter that tracks how many
times `notified_waiters` has been called. Upon creation of
the future the number of times is loaded. When first
polled the future compares this number with the count
state of the `Notify` type. This avoids the need for
registering the waiter upfront.
Fixes: #3066
=> Avoid pinning notified future

tokio/src/net/tcp/stream.rs, tokio/src/net/udp/socket.rs, tokio/tests/udp.rs
Adds `ready()`, `readable()`, and `writable()` async methods for waiting
for socket readiness. Adds `try_send`, `try_send_to`, `try_recv`, and
`try_recv_from` for performing non-blocking operations on the socket.
This is the UDP equivalent of #3130.
=> net: add UdpSocket readiness and non-blocking ops

tokio/Cargo.toml, tokio/src/net/tcp/stream.rs, tokio/tests/tcp_stream.rs
The ability to set_linger option on a TcpStream was removed in v0.3 so that TcpStream could be similar to std. I wasn't able to find the reason for why this `set_linger` was removed from std's TcpStream.
This PR reintroduces this option.
Convert the stream using it's raw fd to get a mio TcpSocket and set the option.
=> net: reintroduce getter/setter for SO_LINGER to tokio::net::tcp::stream

tokio/src/io/async_write.rs, tokio/src/io/poll_evented.rs, tokio/src/net/tcp/split.rs, tokio/src/net/tcp/split_owned.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/unix/split.rs, tokio/src/net/unix/split_owned.rs, tokio/src/net/unix/stream.rs
This adds `AsyncWrite::poll_write_vectored`, and implements it for
`TcpStream` and `UnixStream`. Based on the proposal in #3135.
=> io: reintroduce vectored writes

tokio-macros/src/entry.rs
Looks like the Rust 1.48.0 version of `rustfmt` changed some formatting
rules (fixed some bugs?), and some of the code in `tokio-macros` is no
longer correctly formatted. This is breaking CI.
This commit runs rustfmt on Rust 1.48.0. This fixes CI.
Closes #3158
=> macros: fix rustfmt on 1.48.0

tokio-util/src/codec/framed_read.rs
fix #3165 
Can this PR also be patched to the 0.3.x version of `tokio-util`?
=> feat: add mutable buffer api to FramedRead

tokio/src/time/driver/handle.rs
It appears that part of commit ae67851f may have had a partial search-and-replace of "ts" with "ClockTime" - just in one file. This just replaces those `ClockTime`s with `ts` to change the relevant pieces of those comments to what they were before.
=> replace 'ouClockTimeide' in internal docs with 'outside'

tokio-macros/src/lib.rs
1. Changed 0.2 to 0.3
2. Changed ‘multi’ to ‘single’ to indicate that the behavior is single threaded
Closes: #3177
=> Fix outdated macro documentation

tokio/src/runtime/blocking/shutdown.rs
After a brief discussion with @Darksonn about the precise behavior given by various methods of shutting down a `Runtime` (dropping it, [`shutdown_timeout`](https://docs.rs/tokio/0.3.4/tokio/runtime/struct.Runtime.html#method.shutdown_timeout), `shutdown_background`), I was experimenting with the available options to try to determine the differences between them.
During this experimentation, I discovered that calling `rt.shutdown_timeout(Duration::from_nanos(0))` actually *does* wait until all blocking tasks finish, contrary to what would be expected. This is notably different from if we passed `Duration::from_nanos(1)` instead, which has the effect of shutting down immediately. As best I can tell, this is a bug.
[Here's a sample program on the playground that demonstrates this …
=> fix `shutdown_timeout(0)` blocking

tokio/tests/rt_common.rs
Solves issue #3193 
Added a regression test to make sure that `Runtime::shutdown_timeout` with `Duration::from_nanos(0)` instantly shuts down instead of waiting forever for all tasks.
Spawn a task that sleeps for 10k seconds, then time the call to `shutdown_timeout` with a zero duration. Assert that actual time to shutdown should be <1 second.
=> add test for regression with shutdown_timeout 0

tokio-macros/src/lib.rs
Mention that tokio::main could be use in any function.
Fix #3195
It is not easy to discover that `#[tokio::main]` could be used for non-main functions.
Explain this in docs, maybe it would be better to show an example.
=> Add portability note to tokio::main

tokio/src/io/async_fd.rs
Expose `Interest` customization for `AsyncFd`
Fixes #3072
=> Add AsyncFd::with_interest

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- rt: fix `shutdown_timeout(0)` (#3196).
- time: fixed race condition with small sleeps (#3069).
- io: `AsyncFd::with_interest()` (#3167).
- signal: `CtrlC` stream on windows (#3186).
=> chore: prepare v0.3.5 release

.cirrus.yml
It was temporarily disabled in 06c473e62842d257ed275497ce906710ea3f8e19
and never reenabled.
=> Reenable CI on FreeBSD i686

.cirrus.yml, tokio/tests/process_kill_on_drop.rs
"disown" is a bash builtin, not part of POSIX sh.
While running the tests locally on FreeBSD, I noticed a console message about "disown not found".  The fact that the test passed suggests that there may be something wrong with its logic, but I didn't investigate further.
Always execute this script with bash instead of sh.
=> Fix the process_kill_on_drop.rs test on non-Linux systems

examples/udp-codec.rs
UdpFramed is enabled, so add back udp-codec example.
=> example: add back udp-codec example

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/semaphore.rs, tokio/tests/sync_semaphore.rs
Fixed incorrect shift in the assignment of permits on batch_semaphore.rs
Fixes: #3095
=> sync: add_permits does not panic with usize::MAX >> 3

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml, tokio-util/src/lib.rs
- io: `poll_read_buf` util fn (#2972).
- io: `poll_write_buf` util fn with vectored write support (#3156).
=> util: prepare v0.5.1 release

tokio/src/runtime/thread_pool/worker.rs, tokio/tests/task_abort.rs
We have an issue in #3157 where a call to `JoinHandle::abort` releases a task, causing a panic because the current implementation of `release` for a thread pool requires it to be called from within a worker context.
This change makes access of  the thread-local context optional under release, by falling back to remotely marking a task remotely as dropped. Behaving the same as if the core was stolen by another worker.
Needs a review by someone familiar with the scheduler, cause I'm not entirely sure I've grok:ed the internals well enough.
=> Support aborting a task remotely in a multithreaded runtime without panicking

tokio/Cargo.toml, tokio/src/process/unix/mod.rs, tokio/src/signal/registry.rs
`once_cell` is a macro-free alternative to `lazy_static`. Its `Lazy` type has the same API as `lazy_static`, but it will not use any "macro magic" and it might be more clear to read by non-experienced Rust developers.
This solution is being proposed to be implemented at the Rust standard library level with an [RFC](https://github.com/rust-lang/rfcs/pull/2788). This could be an opportunity to migrate to the new solution and to check that everything is working correctly in Tokio.
Furthermore, as per [this](https://github.com/async-rs/async-std/issues/406#issuecomment-547286625) comment, it seems that due to a possible compiler bug, using `once_cell` is noticeably faster than `lazy_static` in certain hot get operations.
This PR replaces all mentions to `lazy_static` by `once_cell` using the …
=> Replace lazy_static with once_cell

tokio/src/io/poll_evented.rs, tokio/src/net/tcp/stream.rs, tokio/tests/tcp_into_std.rs
Closes https://github.com/tokio-rs/tokio/issues/3031
1. Add an `into_inner` method on `PollEvented`. Make sure to deregister the stream from Tokio.
2. Convert the `mio` tcp stream into an std one. Go through mio's `IntoRawFd` to do so.
=> io: add a into_std method for tokio's TcpStream

tokio/src/runtime/thread_pool/worker.rs, tokio/src/time/driver/mod.rs, tokio/tests/rt_threaded.rs
Previously, the runtime shutdown logic would first hand control over all cores
to a single thread, which would sequentially shut down all tasks on the core
and then wait for them to complete.
This could deadlock when one task is waiting for a later core's task to
complete. For example, in the newly added test, we have a `block_in_place` task
that is waiting for another task to be dropped. If the latter task adds its
core to the shutdown list later than the former, we end up waiting forever for
the `block_in_place` task to complete.
Additionally, there also was a bug wherein we'd attempt to park on the parker
after shutting it down that was fixed as part of the refactors above.
This change restructures the code to bring all tasks to a halt (and do any
parking needed) before we collapse to …
=> rt: fix deadlock in shutdown

.github/workflows/stress-test.yml, Cargo.toml, stress-test/Cargo.toml, stress-test/examples/simple_echo_tcp.rs
Created a simple echo TCP server that on two different runtimes that is
called from a Github action using Valgrind to ensure that there are
no memory leaks.
=> Add stress test

.github/workflows/stress-test.yml, stress-test/examples/simple_echo_tcp.rs
CI run 1515308234 reported that the command
Run apt install -y valgrind failed due to missing root permissions.
This patch adds sudo before the apt install to overcome this.
=> chore: fix stress test

tokio/src/time/driver/entry.rs, tokio/src/time/driver/wheel/mod.rs, tokio/tests/time_sleep.rs
Dropping a timer on the millisecond that it was scheduled for, when it was on
the pending list, could result in a panic previously, as we did not record the
pending-list state in cached_when.
Hopefully fixes: ZcashFoundation/zebra#1452
=> time: Fix race condition in timer drop

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- sync: fix mpsc bug related to closing the channel (#3215)
=> chore: prepare 0.2.24 release

benches/Cargo.toml, examples/Cargo.toml, stress-test/Cargo.toml, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio-test/Cargo.toml, tokio-test/src/lib.rs, tokio-util/Cargo.toml, tokio-util/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs
Updates the Cargo.toml files to disable publishing and set versions for 1.0.
=> chore: prepare for Tokio 1.0 work

tokio/src/task/blocking.rs, tokio/src/task/task_local.rs
Fixes #3206 on `master` branch.
Additionally added indication that `task::spawn_blocking` requires `rt` feature flag enabled.
=> task: add missing feature flags for docs.rs on master

tokio/src/sync/watch.rs
Closes: #3168
I will push the fix that @tijsvd suggested once I have observed the test failing on CI. It does fix the test locally.
```Rust
loop {
let notified = self.shared.notify_rx.notified();
if let Some(ret) = maybe_changed(&self.shared, &mut self.version) {
return ret;
}
notified.await;
}
```
command to run the test:
```
LOOM_MAX_PREEMPTIONS=1 RUSTFLAGS="--cfg loom" cargo test --lib --release --features full -- --test-threads=1 --nocapture watch_spurious_wakeup
```
=> watch: fix spurious wakeup

tokio/Cargo.toml
this allows using e.g. `tokio::time::pause();`, which is useful for timing-related tests to be shared via the playground
Like PR #1960 (issue #1932), this simply adds metadata to Cargo.toml to tell Playground how to compile tokio.
=> Enable `test-util` feature for the playground

tokio/src/sync/watch.rs
=> backport watch spurious wakeup fix for v0.3.x (#3234)

tokio/src/signal/mod.rs
Hi, I've found there is typo in [tokio::signal](https://docs.rs/tokio/0.3.5/tokio/signal/index.html).
It seems like the sentence `The are some fundamental limitations ...` should be started with `There are ...`.
=> docs: fix typo in signal module documentation

tokio-util/src/udp/frame.rs, tokio/src/net/udp/socket.rs, tokio/tests/udp.rs
=> net: Pass SocketAddr by value

tokio/src/sync/mod.rs
The [`Semaphore::try_acquire`][1] method currently returns a private error type.
[1]: https://docs.rs/tokio/0.3/tokio/sync/struct.Semaphore.html#method.try_acquire
=> Make TryAcquireError public

tokio-util/src/context.rs
This PR changes the following:
1. Change [`TokioContext`][1] to use `Handle` rather than `&'a Runtime`.
2. Add two constructors.
3. Add examples to documentation.
The current design of `TokioContext` uses a `&'a Runtime` field because `Handle` did not exist when `TokioContext` was added to tokio-util, but now that we have a `Handle` type, we can change it to use `Handle` instead. To avoid a breaking change, I have kept the lifetime and defined the struct like this:
```Rust
pub struct TokioContext<'a, F> {
#[pin]
inner: F,
handle: Handle,
runtime_ref: PhantomData<&'a Runtime>,
}
```
The lifetime can still be used to verify at compile time that the `TokioContext` does not outlive its runtime, so it can be useful to keep it. However I have added a `new_static` constructor that opts-out of …
=> util: add constructors to TokioContext

tokio/src/lib.rs
The documentation is not clear about the lifetime of the threads of the blocking threadpool (https://github.com/tokio-rs/tokio/discussions/3251).
I Added link which explains that blocking threads have a timeout which can be configured.
The modification is in the sentence:
```
spawned on demand, can be used to run blocking code that would otherwise
block other tasks from running and are kept alive when not used for a certain
amount of time which can be configured with [`thread_keep_alive`].
```
=> docs: Improve documentation about blocking threads timeout

tokio/src/sync/watch.rs
The `watch::Receiver` type has the borrow method, to borrow the value last sent.
The `watch::Sender` also has access to this, but it isn't exposed. It would be nice to have this when passing around a `Sender` since it enables someone to check what has last been sent.
I've added an identical `borrow` method to `sync::watch::Sender`, along with some tests for the borrow method in general.
=> Add `sync::watch::Sender::borrow` method

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/error.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/tests/sync_mpsc.rs
The mpsc `try_recv()` functions have an issue where a sent message
happens-before a call to `try_recv()` but `try_recv()` returns `None`.
Fixing this is non-trivial, so the function is removed for 1.0. When the
bug is fixed, the function can be added back.
Closes #2020
=> sync: remove `try_recv()` from mpsc types

tokio-util/Cargo.toml
`SinkExt` and other futures traits are extremely hard to find if you don't already know they exist. They do not appear in docs generated by Rustdoc because tokio-utils doesn't depend on futures-util itself, you have to do that in your downstream crate.
Add an optional dependency enabled only on docs.rs, so that it shows up with `cargo doc --all-features`.
Before (https://docs.rs/tokio-util/0.5.1/tokio_util/codec/struct.Framed.html): ![image](https://user-images.githubusercontent.com/23638587/102089829-bbf57780-3dea-11eb-9d4e-541bcc875974.png)
After:
=> Document `SinkExt` and other futures traits on docs.rs

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- rt: fix deadlock in shutdown (#3228)
- rt: fix panic in task abort when off rt (#3159)
- sync: make `add_permits` panic with usize::MAX >> 3 permits (#3188)
- time: Fix race condition in timer drop (#3229)
- watch: fix spurious wakeup (#3244)
- example: add back udp-codec example (#3205)
- net: add `TcpStream::into_std` (#3189)
=> chore: prepare v0.3.6 release

tokio/Cargo.toml, tokio/README.md, tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/runtime/handle.rs
Enabling `tracing` integration now requires compiling with `--cfg
tokio_unstable`. Once `tracing-core` guarantees the same level of
stability as Tokio 1.0, unstable can be removed.
Closes #3258
=> tracing: switch to unstable for 1.0.

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mod.rs, tokio/src/sync/semaphore.rs
The need to expose `Semaphore::close` as explained in #3061. 
Expose `Semaphore::close`
=> Expose `Semaphore::close`

tokio-stream/src/lib.rs
Follow up fixes from https://github.com/tokio-rs/tokio/pull/3277
Closes: #3284
=> stream: Fix a few doc issues

tokio/src/runtime/builder.rs, tokio/src/runtime/driver.rs, tokio/src/time/clock.rs, tokio/src/time/driver/tests/mod.rs, tokio/tests/time_pause.rs
Pausing time is a capability added to assist with testing Tokio code
dependent on time. Currently, the capability implicitly requires the
current_thread runtime.
This change enforces the requirement by panicking if called from a
multi-threaded runtime.
=> time: enforce `current_thread` rt for time::pause

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs
- fix outdated macro documentation (#3180)
- add portability note to `tokio::main` (#3199)
Closes: #3290
=> chore: prepare tokio-macros v0.3.2

tokio/src/runtime/builder.rs, tokio/tests/rt_threaded.rs
Closes https://github.com/tokio-rs/tokio/issues/2802
=> rt: Change `max_threads` to `max_blocking_threads`

tokio-macros/src/lib.rs, tokio/src/lib.rs
=> docs: `tokio::main` macro also supported on `rt`

tokio/src/net/tcp/split.rs, tokio/src/net/tcp/split_owned.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/unix/split.rs, tokio/src/net/unix/split_owned.rs, tokio/src/net/unix/stream.rs
#3294 describes that the shutdown method should be removed from the {Tcp,Unix}Stream types in favour of the one on AsyncWriteExt. However, plain removing it lead to some compilation failures that were difficult to resolve, so @Darksonn suggested we instead rename the method (to shutdown_std) and make it private. Closes #3294.
Rename {Tcp,Unix}Stream::shutdown to shutdown_std and make it private.
=> Rename shutdown method on {Tcp,Unix}Stream to shutdown_std and make it private, to avoid clash with AsyncWriteExt::shutdown

tokio-test/Cargo.toml, tokio-util/Cargo.toml, tokio/Cargo.toml
Removes the `stream` feature flag from `Cargo.toml` and removes the
`futures-core` dependency. Once `Stream` lands in `std`, a feature flag
is most likely not needed.
=> chore: remove some left over `stream` feature code

examples/Cargo.toml, tokio-test/Cargo.toml, tokio-util/Cargo.toml, tokio-util/src/io/stream_reader.rs, tokio-util/src/lib.rs, tokio-util/src/udp/frame.rs, tokio/Cargo.toml, tokio/src/io/util/read_buf.rs, tokio/src/io/util/read_to_end.rs, tokio/src/io/util/write_buf.rs
Updates the codebase to track the `bytes` git branch. This is in
preparation for the 1.0 release.
Closes #3058
=> chore: update to `bytes` 1.0 git branch

tokio/src/io/async_fd.rs, tokio/src/io/mod.rs, tokio/tests/io_async_fd.rs
* https://github.com/rust-lang/rfcs/pull/3014 
* Update `AsyncFdReadGuard::with_poll` to pass a reference to the underlying
object to the clousure.
* Create a new `AsyncFdReadMutGuard` to provide mutable APIs on the underlying
object.
=> Add _mut variants of methods on AsyncFd

tokio/src/io/async_fd.rs, tokio/src/io/mod.rs, tokio/tests/io_async_fd.rs
=> Rename with_io to try_io and drop with_poll

tokio/src/fs/read_dir.rs, tokio/src/io/util/lines.rs, tokio/src/io/util/split.rs, tokio/src/lib.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/unix/listener.rs, tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/tests/support/mpsc_stream.rs
This PR exposes a `poll_next` equivalent on some of the types whose `Stream` impl were removed in #3277. It also tweaks the documentation on `poll_accept`.
The methods are moved around in their impl blocks so they appear at the bottom of the generated documentation.
=> Expose poll_next replacement on Split, Lines, DirEntry, Receiver and UnboundedReceiver

tokio/src/fs/copy.rs, tokio/src/fs/dir_builder.rs, tokio/src/fs/file.rs, tokio/src/fs/write.rs
I did a scan of `fs` and found a few minor things to change.
=> fs: misc small API tweaks

tokio/src/time/interval.rs
This was missed when pulling out all the `Stream` stuff.
=> time: make Interval::poll_tick() public

examples/tinyhttp.rs, tokio-stream/src/timeout.rs, tokio-util/src/codec/bytes_codec.rs, tokio-util/src/codec/framed.rs, tokio-util/src/codec/length_delimited.rs, tokio/src/io/async_fd.rs, tokio/src/io/util/empty.rs, tokio/src/io/util/sink.rs, tokio/src/runtime/handle.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mpsc/error.rs, tokio/src/sync/mutex.rs, tokio/src/task/task_local.rs, tokio/src/time/error.rs, tokio/src/time/timeout.rs
#[non_exhaustive] is the official feature for this pattern and was stable at Rust 1.40.
=> chore: use #[non_exhaustive] instead of private unit field

examples/tinyhttp.rs, tokio-stream/src/timeout.rs, tokio-util/src/codec/bytes_codec.rs, tokio-util/src/codec/framed.rs, tokio-util/src/codec/length_delimited.rs, tokio/src/io/async_fd.rs, tokio/src/io/util/empty.rs, tokio/src/io/util/sink.rs, tokio/src/runtime/handle.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mpsc/error.rs, tokio/src/sync/mutex.rs, tokio/src/task/task_local.rs, tokio/src/time/error.rs, tokio/src/time/timeout.rs
This reverts commit 575938d4579e6fe6a89b700aadb0ae2bbab5483b. (#3320)
For context, see discussion in discord.
=> Revert "chore: use #[non_exhaustive] instead of private unit field (#3320)"

tokio-util/src/compat.rs
They hadn't been updated yet.
Rename them, as discussed on Discord.
=> compat: update traits naming to match tokio 1.0

tokio/src/lib.rs
The streams haven't been stabilized yet, but the crate docs still mention their feature.
Remove the feature for now.
Fixes #3333
=> Remove stream feature from docs

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/lib.rs
This release fixes a soundness hole caused by the combination of `RwLockWriteGuard::map` and `RwLockWriteGuard::downgrade` by removing the `map` function. This is a breaking change, but breaking changes are allowed under our semver policy when they are required to fix a soundness hole. (See [this RFC][semver] for more.)
Note that we have chosen not to do a deprecation cycle or similar because Tokio 1.0.0 was released two days ago, and therefore the impact should be minimal.
Due to the soundness hole, we have also yanked Tokio version 1.0.0.
- sync: remove `RwLockWriteGuard::map` and `RwLockWriteGuard::try_map` (#3345)
- docs: remove stream feature from docs (#3335)
[semver]: https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md#soundness-changes
=> chore: prepare tokio 1.0.1 release

examples/connect.rs, examples/echo.rs, examples/proxy.rs, examples/udp-codec.rs
#2444 identified an example (`echo.rs`) which uses a stack-based buffer and suggests it would be improved by using a heap-based buffer instead.
`echo.rs` is a straightforward switch from array to `Vec`. `BytesMut` was also suggested in discussion on #2444, but I chose `Vec` because it matches the approach in [the website tutorial](https://tokio.rs/tokio/tutorial/io).
=> Adjust buffering in examples

tokio/src/macros/select.rs
As https://github.com/tokio-rs/tokio/issues/2740, while no branch is avaiblable in `select!`, the `internal error: entered unreachable code` error message would be confusing.
Improve the error message.
=> Improve select! error message

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/io/stream_reader.rs
Many wrapper types under `tokio::io` like `BufReader` have `get_ref`, `get_mut` and `get_pin_mut` methods and they seem to be good to have for `tokio-util` types as well.
This commit adds:
- `Framed::get_pin_mut`
- `FramedRead::get_pin_mut`
- `FramedWrite::get_pin_mut`
- `StreamReader::get_ref`
- `StreamReader::get_mut`
- `StreamReader::get_pin_mut`
- `StreamReader::into_inner`
=> util: add more `get_{ref,mut,pin_mut}` methods

tokio-stream/Cargo.toml
`syn`-less usage of tokio-util.
Move async-stream to dev-deps.
=> stream: move async-stream to dev-deps

tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/stream.rs, tokio/tests/tcp_stream.rs, tokio/tests/udp.rs, tokio/tests/uds_datagram.rs, tokio/tests/uds_stream.rs
Refs: https://github.com/tokio-rs/tokio/issues/3313
two questions:
- what i have done was in the right direction? 
- what a `vectored read` function should look like?
function signature like below?
```rust
pub fn try_read_vectored<B: BufMut>(&self, buf: &mut [B]) -> io::Result<usize>;
```
=> net: Add try_read_buf and try_recv_buf

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml, tokio-stream/src/lib.rs
Added
- add `Stream` wrappers (#3343)
Fixed
- move `async-stream` to `dev-dependencies` (#3366)
=> chore: prepare tokio-stream 0.1.1

tokio-stream/Cargo.toml
Follow-up to: #3374
I forgot to remove path deps :sweat_smile:
=> stream: remove path deps

tokio-stream/Cargo.toml
Actually enable all features on docs.rs
=> docs: fix tokio-stream features not being displayed

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_write.rs
I have a scenario where given a specific event trigger, I need to consider all data in my Framed object is invalid, and I need to clear all of it. The framed object already exposes the [read_buffer](https://docs.rs/tokio-util/0.6.0/tokio_util/codec/struct.Framed.html#method.read_buffer), I am just exposing the corresponding write buffer, so that I can clear that data as well.
Copying the API used for read_buffer in the FramedWrite/Framed files as well.
=> Exposing write_buffer on FramedWrite/Framed for consistency with FramedRead

tokio/src/task/local.rs, tokio/tests/task_local_set.rs
Wake the `tokio::task::LocalSet` after
`tokio::task::LocalSet::spawn_local` is called.
Note this side effect in the `tokio::task::LocalSet::spawn_local` docs.
Add test for spawn_local being woke in `task_local_set.rs`
Fixes: #3117
Fixes #3117 
Add call to shared waker in localset after adding future to localset task queue.
=> tokio: wake localset on spawn_local

tokio/src/io/blocking.rs, tokio/src/runtime/mod.rs
Fixing a few typos while reading
=> io/runtime: typo fixes

CONTRIBUTING.md
The 1.0 roadmap of #2718 and the [Announcing Tokio 1.0 blog post](https://tokio.rs/blog/2020-12-tokio-1-0) both contain details of release and versioning policy moving forward. As discussed on discord, its helpful to contributors to have all the policies in one place. 
I've tried to consolidate these appropriately in the CONTRIBUTING.md guide, and I also have made few general cosmetic changes.
=> Add tokio 1.0 policies to contributing guide

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml, tokio-stream/src/lib.rs
This just fixes the documentation. We should have done this a week ago honestly.
=> chore: prepare tokio-stream 0.1.2

tokio/src/sync/mpsc/bounded.rs, tokio/tests/sync_mpsc.rs
Add a `try_reserve` function to the mpsc `Sender`. This allows to attempt to query the `Sender` for available send slots without having to materialize the `T` value.
=> mpsc: Add `Sender::try_reserve` function

tests-integration/tests/process_stdio.rs
Cargo has added the environment variable `CARGO_BIN_EXE_<name>` in Rust 1.43 to make it easier to run such tests.
Refs: https://github.com/rust-lang/cargo/pull/7697
=> chore: use CARGO_BIN_EXE instead of inspecting env::current_exe()

tokio/src/runtime/task/core.rs, tokio/src/runtime/task/harness.rs
Task spawning is a common operation which results in a lot of instantiations of the task code. Reducing the amount of generated code should lead to faster compile times overall.
This extracts code that does not depend on a type parameter into functions with less or no type parameters at all. Reducing the amount of duplicated code.
=> Minimize the amount of duplicated code in the task harness

tokio/src/sync/mod.rs, tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs, tokio/tests/sync_rwlock.rs
=> sync: RwLock add try_read and try_write methods

.github/workflows/ci.yml, tokio/src/io/util/read_to_end.rs
This is a companion of #3426 that contains just the unsoundness fix so we can release it in a patch release.
=> Fix unsoundness in read_to_end

.github/workflows/ci.yml, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/io/util/read_to_end.rs, tokio/src/lib.rs
Merges `tokio-1.0.x` changes into master.
This PR should be merged w/ the git CLI tool and not the Github UI.
=> chore: merge 1.0.x changes

tokio/src/process/mod.rs
I was using `tokio::process::Child` without much experience of `std::process::Child` and was reading the tokio docs. I worked out that I needed to use the `child.stdin.take().unwrap()` pattern but it would have saved me some time if it was in the docs. I later discovered that this was added to the rust std lib documentation by https://github.com/rust-lang/rust/pull/74192.
Updated the doc comments on the public fields of `Child` to match the changes made by https://github.com/rust-lang/rust/pull/74192.
=> Add documentation to process::Child fields

tokio/src/io/util/mod.rs, tokio/src/io/util/read_to_end.rs, tokio/src/io/util/read_to_string.rs, tokio/src/io/util/vec_with_initialized.rs, tokio/tests/io_read_to_end.rs
This keeps track of the number of initialized bytes inside `read_to_end`.
Note that old implementation is actually unsound as replacing the buffer inside `ReadBuf` does not require unsafe, and it does not check whether the pointer has been changed.
```Rust
// This should no longer even be possible in safe Rust. An implementor
// would need to have unsafely *replaced* the buffer inside `ReadBuf`,
// which... yolo?
assert!(new_len <= buf.capacity());
```
=> Keep track of initialized bytes in read_to_end

tokio-util/Cargo.toml, tokio-util/src/sync/mod.rs, tokio-util/src/sync/poll_semaphore.rs
The [`Semaphore`][1] type has no `poll_acquire` method as it uses an intrusive linked list, but the recommendation I want to make when people ask for a `poll_send` on `mpsc` is to combine the unbounded channel with a semaphore. However this requires a pollable semaphore.
[1]: https://docs.rs/tokio/1/tokio/sync/struct.Semaphore.html#method.close
=> util: add pollable Semaphore

tokio/src/io/read_buf.rs
This returns the entire buffer as a `&mut [MaybeUninit<u8>]`, which may
be useful for building abstractions on top.
It looks like `ReadBuf` doesn't have a way to get the entire buffer, only various sections of it. Being able to work with the entire buffer is useful in some situations, such as while building testing tools that limit the size of the buffer (similar to `BufMut::limit` in tokio 0.2).
Add `ReadBuf::inner_mut` which returns the entire inner buffer.
This is unsafe for the same reason that `unfilled_mut` is: the caller must not deinitialize portions of the buffer that have already been initialized.
I've used this method in `partial-io`: https://github.com/facebookincubator/rust-partial-io/pull/33#discussion_r559884801 and it looks like it does the job.
I'm not sure if any tests …
=> io: add ReadBuf::inner_mut

tokio/src/sync/mutex.rs
Trivial typo fix to the documentation.
=> docs: trivial typo fix

tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs
This change makes ctrl+f for `split` turn up an explanation of how to split it.
=> Update datagram docs on splitting

tokio/src/sync/broadcast.rs, tokio/src/sync/tests/loom_broadcast.rs
Fixes: #2533
I came across this problem in my program with multiple worker threads and an insufficient channel capacity. With a debugger, I noticed that `self.next` can be set a greater value than `until` by `self.recv_ref()` when it's called multiple times in the loop in drop.
Here is another program that reproduces the panic: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d09c0b70aeb7187b87a01db544c6b821
* Only call `self.recv_ref` when `self.next` is smaller than `until`. 
*  Added a loom test that fails without this change.
=> sync: fix panic in broadcast::Receiver drop 

tokio-util/src/time/delay_queue.rs, tokio-util/src/time/wheel/level.rs, tokio-util/src/time/wheel/mod.rs, tokio-util/tests/time_delay_queue.rs, tokio/src/time/driver/wheel/level.rs, tokio/src/time/driver/wheel/mod.rs
This PR addresses two related bugs related to edge cases in `tokio_util::time::DelayQueue`.
1. When an entry is inserted into the queue with a deadline that has already elapsed it is flagged and put on a special-cased subqueue. If the entry's key is subsequently reset with a deadline in the future, the expired flag is not cleared. Trying to use `DelayQueue::{reset, reset_at, remove}` with the same key a second time will either cause a debug assert or trigger various kinds of breakage in builds without debug assertions—the key may be left in the timer wheel after a `remove` call and then reused for a separate storage entry, etc.
2. Under specific circumstances, calling `DelayQueue::{reset, reset_at, remove}` with an entry which has expired but has not yet been retrieved with …
=> Fix panics on updating DelayQueue entries

tokio/tests/rt_common.rs
Signal the tasks driving the ping pong to stop running after spawning
a few others. After that, awaits for each of them to ensure that all ran properly.
Fixes #3305
=> tests: fix ping pong saturation

tokio/src/io/util/read_to_end.rs, tokio/src/io/util/read_to_string.rs, tokio/src/io/util/vec_with_initialized.rs
Use a sealed trait to constrain `VecWithInitialized`'s generic type parameter.  The safety of that struct relies on invariants upheld by `Vec<u8>`.  The struct currently has an `unsafe new` associated fn where `V: AsMut<Vec<u8>>`.
Avoids a bit of `unsafe`.
This PR defines a crate private `VecU8` trait and implements it for `Vec<u8>` and `&mut Vec<u8>`.
cc @Darksonn as we discussed this a bit in https://github.com/tokio-rs/tokio/pull/3426
=> Use a sealed trait to constrain VecWithInitialized

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml, tokio-util/src/lib.rs
- sync: add pollable `Semaphore` (#3444)
- time: fix panics on updating `DelayQueue` entries (#3270)
=> Prepare tokio-util 0.6.2

tokio/src/sync/semaphore.rs
This links to [`PollSemaphore`][1] from [`Semaphore`][2].
[1]: https://docs.rs/tokio-util/0.6/tokio_util/sync/struct.PollSemaphore.html
[2]: https://docs.rs/tokio/1/tokio/sync/struct.Semaphore.html
=> Add link to PollSemaphore

tokio/src/task/local.rs
People are often confused about how to spawn `!Send` futures. This example should hopefully point them in the right direction.
=> Add LocalSet example

tokio/Cargo.toml
Follow up to https://github.com/tokio-rs/mio/pull/1405. Would probably help greatly with the adoption rate of the fixed versions of `net2` and `miow`. Helps unblock https://github.com/rust-lang/rust/pull/78802. See that PR for more details.
=> Upgrade mio dependency

tokio/src/sync/mpsc/bounded.rs
This clarifies various things in the documentation for bounded mpsc channels.
=> Improve bounded mpsc documentation

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- net: add `try_read_buf` and `try_recv_buf` (#3351)
- mpsc: Add `Sender::try_reserve` function (#3418)
- sync: add `RwLock` `try_read` and `try_write` methods (#3400)
- io: add `ReadBuf::inner_mut` (#3443)
- macros: improve `select!` error message (#3352)
- io: keep track of initialized bytes in `read_to_end` (#3426)
- runtime: consolidate errors for context missing (#3441)
- task: wake `LocalSet` on `spawn_local` (#3369)
- sync: fix panic in broadcast::Receiver drop (#3434)
- stream: link to new `Stream` wrappers in `tokio-stream` (#3343)
- docs: mention that `test-util` feature is not enabled with full (#3397)
- process: add documentation to process::Child fields (#3437)
- io: clarify `AsyncFd` docs about changes of the inner fd (#3430)
- net: update datagram docs on splitting (#3448) …
=> Prepare Tokio 1.1.0

tokio/CHANGELOG.md
Fixed the dates in CHANGELOG.md
The dates listed for versions 1.0.2 and 1.1.0 were in 2020 when they should have been in 2021.
Changed to 2021.
=> Fix the dates in CHANGELOG.md

tokio/src/sync/mpsc/bounded.rs
#3418 added a new `Sender::try_reserve` method.  Update `Permit`'s rustdoc to account for it.
Also fix a typo in `try_reserve`'s rustdoc.
=> Update `Permit` rustdoc to account for `Sender::try_reserve`

tokio/src/net/addr.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs
This PR improves the discoverability of `TcpSocket`. It also removes some comments about strings implementing `ToSocketAddrs`, which were made redundant by #2951.
=> Improve discoverability of TcpSocket

tokio/src/io/driver/mod.rs, tokio/src/runtime/handle.rs, tokio/src/sync/broadcast.rs, tokio/src/task/spawn.rs, tokio/src/time/driver/handle.rs
=> Tokio 0.2.x: Update panic messages to include version

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- chore: upgrade mio dependency (#3207)
- runtime: update panic messages to include version (#3460)
- task: add missing feature flags for `task_local` (#3236)
=> chore: prepare Tokio 0.2.25

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- runtime: update panic messages to include version (#3461)
=> chore: prepare Tokio 0.3.7

tokio-util/src/time/wheel/level.rs, tokio/src/sync/rwlock.rs
Add detail about why deadlocks might be encountered when a read lock attempt is made following a successful read lock followed by a write lock attempt by the same task.
Update documentation in #2849
=> Update documentation to mention possibility of deadlock

tokio/src/process/mod.rs
* Previously this was only done in methods like `Command::status` or `Child::wait_with_output`, but this change corrects the `Child::wait` method to also ensure that the child stdin handle is consistently closed (as documented)
Refs #3420
=> process: drop child stdin in `wait()`

.github/workflows/ci.yml, tests-integration/Cargo.toml, tests-integration/src/bin/test-mem.rs, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/io/driver/registration.rs, tokio/src/io/driver/scheduled_io.rs, tokio/src/lib.rs
Due to an earlier deadlock fix (#3228), it is possible for a cycle to exist in the I/O driver during shutdown. In some cases, if a waker is held by the I/O driver slab, and the weaker holds an Arc to the struct that holds the slab, then there is a cycle preventing memory from being freed. The easiest fix is to break the cycle when the I/O resource is dropped by clearing any wakers.
This is targeting the 1.0.x branch. I am including the crate version bump.
Fixes #3473
=> io: fix memory leak during shutdown

tokio-util/src/sync/mod.rs, tokio-util/src/sync/reusable_box.rs, tokio-util/tests/reusable_box.rs
I have found myself wanting a utility like this a few times, and inspired by #3463, I have now written it.
One question is which module it should go in. I put it in `tokio_util::sync`, but I'm not sure this is the best place.
Discussed [here](https://users.rust-lang.org/t/is-this-reusable-box-sound/54554).
=> util: add ReusableBoxFuture utility

tokio-util/Cargo.toml, tokio-util/src/sync/poll_semaphore.rs
I removed async-stream from the default dep graph in #3366 but it was re-added due to the new PollSemaphore feature. See that PR for rationale.
Utilising the new ReusableBoxFuture from #3464.
=> util: use ReusableBoxFuture for PollSemaphore

tokio-util/Cargo.toml, tokio-util/src/codec/decoder.rs, tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_impl.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/codec/mod.rs, tokio-util/src/io/reader_stream.rs, tokio-util/src/io/stream_reader.rs, tokio-util/src/udp/frame.rs
Without this change, it would not be possible to use the [`ReusableBoxFuture`][1] in the tokio-stream crate, which I want to use for various wrappers such as the broadcast receiver.
[1]: https://github.com/tokio-rs/tokio/pull/3464
=> Remove tokio-stream dependency from tokio-util

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml, tokio-util/src/lib.rs
- sync: add `ReusableBoxFuture` utility (#3464)
- sync: use `ReusableBoxFuture` for `PollSemaphore` (#3463)
- deps: remove `async-stream` dependency (#3463)
- deps: remove `tokio-stream` dependency (#3487)
=> Prepare tokio-util v0.6.3

tokio/src/loom/std/mod.rs, tokio/src/sync/task/atomic_waker.rs
Replaces #3496 as that's ahead of its time due to MSRV policy.
=> Suppress deprecated warnings for spin_loop_hint

tokio/src/signal/unix.rs
Signed-off-by: Fuyang Liu <liufuyang@users.noreply.github.com>
make the `poll_recv` method public,  So we can add a wrapper to `tokio_stream::wrappers` for them.
=> signal: make Signal::poll_recv method public

examples/Cargo.toml, tokio-stream/Cargo.toml, tokio-stream/src/wrappers.rs, tokio-stream/src/wrappers/broadcast.rs, tokio-stream/src/wrappers/watch.rs
Signed-off-by: Fuyang Liu <liufuyang@users.noreply.github.com>
Closes #3382 
The basic sketch is going to be:
* Make the constructor takes a broadcast receiver
* Then it uses async-stream to turn that into an `impl Stream`
* Still inside the constructor, call `Box::pin` on that stream, the put the pinned box into the struct
* Then your `impl Stream on Wrapper` just forwards calls to `poll_next` to the pinned box
=> tokio-stream: add wrapper for broadcast and watch

tests-build/tests/fail/macros_invalid_input.stderr, tokio-macros/src/entry.rs, tokio-macros/src/lib.rs, tokio/Cargo.toml, tokio/src/runtime/builder.rs, tokio/src/runtime/driver.rs, tokio/src/time/clock.rs, tokio/src/time/driver/mod.rs, tokio/src/time/driver/tests/mod.rs, tokio/src/util/mod.rs, tokio/tests/time_pause.rs
The time driver stores an Instant internally used as a "base" for future
time calculations. Since this is generated as the Runtime is being
constructed, it previously always happened before the user had a chance
to pause time. The fractional-millisecond variations in the timing
around the runtime construction and time pause cause tests running
entirely in paused time to be very slightly deterministic, with the time
driver advancing time by 1 millisecond more or less depending on how the
sub-millisecond components of the `Instant`s involved compared.
To avoid this, there is now a new option on `runtime::Builder` which
will create a `Runtime` with time "instantly" paused. This, along with a
small change to have the time driver use the provided clock as the
source for its start time allow …
=> Make test-util paused time fully deterministic

tokio-stream/Cargo.toml, tokio-stream/src/macros.rs, tokio-stream/src/wrappers.rs, tokio-stream/src/wrappers/broadcast.rs, tokio-stream/src/wrappers/watch.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/watch.rs
This PR adds a `sync` feature to `tokio-stream` to guard the `tokio-util` dependency, and does some doc stuff for the broadcast and stream wrappers.
=> Update features and doc for broadcast/watch stream

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml, tokio-stream/src/lib.rs
Added
- sync: add wrapper for broadcast and watch (#3384, #3504)
=> chore: prepare tokio-stream 0.1.3

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs
- add `start_paused` option to macros (#3492)
This PR is blocked on making a Tokio release. I will rerun CI once that has happened.
=> chore: prepare tokio-macros 1.1.0

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs
- signal: make `Signal::poll_recv` method public (#3383)
- time: make `test-util` paused time fully deterministic (#3492)
- sync: link to new broadcast and watch wrappers (#3504)
=> chore: prepare tokio v1.2.0

tokio/src/runtime/builder.rs
This makes `LocalSet` more easily discoverable.
=> Add link to LocalSet on new_current_thread

tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs
Several `tokio::net` types are missing the `into_std` method. This PR adds it.
=> net: add into_std for net types without it

tokio/src/sync/barrier.rs
We should not recommend `join_all` because of #2401.
=> Do not recommend join_all for Barrier

tokio/src/net/udp.rs
Improve this snippet a bit to avoid one way to misunderstand it.
=> net: update UdpSocket splitting doc

tokio/src/sync/notify.rs
there is no more method `notify`, it has been renamed to `notify_one`
=> doc: rename notify to notify_one

tokio/src/io/async_fd.rs, tokio/src/runtime/builder.rs, tokio/src/sync/notify.rs, tokio/src/time/driver/sleep.rs
=> Doc aliases for pre-1.0 function names

CONTRIBUTING.md, tokio-macros/Cargo.toml, tokio-macros/src/lib.rs, tokio-stream/Cargo.toml, tokio-stream/src/lib.rs, tokio-test/Cargo.toml, tokio-test/src/lib.rs, tokio-util/Cargo.toml, tokio-util/src/lib.rs, tokio/Cargo.toml, tokio/src/lib.rs
AFAIK, `html_root_url` is not needed in most cases. And api-guidelines no longer recommends this. See https://github.com/rust-lang/api-guidelines/issues/229 for more.
This allows us to remove one of the easy-to-forget release steps.
=> Remove html_root_url

tokio/src/io/util/async_buf_read_ext.rs
This is completely stolen from the `read_line` documentation.
My motivation here is that this tripped me up after a quick skim of the documentation: it's obvious in retrospect that `read_until` would have the same behaviour as `read_line`, but I ended up with a loop taking 100% CPU as a result of not handling the `Ok(0)` case correctly!
=> doc: note the EOF behaviour of `read_until`

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs
Found typos "extention trait"
Change found occurences of "extention trait" to "extension trait".
=> doc: fix typos

tokio/src/time/mod.rs
It's confusing to see two slightly different documentations for the same function.
I copied the text from interval.rs into the module documentation.
=> doc: Sync interval.rs and time/mod.rs docs

tokio/src/runtime/builder.rs
Since ed5a94eb2db95b7cc142045fbbd5d68c6276e04e, there is no longer a limit of 32,768 threads on the worker threads and blocking thread pool, but the documentation has not been updated.
Update the documentation.
=> Update documentation of thread limits

tokio-util/src/codec/any_delimiter_codec.rs, tokio-util/src/codec/mod.rs, tokio-util/tests/codecs.rs
To provide codecs that can be used with custom delimiters and encoder characters. The codex will decide based on any character found in the given delimiter characters.
This will work similarly to LinesCodec by trying to find any of the characters while decoding , and appending all of the given characters while encoding.
=> Any delimiter codec

tokio/src/sync/oneshot.rs, tokio/tests/sync_oneshot.rs
Before this commit `close` after successful `try_recv` panics.
My use case is this: on drop, I call `close` to prevent pushing a
message to the queue, and then fetch the message if any and process
it.
But if message is already processed, `close` panics.  And there is
no API to know if message was already fetched or not (except for
writing a wrapped which would track that info, which would be an
overkill).
But generally `close` operation should be safe to be called any
time.
=> Allow oneshot::Receiver::close after successful try_recv

tokio/src/io/async_read.rs
The trait-level documentation accurately describes this method, but the
function-level documentation imples that an implementer should overwrite
the entire buf, rather than just the unfilled portion.
=> doc: Update AsyncRead::poll_read

tokio-util/src/codec/lines_codec.rs, tokio-util/tests/codecs.rs
Fix bug on LinesCodec as described [here](https://github.com/tokio-rs/tokio/issues/3555)
return Ok(None) instead of Err(LinesCodecError::MaxLineLengthExceeded)
=> Bug fix subsequent calls to lines codec decode does not return the desired results

tokio/src/time/driver/sleep.rs, tokio/src/time/instant.rs, tokio/src/time/timeout.rs, tokio/tests/time_timeout.rs
It is tempting to use very large `Duration` value to get a practically
infinite timeout.
Before this commit tokio panics on checked Instant + Duration
overflow.
This commit implements very simple fix: if Instant + Duration
overflows, we use duration = 30 years. Better fix should avoid
firing a timer on duration overflow. It requires deeper understanding
how timers work, but also it is not clear, for example, what
`Sleep::deadline` function should return.
Similar fix is done for `sleep`.
=> Do not panic on timeout(Duration::MAX)

tokio-stream/src/lib.rs
For crates which set `rustc-args = ["--cfg", "docsrs"] ` in `[package.metadata.docs.rs]`, tokio-stream fails to build on docs.rs with
```
[INFO] [stderr]    Compiling tokio-stream v0.1.3
[INFO] [stderr] error[E0636]: the feature `doc_cfg` has already been declared
[INFO] [stderr]   --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.3/src/lib.rs:24:29
[INFO] [stderr]    |
[INFO] [stderr] 24 | #![cfg_attr(docsrs, feature(doc_cfg))]
[INFO] [stderr]    |                             ^^^^^^^
```
Remove duplicate `cfg_attr` line 
The first occurence is on https://github.com/tokio-rs/tokio/blob/master/tokio-stream/src/lib.rs#L17
=> Fix docs.rs build with cfg(docsrs)

tokio/src/sync/semaphore.rs, tokio/tests/sync_semaphore_owned.rs
There are `owned` methods for acquiring single permits, but for multiple ones they are missing.
Therefore I added them :slightly_smiling_face: 
~~I didn't add tests because I couldn't find any for `acquire_many` and `try_acquire_many` in the first place, and because I couldn't successfully compile the tests locally at all.~~
Tests are now added.
=> Add acquire_many_owned and try_acquire_many_owned to tokio::sync::Semaphore

tokio/src/io/util/mod.rs
The big move or 'src' in rust-lang caused this link to be broken
=> Fix link to std src in util

tokio-util/src/sync/mod.rs, tokio-util/src/sync/mpsc.rs, tokio-util/tests/mpsc.rs
This PR replaces #3105, vastly reducing the required amount of unsafe by using the new `ReusableBoxFuture` utility.
=> Add pollable mpsc::Sender

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs
Sometimes we need to check if two senders belongs to the same channel.
Just use Arc::ptr_eq to impl PartialEq and Eq.
=> sync: add same_channel method to mpsc Senders

tokio-stream/src/wrappers/watch.rs
This updates WatchStream to always yield the current value before waiting
for updates. This makes it possible to use it as a drop-in replacement
for watch::Receiver when updating a Tokio 0.2 application.
There is one caveat here, which is that we can't tell if the sender was
used before. This means we might yield the current value twice if it was
(because reading what we think is the initial value doesn't increment
the watcher).
I don't think there really is a way to fix this without changing the API
of Receiver, so for now I went with documenting it. Let me know what you
think.
More context: https://github.com/tokio-rs/tokio/discussions/3575
=> tokio-stream: WatchStream: yield the current value

tokio-stream/src/lib.rs
I noticed more duplicate declarations
=> stream: remove duplicate `doc(test(..))` & `cfg_attr` declarations

tokio/src/sync/oneshot.rs
Added additional documentation on the oneshot, both to the module and the receiver, including the receiver fail on sender drop.
The oneshot docs lacked information at the module level and on `Receiver`. Also, there was no specific information about dropping the `Sender` and the result of that.
=> docs - added additional documenation on the oneshot channel

tokio/src/coop.rs, tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/task/mod.rs, tokio/src/task/unconstrained.rs, tokio/tests/rt_common.rs
Some code doesn't work too well with Tokio coop.
For more context, see the discussion in:
https://github.com/tokio-rs/tokio/pull/3516
This adds an opt-out for code that might not be compatible with Tokio
coop (e.g. heavily nested `FuturesUnordered`).
Notes to reviewer:
- I made the coop module public for this.
- I removed a few docs in said coop module that reference methods that
don't exist yet.
=> coop: expose an unconstrained() opt-out

tokio-util/src/sync/poll_semaphore.rs, tokio-util/tests/poll_semaphore.rs
This makes `PollSemaphore` fused to match the behavior in its description.
=> util: fuse PollSemaphore

examples/Cargo.toml, examples/chat.rs
This change simplifies [examples/chat.rs](https://github.com/tokio-rs/tokio/blob/master/examples/chat.rs) by replacing the `Stream` impl with `tokio::select!`, removing the need for the `async-stream` dependency. It also lets us get rid of the `Message` enum since we have enough context in the `select!` block to handle everything.
Closes: #3586
=> Update chat example to use `tokio::select!`

tokio/CHANGELOG.md, tokio/Cargo.toml
- coop: expose an `unconstrained()` opt-out (#3547)
- net: add `into_std` for net types without it (#3509)
- sync: add `same_channel` method to `mpsc::Sender` (#3532)
- sync: add `{try_,}acquire_many_owned` to `Semaphore` (#3535)
- sync: add back `RwLockWriteGuard::map` and `RwLockWriteGuard::try_map` (#3348)
- sync: allow `oneshot::Receiver::close` after successful `try_recv` (#3552)
- time: do not panic on `timeout(Duration::MAX)` (#3551)
- doc: doc aliases for pre-1.0 function names (#3523)
- io: fix typos (#3541)
- io: note the EOF behaviour of `read_until` (#3536)
- io: update `AsyncRead::poll_read` doc (#3557)
- net: update `UdpSocket` splitting doc (#3517)
- runtime: add link to `LocalSet` on `new_current_thread` (#3508)
- runtime: update documentation of thread limits (#3527)
- …
=> Prepare Tokio v1.3.0

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- codec: `AnyDelimiter` codec (#3406)
- sync: add pollable `mpsc::Sender` (#3490)
- codec: `LinesCodec` should only return `MaxLineLengthExceeded` once per line (#3556)
- sync: fuse PollSemaphore (#3578)
=> Prepare tokio-util v0.6.4

tokio-stream/src/stream_ext/throttle.rs
Add a note in the documentation for Throttle that it can be made to
implement Unpin by pinning it.
I had trouble updating to tokio v1 because the `Throttle` struct is `!Unpin` and my code required it to be `Unpin`.
I asked for help on the PR that I think made the change, #3278. In [that discussion](https://github.com/tokio-rs/tokio/commit/d74d17307dd53215061c4a8a1f20a0e30461e296#r48012180) it was recommended that we document the fix.
Added a sentence to help anyone else in the same boat!
=> stream: documentation note for throttle unpin

tokio-stream/Cargo.toml, tokio-test/Cargo.toml, tokio-test/src/io.rs
Previously, the inner 'rx' of the Mock IO object used an unbound
receiver channel for mock 'Actions'. This allowed Mock to auto
implement Sync. Mock was recently converted to use dynamic 
dispatch, which now needs the marker Sync to continue to
implement these traits.
I am upgrading our package to use Tokio 1.0. This updated tokio-test from 0.2.1 to 0.4. In the current version, `Mock` is not `Sync`. 
This change adds the marker trait `Sync` to the dynamic dispatch, which should make `Mock` both `Send + Sync`.
=> test: Make Mock both Send and Sync

tokio/src/time/driver/sleep.rs
Rustdoc search doesn't do partial matches on aliases so currently searching "delay" doesn't show the `delay_for` or `delay_until` aliases (https://docs.rs/tokio/1.3.0/tokio/?search=delay). 
Alias the `Sleep` struct itself to "Delay" in order to increase visibility.
=> doc: alias sleep to delay

tokio-util/src/cfg.rs, tokio-util/src/lib.rs
`tokio-util::time` requiring the `time` feature was not documented
Add appropriate docs
Fix: #3596
=> docs: anotate time module as requiring time ft

tokio/src/runtime/handle.rs
EnterGuard must always be used.
{
let _guard = handle.enter(); // skipping _guard is wrong in all likelihood
}
Enterguard should be used. Without the let binding the its no-op. 
Mark EnterGuard struct as must_use
=> Issue 3608. Annotate struct EnterGuard with attr must_use

tokio/src/macros/select.rs, tokio/tests/macros_select.rs
Similar to `futures::select_biased!`, it is sometimes beneficial to
provide developers with strict control over the polling order of
futures. Most of the time, the fairness guarantees that `select!`
provides through RNG can be thought out by a careful developer to ensure
that no one future will monopolize all of the CPU time. In exchange for
this, the developer gets a performance boost as they do not need to
spend time generating endless random numbers.
Fixes: #2181
I want to control future polling order - both for more determinism and to decrease CPU burden from generating random numbers.
By adding a `biased;` argument to `select!`, we can disable the RNG that select performs by default. If this is omitted, we continue to do RNG and behavior is unchanged.
There are a myriad of syntax …
=> Introduce `biased` argument for `select!`

tokio/src/sync/mutex.rs
Fixes #3614
Expand example code to demonstrate ordering mechanism, and edit explanation where needed.
=> [docs] Improve Mutex FIFO explanation

tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/tests/loom_basic_scheduler.rs, tokio/src/runtime/tests/mod.rs
As explained in #3475,  futures passed to block_on get polled when subtasks become ready.
Introduce a `was_woken` field in the waker to track when the future should be polled.
=> runtime: avoid unnecessary polling of block_on future

tokio/src/time/mod.rs
Tiny thing I noticed.
Before:
After:
=> timer: Fix double newline in module docs

CONTRIBUTING.md
I ran into this when writing the docs for `Handle::block_on`. Seems to
be caused by a bug in cargo. Until that is fixed I think it makes sense
to mention it in the contributing guide.
=> Mention fix for building docs in contributing guide

tokio/src/sync/mpsc/bounded.rs
There was no link to `PollSender` in mpsc::Sender::send docs
Add link
Fix: #3611
=> docs: add link to PollSender

tokio/src/io/driver/mod.rs, tokio/src/io/driver/registration.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/time/driver/entry.rs, tokio/src/time/driver/handle.rs, tokio/src/time/driver/mod.rs, tokio/src/time/driver/tests/mod.rs, tokio/src/util/error.rs, tokio/tests/rt_handle_block_on.rs
This is a continuation of https://github.com/tokio-rs/tokio/pull/3549 but with tests for the behavior described [here](https://github.com/tokio-rs/tokio/pull/3549#issuecomment-785382050) and part of the implementation.
Still missing network operations failing if runtime associated with the handle has been shutdown. Changes to make timers and filesystem operations fail are at least passing the tests.
This is my first contribution to Tokio but let me know if I'm on the right track here 😊
Refs: #3097
Fixes #2965, #3096
cc @stuhood, @Keruspe
=> rt: add Handle::block_on

tokio/CHANGELOG.md, tokio/Cargo.toml
- macros: introduce biased argument for `select!` ([#3603])
- runtime: add `Handle::block_on` ([#3569])
- runtime: avoid unnecessary polling of `block_on` future ([#3582])
- runtime: fix memory leak/growth when creating many runtimes ([#3564])
- runtime: mark `EnterGuard` with `must_use` ([#3609])
- chore: mention fix for building docs in contributing guide ([#3618])
- doc: add link to `PollSender` ([#3613])
- doc: alias sleep to delay ([#3604])
- sync: improve `Mutex` FIFO explanation ([#3615])
- timer: fix double newline in module docs ([#3617])
[#3564]: https://github.com/tokio-rs/tokio/pull/3564
[#3613]: https://github.com/tokio-rs/tokio/pull/3613
[#3618]: https://github.com/tokio-rs/tokio/pull/3618
[#3617]: https://github.com/tokio-rs/tokio/pull/3617
[#3582]: …
=> chore: prepare Tokio v1.4.0

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- util: annotate time module as requiring `time` feature ([#3606])
[#3606]: https://github.com/tokio-rs/tokio/pull/3606
=> chore: prepare tokio-util v0.6.5

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml
- stream: documentation note for throttle `Unpin` ([#3600])
[#3600]: https://github.com/tokio-rs/tokio/pull/3600
=> chore: prepare tokio-stream v0.1.5

tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs
=> runtime: fix unclear docs for `{Handle,Runtime}::block_on`

tokio-stream/src/stream_ext/all.rs, tokio-stream/src/stream_ext/any.rs
Yielding can be expensive as the task is pushed to the back of the run queue.
Use a loop to continue to process items from the stream as much as possible, instead of yielding every time an item is produced by the stream.
=> stream: avoid yielding in AllFuture and AnyFuture

tokio/src/macros/select.rs
=> fix typo in select macro docs

tokio/src/task/task_local.rs
In some cases, async/await cannot be used, but we want to access `LocalKey`.
We add a `scope_in_place` method to make it support closures.
=> Add sync_scope for LocalKey

tokio-util/src/sync/poll_semaphore.rs
Cloning `PollSemaphore` allocates, even if it ends up unused (e. g. if `.try_acquire_owned` is used as a fast-path). This is due to the underlying `ReusableBoxFuture` which is always initialized and holding a future.
This turns the `ReusableBoxFuture` optional, and only initializes it on the first call to `.poll_acquire`, when it's actually needed.
The size of the semaphore doesn't change, rustc is able to exploit the niche in `NonNull` inside of `ReusableBoxFuture`, but this does introduce an additional branch, so not sure this optimization is worth it in the end.
If desired I can file a similar PR for `PollSender`.
=> chore: Avoid allocation if PollSemaphore is unused

tokio/src/io/async_fd.rs
Clarifies that users of AsyncFd must set the fd to nonblocking and should only poll readiness after failing to read/write.
As a newcomer, I misunderstood what I needed to do elsewhere in my code to properly use an AsyncFd.
Add to docs. Alice Ryhl [helped me debug my code](https://discord.com/channels/500028886025895936/500336333500448798/823549622626156554). Some of the wording paraphrases her explanation to me.
=> doc: Clarify requirements of AsyncFd

tokio/src/macros/select.rs
Not sure if `<expression>` should be `<handler>` for consistency, or not since it doesn't get anything bound.
But the arrow was definitely missing.
=> Usage typo

tokio/src/sync/mod.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/rwlock/owned_read_guard.rs, tokio/src/sync/rwlock/owned_write_guard.rs, tokio/src/sync/rwlock/owned_write_guard_mapped.rs, tokio/src/sync/rwlock/read_guard.rs, tokio/src/sync/rwlock/write_guard.rs, tokio/src/sync/rwlock/write_guard_mapped.rs, tokio/src/sync/tests/loom_rwlock.rs
I did not add mapping functions as it's not possible to implement them soundly without adding another generic parameter to the guards, which I will leave to another PR. I implemented `OwnedRwLockWriteGuard::downgrade` as a method because `RwLockWriteGuard::downgrade` is a method - but that was probably a mistake, so I'm not sure.
Fixes: #3327
The feature is already present for mutexes, and it is useful in some scenarios with `RwLock`s.
Add `OwnedRwLockReadGuard` and `OwnedRwLockWriteGuard`, which are variants of `RwLockReadGuard` and `RwLockWriteGuard` that store an `Arc`.
=> Add OwnedRwLockReadGuard and OwnedRwLockWriteGuard

tokio/src/process/mod.rs, tokio/src/time/driver/entry.rs
Some new warnings were added by Rust 1.51, which broke ci.
=> Fix warning from new Rust version

tokio/src/io/util/async_seek_ext.rs
An async equivalent to [`std::io::Seek::stream_position`](https://doc.rust-lang.org/nightly/std/io/trait.Seek.html#method.stream_position) that stabilized in Rust 1.51.
=> io: add AsyncSeekExt::stream_position

tokio/src/sync/mutex.rs
The opening lines of the current documentation for [tokio::sync::Mutex](https://docs.rs/tokio/1.4.0/tokio/sync/struct.Mutex.html) could be interpreted to imply `std::sync::Mutex` cannot be held across _any_ `.await` points, which isn't the case. 
Attempted to keep reasonably concise but allude to fact that not all `.await` points are equal in terms of bounds required.
=> (minor) amendments to Mutex docs

tokio/src/util/linked_list.rs
This PR makes the `Pointers` struct `!Unpin` to guard against pointers to it being marked noalias by [#82834][1]. It also uses raw pointer manipulation to access its fields to avoid the creation of references to those fields.
[1]: https://github.com/rust-lang/rust/pull/82834
=> Try to avoid noalias attributes on intrusive linked lists

tokio/src/sync/notify.rs, tokio/tests/sync_notify.rs
Noticed this small bug when reading through notify.rs.
The Drop implementation for sync::notify::Notified has a case where it sets the notification state to EMPTY, regardless of previous state. This is motivated by a comment claiming that this is correct in all cases except when the previous state is NOTIFIED, in which case the state will be changed back to NOTIFIED further down in notify_locked. But with the introduction of notify_waiters this is no longer always true, because that call is filtered by the notification type being NotificationType::OneWaiter. Indeed the following can happen:
```
n = Notify::new()
a = n.notified()
a.poll()            // adds a to waiters list, sets state to WAITING
n.notify_waiters()  // removes a from waiters list, sets state to EMPTY
n.notify_one() …
```
=> sync: fix notification permit getting dropped on receiver drop

tokio/src/net/tcp/socket.rs
There's a typo in a rustdoc comment.
Make the typo go away 😅
=> Typo in socket.rs: operationg => operating

tokio/src/sync/semaphore.rs
Right now the only way to check if a semaphore is closed is to do the following:
```rust
let is_closed = matches!(
semaphore.try_acquire_many(0),
Err(TryAcquireError::Closed)
);
```
It would be nice if I could just call `semaphore.is_closed()` instead.
Add a `is_closed` method to the public `Semaphore` API which calls the `is_closed` method of the underlying low level semaphore.
=> Add Semaphore::is_closed method

tokio/src/sync/oneshot.rs, tokio/tests/sync_oneshot.rs
Get oneshot channel to return closed if value already read. This is an alternative to #3671 opening it now to make sure that CI is all good
=> Remove panic from oneshot receiver

tokio/src/sync/mod.rs, tokio/src/sync/once_cell.rs, tokio/tests/async_send_sync.rs, tokio/tests/sync_once_cell.rs
Separating https://github.com/tokio-rs/tokio/pull/3513 into two PRs for clarity, as requested by @Darksonn. Since `Lazy` depends on `OnceCell`, a PR for `Lazy` will be opened once this PR lands.
=> Add OnceCell

tests-build/tests/fail/macros_invalid_input.rs, tests-build/tests/fail/macros_invalid_input.stderr, tokio-macros/src/entry.rs, tokio-macros/src/lib.rs
Improves a few of the error messages for `#[tokio::main]` and `#[tokio::test]`. The changes are probably best illustrated by the [new trybuild tests](https://github.com/tokio-rs/tokio/compare/david/macro-ux-improvements?expand=1#diff-553e2f6155b23cc1814b3d3250207aa169153045fbf16807a1314faa6582d15e).
I also added a note to the docs about `start_paused` requiring the `test-util` feature which wasn't mentioned previously. Took me some digging to discover.
=> macros: various error message improvements

tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/write_vectored.rs
=> io: add `AsyncWriteExt::write_vectored`

tokio-util/src/sync/poll_semaphore.rs
The `tokio::sync::Semaphore` type provides a
[`Semaphore::available_permits` method][1] which returns the current
number of permits available on the semaphore.
`tokio_util::sync::PollSemaphore` [does not expose such a method][2]. It
is possible to use `PollSemaphore::into_inner` or
`PollSemaphore::clone_inner` to unwrap the inner semaphore, but this may
require cloning/dropping the semaphore's `Arc` which shouldn't be
necessary to access the permits.
This commit adds `PollSemaphore::available_permits`. It also adds
`PollSemaphore::add_permits` while we're here.
Closes #3682
[1]: https://docs.rs/tokio/1.4.0/tokio/sync/struct.Semaphore.html#method.available_permits
[2]: https://docs.rs/tokio-util/0.6.5/tokio_util/sync/struct.PollSemaphore.html#implementations
=> util: add `PollSemaphore::{add_permits, available_permits}`

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/rwlock/owned_write_guard.rs, tokio/src/sync/rwlock/owned_write_guard_mapped.rs, tokio/src/sync/rwlock/write_guard.rs, tokio/src/sync/rwlock/write_guard_mapped.rs, tokio/tests/sync_rwlock.rs
Currently `RwLock` `MAX_READS` is capped to 32 which is too low
for some usecases (see #3633).
This PR adds a constructor that allows for specifying the max reads.
It also bumps the default number of max reads from 32 to `u32::MAX >> 3`
Fix: #3633
=> Allow to configure RwLock max reads

tokio/src/net/tcp/socket.rs
Missing trait `IntoRawFd` implementation for `TcpSocket`.
`impl`s `IntoRawFd` for `TcpSocket`.
=> net: implements IntoRawFd for TcpSocket

tokio/src/time/mod.rs
The example uses `Duration::from_secs(1)` and the explanation says something about 300ms, which does not match.
Use "1s" instead in the explanation.
--- 
As said in the Contributors guide: 
> Even tiny pull requests (e.g., one character pull request fixing a typo in API documentation) are greatly appreciated
:laughing:
=> Fix doc: Let comment match example

tokio/src/park/mod.rs, tokio/src/runtime/basic_scheduler.rs
We are seeing a few "failed to park" panics in the wild. The panic messages are very unhelpful as they don't contain information about the underlying error.
Add a `fmt::Debug` constraint to `Park::Error`. This trait is internal and all implementors already satisfy it. Then we can use `expect()` on the result of `park()` directly.
=> Require Park::Error: Debug for better panic messages.

tokio/src/runtime/basic_scheduler.rs, tokio/tests/task_abort.rs
This purports to fix the bug reported in #3662
The first commit simply ignores that the context is missing. What happens then (to the best of my understanding) is that the task header stays linked in the scheduler until the the scheduler is dropped. Any future polls of the task will simply never reach the scheduler, but be stopped by the harness and report the cancellation since it's already aware of the task state.
That leads us to the second commit, where I try to add a mechanism for remotely notifying the scheduler to remove the linked task. This is similar to how `tokio::spawn` notifies the thread about new tasks if run from a different thread (as it would if used from inside a `tokio::spawn_blocking`). This should result in the task *eventually* being cleaned under one of the …
=> Prevent basic_scheduler from panicking if a task is aborted from another thread

tests-build/tests/fail/macros_invalid_input.rs, tests-build/tests/fail/macros_invalid_input.stderr, tests-build/tests/macros.rs, tests-build/tests/pass/forward_args_and_output.rs, tokio-macros/src/entry.rs
Fixes #2388
Previously `#[tokio::test]` would error on functions that took
arguments. That meant other attribute macros couldn't do further
transformations on them. This changes that so arguments are forwarded as
is.
Whatever else might be included on the function is forwarded as well.
For example return type, generics, etc.
Worth noting that this is only for compatibility with other macros.
`#[test]`s that take arguments will still fail to compile.
A bit odd that [trybuild] tests don't fail `#[test]` functions with
arguments which is why the new tests are run with `t.pass(...)`. They do
actually fail if part of a real crate.
[trybuild]: https://crates.io/crates/trybuild
=> macros: forward input arguments in `#[tokio::test]`

tokio/src/sync/mpsc/bounded.rs
=> sync: add `mpsc::Sender::capacity`

tokio/src/sync/semaphore.rs
The fairness can be seen by noting that `RwLock` is implemented using it, and `RwLock` is fair.
=> Document that Semaphore is fair

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- util: makes `Framed` and `FramedStream` resumable after eof (#3272)
- util: add `PollSemaphore::{add_permits, available_permits}` (#3683)
- chore: avoid allocation if `PollSemaphore` is unused (#3634)
=> Prepare tokio-util 0.6.6

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/sync/rwlock.rs, tokio/tests/sync_rwlock.rs
- io: add `AsyncSeekExt::stream_position` (#3650)
- io: add `AsyncWriteExt::write_vectored` (#3678)
- io: add a `copy_bidirectional` utility (#3572)
- net: implement `IntoRawFd` for `TcpSocket` (#3684)
- sync: add `OnceCell` (#3591)
- sync: add `OwnedRwLockReadGuard` and `OwnedRwLockWriteGuard` (#3340)
- sync: add `Semaphore::is_closed` (#3673)
- sync: add `mpsc::Sender::capacity` (#3690)
- sync: allow configuring `RwLock` max reads (#3644)
- task: add `sync_scope` for `LocalKey` (#3612)
- chore: try to avoid `noalias` attributes on intrusive linked list (#3654)
- rt: fix panic in `JoinHandle::abort()` when called from other threads (#3672)
- sync: don't panic in `oneshot::try_recv` (#3674)
- sync: fix notifications getting dropped on receiver drop (#3652)
- io: clarify requirements of …
=> Prepare Tokio v1.5.0

tokio/Cargo.toml, tokio/src/fs/file.rs, tokio/tests/fs_file.rs
I saw [this](https://www.reddit.com/r/rust/comments/lg0a7b/benchmarking_tokio_tasks_and_goroutines/) on the rust subreddit and I wondered if `preadv2(..., RWF_NOWAIT)` would help.
Try doing a non-blocking read before punting to the threadpool on Linux.
If the data is already available in cache this will avoid cross-thread interaction and remove a copy.  It should help with latency too as reads that can be satisfied now won't need to wait in queue until other fs operations are complete.
According to my basic testing it helps. The benchmark I ran was https://github.com/wmanley/tokio-fs-bench which is based on the gist from the reddit thread above. On my laptop with the frequency scaling disabled I get 32s with this change and 42s without.  For comparison the rust_block_in_place …
=> File: Try doing a non-blocking read before punting to the threadpool

tokio-util/src/udp/frame.rs, tokio-util/tests/udp.rs
This changes `UdpFramed` from holding a `UdpSocket` to a `Borrow<UdpSocket>`.
Often, you will have an `Arc<UdpSocket>` which you want to share among many tasks but also still be able to use the helper functions from `tokio-util`. Unfortunately, `UdpFramed` only takes a `UdpSocket`.
~~The disadvantage of this approach is that `into_inner` and `get_mut` must be removed, does that seem like an acceptable trade-off for the added flexibility?~~
edit: `into_inner` doesn't actually have to be removed, ~~my mistake, only `get_mut`~~ 
edit: `get_mut` now implemented specifically for `UdpFramed<C, UdpSocket>`
Make `UdpFramed` take a `T: Borrow<UdpSocket>` so it can take UdpSocket types generically. 
I'm happy to take any feedback or alternate approach that is suggested. But let me take your …
=> util: UdpFramed takes Borrow<UdpSocket>

tokio/src/time/interval.rs
This patch allows accessing the period of an `Interval`
Closes: #3701
=> time: add getter for Interval's period

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/mod.rs
The `mpsc::Sender::reserve` method currently returns a permit that borrows
from the `Sender`. It would be nice to have a version of it that returns
an owned permit.
This branch adds an `OwnedPermit` type and `Sender::{reserve_owned,
try_reserve_owned}` methods. Unlike the comparable methods on
`Semaphore`, these methods do *not* require an `Arc<Sender>` as the
receiver; this is because the sender internally reference counts the
channel and is already cheap to clone. Requiring an `Arc` would simply
add an unnecessary second layer of reference counting, which is not
ideal; instead, the documentation encourages the user to clone the
sender prior to calling `reserve_owned` when necessary.
Since these methods take the `Sender` by value, they also have the ability
to _return_ the `Sender` from …
=> sync: add `mpsc::Sender::{reserve_owned, try_reserve_owned}`

tokio/src/time/clock.rs, tokio/tests/time_pause.rs
Previously, `time::advance` would set the mocked clock forward the
requested amount, then yield. However, if there was no work ready to
perform immediately, this would result in advancing to the next expiring
sleep.
Now, `time::advance(...)` will unblock at the requested time. The
difference between `time::advance(...)` and `time::sleep(...)` is a bit
fuzzy. The main difference is `time::sleep(...)` operates on the current
task and `time::advance(...)` operates at the runtime level.
Fixes #3710
=> time: prevent `time::advance` from going too far

tokio/src/io/util/lines.rs, tokio/src/io/util/read_line.rs, tokio/src/io/util/read_to_string.rs, tokio/src/io/util/split.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/sync/watch.rs, tokio/src/util/slab.rs
Make clippy a little bit happier.
Apply some lints.
There are still few things that clippy complains about but some of them like:
https://github.com/tokio-rs/tokio/blob/2b9b55810847b4c7855e3de82f432ca997600f30/tokio/src/runtime/task/state.rs#L31-L38
were probably put there on purpose see https://github.com/tokio-rs/tokio/pull/3588#discussion_r588998717
And other warnings about wrong self conventions on internal functions and these warnings should be probably ignored but there are few of them so either at crate level or will require few single `#[allow]`
<details>
```
warning: methods called `as_*` usually take `self` by reference or `self` by mutable reference
--> tokio/src/io/driver/scheduled_io.rs:405:19
|
405 |         fn as_raw(handle: &NonNull<Waiter>) -> NonNull<Waiter> {
| …
```
=> chore: Fix some clippy lints

tokio/src/sync/mod.rs, tokio/src/sync/mutex.rs, tokio/tests/sync_mutex.rs
Part of #2471, extends the work of #2445. Both this PR and #2445 together close #2471.
This PR introduces the `MappedMutexGuard` type and adds a `map` associated function to `MutexGuard`. The work here is largely based on #2445, so thanks @udoprog for the great PR. This was very easy to implement using your work as a reference.
`MappedMutexGuard` works almost exactly the same as [`parking_lot::MappedMutexGuard`](https://docs.rs/lock_api/0.3.4/lock_api/struct.MappedMutexGuard.html), but adapted to the internals of `tokio::sync::Mutex`. The `MappedMutexGuard` type stores a reference to the semaphore from the original `Mutex` as well as a raw pointer `*mut T` that is the result of calling the function passed to `map`. The `Mutex` does not hold a mutable reference to its data (it uses an …
=> Added map associated function to MutexGuard that uses new MappedMutexGuard type

tokio/src/runtime/task/core.rs
This PR updates the panic message you get when a `JoinHandle` is polled after completion.
=> Update JoinHandle panic message

tokio/src/macros/select.rs
=> Fix missing backtick in select doc

.github/workflows/ci.yml, tokio-stream/src/stream_map.rs, tokio/src/io/driver/registration.rs, tokio/src/io/poll_evented.rs, tokio/src/time/driver/entry.rs, tokio/src/util/rand.rs
Documentation of private items is not tested in CI.
Adding the `--document-private-items` should check all documentation.
=> CI: check docs of private items

tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/write_all_buf.rs, tokio/tests/io_write_all_buf.rs
This commit adds write_buf_all to AsyncWriteExt. This enables
users to write an entire `Buf` to a writer without needing to manually
loop through each chunk of the `Buf` manually.
With `write_buf`, users still need to loop through the individual chunks of the buffer. This both more verbose and has a misuse potential where a user thinks that the entire buf will be written.
Add `write_all_buf` which provides a 1-call API to write an entire `impl Buf` to `AsyncWrite`
=> io: Add write_all_buf to AsyncWriteExt

tokio-stream/src/wrappers.rs, tokio-stream/src/wrappers/broadcast.rs
Reuse the tokio::sync::broadcast::error::RecvError instead.
I want to use the broadcast stream wrapper in the situtaion where some codes requiring the custom Error implementing std::error:Error trair, such as [wrap_stream()](https://docs.rs/hyper/0.14.7/hyper/body/struct.Body.html#method.wrap_stream) function in hyper crate.
We can add impl std::error::Error, and core::fmt::Display for `BroadcastStreamRecvError`, but since the custom error doesn't provide any additional info, so it's better removing it and reusing the existing error from broadcast channel.
=> stream: implement Error and Display for BroadcastStreamRecvError

tokio/src/process/mod.rs
If we don't supply `.stdin(Stdio::piped())`, the line `8` always panics on `unwrap() on None`.
The example wasn't working when trying to copy-paste it over.
I updated the example, adding `.stdin(Stdio::piped())` and import to fix the issue.
=> process: Updated example

tokio-test/src/macros.rs, tokio/tests/time_pause.rs, tokio/tests/time_sleep.rs
The `assert_elapsed` macro is generally useful for Tokio users. This
commit extracts `assert_elapsed` into `tokio-test`.
It adapts the macro for general use by using `std::time::Duration`
instead of an integral millis value for time comparison.
`assert_elapsed` is a generally very handy macro when interacting with tokio & time, especially because the 1ms tolerance is required.
Extract the macro into tokio-test in the two locations it was defined, refactor to use the slightly modified macro.
=> tokio-test: extract assert_elapsed macro

tokio/src/sync/notify.rs, tokio/src/sync/tests/loom_notify.rs
When there are no current waiters (state is EMPTY or NOTIFIED), `Notify::notify_waiters` just bumps the current generation counter and returns. But it does so non-atomically. Since the lock is held we know that the generation counter is untouched, and we cannot have entered state WAITING; we might however be overwriting NOTIFIED by EMPTY or EMPTY by NOTIFIED if we race with another thread.
The former case is bad: if notify_waiters() races with notify_one(), we might overwrite NOTIFIED by EMPTY and drop a permit.
The latter case is more or less fine, because if we race with a waiter that uses up a permit we can claim to have notified it and have its permit remain. But with enough effort one can show an API contract violation.
Use an atomic increment.
=> sync: preserve permit state in notify_waiters

.github/workflows/ci.yml, tokio-stream/src/stream_map.rs, tokio-util/src/udp/frame.rs, tokio/src/io/driver/mod.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/time/driver/handle.rs, tokio/src/util/linked_list.rs, tokio/src/util/rand.rs
nightly-2020-09-21 (1.48.0-nightly) is very old.
Bump to nightly-2021-04-25, which is the latest nightly where the major components (e.g., rustfmt) are available.
=> chore: bump nightly to nightly-2021-04-25

tokio/src/task/blocking.rs, tokio/src/task/mod.rs
This PR updates the documentation on `block_in_place` to fix some things that were unclear. There is already a PR that tries to address this, but I have found that the documentation needed a larger change.
Closes: #3659, #3658
=> Update documentation on block_in_place

tokio/src/io/util/mem.rs, tokio/tests/io_mem_stream.rs
Performing a write on a closed DuplexStream (i.e. other end is dropped) results in an Err(BrokenPipe). However, if there is a writer waiting to be awoken from a buffer-full condition, it would previously be ignored, and thus stuck in suspended state, as no further reads could ever be made.
We encountered this when trying to write data from a tokio task via the duplex stream to a hyper Body::wrap_stream (via `ReaderStream`) for a server application. If the client aborted the download prematurely, the socket would be closed and the error propagated up to the duplex, but if there was a pending write (very likely, as we read from a fast source over potentially slow network) it would get stuck and never woken up, thus the tokio task would run indefinitely and cleanup routines wouldn't.
This PR …
=> io: wake pending writers on DuplexStream close

tokio/tests/macros_select.rs
The integration test `macros_select` had an unused variable. It doesn't appear to be needed or used, so this PR removes it.
=> Fix CI for Rust 1.52

examples/Cargo.toml, tokio-stream/Cargo.toml, tokio-util/Cargo.toml
This adds path fragments to all workspace tokio dependencies.
If this is not in place, test builds won't pick up now changes from other components. E.g. it's not possible to add an example of something recently added to tokio in `examples` (root cause of build failure in #3760). 
Passes locally so here's to hoping it works in CI. [A `resolver` bump](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) was not needed AFAIU, so there's no MSRV implications.
=> cargo: path dependencies for all tokio things

tokio-util/src/compat.rs
When appropriate, implement `AsRawFd` and `AsRawHandle` for `tokio_util::compat::Compat<T>`, so this wrapper type can be used in contexts requiring them.
I ran into this while trying to wrap tokio's `Stdin`/`Stdout` for usage with the futures crate, while still being able to check if they're a tty with crossterm.
A blanket impl passing AsRawFd/AsRawHandle through to the inner read/write type
=> util: impl AsRawFd/AsRawHandle for Compat<T>

.github/workflows/ci.yml, benches/Cargo.toml, benches/fs.rs
```console
$ cargo build --benches --manifest-path benches/Cargo.toml
Compiling benches v0.0.0 (...)
error[E0432]: unresolved import `tokio::stream::StreamExt`
--> benches/fs.rs:3:5
|
3 | use tokio::stream::StreamExt;
|     ^^^^^^^^^^^^^^^^^^^^^^^^ no `StreamExt` in `stream`
error[E0599]: no method named `next` found for struct `FramedRead<tokio::fs::File, BytesCodec>` in the current scope
--> benches/fs.rs:35:43
|
35 |                 let _bytes = input_stream.next().await.unwrap();
|                                           ^^^^ method not found in `FramedRead<tokio::fs::File, BytesCodec>`
error: aborting due to 2 previous errors
```
=> benches: fix build error

README.md
It is currently being treated as text.
Before:
https://github.com/tokio-rs/tokio#example
After:
https://github.com/taiki-e/tokio/tree/readme#example
=> chore: enable syntax highlighting for toml in readme

tokio/src/io/util/copy_bidirectional.rs, tokio/src/io/util/mem.rs, tokio/src/task/unconstrained.rs
Both `duplex` and `copy_bidirectional` require io-util feature:
https://github.com/tokio-rs/tokio/blob/312321cbd37e544bf10d1e97e5a61b9fac01a49f/tokio/src/io/mod.rs#L242-L252
However, don't displayed on docs:
https://docs.rs/tokio/1.5.0/tokio/io/index.html#functions
=> doc: fix doc-cfg on io::duplex, io::copy_bidirectional, and task::unconstrained

tokio/src/sync/barrier.rs
Thread and task are not interchangeable.
=> Barrier doc should use task, not thread

tokio/src/net/tcp/stream.rs, tokio/src/net/unix/stream.rs, tokio/tests/tcp_stream.rs, tokio/tests/uds_stream.rs
`try_read` and `try_write` on these two types already exist, so it makes sense to add their vectored I/O counterparts. I needed this when implementing vectored writes on a shared TCP stream type (which makes use of `writable`/`try_write` instead of the `AsyncWrite` implementation).
Add these methods.
=> net: add `{Tcp, Unix}Stream::try_{read, write}_vectored`

tokio/src/process/unix/driver.rs, tokio/src/process/unix/mod.rs, tokio/src/process/unix/orphan.rs, tokio/src/process/unix/reap.rs, tokio/src/runtime/driver.rs, tokio/src/signal/unix.rs
* Child processes are akin to global variables within the parent
process. Reaping orphaned child processes can be done by any thread
(so long as someone does it), but repeated efforts from multiple
threads to reap the same process do not add any additional benefit
* Previously, each Runtime would register its own SIGCHLD listener and
check it for updates during every tick. If a signal was received, then
it will attempt to reap the orphan queue.
* Signals are also "global resources" meaning that when one signal comes
in, all listeners within that process are woken up. This means that if
an application has multiple runtimes, each of them will attempt to
drain the entire orphan queue any time a SIGCHLD is received (the
first one to try will reap whichever orphans have exited, and the
other …
=> process: avoid redundant effort to reap orphan processes

tokio/src/io/util/buf_reader.rs, tokio/src/io/util/buf_stream.rs, tokio/src/io/util/buf_writer.rs, tokio/tests/io_buf_reader.rs, tokio/tests/io_buf_writer.rs
Closes #2291
The implementation and added tests are basically based on my PRs in futures-rs. (rust-lang/futures-rs#1573, rust-lang/futures-rs#1608)
However, the implementation is complicated than futures-rs due to:
- tokio 1.x AsyncSeek allows/recommends calling poll_complete before start_seek 
- https://github.com/tokio-rs/tokio/pull/3491#discussion_r571434636
=> io: impl AsyncSeek for BufReader/BufWriter/BufStream

tokio/CHANGELOG.md, tokio/Cargo.toml
- fs: try doing a non-blocking read before punting to the threadpool (#3518)
- io: add `write_all_buf` to `AsyncWriteExt` (#3737)
- io: implement `AsyncSeek` for `BufReader`, `BufWriter`, and `BufStream` (#3491)
- net: support non-blocking vectored I/O (#3761)
- sync: add `mpsc::Sender::{reserve_owned, try_reserve_owned}` (#3704)
- sync: add a `MutexGuard::map` method that returns a `MappedMutexGuard` (#2472)
- time: add getter for Interval's period (#3705)
- io: wake pending writers on `DuplexStream` close (#3756)
- process: avoid redundant effort to reap orphan processes (#3743)
- signal: use `std::os::raw::c_int` instead of `libc::c_int` on public API (#3774)
- sync: preserve permit state in `notify_waiters` (#3660)
- task: update `JoinHandle` panic message (#3727)
- time: prevent …
=> Prepare Tokio v1.6.0

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml
- macros: forward input arguments in `#[tokio::test]` (#3691)
- macros: improve diagnostics on type mismatch (#3766)
- macros: various error message improvements (#3677)
=> chore: prepare tokio-macros v1.2.0

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- udp: make `UdpFramed` take `Borrow<UdpSocket>` (#3451)
- compat: implement `AsRawFd`/`AsRawHandle` for `Compat<T>` (#3765)
=> chore: prepare tokio-util v0.6.7

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml
- stream: implement `Error` and `Display` for `BroadcastStreamRecvError` ([#3745])
- stream: avoid yielding in `AllFuture` and `AnyFuture` ([#3625])
[#3745]: https://github.com/tokio-rs/tokio/pull/3745
[#3625]: https://github.com/tokio-rs/tokio/pull/3625
=> chore: prepare tokio-stream v0.1.6

tokio-test/CHANGELOG.md, tokio-test/Cargo.toml
- test: add `assert_elapsed!` macro (#3728)
=> chore: prepare tokio-test v0.4.2

tokio/src/sync/watch.rs
Add a method to `sync::watch::Sender` to be able to check how many receivers currently exist.
I wanted to be able to get a new `Receiver` from a `Sender` and stop sending if there aren't any receivers. To get a new `Receiver` however i need to store one (a `Sender` cannot create a `Receiver`). Which makes it impossible with the current methods to detect if the channel has no active receivers left.
```rust
struct Sender<T> {
tx: watch::Sender<T>,
rx: watch::Receiver<T>
}
impl<T> Sender<T> {
pub fn subscribe(&self) -> watch::Receiver<T> {
self.rx.clone()
}
/// Returns Err(()) if no receivers exist
pub fn send(&mut self, msg: T) -> Result<(), ()> {
if self.tx.receiver_count() <= 1 {
Err(())
} else {
self.sender.send(msg).unwrap();
Ok(())
}
}
}
```
Adding `receiver_count` seams to be the …
=> add receiver_count to sync::watch::Sender

tokio-stream/tests/stream_chain.rs, tokio-stream/tests/stream_merge.rs, tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/io/util/buf_reader.rs, tokio/src/net/unix/ucred.rs, tokio/src/runtime/queue.rs, tokio/src/runtime/task/state.rs, tokio/src/runtime/tests/task.rs, tokio/src/time/driver/entry.rs, tokio/src/time/driver/wheel/mod.rs, tokio/tests/io_buf_reader.rs
`*::max_value()` and `*::min_value()` will be deprecated in the future rust version. 
We should replace those two methods with the const `*::MAX` and `*::MIN` 
both reach stable since `1.42`. Our minimum supported version is `1.45`, so I don't 
think we have any negative impact on this change.
Simply replace `*::{max, min}_value()` to const `*::MAX` and `*::MIN` respectively.
=> chore: replace `*::{max, min}_value()` to const `*::MAX` and `*::MIN` respectively

tokio-util/src/time/mod.rs, tokio/src/lib.rs, tokio/src/macros/cfg.rs
This pull request proposed a solution to fix issue #3787.
This pull request fixed issue #3787 by removing [doc(inline)] from
macro `cfg_macros` and added proper #[doc(inline)] attributes
to `pub use` items inside `cfg_macros` calls.
It's probably not `cfg_macros`s responsibility to inlining public
macros, though it's conveninent to do so. Notice that in lib.rs:
```rust
cfg_macros! {
/// Implementation detail of the `select!` macro. This macro is **not**
/// intended to be used as part of the public API and is permitted to
/// change.
#[doc(hidden)]
pub use tokio_macros::select_priv_declare_output_enum;
...
}
```
`#[doc(hidden)]` and `#[doc(inline)]` are conflict with each other
in the sense of correctness.
- Adds a little bit of code verbosity, but should be acceptable because the number …
=> doc: fix invalid `#[doc(inline)]` warnings on latest nightly.

tokio/src/io/util/buf_stream.rs
Looks like the `AsyncSeek` implementation for `BufStream` fell through the cracks in #3491 so this PR just adds the missing impl
=> io: impl AsyncSeek for BufStream

tokio/src/task/mod.rs
Typo is easy fix.
Fix the typo
=> Fix minor doc typo (stray backtick)

tokio/tests/tcp_into_std.rs
Assigning a specific port can lead to colisions and test failures
if this port is already in use. This results in this test failing
~0.5% of the time on Android's CI.
Fixes:
test tcp_into_std ... FAILED
failures:
---- tcp_into_std stdout ----
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
=> tcp_into_std: assign an unused port

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/fs/file.rs, tokio/tests/fs_file.rs
This release reverts #3518 because it doesn't work on some kernels due to a kernel bug. (#3803)
Reverting the commit now allows us more time to test #3821.
=> Prepare tokio 1.6.1

tokio/src/io/async_write.rs
Fixes #3819. 
Clarified documentation, using the text from `std::io::Write` as a model.
=> Clarify limits on return values of AsyncWrite::poll_write.

.github/workflows/ci.yml
~~Fixes CI fail on master: https://github.com/tokio-rs/tokio/runs/2710069192?check_suite_focus=true~~ EDIT: see https://github.com/tokio-rs/tokio/pull/3827#issuecomment-851445668
minimal-versions check is a check that is only worthwhile for public crates.
=> ci: ignore private crates in minimal-versions check

tokio/src/sync/mpsc/bounded.rs
Just noticed a minor spelling mistake whilst reading the docs.
Corrected the mistake.
=> sync: Fix minor spelling mistake in mpsc::Sender docs

tokio/src/runtime/task/state.rs
=> runtime: fix typo in task state doc

tokio/src/future/mod.rs, tokio/src/future/trace.rs, tokio/src/runtime/basic_scheduler.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/spawner.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/task/harness.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task/raw.rs, tokio/src/runtime/task/waker.rs, tokio/src/runtime/thread_pool/mod.rs
In support of https://github.com/tokio-rs/console/issues/37, we want to understand when a specific task's waker has been interacted with, such as when it is awoken, or if it's forgotten (not cloned), etc.
When the `tracing` feature is enabled, a super trait of `Future` (`InstrumentedFuture`) is implemented for `Instrumented<F>` that allows grabbing the task's ID (well, its span ID), and stores that in the raw task trailer. The waker vtable then emits events and includes that ID.
=> tracing: instrument task wakers

tokio/src/io/util/async_read_ext.rs
The current documentation for `read_buf` says:
> If the supplied buffer is not empty and the function returns `Ok(0)` then the source has reached an “end-of-file” event.
This confused me since I took "empty" to mean that the buffer had no readable data in it (like a vec with len() == 0).
I think part of the confusion is due to buffers like `bytes::BytesMut` using "empty" to refer to buffers that have
no readable data (i.e. a newly created buffer that hasn't been written to yet).
After reading the source code and chatting with @Darksonn it's clear that `Ok(0)` is returned when there's no more
room in the buffer to write additional bytes. This is "empty" in the sense that an empty in the sense that an empty struct is,
but not in the sense that an empty vec is (which IMO is a closer mental …
=> doc: Clarify EOF condition for AsyncReadExt::read_buf

tokio/src/sync/semaphore.rs
Closes #3795 
Add examples to `Semaphore` and its methods. All doctests pass. Let me know if you find anything too verbose or confusing.
=> doc: Add examples to `Semaphore`

README.md
The first sample in the README mentions adding tokio to Cargo, but it uses version `1.5.0` while `1.6.0` is the current minor.
This PR changes `1.5.0` to `1.6.0` to encourage new users to grab the latest stable.
=> chore: update version in README.md

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/error.rs
The `RecvError` type is not used anywhere.
Closes: #3826
=> Deprecate mpsc::RecvError

tokio/src/sync/futures.rs, tokio/src/sync/mod.rs, tokio/src/sync/notify.rs
This is my attempt to get #3372 in, so addressed the comment there and opened this PR.
Quoting that PR:
> I would like to avoid boxing the Notified future when storing it a struct in fede1024/rust-rdkafka#320 .
Add `sync::futures` module which exposes `sync::notify::Notified`.
=> feat: Export `sync::notify::Notified` publicly.

tokio/src/runtime/task/waker.rs
It was an mistake to emit the `op` as a `dyn Debug`, it should be emitted as a string directly.
=> tracing: emit waker op as str instead as Debug

tokio/tests/uds_cred.rs
It was disabled due to an OS bug that has been fixed on all currently
supported releases of FreeBSD
To increase test coverage
To reenable a test that no longer needs to be disabled
=> Reenable test_socket_pair on FreeBSD

tokio/src/time/clock.rs, tokio/src/time/driver/mod.rs, tokio/tests/time_pause.rs
Update the advance logic to factor in the timer's ms rounding.
Fixes #3837
=> time: fix time::advance() with sub-ms durations

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml
- net: add named pipes on windows (#3760)
- net: add `TcpSocket` from `std::net::TcpStream` conversion (#3838)
- sync: add `receiver_count` to `watch::Sender` (#3729)
- sync: export `sync::notify::Notified` future publicly (#3840)
- tracing: instrument task wakers (#3836)
- macros: suppress `clippy::default_numeric_fallback` lint in generated code (#3831)
- runtime: immediately drop new tasks when runtime is shut down (#3752)
- sync: deprecate unused `mpsc::RecvError` type (#3833)
- io: clarify EOF condition for `AsyncReadExt::read_buf` (#3850)
- io: clarify limits on return values of `AsyncWrite::poll_write` (#3820)
- sync: add examples to Semaphore (#3808)
=> chore: prepare Tokio v1.7.0

tokio/src/io/async_fd.rs
The only way to use `AsyncFdReadyMutGuard` currently is through `try_io`, since it is impossible to access the underlying object. In some situations, it is desirable to use `clear_ready` and `retain_ready` directly instead of `try_io`. Enable this by adding `get_ref` and `get_mut` methods.
When using `AsyncFd` with an I/O object that does not communicate readiness through `ErrorKind::WouldBlock`, code using `try_io` becomes hard to read. In the following example, the `next()` method returns `None` when no new data is ready.
```rust
let mut guard = ready!(self.inner.poll_read_ready_mut(cx))?;
match guard.try_io(|s| {
s.get_mut()
.next()
.ok_or_else(|| ErrorKind::WouldBlock.into())
}) {
Ok(event) => Poll::Ready(Some(event)),
Err(_) => Poll::Pending,
}
```
As seen here, you have to …
=> io: add get_{ref,mut} methods to AsyncFdReadyGuard and AsyncFdReadyMutGuard.

tokio/src/time/instant.rs
The `tokio::time::Instant::saturating_duration_since` docs contain a confusing typo: they say `zero duration if that instant is earlier than this one` instead of `later`.
The corresponding `std::time::Instant` docs say `later`: https://doc.rust-lang.org/std/time/struct.Instant.html#method.saturating_duration_since
In both cases, the doctests confirm that `later` is the correct behaviour.
- Fix the typo
=> Fix typo in Instant::saturating_duration_since docs

tokio/src/time/interval.rs, tokio/src/time/mod.rs, tokio/tests/time_interval.rs
Occasionally, `tokio::time::Interval` may be delayed from ticking, usually because `tick` isn't being called often enough (like if a task is `.await`ing something else). By default, `Interval` continues to schedule ticks normally, which causes a burst of ticks until it is "caught up" in time where it should be. This behavior is not always desired, however.
This PR adds the `MissedTickBehavior` enum to the `time` module to allow users to specify what behavior they'd like `Interval` to exhibit when ticks are missed.
Closes #3574
=> time: allow users to specify `Interval` behavior when delayed

tokio/src/sync/watch.rs
Add a method similar to `borrow` that updates the version counter. Using this method, it would be possible to update `WatchStream` to avoid the issue described by #3655.
Fixes: #3666
Closes: #3731
=> sync: add `Receiver::borrow_and_update`

tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/src/lib.rs, tokio/src/runtime/queue.rs, tokio/src/runtime/thread_pool/mod.rs, tokio/src/runtime/thread_pool/worker.rs, tokio/tests/rt_threaded.rs
Tokio 1.7.0 introduced a change intended to eagerly shutdown newly
spawned tasks if the runtime is in the process of shutting down.
However, it introduced a bug where already spawned tasks could be
shutdown too early, resulting in the potential introduction of deadlocks
if tasks acquired mutexes in drop handlers.
Fixes #3869
The PR is based on the `tokio-1.7.x` branch and will be released as 1.7.1.
=> rt: avoid early task shutdown

tokio/src/sync/once_cell.rs, tokio/tests/sync_once_cell.rs
[`std::lazy::OnceCell`](https://doc.rust-lang.org/std/lazy/struct.OnceCell.html) [implements `From<T>` for `OnceCell<T>`](https://doc.rust-lang.org/std/lazy/struct.OnceCell.html#impl-From%3CT%3E), but [`tokio::sync::OnceCell`](https://docs.rs/tokio/1.7.1/tokio/sync/struct.OnceCell.html) does not. Generally, tokio tries to match std's API as closely as possible, so this could be considered an API hole.
This PR adds that implementation. While this is a niche case, it also allows `tokio::OnceCell` to be constructed from a `T`. As it is right now, one can construct an uninitialized `OnceCell` with `new` and `const_new`, or one that may or may not be initialized using `new_with`, but it is not possible to construct one directly from a `T` (although this could be done with `new_with(Some(T))`).
=> sync: Implement `From<T>` for `OnceCell<T>`

examples/Cargo.toml, examples/named-pipe-ready.rs, tokio/src/net/windows/named_pipe.rs, tokio/tests/named_pipe.rs
As discussed in [other issues](https://github.com/tokio-rs/tokio/pull/3388#issuecomment-773633244) related to named pipes, a very common use case for named pipes is using them similarly to unix domain sockets, however the initial named pipe support in 1.7 was intentionally bare bones and thus didn't support doing both read and write operations on the same pipe in the same task, but which is supported for `UnixStream` and other `net` types via the ready/try_read/try_write etc family of methods.
This PR just copies the following methods from `UnixStream` to `NamedPipeClient` with 0 changes other than in the doc comments, as well as adding an example and a test.
- [`ready`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.ready)
- …
=> Add ready/try methods to `NamedPipeClient`

tokio/src/time/driver/sleep.rs
I was searching for how to wait, and I couldn't find anything so I then looked for sleep after 5 minutes. Now, on the docs, if you search for `wait` the sleep method will come up.
I added a `#[doc(alias = "wait")]` to make it so when you search on the docs for wait, you will get shown the sleep method.
=> feat: add wait alias to sleep

tokio-util/src/sync/cancellation_token.rs, tokio-util/src/sync/cancellation_token/guard.rs, tokio-util/src/sync/mod.rs
Usually, cancellation is implemented as dropping a future. However, this does not work when a future internally spawns background tasks.
A new method `drop_guard` is added. It returns a special guard which cancels the token unless disarmed.
Intended usage:
```rust
async fn my_simple_fut() {
let token = CancellationToken::new();
let _g = token.clone().drop_guard();
tokio::task::spawn(async move {
some_lib::do_work(..., token);
});
// some other work here.
}
```
=> Add drop guard for cancellation token

examples/named-pipe-ready.rs, tokio/src/net/windows/named_pipe.rs, tokio/tests/named_pipe.rs
#3866 added various methods to the `NamedPipeClient`, but to keep the PR small, didn't for `NamedPipeServer`, so this is just the follow up PR to #3866 to add those same methods to `NamedPipeServer`.
Adds the same methods to `NamedPipeServer` as were added to `NamedPipeClient` in #3866.
- [`ready`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.ready)
- [`readable`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.readable)
- [`poll_read_ready`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.poll_read_ready)
- [`try_read`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.try_read)
- [`try_read_vectored`](https://docs.rs/tokio/1.7.0/tokio/net/struct.UnixStream.html#method.try_read_vectored)
- …
=> Add read/try methods to `NamedPipeServer`

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/async_write_ext.rs, tokio/src/macros/select.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs, tokio/src/net/windows/named_pipe.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/mutex.rs, tokio/src/sync/notify.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs, tokio/src/sync/watch.rs
This PR documents cancellation safety. It also moves the "Avoid racy `if` preconditions" section in the `select!` documentation since otherwise the first code block on the page shows how _not_ to use it, which seems counterintuitive.
=> Document cancellation safety

tokio/src/runtime/handle.rs, tokio/src/task/builder.rs, tokio/src/task/local.rs, tokio/src/task/mod.rs, tokio/src/task/spawn.rs, tokio/src/util/trace.rs, tokio/tests/task_builder.rs
Task name annotations are helpful in order to better understand what is happening in an async application
This PR adds a cfg_trace-gated unstable builder tokio::task::Builder, which allows authors to annotate a task at runtime with an appropriate name. It includes `task.name` instrumentation for Builder::spawn, Builder::spawn_local, and Builder::spawn_blocking
=> tracing: add tokio::task::Builder

tokio/src/io/util/buf_reader.rs, tokio/src/io/util/buf_stream.rs, tokio/src/io/util/buf_writer.rs, tokio/tests/io_buf_writer.rs, tokio/tests/support/io_vec.rs
With vectored writes reintroduced in #3149, `BufWriter` can provide an efficient implementation both with or without vectored write support in the underlying writer, and advertise it with `is_write_vectored`.
Provide a custom implementation of `AsyncWrite::poll_write_vectored` by coalescing data from the slices in the buffer, unless it is more efficient to pass one or all of them directly to the underlying writer. This needs to be optimized differently depending on whether the underlying writer supports efficient vectored output.
=> Efficient implementation of vectored writes for BufWriter

tokio/src/net/unix/stream.rs, tokio/tests/tcp_accept.rs, tokio/tests/uds_stream.rs
=> net: add epollhup test

.github/workflows/ci.yml, tokio/src/runtime/tests/loom_queue.rs, tokio/src/runtime/tests/mod.rs, tokio/src/runtime/tests/queue.rs, tokio/src/runtime/tests/task.rs
We currently don't run any tests with tracing enabled.
=> Test with tracing

tokio/src/sync/watch.rs, tokio/tests/sync_watch.rs
This fixes a bug where `borrow_and_update` incorrectly sets the version when called after closing the channel.
=> sync: fix watch borrow_and_update

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml
- io: add `get_{ref,mut}` methods to `AsyncFdReadyGuard` and `AsyncFdReadyMutGuard` ([#3807])
- io: efficient implementation of vectored writes for `BufWriter` ([#3163])
- net: add ready/try methods to `NamedPipe{Client,Server}` ([#3866], [#3899])
- rt: add `tokio::task::Builder` ([#3881])
- sync: add `watch::Receiver::borrow_and_update` ([#3813])
- sync: implement `From<T>` for `OnceCell<T>` ([#3877])
- time: allow users to specify Interval behaviour when delayed ([#3721])
- net: handle HUP event with `UnixStream` ([#3898])
- doc: document cancellation safety ([#3900])
- time: add wait alias to sleep ([#3897])
- time: document auto-advancing behaviour of runtime ([#3763])
[#3163]: https://github.com/tokio-rs/tokio/pull/3163
[#3721]: https://github.com/tokio-rs/tokio/pull/3721
[#3763]: …
=> Prepare Tokio v1.8.0

tokio-stream/src/stream_ext/collect.rs
```text
warning: replacing a value of type `T` with `T::default()` is better expressed using `std::mem::take`
--> tokio-stream/src/stream_ext/collect.rs:116:9
|
116 |         mem::replace(collection, String::new())
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `std::mem::take(collection)`
|
= note: `#[warn(clippy::mem_replace_with_default)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default
warning: replacing a value of type `T` with `T::default()` is better expressed using `std::mem::take`
--> tokio-stream/src/stream_ext/collect.rs:135:9
|
135 |         mem::replace(collection, vec![])
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `std::mem::take(collection)` …
```
=> chore: fix new clippy complaint
