README.md

Please believe me, I'm not trying to stalk you :-)
I'm not sure if there's any criteria to be met in order to be in that list, so just reject this PR if my crate doesn't cut it.

Add tokio-inotify to the list of 3rd party tokio crates

---

README.md
examples/tinyhttp.rs

Pull in the latest changes from tokio-core.

Track core

---

src/reactor/mod.rs

Remove Core:id.

---

src/lib.rs
src/net/mod.rs
src/net/tcp.rs
src/net/udp/frame.rs
src/net/udp/mod.rs
src/reactor/io_token.rs
src/reactor/mod.rs
src/reactor/poll_evented.rs

For about every public struct.

Doc improvements

---

src/lib.rs
src/net/tcp.rs
src/net/udp/frame.rs
src/net/udp/mod.rs

Follow up on https://github.com/tokio-rs/tokio/pull/47.

Derive debug on public structs

---

src/reactor/global.rs
src/reactor/mod.rs
tests/wakeup.rs

Change a return value of reactor::poll to io::Result.

---

src/reactor/mod.rs

The caller should be required to have control of a reactor when setting
it as a fallback. A `Handle` is used to pass into libraries and
functions and should not grant capability of using the associated
reactor as a fallback.
Closes #71

Move set_fallback to Reactor from Handle.

---

src/net/mod.rs
src/net/tcp.rs

Rename TcpStreamNew -> ConnectFuture

---

examples/chat-combinator.rs
examples/chat.rs
examples/hello_world.rs

This adds a more detailed chat example.

Add a chat example

---

examples/README.md
examples/connect.rs
examples/udp-codec.rs
src/net/mod.rs
src/net/udp/frame.rs
src/net/udp/mod.rs
tests/udp.rs

Remove UdpCodec

---

examples/hello_world.rs

Fix example doc comment

---

src/reactor/mod.rs

Remove references to `Remote`

---

.travis.yml
benches/latency.rs
benches/tcp.rs

Make benches compilable again

---

src/reactor/mod.rs

Sort of based on this:
https://github.com/tokio-rs/tokio/issues/139

Adjust handle documentation

---

.travis.yml

Try using an env var to enforce the doc deploy condition.

Only deploy docs on linux. Take 2

---

src/runtime.rs

Sometimes, passing ownership to an executor is necessary. For example,
some libraries require taking ownership of one.
This patch adds a function that returns an executor associated with a
runtime.

Provide a handle to Runtime's executor.

---

examples/chat.rs
examples/hello_world.rs

The PR that updated the examples skipped some comments. This patch
updates thhe comments.

Fix some comments in the examples.

---

tokio-threadpool/src/lib.rs
tokio-threadpool/tests/threadpool.rs

Currently, if a thread pool instance is dropped without being shutdown,
the workers will run indefinitely. This is not ideal as it leaks the
threadpool.
This patch forces the thread pool to shutdown on drop.
Closes #151

Shutdown the thread pool on drop.

---

examples/chat.rs

This handles cases where clients send large amounts of data while on
localhost.
Closes #192

Improve the chat example, making it more robust

---

src/runtime.rs

Currently, the runtime does not shutdown if the runtime handle is
dropped. This can happen during a panic or when the value is simply
dropped.
This patch forces the runtime to shutdown if it is not explicitly
shutdown.
Fixes #209

Shutdown the runtime on drop

---

tokio-reactor/src/atomic_task.rs

This is a port of https://github.com/rust-lang-nursery/futures-rs/pull/868.

Reduce AtomicTask spurious notifications

---

Cargo.toml
README.md
src/lib.rs
src/net.rs
src/net/mod.rs
src/net/tcp/mod.rs
src/net/udp/mod.rs
tokio-tcp/CHANGELOG.md
tokio-tcp/Cargo.toml
tokio-tcp/LICENSE
tokio-tcp/README.md
tokio-tcp/src/incoming.rs
tokio-tcp/src/lib.rs
tokio-tcp/src/listener.rs
tokio-tcp/src/stream.rs
tokio-tcp/tests/chain.rs
tokio-tcp/tests/echo.rs
tokio-tcp/tests/limit.rs
tokio-tcp/tests/stream-buffered.rs
tokio-tcp/tests/tcp.rs
tokio-udp/CHANGELOG.md
tokio-udp/Cargo.toml
tokio-udp/LICENSE
tokio-udp/README.md
tokio-udp/src/frame.rs
tokio-udp/src/lib.rs
tokio-udp/src/recv_dgram.rs
tokio-udp/src/send_dgram.rs
tokio-udp/src/socket.rs
tokio-udp/tests/udp.rs

Hope it's an okay time to do this!
Fixes #217

Move tokio::net module into tokio tcp/udp crates

---

examples/README.md
examples/udp-client.rs

Add UDP client example (send/recv_dgram)

---

examples/connect.rs

I've postpone the *spawn* of the stream that forwards data from *stdin* to the connection by utilizing `future::lazy`. It's the most easy way to fix the example (#240) I was able to come up with.
Closes  #240.

Fix `connect` example for UDP

---

CHANGELOG.md
Cargo.toml
src/lib.rs
tokio-executor/CHANGELOG.md
tokio-executor/Cargo.toml
tokio-executor/src/lib.rs
tokio-io/Cargo.toml
tokio-reactor/CHANGELOG.md
tokio-reactor/Cargo.toml
tokio-reactor/src/lib.rs
tokio-tcp/Cargo.toml
tokio-threadpool/CHANGELOG.md
tokio-threadpool/Cargo.toml
tokio-threadpool/src/lib.rs
tokio-udp/Cargo.toml

This bumps the versions of crates that need to be released.

Bump versions

---

tokio-threadpool/tests/threadpool.rs

Fix unused variable in tokio-threadpool\tests\threadpool.rs:581:9

---

.travis.yml

See https://github.com/tokio-rs/tokio/issues/285

Build 32/64-bit Linux and FreeBSD on Travis CI

---

ci/tsan

This uses fences, which tsan does not understand.

Add arc::Weak to tsan filter.

---

examples/README.md
examples/print_each_packet.rs

Made by request from gitter:ruRust/easy

Add example that prints each packet from tcp client

---

tokio-timer/src/error.rs

Add additional timer::Error docs.

---

tokio-reactor/src/lib.rs
tokio-tcp/src/listener.rs
tokio-tcp/src/stream.rs
tokio-udp/src/socket.rs

Document Handle::default() behavior

---

Cargo.toml
README.md
tokio-uds/Cargo.toml
tokio-uds/LICENSE
tokio-uds/README.md
tokio-uds/src/datagram.rs
tokio-uds/src/incoming.rs
tokio-uds/src/lib.rs
tokio-uds/src/listener.rs
tokio-uds/src/recv_dgram.rs
tokio-uds/src/send_dgram.rs
tokio-uds/src/stream.rs
tokio-uds/src/ucred.rs
tokio-uds/tests/stream.rs

This moves http://github.com/tokio-rs/tokio-uds into the repository.

Import tokio-uds

---

tokio-threadpool/src/pool/mod.rs
tokio-threadpool/tests/threadpool.rs

The thread pool optimizes cases where a task currently running on the
pool spawns a new future. However, the optimization did not factor in
cases where two thread pools interacted.
This patch fixes the optimization and includes a test.
Fixes #342

Fix bug related to spawning optimization

---

tokio-fs/src/lib.rs

This doesn't conflict with anything in #450. It adds more detailed information, of a topic I'd like to link to from a summary of `blocking` for the tokio runtime.  Some of these details or a link could also be added to the blocking section of the tokio-threadpool documentation (as made visible as rustdoc in #450).

Additional details for tokio-fs rustdoc

---

tokio-threadpool/src/worker/mod.rs

Benchmark:
```
name                    before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
threadpool::spawn_many  4,682,929       4,076,864          -606,065  -12.94%   x 1.15
threadpool::yield_many  11,976,416      11,835,437         -140,979   -1.18%   x 1.01
```

Optimize spinning in Worker::run

---

tokio-executor/src/global.rs

Meant to address #376 based on our discusson on the issue. Hope this matches what you had in mind!

implement Send and Sync for DefaultExecutor

---

tests/runtime.rs
tokio-current-thread/src/lib.rs
tokio-current-thread/src/scheduler.rs

Previously, futures spawned on a `Handle` to a current thread executor would not be counted as running on the executor until they were received. This caused some sad races where a spawned future may never be executed even though the remote thread was running at the time of the spawn (see #476).
This PR makes the `num_futures` count atomic, and updates it atomically in the `Handle` before the future is even sent. This ensures that as long as the executor is running when `spawn` returns, the future will be executed.
Unfortunately, we still have a race in that a `spawn` can succeed just after the executor has determined that it is idle, but before it is dropped. To solve this, an analogue to `Runtime::shutdown_on_idle` should be added that sets the shutdown marker bit in `num_futures`, and …

Count in-transit spawned futures to current thread executor as pending

---

src/fs.rs

tokio: expose tokio_fs::metadata

---

tokio-threadpool/src/pool/backup.rs
tokio-threadpool/src/pool/mod.rs

Terminate backup threads when idle

---

tokio-executor/src/global.rs

This is a bugfix to prevent stack overflow when calling `DefaultExecutor` recursively, which can happen when you pass `DefaultExecutor` to `with_default`.
I haven't yet run into this in production, but I realised it could happen when working on #472 and thought this might be worth fixing before someone else runs into this.
An alternative to returning an error could be to panic in these situations with a useful error message.
Let me know what you think!

detect and handle recursive calls to DefaultExecutor

---

tokio-threadpool/src/builder.rs

Fix num CPUs in threadpool::builder::Builder::new

---

.travis.yml
tokio-threadpool/Cargo.toml

Enable sanitizer tests for tokio-threadpool

---

tokio-tls/examples/echo.rs

Based on the current example on the front page of tokio.rs.

Add tokio-tls echo example.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This will help guide new contributors through the process. This has been adapted from the node.js contributing guide.
[Rendered](https://github.com/tokio-rs/tokio/blob/contributing/CONTRIBUTING.md)

draft initial CONTRIBUTING guide

---

tokio-async-await/Cargo.toml
tokio-async-await/README.md
tokio-async-await/src/async_await/compat/backward.rs
tokio-async-await/src/async_await/io/mod.rs
tokio-async-await/src/lib.rs

Fix some typos. This also includes a version bump.

async-await: misc fixes and typos

---

tokio-io/src/_tokio_codec/framed_write.rs

Reading code. Come across this line. Believe this (multi-line error message) is wrong.
Add a slash. I think this PR is trivial enough! :smiley:

Fix undesired multi-line error message

---

tokio-io/src/async_write.rs

These implementations were deferred because the standarad library did not provide a way to access the wrapped values at the time the code was originally written.  As of Rust 1.20, both `std::io::Take` and `std::io::Chain` offer `get_ref()` methods, so we can properly implement these functions now.

io: implement prepare_uninitialized_buffer for Take and Chain

---

src/io.rs

This was a missing export in the file. See #688.
Nothing to extraordinary, just added an export line.

re-export tokio_io::read in tokio::io

---

examples/hello_world.rs

The [hello-world example of in the docs](https://tokio.rs/docs/getting-started/hello-world/) has been changed to be a more simple client example. It links to the hello_world example in this repo which should also be changed to match.
I've updated the example to match the new simpler example from the docs.

Change hello-world example to new, simpler example

---

tokio-fs/src/file/mod.rs

I need this to work around line buffering in stdio - but I can imagine would be useful for other people too.
Ref https://github.com/denoland/deno/issues/948

Expose fs::File::from_std()

---

CONTRIBUTING.md

Just move a dot to the right place.

fix an invalid link

---

tokio-timer/src/delay_queue.rs
tokio-timer/tests/queue.rs

Fixes a bug that causes problems when doing multiple resets in delay queue.
We currently need to store both the delay and the key of the first expiring item, in order to know whether we should reset the delay of the first expiring item or not

Fix multi reset bugs in delay_queue

---

tokio-reactor/src/registration.rs

This replaces `AtomicTask::register_task(task::current())` with just `AtomicTask::register()`, making use of the optimization in there to not clone the task if not needed.
I tested this in hyper and did see it working, though the existing benchmarks weren't able to exercise it enough to see a difference.

reactor: use AtomicTask::register to reduce unnecessary task clones

---

tokio-fs/tests/file.rs

fs: fix tests

---

tokio-buf/CHANGELOG.md
tokio-buf/Cargo.toml
tokio-buf/README.md

Minor tweaks to `Cargo.toml` and add the date to `CHANGELOG`.

Bump tokio-buf to v0.1.0

---

.travis.yml
Cargo.toml
tokio-buf/src/lib.rs
tokio-buf/src/u8.rs

The rustfmt check did not fail when it should have.

Fix rustfmt check

---

ci/azure-test-stable.yml
tokio-tls/tests/smoke.rs

Per this thread
https://twitter.com/carllerche/status/1099875486061125632
Fixes the build
https://dev.azure.com/johnterickson/tokio/_build/results?buildId=398

Use generic CI environment variable that is already set by Appveyor

---

Cargo.toml

fix the dependencies version

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs
tokio-sync/CHANGELOG.md
tokio-sync/Cargo.toml
tokio-sync/README.md
tokio-sync/src/lib.rs

Also bumps:
- tokio-sync (v0.1.4)

Bump Tokio to v0.1.17

---

tokio/examples/README.md

Line for connect.rs is fixed
README.md has typo.
Fix line with typo.

Fix typo in README.md in examples

---

tokio-buf/src/size_hint.rs

Documentation was incorrect.
Documentation comment is corrected.

Corrected doc for tokio_buf SizeHint

---

tokio-trace/tokio-trace-core/src/subscriber.rs

The example code is ignored, because the macros would require pulling in `tokio_trace` as a dependency for `tokio_trace_core`.
Closes https://github.com/tokio-rs/tokio/issues/1007

Improve documentation of Subscriber::record and Subscriber::event

---

tokio-buf/src/util/mod.rs
tokio-buf/src/util/stream.rs

Produce a `Stream` from a `BufStream`.

buf: Add IntoStream

---

tokio-buf/Cargo.toml
tokio-codec/Cargo.toml
tokio-current-thread/Cargo.toml
tokio-executor/Cargo.toml
tokio-fs/Cargo.toml
tokio-io/Cargo.toml
tokio-reactor/Cargo.toml
tokio-signal/Cargo.toml
tokio-sync/Cargo.toml
tokio-tcp/Cargo.toml
tokio-test/Cargo.toml
tokio-threadpool/Cargo.toml
tokio-timer/Cargo.toml
tokio-tls/Cargo.toml
tokio-trace/Cargo.toml
tokio-trace/tokio-trace-core/Cargo.toml
tokio-udp/Cargo.toml
tokio-uds/Cargo.toml
tokio/Cargo.toml

Hopefully I will stop forgetting this step.

chore: remember to remove path deps on release

---

ci/azure-is-release.yml
ci/azure-test-stable.yml

The condition in CI is incorrect. This ports the fix from https://github.com/tower-rs/tower/pull/274

ci: fix isRelease condition

---

async-await/Cargo.toml
async-await/tests/macros.rs
azure-pipelines.yml
ci/azure-cargo-check.yml
ci/azure-test-nightly.yml
tokio-macros/src/lib.rs
tokio/src/runtime/current_thread/async_await.rs
tokio/src/runtime/current_thread/mod.rs

The function was left out from #1058. 
This also adds some tests and includes them in CI.
(WIP: lets see if CI works).

async-await: add `current_thread::Runtime::block_on_async`

---

tokio-futures/README.md

`tokio-futures/README.md`'s link to the examples was wrong.

Fix link in tokio-futures/README.md

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/lib.rs

Bump `tokio` version to v0.1.21.

---

.cirrus.yml
azure-pipelines.yml
ci/azure-test-stable.yml
tokio-executor/src/enter.rs
tokio-executor/src/executor.rs
tokio-executor/src/global.rs
tokio-executor/src/park.rs
tokio-futures/src/lib.rs
tokio-futures/src/macros.rs
tokio-sync/src/lib.rs
tokio-sync/src/loom.rs
tokio-sync/src/oneshot.rs
tokio-sync/src/task/atomic_waker.rs
tokio-sync/src/watch.rs
tokio-sync/tests/atomic_task.rs
tokio-sync/tests/errors.rs
tokio-sync/tests/fuzz_atomic_task.rs
tokio-sync/tests/fuzz_list.rs
tokio-sync/tests/fuzz_mpsc.rs
tokio-sync/tests/fuzz_oneshot.rs
tokio-sync/tests/fuzz_semaphore.rs
tokio-sync/tests/lock.rs
tokio-sync/tests/mpsc.rs
tokio-sync/tests/oneshot.rs
tokio-sync/tests/semaphore.rs
tokio-sync/tests/watch.rs
tokio-test/src/lib.rs
tokio-test/src/task.rs

This should (hopefully) get CI working in a partial way.

Update oneshot tests

---

ci/azure-install-rust.yml
ci/azure-test-nightly.yml
ci/azure-tsan.yml
tokio-sync/CHANGELOG.md
tokio-sync/Cargo.toml
tokio-sync/README.md
tokio-sync/src/lib.rs

Add Sync impl for Lock (#1117).
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>

Bump `tokio-sync` to 0.1.6

---

tokio/src/reactor/mod.rs
tokio/src/runtime/current_thread/mod.rs
tokio/src/runtime/mod.rs

https://github.com/tokio-rs/tokio/issues/1157
fix links

Fix links In Docs

---

tokio-sync/src/lock.rs
tokio-sync/tests/lock.rs

sync: Add LockFuture for Lock

---

tokio-sync/tests/lock.rs

sync: Fix lock test to actually test the inner lock value

---

tokio/src/io/mod.rs
tokio/src/io/read_exact.rs
tokio/tests/io.rs

Add read_exact method mirroring the read_exact method present in tokio-io

---

tokio/src/sync.rs

These types have been updated already.

tokio: re-export sync::{lock,mpsc}

---

.cirrus.yml

Caching takes longer than rebuilding.

ci: disable cache on cirrus

---

README.md

Add note in the readme about the master branch

---

tokio-timer/src/timer/handle.rs

Merging an older PR broke the build (even though CI passed).

timer: fix build

---

README.md

chore: Add link to docs

---

tokio/examples/echo.rs
tokio/examples/hello_world.rs

Finally got to the point where the TCP echo example can be updated.

tokio: Update echo example

---

tokio-test/Cargo.toml
tokio-test/src/io.rs
tokio-test/src/lib.rs
tokio-test/tests/io.rs

This is the mock_io ported from h2.

tokio-test: add tokio_test::io mock builder

---

README.md

chore: indicate the master branch docs are old.

---

azure-pipelines.yml
tokio-tcp/Cargo.toml
tokio-tcp/src/lib.rs
tokio-tcp/src/listener.rs
tokio/Cargo.toml

Forward incoming from tokio to tokio-tcp

---

.cirrus.yml
azure-pipelines.yml

chore: bump to newer nightly

---

tokio-codec/src/lib.rs
tokio-codec/src/lines_codec.rs
tokio/src/codec/mod.rs

Export `LinesCodecError`

---

tokio-sync/Cargo.toml
tokio-sync/tests/fuzz_atomic_waker.rs
tokio-sync/tests/fuzz_list.rs
tokio-sync/tests/fuzz_mpsc.rs
tokio-sync/tests/fuzz_oneshot.rs
tokio-sync/tests/fuzz_semaphore.rs

CI has failed on the master: https://github.com/tokio-rs/tokio/runs/180329463
This seems to be because loom's `std-future2` branch was deleted.

sync: switch branch of loom dev-dependency to master

---

tokio-io/src/async_buf_read.rs
tokio-io/src/async_read.rs
tokio-io/tests/lines.rs
tokio-io/tests/read_exact.rs
tokio-io/tests/read_line.rs
tokio-io/tests/read_to_end.rs
tokio-io/tests/read_to_string.rs
tokio-io/tests/read_until.rs

* `impl AsyncRead for &[u8]`
* `impl AsyncBufRead for &[u8]`
* `impl<T: AsRef<[u8]> + Unpin> AsyncRead for Cursor<T>`
* `impl<T: AsRef<[u8]> + Unpin> AsyncBufRead for Cursor<T>`

io: implement AsyncBufRead for &[u8] and Cursor

---

tokio-executor/src/park.rs

Update park implementation

---

tokio-tcp/Cargo.toml
tokio-tcp/src/listener.rs
tokio-tcp/src/stream.rs
tokio-threadpool/Cargo.toml
tokio-threadpool/src/task/mod.rs
tokio-threadpool/src/waker.rs
tokio-threadpool/tests/blocking.rs
tokio-timer/Cargo.toml
tokio-timer/src/delay_queue.rs
tokio-timer/src/interval.rs

Migrate threadpool to futures-util

---

tokio-test/Cargo.toml
tokio-test/src/clock.rs
tokio-test/src/lib.rs
tokio-test/src/macros.rs
tokio-test/src/task.rs

Remove git dep and add macro examples

---

tokio-sync/src/loom.rs
tokio-sync/src/mpsc/block.rs
tokio-sync/src/mpsc/list.rs
tokio-sync/src/semaphore.rs
tokio-sync/tests/fuzz_list.rs

Tracks changes made in https://github.com/carllerche/loom/pull/31.

sync: track loom changes

---

tokio-codec/src/decoder.rs

codec: a few suggestions

---

.cirrus.yml

Fixes https://github.com/tokio-rs/tokio/pull/1416#discussion_r312691921

ci: deny warnings in cirrus

---

tokio-codec/Cargo.toml
tokio-executor/Cargo.toml
tokio-fs/Cargo.toml
tokio-io/Cargo.toml
tokio-process/Cargo.toml
tokio-reactor/Cargo.toml
tokio-signal/Cargo.toml
tokio-sync/Cargo.toml
tokio-tcp/Cargo.toml
tokio-test/Cargo.toml
tokio-threadpool/Cargo.toml
tokio-threadpool/src/task/mod.rs
tokio-timer/Cargo.toml
tokio-tls/Cargo.toml
tokio-udp/Cargo.toml
tokio-uds/Cargo.toml
tokio/Cargo.toml
tokio/tests/reactor.rs

chore: update futures-preview to 0.3.0-alpha.18

---

tokio-process/src/lib.rs

Delete blocking Read/Write impls on ChildStd{in, out, err}

---

tokio-macros/Cargo.toml
tokio-macros/src/lib.rs

Subj, also removed unnecessary proc macro 2

macros: Upgrade syn/quote

---

Cargo.toml
azure-pipelines.yml
ci/patch.toml
tokio-net/Cargo.toml
tokio-net/src/lib.rs
tokio-net/src/udp/frame.rs
tokio-net/src/udp/mod.rs
tokio-net/src/udp/socket.rs
tokio-net/src/udp/split.rs
tokio-net/tests/udp.rs
tokio/Cargo.toml
tokio/src/net.rs
ui-tests/Cargo.toml
ui-tests/tests/features.rs
ui-tests/tests/ui/net_without_udp_missing_udp.rs
ui-tests/tests/ui/net_without_udp_missing_udp.stderr

udp: move tokio-udp into tokio-net

---

ci/azure-test-stable.yml

* This includes running docs, examples, and lib tests for each added
feature, to ensure nothing is broken

ci: ensure all tests are run for each feature

---

tokio-io/tests/chain.rs
tokio-io/tests/take.rs

chore: two async_await feature remained

---

tokio/Cargo.toml
tokio/src/net.rs

Address #1490 
Add a feature to main tokio crate for signal.

Expose signal from net as a feature

---

tokio-net/src/tcp/stream.rs

This is used in hyper, so re-add it temporarily, until we figure out a better solution (`tokio::net::TcpSocket` builder?).

Re-add temporarily TcpStream::connect_std

---

tokio-udp/CHANGELOG.md
tokio-udp/Cargo.toml
tokio-udp/README.md
tokio-udp/src/lib.rs

This is blocked on #1517 being merged first.

udp: Prep release v0.1.5

---

tokio-udp/tests/udp.rs

For https://github.com/tokio-rs/tokio/pull/1517 and https://github.com/tokio-rs/tokio/issues/1510

Add more unit tests for UdpFramed

---

tokio-io/src/split.rs
tokio-io/tests/split.rs

#1521 left off the `Send` / `Sync` imlementations.

io: add Send / Sync impls for ReadHalf / WriteHalf

---

README.md

Make sure people know about the current status of master.

chore: add stability note to readme.

---

tokio-executor/src/threadpool/pool/mod.rs
tokio-executor/src/threadpool/task/mod.rs
tokio-executor/src/threadpool/worker/mod.rs

clippy check failed on the master branch.
Related: https://github.com/rust-lang/rust-clippy/issues/3900

chore: fix clippy check failure

---

build-tests/Cargo.toml
build-tests/tests/features.rs
tokio-net/Cargo.toml
tokio-net/src/tracing.rs

This is causing doc generation to fail.

net: fix build with only process

---

tokio-io/Cargo.toml
tokio-io/src/io/buf_stream.rs

Changes: https://github.com/taiki-e/pin-project/releases/tag/v0.4.0-beta.1 (https://github.com/taiki-e/pin-project/pull/90 is the biggest change in this release)

chore: update pin-project to 0.4.0-beta.1

---

azure-pipelines.yml
build-tests/Cargo.toml
build-tests/tests/fail/macros_invalid_input.rs
build-tests/tests/fail/macros_invalid_input.stderr
build-tests/tests/features.rs
tokio-macros/src/lib.rs

macros: add build tests for #[tokio::main] and #[tokio::test]

---

build-tests/tests/fail/net_without_uds_missing_uds.rs
build-tests/tests/fail/net_without_uds_missing_uds.stderr
build-tests/tests/features.rs

net: fix build-tests for uds

---

tokio-sync/src/barrier.rs
tokio-sync/tests/barrier.rs

It wasn't before. Now it is. And that is better.

Make Barrier::wait future Send

---

azure-pipelines.yml

Because that has async/await now!

Move CI to beta

---

tokio-current-thread/tests/current_thread.rs
tokio-reactor/src/lib.rs
tokio-signal/examples/multiple.rs
tokio-signal/examples/sighup-example.rs
tokio-test/src/macros.rs

Not sure how this slipped past ci...
cc @dekellum

reactor: Remove extra semi colon

---

azure-pipelines.yml

chore: do not trigger CI on std-future branch

---

.cirrus.yml

chore: update Cirrus CI config to test on beta

---

tokio-io/src/io/copy.rs

Comments with typos are confusing
clean up a comment

fix a comment typo

---

tokio-sync/CHANGELOG.md
tokio-sync/Cargo.toml
tokio-sync/src/lib.rs

prepare tokio-sync v0.1.7 release.

---

tokio-fs/src/read_dir.rs
tokio-fs/src/symlink_metadata.rs
tokio-fs/src/write.rs

fs: remove unnecessary trait and lifetime bounds

---

tokio-io/src/io/mod.rs
tokio-io/src/lib.rs
tokio/src/io.rs

Take struct reexport to main crate

Take struct reexport to main crate

---

tokio/Cargo.toml
tokio/src/timer/timer/entry.rs

Much lighter-weight for a couple `align(_)` attributes.

timer: inline CachePadded type

---

tokio/src/timer/delay.rs

Make Delay must_use

---

tokio/src/timer/timer/handle.rs

Fix delay construction from non-lazy Handles

---

tokio/src/io/async_write.rs
tokio/tests/io_write.rs

Based on the implementation from the futures crate.

impl AsyncWrite for std::io::Cursor

---

ci/azure-clippy.yml
tokio/src/io/async_read.rs
tokio/src/process/mod.rs
tokio/src/runtime/current_thread/mod.rs
tokio/src/runtime/thread_pool/worker.rs
tokio/src/sync/watch.rs
tokio/src/timer/wheel/mod.rs

New lints were added, which fails on Tokio.

fix clippy

---

tokio-util/Cargo.toml
tokio-util/src/codec/framed.rs
tokio-util/src/codec/framed_read.rs
tokio-util/src/codec/framed_write.rs
tokio-util/src/codec/macros.rs
tokio-util/src/codec/mod.rs

feat: Remove Unpin requirement from Framed[Read,Write,]

---

tokio/src/sync/mod.rs
tokio/src/sync/task/atomic_waker.rs
tokio/src/sync/task/mod.rs
tokio/src/sync/tests/atomic_waker.rs
tokio/src/sync/tests/mod.rs

this is provided by `futures`.

make AtomicWaker private

---

tokio/src/runtime/thread_pool/idle.rs
tokio/src/runtime/thread_pool/queue/global.rs

When checking if a worker needs to be unparked, the SeqCst load does not
provide the necessary synchronization to ensure the scheduled task is
visible to the searching worker. The `load` is switched to
`fetch_add(0)` which does establish the necessary synchronization.
Adding unit tests catching this bug will require a fix to loom and will
be done at a later time. The bug fix has been validated with manual
testing.
Fixes #1768

runtime: fix lost wakeup bug in scheduler

---

ci/azure-test-stable.yml
tokio/src/sync/mod.rs

cargo-hack 0.3+ works on windows.
fixes https://github.com/tokio-rs/tokio/pull/1695#discussion_r340598096

chore: enable feature flag check on windows

---

tokio/src/fs/mod.rs
tokio/src/fs/read_dir.rs
tokio/src/lib.rs
tokio/src/net/tcp/listener.rs
tokio/src/net/tcp/mod.rs
tokio/src/net/tcp/stream.rs
tokio/src/net/udp/socket.rs
tokio/src/net/unix/datagram.rs
tokio/src/net/unix/listener.rs
tokio/src/net/unix/stream.rs
tokio/src/process/mod.rs
tokio/src/runtime/mod.rs
tokio/src/time/interval.rs

Link fix only, after this fix, it can succed to build `cargo doc --package`

Fix doc links

---

azure-pipelines.yml
ci/azure-check-docs.yml
ci/azure-test-stable.yml
tokio-test/src/io.rs

Check docs as part of CI. This should catch link errors.

ci: generate docs

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/lib.rs

This includes `task::LocalSet` as well as some misc small fixes.

prepare v0.2.1 release

---

tokio/src/signal/unix.rs

Implement Stream for signal::unix::Signal

---

tokio/src/io/util/async_buf_read_ext.rs

Include more details and an example.
Closes #1592

doc: add API docs for AsyncBufReadExt::read_line

---

tokio/src/net/tcp/stream.rs

This used to be exposed in 0.1, but was switched to private during the
upgrade. The `async fn` is sufficient for many, but not all cases.
Closes #1556

net: expose `TcpStream::poll_peek`

---

tokio/src/macros/cfg.rs
tokio/src/task/blocking.rs
tokio/src/task/error.rs
tokio/src/task/join.rs
tokio/src/task/local.rs
tokio/src/task/mod.rs
tokio/src/task/spawn.rs
tokio/src/task/yield_now.rs

Some feature flags are missing and some are duplicated.
Closes #1836

doc: fix documented feature flags for tokio::task

---

examples/Cargo.toml
examples/tinyhttp.rs

cannot build example  tinyhttp.
update dependency  crate http to version 0.2

examples: fix tinyhttp

---

examples/connect.rs

This PR removes no longer needed io workarounds from connect example.

remove io workarounds from example

---

tokio/src/time/instant.rs

Implement From conversions between std and tokio Instants

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

lots of fixes and some new features.

prepare v0.2.3 release

---

tokio/src/runtime/mod.rs
tokio/src/task/spawn.rs

doc: expand on runtime / spawn docs

---

tokio/benches/thread_pool.rs
tokio/src/runtime/park.rs

Update the rotted thread_pool benchmarks. These benchmarks are not the
greatest, but as of now it is all we have for micro benchmarks.
Adds a little yielding in the parker as it helps a bit.

chore: fix thread_pool benchmarks

---

tokio/src/task/spawn.rs

Fix typo with updated docs

---

tokio-macros/src/lib.rs

Fixes  #1944 by simply copying visibility

macros: inherit visibility

---

tokio/Cargo.toml

Enable the `full` feature when compiled for the playground

---

tokio/src/runtime/builder.rs

Improve runtime threading options docs

---

tokio-util/src/udp/frame.rs

Fix UdpFramed doc cfg_attr

---

tokio/src/io/poll_evented.rs
tokio/src/io/registration.rs
tokio/src/net/tcp/listener.rs
tokio/src/net/tcp/stream.rs
tokio/src/net/udp/socket.rs
tokio/src/net/unix/datagram.rs
tokio/src/net/unix/listener.rs
tokio/src/net/unix/stream.rs

... when thread-local tokio runtime is not set.

Document from_std functions panic

---

README.md
examples/README.md
tokio/README.md

Fixes outdated notes that claim the master branch is still being updated to async/await.

Fix old notes regarding examples

---

tokio/src/lib.rs

Add feature flag docs

---

README.md

Updates the url to https://discord.gg/tokio

Update tokio discord url

---

tokio/src/stream/chain.rs
tokio/src/stream/mod.rs
tokio/tests/stream_chain.rs

Asynchronous equivalent to `Iterator::chain`

stream: add `StreamExt::chain`

---

tokio/src/sync/broadcast.rs

sync: Add std error impl for broadcast errors

---

tokio/src/sync/broadcast.rs
tokio/src/sync/tests/loom_broadcast.rs

Fix broadcast bugs

---

tokio/src/runtime/mod.rs

Typo fix in runtime doc

---

tokio/examples/blocking.rs

fix typos in blocking example

---

tokio/src/task/state.rs

To see if they can actually be hit.

Run task state assertions under loom

---

ROADMAP.md

fix: small typos in ROADMAP.md

---

tokio/src/task/harness.rs

The previous implementation would perform a load that might be part of a
data race. The value read would be used only when race did not occur.
This would be well defined in a memory model where a load that is a part
of race merely returns an undefined value, the Rust memory model on the
other hand defines it to be undefined behaviour.
Perform read conditionally to avoid data race.
Covered by existing loom tests after changing casualty check to be
immediate rather than deferred.
Fixes: #2087

Read join waker conditionally to avoid data race

---

tokio-udp/src/frame.rs

udp: Fix warning with unused paren

---

tokio/tests/tcp_accept.rs

The old test from #2222 would occasionally fail on Windows and FreeBSD

Avoid race in tcp_accept::no_extra_poll

---

tokio/src/runtime/builder.rs

This tweaks the runtime builder default to defer and lazily
auto-detect the number of CPUs. This is done in order to
avoid performing useless operations which may be expensive
on some platforms (e.g. Linux, where it is coupled to CPU
frequency probing).
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7d5905dc14a87805a59f3c5bf70173aac2bb18f8
---
On Linux systems, creating a `runtime::Builder` and setting a fixed number of `core_threads` results in a number of useless syscalls to read `/proc/cpuinfo`. This becomes noticeable when building a large number of runtimes.
Do not perform auto-detection upfront, but lazily perform it only if a fixed number of worker threads was not specified.

runtime: lazily detect number of CPUs

---

tokio/src/sync/rwlock.rs

When reading #2252, I noticed that the `read` method had not been corrected in the same manner.

sync: Use yield rather than block on read method

---

tokio/src/net/tcp/listener.rs
tokio/src/net/unix/listener.rs

Following comments in https://github.com/tokio-rs/tokio/pull/2275, clarify the documentation of impl Stream for TcpListener and UnixListener.

Update listener docs

---

tokio-macros/CHANGELOG.md
tokio-macros/Cargo.toml
tokio-macros/src/lib.rs
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

Also includes `tokio-macros` v0.2.5.

prepare v0.2.12 release

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

chore: prepare v0.2.13 release

---

tokio-util/CHANGELOG.md
tokio-util/Cargo.toml
tokio-util/src/lib.rs

util: Prepare `0.3.0` release

---

tokio/src/sync/batch_semaphore.rs

notify out of lock again

---

tokio/tests/rt_common.rs

Add test verifying that joining on a task consumes the caller's budget.

rt: add task join coop test

---

tokio/tests/fs_file.rs

Adds a test ensuring that FS ops yield. While spawning to a bg thread will probably result in a yield, joining a task does count against the budget as well.

fs: add coop test

---

tokio/src/sync/broadcast.rs

This reverts commit 826fc21abfd04779cde92e4cc33de2adb42cf327.
The code was intentional. Holding the lock while notifying is
unnecessary. Also change the code to use `drop` so clippy doesn't
confuse people against their will.

Revert "Keep lock until sender notified (#2302)"

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

chore: Prepare `0.2.15` release

---

examples/Cargo.toml

This caused someone on discord a lot of trouble, so I thought I'd document the gotcha.

examples: add comment about dependency gotcha

---

tokio/src/stream/empty.rs
tokio/src/stream/pending.rs
tokio/tests/async_send_sync.rs

Add Send/Sync tests for all async fns

---

tokio/src/sync/mpsc/bounded.rs

close: https://github.com/tokio-rs/tokio/issues/2371
Sort methods on mpsc::Sender.

Sort methods on mpsc::Sender in doc

---

tokio-test/CHANGELOG.md
tokio-test/Cargo.toml
tokio-test/src/lib.rs
tokio-test/src/task.rs

test: Add `Future` and `Stream` impl for `Spawn`.

---

tokio/src/io/stdin.rs

io: rewrite stdin documentation

---

tokio/src/task/blocking.rs

This PR adds additional documentation to `spawn_blocking` and `block_in_place`.

task: update doc on spawn_blocking and block_in_place

---

tokio/src/runtime/builder.rs
tokio/src/runtime/handle.rs
tokio/src/runtime/mod.rs

As #2437 has been merged, some additional documentation on the exact semantics of `block_on` functions is necessary.

Update the documentation around Handle and Runtime

---

tokio/src/runtime/task/core.rs
tokio/src/runtime/task/harness.rs

Minor nit.
~~Also marked `bind_scheduler` as `unsafe` since that seems appropriate and `# Safety` is a nice place to put relevant documentation. Even though it's an internal function.~~

runtime: Get rid of ManuallyDrop usage

---

tokio/src/net/tcp/listener.rs

net: mention that bind sets SO_REUSEADDR

---

tokio/src/sync/mod.rs

Fix a typo

---

tokio/src/stream/mod.rs

stream: update StreamExt::merge doc

---

ci/azure-clippy.yml
tokio/src/macros/select.rs
tokio/tests/tcp_into_split.rs
tokio/tests/tcp_split.rs

Fixes #2251
Add `#[allow(clippy::modulo_one)]` on the statement in question.

Fix clippy errors

---

ci/azure-test-stable.yml
examples/echo-udp.rs
examples/echo.rs
examples/tinyhttp.rs
tokio/src/runtime/thread_pool/worker.rs
tokio/src/sync/batch_semaphore.rs
tokio/src/sync/mutex.rs
tokio/src/sync/semaphore_ll.rs
tokio/tests/rt_basic.rs
tokio/tests/task_local_set.rs
tokio/tests/tcp_accept.rs

CI failed on master as some lints was added in new stable rust: https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=6013&view=logs&jobId=3d108b53-2ec6-5cdc-c7d6-8422e74d0ce2&j=3d108b53-2ec6-5cdc-c7d6-8422e74d0ce2&t=3be243a4-6cf0-5788-6839-31e7c0a8dc85

chore: fix ci failure on master

---

azure-pipelines.yml
ci/azure-miri.yml

Fixes ci failure on master: https://github.com/tokio-rs/tokio/pull/2613#issuecomment-643081037

ci: pin compiler version in miri tests

---

tokio/tests/fs_file_mocked.rs

cargo clippy is failing on the [`many_single_char_names`](https://rust-lang.github.io/rust-clippy/master/index.html#many_single_char_names) lint
switch to more descriptive variable names

fix cargo clippy many_single_char_names on fs_file_mocked.rs test

---

.github/workflows/test_tokio.yml
ci/azure-test-stable.yml

https://github.com/tokio-rs/tokio/pull/2602#issuecomment-646301875

ci: use latest stable compiler on macOS ci

---

tokio-macros/src/lib.rs

macros: document basic_scheduler option

---

tokio/src/time/interval.rs

time: interval Stream impl requires stream feature

---

tokio/src/sync/broadcast.rs

Fix typo: suspectible -> susceptible

---

tokio/src/process/mod.rs

process: document remote killing for Child

---

benches/Cargo.toml
examples/Cargo.toml
tokio-macros/Cargo.toml
tokio-macros/src/lib.rs
tokio-test/Cargo.toml
tokio-test/src/lib.rs
tokio-util/Cargo.toml
tokio-util/src/lib.rs
tokio/Cargo.toml
tokio/src/lib.rs

This primarily disable publishing. Bug fixes will be applied to the v0.2.x branch.

chore: prepare for v0.3 breaking changes

---

tokio/src/sync/batch_semaphore.rs

sync: typo in impl Semaphore

---

tokio/src/sync/mpsc/bounded.rs

sync: remove rt-core from blocking_{send,recv}

---

tokio/src/sync/mod.rs
tokio/src/sync/rwlock.rs
tokio/src/time/delay_queue.rs

A few more small documentation fixes. Definitely open to suggestions on the new wording of `DelayQueue::insert` it still feels a bit awkward to me.

More docs fixes

---

tokio-util/src/lib.rs
tokio/src/io/util/async_read_ext.rs
tokio/src/net/udp/socket.rs
tokio/src/sync/mod.rs

Newest nightly found some new broken links.

Fix some links

---

tokio/src/process/mod.rs

Fixed some documentation in process module.
I believe this fixes #2235.

process: fix some docs

---

tokio/src/time/interval.rs

This fixed in https://github.com/tokio-rs/tokio/commit/8a7e57786a5dca139f5b4261685e22991ded0859#diff-709376f09a586d54932f814806dccb87R126-R128.

time: remove outdated todo comment

---

tokio-util/tests/framed_read.rs

util: remove Slice wrapper

---

.github/workflows/ci.yml
tokio-macros/src/lib.rs
tokio-test/src/lib.rs
tokio-util/src/lib.rs
tokio/src/io/util/async_read_ext.rs
tokio/src/lib.rs
tokio/src/net/udp/socket.rs
tokio/src/sync/mod.rs
tokio/src/time/delay_queue.rs

Backport of #2851
Closes #2850

ci: update nightly and fix all sorts of new failures

---

.github/workflows/ci.yml

ci: update miri flags

---

tokio/src/sync/mpsc/chan.rs
tokio/tests/sync_mpsc.rs

This requires performing the merge to master manually.

chore: merge v0.2.x changes

---

benches/mpsc.rs
benches/signal.rs

Currently e.g. VSCode "problems" window warns about unrelated code.

Fix unused_mut lint in benches

---

tokio/src/net/addr.rs
tokio/src/net/lookup_host.rs
tokio/src/net/mod.rs
tokio/src/net/tcp/listener.rs
tokio/src/net/tcp/stream.rs
tokio/src/net/udp/socket.rs

Seal ToSocketAddrs methods with an internal argument

---

tokio/src/stream/collect.rs

Seal FromStream methods with an internal argument

---

tokio/src/stream/collect.rs
tokio/tests/stream_collect.rs

stream: remove bytes from public API

---

tokio/src/io/util/async_buf_read_ext.rs
tokio/tests/async_send_sync.rs

https://github.com/tokio-rs/tokio/pull/2910#pullrequestreview-501739040

io, stream: assert !Unpin for ext trait futures

---

tokio-util/src/sync/cancellation_token.rs

util: fix a typo in sync/cancellation_token.rs

---

tokio-util/tests/time_delay_queue.rs
tokio/src/runtime/enter.rs
tokio/src/runtime/task/error.rs
tokio/src/sync/batch_semaphore.rs
tokio/src/time/error.rs
tokio/tests/macros_select.rs
tokio/tests/rt_common.rs
tokio/tests/stream_stream_map.rs
tokio/tests/sync_broadcast.rs

Closes: #2929
CI is broken
Fix the clippy lints

chore: Fix clippy lints

---

tokio/src/lib.rs

It currently says `0.2`
Change to `0.3`

Update version to 0.3 in module documentation

---

tokio-util/src/io/poll_read_buf.rs

This hopefully patches the soundness hole documented in #2827
Thanks to @Darksonn for spotting it!

util: prevent read buffer from being swapped during a read_poll

---

tokio/src/sync/watch.rs

The same as #2469; it is useful in synchronous contexts.

sync: Add `is_closed` method to watch sender

---

tokio/src/runtime/blocking/pool.rs
tokio/src/runtime/handle.rs
tokio/src/runtime/mod.rs
tokio/src/task/blocking.rs

Move common code and tracing integration into Handle
Fixes #2998
Closes #3004

tokio: deduplicate spawn_blocking

---

tokio/src/io/read_buf.rs

Currently it is unclear whether it is sound to convert an [`UninitSlice`][1] to a `ReadBuf` without first initializing it.
[1]: https://docs.rs/bytes/0.6/bytes/buf/struct.UninitSlice.html

Expand on de-initialization of ReadBuf

---

tokio/src/net/udp/socket.rs

udp: add UdpSocket::take_error

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

chore: prepare v0.3.3 release

---

tokio/src/net/tcp/listener.rs
tokio/src/net/tcp/stream.rs
tokio/src/net/udp/socket.rs
tokio/src/net/unix/datagram/socket.rs

net: add set_nonblocking to doc

---

tokio/src/process/unix/mod.rs

Potential fd leak was introduced in #3124
Apply an ownership wrapper to the fd before we potentially bail out.

process: fix potential file descriptor leak

---

tokio/src/stream/mod.rs

This is a commonly asked question.

Add documentation regarding futures' StreamExt

---

tokio/src/time/sleep.rs
tokio/tests/time_sleep.rs

Document maximum sleep duration

---

tokio/src/fs/copy.rs
tokio/src/fs/mod.rs
tokio/src/fs/read_to_string.rs
tokio/src/fs/write.rs

- link to AsyncRead trait
- consistency linking to std equivalents

fs: Small documentation fixes

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs

chore: prepare v0.3.4 release

---

tokio-util/src/udp/frame.rs

util: fix typo

---

tokio-util/Cargo.toml

Add rt to tokio-util full feature

---

.cirrus.yml

12.1 will be EoL in two months.

Switch FreeBSD CI environment to 12.2-RELEASE

---

tokio/tests/sync_mpsc.rs

Forward ports the test included in #3215. The mpsc semaphore has been
replaced in 0.3 and does not include the bug being fixed.

sync: forward port 0.2 mpsc test

---

tokio/src/task/task_local.rs

Fixes #3206 on `0.2.x` branch.

task: add missing feature flags for docs.rs on 0.2.x

---

tokio/src/net/unix/datagram/socket.rs
tokio/tests/uds_datagram.rs

net: expose poll_* methods on UnixDatagram

---

.github/workflows/ci.yml

https://github.com/tokio-rs/tokio/pull/3244#issuecomment-742412255

Enable ci for v0.3.x

---

tokio/src/net/tcp/split.rs
tokio/src/net/tcp/split_owned.rs
tokio/src/net/tcp/stream.rs

net: Update `TcpStream::poll_peek` to use `ReadBuf`

---

tokio/src/sync/mpsc/unbounded.rs

I'm upgrading one of my crates to tokio 0.3 and noticed that there is no `UnboundedReceiver::blocking_recv` even though such a method exists on `Receiver`. This PR copies the method over and updates the docs so now both receivers have that method.

Add blocking_recv method to UnboundedReceiver, similar to Receiver::blocking_recv

---

tokio/src/net/tcp/stream.rs
tokio/src/net/udp.rs

Closes: https://github.com/tokio-rs/tokio/issues/3248

doc: check for false-positives in TcpStream::ready doc test

---

tokio/src/lib.rs

Issue #3241 
Added it to the documentation needed

Added tracing to the feature flags section

---

tokio/src/net/unix/stream.rs
tokio/tests/uds_stream.rs

Refs: https://github.com/tokio-rs/tokio/issues/2968

net: add UnixStream readiness and non-blocking ops

---

tokio/src/lib.rs

Closes https://github.com/tokio-rs/tokio/issues/3282

docs: Add more comprehensive stream docs

---

tokio-util/Cargo.toml
tokio-util/src/codec/mod.rs

Write documentation for codec

---

.github/workflows/stress-test.yml

chore: fix stress test

---

.github/workflows/stress-test.yml

If this works, I will also submit PR for master.

Fix stress test 0.3

---

examples/Cargo.toml
tokio-test/Cargo.toml
tokio-util/Cargo.toml
tokio/Cargo.toml

chore: update to released `bytes` 1.0

---

tokio/src/sync/broadcast.rs

While working my way through the code of the broadcast module I noticed this newtype. There doesn't seem to be a good reason for it to exist compared to using a mutable reference directly. I guess at some time in the past it was or was intended to be used a shared `Recv` abstraction or some such.

sync: Remove underused internal Borrow wrapper

---

tokio-util/src/time/wheel/level.rs

remove macro_rules semicolon

---

tokio/src/lib.rs

Refs: https://github.com/tokio-rs/tokio/issues/3395

docs: test-util feature doesn't enabled with full

---

tokio/src/runtime/thread_pool/idle.rs

runtime: fix typo

---

tokio-macros/src/entry.rs
tokio/tests/macros_test.rs

macros: fix unused_braces in generated code

---

tokio/src/io/driver/mod.rs
tokio/src/runtime/blocking/pool.rs
tokio/src/runtime/handle.rs
tokio/src/task/spawn.rs
tokio/src/time/driver/handle.rs

Tokio 0.3.x: Update panic messages to include version

---

.github/workflows/ci.yml
tests-integration/Cargo.toml
tests-integration/src/bin/test-mem.rs
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/io/driver/registration.rs
tokio/src/io/driver/scheduled_io.rs
tokio/src/lib.rs

Merge branch 'tokio-1.0.x' into 'tokio-1.1.x' .
This also prepares for a 1.1.1 release.

chore: merge 1.0.x

---

tokio/src/loom/std/atomic_usize.rs
tokio/src/runtime/queue.rs
tokio/src/runtime/task/core.rs
tokio/src/runtime/task/harness.rs
tokio/src/sync/oneshot.rs

Split out of #3314 as it touches a wider set of the code. Still based on that PR however due to conflicts.

Minimize the amount of duplicated code 

---

.github/workflows/ci.yml
tests-integration/Cargo.toml
tests-integration/src/bin/test-mem.rs
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/io/driver/registration.rs
tokio/src/io/driver/scheduled_io.rs
tokio/src/lib.rs

Merges `tokio-1.1.x` into master.

chore: merge tokio-1.1.x

---

tokio/src/runtime/basic_scheduler.rs

edit a small word spelling mistake

edit a small word spelling mistake

---

tokio-util/src/codec/length_delimited.rs
tokio-util/src/sync/mpsc.rs
tokio/src/io/driver/scheduled_io.rs
tokio/src/runtime/context.rs
tokio/src/runtime/task/state.rs
tokio/src/runtime/thread_pool/worker.rs
tokio/src/sync/watch.rs
tokio/src/task/local.rs

Refs: https://github.com/tokio-rs/tokio/issues/3585

fix clippy warnings in newer versions

---

tokio-test/CHANGELOG.md
tokio-test/Cargo.toml
tokio-test/src/lib.rs

chore: Prepare `tokio-test v0.4.1` release

---

tokio-util/src/time/delay_queue.rs

While looking into another issue I noticed the docs for `DelayQueue` had bad indentation and some typos.

util: fix indentation and typos in `DelayQueue` docs

---

tokio/src/lib.rs
tokio/src/runtime/mod.rs
tokio/src/runtime/queue.rs
tokio/src/sync/mpsc/block.rs
tokio/src/task/task_local.rs
tokio/src/time/driver/handle.rs
tokio/src/util/linked_list.rs
tokio/src/util/wake.rs

fixed several typos in docs

---

tokio-stream/Cargo.toml
tokio/Cargo.toml

chore: update proptest to 1

---

tokio/src/macros/pin.rs

Fix incorrect link in doc

---

README.md

https://stackoverflow.com/questions/63874178/cannot-find-tokiomain-macro
looks obvious but I took 30 minutes to find what was going on

adds features full to readme

---

tokio/Cargo.toml

This fixes the CI failure in #3695 and #3696.

Upgrade loom to 0.5.0

---

tokio/src/signal/unix.rs

`libc::c_int` and `std::os::raw::c_int` are currently the same type, and are unlikely to change to other types, but technically libc can change this in the future minor version.
See https://github.com/tokio-rs/tokio/issues/3767 for more.
Use `std::os::raw::c_int` on public API to prevent leaking a non-stable type alias from libc.
Fixes #3767

signal: use std::os::raw::c_int instead of libc::c_int on public API

---

tokio/src/sync/task/atomic_waker.rs

Add missing backtick

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/fs/file.rs
tokio/tests/fs_file.rs

This PR will need to be manually merged into master via the CLI.

merge tokio 1.6.1 into master

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/time/clock.rs
tokio/src/time/driver/mod.rs
tokio/tests/time_pause.rs

Pull in the latest 1.6.x changes.
This PR must be merged using the CLI.

chore: merge 1.6.x

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/lib.rs
tokio/src/runtime/queue.rs
tokio/src/runtime/thread_pool/mod.rs
tokio/src/runtime/thread_pool/worker.rs
tokio/tests/rt_threaded.rs

This PR must be merged via the CLI to maintain the merge commits.

chore: merge tokio-1.7.1

---

tokio-stream/src/stream_ext/timeout.rs

Fix Timeout size_hint

---

tokio-stream/Cargo.toml
tokio-stream/src/wrappers/watch.rs
tokio-stream/tests/watch.rs

Closes: #3655
Requires: #3913, #3912

sync: fix watch wrapper

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/runtime/task/harness.rs
tokio/src/runtime/task/join.rs
tokio/src/runtime/task/raw.rs
tokio/src/runtime/task/state.rs
tokio/tests/task_abort.rs

chore: merge 1.5.x

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/runtime/task/harness.rs
tokio/src/runtime/task/join.rs
tokio/src/runtime/task/raw.rs
tokio/src/runtime/task/state.rs
tokio/tests/task_abort.rs

chore: merge 1.6.3

---

tokio/src/sync/watch.rs

This PR uses the type system to prevent bugs like the one in #3913 from happening again.

Wrap watch state in helper struct

---

tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/runtime/task/harness.rs
tokio/src/runtime/task/join.rs
tokio/src/runtime/task/raw.rs
tokio/src/runtime/task/state.rs
tokio/tests/task_abort.rs

chore: merge 1.8.1

---

.github/workflows/ci.yml

This updates the nightly rustc used in CI.

Update nightly version in CI

---

tokio/Cargo.toml

The previous commit forgot to update the version in Cargo.toml

chore: release 1.5.2

---

tokio/CHANGELOG.md
tokio/Cargo.toml

This PR will have to be merged by hand to maintain history.

chore: merge 1.8.x into master

---

tokio-util/src/udp/frame.rs

codec: remove unnecessary doc(cfg(...))

---

tests-build/tests/fail/macros_core_no_default.stderr

The new Rust release changed an error message.

Fix CI on master

---

tokio/src/sync/watch.rs

Document when watch::send fails

---

tokio/src/sync/mpsc/block.rs

Use spin_loop_hint instead of yield_now in mpsc

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/runtime/task/mod.rs
tokio/src/runtime/tests/task.rs

Fixes: #4062
The new test catches the leak when I run it with miri.

Fix leak in UnownedTask

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/runtime/task/mod.rs
tokio/src/runtime/tests/task.rs

This merges the fix in #4063 to master.

Merge 1.10.1

---

tokio/src/sync/watch.rs

Make SendError field public

---

tokio-util/README.md

Update `README.md` so it matches crate description and documentation.

util: update README

---

.github/workflows/ci.yml
.github/workflows/stress-test.yml

This adds caching to the CI, which drastically speeds it up.

ci: Add caching to the CI

---

tokio/src/sync/mpsc/bounded.rs

sync: PollSender impls Sink

---

.github/workflows/ci.yml
CONTRIBUTING.md

Signed-off-by: hi-rustin <rustin.liu@gmail.com>
Ignore the target folder when formatting, it always gets false positives.
<details>
```log
➜  tokio git:(master) rustfmt --check --edition 2018 $(find . -name '*.rs' -print)   
Diff in /Users/rustin/ClionProjects/tokio/target/debug/build/proc-macro-nested-bbbacb4578d95e8a/out/count.rs at line 1:
#[doc(hidden)]
#[macro_export]
macro_rules! count {
-    () => { proc_macro_call_0!() };
-    (!) => { proc_macro_call_1!() };
-    (!!) => { proc_macro_call_2!() };
-    (!!!) => { proc_macro_call_3!() };
-    (!!!!) => { proc_macro_call_4!() };
-    (!!!!!) => { proc_macro_call_5!() };
-    (!!!!!!) => { proc_macro_call_6!() };
-    (!!!!!!!) => { proc_macro_call_7!() };
-    (!!!!!!!!) => { proc_macro_call_8!() };
-    (!!!!!!!!!) => { …
```

fmt: Ignore the target dir when formatting

---

tokio/src/time/interval.rs

Document `Interval::tick` cancel safety

---

tokio/src/sync/notify.rs

sync: fix Notify example

---

.github/workflows/ci.yml
benches/fs.rs
examples/tinydb.rs
tokio-stream/src/stream_ext/collect.rs
tokio/src/io/async_fd.rs
tokio/src/io/util/buf_reader.rs
tokio/src/io/util/read_exact.rs
tokio/src/task/task_local.rs
tokio/src/task/yield_now.rs
tokio/src/time/driver/wheel/level.rs

This fixes newly added rustc and clippy warnings.

chore: fix newly added warnings

---

tokio/src/time/driver/entry.rs

time: add doc links in entry doc

---

tokio/src/time/interval.rs

There's a typo in Tokio-time interval document
fix it

fix typo in tokio-time document

---

tokio-stream/src/stream_ext.rs
tokio-stream/src/stream_ext/then.rs

This is a combinator that we really should have.

stream: add `StreamExt::then`

---

.circleci/config.yml

Run tests on ARM hardware using CircleCI.

chore: setup ARM CI with CircleCI

---

LICENSE
tokio-macros/LICENSE
tokio-stream/LICENSE
tokio-test/LICENSE
tokio-util/LICENSE
tokio/LICENSE

New year, new PR updating the copyright notice in LICENSE files.

chore: update year in LICENSE files

---

tokio/src/io/util/take.rs

This fixes a bug in #4428.
Closes: #4435

io: fix take pointer check

---

examples/Cargo.toml

The poll request [#4521](https://github.com/tokio-rs/tokio/runs/5273189299?check_suite_focus=true) CI `cargo test --workspace --all-features` failed,
remove `examples/Cargo.toml`  path dependencies

remove `example`'s `Cargo.toml` dependencies path,make example works.

---

tokio/src/sync/broadcast.rs

chore: add panic documentation for `tokio::sync::broadcast::channel`

---

tokio-util/src/sync/reusable_box.rs

The safety comment is unclear.

util: improve `impl Send for ReusableBoxFuture` docs

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md

Merge the changelog changes in #4666 into master.

Merge 1.18.2

---

tokio/tests/rt_common.rs

Fix flaky test introduced by #4696.

rt: fix flaky `wake_while_rt_is_dropping` test

---

README.md
tokio/README.md

We should add a new LTS release.

Add 1.18 as LTS release

---

tokio/CHANGELOG.md

chore: fix changelog typo

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md

Merge the history in #4830 back into the master branch.
This branch must be merged manually from the command-line to preserve the history in the right way.

Merge 1.20.0

---

tokio/src/task/mod.rs

I had to re-read the edited sentence several times before I understood it. I have proposed a new, potentially clearer, wording that has the same semantics.

Slight re-wording of unconstrained's module docs

---

README.md
tokio/README.md

Half a year is pretty short. This PR increases the LTS release duration to one year.

Increase LTS duration

---

tokio/src/lib.rs
tokio/src/macros/cfg.rs
tokio/src/runtime/tests/loom_join_set.rs
tokio/src/task/mod.rs
tokio/tests/async_send_sync.rs
tokio/tests/task_join_set.rs

There are some documentation and test related things that were not updated when stabilizing `JoinSet`. This PR fixes those.

task: fix some doc and test things related to stabilizing `JoinSet`

---

tokio/src/runtime/driver.rs
tokio/src/runtime/time/mod.rs

A step towards the goal of consolidating thread-local variables, this patch removes the `time::Handle` reference from the time driver struct. The reference is moved a level up and passed into methods that need it.
The end goal is to have a single `Driver` struct that holds each sub-driver and a single `Handle` ref-counted struct that holds all the misc handles. Further work on the time driver is blocked by some other refactoring that will happen in follow-up patches.

rt: remove `Handle` reference from time driver

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/task/local.rs
tokio/tests/task_local_set.rs

Merges changes from #5003 into the master branch.
This PR should be merged from the command-line rather than via the github UI.

Merge 1.21.x

---

.github/workflows/ci.yml
.github/workflows/stress-test.yml

ci: use latest Valgrind

---

.circleci/config.yml
.cirrus.yml
.github/workflows/ci.yml
.github/workflows/loom.yml
.github/workflows/stress-test.yml
examples/Cargo.toml
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/src/loom/std/parking_lot.rs
tokio/src/process/unix/mod.rs
tokio/src/runtime/task/mod.rs
tokio/src/signal/registry.rs
tokio/src/util/mod.rs
tokio/src/util/once_cell.rs

Merge #5055 into branch tokio-1.21.x, which is the latest point release of Tokio.
This PR must be merged from the command-line!

Merge 1.20.3

---

tokio/src/future/block_on.rs

chore: fix typo in expect message

---

.github/workflows/ci.yml
target-specs/i686-unknown-linux-gnu.json
tokio/src/macros/cfg.rs

Closes #5187
See https://github.com/tokio-rs/tokio/issues/5187#issuecomment-1323004269 and https://github.com/tokio-rs/tokio/issues/5187#issuecomment-1323280893.

Add tokio_no_atomic_u64 cfg

---

tokio/src/runtime/task/mod.rs

task: fix the incomplete/wrong description of JOIN_WAKER bit.

---

tokio/tests/async_send_sync.rs

Signed-off-by: Loong <loong.dai@intel.com>

tests: fix a typo

---

.github/workflows/ci.yml
README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/net/windows/named_pipe.rs

This PR merges outstanding changes from 1.18.x into 1.20.x

chore: merge changes from 1.18.x

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/net/windows/named_pipe.rs

This PR will need to be merged via the CLI to maintain history.

chore: merge changes from 1.23.x into master

---

tokio/CHANGELOG.md
tokio/src/io/split.rs

Depends on #5379.
I'm submitting the PR a bit early to hopefully to get a head start with CI.

chore: merge tokio-1.20.x changes

---

LICENSE
tokio-macros/LICENSE
tokio-stream/LICENSE
tokio-test/LICENSE
tokio-util/LICENSE
tokio/LICENSE

Closes: #5401
Update the year in the LICENSE files to reflect the current year.

Update copyright year to reflect the current year

---

tokio-util/src/sync/cancellation_token.rs

sync: make CancellationToken UnwindSafe

---

tokio-util/Cargo.toml

chore: fix dependency on Tokio

---

tokio-stream/CHANGELOG.md

stream: fix changelog date

---

tokio-stream/Cargo.toml

stream: fix minimum Tokio dependency

---

tokio/src/sync/broadcast.rs

sync: add broadcast::Receiver::blocking_recv method

---

tokio/src/runtime/scheduler/current_thread.rs

There should be no functional changes.

rt: small current_thread scheduler cleanup

---

.cargo/config
.gitignore

It was most likely included by accident.

chore: rm .cargo/config and include in .gitignore

---

.github/workflows/ci.yml
tokio/src/macros/loom.rs
tokio/src/task/builder.rs
tokio/src/time/interval.rs

ci: update nightly version

---

tokio/CHANGELOG.md
tokio/Cargo.toml

Fifth PR in a sequence related to https://github.com/tokio-rs/mio/pull/1673.
Depends on #5731, #5732.

Merge 1.20.5 into 1.25.x

---

tokio/src/sync/oneshot.rs

style: remove unnecessary mod prefix

style: remove unnecessary mod prefix

---

tokio/src/task/spawn.rs

This guarantee is widely relied upon for correctness, but is not explicitly mentioned in the documentation.
No code changes.

Add guarantee about when a spawned task may be polled

---

.github/workflows/ci.yml

ci: disable tuning tests for cross tests

---

tokio-util/src/io/sink_writer.rs

util: fix broken intra-doc link

---

tokio/src/macros/cfg.rs
tokio/src/process/mod.rs

process: fix raw_arg not showing up in docs

---

tokio/src/sync/mpsc/bounded.rs

Fix clippy warning in docs

---

tokio/src/loom/std/mod.rs

A change to parking lot or miri resulted in CI breaking.

ci: fix MIRI tests

---

tokio/Cargo.toml

It's been quite a few releases at this point.

Remove stats feature

---

tokio-test/Cargo.toml

Fix tokio-test category slugs

---

tokio/src/runtime/metrics/runtime.rs

Reading the docs, I found a copy-paste error in `worker_overflow_count`
Change the wrong word

docs: fix worker_overflow_count

---

tokio/Cargo.toml
tokio/src/io/util/read_until.rs
tokio/src/util/memchr.rs
tokio/src/util/mod.rs

backport io: use memchr from libc

---

tokio/src/time/sleep.rs

This comment is in the wrong place.

time: reorder comment in sleep.rs

---

tokio/src/io/util/take.rs

io: fix integer overflow in `take`

---

tokio/src/sync/broadcast.rs

doc: fix broadcast::channel link

---

tokio/src/runtime/tests/task_combinations.rs
tokio/src/sync/tests/atomic_waker.rs
tokio/tests/io_panic.rs
tokio/tests/join_handle_panic.rs
tokio/tests/net_panic.rs
tokio/tests/rt_handle.rs
tokio/tests/rt_panic.rs
tokio/tests/sync_panic.rs
tokio/tests/task_blocking.rs
tokio/tests/task_panic.rs
tokio/tests/time_panic.rs
tokio/tests/time_pause.rs

#[cfg(panic = "unwind")]

---

tokio-util/src/io/stream_reader.rs
tokio/src/io/interest.rs
tokio/src/runtime/scheduler/multi_thread/queue.rs
tokio/src/runtime/scheduler/multi_thread/worker.rs
tokio/src/runtime/scheduler/multi_thread_alt/queue.rs
tokio/src/runtime/scheduler/multi_thread_alt/worker.rs
tokio/tests/time_interval.rs

I ran [`typos`](https://github.com/crate-ci/typos) on this repo and found some typos/spelling mistakes.
I corrected said spelling mistakes/typos.

Fixed typos

---

tokio-stream/src/stream_ext.rs

Fix typo in peekable docs

---

tokio/tests/rt_metrics.rs

metrics: fix hang in `worker_overflow_count` test

---

tokio/src/doc/mod.rs

chore: fix docsrs without net feature

---

tokio/src/future/maybe_done.rs

Noticed that `maybe_done.rs` file has some unnecessary `unsafe`, and decided to remove them.
Used `pin_project!` macro to remove `unsafe` uses.

chore: remove uses of unsafe from maybe_done.rs

---

tokio/src/sync/broadcast.rs

docs: fix typo in `tokio/src/sync/broadcast.rs`

---

.cirrus.yml

Update FreeBSD CI environment to 13.2

---

tokio/src/macros/cfg.rs
tokio/src/net/tcp/socket.rs

Mark *Fd traits on TcpSocket as unix-only

---

tokio/src/io/util/chain.rs

Just a plain simplification of the emptiness check.

util: simplify check for empty slice in chain

---

tokio/tests/rt_metrics.rs

We had a CI failure from this test.
```text
Finished test [unoptimized + debuginfo] target(s) in 2m 12s
info: for the target platform, using target runner `qemu-aarch64` defined by environment variable `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER`
Starting 1227 tests across 140 binaries (21 skipped)
[...]
SLOW [>21120.000s] tokio::rt_metrics worker_steal_count
SLOW [>21180.000s] tokio::rt_metrics worker_steal_count
SLOW [>21240.000s] tokio::rt_metrics worker_steal_count
SLOW [>21300.000s] tokio::rt_metrics worker_steal_count
Error: The operation was canceled.
```

metrics: fix worker_steal_count test hanging

---

spellcheck.dic
tokio/src/task/mod.rs

https://docs.rs/tokio/1.36.0/tokio/task/

task: fix documentation links

---

tokio-stream/src/wrappers/signal_unix.rs

Probably a copy-paste leftover

Small typo fix in `tokio-stream`

---

tokio/src/macros/select.rs

macros: render more comprehensible documentation for `select!`

---

examples/tinyhttp.rs
tokio-stream/src/stream_map.rs
tokio-stream/tests/async_send_sync.rs
tokio-stream/tests/stream_timeout.rs
tokio-util/src/sync/cancellation_token/tree_node.rs
tokio-util/src/task/spawn_pinned.rs
tokio/src/fs/open_options.rs
tokio/src/runtime/io/scheduled_io.rs
tokio/src/sync/tests/atomic_waker.rs
tokio/tests/async_send_sync.rs
tokio/tests/sync_broadcast.rs
tokio/tests/sync_mpsc.rs
tokio/tests/sync_notify.rs
tokio/tests/sync_once_cell.rs
tokio/tests/sync_oneshot.rs

Clippy has opinions on master branch
here are the fixes

Fix minor clippy lints

---

spellcheck.dic
tokio/src/fs/mod.rs

[Rendered](https://deploy-preview-6467--tokio-rs.netlify.app/tokio/fs/index.html)

fs: rewrite file system docs

---

tokio/src/net/mod.rs

[Rendered](https://deploy-preview-6482--tokio-rs.netlify.app/tokio/net/index.html)

Add missing types to net module docs

---

tokio/tests/rt_metrics.rs

metrics: fix flaky injection_queue_depth test

---

.github/workflows/ci.yml

Set RUSTUP_WINDOWS_PATH_ADD_BIN=1

---

tokio/src/macros/join.rs
tokio/src/macros/try_join.rs

Typo fix in join.rs and try_join.rs

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/runtime/time/mod.rs

chore: release Tokio v1.38.1

---

tokio/src/runtime/blocking/pool.rs

Adds cfg for loom specific code to avoid unnecessary execution.

runtime: add cfg for loom specific code

---

tokio/tests/rt_threaded_alt.rs

tests: ignore many_oneshot_futures test for alt scheduler

---

README.md
tokio/CHANGELOG.md
tokio/Cargo.toml
tokio/README.md
tokio/src/net/unix/listener.rs
tokio/src/net/unix/stream.rs
tokio/tests/uds_stream.rs

Merge tokio-1.39.x into master.
Once this PR is approved, merge this in cli.
Ref: https://github.com/tokio-rs/tokio/pull/6782

Merge 1.39.x into master

---

tokio-stream/src/stream_ext/peekable.rs
tokio/src/net/tcp/socket.rs

Fix: comment error

---

CONTRIBUTING.md

This command follows the miri command in ci, and will run miri on ``tests/``.

Update miri test command in CONTRIBUTING.md

---

tokio/src/time/instant.rs

Fix typo in `time::Instant` docs

---

deny.toml

ci: allow Unicode-3.0 license for unicode-ident

---

README.md
tokio/README.md
tokio/src/lib.rs
tokio/src/runtime/mod.rs

Minor simplification in lib.rs doc string

---

tokio/tests/process_kill_after_wait.rs

Forgot to submit as part of #7160.
CC @maminrayej

Test for Child::kill after wait

---

tokio/tests/coop_budget.rs

This pull request contains changes to improve clarity, correctness and structure.

Adjust grammar in tokio/tests/coop_budget.rs

---

README.md
tokio/README.md

In practice we make around one release per month these days. Adjust the readme to match that.

readme: adjust release schedule to once per month

---

tokio/src/runtime/metrics/histogram/h2_histogram.rs

Solve code comment inconsistency problem in #7270.
Fix comments to be consistent with code.
Closes https://github.com/tokio-rs/tokio/issues/7270.

Fix Code Comment Inconsistency

---

tokio/src/runtime/builder.rs

runtime: document the queue behavior of spawn_blocking

---

tokio/src/net/tcp/listener.rs
tokio/src/net/tcp/socket.rs
tokio/src/net/tcp/stream.rs
tokio/src/net/udp.rs
tokio/src/net/unix/datagram/socket.rs
tokio/src/net/unix/stream.rs
tokio/src/process/mod.rs
tokio/src/runtime/runtime.rs

These tests don't actually get run. The `if` needs be inside the main function.
See more at: https://github.com/rust-lang/rust/issues/140162

ci: fix cfg!(miri) declarations in tests

---

tokio/src/runtime/time/entry.rs
tokio/src/runtime/time/mod.rs
tokio/src/runtime/time/wheel/mod.rs

This PR fixes some minor style issues that were find while reading the source.

time: address style issues

---

benches/Cargo.toml
benches/fs.rs
benches/signal.rs

See https://github.com/tokio-rs/tokio/pull/7392#discussion_r2152117405.

Revert "benches: properly gate unix benches"

---

tokio-util/tests/task_join_map.rs
tokio/src/process/mod.rs

fix some minor issues in the comments

chore: fix some minor issues in the comments

---

tokio/src/task/blocking.rs

blocking: clarify that spawn_blocking is aborted if not yet started

---

tokio/src/runtime/scheduler/multi_thread/worker.rs

Fix #7521 
ix typo in comment for MAX_LIFO_POLLS_PER_TICK

doc: fix typo in comment for MAX_LIFO_POLLS_PER_TICK

---

.github/workflows/ci.yml

See <https://github.com/tokio-rs/tokio/pull/7574#issuecomment-3253967849>.

ci: remove the job `test-pass`

---

.github/workflows/ci.yml
.github/workflows/uring-kernel-version-test.yml
Cargo.toml
tokio/Cargo.toml
tokio/src/fs/mod.rs
tokio/src/fs/open_options.rs
tokio/src/io/mod.rs
tokio/src/macros/cfg.rs
tokio/src/runtime/builder.rs
tokio/src/runtime/driver.rs
tokio/src/runtime/io/driver.rs
tokio/src/runtime/io/mod.rs
tokio/tests/fs_try_exists.rs
tokio/tests/fs_uring.rs

Derived from #7547, with a few updates.

fs: use feature for io-uring instead of cfg

---

spellcheck.dic
tokio/src/runtime/mod.rs

runtime: add guide for choosing between runtime types
