- tokio-stream/src/stream_map.rs
Document bug: modify HashMap to StreamMap
> Modify HashMap to StreamMap in example.

- tokio-macros/src/entry.rs
Up until now there were a few places on the code where
both the macros tokio::test and tokio::main were unwrapping.
This patch changes .unwrap() for .expect(), to be compatible with
clippy::unwrap_used
Ref: #3887
> tokio-macros: compat with clippy::unwrap_used

- tokio-macros/src/lib.rs
- tokio-stream/src/lib.rs
- tokio-test/src/lib.rs
- tokio-util/src/lib.rs
- tokio/src/fs/read.rs
- tokio/src/fs/read_dir.rs
- tokio/src/fs/read_to_string.rs
- tokio/src/fs/write.rs
- tokio/src/lib.rs
Add a note on some functoins/methods that belong to `fs`
to let the user  note that they are blocking, and
handled by spawn_blocking.
Ref: #2700
> fs: document performance considerations

- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/raw.rs
- tokio/src/runtime/task/state.rs
- tokio/tests/macros_select.rs
- tokio/tests/task_abort.rs
> Remotely abort tasks on JoinHandle::abort

- benches/spawn.rs
This updates some spawning benchmarks. I'm not sure if these benchmarks are the greatest, but unclear to me how to best benchmark spawning. Could hopefully help benchmark #3909.
Refs:  #3904
> bench: update spawn benchmarks

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- macros: don't trigger `clippy::unwrap_used` ([#3926])
[#3926]: https://github.com/tokio-rs/tokio/pull/3926
> Prepare tokio-macros 1.3.0

- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/stream.rs
- tokio/src/net/windows/named_pipe.rs
https://github.com/tokio-rs/tokio/issues/3873
Exposes two APIs from the underlying `registration`
- <del>`poll_read_io`</del>, `try_read_io`
- <del>`poll_write_io`</del>, `try_write_io`
> net: allow customized I/O operations for TcpStream (#3873)

- tokio/Cargo.toml
- tokio/tests/io_async_fd.rs
In this version, io::Error implements From<nix::Error>
To simplify existing test code.
Update Nix and adapt the tests.
> Update Nix to 0.22.0

- tokio/src/runtime/queue.rs
- tokio/src/runtime/task/inject.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/tests/loom_queue.rs
- tokio/src/runtime/tests/queue.rs
- tokio/src/runtime/thread_pool/worker.rs
This PR moves the inject queue into the `tokio::runtime::task` module. This is an incremental change towards the goal of isolating the unsafety in the task module and providing a safe API to `tokio::runtime::task`.
The main two changes in this PR are:
1. Move the inject queue from `src/runtime/queue.rs` to `src/runtime/task/inject.rs`.
2. Change `Inject::push_batch` to an iterator-based interface.
The work-stealing local run queue will continue to have unsafe code despite being outside the task module, but its unsafety is going to be unrelated to the invariants of the `tokio::task` module.
It may be easier to read this change one commit at the time. The first commit performs no changes to the code besides moving it around and running rustfmt.
> Move inject queue to `tokio::runtime::task`

- tokio/src/sync/once_cell.rs
This cleans up the `OnceCell` a bit.
> Clean up OnceCell

- tokio/tests/uds_datagram.rs
io::ErrorKind just replaced most uses of "Other" with "Uncategorized"
and prohibits users from matching on "Uncategorized".  So match on the
errno instead.
https://github.com/rust-lang/rust/pull/85746
Fix tests on the latest nightly stdlib
Don't match io::Error::Errorkind to Other or Uncategorized.
> Fix the uds_datagram tests with the latest nightly stdlib

- tokio/src/runtime/task/mod.rs
- tokio/src/task/local.rs
Replace the `LinkedList` in `LocalSet` with `OwnedTasks`. This introduces an unnecessary mutex, but is part of the transition to a safe task API. The mutex will be removed again in the follow-up PR that handles the Send safety part of the safe task API.
> Use OwnedTasks in LocalSet

- tokio/src/task/task_local.rs
- tokio/tests/async_send_sync.rs
This updates the `async_send_sync.rs` test.
> chore: update async_send_sync test

- tokio/src/runtime/task/error.rs
- tokio/src/util/mod.rs
- tokio/src/util/sync_wrapper.rs
- tokio/tests/async_send_sync.rs
This PR removes a mutex from the `JoinError` type. The mutex was originally added in #1888 to make the `JoinError` type `Sync`, but we can achieve the same with the technique outlined in [`sync_wrapper`](https://crates.io/crates/sync_wrapper).
> Remove mutex in JoinError

- tokio/src/sync/mutex.rs
There are various situations where it is useful to be able to recover `&Mutex` from a `MutexGuard`.  One of them is condition variables (see #3892 and my new [async-condvar-fair](https://crates.io/crates/async-condvar-fair) crate) but there are other possibilities.
Broadly, for the applicable guard types, and where possible:
```
impl Guard<'l, T> {
pub fn mutex(this: &Self) -> &'l Mutex<T> { self.lock }
}
```
(Mutatis mutandis for the various mutex types - varies eg for `Owned` and `RwLock`.)
In #3741 a method was proposed to *convert* the guard into the mutex reference.  Obtaining a borrow is strictly more general, and is what is implemented in `parking_lot` and `smol` for their mutex types.
* Are these the best names?  `parking_lot` uses `fn mutex()` for its mutex type but does not …
> Mutex guard lock ref recovery methods

- tokio/src/io/poll_evented.rs
clear_read_ready andn clear_write_ready do not exist for
io::driver::Registration. Instead, the doc should refer to
`clear_readiness`.
Ref: #3746
> io: fix docs referring to clear_{read,write}_ready

- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/harness.rs
In #3955, I changed it such that tasks are always bound to a scheduler. This PR removes the `Option` around the scheduler.
> Make scheduler non-optional

- tokio/src/runtime/tests/loom_local.rs
- tokio/src/runtime/tests/mod.rs
- tokio/src/task/local.rs
If a task is woken during shutdown, it is possible for it to remain in the shared queue after shutting down the `LocalSet`, which would be a leak due to a ref-count cycle. This PR provides a fix. The `Enable loom test` commit was pushed first without the fix to show that the test really fails.
> Fix leak in LocalSet

- README.md
- tokio/README.md
This PR contains describes the release schedule and proposes a new policy for backporting bugfixes.
> Add release schedule and bugfix policy

- tokio/src/process/mod.rs
- tokio/tests/process_arg0.rs
Currently, there is no way to set the `arg0` parameter in the `Command` struct.
Therefore, the `arg0` method of the `Process` struct is exposed by `Command`.
> process: add arg0 method to Command

- tokio/src/task/blocking.rs
The documentation of `spawn_blocking` does not say what happens when the upper thread limit is reached. This PR adds a line that says that tasks are put in a queue.
> task: elaborate on queue behavior of spawn_blocking

- tokio/src/loom/std/atomic_u64.rs
- tokio/src/macros/cfg.rs
- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/list.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/state.rs
- tokio/src/runtime/tests/mod.rs
- tokio/src/runtime/tests/task.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/src/task/local.rs
This change makes `OwnedTasks::remove` safe and guarantees that non-Send tasks are not polled on the wrong thread.
> Add owner id for tasks in OwnedTasks

- tokio/src/fs/read_dir.rs
- tokio/src/io/util/async_buf_read_ext.rs
- tokio/src/io/util/lines.rs
This PR documents cancellation safety of the methods on `AsyncBufReadExt` and related methods on various structs.
> io: document cancellation safety of AsyncBufReadExt

- tokio/src/process/mod.rs
- tokio/src/process/windows.rs
- tokio/tests/process_raw_handle.rs
Implementation of #3987. /ping @ipetkov 
Notes from discussion in issue:
- The process id returned by `Child.id()` is not the Windows handle.
- It _is_ possible to obtain a Handle from a PID, but it is without many access privileges that the handle obtained by spawning the child process has.
- Windows process handles do not suffer from the PID problem where a stale PID can be recycled:
> When a new process is created by the `CreateProcess` function, handles of the new process and its primary thread are returned. These handles are created with full access rights, and — subject to security access checking — can be used in any of the functions that accept thread or process handles. These handles can be inherited by child processes, depending on the inheritance flag specified when they are …
> process: implement `raw_handle` getter on Child (#3987)

- tokio/src/io/util/async_buf_read_ext.rs
- tokio/src/io/util/fill_buf.rs
- tokio/src/io/util/mod.rs
- tokio/tests/async_send_sync.rs
- tokio/tests/io_buf_reader.rs
This PR adds `fill_buf` and `consume` to `AsyncBufReadExt`.
> io: add fill_buf and consume

- tokio/src/io/util/copy.rs
- tokio/tests/io_copy.rs
The current copy works poorly in some cases.
when reader output depends on writer and writer is buffered, a deadlock may occur.
see https://github.com/tokio-rs/tls/issues/66
we can call flush when the reader is not progressing to prevent such deadlocks.
> Fix copy buffered write

- tokio/src/runtime/tests/loom_pool.rs
This PR attempts to reduce the number of atomic operations in the expensive loom tests, hopefully decreasing their running time.
> tests: simplify loom tests

- .github/workflows/ci.yml
- tokio-stream/Cargo.toml
- tokio-stream/src/wrappers.rs
- tokio/src/signal/unix.rs
- tokio/src/signal/windows.rs
- tokio/src/signal/windows/os_impl.rs
- tokio/src/signal/windows/stub.rs
- tokio/src/signal/windows/sys.rs
This PR moves most of the windows implementation for signal into a new `tokio/src/signal/windows/os_impl.rs` file, leaving the `tokio/src/signal/windows.rs` file with only definitions of the public types. This makes the documentation show up when building on unix.
> Make windows docs for signal module show up on unix builds

- tokio-stream/src/wrappers.rs
- tokio/src/macros/cfg.rs
I merged #3213 and CI on master broke. This PR fixes that by not generating the module when generating documentation if Tokio is not the crate being documented.
> Fix doc failure in CI on master

- tokio-util/src/udp/frame.rs
- tokio-util/tests/sync_cancellation_token.rs
- tokio/src/io/split.rs
- tokio/src/process/unix/orphan.rs
- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/signal/registry.rs
- tokio/src/sync/batch_semaphore.rs
- tokio/src/sync/notify.rs
- tokio/src/sync/semaphore.rs
- tokio/src/task/local.rs
- tokio/src/task/task_local.rs
- tokio/tests/io_split.rs
- tokio/tests/io_write_all_buf.rs
- tokio/tests/sync_mutex.rs
- tokio/tests/sync_mutex_owned.rs
To improve the code quality, the clippy warnings were fixed.
Fix the clippy warnings. Also, prevent futures warnings to be merged by add the option `-D warnings` to the build job.
Fixes #3585.
> Fix clippy warnings

- tokio/src/io/util/async_read_ext.rs
- tokio/src/io/util/async_write_ext.rs
- tokio/src/io/util/read_int.rs
- tokio/src/io/util/write_int.rs
- tokio/tests/async_send_sync.rs
The methods (read|write)_f(32|64)[_le] to Async(Read|Write)Ext.
Now, it is possible to read and write floating types from an Async(Read|Write) type.
Add (read|write)_f(32|64)[_le] methods.
Fixes #3435.
> io: Add (read|write)_f(32|64)[_le] methods

- tokio/tests/async_send_sync.rs
I forgot in the last PR #4022 to add the test for `write_f(32|64)[_le]`. 
Sorry.
> Add test for write_f(32|64)[_le]

- tokio/Cargo.toml
Fixes #4035
The build will fail for a crate that uses tokio with the test-util feature but not the rt, sync, and time features.
Add the features dependencies to Cargo.toml
This bug was revealed by running `cargo hack check --feature-powerset --no-dev-deps`.  However, that command takes 205 minutes with this patch, and even longer without it, so it can't be added to CI.
> The test-util feature depends on rt, sync, and time

- tokio/src/task/spawn.rs
> task: quickly send task to heap on debug mode

- tokio/tests/task_local_set.rs
This test has failed a few times because only some of the tasks had completed. This is simply due to bad timing.
> Fix flaky test

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- io: add `(read|write)_f(32|64)[_le]` methods ([#4022])
- io: add `fill_buf` and `consume` to `AsyncBufReadExt` ([#3991])
- process: add `Child::raw_handle()` on windows ([#3998])
- doc: fix non-doc builds with `--cfg docsrs` ([#4020])
- io: flush eagerly in `io::copy` ([#4001])
- runtime: a debug assert was sometimes triggered during shutdown ([#4005])
- sync: use `spin_loop_hint` instead of `yield_now` in mpsc ([#4037])
- tokio: the test-util feature depends on rt, sync, and time ([#4036])
- runtime: reorganize parts of the runtime ([#3979], [#4005])
- signal: make windows docs for signal module show up on unix builds ([#3770])
- task: quickly send task to heap on debug mode ([#4009])
- io: document cancellation safety of `AsyncBufReadExt` ([#3997])
- sync: document when `watch::send` …
> Prepare Tokio v1.10.0

- tokio/src/time/driver/sleep.rs
This PR makes the examples on the `Sleep` type easier to find when you are viewing the documentation for the `sleep` function.
> time: make Sleep examples easier to find

- tokio/src/runtime/handle.rs
- tokio/src/util/trace.rs
Currently, the per-task spans generated by Tokio's `tracing` feature
have the span name "task" and the target "tokio::task". This is because
the console subscriber identified tasks by looking specifically for the
"tokio::task" target.
In tokio-rs/console#41, it was proposed that the console change to a
more generic system for identifying the spans that correspond to tasks,
to allow recording tasks belonging to multiple runtime crates (e.g. an
application that uses Tokio for async tasks and Rayon for CPU-bound
tasks). PR tokio-rs/console#68 changed the console to track any spans
"runtime.spawn", regardless of target (so that the target can be used to
identify the runtime a task came from), with "tokio::task/task" tracked
for backwards-compatibility with the current release version of …
> tracing: change span naming to new console convention

- tokio/src/time/driver/mod.rs
> Don't panic when Instant is not monotonic

- tokio/src/process/mod.rs
- tokio/src/process/unix/mod.rs
- tokio/src/process/windows.rs
This is potentially useful if you use another crate to set up the pipes between the children, but that other crate only provides blocking endpoints to their pipes.
Closes: #2837
> process: add from_std to ChildStd*

- tokio-stream/src/stream_map.rs
This allows to collect iterator into a `StreamMap` and to extend `StreamMap` with another one
Closes #3982.
> stream: Impl {From, Into}Iterator, Extend for StreamMap

- .github/workflows/ci.yml
As noted in https://github.com/tokio-rs/tokio/issues/4062#issuecomment-904822057, our valgrind tests don't actually cause a CI failure. 
This PR should fail CI until  #4065 is merged.
> ci: fail if valgrind complains

- tokio/tests/process_kill_on_drop.rs
The process_kill_on_drop test would fail on systems that did not have bash installed.
Skip that test if the error code indicates that bash cannot be found.
> Skip the process_kill_on_drop test if bash is not installed.

- tokio-stream/src/wrappers/broadcast.rs
- tokio-stream/src/wrappers/mpsc_bounded.rs
- tokio-stream/src/wrappers/mpsc_unbounded.rs
- tokio-stream/src/wrappers/watch.rs
Receiver streams can be better created via `From` trait.
Add `From<Receiver<T>>` implementation for streams that take a `Receiver`.
Note: Should other streams implement the `From` trait as well?
Resolves #4015
> Add From<Receiver<T>> impl for receiver streams

- tokio-util/src/time/delay_queue.rs
It's useful to be able to extract the `Key` assigned to a given entry in a `DelayQueue` when being handed back an expired item, so that callers can interact with the delay queue in a correct fashion.
We've exposed the `Key` used in `Expired<T>` such that it can be not only accessed from `Expired<T>`, but is now also `Copy`, `Eq`, and `Hash`, so it can be easily used in hash maps and sets, as well as trivially copied, since it's just a `usize` under the hood.
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
> tokio-util: expose key used in DelayQueue's Expired

- tokio/src/io/util/fill_buf.rs
- tokio/tests/io_fill_buf.rs
There are some IO resources which hit the panic when calling `poll_fill_buf` twice, e.g. a `BufReader<File>` will do this when you are at EOF.
A safe alternative is to check for empty slices and handle those in a special way, but I prefer this as it is a more robust solution.
Fixes: #4085
> Fix fill_buf by not calling poll_fill_buf twice

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- time: don't panic when Instant is not monotonic ([#4044])
- io: fix panic in `fill_buf` by not calling `poll_fill_buf` twice ([#4084])
- watch: add `watch::Sender::subscribe` ([#3800])
- process: add `from_std` to `ChildStd*` ([#4045])
- stats: initial work on runtime stats ([#4043])
- tracing: change span naming to new console convention ([#4042])
- io: speed-up waking by using uninitialized array ([#4055], [#4071], [#4075])
- time: make Sleep examples easier to find ([#4040])
[#3800]: https://github.com/tokio-rs/tokio/pull/3800
[#4040]: https://github.com/tokio-rs/tokio/pull/4040
[#4042]: https://github.com/tokio-rs/tokio/pull/4042
[#4043]: https://github.com/tokio-rs/tokio/pull/4043
[#4044]: https://github.com/tokio-rs/tokio/pull/4044
[#4045]: …
> chore: prepare Tokio v1.11.0

- tokio/src/time/clock.rs
> time: document paused time details better

- tokio-util/src/io/reader_stream.rs
I try to build a static file server with `axum` + `tower-http`, and decide to improve tower-http's file sending speed with `tokio-util`'s ReaderStream.
But did not find a way to cutomized the buf chunk size.
With `tokio-util`'s default 4096 buf chunk size, the static server can only stable at `50MiB/s`
so I try to increase the buf chunk size to 8K, 32K, 64K and the speed got improved to > `200MiB/s`
but by default, there's no `with_capacity`  method, so I have to use crate patch.
add `with_capacity` 
https://github.com/tokio-rs/tokio/pull/2215
> feat: add with_capacity for ReaderStream

- tokio-util/src/compat.rs
Closes #4068 
This code was copied from https://github.com/smol-rs/async-compat/blob/master/src/lib.rs and is marked as authored by `Stjepan Glavina <stjepang@gmail.com>` and is licensed by MIT or Apache 2.0.
> Added AsyncSeek compat.

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
- sync: add drop guard for `CancellationToken` (#3839)
- compact: added `AsyncSeek` compat (#4078)
- time: expose `Key` used in `DelayQueue`'s `Expired` (#4081)
- io: add `with_capacity` to `ReaderStream` (#4086)
- codec: remove unnecessary `doc(cfg(...))` (#3989)
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
> chore: prepare tokio-util v0.6.8

- tokio-util/src/codec/length_delimited.rs
Hey there!
Unless I'm missing a reason why `LengthDelimitedCodec` can not implement `Clone`, this would come in handy.
This PR adds `Clone` to the derive macro, and all the internal fields already implement `Clone`.
> codec: implement `Clone` for `LengthDelimitedCodec`

- tokio/src/doc/mod.rs
Fixes the following warning:
```
warning: type does not implement `Debug`; consider adding `#[derive(Debug)]` or a manual implementation
--> tokio/src/doc/mod.rs:20:1
|
20 | pub enum NotDefinedHere {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> tokio/src/lib.rs:7:5
|
7  |     missing_debug_implementations,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
> chore: add Debug to NotDefinedHere

- tokio/src/task/yield_now.rs
People are sometimes confused by the behavior of `yield_now()`. Hopefully this should help a bit.
This PR also removes the `cfg_rt!` macro as rustfmt doesn't work inside it. There is another use of `cfg_rt!` around `yield_now` in `tokio/src/task/mod.rs`.
> task: document non-guarantees of yield_now

- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
This adds a tracing span to the future in `block_on`, when the unstable tracing support is enabled. While not technically a spawn, we still call it a "task spawn" with the kind set to `block_on`.
Unfortunately, it cannot collect the `#[tokio::main]` task, since even though it is instrumented, the task is entered before we can call `console_subscriber::init()`. But all manual usage of `block_on` is collected.
Closes https://github.com/tokio-rs/console/issues/106
> runtime: add tracing span for block_on futures

- tokio/src/io/util/async_seek_ext.rs
- tokio/tests/fs_file.rs
Since version 1.55 has the Rust std library implemented a convenience function called [rewind](https://doc.rust-lang.org/std/io/trait.Seek.html#method.rewind) that is part of the io::Seek trait. I have found this to be a very helpful function in making my code more readable/simpler.
Implement the rewind function as part of the AsyncSeekExt trait.
The test might not be in the proper place apologies for that. I didn't know of a better place to put it.
> io: Add convenience method `AsyncSeekExt::rewind`.

- tests-build/tests/fail/macros_type_mismatch.stderr
- tokio-macros/src/entry.rs
- tokio-macros/src/lib.rs
- tokio/tests/task_local_set.rs
Make the "current_thread" flavor run the function body in a LocalSet so
that tokio::task::spawn_local() just works.
It's very helpful when you have hundreds of tests and don't want to
repeat the same LocalSet::new().run_until(...) stanza every time.
<hr>
Aside: I ran the `rustfmt --check --edition 2018 $(find . -name '*.rs' -print)` command suggested in CONTRIBUTING.md but it spits out _a lot_ of suggestions unrelated to my change. That's with `rustfmt 1.4.37-stable (a178d03 2021-07-26)`.
> macros: run current_thread inside LocalSet

- tokio/Cargo.toml
- tokio/src/io/bsd/poll_aio.rs
- tokio/src/io/driver/interest.rs
- tokio/src/io/driver/mod.rs
- tokio/src/io/driver/ready.rs
- tokio/src/io/mod.rs
- tokio/src/io/poll_aio.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/tests/io_poll_aio.rs
Unlike every other kqueue event source, POSIX AIO registers events not
via kevent(2) but by a different mechanism that needs the kqueue's file
descriptor. This commit adds a new PollAio type, designed to be used
by an external crate that implements a POSIX AIO Future for use with
Tokio's reactor.
Fixes: #3197
With Tokio 0.1 and 0.2, PollEvented was sufficiently powerful to allow external crates to implement a POSIX AIO event source. Beginning with Tokio 0.3, PollEvented became private, and it also lost some needed functionality. Thus, there was no possible way for a consumer to use POSIX AIO with Tokio.
The first proposed solution was to reexpose `PollEvented.`  That idea was rejected because Tokio's maintainers thought that `PollEvented` peered too intimately into Tokio's internals, and …
> Allow consumers to implement POSIX AIO sources.

- tokio/src/time/clock.rs
Be more explicit about the behavior of `advance`. See #3985 for info.
> time: more docs on advance

- tokio/Cargo.toml
Better to depend on released crates than git tags
Update dependency to newly released mio-aio
> Update the mio-aio dev-dependency

- tokio/src/sync/mpsc/bounded.rs
- tokio/src/sync/mpsc/chan.rs
- tokio/src/sync/mpsc/error.rs
- tokio/src/sync/mpsc/list.rs
- tokio/src/sync/mpsc/unbounded.rs
- tokio/src/sync/tests/loom_mpsc.rs
- tokio/tests/sync_mpsc.rs
Implement `mpsc::Sender::try_recv` and `mpsc::UnboundedSender::try_recv`.
Closes: #3350
Closes: #3639
> sync: implement try_recv for mpsc channels

- tokio/src/loom/std/mod.rs
- tokio/src/sync/mpsc/block.rs
The mpsc channel has a bunch of calls to `yield_now` that should be `spin_loop_hint`. However they should remain as calls to `yield_now` when testing with loom. This PR expands the `crate::loom` mock to handle this.
Related: #4037
> mpsc: use spin_loop_hint instead of yield_now

- tokio/src/sync/mpsc/bounded.rs
- tokio/tests/sync_mpsc.rs
Fixes #4118.
`try_reserve()` and `try_reserve_owned()` of `tokio::sync::mpsc::Sender` are inconsistent with `try_send()` in the error they return, signalling `Full` instead of `Closed` for a closed channel. If other code relies on this error as documented, it might forever retry sending to a closed channel.
I copied the handling of the `TryAcquireError` from `try_send()` to `try_reserve()` and `try_reserve_owned()`; as far as I can tell, this is probably what it should have been in the first place when `try_reserve()` was introduced by 672be92a03a489d028ed7ec2c6b1abdbf0874a1d, and then `try_reserve_owned()` just copied `try_reserve()` behaviour.
> mpsc: ensure try_reserve error is consistent with try_send

- tokio/src/sync/mpsc/bounded.rs
- tokio/src/sync/mpsc/unbounded.rs
This PR elaborates that `poll_recv` could fail with a spurious failure, but that `try_recv` won't.
> sync: document spurious failures on poll_recv

- .github/labeler.yml
- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/loom.yml
This PR makes the loom tests optional for merging PRs. They can be enabled on specific PRs by adding the `R-loom` label. Loom tests still run on the master branch.
> ci: make loom tests optional

- tokio/src/runtime/task/join.rs
Previous description misleads that `JoinError` can be used as an exhaustive enum in _match_ statements.
Description was improved.
> docs: Improve JoinHandle::abort cancellation checking description

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- mpsc: ensure `try_reserve` error is consistent with `try_send` ([#4119])
- mpsc: use `spin_loop_hint` instead of `yield_now` ([#4115])
- sync: make `SendError` field public ([#4097])
- io: add POSIX AIO on FreeBSD ([#4054])
- io: add convenience method `AsyncSeekExt::rewind` ([#4107])
- runtime: add tracing span for `block_on` futures ([#4094])
- runtime: callback when a worker parks and unparks ([#4070])
- sync: implement `try_recv` for mpsc channels ([#4113])
- macros: run runtime inside `LocalSet` when using macro ([#4027])
- docs: clarify CPU-bound tasks on Tokio ([#4105])
- mpsc: document spurious failures on `poll_recv` ([#4117])
- mpsc: document that `PollSender` impls `Sink` ([#4110])
- task: document non-guarantees of `yield_now` ([#4091])
- time: document paused time details …
> Prepare Tokio v1.12.0

- tokio/src/io/util/copy.rs
Wrong poll_write implementation may lead to thread blocking.
e.g., poll_write returns written length larger than cap. When reader connection alive, thread will stuck in buf_copy.
This is hard to debug, maybe add a `debug_assert!` will help.
> add debug_assert in case pos > cap for copy_bidirectional

- tokio/src/util/trace.rs
This change enables `tokio-console` to parse the location information
for a spawned task into a structured object rather than simply displaying
this info as a field on the task.
> tracing: use structured location fields for spawned tasks

- tokio/src/sync/notify.rs
- tokio/src/sync/tests/mod.rs
- tokio/src/sync/tests/notify.rs
Since a waker can trigger arbitrary code, such as with a custom waker,
and even more so now that it can emit a tracing event that could do
respond, we must be careful about the internal state when that code is
triggered. The clone method of a waker is one of those instances.
This changes the internals of `Notify` so that the waker is cloned
*before* locking the waiter list. While this does mean that in some
contended cases, we'll have made an optimistic clone, it makes `Notify`
more robust and correct.
Note that the included test case is built from an instance that did
happen naturally in another project, see
https://github.com/tokio-rs/console/issues/133.
> sync: fix Notify to clone the waker before locking its waiter list

- tokio/src/sync/mutex.rs
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
part of https://github.com/tokio-rs/tokio/issues/4109
add blocking_lock for mutex
> sync: add blocking_lock for mutex

- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/tests/udp.rs
- tokio/tests/uds_datagram.rs
UDP was missing `poll_read_ready` and `poll_write_ready` methods
UDS datagram was missing them as well
similar to unix and tcp sockets, this brings poll_read_ready and
poll_write_ready methods to udp and UDS Datagram
> net: add poll_{recv,send}_ready methods to udp/uds_datagram

- tokio/src/macros/try_join.rs
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
close https://github.com/tokio-rs/tokio/issues/4127
add returning on the first error example for try_join!
> docs: add returning on the first error example for try_join!

- tokio/src/net/tcp/split.rs
- tokio/src/net/tcp/split_owned.rs
- tokio/src/net/unix/split.rs
- tokio/src/net/unix/split_owned.rs
- tokio/src/net/unix/stream.rs
Currently, Tokio's split halves APIs leave out a lot of fairly useful methods from TcpStream and UnixStream.
This PR adds the try_*, readable, writable, ready, and peer_addr methods to the split halves APIs for TcpStream and UnixStream.
This PR also adds a doc example for the UnixStream-related peer_addr methods.
Closes: #4098
> Add try_*, readable, writable, ready, and peer_addr methods to TCP and Unix split halves

- tokio/src/sync/watch.rs
The `tokio::sync::watch` channel currently requires that each value sent into the channel is completely independent, but this means that the buffers of old values cannot be reused.
Add `send_replace` which allows the sender to retrieve the previous value that was in the channel. The naming is inspired by `mem::replace`.
> Add `watch::Sender::send_replace`

- tokio/src/sync/mutex.rs
This follows precedent of e.g. [the standard library](https://doc.rust-lang.org/1.55.0/src/std/sync/mutex.rs.html#431-454). Adds a level of indirection in order to still be able to coerce the argument to a `&dyn Debug`.
I tried to do an exhaustive search, AFAICT this seems to be the only type in this repo with an `?Sized` type argument that has a too restrictive (<code>\<T: <s>?Sized</s>\></code>) impl for Debug.
> Expand `Debug for Mutex<T>` implementation to unsized `T`

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- macros: run current_thread inside LocalSet ([#4027])
- macros: explicitly relaxed clippy lint for `.expect()` in runtime entry macro ([#4030])
- macros: fix invalid error messages in functions wrapped with `#[main]` or `#[test]` ([#4067])
[#4027]: https://github.com/tokio-rs/tokio/pull/4027
[#4030]: https://github.com/tokio-rs/tokio/pull/4030
[#4067]: https://github.com/tokio-rs/tokio/pull/4067
> Prepare tokio-macros 1.4.0

- tests-build/tests/fail/macros_type_mismatch.stderr
- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio-macros/src/entry.rs
- tokio-macros/src/lib.rs
- tokio/CHANGELOG.md
- tokio/tests/rt_threaded.rs
- tokio/tests/task_local_set.rs
This PR prepares tokio-macros 1.4.1, reverting #4027. The previous version 1.4.0 was yanked due to breaking changes.
Closes: #4138
Closes: #4140
> Macros 1.4.1

- tokio/src/runtime/blocking/shutdown.rs
- tokio/src/runtime/handle.rs
Rust nightly has some new warnings. This PR fixes them.
> chore: fix unused field warnings

- tokio/src/io/util/copy.rs
This updates the buffer sized used by `tokio::io::copy` to match the size in std.
> io: update copy buffer size

- tokio-macros/src/lib.rs
- tokio-macros/src/select.rs
- tokio/Cargo.toml
- tokio/src/lib.rs
- tokio/src/macros/select.rs
- tokio/tests/macros_select.rs
> macros: fix mut patterns in `select!` macro

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/task/builder.rs
- tokio/src/util/error.rs
- tokio/tests/rt_basic.rs
> runtime: drop basic scheduler tasks inside context

- tokio/src/runtime/stats/stats.rs
Add busy duration statistic. Refs: #3845
cc @Matthias247
> stats: add busy_duration stats

- .github/workflows/ci.yml
- tokio/Cargo.toml
We didn't catch that tracing was out-of-date.
> ci: check for minimal versions with tokio_unstable

- tokio/Cargo.toml
- tokio/src/runtime/stats/stats.rs
> stats: only expose `busy_duration_total`

- tokio/src/io/util/async_write_ext.rs
I think `file` is more reasonable name in this case.
> io: rename buffer to file

- tokio/src/sync/oneshot.rs
- tokio/src/sync/tests/loom_oneshot.rs
Issue #4225 describes a potential race condition in the `oneshot`
channel in `tokio-sync`. The race occurs when the oneshot is closed, and
then a thread calls `oneshot::Sender::send` while another thread is
calling `oneshot::Receiver::try_recv` or awaiting the reciever. The call
to `send` puts the sent value in the cell. Then, it sets the
`VALUE_SENT` (completed) bit, returning a snapshot of the state. If the
state is closed, the sender takes the sent value back out of the cell.
Receiving from the channel _also_ loads the state. The reciever first
checks if the channel is completed, and takes the value out of the cell
if the completed bit is set. This is racy, because if a call to `recv`
loads the state after the completed bit has been set, it will no longer
treat the channel as closed, …
> sync: fix racy `UnsafeCell` access on a closed oneshot

- tokio/src/sync/oneshot.rs
Depends on #4226
Currently, the safety invariants and synchronization strategy used in
`tokio::sync::oneshot` are not particularly obvious, especially to a new
reader. It would be nice to better document this code to make these
invariants clearer.
This branch adds `SAFETY:` comments to the `oneshot` channel
implementation. In particular, I've focused on documenting the
invariants around when the inner `UnsafeCell` that stores the value can
be accessed by the sender and receiver sides of the channel.
I still want to take a closer look at when the waker cells can be set,
and I'd like to add more documentation there in a follow-up branch.
> oneshot: document UnsafeCell invariants 

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/sync/oneshot.rs
- tokio/src/sync/tests/loom_oneshot.rs
This backports #4226 and #4229 to `tokio-v1.13.x` and prepares a release for v1.13.1.
This should be rebase merged so that we have separate commits in the history for the backports and release prep.
> chore: prepare Tokio v1.13.1

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/sync/oneshot.rs
- tokio/src/sync/tests/loom_oneshot.rs
> Merge v1.13.1

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- macros: fix compiler errors when using `mut` patterns in `select!`
([#4211])
- sync: fix a data race between `oneshot::Sender::send` and awaiting a
`oneshot::Receiver` when the oneshot has been closed ([#4226])
- sync: make `AtomicWaker` panic safe ([#3689])
- runtime: fix basic scheduler dropping tasks outside a runtime context
([#4213])
- stats: add `RuntimeStats::busy_duration_total` ([#4179], [#4223])
- io: updated `copy` buffer size to match `std::io::copy` ([#4209])
- io: rename buffer to file in doc-test ([#4230])
- sync: fix Notify example ([#4212])
[#4211]: https://github.com/tokio-rs/tokio/pull/4211
[#4226]: https://github.com/tokio-rs/tokio/pull/4226
[#3689]: https://github.com/tokio-rs/tokio/pull/3689
[#4213]: https://github.com/tokio-rs/tokio/pull/4213
[#4179]: …
> chore: prepare Tokio v1.14.0

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio/Cargo.toml
- macros: fix mut patterns in `select!` macro ([#4211])
[#4211]: https://github.com/tokio-rs/tokio/pull/4211
> chore: prepare tokio-macros 1.6.0

- tokio/src/net/tcp/socket.rs
In old versions of Tokio there was a method called `connect_std`, which served some of the purposes that `TcpSocket` now serves.
> net: add connect_std -> TcpSocket doc alias

- tokio-macros/src/entry.rs
- tokio/tests/macros_test.rs
> macros: address remainging clippy::semicolon_if_nothing_returned warning

- .cirrus.yml
- .github/workflows/ci.yml
- tokio-macros/src/lib.rs
- tokio-stream/src/lib.rs
- tokio-test/src/lib.rs
- tokio-util/src/lib.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
The behavior introduced in https://github.com/rust-lang/rust/pull/89596 (auto doc_cfg) is now split to another feature flag (https://github.com/rust-lang/rust/pull/90502).
We can remove some changes done in https://github.com/tokio-rs/tokio/pull/4193.
> ci: upgrade to new nightly

- tokio-macros/Cargo.toml
- tokio-stream/Cargo.toml
- tokio-test/Cargo.toml
- tokio-util/Cargo.toml
- tokio/Cargo.toml
- tokio/tests/rt_handle_block_on.rs
https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field
> If no URL is specified in the manifest file, crates.io will
> automatically link your crate to the corresponding docs.rs page.
> chore: remove doc URL from Cargo.toml

- tokio-stream/src/stream_map.rs
This allows `StreamMap` to be used with [`futures::stream::StreamExt::collect`][collect].
My use case is something like this:
```rust
let stream_map: StreamMap<_, _> = things
.into_iter()
.map(|thing| make_stream(thing)) // iterator of futures
.collect::<FuturesUnordered<_>>() // stream of streams
.collect::<StreamMap<_, _>>() // combine all the inner streams into one
.await;
async fn make_stream(thing: Thing) -> impl Stream { ... }
```
[collect]: https://docs.rs/futures/0.3.17/futures/stream/trait.StreamExt.html#method.collect
Add `Extend` impl that delegates to the inner `Vec`.
> stream: impl Extend for StreamMap

- tokio/src/lib.rs
The current docs only specify that public API features are enabled using full, this is not correct.
Update documentation to be in line with actual features.
> docs: document that parking_lot is enabled by full

- tokio/src/time/interval.rs
- tokio/tests/time_interval.rs
Some networking protocols need heartbeat mechanism and `Interval` makes it very easy to implement it. However if the protocol requires the heartbeat to be send only if the connection is idle, then there is no way to reset the `Interval` when is not.
Add `Interval::reset` method
> time: Add `Interval::reset` method

- tokio/src/io/async_fd.rs
The implicit elided lifetimes of the `AsyncFd` references in return types of methods on `AsyncFdReadyGuard` resolved to that of `&self`, which is needlessly small.
Change the lifetimes of the references. Should not be a breaking change thanks to subtyping.
---
On a parallel note, I would also like to get an opinion on whether this pull request should be made to include a new `into_try_io()` method on `AsyncFdReadyMutGuard`:
```rust
pub fn into_try_io<R>(
self,
f: impl FnOnce(&'a mut Inner) -> io::Result<R>,
) -> Result<io::Result<R>, TryIoError> {
let AsyncFdReadyMutGuard {
async_fd,
mut event,
} = self;
let result = f(async_fd.inner.as_mut().unwrap());
match result {
Err(err) if err.kind() == io::ErrorKind::WouldBlock => {
if let Some(event) = event.take() { …
```
> extend AsyncFdReadyGuard method rettypes lifetimes

- README.md
- tokio/README.md
The MSRV was bumped to 1.46 in #4254 and 1.14.x will be the last release with a MSRV of 1.45. Hence, it seems reasonable to make 1.14.x an LTS release.
> Add 1.14.x to LTS releases

- tokio/src/io/async_fd.rs
Though the description for AsyncFd says, 
> the file descriptor must have the nonblocking mode set to true.
However, it does not set to true in the AsyncFd example. So if developers just copied the example, it would not work expectedly.
Call `tcp.set_nonblocking(true)?;` in AsyncTcpStream::new().
> Call tcp.set_nonblocking(true) in AsyncFd example.

- tokio/src/process/mod.rs
- tokio/src/runtime/handle.rs
* This allows callers to cheaply convert to a &std::process::Command and
use any (immutable) methods added on the stdlib type in case they are
missing from our own wrapper (e.g. because MSRV is lagging)
Refs #4285
> process: Add `as_std()` method to `Command`

- tokio/src/runtime/mod.rs
> runtime: fix typo

- .github/labeler.yml
- .github/workflows/labeler.yml
Using the `./` prefix apparently foobars the config and makes it not match anything.
Closes #4164.
> chore: update labeler.yml to drop filepath prefixes

- tokio/src/io/util/empty.rs
- tokio/tests/io_util_empty.rs
Fixes: #4291
Reads and buffered reads from a `tokio::io::empty` were always marked
as ready. That makes sense, given that there is nothing to wait for.
However, doing repeated reads on the `empty` could stall the event
loop and prevent other tasks from making progress.
This change makes reads on empty objects cooperative. One of every two
reads will return `Poll::Pending`, which will give the executor a
chance to keep making progress elsewhere.
I've added four integration tests. The tests wouldn't fail if the fix hadn't been implemented,
they would just hang forever (just like the original issue). 
This is my first contribution to the project, so maybe there are higher-level ways of achieving
this behaviour and testing this functionality. Let me know if that's the case!
> make `tokio::io::empty` cooperative

- benches/Cargo.toml
- examples/Cargo.toml
- tokio-stream/Cargo.toml
- tokio-util/Cargo.toml
Bumps `tokio-util` to `v0.7` but flags it as unpublishable, as we work towards the next (breaking) release of `tokio-util`.
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
> chore(util): start v0.7 release cycle

- tokio/src/macros/cfg.rs
- tokio/src/macros/trace.rs
- tokio/src/sync/barrier.rs
- tokio/src/sync/batch_semaphore.rs
- tokio/src/sync/mutex.rs
- tokio/src/sync/oneshot.rs
- tokio/src/sync/rwlock.rs
- tokio/src/sync/rwlock/owned_read_guard.rs
- tokio/src/sync/rwlock/owned_write_guard.rs
- tokio/src/sync/rwlock/owned_write_guard_mapped.rs
- tokio/src/sync/rwlock/read_guard.rs
- tokio/src/sync/rwlock/write_guard.rs
- tokio/src/sync/rwlock/write_guard_mapped.rs
- tokio/src/sync/semaphore.rs
- tokio/src/time/driver/sleep.rs
- tokio/src/time/interval.rs
- tokio/src/util/trace.rs
This PR adds instrumentation to more resources from the `sync` package.
Related: https://github.com/tokio-rs/console/pull/188
> tracing: instrument more resources

- tokio/src/coop.rs
- tokio/src/time/timeout.rs
- tokio/tests/time_timeout.rs
Refs: #4291 , #4300
Up until now, if the future that we were applying a timeout to
consistently depleted the coop budget, the timeout never got a chance to
be evaluated. In the next call to `poll`, the underlying future would be
polled and it would once again deplete the budget. In those circumstances,
timeouts would not be respected. This can be surprising to people, and
in fact it was in #4291
The solution is to make a budget exception with `timeout` if it was the
underlying future that depleted the budget.
I guess there are still pathological cases where the budget is almost depleted
before polling the `delay`, and it gets depleted while polling the delay, resulting in
the timeout never being hit as well. How do we want to go about that? I could simply do:
```
if had_budget_before { …
```
> make timeout robust against budget-depleting tasks

- README.md
- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This also includes a `tokio-macros` 1.7 release.
- io: add cooperative yielding support to `io::empty()` ([#4300])
- update minimum supported Rust version to 1.46.
- time: add `Interval::reset()` ([#4248])
- io: add explicit lifetimes to `AsyncFdReadyGuard` ([#4267])
- process: add `Command::as_std()` ([#4295])
- tracing: instrument `tokio::sync` types ([#4302])
[#4302]: https://github.com/tokio-rs/tokio/pull/4302
[#4300]: https://github.com/tokio-rs/tokio/pull/4300
[#4295]: https://github.com/tokio-rs/tokio/pull/4295
[#4267]: https://github.com/tokio-rs/tokio/pull/4267
[#4248]: https://github.com/tokio-rs/tokio/pull/4248
> chore: prepare Tokio v1.15.0 release

- tokio/src/net/tcp/socket.rs
- tokio/tests/tcp_socket.rs
For now, this is only allowed on TcpStream. This is a problem when one
want to disable lingering (i.e. set it to Duration(0, 0)). Without being
able to set it prior to the connect call, if the connect future is
dropped it would leave sockets in a TIME_WAIT state.
We need to be able to disable lingering on the socket. Otherwise if we drop the connect call, close will cause the socket to move to TIME_WAIT which is a problem for us.
SO_LINGER is a socket option (https://man7.org/linux/man-pages/man7/socket.7.html), expose it as such similar to what is done for buffer sizes for example. I left the possibility to do that on the connected stream as well
Note that I reused the same comments than in TcpStream for consistency. I found that the last part [1] is a bit confusing but I thought that …
> net: allow to set linger on TcpSocket

- tokio/src/io/read_buf.rs
The layout of wide pointers is unspecified, so `transmute`ing them is not valid.
Use `slice::from_raw_parts(_mut)` instead
> replace use of `transmute` with pointer manipulations

- tokio/src/lib.rs
The PR #4325 reminded me that stats is not currently mentioned in lib.rs.
> stats: mark stats feature unstable in lib.rs

- examples/Cargo.toml
When I copy some examples to my own project, found the introduce in examples/Cargo.toml are not clear enough.
1. Make the introduction more clear in examples/Cargo.toml.
2. Fix a style problem for examples/Cargo.toml
> chore: make the introduction in examples/Cargo.toml more clear

- CONTRIBUTING.md
- tokio/Cargo.toml
- tokio/src/macros/cfg.rs
- tokio/src/runtime/stats/mod.rs
- tokio/src/runtime/stats/stats.rs
- tokio/src/task/builder.rs
Currently, the docs.rs documentation for `tokio` is built without `--cfg
tokio_unstable` set. This means that unstable features are not shown in
the API docs, making them difficutl to discover. Clearly, we do want to
document the existence of unstable APIs, given that there's a section in
the lib.rs documentation listing them, so it would be better if it was
also possible to determine _what APIs_ an unstable feature enables when
reading the RustDoc documentation.
This branch changes the docs.rs metadata to also pass `--cfg
tokio_unstable` when building the documentation. It turns out that it's
necessary to separately pass the cfg flag to both RustDoc _and_ `rustc`,
or else the `tracing` dependency, which is only enabled in
`target.cfg(tokio_unstable).dependencies`, will be missing and the …
> docs: improve RustDoc for unstable features

- tokio-util/src/codec/length_delimited.rs
A tiny tweak to the documentation fixing #4340 by:
- modifying the example to set the length to 8MB instead of 8KB
- mentions the frame length is set in bytes
Closes: #4340
> improve Builder::max_frame_length docs

- .github/workflows/ci.yml
- tokio/src/io/util/write_all.rs
This fixes a clippy lint (from a newer version of clippy than we currently use in CI).
> io: fix clippy lint in `write_all`

- tokio/Cargo.toml
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
Closes #4135 
Unblocks #3082, #3312, #3542
> Update mio to 0.8

- tokio/src/net/tcp/socket.rs
This fixes CI failure on master: https://github.com/tokio-rs/tokio/actions/runs/1639606619
TcpSocket::linger has been added in https://github.com/tokio-rs/tokio/pull/4324 (2 weeks ago), but #4270 was last edited a month ago, so missed this change.
```
error[E0599]: no method named `get_linger` found for struct `Socket` in the current scope
--> tokio/src/net/tcp/socket.rs:381:20
|
381 |         self.inner.get_linger()
|                    ^^^^^^^^^^ help: there is an associated function with a similar name: `set_linger`
```
> net: fix build error on master

- tokio/src/net/tcp/socket.rs
- tokio/src/net/udp.rs
- tokio/tests/udp.rs
Closes #3312
Solves https://github.com/tokio-rs/tokio/discussions/3309
The first commit is from #4361.
Refs:
- [`std::net::UdpSocket::peer_addr`](https://doc.rust-lang.org/nightly/std/net/struct.UdpSocket.html#method.peer_addr)
- [`mio::net::UdpSocket::peer_addr`](https://docs.rs/mio/latest/mio/net/struct.UdpSocket.html#method.peer_addr)
> net: add UdpSocket::peer_addr

- tokio/src/net/tcp/socket.rs
Solves https://github.com/tokio-rs/tokio/discussions/3170
cc #3082
The first commit is from #4361.
Refs:
- [socket2::Socket::take_error](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.take_error)
> net: add TcpSocket::take_error

- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
This adds:
- UdpSocket::set_send_buffer_size
- UdpSocket::send_buffer_size
- UdpSocket::set_recv_buffer_size
- UdpSocket::recv_buffer_size
Closes #3542
The first commit is from #4361.
Refs:
- [socket2::Socket::set_send_buffer_size](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_send_buffer_size)
- [socket2::Socket::send_buffer_size](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.send_buffer_size)
- [socket2::Socket::set_recv_buffer_size](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_recv_buffer_size)
- [socket2::Socket::recv_buffer_size](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.recv_buffer_size)
> net: add buffer size methods to UdpSocket

- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
Closes #3545
cc #3082
The first commit is from #4361.
Refs:
- [socket2::Socket::tos](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.tos)
- [socket2::Socket::set_tos](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_tos)
> net: add tos and set_tos methods to TCP and UDP sockets

- tokio-stream/src/stream_ext.rs
- tokio-stream/src/stream_ext/map_while.rs
Fixes #4337
Rust 1.57 stabilized the `Iterator::map_while` API. This PR adds the same functionality to the `StreamExt` trait, to keep parity.
Keep parity with the standard iterator trait. There are many APIs that are available in `std::iter::Iterator` that aren't in `StreamExt`, but I guess it wouldn't harm to add this one?
The change is straight-forward, and is heavily inspired by the implementations of `map` and `take_while`.
> tokio-stream: add `StreamExt::map_while`

- .github/workflows/ci.yml
- tokio/src/loom/std/parking_lot.rs
Currently our `tokio::sync::watch::Ref` type can become `Send` if Tokio is compiled with the `parking_lot` feature and `parking_lot` is compiled with its `send_guard` feature. This PR will prevent the `send_guard` feature from affecting whether Tokio types are `Send` or not.
Strictly speaking, this PR is a breaking change, however I believe we should make the change regardless. As it stands now, the `parking_lot` crate is in our public API, and if don't want to make this change, then we should also commit to never upgrading `parking_lot` beyond `0.11.x`, as such an upgrade would be also be a breaking change for the same reasons.
I don't think many people will be affected by this. Anyone who is affected is probably holding a `tokio::sync::watch::Ref` alive across an `.await`, which is …
> Don't inherit Send from parking_lot::*Guard

- tokio/src/sync/watch.rs
- tokio/tests/sync_watch.rs
I'm using `sync::watch` to tell a bunch of workers to do some work, and once in a while they check to see what's the latest job, and if there's no new job they should keep doing what they're already doing, and currently the only way to do that is via `rex.changed().now_or_never().is_some()` which has some `Waker` overhead (see asm in https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=8fdf2f1bf2b6b16827b106dc13ef5895)
Add a `has_changed` method to check if the value had changed.
1. This method doesn't change the version that the receiver currently holds, this is the only function in the API that observes the version without changing it, should it maybe also change it? (that comes at the cost of being a `&mut self` function).
2. Implement  a `try_changed` function …
> Add a has_changed function to `watch::Receiver`

- tokio-util/src/codec/framed.rs
- tokio-util/src/codec/framed_read.rs
- tokio-util/src/codec/framed_write.rs
Previously it was not possible to get a mutable reference to the codec of a pinned `Framed`/`FramedWrite`/`FramedRead`. This shouldn't be a problem because we never access the codec through a pinned reference.
This pr adds the mutable reference getters `Framed::codec_pin_mut`, `FramedRead::decoder_pin_mut` and `FramedWrite::encoder_pin_mut`. 
The names were inspired by the `get_pin_mut` getters which return a pinned mutable reference to the underlying io streams. The added getters are slightly different in that they return a normal reference and not a pinned reference, so I'm not completely sure if adapting the same naming scheme is appropriate.
> util: add mutable reference getters for codecs to pinned `Framed`

- tokio-test/Cargo.toml
`cargo minimal-versions check` ([taiki-e/cargo-minimal-versions](https://github.com/taiki-e/cargo-minimal-versions)) should succeed on a project with tokio-test as a dependency.
Currently fails here:
```
...
Checking tokio-stream v0.1.0
Checking tokio-test v0.4.2
error[E0432]: unresolved import `tokio_stream::wrappers`
--> /Users/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-test-0.4.2/src/io.rs:24:19
|
24 | use tokio_stream::wrappers::UnboundedReceiverStream;
|                   ^^^^^^^^ could not find `wrappers` in `tokio_stream`
error[E0599]: no method named `poll_next` found for struct `Pin<_>` in the current scope
--> /Users/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-test-0.4.2/src/io.rs:206:32
|
206 |         Pin::new(&mut self.rx).poll_next(cx)
| …
```
> test: fix version requirement of tokio-stream

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/tests/loom_basic_scheduler.rs
- tokio/src/runtime/thread_pool/mod.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/src/util/atomic_cell.rs
- tokio/src/util/mod.rs
This PR does some refactoring to the current-thread scheduler bringing it closer to the structure of the multi-threaded scheduler. More specifically, the core scheduler data is stored in a `Core` struct and that struct is passed around as a "token" indicating permission to do work. The `Core` structure is also stored in the thread-local context.
This refactor is intended to support #4373, making it easier to track counters in more locations in the current-thread scheduler.
I tried to keep commits small, but the "set `Core` in thread-local context" is both the biggest commit and the key one.
> rt: refactor current-thread scheduler

- .cargo/audit.toml
- examples/Cargo.toml
The Tokio examples currently depend on an outdated `tracing-subscriber`
version, 0.2.7. This depends on the `chrono` crate, which is not
necessary.
I've updated the examples to the latest version. This also lets us stop
ignoring RUSTSEC-2020-0159 in `cargo audit`, so I removed the
configuration that was added in #4186.
Fixes #4177
> examples: update `tracing-subscriber` to 0.3

- tokio/src/net/udp.rs
I came across needing to generate a UDP Socket and allow the port to be dynamically allocated. The docs didn't have anything referencing how to do that. Thanks to the discord community I was able to get this answered
Add a note in the API Docs explaining that if Port 0 is given, then on bind() of the UDP socket, a port will be assigned.
> Edit API Docs to reference using port 0 on UDPSocket

- tokio/src/process/mod.rs
Drop the stdout/stderr pipes after the child has exited in `wait_with_output`. This will supposedly avoid a crash in some rare circumstances as discussed in #4309.
> process: drop pipe after child exits in `wait_with_output`

- tokio/src/sync/watch.rs
Under the hood, the watch channel uses a RwLock to implement reading
(borrow) and writing (send). This may cause a deadlock if a user has
concurrent borrows on the same thread. This is most likely to occur  due
to a recursive borrow.
This PR adds documentation to describe the deadlock so that future users
of the watch channel will be aware.
> watch: document recursive `borrow` deadlock

- tokio/src/sync/oneshot.rs
See #4319
The solution is same as in `mpsc` channels, except that method receiver is `self` instead of `&mut self`.
> Add blocking_recv method to oneshot::Receiver

- tokio/Cargo.toml
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/tests/udp.rs
The upgrade to Mio 0.8 came with other changes that introduced a regression
not caught by our CI. While we could move forward and fix that change, in an
effort to keep master "releasable" at all times, I propose reverting the changes
to give us time to re-introduce them after we fix the CI changes.
PR #4390 includes the fix + improving CI, but cannot be merged *yet* because
the CI improvements don't pass yet.
This reverts commits:
* ee0e811a362e4aeb8f47cb530cace2d352fb4b8a
* 49a9dc6743a8d90c46a51a42706943acf39a5d85
* 0190831ec1922047751b6d40554cc4a11cf2a82c
* 43cdb2cb5004a68d28c4394664b9f9964f3d59e2
* 96370ba4ce9ea5564f094354579d5539af8bbc9d
* a9d9bde0688cb88149272d78f8239a89b357974e
> Revert "Update mio to 0.8 (#4270)" and dependent changes

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/tests/loom_basic_scheduler.rs
- tokio/src/runtime/thread_pool/atomic_cell.rs
- tokio/src/runtime/thread_pool/mod.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/src/util/mod.rs
This reverts commit cc8ad367a0e5d8536f8be58fe560bfdea1a976a5, which caused hyper's tests to fail.
> Revert "rt: refactor current-thread scheduler (#4377)"

- .github/workflows/ci.yml
Split from #4390.
~~As said in #4392, this fails until https://github.com/tokio-rs/tokio/commit/cc8ad367a0e5d8536f8be58fe560bfdea1a976a5 (#4377) is reverted (or until the regression introduced by that commit is fixed).~~
UPD: https://github.com/tokio-rs/tokio/commit/cc8ad367a0e5d8536f8be58fe560bfdea1a976a5 has been reverted in #4394
> chore: test hyper on CI

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/tests/loom_basic_scheduler.rs
- tokio/src/runtime/thread_pool/mod.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/src/util/atomic_cell.rs
- tokio/src/util/mod.rs
- tokio/tests/rt_basic.rs
Re-applies #4377 and fixes the bug resulting in Hyper's double panic.
Revert: #4394
Original PR:
This PR does some refactoring to the current-thread scheduler bringing it closer to the structure of the multi-threaded scheduler. More specifically, the core scheduler data is stored in a Core struct and that struct is passed around as a "token" indicating permission to do work. The Core structure is also stored in the thread-local context.
This refactor is intended to support #4373, making it easier to track counters in more locations in the current-thread scheduler.
I tried to keep commits small, but the "set Core in thread-local context" is both the biggest commit and the key one.
> rt: refactor current-thread scheduler (take 2)

- tokio/src/runtime/blocking/pool.rs
In [SergioBenitez/Rocket/issues/2031](https://github.com/SergioBenitez/Rocket/issues/2031#issue-1085783035), an issue was encountered where the OS could not spawn new blocking worker threads. This PR adds a more clear error message to the panic.
> Add better error message when spawning blocking threads

- tests-build/tests/fail/macros_type_mismatch.stderr
A change in rustc broke some tests checking our macro error output.
> chore: fix ci to track Rust 1.58

- tokio/src/runtime/thread_pool/idle.rs
- tokio/src/runtime/thread_pool/worker.rs
This PR reduces the number of times worker threads wake up without having work to do in the multi-threaded scheduler. Unnecessary wake-ups are expensive and slow down the scheduler. I have observed this change reduce no-op wakes by up to 50%.
The multi-threaded scheduler is work-stealing. When a worker has tasks to process, and other workers are idle (parked), these idle workers must be unparked so that they can steal work from the busy worker. However, unparking threads is expensive, so there is an optimization that avoids unparking a worker if there already exists workers in a "searching" state (the worker is unparked and looking for work). This works pretty well, but transitioning from 1 "searching" worker to 0 searching workers introduces a race condition where a thread unpark can be …
> rt: reduce no-op wakeups in the multi-threaded scheduler

- tokio/src/runtime/task/join.rs
- tokio/tests/unwindsafe.rs
Marking JoinHandle as UnwindSafe allows for more ergonomic panic handling resolving this example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=77e8b4432bd28f50080cbae9eb26b8ae
> runtime: mark JoinHandle as UnwindSafe (#4414)

- tokio-util/src/codec/framed.rs
- tokio-util/src/codec/framed_read.rs
- tokio-util/src/codec/framed_write.rs
- tokio-util/tests/framed.rs
- tokio-util/tests/framed_read.rs
- tokio-util/tests/framed_write.rs
Currently, changing the codec of a `Framed` is verbose and unnecessarily complicated, as noted in #717.
This PR implements a method that maps the inner codec to a new type, preserving the read/write buffers and IO state. The syntax was first suggested by Carl Lerche.
The usage is as follows:
```rust
let framed: Framed<Io, U32Codec> = Framed::new(io, U32Codec);
let _: u32 = framed.next().await.unwrap();
let framed: Framed<Io, U64Codec> = framed.map_codec(|_codec| U64Codec);
let _: u64 = framed.next().await.unwrap();
```
> feat: implement `Framed::map_codec` 

- .github/workflows/ci.yml
- tokio/Cargo.toml
- tokio/src/coop.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/sync/tests/atomic_waker.rs
- tokio/src/sync/tests/notify.rs
- tokio/src/sync/tests/semaphore_batch.rs
- tokio/src/util/linked_list.rs
- tokio/tests/_require_full.rs
- tokio/tests/macros_join.rs
- tokio/tests/macros_pin.rs
- tokio/tests/macros_select.rs
- tokio/tests/macros_test.rs
- tokio/tests/macros_try_join.rs
- tokio/tests/net_lookup_host.rs
- tokio/tests/no_rt.rs
- tokio/tests/sync_barrier.rs
- tokio/tests/sync_broadcast.rs
- tokio/tests/sync_errors.rs
- tokio/tests/sync_mpsc.rs
- tokio/tests/sync_mutex.rs
- tokio/tests/sync_mutex_owned.rs
- tokio/tests/sync_notify.rs
- tokio/tests/sync_oneshot.rs
- tokio/tests/sync_rwlock.rs
- tokio/tests/sync_semaphore.rs
- tokio/tests/sync_semaphore_owned.rs
- tokio/tests/sync_watch.rs
- tokio/tests/task_local.rs
Several of tokio's features (e.g. the channel implementation) do not need a runtime to work, and can be compiled and used for wasm32-unknown-unknown targets
This change enables running tests for the `sync` and `macros` features so that we can note any regressions there
> Enable running wasm32-unknown-unknown tests

- tokio/src/sync/mutex.rs
- tokio/src/sync/rwlock.rs
Same as #4130, but for `RwLock` this time.
> Add blocking lock methods to `RwLock`

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
Fixes a soundness bug in `io::Take` ([#4428]). The unsoundness is exposed when
leaking memory in the given `AsyncRead` implementation and then overwriting the
supplied buffer:
```rust
impl AsyncRead for Buggy {
fn poll_read(
self: Pin<&mut Self>,
cx: &mut Context<'_>,
buf: &mut ReadBuf<'_>
) -> Poll<Result<()>> {
let new_buf = vec![0; 5].leak();
*buf = ReadBuf::new(new_buf);
buf.put_slice(b"hello");
Poll::Ready(Ok(()))
}
}
```
Also, this release includes improvements to the multi-threaded scheduler that
can increase throughput by up to 20% in some cases ([#4383]).
- io: **soundness** don't expose uninitialized memory when using `io::Take` in edge case ([#4428])
- fs: ensure `File::write` reaches the disk when the runtime shuts down ([#4316])
- process: drop pipe after child exits in …
> chore: prepare Tokio v1.16 release.

- tokio/src/runtime/task/harness.rs
- tokio/tests/join_handle_panic.rs
Fixes #4412
From the issue description:
> In Tokio, panics are generally caught and not passed resumed when
dropping the JoinHandle, however when dropping the JoinHandle of a task
that has already completed, that panic can propagate to the user who
dropped the JoinHandle.
Just swallow the panic? I've seen other places in tokio where that happens, but I'm open to hearing
if you had other ideas for this.
> runtime: swallow panics in drop(join_handle)

- tokio-stream/tests/stream_timeout.rs
- tokio-stream/tests/time_throttle.rs
Closes: #4341 
Before was using full that is not a feature in tokio-stream/cargo, in time_thorttle i could use time as feature, in stream_time out i could not. I chose io-util because I think makes sense but i would like some help to make this one correct too
> adjusted feature name in tests

- tokio/src/runtime/blocking/pool.rs
I found an unnecessary lock operation. 
https://github.com/tokio-rs/tokio/blob/afd2189eec8b21075a98613ffc2e11c38b82d4b9/tokio/src/runtime/blocking/pool.rs#L222-L271
```rs
let shutdown_tx = {
let mut shared = self.inner.shared.lock(); 
...
}
if let Some(shutdown_tx) = shutdown_tx {
let mut shared = self.inner.shared.lock();
}
```
delete it
> rt: reduce an unnecessary lock operation

- .circleci/config.yml
- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/stress-test.yml
When backporting patches to LTS branches, we often run into CI failures due to changes in rust. Newer rust versions add more lints, which break CI. We really don't want to also have to backport patches that fix CI, so instead, LTS branches should pin the stable rust version in CI (e.g. #4434).
This PR restructures the CI config files to make it a bit easier to set a specific rust version in CI.
> chore: make it easier to pin Rust versions in CI

- .cirrus.yml
- .github/workflows/ci.yml
- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/LICENSE
- tokio/src/io/util/take.rs
- tokio/tests/io_take.rs
> io: fix `take` when using evil reader (backport #4428)

- tokio/src/loom/std/atomic_u64.rs
building with `tokio-unstable` fails for arm32v7
Implement `fetch_add` for the custom AtomicU64 type fixes https://github.com/tokio-rs/tokio/issues/4452
> Add fetch_add for AtomicU64

- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/stress-test.yml
- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/LICENSE
- tokio/README.md
- tokio/src/io/util/take.rs
- tokio/tests/io_take.rs
Backports #4428 into 1.14.x
Refs: #4434
> io: fix take when using evil reader (backport #4428 to 1.14)

- tokio/Cargo.toml
The version was not specified, preventing publishing a crate.
> chore: specify tokio-macros version

- tokio/tests/io_take.rs
> io: add test for take bug

- tokio/src/runtime/basic_scheduler.rs
The enum is no longer needed. It was used previously to support multiple
kinds of control messages to the scheduler but that has been refactored
out.
> rt: remove unnecessary enum in basic_scheduler

- tokio/src/time/instant.rs
`Instant::duration_since`, `Instant::elapsed`, and `Instant::sub` may
panic. This is especially dangerous when `Instant::now` travels back in
time. While this isn't supposed to happen, this behavior is highly
platform-dependent (e.g., rust-lang/rust#86470).
This change modifies the behavior of `tokio::time::Instant` to prevent
this class of panic, as proposed for `std::time::Instant` in
rust-lang/rust#89926.
---
@carllerche Suggested we may be able to make these changes to `tokio::time::Instant` to avoid `std::time::Instant` bugs. I've attempted to make similar changes in a variety of ecosystem projects (hyperium/hyper#2746, etc); but it seems higher-leverage to modify tokio to avoid this problem so that ecosystem projects can rely on Tokio's `Instant` type safely.
> time: Eliminate panics from `Instant` arithmetic

- tokio/src/macros/cfg.rs
- tokio/src/runtime/metrics/worker.rs
Fix build on mips.
close #4469 
Use atomic primitive types provided by `crate::loom`.
> metrics: fix build on mips

- tokio/src/io/util/fill_buf.rs
This improves the safety comment on `FillBuf`.
> io: improve safety comment on FillBuf

- tokio-util/src/codec/bytes_codec.rs
- tokio-util/tests/codecs.rs
Let's assume that we want to write an echo server (actually, I'm writing a reverse proxy). It should be great if we can write as following:
```rust
use std::io;
use futures::StreamExt;
use tokio::net::{TcpListener, TcpStream};
use tokio_util::codec::{BytesCodec, FramedRead, FramedWrite};
#[tokio::main]
async fn main() -> io::Result<()> {
let listener = TcpListener::bind("0.0.0.0:8080").await?;
loop {
let (socket, _) = listener.accept().await?;
tokio::spawn(process_socket(socket));
}
}
async fn process_socket(socket: TcpStream) {
let (reader, writer) = socket.into_split();
let reader = FramedRead::new(reader, BytesCodec::new());
let writer = FramedWrite::new(writer, BytesCodec::new());
reader.forward(writer).await.unwrap();
}
```
However, rustc complains that  `Encoder<BytesMut>` is not …
> Implement Encoder<BytesMut> for BytesCodec

- tokio/src/io/util/mem.rs
- tokio/tests/io_mem_stream.rs
Add coop checks on pipe poll_read and poll_write.
Fixes: #4470
Refs: #4291, #4300
This attempts to fix https://github.com/tokio-rs/tokio/issues/4470 DuplexStream does not participate in coop.
Similar to what's done in https://github.com/tokio-rs/tokio/issues/4291. The change calls coop `poll_proceed` to decrement budge on poll_read and poll_write, then it calls `made_progress` to resume budget if made progress. 
Without the changes, the added `duplex_is_cooperative` test would hang. 
Ran cargo build, check and test with all-features. Ran cargo fmt.
> io: make duplex stream cooperative (#4470)

- tokio/src/task/local.rs
PR #3881 factored out the spawning of local tasks on a `LocalSet` into a
function `spawn_local_inner`, so that the implementation could be shared
with the `task::Builder` API. But, that PR neglected to add a
`#[track_caller]` attribute to `spawn_local_inner`, so the `tracing`
spans for local tasks are all generated with `spawn_local_inner` as
their spawn location, rather than forwarding the actual spawn location
from the calling function.
This causes pretty useless results when using `tokio-console` with code
that spawns a number of local tasks, such as Actix
(https://old.reddit.com/r/rust/comments/snt5fq/can_tokioconsole_profile_actixrt/)
This commit fixes the issue by adding the missing `#[track_caller]`
attribute.
> task: fix missing `#[track_caller]` in `spawn_local`

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
- task: add `spawn_pinned` ([#3370])
- time: add `shrink_to_fit` and `compact` methods to `DelayQueue` ([#4170])
- codec: improve `Builder::max_frame_length` docs ([#4352])
- codec: add mutable reference getters for codecs to pinned `Framed` ([#4372])
- net: add generic trait to combine `UnixListener` and `TcpListener` ([#4385])
- codec: implement `Framed::map_codec` ([#4427])
- codec: implement `Encoder<BytesMut>` for `BytesCodec` ([#4465])
- sync: add lifetime parameter to `ReusableBoxFuture` ([#3762])
- sync: refactored `PollSender<T>` to fix a subtly broken `Sink<T>` implementation ([#4214])
- time: remove error case from the infallible `DelayQueue::poll_elapsed` ([#4241])
[#3370]: https://github.com/tokio-rs/tokio/pull/3370
[#4170]: https://github.com/tokio-rs/tokio/pull/4170 …
> chore: prepare tokio-util 0.7.0

- tokio/src/process/mod.rs
I struggled with figuring out how to effectively use `ChildStdin` in tokio::process . There are a lot of examples on how to capture `stdout` but only one combined example with stdin which focuses more on chaining. I've found this more well documented in other languages (Go, Python).
I created a quick example which showcases how to write to `stdin` but also highlighting that the user needs to drop the handle for EOF to be signaled.
Closes: #4477
> doc: Created a simple example for tokio::process::ChildStdin

- tokio-util/Cargo.toml
This failed in h2 CI:
https://github.com/hyperium/h2/runs/5153518790?check_suite_focus=true
It looks like minimal versions support does not the right thing in the face of path dependencies.
> util: bump tokio dependency to 1.6 to satisfy minimal versions

- tokio/Cargo.toml
Update minimal mio requirement to 0.7.11 includes https://github.com/tokio-rs/mio/pull/1478 (needed for windows) and https://github.com/tokio-rs/mio/pull/1434 (needed for macos).
Caught in https://github.com/tokio-rs/tokio/pull/4490#issuecomment-1037008658 by using https://github.com/taiki-e/cargo-minimal-versions/pull/4.
```
info: running `cargo check --all-features` on tokio-stream (1/1)
Compiling libc v0.2.69
Compiling log v0.4.8
Compiling autocfg v1.0.0
Compiling memchr v2.2.0
Checking cfg-if v0.1.2
Checking arc-swap v0.4.0
Checking pin-project-lite v0.2.5
Checking once_cell v1.5.2
Checking bytes v1.0.0
Checking futures-core v0.3.0
Checking futures-sink v0.3.0
Compiling tokio v1.8.0
Checking signal-hook-registry v1.1.1
Checking mio v0.7.6
error[E0425]: cannot find value …
```
> chore: update minimal mio requirement to 0.7.11

- tokio/src/loom/std/mod.rs
- tokio/src/sync/task/atomic_waker.rs
Since our MSRV has been increased to 1.49 in #4457, it's ok to replace deprecated `spin_loop_hint` with `hint::spin_loop`.
close #3498.
> replace deprecated `spin_loop_hint` with `hint::spin_loop`

- tokio/Cargo.toml
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
The major breaking change in Mio v0.8 is TcpSocket type being removed.
Replacing Mio's TcpSocket we switch to the socket2 library which
provides a similar type Socket, as well as SockRef, which provide all
options TcpSocket provided (and more!).
Tokio's TcpSocket type is now backed by Socket2 instead of Mio's
TcpSocket. The main pitfall here is that socket2 isn't non-blocking by
default, which Mio obviously is. As a result we have to do potentially
blocking calls more carefully, specifically we need to handle
would-block-like errors when connecting the TcpSocket ourselves.
One benefit for this change is that adding more socket options to
TcpSocket is now merely a single function call away (in most cases
anyway).
> Update to Mio v0.8

- tokio-util/src/sync/cancellation_token.rs
There was a missing exclamation mark in the condition we used to test whether we need a waker update in `check_for_cancellation`.
> Fix waker update condition in `CancellationTokenState::check_for_cancellation`

- tokio/src/macros/cfg.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/task/mod.rs
- tokio/src/util/mod.rs
- tokio/tests/async_send_sync.rs
- tokio/tests/task_join_set.rs
There are still some open questions related to the API. Until they are
resolved, the type should be marked as unstable so releases are not
blocked.
Specifically, how can tasks spawned onto the `JoinSet` be canceled?
My inclination would be to return an `AbortHandle` from `JoinSet::spawn`.
> rt: make `JoinSet` unstable

- tokio/src/time/driver/wheel/level.rs
time: resolve TODO
Existing `TODO` comment in `src/time/driver/wheel/level.rs`.
`level_range()` always return a strictly positive power of 2. If `b` is a
strictly positive power of 2, `a - (a % b)` is equal to `a & !(b - 1)`.
> time: use bit manipulation instead of modulo

- tokio/src/task/builder.rs
- tokio/src/task/join_set.rs
PR #4499 made the `JoinSet` API unstable, but did not add a
documentation note explaining unstable features. In general, since the
docs.rs build includes unstable APIs, it's probably worth including
these notes so that users understand what it means for an API to be
unstable.
This branch adds a note on unstable APIs to the `JoinSet` type-level
documentation, similar to the notes for `task::Builder` and the runtime
metrics APIs.
Also, I noticed that there was a broken link to the top-level
documentation on unstable APIs in the docs for `task::Builder`, so I
fixed that as well.
> task: fix unstable API documentation notes

- tokio/src/sync/watch.rs
- tokio/tests/sync_watch.rs
`send_modify` allows to modify inner value without having to allocate new value which can be expensive if the inner value is for example struct that holds a lot of data.
> sync: add `watch::Sender::send_modify` method

- tokio/tests/sync_watch.rs
This fixes a test failure that broke master.
> ci: fix test not working on wasm

- tokio-util/src/sync/cancellation_token.rs
Examples in `cancellation_token.rs` doesn't work since import path of `CancellationToken` is not up to date. I'd like to fix this to make the examples work without each developer fixing import path.
Fix import path of CancellationToken👍
> util: fix import path of CancellationToken in example code

- tokio-util/src/codec/length_delimited.rs
Like `length_field_length` except you pass a compile-time checked unsigned integer type instead.
Powers of two are the most common values for `length_field_length`, but passing in a number of bytes for these feels a bit awkward, especially when the docs state "parse a `u16` length field".
Add `length_field_type` method that takes a generic type.
Implement a sealed (public in private) trait for acceptable types, failing on bad types at compile-time (e.g. `i32`, `u128`, `String`).
> Add `length_field_type` to `LengthDelimitedCodec` builder

- tokio/src/task/join_set.rs
The `JoinSet` type is currently missing the `tokio_unstable` and
`feature = "rt"` `doc(cfg(...))` attributes, making it erroneously
appear to be available without the required feature and without unstable
features enabled. This is incorrect.
I believe this is because `doc(cfg(...))` on a re-export doesn't
actually add the required cfgs to the type itself, and the
`cfg_unstable!` is currently only guarding a re-export and module.
This PR fixes the missing attributes.
Before:
After:
> task: fix missing doc(cfg(...)) attributes for `JoinSet`

- .gitignore
- tests-integration/Cargo.toml
- tokio/src/io/driver/metrics.rs
- tokio/src/io/driver/mod.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/src/runtime/metrics/io.rs
- tokio/src/runtime/metrics/mod.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/mod.rs
- tokio/tests/rt_metrics.rs
This adds the initial IO driver metrics.
Ref: https://github.com/tokio-rs/tokio/issues/4073
> tokio: Add initial io driver metrics

- tests-build/tests/fail/macros_invalid_input.stderr
- tests-build/tests/fail/macros_type_mismatch.stderr
Rust error messages seem to have changed a bit in 1.59.0
Update the `trybuild` stderr output.
This should unbreak the tests on the latest Rust (and fix CI).
> macros: update `trybuild` output for Rust 1.59.0 

- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/raw.rs
- tokio/src/runtime/tests/task.rs
- tokio/src/runtime/tests/task_combinations.rs
- tokio/src/task/join_set.rs
- tokio/src/task/mod.rs
- tokio/tests/task_join_set.rs
Before we stabilize the `JoinSet` API, we intend to add a method for
individual tasks in the `JoinSet` to be aborted. Because the
`JoinHandle`s for the tasks spawned on a `JoinSet` are owned by the
`JoinSet`, the user can no longer use them to abort tasks on the
`JoinSet`. Therefore, we need another way to cause a remote abort of a
task on a `JoinSet` without holding its `JoinHandle`.
This branch adds a new `AbortHandle` type in `tokio::task`, which
represents the owned permission to remotely cancel a task, but _not_ to
await its output. The `AbortHandle` type holds an additional reference
to the task cell.
A crate-private method is added to `JoinHandle` that returns an
`AbortHandle` for the same task, incrementing its ref count.
`AbortHandle` provides a single method, …
> task: add `AbortHandle` type for cancelling tasks in a `JoinSet`

- tokio/src/runtime/blocking/pool.rs
As described in #2309 the runtime panics when trying to spawn a new thread and the OS have reaches the limit of threads / processes.
This can be observed on a Linux machine decreasing the limit with `ulimit -u` and running the program in #2309.
As noted by @Darksonn there is a pool of threads, and failing to spawn a new one is not mandatory for the program to make progress.
Ignore the temporary errors when failing to spawn a new thread from the OS.
The task will be naturally scheduled by threads already in the pool.
Fixes: #2309
> recover when OS fails to spawn a new thread

- .cirrus.yml
- .github/workflows/ci.yml
- tokio/src/lib.rs
Ran into some headaches getting `tokio_unstable` working, since I'd never had to deal with `--cfg` directly before. I was told "PRs welcome" in the [Tokio Discord][1], so here I am. :) 
[1]: https://discord.com/channels/500028886025895936/500336333500448798/945420414052614204
Mostly I added an example `.cargo/config.toml` for others who run into this.
But the existing docs seemed really focused on "these feature flags are enabled by tokio_unstable", but now tioko_unstable also enables JoinSet, so I reworked it a bit to call that out explicitly.
I didn't want to blather on too much in rustdoc about "this is why we can't just use a crate feature", so I just linked to the writeup I posted about it on the Rust internals forum.  Is that weird? 😅
> Improve docs for tokio_unstable.

- tokio/src/runtime/task/abort.rs
There's a broken docs link in the docs for `AbortHandle`. Somehow this
managed to slip past CI yesterday when #4530 was merged
(https://github.com/tokio-rs/tokio/runs/5325278596?check_suite_focus=true)
but it's breaking the build now
(https://github.com/tokio-rs/tokio/runs/5337182732?check_suite_focus=true)
which seems really weird to me, but...whatever...
This branch fixes the broken link lol.
> task: fix broken link in `AbortHandle` RustDoc

- tokio-util/Cargo.toml
- tokio-util/src/codec/framed_impl.rs
I am trying to remove any usage of `log` in our dep tree, so I can turn off the `tracing-log` feature, and I noticed `tokio-util` still used `log`, so I am trying to change it to `tracing`!
There were only a few callsites using `log` in `tokio-util`, so I figured switching them to tracing, like the rest of the tokio ecosystem would be fine!
> switch tokio-util from log to tracing

- tokio/src/signal/unix.rs
The type `tokio::signal::unix::SignalKind` corresponds to a `libc::c_int`. The newtype is missing some useful functionality:
* No `Hash`/`Eq` impls, so they can't be compared or used as map keys
* No ability to convert a `SignalKind` back into a `c_int`, which can be useful for interop
* Add derived impls of `Hash`, `PartialEq`, and `Eq` to `SignalKind`
* Add `as_raw_value()` method and `From`/`Into`
* Add conversion tests
> feat: Add SignalKind Hash/Eq impls and c_int conversion

- tokio/src/sync/mpsc/unbounded.rs
cc @Firstyear
The documentation for `tokio::sync::mpsc::UnboundedReceiver` is inconsistent with the bounded `Receiver` counterpart, lacking critical details including how calling `UnboundedReceiver::recv` returns `None` after `close` is called, even if there are remaining senders.
Copy and paste the relevant parts from the bounded `Receiver` documentation into `UnboundedReceiver`.
> Unbounded receiver docs

- tokio/src/runtime/thread_pool/worker.rs
Quick PR: noticed all those vecs are pushed to unconditionally, so pre-allocate their sizes.
> Use with_capacity

- tokio/src/macros/select.rs
This internal module's identifier can clash with existing identifiers in library users' code and produce confusing error messages.
```rust
mod util {
pub fn hello_world() {
println!("Hello, world!");
}
}
#[tokio::main]
async fn main() {
let f1 = async {};
let f2 = async {};
tokio::select! {
_ = f1 => {
// The following line would fix the compile error, showing that Tokio is creating an internal identifier called `util` which is clashing
// use crate::util;
util::hello_world();
},
_ = f2 => {}
}
}
```
```rust
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find function `hello_world` in module `util`
--> src/main.rs:14:19
|
14 |             util::hello_world();
|                   ^^^^^^^^^^^ not found in `util`
|
help: consider importing this function
|
1 …
```
> Rename `tokio::select!`'s internal `util` module to `__tokio_select_util`

- tokio/src/runtime/thread_pool/worker.rs
After spending some time reading the internals of the runtime I thought that having more comments on the code around specific behaviors would be helpful to others.
> Include more documentation for thread_pool/worker

- tokio/src/signal/registry.rs
- tokio/src/signal/unix.rs
The POSIX standard not only supports "reliable signals", but also
"real-time signals". This commit adds support for the latter.
Fixes: #4554
> tokio: add support for signals up to SIGRTMAX

- tokio/src/sync/broadcast.rs
- tokio/tests/sync_broadcast.rs
Attempts to fix https://github.com/tokio-rs/tokio/issues/4405
This PR adds a method `recv_with_queue_status` to `Receiver` that returns (in a successful call) a tuple consisting of the received message and the number of messages that have been sent into the channel but have yet to be received by this Receiver.
> Add a method on Receiver that gives information on queue status in broadcast channel

- tokio/src/io/driver/mod.rs
- tokio/src/net/addr.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/sync/barrier.rs
- tokio/src/sync/batch_semaphore.rs
- tokio/src/sync/oneshot.rs
- tokio/src/time/driver/sleep.rs
- tokio/tests/sync_mutex.rs
- tokio/tests/sync_mutex_owned.rs
Recent Clippy releases have added some new lints that trigger on some
code in Tokio. These aren't a big deal, but seeing them in my editor is
mildly annoying.
This branch fixes the following issues flagged by Clippy:
* manual `Option::map` implementation
* use of `.map(...).flatten(...)` that could be replaced with
`.and_then(...)`
* manual implementation of saturating arithmetic on `Duration`s
* simplify some boolean expressions in assertions (`!res.is_ok()` can be
`res.is_err()`)
* fix redundant field names in initializers
* ~~allow the `clippy::unnecessary_to_owned` lint in `ToSocketAddrs` impl
for `&[SocketAddr]` --- the "unnecessary" `to_vec()` call is actually
necessary to ensure the iterator is `'static`~~
* replace an unnecessary cast to `usize` with an explicitly typed
integer …
> chore: fix a bunch of annoying clippy lints

- .github/workflows/ci.yml
- tokio/src/runtime/metrics/runtime.rs
It turns out that the CI job for testing `tokio_unstable` features isn't
actually running doctests for `tokio_unstable`, just lib and integration
tests. This is because RustDoc is responsible for running doctests, and
it needs the unstable cfg passed to it separately from `RUSTFLAGS`.
This means that if the examples for unstable APIs are broken, CI won't
catch this, which is not great!
This commit changes the `test-unstable` CI job to pass `--cfg
tokio_unstable` in `RUSTDOCFLAGS` as well as `RUSTFLAGS`. This way,
doctests for unstable APIs should actually run.
> ci: run doctests for unstable APIs

- tokio-util/src/io/stream_reader.rs
Attempt to fix https://github.com/tokio-rs/tokio/issues/4552 by exposing the internal buffer of `StreamReader`.
> Add method that exposes the internal buffer of StreamReader

- tokio/src/sync/watch.rs
I'd like to determine if two `watch::Receiver`s are part of the same channel (i.e. will receive values from the same `watch::Sender`.
Specifically, I'd like to have a `HashMap<K, watch::Receiver<V>>`, and then later be able to check if *my* entry is still there, or someone else has removed it (and potentially replaced it with a Receiver for a different Sender).
Closes: https://github.com/tokio-rs/tokio/issues/4579
Add a `same_channel()` method which uses `Arc::ptr_eq` on `Receiver::shared`
> sync: add `watch::Receiver::same_channel`

- tokio/Cargo.toml
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/stream.rs
A user defined I/O closure should be called by mio's try_io to ensure that the I/O receives more events if it hits a WouldBlock error.
Make tokio's try_io methods call mio's try_io method using a given closure.
Fixes: #4510
> Make try_io methods call mio's try_io internally

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
The minimal versions fix from #4490 is required to bump h2, which is probably one of the more prominent tokio-util users.
We might want to wait to get #4520 and/or #4508 in, too?
> chore: prepare tokio-util 0.7.1 release

- tokio/tests/uds_stream.rs
This completes the TODOs in uds_stream `accept_read_write` test by
using `AsyncWriteExt::write_all` instead of `AsyncWriteExt::write` and
`AsyncReadExt::read_to_end` instead of `AsyncReadExt::read_exact`.
Complete the TODOs in uds_stream `accept_read_write` test.
Use `AsyncWriteExt::write_all` instead of `AsyncWriteExt::write` and
`AsyncReadExt::read_to_end` instead of `AsyncReadExt::read_exact`.
> tests: complete TODOs in uds_stream.

- tokio-util/Cargo.toml
tracing enables the `attributes` feature by default, which we don't need here. I'd like to keep a close eye on the proc macro crates in my dependency tree.
Disable default features and enable only the ones we need.
> Import tracing without the default attributes feature

- tokio-stream/src/lib.rs
Expose `Timeout` so users can refer to it in their code.
> stream: expose Timeout

- tokio/src/runtime/handle.rs
`Handle::current` docs say it's not possible to call it on any non-runtime thread, but you can call it from a runtime context created by an `EnterGuard`. This updates the docs to mention `EnterGuard` as a way to avoid this panic.
> Update Handle::current to mention EnterGuard

- tokio-stream/src/wrappers/broadcast.rs
- tokio/src/sync/broadcast.rs
- tokio/src/sync/mpsc/error.rs
- tokio/src/sync/oneshot.rs
- tokio/src/sync/watch.rs
So `Result<T, RecvError>` is `Clone`, so `Receiver<T>` can be placed in `Shared<...>`.
Note `mpsc::TryRecvError` is already `Clone`.
Note `mpsc::TryRecvError` is also `Copy`, but this PR only adds `Clone`, because it is future proof.
> Add Clone to RecvError types

- tokio/src/net/udp.rs
The std [UdpSocket](https://doc.rust-lang.org/stable/std/net/struct.UdpSocket.html) exposes the method [peer_addr](https://doc.rust-lang.org/stable/std/net/struct.UdpSocket.html#method.peer_addr) to get the address of the remote peer the socket is connected to but tokio `UdpSocket` does not.
There are other ways to get the peer address as mentioned in #4609 but `peer_addr` makes it convenient.
Fixes: #4609
Implement `peer_addr` for `UdpSocket` and forward the call to [mio](https://github.com/tokio-rs/mio).
> net: add peer_addr to UdpSocket

- tokio/src/runtime/blocking/pool.rs
This PR adds a `#[track_caller]` annotation to [`runtime::blocking::spawn_blocking()`](https://github.com/domodwyer/tokio/blob/eed85e46740cb21449fcfa92e14485d6b6c936e2/tokio/src/runtime/blocking/pool.rs#L108).
Similar to #4483, the driver behind this change is to correctly tag the caller as the spawn location in tracing spans, primarily for consumption with `tokio-console`. 
Prior to this PR, any tasks spawned with `spawn_blocking()` would show a spawn location within tokio:
After this PR, the spawn location is correctly recorded as the `main.rs` file in my reproducer:
I am not sure how to effectively test this, and #4483 didn't test it either - happy to add tests with a bit of guidance!
---
* blocking: #[track_caller] for spawn_blocking (eed85e46)
Annotates spawn_blocking() with …
> blocking: #[track_caller] for spawn_blocking

- .cirrus.yml
FreeBSD 12.2 is EoL.  It has no support, and at some point soon pre-built packages might start depending on 12.3 features.
Update the CI image.
> Update FreeBSD CI image to 12.3.  12.2 is EoL.

- tests-build/tests/fail/macros_invalid_input.rs
- tests-build/tests/fail/macros_invalid_input.stderr
- tokio-macros/src/entry.rs
- tokio-macros/src/lib.rs
- tokio/tests/macros_rename_test.rs
* Accommodate to dependency rename(rust-lang/cargo#5653). Fixes #2312.
* Enable `#[crate::test(crate = "crate")]` in unit tests.
Support `NameValue` attribute `crate` to custom crate name.
> macros: custom crate name for #[tokio::main] and #[tokio::test]

- tokio/Cargo.toml
This reduces tokio's test compile time by a few seconds.
Upgrade nix to 0.24, which split nix into multiple features. Opt out of the default features and request just the ones required for tokio.
> Upgrade nix to 0.24, limit features

- tokio/src/net/windows/named_pipe.rs
[`net::windows::named_pipe::NamedPipeClient`](https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.NamedPipeClient.html) is missing the `add_try_buf` method. Similar structs implement this method like [`net::TcpStream`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.try_read_buf) or [`net::UnixStream`](https://docs.rs/tokio/latest/tokio/net/struct.UnixStream.html#method.try_read_buf).
Therefore this will fix #4602.
Since `TcpStream` and `UnixStream` are so similar, I just copied over the method body and replaced references to the original type.
I realized that all three types are very similar and may benefit from using macros but since it's not currently used, this is out of scope of this PR.
Also a test is missing. `TcpStream` and `UnixStream` have test …
> Add `add_try_buf` for `net::windows::named_pipe::{NamedPipeClient, NamedPipeServer}`

- tokio/src/macros/select.rs
- tokio/src/signal/unix.rs
I think this is the case, so let's document it!
> docs: Signal::recv is cancel-safe

- tokio/Cargo.toml
- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/spawner.rs
- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/error.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/list.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/raw.rs
- tokio/src/runtime/tests/mod.rs
- tokio/src/runtime/tests/task.rs
- tokio/src/runtime/thread_pool/mod.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/src/task/join_set.rs
- tokio/src/task/local.rs
- tokio/src/task/mod.rs
- tokio/src/task/spawn.rs
- tokio/src/util/trace.rs
PR #4538 adds a prototype implementation of a `JoinMap` API in
`tokio::task`. In [this comment][1] on that PR, @carllerche pointed out
that a much simpler `JoinMap` type could be implemented outside of
`tokio` (either in `tokio-util` or in user code) if we just modified
`JoinSet` to return a task ID type when spawning new tasks, and when
tasks complete. This seems like a better approach for the following
reasons:
* A `JoinMap`-like type need not become a permanent part of `tokio`'s
stable API
* Task IDs seem like something that could be generally useful outside of
a `JoinMap` implementation
This branch adds a `tokio::task::Id` type that uniquely identifies a
task relative to all other spawned tasks. Task IDs are assigned
sequentially based on an atomic `usize` counter of spawned tasks.
In …
> task: add task IDs

- .cargo/config
- README.md
- tokio-util/Cargo.toml
- tokio-util/src/task/join_map.rs
- tokio-util/src/task/mod.rs
- tokio-util/tests/task_join_map.rs
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/runtime/task/abort.rs
Depends on #4630.
In many cases, it is desirable to spawn a set of tasks associated with
keys, with the ability to cancel them by key. As an example use case for
this sort of thing, see Tower's [`ReadyCache` type][1].
Now that PR #4530 adds a way of cancelling tasks in a
`tokio::task::JoinSet`, we can implement a map-like API based on the
same `IdleNotifiedSet` primitive.
This PR adds an implementation of a `JoinMap` type to
`tokio_util::task`, using the `JoinSet` type from `tokio::task`, the
`AbortHandle` type added in #4530, and the new task IDs added in #4630.
Individual tasks can be aborted by key using the `JoinMap::abort`
method, and a set of tasks whose key match a given predicate can be
aborted using `JoinMap::abort_matching`.
When tasks complete, `JoinMap::join_one` returns their …
> util: implement `JoinMap`

- tokio/CHANGELOG.md
This release adds a number of new APIs in `tokio::net`, `tokio::signal`, and
`tokio::sync`. In addition, it adds new unstable APIs to `tokio::task` (`Id`s
for uniquely identifying a task, and `AbortHandle` for remotely cancelling a
task), as well as a number of bugfixes.
- blocking: add missing `#[track_caller]` for `spawn_blocking` ([#4616])
- macros: fix `select` macro to process 64 branches ([#4519])
- net: fix `try_io` methods not calling Mio's `try_io` internally ([#4582])
- runtime: recover when OS fails to spawn a new thread ([#4485])
- macros: support setting a custom crate name for `#[tokio::main]` and
`#[tokio::test]` ([#4613])
- net: add `UdpSocket::peer_addr` ([#4611])
- net: add `try_read_buf` method for named pipes ([#4626])
- signal: add `SignalKind` `Hash`/`Eq` impls and …
> tokio: prepare to release v1.18.0

- tests-build/tests/fail/macros_core_no_default.stderr
- tests-build/tests/fail/macros_dead_code.stderr
- tests-build/tests/fail/macros_invalid_input.rs
- tests-build/tests/fail/macros_invalid_input.stderr
- tests-build/tests/fail/macros_type_mismatch.rs
- tests-build/tests/fail/macros_type_mismatch.stderr
- tokio-macros/src/entry.rs
Fixes #4635
There are two approaches, each divided into commits to compare.
The first commit is the `let () =` approach mentioned in https://github.com/tokio-rs/tokio/issues/4635#issuecomment-1107684720, which fixes #4635 while maintaining the current diagnostics. However, the diagnostics for #4635's case are not very good.
The second commit is a greatly simplified version of the current approach. There is small diagnostics regression, but it improves somewhat for #4635's case.
I tend to prefer the second one, but if other reviewers prefer the first one, I can revert the second commit.
> macros: always emit return statement

- .github/workflows/ci.yml
- Cross.toml
- tokio/src/loom/std/atomic_u64.rs
- tokio/src/runtime/metrics/io.rs
> Use mocked AtomicU64 in IO metrics driver

- tokio-util/src/lib.rs
- tokio-util/src/udp/frame.rs
We are auditing a tokio update in https://fuchsia-review.googlesource.com/c/fuchsia/+/611683, and we thought it would save other auditors time if we documented and shrunk down some `unsafe {}` blocks.
This documents why it is safe to convert `bytes::UninitSlice` to `&mut [MaybeUninit<u8>]`, and shrinks one of the unsafe blocks to make these functions easier to audit.
This also removes an out of date comment around converting a `&mut [MaybeUninit<u8>]` to a `&mut [u8]`, which predated the conversion over to `ReadBuf`, and is no longer applicable to the code.
> Document and shrink some unsafe blocks in tokio-util

- tokio/src/macros/join.rs
- tokio/src/macros/try_join.rs
- tokio/tests/macros_join.rs
- tokio/tests/macros_try_join.rs
Fixes: https://github.com/tokio-rs/tokio/issues/4612
Since `tokio::join!` runs the futures in the same task, the futures were are the same budget which makes it possible for one future to consume the whole budget leaving nothing for the other futures to consume.
Starvation example taken from #4612
```rust
use std::{sync::Arc, time::Duration};
use tokio::sync::Semaphore;
#[tokio::main]
async fn main() {
let permits = Arc::new(Semaphore::new(10));
tokio::join!(non_cooperative_task(permits), poor_little_task());
}
async fn non_cooperative_task(permits: Arc<Semaphore>) {
loop {
let permit = permits.clone().acquire_owned().await.unwrap();
// uncommenting the following makes it work
// tokio::time::sleep(Duration::from_millis(1)).await;
}
}
async fn poor_little_task() {
loop { …
```
> macros: join! start by polling a different future each time poll_fn is polled

- tokio/Cargo.toml
Switching from winapi to windows-sys in mio means that the `std` feature of winapi is no longer enabled when compiling Tokio on windows. However, in this case, the `c_void` type is not the same as the `c_void` type in the standard library, which causes some compiler errors in various places.
(The first commit to this PR does not add the feature to verify that CI catches the issue when its not fixed.)
Closes: #4662
> windows: add feature std for winapi

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
Add missing features for the `winapi` dependency. ([#4663])
[#4663]: https://github.com/tokio-rs/tokio/pull/4663
> Prepare tokio 1.18.2

- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- tokio/README.md
In #4675 I learnt the hard way that Tokio uses Clippy on its MSRV. 
Document this in the contributor's guide.
> docs: mention that Clippy must be run with the MSRV

- tokio/src/io/driver/metrics.rs
- tokio/src/io/driver/mod.rs
- tokio/src/macros/cfg.rs
> metrics: fix compilation with unstable, process, and rt

- tokio-util/src/sync/reusable_box.rs
- tokio-util/tests/reusable_box.rs
`ReusableBoxFuture` is currently complex-ish, with `unsafe` code and types in multiple places.
Move all the `unsafe`ty into a single function `reuse_pin_box` (and a helper type). I think this makes the definition of `ReusableBoxFuture` a bit simpler, and I'm pretty sure that it's sound. The function has the signature:
```rs
fn reuse_pin_box<T: ?Sized, U, O, F>(boxed: Pin<Box<T>>, new_value: U, callback: F) -> Result<O, U>
where
F: FnOnce(Box<U>) -> O,
```
It encapsulates the basic premise of `ReusableBoxFuture` — a `Box` that can be reused — and `ReusableBoxFuture` is then implemented on top of it. It accepts a callback instead of returning `Result<Box<U>, O>` so that code can be run even if dropping the old `T` fails.
> util: implement `ReusableBoxFuture` with one function

- tokio-util/Cargo.toml
Currently, the new `JoinMap` introduced by [#4640] would not be visible on [docs.rs] because we don't enable unstable features.
[#4640]: https://github.com/tokio-rs/tokio/pull/4640
[docs.rs]: https://docs.rs/tokio-util/
> Display JoinMap on docs.rs

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
Merges changelog changes from #4691 and #4690 into master with a merge commit.
> Merge tokio-util 0.7.2

- .github/workflows/ci.yml
- tokio/tests/io_read.rs
- tokio/tests/io_take.rs
- tokio/tests/rt_common.rs
- tokio/tests/support/leaked_buffers.rs
LLVM's ASAN is a very useful tool to find memory leaks, and it is built-in for the rust nightly compier.
When I ran it on my local computer, there were several memory leaks detected in the tests.
According to the LLVM docs, ASAN does not produce false positives.
Sadly, ASAN is not yet enabled in the CI.
> Enable ASAN in CI

- tokio-util/src/task/join_map.rs
- tokio/src/task/join_set.rs
Currently, the various spawning methods on `tokio::task::JoinSet` and
`tokio_util::task::JoinMap` lack `#[track_caller]` attributes, so the
`tracing` spans generated for tasks spawned on `JoinSet`s/`JoinMap`s
will have the `JoinSet` spawning method as their spawn location, rather
than the user code that called that method.
This PR fixes that by...adding a bunch of `#[track_caller]` attributes.
In the future, we may also want to consider adding additional data to
the task span indicating that the task is spawned on a `JoinSet`...
> task: add `#[track_caller]` to `JoinSet`/`JoinMap`

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/builder.rs
- tokio/src/runtime/thread_pool/mod.rs
- tokio/src/runtime/thread_pool/worker.rs
Closes #4651
Some workloads strongly benefit from changing the scheduler constants that control:
* Global queue polling
* Event polling (the driver: timer, process, and I/O events)
Adds knobs to the runtime builder to control the number of ticks between polling the global task queue (fairness) and the event driver (I/O prioritization). The default values for these knobs are determined based on what scheduler kind the builder is started with.
Both varieties of scheduler already supported these intervals, but they were defined by private constants. This PR moves the constants into the `Core` struct, where they can be supplied by the builder configuration.
> Make global queue and event polling intervals configurable

- tokio/src/io/driver/mod.rs
- tokio/src/io/driver/registration.rs
- tokio/src/runtime/metrics/runtime.rs
Fix https://github.com/tokio-rs/tokio/issues/4509
The cycle is broken by making sure nobody can register a new io resources on shutdown and by emptying the driver.
> io: Refactor out usage of Weak in the io handle

- tests-build/tests/fail/macros_dead_code.stderr
- tests-build/tests/fail/macros_invalid_input.stderr
- tests-build/tests/fail/macros_type_mismatch.stderr
Rust version 1.61.0 was just released, and it comes with some changes to how errors are formatted.
> chore: update macro output tests for 1.61.0

- tokio/Cargo.toml
Fix RUSTSEC-2020-0095(#4012)
Bump mockall version to 0.11
> chore: fix cargo audit warning

- tokio/src/lib.rs
I was for a moment irritated when reading the "Working with Tasks" because only 3 channel types were listed there.
List the `broadcast` channel type there too.
> Add broadcast to list of channel types

- tokio/src/time/interval.rs
Hi there! While looking at the [docs for MissedTickBehavior](https://docs.rs/tokio/1.18.2/tokio/time/enum.MissedTickBehavior.html#variant.Burst), I noticed that the comments in the code example have a very small error.
```rust
use tokio::time::{interval, Duration};
let mut interval = interval(Duration::from_millis(50));
task_that_takes_200_millis().await;
// The `Interval` has missed a tick
// Since we have exceeded our timeout, this will resolve immediately
interval.tick().await;
// Since we are more than 100ms after the start of `interval`, this will
// also resolve immediately.
interval.tick().await;
// Also resolves immediately, because it was supposed to resolve at
// 150ms after the start of `interval`
interval.tick().await;
// Resolves immediately
interval.tick().await;
// Since we …
```
> docs: correct example in MissedTickBehavior::Burst

- tokio-stream/src/stream_ext.rs
- tokio-stream/src/stream_ext/next.rs
- tokio-stream/src/stream_ext/try_next.rs
Many futures are commonly used in `select!` (or similar) constructs, and people are interested to know which futures are cancel-safe. Two such common features are `next` and `try_next`, to get new values from a `Stream`. These only hold onto references to the underlying stream, and are therefor cancel-safe.
Document the cancel-safety of the `StreamExt::next` and `StreamExt::try_next` methods (and their underlying future types)
> docs: add cancel-safety docs to StreamExt::next methods and types

- tokio/src/sync/broadcast.rs
- tokio/src/sync/tests/loom_broadcast.rs
- tokio/tests/sync_broadcast.rs
Add subscribe method to broadcast::Receiver with the same functionality as the clone impl removed in #3020.
> WIP: Add resubscribe functionality to broadcast::Receiver

- tokio/src/runtime/metrics/io.rs
Updating an atomic variable with a load followed by a store is racy.  It
defeats the entire purpose of using atomic variables, and can result in
"lost" updates.  Instead, use fetch_add .
Avoid inaccurate metrics due to update races.
Always use atomic instructions to update atomic variables.
> Correctly update atomics in IoDriverMetrics

- tokio/src/task/consume_budget.rs
- tokio/src/task/mod.rs
- tokio/tests/rt_common.rs
For cpu-only computations that do not use any Tokio resources, budgeting does not really kick in in order to yield and prevent other tasks from starvation. One way to take part in budgeting is to use a Tokio resource, but some workloads simply don't need any, as they just need to compute a lot and occasionally  yield in order to keep latencies low (e.g. a Wasm engine).
The new mechanism - `task::consume_budget`, performs a budget check and consumes a unit of it as if a Tokio resource was used (except it wasn't, so it's cheaper) and yields only if the task exceeded the budget. That allows cpu-intenstive computations to define yield points that yield only conditionally, since unconditional yielding to runtime is a potentially heavy operation.
> Add task::consume_budget util for cooperative scheduling

- tokio-util/src/task/join_map.rs
- tokio/src/runtime/tests/loom_join_set.rs
- tokio/src/task/join_set.rs
- tokio/tests/task_join_set.rs
We agreed in #4535 to change the return value of `JoinSet::join_one`. This PR makes that change.
This is an unstable API, so changing it is okay.
> task: update return value of `JoinSet::join_one`

- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/join.rs
add `is_finished` method for `JoinHandle` and `AbortHandle` .
Close #4707
Check task's state is whether `COMPLETE` or `CANCELLED`.
> chore(runtime): add `is_finished` method for `JoinHandle` and `AbortHandle`

- tokio/src/future/poll_fn.rs
- tokio/src/io/util/vec_with_initialized.rs
- tokio/src/net/addr.rs
This fixes the following clippy warnings. (They don't appear in CI because CI uses an older clippy.)
```text
warning: this expression borrows a value the compiler would automatically borrow
--> tokio/src/future/poll_fn.rs:38:9
|
38 |         (&mut self.f)(cx)
|         ^^^^^^^^^^^^^ help: change this to: `self.f`
|
= note: `#[warn(clippy::needless_borrow)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
warning: methods called `is_*` usually take `self` by reference or no `self`
--> tokio/src/io/util/vec_with_initialized.rs:67:28
|
67 |     pub(crate) fn is_empty(&mut self) -> bool {
|                            ^^^^^^^^^
|
= note: `#[warn(clippy::wrong_self_convention)]` on by default
= help: consider choosing …
```
> chore: fix clippy warnings

- tokio/src/sync/notify.rs
Found some `if let` statements that don't actually bind any variables. This can make it somewhat confusing as to whether the pattern is binding the value or being matched against (note that irrefutable `if let` patterns are flagged by clippy).
Switching to `matches!` and equality comparisons allow these to be removed.
> Replace non-binding `if let` statements

- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
When manually creating a `TcpSocket` or `TcpStream` e.g. via `tokio::net::TcpStream::try_from` one should be able to check for errors after awaiting the connection to be writable (`writable()`) before assuming the connection to be successfully established.
This is needed e.g. in rust-libp2p, see https://github.com/libp2p/rust-libp2p/pull/2458.
The first commit reintroduces https://github.com/tokio-rs/tokio/pull/4364 which first merged but later on reverted in https://github.com/tokio-rs/tokio/pull/4392. See also https://github.com/tokio-rs/tokio/pull/4392#issuecomment-1035542164.
The second commit adds the same method to `TcpStream`.
Tagging @taiki-e as the initial author.
> net: Add `take_error` to `TcpSocket` and `TcpStream`

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- runtime: add `is_finished` method for `JoinHandle` and `AbortHandle` ([#4709])
- runtime: make global queue and event polling intervals configurable ([#4671])
- sync: add `Notified::enable` ([#4705])
- sync: add `watch::Sender::send_if_modified` ([#4591])
- sync: add resubscribe method to broadcast::Receiver ([#4607])
- io: refactor out usage of Weak in the io handle ([#4656])
- macros: avoid starvation in `join!` and `try_join!` ([#4624])
- runtime: clarify semantics of tasks outliving `block_on` ([#4729])
- time: fix example for `MissedTickBehavior::Burst` ([#4713])
- metrics: correctly update atomics in `IoDriverMetrics` ([#4725])
- metrics: fix compilation with unstable, process, and rt, but without net ([#4682])
- task: add `#[track_caller]` to `JoinSet`/`JoinMap` ([#4697])
- task: …
> chore: prepare Tokio v1.19.0

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
- tracing: don't require default tracing features ([#4592])
- util: simplify implementation of `ReusableBoxFuture` ([#4675])
- task: add `JoinMap` ([#4640], [#4697])
[#4592]: https://github.com/tokio-rs/tokio/pull/4592
[#4640]: https://github.com/tokio-rs/tokio/pull/4640
[#4675]: https://github.com/tokio-rs/tokio/pull/4675
[#4697]: https://github.com/tokio-rs/tokio/pull/4697
> chore: prepare tokio-util 0.7.3

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio/CHANGELOG.md
- macros: always emit return statement ([#4636])
- macros: support setting a custom crate name for `#[tokio::main]` and `#[tokio::test]` ([#4613])
[#4613]: https://github.com/tokio-rs/tokio/pull/4613
[#4636]: https://github.com/tokio-rs/tokio/pull/4636
> chore: prepare tokio-macros 1.8.0

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
- deps: upgrade `tokio-util` dependency to `0.7.x` ([#3762])
- stream: add `StreamExt::map_while` ([#4351])
- stream: add `StreamExt::then` ([#4355])
- stream: add cancel-safety docs to `StreamExt::next` and `try_next` ([#4715])
- stream: expose `Elapsed` error ([#4502])
- stream: expose `Timeout` ([#4601])
- stream: implement `Extend` for `StreamMap` ([#4272])
- sync: add `Clone` to `RecvError` types ([#4560])
[#3762]: https://github.com/tokio-rs/tokio/pull/3762
[#4272]: https://github.com/tokio-rs/tokio/pull/4272
[#4351]: https://github.com/tokio-rs/tokio/pull/4351
[#4355]: https://github.com/tokio-rs/tokio/pull/4355
[#4502]: https://github.com/tokio-rs/tokio/pull/4502
[#4560]: https://github.com/tokio-rs/tokio/pull/4560
[#4601]: https://github.com/tokio-rs/tokio/pull/4601
[#4715]: …
> chore: prepare tokio-stream 0.1.9

- tokio/src/sync/notify.rs
- tokio/tests/sync_notify.rs
> sync: fix panic in `Notified::enable`

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release fixes a bug in `Notified::enable`. ([#4747])
[#4747]: https://github.com/tokio-rs/tokio/pull/4747
> chore: prepare Tokio v1.19.1

- tokio/src/sync/notify.rs
- tokio/tests/sync_notify.rs
This fixes a bug introduced by #4747.
The `will_wake` function is really tricky :(
> sync: fix `will_wake` usage in `Notify`

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release fixes another bug in `Notified::enable`. ([#4751])
[#4751]: https://github.com/tokio-rs/tokio/pull/4751
> chore: prepare Tokio v1.19.2

- tokio-util/src/task/join_map.rs
- tokio-util/tests/task_join_map.rs
- tokio/src/runtime/tests/loom_join_set.rs
- tokio/src/task/join_set.rs
- tokio/tests/async_send_sync.rs
- tokio/tests/task_join_set.rs
After some discussion and usage, several people including myself agreed that `join_one` is better named as `join_next`. Once `AsyncIterator` is stabilized, `AsyncIterator::next` can delegate to `JoinSet::join_next`.
> joinset: rename `join_one` to `join_next`

- tokio-macros/src/lib.rs
Improved documentation for #[tokio::test] to mirror the #[tokio::main] one
Fixing issue #4720 
Mirrored the #[tokio::main] documentation + explained that each test gets a separate current-thread runtime.
> Improve the documentation for #[tokio::test]

- .circleci/config.yml
- tokio-stream/src/stream_ext.rs
- tokio-util/src/codec/decoder.rs
- tokio-util/src/io/stream_reader.rs
- tokio/CHANGELOG.md
- tokio/src/park/mod.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/sync/barrier.rs
- tokio/src/sync/mpsc/chan.rs
- tokio/src/time/timeout.rs
- tokio/tests/rt_metrics.rs
Signed-off-by: Richard Zak <richard@profian.com>
Looking at the code, I found a few spelling mistakes with the in-line documentation.
Spelling mistakes fixed.
> chore: fix spelling

- tokio/Cargo.toml
be more specific about winapi features (#4737)
add  `winapi/std` dependency in `net` feature, remove features in `dependencies.winapi`.
Below run all OK on my windows 10 PC
```
cargo build --all-features
cargo check --all-features
cargo test --all-features
```
> net: be more specific about winapi features

- tokio/src/runtime/basic_scheduler.rs
- tokio/src/runtime/builder.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/task/local.rs
- tokio/tests/rt_basic.rs
- tokio/tests/task_local_set.rs
This is a rebased version of #4518.
Allows the user to configure the runtime's behavior when a spawned task
panics. Currently, the panic is propagated to the JoinHandle and the
runtime resumes. This patch lets the user set the runtime to shutdown on
unhandled panic.
So far, this is only implemented for the current-thread runtime and is flagged as unstable. The intent is
to build this incrementally and track outstanding questions and issues.
Refs: #4516
> rt: unhandled panic config for current thread rt

- tokio-util/src/task/mod.rs
- tokio-util/src/task/spawn_pinned.rs
- tokio-util/tests/spawn_pinned.rs
Adds some functionality to `LocalPoolHandle` and tries to improve existing docs.
Fixes https://github.com/tokio-rs/tokio/issues/4661
> Improve LocalPoolHandle

- tokio/src/sync/oneshot.rs
- tokio/tests/sync_oneshot.rs
This change is motivated by #4776.
> sync: document spurious failures in oneshot

- tokio/src/runtime/tests/loom_join_set.rs
```bash
LOOM_MAX_PREEMPTIONS=1 RUSTFLAGS="--cfg loom"  cargo test --lib --release --features full -- --test-threads=1 --nocapture
```
The command should be working without tokio_unstable RUSTFLAGS
> joinset: fix loom test without tokio_unstable

- tokio/src/time/clock.rs
- tokio/src/time/driver/handle.rs
- tokio/src/time/driver/sleep.rs
- tokio/tests/time_panic.rs
When a user of tokio calls a function that panics when misused (e.g. calling
`time::interval` with 0 duration) then the user currently sees the line number
of the panic call inside tokio. It would be more informative for the user to see
the place where they called the panicking function.
hidden.
This change is the 4th in a series towards closing #4413 (starting with #4772),
this change is for the time functions in the main `tokio` crate.
Functions that may panic can be annotated with #[track_caller] so that
panicking function is shown instead of the file and line within Tokio
source. …
> time: add track_caller to public APIs

- tokio/src/io/async_fd.rs
- tokio/src/io/driver/mod.rs
- tokio/src/io/read_buf.rs
- tokio/src/io/split.rs
- tokio/tests/io_panic.rs
- tokio/tests/rt_panic.rs
- tokio/tests/support/panic.rs
- tokio/tests/time_panic.rs
When a user of tokio calls a function that panics when misused (e.g. trying to unsplit
a ReadHalf and WriteHalf that don't match) then the user currently sees the line
number of the panic call inside tokio. It would be more informative for the user to see
the place where they called the panicking function.
hidden.
This change is the 4th in a series towards closing #4413 (starting with #4772),
this change is for the time functions in the main tokio crate.
Functions that may panic can be annotated with #[track_caller] so that
panicking function is shown instead of the file and line within …
> io: add track_caller to public APIs

- .github/workflows/ci.yml
CI is running into https://github.com/cross-rs/cross/issues/724, which should be fixed if we clear the cache.
> chore: disable caching for cross jobs

- tokio/src/fs/read_dir.rs
Found typo in `read_dir` doc.
Remove typo :)
> chore: fix typo

- tests-integration/Cargo.toml
- tests-integration/src/bin/test-cat.rs
- tests-integration/tests/process_stdio.rs
This fixes #4801, where, as a result of https://github.com/rust-lang/rust/pull/95469, our implementation of cat used for this test no longer works, as stdio functions on windows now can abort the process if the pipe is set to nonblocking mode.
Unfortunately in windows, setting one end of the pipe to be nonblocking makes the whole thing nonblocking, so when, in tokio::process we set the child pipes to nonblocking mode, it causes serious problems for any rust program at the other end.
Fixing this issue is for another day, but fixing the tests is for today.
> tests: alter integration tests for stdio to not use a handrolled cat implementation

- tokio/src/signal/unix.rs
- tokio/src/signal/unix/driver.rs
- tokio/tests/signal_panic.rs
When a user of tokio calls a function that panics when misused (e.g. calling
`signal()` without having an IO driver enabled in the surrounding tokio runtime)
then the user currently sees the line number of the panic call inside tokio. It
would be more informative for the user to see the place where they called the
panicking function.
hidden.
This change is the 6th in a series towards closing #4413 (starting with #4772),
this change is for the signal functions in the main tokio crate.
Functions that may panic can be annotated with #[track_caller] so that
panicking function is shown …
> signal: add track_caller to public APIs

- tokio/src/future/block_on.rs
- tokio/src/runtime/enter.rs
- tokio/src/sync/broadcast.rs
- tokio/src/sync/mpsc/bounded.rs
- tokio/src/sync/mpsc/unbounded.rs
- tokio/src/sync/mutex.rs
- tokio/src/sync/oneshot.rs
- tokio/src/sync/rwlock.rs
- tokio/tests/sync_panic.rs
When a user of tokio calls a function that panics when misused (e.g. calling
`Mutex::blocking_lock()` from within a tokio runtime) then the user currently
sees the line number of the panic call inside tokio. It would be more informative
for the user to see the place where they called the panicking function.
hidden.
This change is the 7th in a series towards closing #4413 (starting with #4772),
this change is for the sync functions in the main tokio crate.
Functions that may panic can be annotated with `#[track_caller]` so that
panicking function is shown instead of the file and line …
> sync: add track_caller to public APIs

- .github/workflows/ci.yml
- tests-integration/Cargo.toml
- tests-integration/tests/macros_main.rs
- tests-integration/tests/rt_yield.rs
Currently, we only have WASM regression tests that run without WASI.
However, rust provides a WASI specific target which enables code to
special case WASI. This PR adds a basic test to cover that case.
This is an initial addition to help land tokio-rs/tokio#4716.
> chore: add a regression test for WASI

- .github/workflows/ci.yml
It would seem that the latest nightly is having issues, so I went with the one from yesterday (2022-7-10).
> chore: fix ci by hard-coding nightly version for miri

- tokio/src/runtime/blocking/mod.rs
- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/handle.rs
- tokio/src/task/builder.rs
- tokio/src/task/join_set.rs
- tokio/tests/task_builder.rs
Tokio's current stable `spawn*` methods are all infallible but may internally panic on unrecoverable errors (for example, if the blocking threadpool is empty and the OS refuses to spawn additional threads). Unfortunately, this means that applications cannot opt-into gracefully handling such situations.
Convert all `task::Builder::spawn*` methods to return a fallible `io::Result<_>`, giving applications the opportunity to opt-into handling spawn errors themselves. This also is a fitting analogue to `std::thread::Builder` which also has fallible spawn methods (contrasted with `std::thread::spawn` which panic on failure).
Given that the `task::Builder` and its APIs are currently marked as unstable, this is a good time to make the change before we start stabilizing them. Currently …
> Make `task::Builder::spawn*` methods fallible

- tokio/src/task/blocking.rs
I was looking at these docs again and I was thinking the
"cannot be cancelled" is misleading; let's talk about approaches
to do so.
> `spawn_blocking`: Expand on cancellation a bit

- .github/workflows/ci.yml
This reverts [#4825], as miri seems to be working again on the latest nightly.
I had originally thought it was this issue with rustup which was to blame, but this seems to be wrong: https://github.com/rust-lang/rustup/issues/3031
[#4825]: https://github.com/tokio-rs/tokio/pull/4825
> chore: allow miri to use latest nightly once again

- tokio/build.rs
- tokio/src/io/driver/scheduled_io.rs
- tokio/src/macros/addr_of.rs
- tokio/src/macros/mod.rs
- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/sync/batch_semaphore.rs
- tokio/src/sync/broadcast.rs
- tokio/src/sync/notify.rs
- tokio/src/time/driver/entry.rs
- tokio/src/util/idle_notified_set.rs
Tokio uses temporary references in implementations of `Link` when mapping between a raw pointer for a struct, and a raw pointer for a field. This causes all sorts of miri-related issues. This PR avoids that.
> tokio: avoid temporary references in Link impls

- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/list.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/raw.rs
This PR moves the `owned` field from the task header to the trailer. 
**Motivation.** Various other PRs have run into trouble with the header not having enough space to add new fields. This PR exists to make more space in the header for those other PRs.
**Why is this ok?** The purpose of the trailer is to store fields only needed during shutdown of the task, and the `owned` field is only accessed during shutdown (and creation) of tasks, and during shutdown of the runtime. Thus, it is only rarely accessed. This makes it ok to store the field in cold memory.
> runtime: move owned field to Trailer

- tokio/Cargo.toml
- tokio/src/net/windows/named_pipe.rs
Allow requesting security permission changes for named pipes. 
Add methods to named_pipe::ServerOptions to set the required bits.
Fixes #4844
> net: Add security flags to ServerOptions

- tokio/src/runtime/mod.rs
- tokio/src/task/local.rs
- tokio/src/task/task_local.rs
- tokio/tests/task_panic.rs
When a user of tokio calls a function that panics when misused (e.g. calling
`spawn()` from outside a tokio runtime) then the user currently
sees the line number of the panic call inside tokio. It would be more informative
for the user to see the place where they called the panicking function.
hidden.
This change is the 8th in a series towards closing #4413 (starting with #4772),
this change is for the functions in the task module in the main tokio crate.
Functions that may panic can be annotated with `#[track_caller]` so that
panicking function is shown instead of the file and line …
> task: add track_caller to public APIs

- tokio/src/io/driver/mod.rs
A single case was missed in the original PR #4793, which is where the `rt`
feature is not enabled. This case cannot be tested (because tests run with
all features enabled), but it's worth adding the `#[track_caller]` attribute
anyway.
This change adds a case that was missing from the original PR, #4793.
The `io::driver::Handle::current` function was only covered by
`#[track_caller]` in the case that the `rt` feature  is enabled, however
it was missing in the case that the `rt` feture isn't enabled (in which
case a panic would be more common).
This particular case cannot be tested in the tokio tests as they always
run with all features enabled.
Refs: #4413
> io: add track_caller caller to no-rt io driver

- tokio/Cargo.toml
- tokio/src/io/blocking.rs
- tokio/src/io/poll_evented.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/src/process/mod.rs
- tokio/src/process/unix/mod.rs
- tokio/src/process/windows.rs
- tokio/src/runtime/builder.rs
- tokio/src/runtime/handle.rs
We can't mix async pipes and child process stdio on Windows. This switches our Windows process implementation to use the blocking threadpool instead of using an async named pipe as we did in the past.
Refs #4802
> process: use blocking threadpool for child stdio I/O

- tokio/src/runtime/builder.rs
The documentation for the function `Builder::worker_threads` states that if it is used
with `current_thread` runtime it will panic. However it doesn't panic, it appears to
ignore the value set by the call instead.
Documentation:
https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.worker_threads
While this is probably not going to catch a lot of people out, it would be better if it
was correct.
Also, this function documentation had 2 `Panics` sections in it. 🤷‍♀️
The documentation for the runtime `Builder::worker_threads` function
incorrectly stated that it would panic if used when constructing a
`current_thread` runtime. In truth, the call to the function has no
effect.
Since adding the described panic to the code could cause new panics in
existing code using tokio, the …
> doc: remove incorrect panic section for Builder::worker_threads

- tests-integration/Cargo.toml
- tests-integration/src/bin/test-cat.rs
- tests-integration/tests/process_stdio.rs
Now that the issue has been resolved with doing async I/O with child processes, we can revert our testing `cat` process to using blocking I/O as before (i.e. test how most child processes would handle I/O by default)
Fixes #4802
> process: revert test_cat to use blocking I/O

- tokio/build.rs
- tokio/src/macros/thread_local.rs
- tokio/src/task/task_local.rs
Currently, Tokio does not compile on some nightly releases such as 2021-12-05. This is due to how our version detection is implemented. This PR fixes that.
Additionally, the cfg flag is inverted. The motivation for doing this is that it makes it possible to disable the feature by passing `RUSTFLAGS="--cfg tokio_no_const_thread_local"` even if you are using a compiler that supports it.
This PR replaces #4859
> chore: fix version detection in build script

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/build.rs
- tokio/src/macros/thread_local.rs
- tokio/src/task/task_local.rs
- chore: fix version detection in build script ([#4860])
[#4860]: https://github.com/tokio-rs/tokio/pull/4860
> Prepare tokio 1.20.1

- tokio/build.rs
This fixes the version detection for `addr_of!` introduced by #4841. Currently, it causes compile failures on some specific nightly versions of rustc.
This change is submitted separately from #4860 because that PR was building on top of `tokio-1.20.x`, which is from before the `addr_of!` version detection was merged.
> chore: fix version detection for `addr_of`

- tokio/src/io/driver/registration.rs
- tokio/src/io/poll_evented.rs
As the [epoll documentation points out](https://man7.org/linux/man-pages/man7/epoll.7.html), a read that only partially fills a buffer is sufficient to show that the socket buffer has been drained.
We can take advantage of this by clearing readiness in this case, which seems to significantly improve performance under certain conditions.
> io: reduce syscalls in poll_read

- tokio/Cargo.toml
- tokio/src/coop.rs
- tokio/src/io/driver/registration.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/sync/tests/atomic_waker.rs
- tokio/src/sync/tests/notify.rs
- tokio/src/sync/tests/semaphore_batch.rs
- tokio/src/util/linked_list.rs
- tokio/tests/_require_full.rs
- tokio/tests/macros_join.rs
- tokio/tests/macros_pin.rs
- tokio/tests/macros_select.rs
- tokio/tests/macros_try_join.rs
- tokio/tests/sync_barrier.rs
- tokio/tests/sync_broadcast.rs
- tokio/tests/sync_errors.rs
- tokio/tests/sync_mpsc.rs
- tokio/tests/sync_mutex.rs
- tokio/tests/sync_mutex_owned.rs
- tokio/tests/sync_notify.rs
- tokio/tests/sync_oneshot.rs
- tokio/tests/sync_rwlock.rs
- tokio/tests/sync_semaphore.rs
- tokio/tests/sync_semaphore_owned.rs
- tokio/tests/sync_watch.rs
According to [this comment](https://github.com/tokio-rs/tokio/pull/4716#issuecomment-1182471863), this is the correct way to check for wasm.
> chore: use target_family wasm instead of wasm32

- .github/workflows/labeler.yml
- .github/workflows/loom.yml
Workflows can run on forks. While github defaults to not running scheduled tasks on forks, even those will at times...
* The Loom workflow is incredibly expensive, and it will probably run when a fork updates to the latest master.
* The labeler workflow will run if a user creates a PR into their own fork. (I do this regularly.) The odds are that these forks don't need/want this workflow to run.
Limit the loom&labeler workflows to only run on the tokio-rs/tokio repository.
Note: I'm not skipping the stress test workflow, that seems to be sufficiently fast and interesting that a developer might want it to run in a fork.
> Scope workflows

- benches/sync_rwlock.rs
- tokio/src/sync/mutex.rs
- tokio/src/sync/rwlock/read_guard.rs
- tokio/src/sync/rwlock/write_guard.rs
- tokio/tests/sync_mutex.rs
- tokio/tests/sync_panic.rs
- tokio/tests/sync_rwlock.rs
> Add #[must_use] to lock guards

- CONTRIBUTING.md
When I submitted my first PR I followed the contribution guide, but still had it fail
on the clippy job because I hadn't run clippy on my tests locally (because I just
copy-pasted the commands and it didn't include the `--tests` flag). It's been at the
back of my mind since and so I finally created a PR to update the contribution guide.
The contribution guide describes the Tokio code of conduct and gives a
list of steps to follow when contributing in different ways. In the
guide to contributing a pull request, commands are listed to be run by
the contributor locally to help ensure that the PR will pass on CI.
The command to run clippy isn't the same as the one run on CI,
specifically it the command doesn't check the tests. This commit changes
the command to match the one on CI, so that …
> doc: update clippy command in contribution guide

- tokio/src/net/tcp/socket.rs
- tokio/src/net/udp.rs
Currently, tokio cannot bind a socket to a specific device, which is sometimes useful on platforms like Linux.
Add two wrapper methods `device()` `bind_device(Option<&[u8]>)` to make use of the ability of `socket2`.
doc and cfg also come from `socket2`
> net: add device and bind_device methods to TCP/UDP sockets

- tokio/src/io/util/async_seek_ext.rs
There are double `to`'s in `AsyncSeekExt::rewind`'s docs
Remove a single `to` from the docs
> Only use a single `to` in `AsyncSeekExt::rewind`'s documentation

- tokio/src/signal/unix/driver.rs
- tokio/tests/rt_metrics.rs
Our signal driver over-zealously subscribes to write readiness for the pipe used to wake when signals are delivered.
Only register for read-readiness.
Fixes #4895
> signal: don't register write interest on signal pipe

- tokio/src/fs/file.rs
- tokio/src/fs/file/tests.rs
Following https://github.com/tokio-rs/tokio/issues/4875#issuecomment-1210653815 this PR changes the panic in `File`'s `AsyncSeek` implementation to an error. 
The panic is changed to an error.
I only managed to reproduce the panic with the specific example using a `BufReader<File>` as provided in #4875, the added test also uses a BufReader and panics without the change to `File`'s seek impl.
---
I raised a question regarding inconsistent behavior between AsyncSeek impls for BufReader / BufWriter in #4875
> Change panic on seeking busy file to error.

- tokio/src/sync/semaphore.rs
Fixes #4891 which mentions this change is required to eventually update clippy
Removes the unused lifetime parameter on the impl block for `SemaphorePermit::drop`
----
~~Recent clippy versions also emit numerous warnings for https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const but should probably be tracked & fixed in a different issue~~
https://github.com/tokio-rs/tokio/issues/4872 tracks this already and it's false positives
> Remove unused lifetime on Semaphore impl

- tokio/src/runtime/task/join.rs
> task: add cancel safety docs to `JoinHandle`

- tests-build/README.md
- tests-build/tests/fail/macros_core_no_default.stderr
- tests-build/tests/fail/macros_dead_code.stderr
The 1.63.0 release of rustc changed the output of some errors. This PR fixes our CI to reflect that.
> ci: fix new error output from rustc 1.63.0

- README.md
- tokio/README.md
People sometimes look for Tokio's changelog in the root directory, but can't find it because it's stored in the `tokio` subdirectory. 
This PR adds links to make the changelogs more easily discoverable.
> docs: add changelog links to readme

- .github/workflows/ci.yml
The current nightly (2022-04-18) used in CI leads to an ICE when producing rustdoc JSON for Tokio. The rustdoc JSON output is required to successfully add `cargo-check-external-types` to CI for #4902.
Upgrade the nightly to a version that works with all of miri, cargo-hack, minimal-versions, and cargo-check-external-types.
Note: I wasn't able to test the `asan` CI step locally since I'm not on the right CPU architecture, so that may fail when CI runs for the PR. The others seemed to work locally.
> ci: upgrade nightly to `nightly-2022-07-25`

- .github/workflows/ci.yml
As discovered in #4914, the `miri` CI check wasn't pinned to a specific nightly, and the nightly chosen in #4903 didn't have a `miri` component.
This PR pins the `miri` check to the `rust_nightly` env value and updates the nightly to a version that is compatible with everything else.
> ci: upgrade to `nightly-2022-07-26` and pin `miri` nightly

- tokio/src/sync/watch.rs
I found that [the example code of `tokio::sync::watch`](https://docs.rs/tokio/latest/tokio/sync/watch/index.html#examples) had odd indent.
This PR removes the unnecessary indentation from the example code.
> docs: fix indent of `tokio::sync::watch` example code

- .github/workflows/ci.yml
- tokio-util/src/task/join_map.rs
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/task/join_set.rs
- tokio/src/task/mod.rs
- tokio/src/util/mod.rs
Closes #4535.
This leaves the ID-related APIs unstable.
> chore: stabilize JoinSet and AbortHandle

- tokio/src/io/poll_evented.rs
The (internal) docs for `PollEvented` still had a single reference to
`Registration::clear_read_ready` left (the others had been removed in
#3957). With this change we should be able to close the original issue.
Closes #3746
The documentation for`PollEvented` had a single remaining reference to
`Registration::clear_read_ready`, which no longer exists. This change
updates the documentation to refer to `Registration::clear_readiness`
instead.
> io: remove `PollEvented` docs reference to `clear_read_ready`

- CONTRIBUTING.md
The command to build docs listed in the contribution guide was missing an
environment variable needed to build `tokio-stream`. Additionally it turns out
that there was outdated information about not being able to build docs from
the root of the workspace. After the resolution of rust-lang/cargo#9274, this
is not longer correct. 
The command to build the documentation locally provided in the
Contribution Guide did not work for all crates in the project workspace.
Specifically, to build the docs for `tokio-stream` the flag `--cfg
docsrs` needs to be in the environment variable `RUSTFLAGS` in addition
to being in `RUSTDOCFLAGS`.
Additionally, there was text describing that the docs cannot be built
from the root of the workspace with a link to rust-lang/cargo#9274. That
issue has since been …
> doc: correct `cargo doc` command in contrib guide

- .github/workflows/ci.yml
- tokio/external-types.toml
This PR adds `cargo-check-external-types` to CI for #4902.
A new `check-external-types` CI step is added which pulls down a pinned nightly version of Rust, installs `cargo-check-external-types`, and then runs it against an `external-types.toml` config file which allow-lists types that are currently exposed in Tokio's public API.
If a PR exposes additional types that aren't listed in the config, then the CI job will output an error. To illustrate what this looks like, the following is the output if the `libc` entries are removed from `external-types.toml`:
```
error: Unapproved external type `libc::unix::uid_t` referenced in public API
--> tokio/src/net/unix/ucred.rs:16:5
|
16 |     pub fn uid(&self) -> uid_t {
| ...
18 |     }␊
|     ^
|
= in return value of `tokio::net::unix::UCred::uid` …
```
> ci: add `cargo-check-external-types` check

- tokio-util/src/io/sync_bridge.rs
- tokio-util/tests/io_sync_bridge.rs
Closes https://github.com/tokio-rs/tokio/issues/4932
Add a `shutdown()` function to shutdown the writer of `SyncIoBridge`
> util: add shutdown() to SyncIoBridge

- tokio/src/runtime/builder.rs
- tokio/src/runtime/config.rs
- tokio/src/runtime/thread_pool/worker.rs
- tokio/tests/rt_threaded.rs
Depends on: #4935
The multi-threaded scheduler includes a per-worker LIFO slot to
store the last scheduled task. This can improve certain usage patterns,
especially message passing between tasks. However, this LIFO slot is not
currently stealable.
Eventually, the LIFO slot **will** become stealable. However, as a
stop-gap, this unstable option lets users disable the LIFO task when
doing so improves their application's overall performance.
> rt: add unstable option to disable the LIFO slot

- tokio/src/net/tcp/split.rs
- tokio/src/net/tcp/split_owned.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/unix/split.rs
- tokio/src/net/unix/split_owned.rs
- tokio/src/net/unix/stream.rs
- tokio/src/net/windows/named_pipe.rs
The previous documentation falsely implied that a return  value of `Ok(0)`
from `try_read()` always meant that the stream's read half had closed.
However, `Ok(0)` can be returned while the stream's read half is
still open if the specified buffer has a length of 0.
I've updated the documentation to reflect this, roughly mirroring the language
used in `std:io` here: https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read
> net: add documentation to `try_read()` for zero-length buffers

- tokio/src/time/interval.rs
The comment simply reminds the reader that the first tick of an `Interval` completes immediately.
> Adds a comment to Interval.tick() example 

- tokio/src/signal/unix.rs
`SignalKind` is just a libc int wrapper, so creation methods can be const.
> signal: make `SignalKind` methods const

- tokio/src/task/builder.rs
Signed-off-by: TennyZhuang <zty0826@gmail.com>
All `spawn*` methods on `task::Builder` except `task::Builder::spawn_on` consume the ownership, and also `task::join_set::Builder::spawn_on`. I guess `task::Builder::spawn_on` accept the mutable reference is just a mistake.
Since it's an unstable API, break it to make all APIs more consistent is acceptable.
> fix incorrect signature in task::Builder::spawn_on

- tokio/src/signal/windows.rs
- tokio/src/signal/windows/stub.rs
- tokio/src/signal/windows/sys.rs
Add the other _event types from the winapi crate. Addresses #4921 
Includes:
- Console Close
- Shutdown
- Logoff
It might be worth tying console close into the ctrl_c handling framework, depending on how the Tokio authors consider it to fit.
Console Close I believe is analogous to unix's SIGHUP, which doesn't seem to be in the ctrl_c framework.
> Feature: Add more windows signal handlers

- tokio/src/signal/windows/sys.rs
- tokio/src/task/join_set.rs
Somehow the auto-merge feature merged #4953 even though it didn't pass CI. This PR fixes the warning from that PR.
> task: fix warning

- tokio/src/park/thread.rs
There's no reason to limit this cfg to wasi. Other types of wasm then wasi may also support `thread::sleep`.
> wasm: use `thread::sleep` on non-wasi wasm too

- README.md
- tokio/README.md
This adds a new LTS release and removes an expired one.
> tokio: make 1.20.x an LTS release

- tokio/src/sync/watch.rs
Current documentation of `sync::watch::Sender::send` may be intepreted as the method failing if at some point in past the channel has been closed because every receiver has been dropped. This isn't true, however, as the channel could have been reopened by using `sync::watch::Sender::subscribe`.
This fix clarifies the behavior. Moreover, it is noted that on failure, the value isn't made available to future subscribers (but returned as part of the `SendError`).
Fixes #4957.
> sync: doc of watch::Sender::send improved

- tokio/src/lib.rs
We are adding WASM support in the next release, but we have no documentation about it what-so-ever. This PR adds some documentation.
> wasm: add documentation for wasm support

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release is the first release of Tokio to intentionally support WASM. The `sync,macros,io-util,rt,time` features are stabilized on WASM. Additionally the wasm32-wasi target is given unstable support for the `net` feature.
- net: add `device` and `bind_device` methods to TCP/UDP sockets ([#4882])
- net: add `tos` and `set_tos` methods to TCP and UDP sockets ([#4877])
- net: add security flags to named pipe `ServerOptions` ([#4845])
- signal: add more windows signal handlers ([#4924])
- sync: add `mpsc::Sender::max_capacity` method ([#4904])
- sync: implement Weak version of `mpsc::Sender` ([#4595])
- task: add `LocalSet::enter` ([#4765])
- task: stabilize `JoinSet` and `AbortHandle` ([#4920])
- tokio: add `track_caller` to public APIs ([#4805], [#4848], [#4852])
- wasm: initial support …
> chore: prepare Tokio v1.21.0

- tokio/src/io/poll_evented.rs
This applies the same optimization made in #4840 to writes.
> io: reduce syscalls in `poll_write`

- tokio/src/task/task_local.rs
> task: fix a doc typo in `LocalKey::sync_scope`

- tokio/src/task/local.rs
- tokio/src/util/mod.rs
- tokio/src/util/rc_cell.rs
Similar to [`src/util/vec_deque_cell.rs`][1], this PR introduces a helper for making it easier to work with `Cell<Option<Rc<T>>>`. Using an ordinary `Cell` for this requires an elaborate dance to clone the `Rc`:
```Rust
fn clone_rc<T>(rc: &Cell<Option<Rc<T>>>) -> Option<Rc<T>> {
let value = rc.take();
let cloned = value.clone();
rc.set(value);
cloned
}
```
However, with this helper, one can simply call `.get()` to clone the `Rc`. The dance is necessary because `Cell` does not know that `Rc::clone` will not try to access the `Cell` recursively.
Note that, godbolt shows that the `clone_rc` dance does not get optimized down to what this `RcCell` helper compiles to.
[1]: https://github.com/tokio-rs/tokio/blob/master/tokio/src/util/vec_deque_cell.rs
> task: introduce RcCell helper

- tokio/src/net/unix/stream.rs
The UnixStream docs say the socket can be "accepted from a listener with UnixListener::incoming" but no method incoming exists on UnixListener. I think it should say UnixListener::accept instead?
Change the method cited in the docs. Also added a few other links to methods in that paragraph.
> docs: Fix links in UnixStream

- tokio-util/src/io/stream_reader.rs
Often when working with a stream and `StreamReader`, the error type from the stream
will not align with std::io::Error requried by AsyncRead (and transitively `StreamReader`).
Adds a documentation example to `StreamReader` showing how to convert other error
types to std::io::Error using stream combinators.
Refs: tokio-rs/tokio#4954
> docs: Add error handling example to StreamReader

- tokio/src/runtime/time/handle.rs
- tokio/src/runtime/time/mod.rs
- tokio/src/runtime/time/source.rs
- tokio/src/runtime/time/tests/mod.rs
- tokio/src/time/sleep.rs
This patch makes some minor refactors. It renames `ClockTime` to `TimeSource` since that is how all variables refer to it. It also moves the type into a new file.
Finally, it moves the `unpark` handle out of the mutex as it does not need to be there. Note, the call to `unpark` is still called while the mutex is held, so there is no functional change. Moving it out of the mutex is in preparation for moving the unpark handle entirely out of the time driver.
> rt: minor time driver refactors

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
- io: add `SyncIoBridge::shutdown()` ([#4938])
- task: improve `LocalPoolHandle` ([#4680])
- util: add `track_caller` to public APIs ([#4785])
- task: fix compilation errors in `JoinMap` with Tokio v1.21.0 ([#4755])
- task: remove the unstable, deprecated `JoinMap::join_one` ([#4920])
[#4680]: https://github.com/tokio-rs/tokio/pull/4680
[#4755]: https://github.com/tokio-rs/tokio/pull/4755
[#4785]: https://github.com/tokio-rs/tokio/pull/4785
[#4920]: https://github.com/tokio-rs/tokio/pull/4920
[#4938]: https://github.com/tokio-rs/tokio/pull/4938
Closes: #4986
> chore: prepare tokio-util 0.7.4

- tokio/tests/io_copy_bidirectional.rs
Closes https://github.com/tokio-rs/tokio/issues/4900
Mocked `Stream` to return write error instead of relying on filling up TCP buffers. As a side-effect, increased coverage to include errors from `read`.
Test tested by temporarily doing this:
and this:
> rewrite `immediate_exit_on_error` to use `io::Mock`

- tokio/src/runtime/blocking/mod.rs
- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/handle.rs
- tokio/src/task/builder.rs
A few spawn_blocking methods were implemented on a Handle struct that is intended to hold all runtime driver handles. These methods make more sense in the blocking module.
> rt: move spawn_blocking methods to blocking mod

- tokio/src/runtime/io/registration.rs
Fixes #3747
Internal docs on `Registration` struct mentioned functions which no longer
exist. This was brought up in an issue from over a year ago (linked) and
it would be nice to fix it.
The docs for `Registration::new_with_interest_and_handle` (internal
function) included a reference to two old functions `new_with_interest`
and `new` on the same struct. These functions no longer exist, which
could be confusing.
Since there is currently only a single constructor function on
`Registration`, the misleading text has simply been removed.
> io: remove reference to missing functions from `Registration` docs

- tokio-util/src/codec/length_delimited.rs
The `LengthDelimitedCodec` calls `BytesMut::reserve` on two occasions:
- after the header is read, to allocate memory for the expected frame
- after a frame is read, to allocate memory for another header that may follow
In both cases, the implementation currently calls `src.reserve(n)` which reserves the necessary `n` bytes for [**additional** data](https://docs.rs/bytes/latest/bytes/struct.BytesMut.html#method.reserve), disregarding the fact that the buffer might already have additional data present that just wasn't decoded yet.
This causes excess memory allocation, which might be quite substantial in certain cases.
Take into account the buffer's current length when calculating the amount of memory that should be reserved.
As a small drive-by cleanup, I also removed a check that `n != 0` …
> Fix LengthDelimitedCodec buffer over-reservation.

- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
The internal `runtime::ToHandle` trait is no longer needed as the runtime handle is used everywhere now.
> rt: remove internal runtime::ToHandle trait

- tokio/Cargo.toml
> net: fix dependency resolution for socket2

- tokio/src/task/local.rs
- tokio/tests/task_local_set.rs
If we can't set the thread-local when destroying a `LocalSet`, then we just ignore it and proceed as normal. This means that task destructors wont be able to access the thread-local, but they wouldn't be able to do that previously either.
Closes: #4973
> task: ignore failure to set TLS in LocalSet Drop

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- net: fix dependency resolution for socket2 ([#5000])
- task: ignore failure to set TLS in `LocalSet` Drop ([#4976])
[#4976]: https://github.com/tokio-rs/tokio/pull/4976
[#5000]: https://github.com/tokio-rs/tokio/pull/5000
> chore: prepare Tokio v1.21.1

- .cirrus.yml
I've noticed that CI has started auto-cancelling old jobs on our master and master-like branches. This should hopefully fix that.
> ci: don't auto-cancel CI on old commits on master

- .github/workflows/ci.yml
Adds (failing until #5000 is merged) test for build on `x86_64-fortanix-unknown-sgx` target (see #4999).
> ci: Add build test for x86_64-fortanix-unknown-sgx target

- .github/workflows/ci.yml
- tokio/src/process/unix/driver.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/signal/unix/driver.rs
As has been pointed out a few times in the past (e.g., https://github.com/tokio-rs/tokio/pull/4036#issuecomment-897252076), each-feature is not sufficient for features check.
Ideally, we'd like to check all combinations of features, but there are too many combinations.
So limit the max number of simultaneous feature flags to 2 by [`--depth` option](https://github.com/taiki-e/cargo-hack/pull/59). I think this should be sufficient in most cases as @carllerche said in https://github.com/taiki-e/cargo-hack/issues/58.
> ci: use --feature-powerset --depth 2 in features check

- tokio/src/runtime/builder.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/multi_thread/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/runtime/spawner.rs
In an earlier PR (#4629), driver handles were moved into the scheduler handle (`Spawner`). This was done to let the multi-threaded scheduler have direct access to the thread pool spawner.
However, we are now working on a greater decoupling of the runtime internals. All drivers and schedulers will be peers, stored in a single thread-local variable, and the scheduler will be passed the full runtime::Handle. This will achieve the original goal of giving the scheduler access to the thread-pool while also (hopefully) simplifying other aspects of the code.
> rt: store driver handles next to scheduler handle

- tokio/src/runtime/driver.rs
- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/mod.rs
Currently, the various resource drivers use a layered approach where each driver contains the next one. When the scheduler calls park on the top-most driver, it does work, then calls park on the inner driver. The handles do the same with unparking.
This patch is a step towards refactoring the runtime to move away from the nested approach towards keeping all drivers and handles together in a single runtime driver/handle. The unparker is removed from the time handle and placed in the runtime handle and passed into the time driver as needed.
Depends on #5012.
> rt: move unpark out of time driver

- tokio/src/lib.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/handle.rs
- tokio/src/runtime/time/mod.rs
- tokio/src/runtime/time/tests/mod.rs
- tokio/src/time/sleep.rs
- tokio/src/util/error.rs
- tokio/src/util/mod.rs
The `TimerEntry` struct is the internal integration point for public time APIs (`sleep`, `interval`, ...) with the time driver. Currently, `TimerEntry` holds a ref-counted reference to the time driver handle.
This patch replaces the reference to the time driver handle with a reference to the runtime handle. This is part of a larger effort to consolidate internal handles across the runtime.
> rt: update TimerEntry to use runtime::Handle

- tokio/src/runtime/driver.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
Currently, drivers are responsible for cleaning themselves up when they are dropped. This is possible today because each driver struct holds a reference to its internal handle.
As part of an effort to decouple drivers from their handles, this patch removes the drop implementations for the time and IO driver in favor of having the scheduler explicitly call `shutdown()` as part of its shutdown process. The scheduler will hold a reference to both the driver and the driver handles, so in the future, it will be able to pass in the driver handles as part of the shutdown process.
> rt: remove driver drop implementations

- tokio/src/runtime/tests/task_combinations.rs
- tokio/tests/rt_handle_block_on.rs
- tokio/tests/rt_threaded.rs
- tokio/tests/sync_mpsc.rs
- tokio/tests/task_abort.rs
- tokio/tests/task_local_set.rs
- tokio/tests/time_sleep.rs
- tokio/tests/uds_datagram.rs
This patch removes println statements from tests. Some of these were used to test that types implement `fmt::Debug`. These println statements have been replaced with an equivalent test that does not output to STDOUT. The rest of the println statements are most likely left over from debugging sessions.
> chore: remove println from tests

- tokio/src/runtime/builder.rs
- tokio/src/runtime/mod.rs
The `runtime::Kind` enum doesn't really represent the runtime flavor but is an enumeration of the different scheduler types. This patch renames the enum to reflect this.
At a later time, it is likely the `Scheduler` enum will be moved to `tokio::runtime::scheduler`, but that is punted to a later PR.
This rename is to make space for other enums.
> rt: rename internal `runtime::Kind` to `Scheduler`

- tokio/src/runtime/builder.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/tests/mod.rs
Move all individual driver handles into a single `driver::Handle` struct.
> rt: create driver::Handle struct

- tokio/src/runtime/builder.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
This is the next step in the internal runtime refactoring. This patch updates `CurrentThread` to use `Arc<Handle>` for all of its cross-thread needs instead of `Arc<Shared>`.
The effect of this change is that the current-thread scheduler only has a single `Arc` type, which includes the driver handles, keeping all "shared state" together.
> rt: update CurrentThread to use its own Handle

- tokio/src/runtime/builder.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/handle.rs
- tokio/src/runtime/scheduler/multi_thread/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
This is the equivalent of tokio-rs/tokio#5023, but for the MultiThread scheduler. This patch updates `MultiThread` to use `Arc<Handle>` for all of its cross-thread needs instead of `Arc<Shared>`.
The effect of this change is that the multi-thread scheduler only has a single `Arc` type, which includes the driver handles, keeping all "shared state" together.
> rt: update MultiThread to use its own Handle

- tokio/src/runtime/scheduler/multi_thread/mod.rs
- tokio/src/runtime/scheduler/multi_thread/park.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
This patch removes the driver Unpark handle out of the multi-thread parker and passes a reference in when it is needed. This is a first step towards getting rid of the separate driver unpark handle in favor of just using the regular driver handle. Because the regular driver handle is owned at a higher level (at the top of the worker struct).
> rt: move driver unpark out of multi-thread parker

- tokio/src/process/unix/driver.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/multi_thread/handle.rs
- tokio/src/runtime/scheduler/multi_thread/mod.rs
- tokio/src/runtime/scheduler/multi_thread/park.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/runtime/time/handle.rs
- tokio/src/runtime/time/mod.rs
- tokio/src/signal/unix/driver.rs
This patch removes all internal `Unpark` runtime types. The runtime now uses the `Handle` types (`runtime::io::Handle` and `runtime::time::Handle`) to signal threads to unpark.
Without separate `Unpark` types, future patches will be able to remove more `Arc`s used inside various drivers.
This depends on #5026
> rt: rm internal `Unpark` types for Handle types

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
> chore: release tokio-stream 0.1.10

- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/sync/mpsc/bounded.rs
- tokio/src/task/blocking.rs
- tokio/src/task/local.rs
- tokio/tests/task_panic.rs
Most of the public APIs in the `task` module were covered with the `#[track_caller]`
attribute in #4848. However, two functions were skipped because the call stack
leading to the panic passed through a closure (rust-lang/rust#87417).
The fact that this is missing was brought up again in #5030. At that point, a work around
solution was collectively worked out for that use case, bringing the panic call outside the
closure.
Functions that may panic can be annotated with `#[track_caller]` so that in the event of a panic, the function where the user called the panicking function is shown instead of the file and line within Tokio source.
This change adds `#[track_caller]` to two public APIs in tokio task module which weren't added in #4848.
* `tokio::task::block_in_place`
* …
> task: add track_caller to `block_in_place` and `spawn_local`

- .circleci/config.yml
- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/stress-test.yml
- examples/Cargo.toml
- tokio/Cargo.toml
- tokio/src/loom/std/parking_lot.rs
- tokio/src/process/unix/mod.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/signal/registry.rs
- tokio/src/util/mod.rs
- tokio/src/util/once_cell.rs
The latest `OnceCell` release is not compatible with the MSRV of this LTS release. This PR adds a simple `OnceCell` implementation to Tokio and uses it instead.
> Don't use OnceCell for 1.18.x LTS release

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release removes the dependency on the `once_cell` crate to restore the MSRV of the 1.18.x LTS release. ([#5048])
[#5048]: https://github.com/tokio-rs/tokio/pull/5048
> Prepare Tokio v1.18.3

- .circleci/config.yml
- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/stress-test.yml
- examples/Cargo.toml
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/src/loom/std/parking_lot.rs
- tokio/src/process/unix/mod.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/signal/registry.rs
- tokio/src/util/mod.rs
- tokio/src/util/once_cell.rs
This commit merges #5051 into the tokio-1.20.x branch. The `rust_stable` pin is updated to 1.62.1 rather than 1.60.0 as part of the merge.
This PR must be merged from the command line!
> Merge 1.18.3

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release removes the dependency on the `once_cell` crate to restore the MSRV of the 1.20.x LTS release. ([#5048])
[#5048]: https://github.com/tokio-rs/tokio/pull/5048
> chore: prepare Tokio v1.20.2

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release removes the dependency on the `once_cell` crate to restore the MSRV of 1.21.x, which is the latest minor version at the time of release. ([#5048])
[#5048]: https://github.com/tokio-rs/tokio/pull/5048
> chore: prepare Tokio v1.21.2

- .github/workflows/ci.yml
- examples/Cargo.toml
Currently the minrust check only looks at the main tokio crate, but we should look at all crates. This also re-enables an example that was disabled.
Fixes #5049.
> ci: improve minrust check and reenable example

- tokio/tests/net_panic.rs
These tests fail on my system because I have a local service already
bound to 127.0.0.1:8080 - the exact port number doesn't matter, so allow
the kernel to choose a random port instead.
These tests fail whenever I have my own local service running on port 8080. Similar problems would apply to any port we choose, and `tcp_stream_from_std_panic_caller` avoids the problem already by listening on a kernel-chosen port.
Reuse the solution from `tcp_stream_from_std_panic_caller` - we can listen to any random port successfully, so let the kernel choose an unused port for our test.
> use random port in tests, not 8080

- tokio/build.rs
- tokio/src/loom/std/mutex.rs
- tokio/src/macros/cfg.rs
- tokio/src/process/unix/mod.rs
- tokio/src/process/unix/orphan.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/util/mod.rs
- tokio/src/util/once_cell.rs
This PR removes `OnceCell` in favor of a const `Mutex::new` call when it is available (on sufficiently new rustc or with parking_lot).
> tokio: use const `Mutex::new` for globals

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/loom.yml
- .github/workflows/pr-audit.yml
- .github/workflows/stress-test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/tokio-rs/tokio/actions/runs/3169751968/jobs/5161876737#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- audit.yml
- ci.yml
- labeler.yml
- loom.yml
- pr-audit.yml
- stress-test.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/au …
> ci: add minimum GitHub token permissions for workflows

- benches/Cargo.toml
- benches/copy.rs
- tokio/src/io/util/copy.rs
Fixes: #3694 
When a reader is giving small chunks of data (e.g. reading over a congested TCP link), and the writer stalls because it's also overloaded, we can end up issuing smaller writes than a buffer because we do at most one read for every write.
In the overload case, demonstrated by the `copy_chunk_to_slow_hdd` benchmark, this results in us being slower than we could be if we aimed to fill the buffer each time we did a read.
Refactor so that we can read every time we get a `Poll::Pending` from the writer. This has no significant impact on times if either the reader is able to fill the copy buffer each time, or the writer never stalls, but on my Xeon E3-1245v2, I see `copy_chunk_to_slow_hdd` speed up:
Before:
`test copy_chunk_to_slow_hdd ... bench: 161,070,661 ns/iter (+/- …
> make copy continue filling the buffer when writer stalls

- tokio/src/net/tcp/socket.rs
- tokio/src/net/udp.rs
This PR updates the documentation for the `set_tos` methods on `tokio::net::{TcpSocket, UdpSocket}`, which is currently stating to set the _time-to-live_ field of packets sent from the socket. This should be corrected, since it actually sets the _type-of-service_ field.
I was reading the documentation and noticed the inconsistency.
Update the documentation to avoid confusion.
> net: fix doc typos for TCP and UDP set_tos methods

- tokio/tests/rt_common.rs
This test sometimes fails if the tasks aren't completed within 100ms. This test uses an unbounded mpsc channel instead of 1000 tasks. This works because mpsc also hooks into the coop system, and it eliminates the race.
> coop: fix flaky coop test

- tokio/src/runtime/io/mod.rs
`tokio::runtime::io::Driver` has a field `events` with the type`Option<mio::Events>`. The `Option` wrapper is used to solve the second mutable borrow conflicts in the method `Driver::turn`. This requires to take the inner `mio::Events` every time `Driver::turn` is called, which introduce unnecessary overheads.
1. Change `Option<mio::Events>` to `mio::Events` so that no `Option::take` is needed to call in the method `Driver::turn`.
2. Change the function signature of `Driver::dispatch` from:
```rust
fn dispatch(&mut self, token: mio::Token, ready: Ready)
```
to
```rust
fn dispatch(resources: &mut Slab<ScheduledIo>, tick: u8, token: mio::Token, ready: Ready)
```
so that the compiler won't complain.
> remove unnecessary `Option` for `mio::Events` in `Driver`

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
- time: allow `StreamExt::chunks_timeout` outside of a runtime ([#5036])
[#5036]: https://github.com/tokio-rs/tokio/pull/5036
> chore: release tokio-stream 0.1.11

- tokio/src/runtime/task/list.rs
- tokio/src/task/local.rs
It turns out that `LocalSet` has...never actually passed Miri. This is
because all of the tests for `LocalSet` are defined as integration tests
in `tokio/tests/task_local_set.rs`, rather than lib tests in
`tokio/src`, and we never run Miri for integration tests.
PR #5095 added a new test reproducing an unrelated bug in `LocalSet`,
which had to be implemented as a lib test, as it must make internal
assertions about the state of the `LocalSet` that cannot be tested with
just the public API. This test failed under Miri, and it turns out that
the reason for this is unrelated to the change in #5095 --- `LocalSet`
uses the `LocalOwnedTasks` type, which turns out to contain a stacked
borrows violation due to converting an `&Header` into an
`NonNull<Header>` when removing a task from the …
> runtime: fix Stacked Borrows violation in `LocalOwnedTasks`

- tokio/src/coop.rs
- tokio/src/fs/mocks.rs
- tokio/src/macros/scoped_tls.rs
- tokio/src/macros/thread_local.rs
- tokio/src/park/thread.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/enter.rs
- tokio/src/task/local.rs
- tokio/src/util/rand.rs
Tokio maintains an internal thread_local macro that abstracts some conditional build logic. Before this patch, the macro was named the same as the `std` macro (`thread_local`). This resulted in confusion as to whether or not the internal macro or the std macro was being called.
This patch renames the internal macro to `tokio_thread_local`, making it more obvious.
> tokio: rename internal thread_local macro

- tokio/src/task/local.rs
- tokio/src/util/rc_cell.rs
The `LocalSet` implementation includes a conditional compilation clause that removes the `const` statement from the `thread_local` definition. However, there already is an internal macro that does this: `tokio_thread_local`.
This patch removes the conditional compilation in favor of using the `tokio_thread_local` macro. This also fixes a conditional compilation issue with an internal utility (`RcCell`).
> rt: remove a conditional compilation clause

- tokio-macros/src/entry.rs
This excludes the initial let statement of the proc-macro expansion from receiving the last statement spans to aid completions in rust-analyzer. The current span confuses rust-analyzer as it will map the tail expression tokens to the let keyword (as this is the first token it finds with the same span) which currently breaks completions. This commit should not degrade the initial intent of the span reusages, as the type mismatch parts are still spanned appropriately.
R-a is currently pretty terrible with spans, but needs them for proper usage of features in proc-macros, for example it uses them for figuring out where to analyse surrounding context for completions. More importantly it uses them to figure out what tokens to remove after fixing up syntax errors. Tokio's usage of the trailing …
> Reduce usage of last statement spans in proc-macros

- tokio-stream/src/stream_ext/throttle.rs
Yes, these methods are safe without `T: Unpin` since the module contains no unsafe anywhere.
> time: remove Unpin bound on throttle methods

- tokio-stream/src/stream_ext.rs
Was stuck here for some time debugging.
Small documentation fix. `Throttle` uses `tokio::time::sleep_until` which states that it shouldn't be used for sub ms granularity.
> stream: document that `throttle` operates on ms granularity

- tokio/src/runtime/time/entry.rs
Update the alignment of `CachePadded` based on [crossbeam](https://github.com/crossbeam-rs/crossbeam/blob/fa35346b7c789bba045ad789e894c68c466d1779/crossbeam-utils/src/cache_padded.rs#L62-L127)'s implementation.
> runtime: update the alignment of `CachePadded`

- tokio/src/runtime/time/entry.rs
The `debug_assert` can be triggered in release mode (https://github.com/tokio-rs/tokio/issues/3675).
a) panic in release mode as well
b) have a better error message describing the problem. (I added the direct cause of the problem)
Previous PR: https://github.com/tokio-rs/tokio/pull/3681
Fixes https://github.com/tokio-rs/tokio/issues/3675
> time: panic in release mode when `mark_pending` called illegally

- tokio/src/runtime/driver.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/park.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/runtime/time/mod.rs
This patch removes a handle to the internal runtime driver handle held by the
runtime. This is another step towards reducing the number of Arc refs across
the runtime internals. Specifically, this change is part of an effort to remove
an Arc in the time driver itself.
> rt: remove a reference to internal time handle

- tokio/src/time/error.rs
- tokio/src/time/timeout.rs
Since `timeout` returns a named future, it is not so easy to see what its return type is.
> time: document return type of `timeout`

- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/task/join.rs
- tokio/src/task/join_set.rs
- tokio/src/task/local.rs
- tokio/src/task/spawn.rs
It appears that this is not already sufficiently well documented.
> task: document that spawned tasks execute immedaitely

- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/handle.rs
- tokio/src/runtime/time/mod.rs
- tokio/src/runtime/time/source.rs
- tokio/src/time/sleep.rs
Removes an unnecessary `Arc` and reduces internal state clones.
> rt: misc time driver cleanup

- tokio/src/macros/cfg.rs
- tokio/src/process/unix/driver.rs
- tokio/src/process/unix/mod.rs
- tokio/src/process/unix/orphan.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/signal/mod.rs
- tokio/src/signal/mod.rs
- tokio/src/signal/unix.rs
The signal feature only requires a driver with unix platforms. The unix signal
driver uses the I/O driver. A future refactor would like to make the signal driver
use internal APIs of the I/O driver. To do this, the signal driver must be moved
to the runtime module.
> rt: move signal driver to runtime module

- tokio/src/process/unix/mod.rs
- tokio/src/process/unix/orphan.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/process.rs
- tokio/src/runtime/signal/mod.rs
This is the start of applying a similar treatment to the I/O driver as the time
driver. The I/O driver will no longer hold its own reference to the I/O handle.
Instead, the handle is passed in when needed.
This patch also moves the process driver to the `runtime` module.
> rt: start decoupling I/O driver and I/O handle

- tokio/src/io/async_fd.rs
- tokio/src/io/bsd/poll_aio.rs
- tokio/src/io/poll_evented.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/io/registration.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/time/sleep.rs
The `schedule::Handle` reference is the internal runtime handle. This
patch replaces owned refs to `runtime::io::Handle` with
`scheduler::Handle`.
> rt: switch io::handle refs with scheduler:Handle

- tokio/tests/rt_threaded.rs
The improvement to the `rng_seed` tests added in #5075 missed a case in the `rt_threaded` tests which was still checking for a specific value. As described in that PR, this makes the tests fragile and changing tokio internals may require updating the test.
This change fixes that half-implemented improvement so that the tests no longer depend on the exact internal ordering, but rather compare two runs of separate runtimes built with the same seed to check that the results are the same.
> rt: fix `rng_seed` test for threaded runtime

- tokio/src/runtime/driver.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/io/registration.rs
- tokio/src/runtime/metrics/runtime.rs
The next step in the great driver cleanup. This patch removes the Arc used in the I/O driver in favor of `runtime::scheduler::Handle`.
> rt: remove Arc from I/O driver

- tokio/src/runtime/context.rs
- tokio/src/runtime/driver.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/signal/mod.rs
- tokio/src/signal/unix.rs
The signal driver still uses an `Arc` internally to track if the driver
is still running, however, using the `scheduler::Handle` to access the
signal driver handle lets us delete some code.
> rt: use signal driver handle via scheduler::Handle

- tokio/src/runtime/context.rs
- tokio/src/time/clock.rs
A step towards getting rid of `runtime::context`. Internal functions
related to getting the current clock are moved to the time driver.
> rt: move internal clock fns out of context

- tokio/src/runtime/builder.rs
- tokio/tests/rt_threaded.rs
While setting the random number generator seed with the multi-threaded
scheduler does result in deterministic behavior related to the random
number generator, threads still introduce non-determinism, making it
hard (impossible?) to test this. There also is little value in doing so.
This patch also updates the docs to remove mention of work-stealing.
> rt: remove rng_seed+mt test and update docs

- tokio-util/src/codec/framed.rs
- tokio-util/src/codec/framed_impl.rs
- tokio-util/src/codec/framed_write.rs
- tokio-util/tests/framed_write.rs
Currently `Framed` uses hardcoded value (8kb) for it's backpressure boundary, which makes it mostly pointless to increase write buffer capacity (which by default is at 8kb too). And in some scenarios I'd like to have more than 8kb write buffer.
Replace `BACKPRESSURE_BOUNDARY` constant with a `WriteFrame::backpressure_boundary` variable (that defaults to 8kb), add `(set_)backpressure_boundary()` functions to `Framed`.
Closes: #5123
> expose backpressure_boundary in Framed API

- tokio/src/time/timeout.rs
Document the case where timeouts may not fire for `tokio::time::timeout`, from discussion on #5119.
Ran into a situation where `timeout` was not always firing, despite exceeding the timeout - docs did not cover this situation.
Updated the docs.
> Doc change for when timeouts may not fire.

- tokio/src/sync/mutex.rs
Fixes https://github.com/tokio-rs/tokio/issues/5109
> Implement Mutex::blocking_lock_owned

- tokio-util/src/sync/poll_semaphore.rs
- tokio-util/tests/poll_semaphore.rs
Adds `PollSemaphore::poll_acquire_many`, to allow acquiring `n` permits
from it.
Feature parity with `Semaphore`.
Introduce the more general `poll_acquire_many` function, to which the `poll_acquire` one now delegates.
> Allow acquiring `n` permits from `PollSemaphore`

- tokio/src/sync/mpsc/bounded.rs
- tokio/src/sync/mpsc/chan.rs
- tokio/src/sync/mpsc/unbounded.rs
Make code easier to read. No functional/perf changes.
> Make channel semaphore types named

- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
> rt: add a method to determine the flavor of the runtime.

- tokio-util/src/sync/poll_semaphore.rs
- tokio/src/sync/semaphore.rs
- tokio/tests/sync_semaphore.rs
> Expose Semaphore::MAX_PERMITS and document it

- tokio/src/lib.rs
- tokio/src/macros/support.rs
- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/builder.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/util/mod.rs
- tokio/src/util/rand.rs
This patch is the first step towards unifying all the thread-local variables
spread out across Tokio. A new `Context` struct is added, which will be
used to replace the various thread-locals that exist today.
Initially, `Context` only holds the current runtime handle and the random
number generator. Future PRs will add other thread-local states.
A previous PR removed `runtime::context`. At that time,
`runtime::context` was used as an extra layer to access the various
runtime driver handles. This version of `runtime::context` serves a
different purpose (unifying all the thread-locals).
> rt: add runtime::context to unify thread-locals

- tokio/src/net/udp.rs
In the "cancellation safety" section of the UdpSocket recv function,
"recv_from" is referenced when it should be "recv"
> tokio: fix function name in UdpSocket recv doc

- tokio-util/src/io/stream_reader.rs
Rendered docs: [link](https://deploy-preview-5145--tokio-rs.netlify.app/tokio_util/io/struct.streamreader)
> io: add lines example for `StreamReader`

- tokio/src/runtime/context.rs
- tokio/src/runtime/enter.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/src/task/local.rs
This patch does some internal renames to remove some confusion.
* `allow_blocking` is renamed to `allow_block_in_place` to indicate that the variable only impacts the `block_in_place()` function.
* `context::try_enter` is renamed to `context::try_set_current` to disambiguate between the various "enter" functions. This function only sets the runtime handle used by Tokio's public APIs. Entering a runtime is a separate operation.  # Please enter the commit message for your changes.
* `scheduler::Handle::enter()` is removed to consolidate methods that set the current context.
> rt: rename some confusing internal variables/fns

- tokio/src/sync/notify.rs
- tokio/tests/unwindsafe.rs
make Notify panic safe.
close #5122
> sync: make Notify panic safe

- tokio/src/task/local.rs
- tokio/tests/task_local_set.rs
The `LocalSet::run_until` future is just a "plain" future that should run on a runtime that already has a coop budget. In other words, the `run_until` future should not get its own budget but should inherit the calling task's budget. Getting this behavior is done by removing the call to `budget` in `run_until`.
> rt: rm coop::budget from `LocalSet::run_until`

- tokio/src/runtime/context.rs
- tokio/src/runtime/coop.rs
- tokio/src/runtime/mod.rs
This patch consolidates the budget thread-local state with the `runtime::context` thread local. This reduces the number of thread-local variables used by Tokio by one.
> rt: move budget state to context thread-local

- tokio/src/sync/mutex.rs
Current [`TryLockError`](https://docs.rs/tokio/1.21.2/tokio/sync/struct.TryLockError.html) isn't very clear. Seems like a copy paste error from `RwLock::try_read()`'s description which looks right.
See changes
> chore: typo in TryLockError for RwLock::try_write

- .github/workflows/ci.yml
- tokio/tests/macros_join.rs
Rust 1.65 reduces some struct sizes.
> chore: fix tests for Rust 1.65 release

- tokio/src/future/block_on.rs
- tokio/src/runtime/blocking/shutdown.rs
- tokio/src/runtime/enter.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/multi_thread/mod.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
This is a first step towards unifying the concepts of "entering a runtime" and setting `Handle::current`.
Previously, these two operations were performed separately at each call site (runtime block_on, ...). This is error-prone and also requires multiple accesses to the thread-local variable. Additionally, "entering the runtime" conflated the concept of entering a blocking region. For example, calling `mpsc::Receiver::recv_blocking` performed the "enter the runtime" step. This was done to prevent blocking a runtime, as the operation will panic when called from an existing runtime.
To untangle these concepts, the patch splits each logical operation into a separate function. In total, there are three "enter" operations:
* `set_current_handle`
* `enter_runtime`
* `enter_blocking_region` …
> rt: unify entering a runtime with Handle::enter

- tokio/src/sync/tests/atomic_waker.rs
> sync: fix copy-paste error for `AtomicWaker`

- tokio/src/runtime/blocking/pool.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/handle.rs
- tokio/tests/rt_metrics.rs
Add metrics about the blocking thread pool.
Publish the metrics as thread-safe values, written under the blocking thread
pool's lock and able to be read in a lock-free fashion by any reader.
Fixes #5156
> runtime: export metrics about the blocking thread pool

- tokio/src/runtime/builder.rs
- tokio/src/runtime/runtime.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/scheduler/mod.rs
- tokio/src/runtime/scheduler/multi_thread/mod.rs
Instead of each scheduler flavor holding a reference to the scheduler handle, the scheduler handle is passed in as needed. This removes a duplicate handle reference in the `Runtime` struct and lays the groundwork for further handle struct tweaks.
> rt: remove handle reference from each scheduler

- .github/workflows/ci.yml
- tokio-stream/src/stream_ext/collect.rs
- tokio-stream/src/stream_ext/timeout.rs
- tokio-stream/src/wrappers/broadcast.rs
- tokio-util/src/time/delay_queue.rs
- tokio-util/tests/context.rs
- tokio-util/tests/sync_cancellation_token.rs
- tokio/src/io/ready.rs
- tokio/src/lib.rs
- tokio/src/macros/thread_local.rs
- tokio/src/net/addr.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/runtime/io/mod.rs
- tokio/src/sync/batch_semaphore.rs
- tokio/src/sync/broadcast.rs
- tokio/src/sync/once_cell.rs
- tokio/src/sync/oneshot.rs
- tokio/src/time/error.rs
- tokio/tests/fs_file.rs
- tokio/tests/io_buf_writer.rs
- tokio/tests/io_mem_stream.rs
- tokio/tests/macros_test.rs
- tokio/tests/sync_mpsc.rs
- tokio/tests/task_local.rs
- tokio/tests/task_panic.rs
- tokio/tests/tcp_split.rs
- tokio/tests/time_sleep.rs
- tokio/tests/udp.rs
- tokio/tests/uds_datagram.rs
One of our test dependencies now require Rust 1.60.0, which causes clippy to fail. This PR bumps the clippy version and fixes the new lints.
> chore: bump clippy version

- tokio/src/loom/std/atomic_u16.rs
- tokio/src/loom/std/atomic_u32.rs
- tokio/src/loom/std/atomic_usize.rs
- tokio/src/runtime/tests/queue.rs
The `unsync_load` methods currently create a mutable reference to the atomic to perform the read. However, this is not allowed as it will sometimes race with other atomic loads. This occasionally causes the `stress1` test to fail with the following error:
```
error: Undefined Behavior: not granting access to tag <3613730> because that would remove [Unique for <3613708>] which is protected because it is an argument of call 1030169
--> tokio/src/runtime/scheduler/multi_thread/queue.rs:386:28
|
386 |             let src_tail = self.0.tail.load(Acquire);
|                            ^^^^^^^^^^^^^^^^^^^^^^^^^ not granting access to tag <3613730> because that would remove [Unique for <3613708>] which is protected because it is an argument of call 1030169
|
= help: this indicates a potential bug …
```
> runtime: fix `unsync_load` on atomic types

- tokio/src/runtime/task/harness.rs
I came across https://github.com/rust-lang/rust/issues/55005 and learned of the following special exception:
> For both `&T` without `UnsafeCell<_>` and `&mut T`, you must not deallocate the data until the reference expires. As a special exception, given an `&T`, any part of it that is inside an `UnsafeCell<_>` may be deallocated during the lifetime of the reference, after the last time the reference is used (dereferenced or reborrowed). Since you cannot deallocate a part of what a reference points to, this means the memory an `&T` points to can be deallocted only if every part of it (including padding) is inside an UnsafeCell.
>
> [source](https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html)
However, I noticed that our calls to decrement the ref-count are currently written …
> task: elaborate safety comments in task deallocation

- tokio/src/runtime/context.rs
A previous patch moved code related to entering a runtime into the context module but did not change anything. This patch combines both thread-local variables.
> rt: combine context and entered thread-locals

- tokio/src/runtime/context.rs
- tokio/tests/rt_common.rs
An earlier change updated `enter_runtime` to also set the current handle. However, the change did not store the `SetCurrentGuard`, so the "current handle" was immediately unset. This patch stores the `SetCurrentGuard` in the `EnterRuntimeGuard`.
No existing test exposed this bug because all tests went via `Runtime` instead of `Handle`. Currently, `Runtime` is still explicitly setting the handle before entering runtime, so all tests still pass. A new test is added that covers the case of calling `Handle::block_on` and accessing the current handle.
> rt: fix accidental unsetting of current handle

- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/mod.rs
See https://github.com/tokio-rs/tokio/pull/5171#issuecomment-1310201378.
> rt: move CoreStage functions to Core

- tokio-util/src/task/join_map.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/error.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/task/mod.rs
- tokio/tests/task_id.rs
> rt: add a method to retrieve task id

- tokio/tests/sync_mpsc_weak.rs
Master fails with the following warning on wasm:
```
error: unused import: `wasm_bindgen_test::wasm_bindgen_test as test`
--> tokio/tests/sync_mpsc_weak.rs:6:5
|
6 | use wasm_bindgen_test::wasm_bindgen_test as test;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-imports` implied by `-D warnings`
```
This is due to a PR that got merged by auto-merge even though it doesn't pass CI.
I fixed this by using `#[test]` for the non-async tests.
> chore: fix compilation on master

- tokio/src/net/unix/mod.rs
- tokio/src/net/unix/ucred.rs
> net: remove libc type leakage in a public API.

- tokio/external-types.toml
Exposure of the libc ID types was removed in #5191. This change removes them from the allow list
in the `cargo-check-external-types` config.
> Remove libc types from external types allow list

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- process: add `Command::process_group` ([#5114])
- runtime: add `Handle::runtime_flavor` ([#5138])
- runtime: add `Handle::runtime_flavor` ([#5138])
- runtime: export metrics about the blocking thread pool ([#5161])
- sync: add `Mutex::blocking_lock_owned` ([#5130])
- sync: add `Semaphore::MAX_PERMITS` ([#5144])
- sync: add `merge()` to semaphore permits ([#4948])
- sync: add `mpsc::WeakUnboundedSender` ([#5189])
- task: add `task::id()` and `task::try_id()` ([#5171])
- macros: don't take ownership of futures in macros ([#5087])
- runtime: fix Stacked Borrows violation in `LocalOwnedTasks` ([#5099])
- runtime: mitigate ABA with 32-bit queue indices when possible ([#5042])
- task: wake local tasks to the local queue when woken by the same thread ([#5095])
- time: panic in release mode …
> chore: prepare Tokio v1.22.0

- .github/workflows/ci.yml
- tokio/tests/rt_common.rs
- tokio/tests/rt_metrics.rs
- tokio/tests/task_local_set.rs
- tokio/tests/tcp_connect.rs
- tokio/tests/tcp_socket.rs
This patch updates CI to use `cross` to run Tokio tests on virtualized
ARM and i686 VMs. Because ipv6 doesn't work on Github action running in
a docker instance, those tests are disabled
> ci: run tests on ARM and i686 using cross

- tokio/src/lib.rs
Fixes some outdated documentation regarding parking_lot.
> doc: update `parking_lot` info in feature list

- tests-integration/Cargo.toml
- tests-integration/tests/process_stdio.rs
- tokio/src/io/poll_evented.rs
- tokio/src/process/mod.rs
- tokio/src/process/unix/mod.rs
For inter-process communication over stdin and stdout it would be helpful to use vectored writes.
Expose already existing vectored facilities in `tokio::io::PollEvented` on the `AsyncWrite` implementation of `tokio::process::ChildStdin` by providing a forwarding implementation instead of using the default non-vectoring implementation.
Adjusts the `tokio::io::PollEvented` vectored writes support to be enabled on `feature = "process"`.
> process: expose AW::poll_write_vectored on unix

- tokio-util/src/sync/cancellation_token.rs
- tokio-util/src/sync/mod.rs
- tokio-util/src/sync/tests/loom_cancellation_token.rs
- tokio-util/tests/sync_cancellation_token.rs
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
`tokio_util::sync::WaitForCancellationFuture` takes a reference to the `CancellationToken`, which is hard to use in `struct`s where you don't want a lifetime.
`tokio_util::sync::WaitForCancellationFutureOwned` provides an alternative where `CancellationToken` is taken by value so that `WaitForCancellationFutureOwned` does not contain any lifetime (but self-referenced) and can be used without worrying about lifetime.
User use [ouroboros](https://lib.rs/crates/ouroboros) to create self-reference struct, but it is not zero-cost.
Other self-reference crates that are zero-cost are experimental (e.g. [self-reference](https://docs.rs/self-reference)).
Or the user can do:
```rust
let boxed_fut: Pin<Box<(dyn Future<Output = ()> + Send)>> = …
```
> Impl `tokio_util::sync::WaitForCancellationFutureOwned`

- tokio/src/runtime/task/abort.rs
- tokio/src/runtime/task/core.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/join.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/raw.rs
- tokio/src/runtime/task/waker.rs
This PR should hopefully reduce the amount of code generated per future-type spawned on the runtime. The following methods are no longer generic:
* `try_set_join_waker`
* `remote_abort`
* `clone_waker`
* `drop_waker`
* `wake_by_ref`
* `wake_by_val`
A new method is added to the vtable called `schedule`, which is used when a task should be scheduled on the runtime. E.g. `wake_by_ref` will call it if the state change says that the task needs to be scheduled. However, this method is only generic over the scheduler, and not the future type, so it also isn't generated for every task.
Additionally, one of the changes involved in the above makes it possible to remove the `id` field from `JoinHandle` and `AbortHandle`.
> runtime: reduce codegen per task

- examples/hello_world.rs
Signed-off-by: Loong <loong.dai@intel.com>
The current comment misleads beginners, actually, it is only a client, that only work when the expected server is running.
> examples: update hello world comment

- tokio-macros/src/entry.rs
This reduces the amount of copies of the Runtime::block_on and related functions the compiler has to generate and LLVM process. We've seen it reduce the compilation time of our tests (some 1900 of them) from 40s down to 12s, with no impact on the runtime of tests.
Below is an output of llvm-lines for our tests.
Before:
```
Lines                  Copies                Function name
-----                  ------                -------------
8954414                156577                (TOTAL)
984626 (11.0%, 11.0%)   9289 (5.9%,  5.9%)  std::thread::local::LocalKey<T>::try_with
648093 (7.2%, 18.2%)    1857 (1.2%,  7.1%)  tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
557100 (6.2%, 24.5%)    3714 (2.4%,  9.5%)  tokio::park::thread::CachedParkThread::block_on …
```
> Pin Futures in #[tokio::test] to stack

- tokio-macros/src/entry.rs
- tokio/tests/macros_test.rs
Fixes #5243
This is basically the same problem as https://github.com/dtolnay/async-trait/issues/104 and https://github.com/dtolnay/async-trait/issues/46, and can be fixed by assigning a consistent span to the same variable. See also https://github.com/dtolnay/async-trait/pull/105#issuecomment-640348525. (The root cause is a compiler bug that overwrites spans of non-`:tt` metavariables during declarative macro expansion.)
> macros: fix span of body variable

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio/Cargo.toml
- fix a regression introduced in 1.8.1 ([#5244])
[#5244]: https://github.com/tokio-rs/tokio/pull/5244
> chore: prepare tokio-macros v1.8.2

- tokio/src/runtime/context.rs
- tokio/src/runtime/scheduler/multi_thread/worker.rs
- tokio/tests/rt_threaded.rs
PR #5223 changed the behavior of `yield_now()` to store yielded tasks and notify them *after* polling the resource drivers. This PR fixes two bugs with this new behavior when combined with `block_in_place()`.
First, we must avoid freeing the deferred task queue when exiting a runtime if it is *not* the root runtime. Because `block_in_place()` allows a user to start a new runtime from within an existing task, this check is necessary.
Second, when a worker core is stolen from a thread during a `block_in_place()` call, we need to ensure that deferred tasks are notified.
> rt: fix new yield_now behavior with block_in_place

- Cross.toml
- tokio/src/loom/std/atomic_u64.rs
- tokio/src/loom/std/atomic_u64_as_mutex.rs
Keeping the implementation out of a macro lets rustfmt apply to it.
This is a really minor change. I made it as part of work that didn't end up panning out. I thought I would submit this change anyway.
> chore: move conditional AtomicU64 impl to new file

- tokio/src/sync/watch.rs
Fixed just a few logical and grammar mistakes in the docs
> Fix documentation in `tokio::sync::watch`

- tokio/src/runtime/runtime.rs
A friend ran into the `current_thread` + `Handle::block_on` IO-bound task issue today; I figured an additional note about it in the docs may be helpful.
There's already an existing warning about this combination in the documentation for `Handle::block_on`. This PR adds a warning in the docs for `Runtime::handle` and points to `Handle::block_on` for more info.
If this isn't something y'all are interested in, I would totally understand - I figured it doesn't take long to make a PR, so it's easier to discuss here :)
> Add note about current_thread + Handle::block_on

- tokio-util/src/io/sync_bridge.rs
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
Since `SyncIoBridge<T>` implements `std::io::Read` if `T: AsyncRead + Unpin`, it will be nature to assume that it will also implement `std::io::BufRead` if `T: AsyncBufRead + Unpin`.
> Impl `std::io::BufRead` on `SyncIoBridge<T>` if `T: AsyncBufRead + Unpin`

- tokio/src/io/ready.rs
- tokio/src/net/tcp/split.rs
- tokio/src/net/tcp/split_owned.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/split.rs
- tokio/src/net/unix/split_owned.rs
- tokio/src/net/unix/stream.rs
- tokio/src/net/windows/named_pipe.rs
- tokio/src/runtime/io/scheduled_io.rs
- tokio/tests/tcp_stream.rs
Readiness futures inconsistently return current readiness of a I/O resource, if it is immediately available, or all readiness relevant for the given `Interest`, if a future needs to wait. In particular, it always returns `read_closed` for `Interest::READABLE` and `write_closed` for `Interest::WRITABLE`, what often is not true. Tokio should not tolerate false positives for `*_closed` events because they are considered final states and are not cleared internally.
In case of a `io_resource.ready(Interest::READABLE | Interest::WRITABLE)` call, this behavior may also lead to false positives of other events.
If a `Readiness` future is woken up by a new event, store the relevant readiness and return it later.
It pumps the `Waiter` and enclosing structs a bit (8 bytes on x86_64). If it's an …
> rt: fix `*_closed` false positives

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
Blocked on #5231 landing.
- net: fix Windows named pipe connect ([#5208])
- io: support vectored writes for `ChildStdin` ([#5216])
- io: fix `async fn ready()` false positive for OS-specific events ([#5231])
- runtime: `yield_now` defers task until after driver poll ([#5223])
- runtime: reduce amount of codegen needed per spawned task ([#5213])
- windows: replace `winapi` dependency with `windows-sys` ([#5204])
[#5208]: https://github.com/tokio-rs/tokio/pull/5208
[#5216]: https://github.com/tokio-rs/tokio/pull/5216
[#5213]: https://github.com/tokio-rs/tokio/pull/5213
[#5204]: https://github.com/tokio-rs/tokio/pull/5204
[#5223]: https://github.com/tokio-rs/tokio/pull/5223
[#5231]: https://github.com/tokio-rs/tokio/pull/5231
> chore: prepare Tokio v1.23 release

- .github/workflows/ci.yml
- tokio-macros/src/select.rs
- tokio-stream/src/stream_ext/then.rs
- tokio-util/src/sync/poll_semaphore.rs
- tokio-util/tests/spawn_pinned.rs
- tokio-util/tests/time_delay_queue.rs
- tokio/src/io/util/read.rs
- tokio/src/net/tcp/split_owned.rs
- tokio/src/net/unix/split_owned.rs
- tokio/src/runtime/scheduler/multi_thread/queue.rs
- tokio/src/runtime/task/harness.rs
- tokio/src/time/sleep.rs
- tokio/src/util/linked_list.rs
- tokio/tests/buffered.rs
- tokio/tests/io_driver.rs
- tokio/tests/macros_join.rs
- tokio/tests/macros_select.rs
- tokio/tests/macros_try_join.rs
- tokio/tests/rt_common.rs
- tokio/tests/tcp_peek.rs
We hardcode the Rust version used in CI to run clippy. This PR bumps it to the latest stable.
> chore: update CI's clippy version to 1.65

- .github/workflows/ci.yml
- tokio/tests/_require_full.rs
- tokio/tests/support/panic.rs
- tokio/tests/sync_once_cell.rs
- tokio/tests/task_join_set.rs
This adds CI coverage for a couple of code paths that are not currently
hit in CI:
* no `const fn Mutex::new`
* no `AtomicU64`
This is done by adding some new CFG flags used only for tests in order
to force those code paths.
> ci: check task::Id conditional compilation

- tokio-util/src/codec/framed.rs
I cannot construct `FramedParts` in order to construct `Framed` if my codec doesn't implement `Encoder<I>` for some `I`, despite the fact that I can create a `Framed` for the same codec, and it will simply not implement `Sink`.
Remove the bound.
> tokio-util: Remove Encoder bound on FramedParts constructor

- tokio/build.rs
- tokio/src/macros/cfg.rs
See [this comment](https://github.com/tokio-rs/tokio/pull/5282#issuecomment-1345448329). 
The aim of this PR is to use the `target_has_atomic` feature on Rust 1.60, in order to avoid using a less efficient strategy (e.g. mutexes) on platforms that do actually have atomic U64. It changes the `cfg_(not_)has_atomic_u64` to incorporate `target_has_atomic = "64"` based on a build flag.
> Change flags for having an atomic u64

- tokio/tests/rt_metrics.rs
This test is flaky, and that's annoying.
> metrics: make `num_idle_blocking_threads` test less flaky

- tokio/src/runtime/task/harness.rs
- tokio/src/runtime/task/state.rs
The JOIN_WAKER bit in State is unlike the other bits (e.g. RUNNING, COMPLETE),
which indicate a binary condition. The JOIN_WAKER bit is part of a protocol that
enables safe access to the waker field of a task (described in task/mod.rs).
Although currently it so happens that if JOIN_WAKER is set, then there is a
waker in the waker field, this is incidental and can change in the future.
Rename has_join_waker to a more neutral is_join_waker_set to decouple the
meaning of the bit being set from having a waker in the waker field.
> task: refactor: rename State::has_join_waker to State::is_join_waker_set

- tokio/src/signal/registry.rs
- tokio/src/signal/unix.rs
Not sure why it's here in the first place, but it doesn't do anything since `Globals` is `Unpin`.
> signal: remove redundant Pin around globals

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/pr-audit.yml
- .github/workflows/stress-test.yml
actions-rs actions are not maintained and will not be available in the future due to the use of node12.
https://github.com/actions-rs/toolchain/issues/216
https://old.reddit.com/r/rust/comments/vyx4oj/actionsrs_organization_became_unmaintained/ig54zv7/
- Use [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) instead of actions-rs/toolchain
- Use cargo/cross directly instead of actions-rs/cargo
- Use [rustsec/audit-check](https://github.com/rustsec/audit-check) (fork of actions-rs/audit-check) instead of actions-rs/audit-check
Also use [taiki-e/install-action](https://github.com/taiki-e/install-action) for installation of cross to avoid https://github.com/cross-rs/cross/issues/1177 and reduce CI time. (we already use this action for installations such as cargo-hack, …
> ci: remove uses of unmaintained actions-rs actions

- tokio/src/sync/broadcast.rs
- tokio/src/sync/mod.rs
- tokio/src/sync/mpsc/mod.rs
It's a common source of confusion that mpsc channels also work when there's only one sender.
> sync: document that there is no spsc and spmc channel

- tokio/src/process/unix/mod.rs
"Actually a pipe __and__ not a File."  -> "Actually a pipe __is__ not a File."
Signed-off-by: Changyuan Lyu <changyuanl@google.com>
> chore: fix typo in `process::imp::Pipe` comment

- .github/workflows/ci.yml
- .github/workflows/loom.yml
- .github/workflows/stress-test.yml
Fixes "The `set-output` command is deprecated" and "The `save-state` command is deprecated" warnings.
> ci: update Swatinem/rust-cache action to v2

- tokio/docs/reactor-refactor.md
- tokio/src/runtime/io/mod.rs
- tokio/src/runtime/io/registration.rs
- tokio/src/runtime/io/scheduled_io.rs
The global flag is still remaining, and used to prevent duplicated shutdown and new io operations after shutdown.
On shutdown, the driver flip the shutdown flag of every pending io operations and wake them to fail with shutdown error.
Fixes: #5227
I was load testing my tokio based RTMP ingestion server by attaching ffmpeg publishers each emits 4Mbps TCP traffic on AWS c5.4xlarge 16vcpu instance. With 100 publishers its CPU usage is about 7%. With 1k publishers(4Gbps) it's full 100%. Below is a flamegraph I've take from the scenario.
Here's a flamegraph from same 1k scenario after applying this PR. Its CPU usage is about 80%.
It's an implementation of @carllerche's [suggestion](https://github.com/tokio-rs/tokio/issues/5227#issuecomment-1337758117) from the issue. The global flag still …
> remove frequent global is_shutdown flag check on io operations

- tokio/src/fs/read_dir.rs
When using `fs::read_dir`, `spawn_blocking` is called too often, resulting in poor performance.
Use chunks to reduce frequent `spawn_blocking` calls and improve performance.
I implemented `walkdir` using tokio and benchmarked it, and it was 3 to 5 times faster than the existing implementation.
Related Issues: #3664
> fs: use chunks in `fs::read_dir`

- .github/workflows/ci.yml
- tokio/src/runtime/task/id.rs
- tokio/src/runtime/task/mod.rs
This is a minor internal cleanup.
> rt: move task::Id into its own file

- tokio/src/runtime/context.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/thread_id.rs
- tokio/src/task/local.rs
- tokio/tests/rt_metrics.rs
The version provided by `std` has limitations, including no way to try to get a thread ID without panicking.
Replaces #5184
> rt: use internal ThreadId implementation

- .github/workflows/ci.yml
- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/net/windows/named_pipe.rs
The `pipe_mode` function would erase any previously set configuration option specified using the pipe_mode fit field. This patch fixes the builder to maintain the bit field when changing the pipe mode.
> net: fix named pipes server configuration builder

- tokio/src/loom/std/atomic_u64_static_once_cell.rs
The new ThreadId code from #5329 in tokio 1.24.0 assumes that `StaticAtomicU64` has `load` and `compare_exchange_weak` methods, which was not always the case. This was causing the following build failure:
```console
error[E0599]: no method named `load` found for struct `StaticAtomicU64` in the current scope
--> tokio-1.24.0/src/runtime/thread_id.rs:12:32
|
12 |         let mut last = NEXT_ID.load(Relaxed);
|                                ^^^^ method not found in `StaticAtomicU64`
|
::: tokio-1.24.0/src/loom/std/atomic_u64_static_once_cell.rs:5:1
|
5  | pub(crate) struct StaticAtomicU64 {
| --------------------------------- method `load` not found for this
error[E0599]: no method named `compare_exchange_weak` found for struct `StaticAtomicU64` in the current scope
--> …
```
> Fix ThreadId implementation on targets without atomicu64

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release fixes a compilation failure on targets without `AtomicU64` when using rustc older than 1.63. ([#5356])
[#5356]: https://github.com/tokio-rs/tokio/pull/5356
> chore: prepare Tokio v1.24.1

- tokio/src/net/tcp/listener.rs
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/listener.rs
- tokio/src/net/unix/stream.rs
Unlike documentation for other methods performing conversion from std types, docs for the `TcpSocket::from_std_stream` method do not warn about setting the socket in non-blocking mode.
The attached example also doesn't set the socket in non-blocking mode.
This change adds a suitable comment in the docs and sets the socket in non-blocking mode in the example.
> net: improve `from_std` docs

- tokio/src/sync/broadcast.rs
- tokio/tests/sync_broadcast.rs
Since the head index for each receiver isn't stored in a location accessible from the sender, we need to instead binary search for the last value with remaining readers.
Closes #5334
> Add broadcast::Sender::len

- .github/workflows/ci.yml
- tokio/build.rs
- tokio/src/util/mod.rs
Fixes #5373
Closes #5358 
- Add check for no_atomic_u64 & no_const_mutex_new (condition to atomic_u64_static_once_cell.rs is compiled)
- Allow unused_imports in TARGET_ATOMIC_U64_PROBE. I also tested other *_PROBE and found no other errors triggered by -D warning.
- Fix cfg of util::once_cell module
> tokio: fix remaining issues about atomic_u64_static_once_cell.rs

- tokio/src/runtime/handle.rs
- tokio/src/runtime/runtime.rs
- tokio/src/runtime/task/join.rs
- tokio/src/task/join_set.rs
- tokio/src/task/local.rs
- tokio/src/task/spawn.rs
Trying again with new way to phrase this.
> task: clarify doc about tasks starting immediately

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/io/split.rs
Fixes #5372 
Adds `T: Unpin` bound to `ReadHalf::unsplit`. 
Similar functions in `futures` also have the same bound, I believe this should be a reasonable fix here.
https://docs.rs/futures/latest/futures/io/struct.ReadHalf.html#impl-ReadHalf%3CT%3E
https://docs.rs/futures/latest/futures/stream/struct.SplitStream.html#impl-SplitStream%3CS%3E
> io: add `T: Unpin` bound to ReadHalf::unsplit

- tokio/Cargo.toml
This updates nix (dev-dependency) to 0.26.
> chore: update nix to 0.26

- tokio/tests/sync_broadcast.rs
- tokio/tests/sync_watch.rs
These tests rely on unwinding and will fail if built with panic-abort.
The Rust toolchain for Android is built with panic-abort and these tests will fail without these changes.
Add a `cfg` annotation that only enables these tests if `panic = "unwind"`.
> Condition unwinding tests on `cfg(panic = "unwind")`

- tokio/src/fs/file/tests.rs
- tokio/src/io/blocking.rs
- tokio/src/io/stdio_common.rs
While working on [Spacedrive](https://github.com/spacedriveapp/spacedrive/), we were noticing some oddities during file reading in regards to encryption and decryption.
We use a stream reader where 1MiB of the source file is read, encrypted, written and this repeats until the end. We arguably need to use `read` for this, as opposed to `read_exact`, as we need to know the exact amount of bytes read *and* guarantee that if the full 1MiB isn't read, the buffer still contains valid data.
I noticed some oddities while calling `read`, and that it was only reading 16KB at a time. This would have been fine, but this results in 64 `read` calls until the 1MiB buffer is populated.
The 64 read calls to populate a 1MiB buffer turned out to be extremely slow. By increasing the buffer size to 2MiB, we …
> io: increase `MAX_BUF` from `16384` to `2MiB`

- tokio/src/runtime/metrics/batch.rs
- tokio/src/runtime/metrics/mock.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/metrics/worker.rs
- tokio/src/runtime/scheduler/multi_thread/queue.rs
The documentation of `steal_count` does not match what is actually counted.
Fix the documentation of `steal_count`.
Additionally, add `steal_operations` as a metric to track what `steal_count` was originally documented to count.
Having both metrics allows us to see some effects of different stealing policies on work-stealing.
Closes #5281
> metrics: Fix steal_count description and add steal_operations metric

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- rt: fix runtime metrics reporting ([#5330])
- sync: add `broadcast::Sender::len` ([#5343])
- fs: increase maximum read buffer size to 2MiB ([#5397])
[#5330]: https://github.com/tokio-rs/tokio/pull/5330
[#5343]: https://github.com/tokio-rs/tokio/pull/5343
[#5397]: https://github.com/tokio-rs/tokio/pull/5397
> chore: prepare for Tokio v1.25.0 release

- tokio/src/process/mod.rs
As mentioned in #5406, the documentation of `process::Command` does not respect the borrow checker.
I've changed this, analogously to the standard library, to directly call `output().await.unwarp()`. This should now lead to usable examples.
The alternative would have been to create a `let mut command` binding and then calling `command.somefunction()`, which I found to be less readable.
Closes: #5406
> Clarify `process::Command` docs (fixing #5406)

- .cirrus.yml
- [Use image_family for FreeBSD image in Cirrus CI](https://github.com/tokio-rs/tokio/commit/f9f7035e36d188d9c59369cf118b8c9d5d28cb55) -- simplify config 
- [Do not trigger Cirrus CI on branches other than master and tokio-.*](https://github.com/tokio-rs/tokio/commit/16a8b19883d6725e18bffa79036c84097cf8f8da) -- adopt a similar behavior as GitHub workflows
> ci: update Cirrus CI config

- tokio/src/runtime/driver.rs
- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/mod.rs
- tokio/src/runtime/time/source.rs
- tokio/src/runtime/time/tests/mod.rs
- tokio/src/time/clock.rs
- tokio/src/time/sleep.rs
This patch removes `Arc` from Tokio's internal clock source. Instead of cloning `Clock` when needed, a reference is passed into functions that need to get the current instant.
> rt: remove Arc from Clock

- tokio-util/src/io/sink_writer.rs
Per review comment https://github.com/tokio-rs/tokio/pull/5070#discussion_r997835198:
> Adding a wake call here will be a busy loop that consumes 100% CPU
> waiting for it to become ready. We shouldn't do that.
Furthermore, according to https://docs.rs/futures-sink/latest/futures_sink/trait.Sink.html#tymethod.poll_ready, poll_ready will make sure that the current task is notified.
Discussion: https://discord.com/channels/500028886025895936/500336346770964480/1072534504981418024
> bugfix: Remove erroneous wake call in SinkWriter

- CONTRIBUTING.md
- tokio-stream/Cargo.toml
- tokio-stream/fuzz/.gitignore
- tokio-stream/fuzz/Cargo.toml
- tokio-stream/fuzz/fuzz_targets/fuzz_stream_map.rs
- tokio-stream/tests/stream_stream_map.rs
- tokio/Cargo.toml
- tokio/fuzz/.gitignore
- tokio/fuzz/Cargo.toml
- tokio/fuzz/fuzz_targets/fuzz_linked_list.rs
- tokio/src/fuzz.rs
- tokio/src/lib.rs
- tokio/src/util/linked_list.rs
This change ports fuzz tests from the black-box fuzzing framework, proptest-rs over to use the grey-box fuzzing framework cargo-fuzz.
Currently the proptest-rs fuzzing framework only works in black-box mode and does not support coverage-driven feedback. This results in fairly limited performance in terms of the coverage of fuzzing.
This change ports proptest-rs test harnesses over to use cargo-fuzz which can make use of coverage information to optimise fuzzing inputs on the fly.
> stream|tokio: Port proptest fuzz harnesses to use cargo-fuzz

- tokio/src/runtime/mod.rs
- tokio/src/runtime/runtime.rs
The current documentation around this is confusing because it does not
clearly differentiate the cases in which runtime shutdown blocks and
background work continues to run after runtime shutdown.
- Clear this up.
- Use more consistent wording.
- Remove a section refering to runtime internals because it is not
relevant for users, uses terminology that is not defined anywhere, and is
out of date.
closes https://github.com/tokio-rs/tokio/issues/4231
> clarify what happens to spawned work during runtime shutdown

- examples/Cargo.toml
- tokio/Cargo.toml
We may want to wait for the windows-sys update in the dependencies before merging.
- mio: https://github.com/tokio-rs/mio/pull/1644
- parking_lot_core: https://github.com/Amanieu/parking_lot/pull/368
> chore: update windows-sys to 0.45

- tokio/src/runtime/time/entry.rs
- tokio/src/time/sleep.rs
Due to cache-aligned padding, `Sleep` is quite large.
Sleep totals 640 bytes, a majority of it is padding caused by `CachePadded` alignment.
<details>
<summary>Breakdown of cache usage</summary>
Breakdown of the size and padding made with help by @Nilstrieb using `-Zprint-type-sizes`
```
print-type-size type: `tokio::time::Sleep`: 640 bytes, alignment: 128 bytes
print-type-size     field `.entry`: 512 bytes
print-type-size     field `.inner`: 16 bytes
print-type-size     end padding: 112 bytes
print-type-size type: `tokio::runtime::time::entry::TimerEntry`: 512 bytes, alignment: 128 bytes
print-type-size     field `.driver`: 0 bytes
print-type-size     field `._m`: 0 bytes
print-type-size     field `.inner`: 384 bytes
print-type-size     field `.initial_deadline`: 16 bytes
print-type-size …
```
> remove double store of deadline, saving 128 bytes

- tokio/src/sync/mutex.rs
- tokio/src/sync/rwlock/owned_read_guard.rs
- tokio/src/sync/rwlock/owned_write_guard.rs
- tokio/src/sync/rwlock/owned_write_guard_mapped.rs
- tokio/src/sync/rwlock/read_guard.rs
- tokio/src/sync/rwlock/write_guard.rs
- tokio/src/sync/rwlock/write_guard_mapped.rs
- tokio/src/sync/semaphore.rs
`#[clippy::has_significant_drop]` tells that a structure should be considered when evaluating some lints. Examples of such behavior are the existent `clippy::significant_drop_in_scrutinee` and the soon-to-be-finished https://github.com/rust-lang/rust-clippy/issues/9399.
> Mark `MutexGuard` with `#[clippy::has_significant_drop]`

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
Closes: #5388
This release fixes an accidental breaking change where `UnwindSafe` was accidentally removed from `CancellationToken`.
- codec: add `Framed::backpressure_boundary` ([#5124])
- io: add `InspectReader` and `InspectWriter` ([#5033])
- io: add `tokio_util::io::{CopyToBytes, SinkWriter}` ([#5070], [#5436])
- io: impl `std::io::BufRead` on `SyncIoBridge` ([#5265])
- sync: add `PollSemaphore::poll_acquire_many` ([#5137])
- sync: add owned future for `CancellationToken` ([#5153])
- time: add `DelayQueue::try_remove` ([#5052])
- codec: fix `LengthDelimitedCodec` buffer over-reservation ([#4997])
- sync: impl `UnwindSafe` on `CancellationToken` ([#5438])
- util: remove `Encoder` bound on `FramedParts` constructor ([#5280])
- io: add lines example for `StreamReader` ([#5145])
[#4997]: …
> Prepare tokio-util v0.7.5

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
This release fixes a compilation failure in 0.7.5 when it is used together with Tokio version 1.21 and unstable features are enabled. ([#5445])
[#5445]: https://github.com/tokio-rs/tokio/pull/5445
> chore: prepare tokio-util v0.7.6

- tokio-util/src/codec/framed.rs
This PR reverts an accidental breaking change #5280.
> Revert "util: remove `Encoder` bound on `FramedParts` constructor"

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
This release reverts the removal of the `Encoder` bound on the `FramedParts` constructor from [#5280] since it turned out to be a breaking change. ([#5450])
[#5280]: https://github.com/tokio-rs/tokio/pull/5280
[#5450]: https://github.com/tokio-rs/tokio/pull/5450
> chore: prepare tokio-util v0.7.7

- .github/workflows/ci.yml
> CI: Always assume minor release in semver check

- tokio/src/task/local.rs
Typo in the example for the `spawn_local` function. Where the word unsend is being used, which means the act of undoing a send. See: https://en.wiktionary.org/wiki/unsend
Change to `unsent`.
Edit: change to `nonsend`.
> fix: fix wording with 'unsend'

- benches/Cargo.toml
- benches/sync_mpsc_oneshot.rs
This additional benchmark exercises a common request/reply pattern using an MPSC for requests along with a one-shot payload as a reply mechanism. When used in a current threaded scenario, the bench is 17 times faster on my machine than when using the multi-threaded runtime and one worker thread. Not only that, but if I increase the number of worker threads to 6, performance degrades further.
Does this suggest a scheduling problem with the multi-threaded runtime?
No matter what, hopefully, the benchmarks are a useful addition.
> Benchmark for oneshot highlighting runtime disparities

- tokio/src/sync/mpsc/bounded.rs
- tokio/src/sync/mpsc/unbounded.rs
- tokio/src/sync/mutex.rs
- tokio/src/sync/oneshot.rs
Someone recently mentioned on discord that they had trouble finding the `blocking_send` method because they searched for `send_blocking`.
> sync: add doc aliases for `blocking_*` methods

- tokio/src/runtime/context.rs
- tokio/src/sync/watch.rs
- tokio/src/util/rand.rs
See discussion in #5403 for context.
cc @tijsvd
Closes: #5403
> Reduce contention in watch channel

- tokio/src/sync/mutex.rs
- tokio/src/sync/rwlock.rs
- tokio/src/sync/rwlock/owned_read_guard.rs
- tokio/src/sync/rwlock/owned_write_guard.rs
- tokio/src/sync/rwlock/owned_write_guard_mapped.rs
- tokio/src/sync/rwlock/read_guard.rs
- tokio/src/sync/rwlock/write_guard.rs
- tokio/src/sync/rwlock/write_guard_mapped.rs
Currently, `MappedMutexGuard::map` can leak a tracing span, which can lead to a memory leak. This PR fixes that.
I'd also like to add a tracing span to the other guards and add a mapped owned guard, but that can happen in a follow-up PR.
> sync: don't leak tracing spans in mutex guards

- benches/Cargo.toml
- benches/sync_watch.rs
Benchmark related to PR #5464.
See issue #5403.
> Add a new benchmark to test mutex contention in `watch::Receiver`.

- tokio/src/net/windows/named_pipe.rs
- tokio/tests/net_named_pipe.rs
> Named Pipes: Support Message Read Mode

- tokio/src/net/windows/named_pipe.rs
> net: refactor named pipe builders to not use bitfields

- .github/workflows/ci.yml
This option doesn't do anything anymore after #5392.
> ci: remove PROPTEST_CASES from miri

- tokio/src/sync/notify.rs
- tokio/src/sync/tests/loom_notify.rs
- tokio/src/sync/tests/notify.rs
- tokio/src/util/linked_list.rs
`tokio::sync::Notify` has an internal waiters queue locked behind a mutex. `Notify::notify_waiters` is a function to notify all waiters from this queue. It first acquires the lock, then removes waiters from the queue and wakes them up. However, the whole process is done in batches of 32 waiters to avoid deadlocks. The function has to release the lock before waking up a batch and re-acquire it before proceeding to the next one. In this short timespan, another thread can acquire the lock and modify the queue or the internal state. This leads to the following issues:
1. **Spurious wake-ups**. This is an issue reported in #5396. A single `notify_waiters` call can notify multiple futures which are created and awaited sequentially. For example, both futures from the following code can complete: …
> sync: make `notify_waiters` calls atomic

- tokio/src/sync/broadcast.rs
`broadcast` channel does not require sent values to be `Sync`.
> sync: fix docs for Send/Sync bounds in broadcast

- tokio/src/sync/notify.rs
> Drop wakers after unlocking the mutex in Notify

- tokio/src/io/async_fd.rs
Someone mentioned that it would be nice if the example included an `AsyncRead` impl.
> io: improve AsyncFd example

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
- time: remove `Unpin` bound on `Throttle` methods ([#5105])
- time: document that `throttle` operates on ms granularity ([#5101])
[#5105]: https://github.com/tokio-rs/tokio/pull/5105
[#5101]: https://github.com/tokio-rs/tokio/pull/5101
> Prepare tokio-stream 0.1.12

- tokio/src/io/util/copy_bidirectional.rs
I didn't particularly like putting an artificial structure just to convert `Poll` into a `Future`. I think it's clearer with `poll_fn`.
Use `poll_fn` rather than a manual `Future` implementation.
> Use poll_fn in copy_bidirectional

- tokio/src/lib.rs
Document which platforms are supported.
@Thomasdezeeuw Are there any nuances here that we should be careful about?
[View rendered version](https://deploy-preview-5483--tokio-rs.netlify.app/tokio/#supported-platforms)
> Document supported platforms

- .github/workflows/ci.yml
The `--exclude` flags for `cargo-semver-checks` here were previously only needed due to a bug in the `cargo-semver-checks` CLI logic.
The correct behavior (available as of v0.18.3) for `cargo-semver-checks` is to ignore `publish = false` crates when scanning a workspace, *unless* those crates are specifically selected for checking.
All the crates being excluded here are `publish = false`. That makes them excluded by default, so all `--exclude` flags are no-ops.
Remove the unnecessary `--exclude` flags.
> Remove no-longer-necessary cargo-semver-checks flags.

- tokio/src/sync/broadcast.rs
- tokio/src/sync/mpsc/mod.rs
- tokio/src/sync/oneshot.rs
- tokio/src/sync/watch.rs
Some users mentioned that the behavior of a channel when the receivers
and/or senders are dropped isn't explicitly documented.
This change adds wording to the documentation for each channel in the
sync module, explaining under which conditions messages in a channel are
dropped with respect to dropping the senders and the receivers.
Refs: #5490
> sync: document drop behavior for channels

- tokio/src/macros/join.rs
- tokio/src/macros/try_join.rs
- tokio/tests/macros_join.rs
- tokio/tests/macros_try_join.rs
This fixes #5502, i. e. `join!()` and `try_join!()` emitting `loop {}`. It does so in two ways:
1. The current macro implemention entry points are changed to not accept empty invocations
2. New entry points for empty invocations are added
> fix empty `join!` and `try_join!`

- tokio-macros/src/lib.rs
- tokio/src/runtime/runtime.rs
Fixes https://github.com/tokio-rs/tokio/issues/5446
> Document the nature of the main future

- .github/workflows/ci.yml
- tokio/Cargo.toml
- tokio/tests/net_named_pipe.rs
This fixes a compile failure in our test suite where there is a mismatch between two versions of the c_void type.
> net: fix test compilation failure

- tokio/src/signal/unix.rs
- tokio/src/signal/windows.rs
Resolve Issue #5430 and to update the documentation to point to how to create Streams, using the Tokio-stream crate
Update documentation for Windows + Unix signals to not include "streams" since they do not implement the Stream Trait, and give a link to the acceptable Tokio-stream wrapper.
> Updated Documentation for Signals

- tokio/src/io/stdio_common.rs
These tests take a very long time under miri, but the code they're testing isn't unsafe, so there isn't any reason to run them under miri.
> io: ignore SplitByUtf8BoundaryIfWindows test on miri

- tokio/src/time/timeout.rs
Add documentation to `tokio::time::{timeout, timeout_at}`
Closes #5495
Add to documentation the guarantee that future returned from `tokio::time::{timeout, timeout_at}` will complete immediatelly with `Ok` value if provided future completes immediatelly.
> time: document immediate completion guarantee for timeouts

- tokio/src/runtime/coop.rs
- tokio/src/runtime/metrics/runtime.rs
- tokio/src/runtime/metrics/scheduler.rs
- tokio/tests/rt_metrics.rs
This change adds a new runtime metric which counts the number of times that tasks exhaust their budgets and are forced to yield back to the runtime.
This metric is useful for debugging performance issues in many types of applications.
> metrics: add a new metric for budget exhaustion yields

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
- macros: fix empty `join!` and `try_join!` ([#5504])
- sync: don't leak tracing spans in mutex guards ([#5469])
- sync: drop wakers after unlocking the mutex in Notify ([#5471])
- sync: drop wakers outside lock in semaphore ([#5475])
- fs: add `fs::try_exists` ([#4299])
- net: add types for named unix pipes ([#5351])
- sync: add `MappedOwnedMutexGuard` ([#5474])
- chore: update windows-sys to 0.45 ([#5386])
- net: use Message Read Mode for named pipes ([#5350])
- sync: mark lock guards with `#[clippy::has_significant_drop]` ([#5422])
- sync: reduce contention in watch channel ([#5464])
- time: remove cache padding in timer entries ([#5468])
- time: Improve `Instant::now()` perf with test-util ([#5513])
- io: use `poll_fn` in `copy_bidirectional` ([#5486])
- net: refactor named pipe …
> chore: prepare for Tokio v1.26.0 release

- tokio/src/net/tcp/split.rs
- tokio/src/net/tcp/split_owned.rs
- tokio/src/net/unix/split.rs
- tokio/src/net/unix/split_owned.rs
Currently, the docs for the `ready` method on read/write halves of TcpStream/UnixStream suggest using this method to avoid splitting a socket, which is already split. This PR changes the docs to better explain the usage of this method.
> net: document usage of `ready` with stream halves

- tokio/src/process/mod.rs
The noun `regard` means "respect" or "relation", so saying `with regard to` is like saying "with respect to" or "with relation to". The plural form of this noun, `regards`, means "good wishes" or "affection", which is significantly different from the meaning of the singular form.
`with regards` => `with regard to`.
> Fix typo in doc: "with regards"

- tokio/tests/fs_file.rs
One of the `tokio::fs` tests began to spuriously fail in the CI after #5493 was merged. I believe it comes from dropping `File` with the same fd twice. This PR should fix this.
cc @brodybits
> fs: fix `File::from_raw_fd` test

- tokio/src/sync/rwlock/owned_write_guard.rs
- tokio/src/sync/rwlock/write_guard.rs
- tokio/src/sync/rwlock/write_guard_mapped.rs
- tokio/tests/sync_rwlock.rs
Adds `RwLockWriteGuard::{downgrade_map, try_downgrade_map}`.
These functions allow the following code to work:
```rust
impl T {
fn try_get(&self) -> Option<&U> { ... }
}
pub async fn foo(lock: RwLock<T>) -> RwLockReadGuard<U> {
// Check with a read lock
if let Ok(value) = RwLockReadGuard::try_map(lock.read().await, |value| value.try_get()) {
return value;
}
// Else "upgrade" and check if it was changed in the meantime
let guard = lock.write().await;
if let Ok(value) = RwLockWriteGuard::try_downgrade_map(guard, |value| value.try_get()) {
return value;
}
// Use `guard` mutably
// ...
}
```
The code uses a double-checked lock on a `RwLock` to do some action, and then returns a mapped read guard to the inner data.
With the current suite of functions, we can't easily perform the second check …
> Add `RwLockWriteGuard::{downgrade_map, try_downgrade_map}`.

- tokio/src/time/timeout.rs
**This commit**
- Replace instances of "immediatelly" with "immediately".
> time: fix typo

- tokio/build.rs
- tokio/src/fs/file.rs
- tokio/src/net/tcp/listener.rs
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/listener.rs
- tokio/src/net/unix/pipe.rs
- tokio/src/net/unix/stream.rs
- tokio/src/process/mod.rs
- tokio/src/process/unix/mod.rs
The new release of socket2 works with these traits rather than the old `AsRaw*` ones.
> Add implementations of AsFd/AsHandle/AsSocket

- tokio/src/doc/os.rs
- tokio/src/io/async_fd.rs
- tokio/src/io/stderr.rs
- tokio/src/io/stdin.rs
- tokio/src/io/stdout.rs
- tokio/src/net/windows/named_pipe.rs
Since Tokio added implementations of the new IO-safety traits to some types such as `TcpStream`, I think it makes sense to add implementations of these traits to all types which currently implement `AsRawFd`/`AsRawHandle`.
This PR adds those implementations to `tokio::io::{Stderr,Stdin,Stdout}`, `NamedPipeClient`, `NamedPipeServer` and `AsyncFd`.
> io: add missing AsFd/AsHandle impls

- CONTRIBUTING.md
One of the first things a new contributor will want to do, is to execute the tests for the project. We can make tokio more accessible to newbies, by making running tests as simple as possible. 
This PR amends the existing Contributing guide, by adding links to fundamental testing concepts in Rust, and information about conditional compilation attributes and how to use them to run tests with cargo.
> Make Contributing guide more newbie friendly

- tokio/src/doc/os.rs
- tokio/src/fs/file.rs
- tokio/src/fs/mod.rs
- tokio/src/fs/open_options.rs
- tokio/src/fs/symlink_dir.rs
- tokio/src/fs/symlink_file.rs
- tokio/src/io/stderr.rs
- tokio/src/io/stdin.rs
- tokio/src/io/stdout.rs
- tokio/src/macros/cfg.rs
- tokio/src/net/tcp/listener.rs
- tokio/src/net/tcp/socket.rs
- tokio/src/net/tcp/stream.rs
- tokio/src/net/udp.rs
- tokio/src/process/mod.rs
This PR makes all Windows-specific documentation visible in Unix builds similarly to the docs for named pipes.
Items which should be now visible:
- `tokio::fs::symlink_dir`
- `tokio::fs::symlink_file`
- `tokio::fs::OpenOptions` methods (custom_flags, access_mode, share_mode, attributes, security_qos_flags)
- `{AsRawHandle, FromRawHandle}` impls for `tokio::fs::File`
- `AsRawHandle` impl for `tokio::io::{Stdin, Stdout, Stderr}`
- `AsRawSocket` impl for `tokio::net::{TcpListener, TcpStream, UdpSocket}`
- `{AsRawSocket, FromRawSocket, IntoRawSocket}` for `tokio::net::TcpSocket`
- `AsRawHandle` impl for `tokio::process::{ChildStdin, ChildStdout, ChildStderr}`
- `tokio::process::Command::creation_flags`
- `tokio::process::Child::raw_handle`
[View rendered …
> tokio: make all windows docs visible in unix builds

- tokio/src/runtime/task/join.rs
The `AbortHandle` API is currently only exposed through `JoinSet`. This makes custom, user-defined implementations of `JoinSet`-like wrappers impossible.
As mentioned in #4530, the `abort_handle` method is simply made public.
> task: make `JoinHandle::abort_handle` public

- tokio/Cargo.toml
- tokio/src/net/udp.rs
- tokio/tests/udp.rs
closes #5491
Update: amended to add `try_peek_from()` as discussed on Discord.
~The prerequesite addition to `socket2` has landed on their `v0.4.x` branch but, as of writing, has not been released yet. This will remain a draft until that is released, but the API and documentation is ready for review.~
Running Clippy as instructed by `CONTRIBUTING.md` gives the following error:  
```
> cargo +1.49.0 clippy --all --tests --all-features
warning: /home/abonander/rust/tokio/tokio-test/Cargo.toml: unused manifest key: package.rust-version
warning: /home/abonander/rust/tokio/tokio-macros/Cargo.toml: unused manifest key: package.rust-version
warning: /home/abonander/rust/tokio/tokio/Cargo.toml: unused manifest key: package.rust-version
warning: /home/abonander/rust/tokio/tokio-util/Cargo.toml: …
```
> net: add `UdpSocket::peek_sender()`

- tokio/src/fs/read_dir.rs
The implementation of Tokio's ReadDir assumes that ReadDir from std is fused, but that's not the case on Windows. This change wraps the std iterator in `std::iter::Fuse` to make its usage correct.
I don't know how to write a reliable test for it, but I have verified that the example from #5473 does not run indefinitely after this change.
Fixes: #5473
> fs: fuse std iterator in `ReadDir`

- tokio/src/macros/select.rs
This adds a precise definition of cancellation safety to the docs of `select!`.
cc @yoshuawuyts
> macros: define cancellation safety

- tokio/Cargo.toml
- tokio/src/io/util/read_until.rs
- tokio/src/util/memchr.rs
- tokio/src/util/mod.rs
We have a general policy of biasing towards fewer dependencies. Therefore, I think it makes sense to just use the libc implementation of `memchr` rather than pulling in an entire crate just for the implementation of `AsyncRead::read_until`.
I added a simple wrapper around the libc memchr function and a few tests to sanity check the wrapper.
> io: use memchr from libc

- tests-build/tests/fail/macros_invalid_input.rs
- tests-build/tests/fail/macros_invalid_input.stderr
- tokio-macros/src/entry.rs
- tokio/tests/macros_rename_test.rs
Currently Tokio supports renaming the crate inside the macro with the `crate` attribute. I was playing around with a personal library that simplifies some stuff around multiple macros, including the Tokio macro.
To implement this with macro hygiene in mind I was re-exporting Tokio, but turns out Tokio only accepts idents, not full paths.
The solution was quite simple, just let Tokio accept paths, by using `syn::Path`, instead of only accepting an ident. There should be no functional change, as idents can also be parsed as paths.
> Accept path as crate rename as well

- tokio-test/src/io.rs
- tokio-test/tests/io.rs
Clear `waiting` after completion of the current wait allowing subsequent waits to be registered instead of being discarded.
The `Mock` in `tokio-test::io` won't work properly with multiple `Action::Wait()` actions.
Example using `Builder::wait()` 
```rust
let mut mock = Builder::new()
.wait(Duration::from_secs(10))
.read(b"hello ")
.wait(Duration::from_secs(10))
.read(b"world!")
.build();
let mut buf = [0; 256];
let start = Instant::now();
let n = mock.read(&mut buf).await.expect("read 1");
let n = mock.read(&mut buf).await.expect("read 2");
// `start.elapsed()` will be something around 10s instead of the expected 20s
```
The first commit in this PR includes two tests regarding the `wait` issue, one of which `multiple_wait` is equivalent to the example above and fails without the fix …
> Tokio test mock wait

- tokio-util/src/sync/cancellation_token/tree_node.rs
Deadlock safety requires that the parent is locked before the child, but we can still use `try_lock` to attempt to lock the parent without releasing the child.
> sync: try to lock the parent first in CancellationToken

- tokio-util/tests/time_delay_queue.rs
There's a new CI failure on master.
<details>
<summary>CI Output</summary>
```
Running tests/time_delay_queue.rs (target/wasm32-wasi/debug/deps/time_delay_queue-f0c21ef322a44873.wasm)
running 30 tests
test compact_change_deadline ... ok
test compact_expire_empty ... ok
test compact_remove_empty ... ok
test compact_remove_remapped_keys ... ok
test delay_queue_poll_expired_when_empty ... ok
test expire_first_key_when_reset_to_expire_earlier ... ok
test expire_second_key_when_reset_to_expire_earlier ... ok
test expires_before_last_insert ... ok
test insert_after_ready_poll ... ok
test insert_before_first_after_poll ... ok
test insert_in_past_after_poll_fires_immediately ... ok
test insert_in_past_fires_immediately ... ok
test multi_delay_at_start ... ok
test multi_immediate_delays ... ok …
```
> time: fix repeatedly_reset_entry_inserted_as_expired test

- tokio-stream/Cargo.toml
- tokio-stream/src/stream_map.rs
- tokio-test/Cargo.toml
- tokio-util/Cargo.toml
I want to close #5560, so tokio-stream, tokio-util, and tokio-test can be updated to the 2021 edition.
1. I grepped for traits that are already included in the Prelude (TryInto, TryFrom and FromIterator) and removed shortened paths. There weren't any imports that had those traits. 
2. I ran `cargo fix --edition` on the mentioned crates. I did see a disjoint capture change in the closure here: https://github.com/tokio-rs/tokio/blob/b489acb46cb7e932808a1e9c8a4655089375d53c/tokio-util/src/sync/reusable_box.rs#L65 but I changed it back since it seems fine (I'm not entirely sure though). Other than that, I didn't see any more changes.
I'm not sure if there are more things to do. I would be happy to work on them.
Closes #5560
> Update stream, util, test to 2021 edition

- tokio/src/runtime/blocking/pool.rs
In a previous PR (#4128), the `spawn.location` field on task spans was
structured into 3 separate fields for the `file`, `line`, and `col`.
There is a separately created span for blocking tasks which was missed.
This caused tasks created with `spawn_blocking` to appear in
`tokio-console` without a location, but with an additional "free form"
field containing the formatted source code location.
This change modifies this span to use the same format. The span creation
needs to be separate from the other task spans because it records the
function name. This information is useful in the `spawn_blocking` case,
but can be "catastrophically long" in the `async fn` case and was
removed in #3074.
> tracing: fix `spawn_blocking` location fields

- tokio/src/io/util/copy.rs
- tokio/src/io/util/copy_buf.rs
To explain differences between `tokio::io` functions `copy` and `copy_buf`
> add details to docs of `tokio::io::copy[_buf]`

- tokio/src/io/mod.rs
`ReaderStream` and `StreamReader` from the crate `tokio_util` are
the simplest and most convenient adaptors for creating a `Stream`
out of `AsyncRead`, I overlooked it at first, because `tokio::io`
docs point to the `tokio_util::codec` module, which seemed
overkill at first sigh.
So I think it would be cool to also recommend `ReaderStream` and
`StreamReader`, because they are, IMO, the simplest answer for
the most general (and basic) use case.
> cite `ReaderStream` and `StreamReader` in `tokio::io` docs

- tokio/src/runtime/time/wheel/mod.rs
The condition checked in the and_then() call is the same as is checked in the match below, so we can clean it up by just matching on next_expiration() directly.
> time: clean up redundant check in Wheel::poll()

- tokio-macros/Cargo.toml
- tokio-macros/src/entry.rs
- tokio-macros/src/select.rs
syn 2.0 has been released.
Update tokio-macros to syn 2.0. Required first [bumping tokio's MSRV](https://github.com/tokio-rs/tokio/pull/5559).
> macros: update syn

- tokio/src/sync/tests/semaphore_batch.rs
The maximum number of permits is `(usize::MAX >> 3)`, not `(usize::MAX >> 2)`.
> sync: fix `Semaphore::MAX_PERMITS` test

- tokio/src/runtime/time/entry.rs
- tokio/src/runtime/time/tests/mod.rs
- tokio/src/time/interval.rs
- tokio/src/time/sleep.rs
- tokio/tests/time_interval.rs
When `tokio::time::Interval::poll_tick()` returns `Poll::Pending`, it schedules itself for being woken up again through the waker of the passed context, which is correct behavior. However when `Poll::Ready(_)` is returned, the interval timer should be reset but not scheduled to be woken up again as this is up to the caller.
Currently, resetting the timer always involves reregistering the last waker which polled the internal `Sleep` to be woken up on completion.
This PR fixes the bug by introducing a `reset_without_reregister` method on `TimerEntry` which is called by `Intervall::poll_tick(cx)` in case the delay poll returns `Poll::Ready(_)`.
Closes: #5551
> time: fix wake-up with interval on `Ready`

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
This release bumps the MSRV of Tokio to 1.56. ([#5559])
- io: add `async_io` helper method to sockets ([#5512])
- io: add implementations of `AsFd`/`AsHandle`/`AsSocket` ([#5514], [#5540])
- net: add `UdpSocket::peek_sender()` ([#5520])
- sync: add `RwLockWriteGuard::{downgrade_map, try_downgrade_map}` ([#5527])
- task: add `JoinHandle::abort_handle` ([#5543])
- io: use `memchr` from `libc` ([#5558])
- macros: accept path as crate rename in `#[tokio::main]` ([#5557])
- macros: update to syn 2.0.0 ([#5572])
- time: don't register for a wakeup when `Interval` returns `Ready` ([#5553])
- fs: fuse std iterator in `ReadDir` ([#5555])
- tracing: fix `spawn_blocking` location fields ([#5573])
- time: clean up redundant check in `Wheel::poll()` ([#5574])
- macros: define cancellation safety …
> chore: prepare Tokio v1.27.0

- tokio/src/net/unix/ucred.rs
We're proposing AIX on PowerPC as Tier-3 target (see https://github.com/rust-lang/compiler-team/issues/553). And we encountered build failure of tokio for AIX.
Implement AIX's version of `get_peer_cred` which is almost the same as FreeBSD's. Since AIX hasn't been officially accepted, this is in draft status.
> Support AIX for get_peer_cred

- tokio/src/net/udp.rs
- tokio/src/net/unix/datagram/socket.rs
- tokio/tests/udp.rs
- tokio/tests/uds_datagram.rs
Closes  #5563.
In order to supplies buffer with `length=0` to receive data on `UdpSocket` and `UnixDatagram`, `try_recv_buf_from` and `try_recv_buf` should be used.
Unfortunately, they require additional care compared to `standard recv` variants.
Two new methods `recv_buf` and `recv_buf_from` have been added to `UdpSocket` and `UnixDatagram`.
These provide the same ergonomic of `recv` and `recv_from`, without the constraint `buf.length > 0`.
> net: Add recv_buf for UdpSocket and UnixDatagram

- tokio/src/sync/watch.rs
> fix typo in `tokio::sync::watch::Sender` docs

- tokio/src/runtime/coop.rs
It looks like there's a spurious `CURRENT.with` autocompletion in the middle of the poll_proceed() doc comment.
Remove the typo.
> Fix typo in private poll_proceed() doc comment

- tokio/src/sync/broadcast.rs
Hey! This issue looked like a good place to get started contributing to Tokio. I think I've followed the contributing doc correctly, but let me know if anything is missing and I'll add it. :slightly_smiling_face: 
This PR implements a `same_channel` method for the broadcast channel senders and receivers, this method checks if two senders/receivers belong to the same channel.
Closes #5602
This method exists for Tokio's other channel types, but it's missing for the broadcast channel.
Added a `same_channel` method to both receivers and senders for the `sync::broadcast` channel, with a doc test for each.
> sync: add same_channel to broadcast channel

- .cirrus.yml
CI is failing:
```
pkg install -y bash curl
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating database digests format: . done
The following 2 package(s) will be affected (of 0 checked):
New packages to be INSTALLED:
bash: 5.2.15
Installed packages to be UPGRADED:
curl: 7.85.0 -> 7.88.1
Number of packages to be installed: 1
Number of packages to be upgraded: 1
The process will require 9 MiB more space.
3 MiB to be downloaded.
[1/2] Fetching curl-7.88.1.pkg: .......... done
[2/2] Fetching bash-5.2.15.pkg: .......... done
Checking integrity... done (0 conflicting)
[1/2] Upgrading curl from 7.85.0 to 7.88.1...
[1/2] Extracting curl-7.88.1: .......... done
[2/2] Installing bash-5.2.15...
[2/2] Extracting bash-5.2.15: .......... …
```
> Fix FreeBSD ci

- tokio-stream/fuzz/fuzz_targets/fuzz_stream_map.rs
This fuzz test touches some quadratic time code paths. This changes the test to limit the test size so that the test doesn't time out.
cc @silvergasp
> stream: update StreamMap fuzz test

- tokio/src/macros/select.rs
Using a nighly rustdoc the internal `BRANCHES` constant may leak into private documentation.
For background see https://github.com/serde-rs/serde/pull/2426.
Using the example from `select!` ([src](https://github.com/tokio-rs/tokio/blob/3b45e8614d45a44ebe6edf7b7939805f692f90ec/tokio/src/macros/select.rs#L151-L169)) and using `RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --no-deps --document-private-items` show the problem:
- Before the change:
- After the change:
Of course there may be other such instances, I haven't exhaustively searched for them.
> Hide constant in select! macro for docs

- tokio/src/lib.rs
- tokio/src/util/linked_list.rs
Fix the warnings you get when you run `cargo fuzz run fuzz_linked_list` in `/tokio/` directory
preparation for solving https://github.com/tokio-rs/tokio/issues/5601
I added documentation to solve `missing_docs` lint (I think that's what the lint was called). I also added `#[allow(unused_macros)]` to a couple of macros that were used inside unsafe block (clippy apparently can't see inside unsafe blocks).
> Fix fuzz warnings

- .github/workflows/ci.yml
A common source for iterating over a PR is to fail a basic test, this causes a lot of builds to fire off needlessly.
This defines a `basics` job which depends on jobs we want to pass before firing off more expensive ones, it has been added to other jobs as a dependency. In principle I think we could also add a fairly simple `cargo check --all-targets --workspace` for better feedback here.
> ci: Gate costly checks behind basic ones

- tokio-macros/src/entry.rs
- tokio-macros/src/lib.rs
This is a different stab at #4513.
We use syn to parse the signature into our own `ItemFn`, maintaining most of the existing API but avoiding parsing (and reparsing) all statements except the parts we are interested in.
For signature parsing, we rely almost entirely on `syn`. The only notable trouble is the parsing of inner attributes, for which I believe I've matched `syn`'s behavior: The inner attributes are expanded as outer attributes instead. In theory we could expand them as inner attributes to the newly generated function but that doesn't seem to be necessary and I did it like this to match the previous expansion more precisely.
As a basic test, [I modified the tinyhttp example](https://github.com/udoprog/tokio/commit/8f621c862e991f9abcb367a287d1bd065c7aa638) and put everything in …
> Make entrypoints more efficient part 2 (closes #4513)

- tokio/src/sync/semaphore.rs
The `OwnedSemaphorePermit` tracks the `Semaphore` from which it was acquired, but does not allow users to access it.
With this change I don't have to store both, saving some space.
> Allow getting the `Semaphore` from a `OwnedSemaphorePermit`.

- tokio-util/src/time/delay_queue.rs
- tokio-util/src/time/wheel/level.rs
- tokio-util/src/time/wheel/mod.rs
- tokio-util/src/time/wheel/stack.rs
- tokio-util/tests/time_delay_queue.rs
My goal is to implement an expiring LRU cache that uses a `DashMap` + `DelayQueue` with an optional maximum capacity. On capacity overflow, I want to remove the item that would've been next to expire. I described this issue in #5279.
Adding `DelayQueue::peek` allows for getting the `Key` that will expire next. In my usecase, a `DelayQueue<K>` + `DashMap<K, V>` is used, so after removing the next expiring key from the queue, it can also be used to remove it from the map because `K` is now known. I made an implementation that showcases this [here](https://github.com/Gelbpunkt/http-proxy/blob/delay-queue/src/expiring_lru.rs).
This implementation is based on `pop_entry_slot` and uses `peek` methods instead which don't touch the contents of the stack and levels.
> tokio-util: time: add `DelayQueue::peek`

- CONTRIBUTING.md
- tokio/src/macros/select.rs
In CI, we are using a newer version of Clippy than what is stated in the
contributions guide.
Additionally, it is no longer necessary to use Clippy from the MSRV. As
of Clippy 1.64, the `rust-version` field in Cargo.toml is respected.
The text and the command have been updated to reflect the current state
of CI and best practices.
> doc: Update Clippy version in contrib guide

- tokio/src/sync/broadcast.rs
- tokio/tests/sync_broadcast.rs
Currently, the `broadcast` channel drops wakers while holding the lock to the internal state. This can lead to a deadlock if a user provides a custom waker implementation, see #5429.
* If the old waker for a future has to be replaced, store the old waker on the side and drop it after releasing the lock,
* Notify waiting futures in batches, similarly to `Notify` and the IO driver.
> sync: avoid deadlocks in `broadcast` with custom wakers

- tokio/src/io/async_fd.rs
In #5512, `async_io` was exposed on various socket types. However, for our work on [ntpd-rs](https://github.com/pendulum-project/ntpd-rs) we would like this function to also be available on `AsyncFd`. We do some low-level epoll configuration there (specifically, listening for `libc::EPOLLPRI` on a separate file descriptor), so all we have is a file descriptor.
Expose the `registration`'s `async_io`. The implementation is a single line. I believe that the implementation of `Registration::async_io` correctly clears the readiness flag, and that therefore use of `AsyncFdReadyGuard` is not needed here.
> add async_io for AsyncFd

- tokio/src/io/util/read_to_end.rs
- tokio/src/io/util/vec_with_initialized.rs
- tokio/tests/io_read_to_end.rs
Fixes: #5594
Explained in #5594
Make `buf.reserve(32)` do an additional check with our original capacity, so we can tell read_to_end to allocate a small buffer to read before reading into the main buffer. Doing so allows us to not allocate again when we reach capacity at an EOF, since we don't allocate with the check and read nothing into the small buffer. If we do not have reach an EOF however, we append out read data and continue as normal.
> io: make read_to_end not grow unnecessarily

- tokio/src/task/join_set.rs
I recently wrote some code that boiled down to spawning a blocking task inside of an async task, which has undesired indentation and `unwrap`ping:
```rust
joinset.spawn(async move {
tokio::task::spawn_blocking(move || {
// blocking work
})
.await
.unwrap(/* Panic occurred; re-raising */)
});
```
This is better expressed as spawning the blocking task directly on the `JoinSet`. The above code can now be written as:
```rust
joinset.spawn_blocking(move || {
// blocking work
});
```
> Add `JoinSet::spawn_blocking`

- tokio-util/CHANGELOG.md
- tokio-util/src/time/wheel/level.rs
- tokio-util/src/time/wheel/mod.rs
- tokio-util/tests/time_delay_queue.rs
Fixes: https://github.com/tokio-rs/tokio/issues/5536
Experienced an upstream service which had been running for over 2 years to have an outage due to this bug.
This was also a bug in tokio up to and including version 0.3.4.
I copied the fix in tokio, which fudges any items which have timers which would logically go into the top+1 level into the top level. 
This means that you can insert an item into "the past" (if the time since the queue has been alive is in the top most level, and the item has been fudged into the top level too, and occupies an earlier slot). We handle this by bumping up the corresponding timer by the level range.
- Added test to check that inserting to a delayqueue that has existed for more than the 2^36 ms doesn't panic.
- Cargo fmt ran.
> [#5536] tokio-util: fix panic in DelayQueue

- benches/Cargo.toml
- benches/sync_notify.rs
- tokio/src/sync/notify.rs
This PR replaces the notification field used by waiters in `Notify` with an atomic variable to reduce lock contention when multiple pending `Notified` futures are completing.
The typical lifecycle of a `Notified` future looks like this:
1. It gets polled for the first time, and it is inserted into the waiting list.
2. It receives a notification from a `notify_one` or `notify_waiters` call and is removed from the waiting list.
3. The notifying function calls `wake()` on the future's waker.
4. The future gets polled again by the executor, consumes the notification and returns `Ready`.
Currently, step 4 requires acquiring the lock to read the notification field and the lock is released immediately after. Using an atomic variable here should significantly reduce lock contention, especially …
> sync: reduce contention in `Notify`

- tokio/tests/rt_common.rs
This test is flaky. Only fail it if it is failing consistently.
> Fix spurious `yield_defers_until_park` test

- tests-build/tests/fail/macros_type_mismatch.stderr
This fixes a change to the compiler output in rustc 1.69, that causes our macro tests to fail.
> chore: fix compiler output changes in rustc 1.69

- tokio/src/sync/semaphore.rs
Remove the extra angle bracket
> docs: Fix typo in `Semaphore::MAX_PERMITS`

- tokio/src/macros/select.rs
This reverts commit cf9a03c107ea523480e03234aff422905abaf8d7.
The underlying rustdoc bug has been fixed in https://github.com/rust-lang/rust/pull/110450.
> Revert "macros: hide internal constant in select! macro (#5617)"

- tokio-stream/Cargo.toml
Add "full" feature flag, that enables all other features. This is analog to tokio's "full" feature flag.
I often use tokio's "full" feature flag during early development and for hobby projects. That way I don't have to manage 
features early on and can just use everything and changing to specific features once a project is further developed.
I'd like to be able to do the same with tokio-stream. 
I was thinking about creating an issue for this first, but I decided that creating a PR is not that much slower so here it is.
> stream: add "full" feature flag

- tokio-stream/src/stream_ext.rs
- tokio-stream/src/stream_ext/timeout.rs
- tokio-stream/src/stream_ext/timeout_repeating.rs
The behavior of `StreamExt::timeout` is it only fires the timeout once (per value produced from the wrapped stream) and while this behavior is documented it is easy to overlook and assume that timeouts are generated repeatedly. I had made use of `timeout` in a project assuming that timeouts did repeat and it led to a subtle bug. It is useful for my use case for timeouts to fire repeatedly, so this change adds that in `timeout_repeating` as an alternative to `timeout`. For example, one might want to log a message at a fixed interval while no messages are being produced from a stream.
The non-repeating timeout behavior of `timeout` was not tested or demonstrated by the doc test, so first this was added.
A new `enum TimeoutMode` has been added to describe the two possible behaviors. …
> stream: add StreamExt::timeout_repeating

- tokio/src/sync/rwlock.rs
Currently the `std::fmt::Debug` impl for `tokio::sync::RwLock` is just what `#[derive(Debug)]` provides and looks like
```
RwLock { mr: 536870911, s: Semaphore { permits: 536870911 }, c: UnsafeCell { .. } }
```
which isn't very useful. Instead we can show the data *if* no thread currently holds the write lock. This matches what is done in `std::sync::RwLock` and in `tokio::sync::Mutex`.
The updated code is basically a 1 to 1 mapping from the tokio [Mutex implementation](https://docs.rs/tokio/latest/src/tokio/sync/mutex.rs.html#787-799).
> sync: useful Debug impl for RwLock 

- .github/workflows/ci.yml
Will provide a substantial performance improvement:
- cargo-semver-checks v0.20 is orders of magnitude faster at checking large crates — 2354x faster on `aws-sdk-ec2`
- the GitHub Action caches baseline rustdoc JSON files which is worth another ~2x speedup.
As discussed here: https://github.com/tokio-rs/tokio/pull/5437#issuecomment-1520366922
Switch to using the `cargo-semver-checks` GitHub Action which handles all of the above correctly and automatically. It also automatically downloads a prebuilt binary for the latest release of `cargo-semver-checks` so it should essentially run on autopilot from here on.
> Use the cargo-semver-checks GitHub Action for semver-checking

- tokio-macros/CHANGELOG.md
- tokio-macros/Cargo.toml
- tokio/Cargo.toml
- macros: fix typo in `#[tokio::test]` docs ([#5636])
- macros: make entrypoints more efficient ([#5621])
[#5621]: https://github.com/tokio-rs/tokio/pull/5621
[#5636]: https://github.com/tokio-rs/tokio/pull/5636
> chore: prepare tokio-macros v2.1.0

- README.md
- tokio/CHANGELOG.md
- tokio/Cargo.toml
- tokio/README.md
Depends on #5649.
- io: add `AsyncFd::async_io` ([#5542])
- io: impl BufMut for ReadBuf ([#5590])
- net: add `recv_buf` for `UdpSocket` and `UnixDatagram` ([#5583])
- sync: add `OwnedSemaphorePermit::semaphore` ([#5618])
- sync: add `same_channel` to broadcast channel ([#5607])
- sync: add `watch::Receiver::wait_for` ([#5611])
- task: add `JoinSet::spawn_blocking` ([#5612])
- deps: update windows-sys to 0.48 ([#5591])
- io: make `read_to_end` not grow unnecessarily ([#5610])
- macros: make entrypoints more efficient ([#5621])
- sync: improve Debug impl for `RwLock` ([#5647])
- sync: reduce contention in `Notify` ([#5503])
- net: support `get_peer_cred` on AIX ([#5065])
- sync: avoid deadlocks in `broadcast` with custom wakers ([#5578])
- sync: fix typo in `Semaphore::MAX_PERMITS` …
> chore: prepare Tokio v1.28.0

- tokio-util/CHANGELOG.md
- tokio-util/Cargo.toml
This release bumps the MSRV of tokio-util to 1.56.
- time: add `DelayQueue::peek` ([#5569])
This release contains one performance improvement:
- sync: try to lock the parent first in `CancellationToken` ([#5561])
- time: fix panic in `DelayQueue` ([#5630])
- sync: improve `CancellationToken` doc on child tokens ([#5632])
[#5561]: https://github.com/tokio-rs/tokio/pull/5561
[#5569]: https://github.com/tokio-rs/tokio/pull/5569
[#5630]: https://github.com/tokio-rs/tokio/pull/5630
[#5632]: https://github.com/tokio-rs/tokio/pull/5632
> chore: prepare tokio-util v0.7.8

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
This release bumps the MSRV of tokio-stream to 1.56.
- stream: add "full" feature flag ([#5639])
- stream: add `StreamExt::timeout_repeating` ([#5577])
- stream: add `StreamNotifyClose` ([#4851])
[#4851]: https://github.com/tokio-rs/tokio/pull/4851
[#5577]: https://github.com/tokio-rs/tokio/pull/5577
[#5639]: https://github.com/tokio-rs/tokio/pull/5639
> chore: prepare tokio-stream v0.1.13

- tokio-stream/CHANGELOG.md
- tokio-stream/Cargo.toml
This bugfix release bumps the minimum version of Tokio to 1.15, which is necessary for `timeout_repeating` to compile. ([#5657])
[#5657]: https://github.com/tokio-rs/tokio/pull/5657
> chore: prepare tokio-stream v0.1.14

- tokio/src/net/unix/datagram/socket.rs
- tokio/src/net/unix/listener.rs
- tokio/src/net/unix/stream.rs
Someone on discord couldn't find our unix domain sockets, and said that they searched for uds. Note that they were previously in a crate called tokio-uds.
> net: add uds doc alias for unix sockets

- .github/workflows/ci.yml
- examples/Cargo.toml
- examples/dump.rs
- tokio/Cargo.toml
- tokio/src/lib.rs
- tokio/src/macros/cfg.rs
- tokio/src/runtime/context.rs
- tokio/src/runtime/dump.rs
- tokio/src/runtime/handle.rs
- tokio/src/runtime/mod.rs
- tokio/src/runtime/runtime.rs
- tokio/src/runtime/scheduler/current_thread.rs
- tokio/src/runtime/task/list.rs
- tokio/src/runtime/task/mod.rs
- tokio/src/runtime/task/raw.rs
- tokio/src/runtime/task/state.rs
- tokio/src/runtime/task/trace/mod.rs
- tokio/src/runtime/task/trace/symbol.rs
- tokio/src/runtime/task/trace/tree.rs
- tokio/src/task/spawn.rs
- tokio/src/task/yield_now.rs
- tokio/src/util/linked_list.rs
- tokio/src/util/trace.rs
- tokio/tests/dump_current_thread.rs
In Java, *thread dumps* are an invaluable tool for debugging a stuck application in production. When a user requests a threaddump from a JVM, they receive text including the following information about each thread managed by the JVM:
- The thread name.
- The thread ID.
- The thread's priority.
- The thread's execution status: e.g., `RUNNABLE`, `WAITING`, or `BLOCKED`.
This information is useful for debugging deadlocks.
- The thread's call stack.
Thread dumps provide a starting point for debugging deadlocks. A programmer can thread dump a deadlocked program, identify the `BLOCKED` threads, and inspect their call stacks to identify the resources they are blocked on.
This PR is a first step towards bringing an analogous functionality to tokio: "task dumps". A task dump is a comprehensive …
> Implement task dumps for current-thread runtime.

- tokio/src/util/linked_list.rs
This PR resolves a semantic conflict between #5608 and #5628. Both PRs modified `tokio/src/runtime/task/list.rs`:
- #5628 changed the field type of `OwnedTasks::inner`
- #5608 added `OwnedTasks::for_each` (that forwards to a `for_each` on `OwnedTasks::inner`)
Because these changes did not occur close together, they did not pose a merge conflict for either PR; rather, [a semantic conflict](https://bors.tech/essay/2017/02/02/pitch/).
This PR fixes the semantic conflict, but does not fix that CI allows such conflicts to occur. To resolve that, this repo would need to adopt something like [bors](https://bors.tech/).
Further discussion: https://discord.com/channels/500028886025895936/500336346770964480/1100809662208675982
> Resolve a semantic conflict between #5608 and #5628.

- tokio/src/fs/read_dir.rs
This change prevents spawning blocking threads once the iteration is complete.
> fs: reduce blocking ops in `fs::read_dir`

- tokio/src/sync/mpsc/error.rs
- tokio/src/sync/watch.rs
Closes #5664
Hi @Darksonn,
I did it, I looked at [std::sync::mpsc::SendError](https://doc.rust-lang.org/std/sync/mpsc/struct.SendError.html#) and [std::sync::mpsc::TrySendError](https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html#) implementations as a based to my commits.
I looked over all the Tokio's channel and found (in addition to the `mpsc`) a similar issue with the `watch` channel so I fixed it too.
There is one difference with the `std` code that I didn't do because it's adding a bond `Send` on `T` for the `Error` trait impl on their error and I don't see why it is required... (See in `std::sync::mpsc` [impl<T: Send> Error for SendError<T>](https://doc.rust-lang.org/std/sync/mpsc/struct.SendError.html#impl-Error-for-SendError%3CT%3E) and [impl<T: Send> Error for …
> mpsc and watch errors (SendError<T>...) without bond T:Debug
