tokio-rs/tokio

.github/workflows/ci.yml
Adds `check-fuzzing` CI steps to install `cargo-fuzz` and check if `fuzz_targets` under `/tokio/` compile
Solves the `/tokio/` piece of https://github.com/tokio-rs/tokio/issues/5601
Adds the following CI steps:
* Install `rust_nightly` - need over `rust_stable` for `cargo-fuzz` see [here](https://github.com/rust-fuzz/cargo-fuzz/blob/main/README.md?plain=1#L14)
* Install `cargo-fuzz`
* Run `cargo fuzz check` on `/tokio/` dir
=> Add ci step to check /tokio/ fuzzing compiles

tokio-macros/src/lib.rs
fix a broken link on the [docs.rs](https://docs.rs/tokio-macros/2.1.0/tokio_macros/attr.main_rt.html) page.
fix the typo in the link
=> docs: fix typo in doc comment

tokio/src/fs/file.rs, tokio/src/lib.rs, tokio/src/macros/cfg.rs, tokio/src/runtime/defer.rs, tokio/src/runtime/scheduler/current_thread.rs, tokio/src/runtime/task/join.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task/trace/mod.rs, tokio/src/task/yield_now.rs
This adds taskdump tracing for `JoinHandle` and various methods in `tokio::fs`.
See #5638 for more information.
cc @jswrenn
=> taskdump: instrument `JoinHandle` and `tokio::fs`

tokio-util/src/sync/mpsc.rs, tokio-util/tests/mpsc.rs
Currently, `PollSender` is limited to sending `'static` types, which limits its usefulness when sending non-`static`ally borrowed things to and from scoped tasks (e.g. `async-scoped`).
Remove the `'static` restriction by introducing a lifetime parameter.
=> tokio-util: enable non-`'static` `PollSender`

tokio/build.rs
The `AsFd` implementations did not actually appear when building with rustc 1.63. The previous state of the probe generated a warning which resulted in `tokio_no_as_fd` being generated:
```
[tokio 1.28.0] error[E0658]: attributes on expressions are experimental
[tokio 1.28.0]  --> <anon>:3:5
[tokio 1.28.0]   |
[tokio 1.28.0] 3 |     #![allow(unused_imports)]
[tokio 1.28.0]   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
[tokio 1.28.0]   |
[tokio 1.28.0]   = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information
[tokio 1.28.0] 
[tokio 1.28.0] error: aborting due to previous error
[tokio 1.28.0] 
[tokio 1.28.0] For more information about this error, try `rustc --explain E0658`.
[tokio 1.28.0] cargo:rustc-cfg=tokio_no_as_fd
```
Instead, add the `allow` to each import …
=> tokio: fix warnings in AS_FD_PROBE

tokio-stream/fuzz/fuzz_targets/fuzz_stream_map.rs
This fixes compilation warnings for `tokio-stream/fuzz`
This is the prereq before the next step of adding a compilation check step in CI to address https://github.com/tokio-rs/tokio/issues/5601
Removes unused code in order for the warnings to go away.
=> Remove unused code from fuzz_steam_map.rs

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release fixes a mistake in the build script that makes `AsFd` implementations unavailable on Rust 1.63. ([#5677])
[#5677]: https://github.com/tokio-rs/tokio/pull/5677
=> chore: prepare Tokio v1.28.1

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/build.rs
Merge tokio-1.28.x into master.
Refs: #5679
This commit sets up the history in the following way:
```text
*   89b73f39bfcd Merge 'tokio-1.28.x' into 'master' (#5680)
|\  
| * a26fc9c9f956 (tokio-1.28.x) chore: prepare Tokio v1.28.1 (#5679)
| * f2d033e4541d build: fix warnings in AS_FD_PROBE (#5677)
* | 7fe88ce4addf fuzz: remove unused code from `fuzz_steam_map.rs` (#5675)
* | c999699f5ed1 sync: remove 'static bound from `PollSender` (#5665)
* | 7430865d655d taskdump: instrument `JoinHandle` and `tokio::fs` (#5676)
* | 56239a9035a5 macros: fix typo in doc comment (#5671)
* | 1b4106a1ce7e net: add nodelay methods on TcpSocket (#5672)
* | 3abe877bf7de ci: check that `tokio/fuzz` compiles (#5670)
* | 61b68a8abc7e sync: implement more traits for channel errors (#5666)
* | 52bc6b6f2d77 fs: …
```
=> Merge 1.28.1

.github/workflows/ci.yml
Solves the `/tokio-stream/` piece of #5601 
Similar to the `/tokio/` check, adds step in CI to run `cargo fuzz check` on `/tokio-stream/` dir
Closes:  #5601
=> Add ci step to check tokio-stream/fuzz compiles

.github/workflows/ci.yml
We don't need to check the fuzz tests until the basic tests have passed.
=> ci: only check fuzz tests after basic tests

tokio/src/runtime/coop.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/tests/rt_threaded.rs
This fixes a problem where using the LIFO slot without consuming budget can result in starvation.
=> Fix starvation when using LIFO slot without consuming budget

tokio/src/util/idle_notified_set.rs
This PR avoids a raw pointer → reference → raw pointer conversion because it violates stacked borrows.
When I wrote this code originally, I didn't think this was an issue because it is used with `LinkedList::remove`, which shouldn't leave any raw pointers derived from the reference anywhere. However, the return value of `remove` gets is provenance from the pointer passed to `remove`, so when `me` is inserted in the other linked list, that raw pointer is derived from the reference.
Note that the code is valid under tree borrows since the reference points at something containing an `UnsafeCell`. Therefore, this issue should not lead to miscompilations.
Refs: https://github.com/tokio-rs/tokio/issues/3399#issuecomment-1546419558
Cc @udoprog
=> Fix stacked borrows issue in `IdleNotifiedSet`

tokio/src/util/idle_notified_set.rs
Disables a recently added miri test when running loom tests.
=> ci: skip miri tests when running loom

tokio/src/runtime/scheduler/multi_thread/counters.rs, tokio/src/runtime/scheduler/multi_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs
These counters are enabled using the `tokio_internal_mt_counters` and are intended to help with debugging performance issues.
Whenever I work on the threaded runtime, I often find myself adding these counters, then removing them before submitting a PR. I think keeping them in will save time in the long run and shouldn't impact dev much.
=> rt: add internal counters to threaded runtime.

tokio/src/process/mod.rs
Adds the `raw_arg` method to `tokio::process::Command`
=> process: add `raw_arg` method to `Command`

.github/workflows/ci.yml, benches/Cargo.toml, benches/rt_current_thread.rs, tokio/src/runtime/scheduler/current_thread.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/task/inject.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task/trace/mod.rs, tokio/tests/rt_common.rs
Depends on #5701
Previously, the current_thread scheduler used its own injection queue instead of sharing the same one as the multi-threaded scheduler. This patch updates the current_thread scheduler to use the same injection queue as the multi-threaded one (`task::Inject`).
`task::Inject` includes an optimization where it does not need to acquire the mutex if the queue is empty.
The primary objective for this PR is to unify the injection queue code paths for future tweaks. The benchmark results between the current `master` and this change are within the margin of error.
**Before:**
```
test spawn_many_local       ... bench:     222,721 ns/iter (+/- 5,288)
test spawn_many_remote_busy ... bench:   5,576,420 ns/iter (+/- 175,418)
test spawn_many_remote_idle ... bench:     228,768 ns/iter …
```
=> rt: use task::Inject with current_thread scheduler

.github/workflows/loom.yml, benches/rt_multi_threaded.rs, tokio/src/runtime/scheduler/multi_thread/queue.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/task/inject.rs, tokio/src/runtime/tests/inject.rs, tokio/src/runtime/tests/loom_queue.rs, tokio/src/runtime/tests/mod.rs, tokio/src/runtime/tests/queue.rs, tokio/tests/rt_metrics.rs
In the multi-threaded scheduler, when no tasks are on the local queue, a worker will attempt to pull tasks from the injection queue. Previously, the worker would only attempt to poll one task from the injection queue and then continue trying to find work from other sources. This can result in the injection queue backing up when many tasks are scheduled outside the runtime.
This patch updates the worker to try to poll more than one task from the injection queue when it has no more local work. Note that we also don't want a single worker to poll **all** tasks on the injection queue, as that would result in work becoming unbalanced.
I added some new benchmarks. All benchmark results are the same except for `spawn_many_remote_busy`
**Before:**
test spawn_many_remote_busy ... bench: …
=> rt: batch pop from injection queue when idle

.github/workflows/ci.yml, .github/workflows/loom.yml, tokio/src/runtime/coop.rs, tokio/src/runtime/scheduler/multi_thread/counters.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/tests/mod.rs
As an optimization to improve locality, the multi-threaded scheduler maintains a single slot (LIFO slot). When a task is scheduled, it goes into the LIFO slot. The scheduler will run tasks in the LIFO slot first before checking the local queue.
Ping-ping style workloads where task A notifies task B, which notifies task A again, can cause starvation as these two tasks repeatedly schedule the other in the LIFO slot. #5686, a first attempt at solving this problem, consumes a unit of budget each time a task is scheduled from the LIFO slot. However, at the time of this commit, the scheduler allocates 128 units of budget for each chunk of work. This is relatively high in situations where tasks do not perform many async operations yet have meaningful poll times (even 5-10 microsecond poll times …
=> rt(threaded): cap LIFO slot polls

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
Sixth PR in a sequence related to https://github.com/tokio-rs/mio/pull/1673.
Depends on #5733.
Forward ports 1.18.6 changes.
- deps: disable default features for mio ([#5728])
[#5728]: https://github.com/tokio-rs/tokio/pull/5728
=> Prepare Tokio v1.25.1

.github/workflows/ci.yml, tokio/CHANGELOG.md, tokio/Cargo.toml
Seventh PR in a sequence related to https://github.com/tokio-rs/mio/pull/1673.
This reverts most of the ci fixes from previous branches.
Depends on #5734.
=> Merge 1.25.1 into 1.28.x

.github/workflows/ci.yml, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
Eight PR in a sequence related to https://github.com/tokio-rs/mio/pull/1673.
Depends on #5735.
Forward ports 1.18.6 changes.
- deps: disable default features for mio ([#5728])
[#5728]: https://github.com/tokio-rs/tokio/pull/5728
=> Prepare Tokio v1.28.2

.github/workflows/ci.yml, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
Ninth (and last) PR in a sequence related to https://github.com/tokio-rs/mio/pull/1673.
Depends on #5736.
=> Merge 1.28.2 into master

.github/workflows/loom.yml, tokio/src/runtime/scheduler/multi_thread/park.rs, tokio/src/runtime/tests/loom_pool.rs
Increase max preemption back to 2 while running the tests in under 90 minutes.
=> ci: speed up multi-threaded runtime loom tests.

tokio-util/src/lib.rs
BytesMut is exposed in:
codec/encoder.rs, codec/decoder.rs and udp/frame.rs,
BufMut is exposed in:
io/read_buf.rs, lib.rs
Buf is exposed in:
lib.rs
It would be helpful to reexport Bytes for CopyToBytes in io/copy_to_byes.rs due to its implementations 
This pr will reexport bytes::{ Bytes, BytesMut, Buf, BufMut } in a submodule at the crate base also named bytes.
resolves #5719
=> Added partial reexport of bytes crate

tokio-util/src/io/inspect.rs
This commit allows you to use `InspectReader` and `InspectWriter` on types that implement both AsyncRead + AsyncWriter without losing those trait implementations.
While implementing clients for tcp interfaces it can be helpful to inspect the bytes sent / received through a `tokio::io::TcpStream`.  The existing InspectReader / InspectWriter structs are a good start, but using them causes the stream to lose its AsyncWrite / AsyncRead trait impls. 
By adding implementations for `AsyncRead` to `InspectWriter` and `AsyncWrite` to `InspectReader` it is now possible to inspect bytes sent through a `TcpStream` (or any other `T: AsyncRead+AsyncWrite`) and still pass that stream onto another subsystem that expects a `T: AsyncRead+AsyncWrite`.
For example:
```rust
use tokio::io::TcpStream;
use …
```
=> tokio-util: add AsyncRead/AsyncWrite passthrough for inspect

tokio/src/runtime/scheduler/multi_thread/idle.rs, tokio/src/runtime/scheduler/multi_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs
To reduce the number of mutex operations in the multi-threaded scheduler hot path, we need to unify the various mutexes into a single one. To start this work, this commit splits up `Idle` into `Idle` and `Synced`. The `Synced` component is stored separately in the scheduler's `Shared` structure.
This commit starts small to demonstrate the strategy. Each scheduler component will introduce its own `Synced` type, which will all be stored in `Shared::synced`.
=> rt: start work to unify MT scheduler mutexes

.github/workflows/ci.yml, tokio/tests/rt_threaded.rs
PR #5720 introduced runtime self-tuning. It included a test that attempts to verify self-tuning logic. The test is heavily reliant on timing details. This patch tries to make the test more reliable by not assuming tuning will converge within a set amount of time.
=> ci: fix spurious CI failure

tokio/src/runtime/context.rs, tokio/src/runtime/context/scoped.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/util/rand.rs, tokio/src/util/rand/rt.rs, tokio/src/util/rand/rt_unstable.rs
This makes initializing `Context` const, which lets us use const thread-locals. The next step will be to ensure `Context` does not have a drop impl.
=> rt: make `CONTEXT` const TLS

tokio-macros/src/entry.rs
This change prevents rust-analyzer from incorrectly analyzing the last statement of the main function as a `Builder::new_*` method.
Fixes #5518
=> macros: fix diagnostics of last statement

tokio/src/runtime/context/scoped.rs
If the `Scoped` type is `Sync`, then you can call `set` from two threads in parallel. Since it accesses `inner` without synchronization, this is a data race.
This is a soundness issue for the `Scoped` type, but since this is an internal API and we don't use it incorrectly anywhere, there is no harm done.
=> runtime: `Scoped` should not be `Sync`

tokio/src/runtime/context.rs, tokio/src/util/markers.rs, tokio/src/util/mod.rs, tokio/tests/async_send_sync.rs
Removes `Send` from `EnterGuard` (returned by `Handle::enter()`. The guard type changes a thread-local variable on drop. If the guard is moved to a different thread, it will modify the wrong thread-local.
This is a **breaking change**, but it fixes a bug and prevents incorrect user behavior. If user code breaks because of this, it is because they (most likely) have a bug in their code.
=> rt: `EnterGuard` should not be `Send`

.github/workflows/ci.yml, tokio/tests/rt_threaded.rs
The tuning test relies on a predictable execution environment. It assumes that spawning a new task can complete reasonably fast. When running tests with ASAN, the tuning test will spuriously fail. After investigating, I believe this is because running tests with ASAN enabled and without `release` in a low-resource environment (CI) results in an execution environment that is too slow for the tuning test to succeed.
=> ci: disable tuning test when runing ASAN

tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread/handle/taskdump.rs, tokio/src/runtime/scheduler/multi_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/trace.rs, tokio/src/runtime/scheduler/multi_thread/trace_mock.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread/worker/metrics.rs, tokio/src/runtime/scheduler/multi_thread/worker/taskdump.rs, tokio/src/runtime/scheduler/multi_thread/worker/taskdump_mock.rs
Instead of defining code in macros, move code definition to sub-modules and use the cfg_macro to declare the module.
=> rt: reduce code defined in macros

.github/workflows/ci.yml
Due to #5766, we need to temporarily disable this check until the next release.
=> ci: temporarily disable semver check

tokio-stream/Cargo.toml, tokio-util/Cargo.toml, tokio/Cargo.toml, tokio/src/task/task_local.rs
As `pin-project-lite` supported custom `Drop` implementation in https://github.com/taiki-e/pin-project-lite/pull/25, I suppose it's worthwhile switching back to the `pin-project` implementation to eliminate unsafe code for `TaskLocalFuture`.
Implement `TaskLocalFuture` with `pin_project_lite::pin_project!` with `PinnedDrop`.
=> task: use pin-project for `TaskLocalFuture`

examples/dump.rs, tokio/src/runtime/dump.rs, tokio/src/runtime/handle.rs
Adds depth to the task dump example, and documentation to `Handle::dump`.
=> Improve task dump documentation

tokio/src/runtime/time/entry.rs, tokio/src/runtime/time/mod.rs, tokio/src/runtime/time/source.rs, tokio/tests/time_sleep.rs
As described in #5183, Tokio will panic if you sleep far, but not too far into the future.
This can cause issues and crashes in some cases where you don't expect it which is the main motivation for solving it.
The issue is that the time value will overflow and then get set to `u64::MAX`, `u64::MAX` is also used as the signal value for the state `STATE_DEREGISTERED` which will cause the [`when`] function to think that the time already have fired and thus been deregistered.
If the program is run in debug mode it will fail a bit earlier because of a [`debug_assert`]
This PR will currently never complete CI since the test I have added fails to ever complete. I am not sure how that should be resolved so I have opened this PR to discuss it as well. Should it be commented out or can it be made …
=> time: Do not overflow to signal value

.github/workflows/ci.yml, Cargo.toml, tokio/Cargo.toml
Currently building with MSRV from the workspace root fails with the following error ([ci log](https://github.com/tokio-rs/tokio/actions/runs/5233633822/jobs/9449234197)):
```console
$ cargo +1.56 check --workspace --all-features
error: package `log v0.4.19` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.56.1
```
This is because the development dependency (mio-aio) enables mio's log feature (requires Rust 1.60 since log [0.4.19](https://github.com/rust-lang/log/releases/tag/0.4.19) released a few hours ago), and it is propagated to the normal dependencies by the cargo v1 resolver's [feature unification](https://doc.rust-lang.org/stable/cargo/reference/features.html#feature-unification).
Enable cargo v2 resolver to prevent dev-deps …
=> chore: enable cargo v2 resolver to prevent dev-deps from enabling log feature of mio

.github/workflows/ci.yml, CONTRIBUTING.md, benches/Cargo.toml, examples/Cargo.toml, examples/tinyhttp.rs, stress-test/Cargo.toml, tests-build/Cargo.toml, tests-integration/Cargo.toml, tests-integration/tests/process_stdio.rs, tokio-macros/Cargo.toml, tokio-stream/fuzz/Cargo.toml, tokio/fuzz/Cargo.toml
https://github.com/tokio-rs/tokio/pull/5559 and https://github.com/tokio-rs/tokio/pull/5571 have updated some crates to 2021 edition, but there are still some left.
This upgrades all remaining 2018 edition crates to 2021 edition.
=> chore: upgrade remaining 2018 edition crates to 2021 edition

tokio/Cargo.toml, tokio/src/net/unix/ucred.rs
I recently got an MR merged into rust libc to add the ucred struct for redox-os.
That was what was missing in order to allow tokio to compile for redox-os.
That change was recently released as part of libc version 0.2.245.
This PR adds the redox-os to the conditional compile directives for the linux-like OSs, so that it can use ucred and compile without any tokio code changes.
This will unblock much useage (and fork and patch maintenance) in redox development for tokio, and allow it to be used much more widely.
It's still WIP as I work on an issue on my end, but wanted to get it here sooner rather than later - hope that is OK.
=> Add redox-os to conditional compilation #[cfg] for ucred usage alongside other linux-like OS

tokio/src/runtime/scheduler/multi_thread/queue.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs
Fix #5751
As described in  #5751
=> rt(threaded): adjust transition_from_parked behavior after introducing disable_lifo_slot feature

.github/workflows/ci.yml
This PR adds a `cargo check` job for redox-os, to ensure tokio continues to compile correctly for that target, as discussed with @Darksonn in this comment thread https://github.com/tokio-rs/tokio/pull/5790#issuecomment-1589772978
Have tokio support redox-os as a target and avoid changes breaking it.
Pending solving some issues and providing a CI solution on redox-os to the tokio project, so that build can be done, and tests to run and pass - this interim step add a compile check to ensure that tokio will compile for that target.
Redox-os project will work on build and test run and create new PRs in the future to add them to tokio CI.
Thanks for your collaboration and support of redox-os
=> Add a check-redox job in GH Action ci.yml workflow

tokio/src/runtime/handle.rs
- Add example trace output.
- Add note on enabling unstable features.
- Add note on `aarch64` support.
- Add note on performance overhead.
=> tokio: improve taskdump documentation

tokio/src/runtime/task/core.rs
This change pads the task struct to avoid false sharing. These structs can overlap cache lines without this alignment.
I avoided adding a `CachePadded` wrapper struct as I am not sure how the padded wrapper struct would impact the pointer stuff we do in the task harness (casting `*Header` to `*Cell` as well as the other pointer math). 
I'm also not 100% sure what happens when you combine `repr(C)` with `repr(align(n))` but I would guess (hope) it does the right thing.
Thoughts @Darksonn ?
As part of a larger scheduler refactor that I am working on, I have observed false sharing happened and confirmed the false sharing using `perf c2c`. Adding the padding here resolves the issue.
=> rt: pad the task struct to avoid false sharing

tokio/src/fs/read_dir.rs
This change updates the cfg attribute to prevent unnecessary file metadata fetching on new targets.
The current `DirEntry::file_type` implementation returns a pre-parsed value from `fs::read_dir` for most targets. Some Unix operating systems are excluded because of the overhead of fetching metadata to get the file type. However, as the Rust compiler has been updated, new targets have been added and an update is needed. The cfg attribute is taken from [the std implementation](https://github.com/rust-lang/rust/blob/3c9e0705ba0c1c845fe7cdbd0bdf4a914f49cc8e/library/std/src/sys/unix/fs.rs#L862-L869).
Related Issue: #5804
=> fs: update cfg attr in `fs::read_dir`

tokio-util/Cargo.toml, tokio-util/src/compat.rs, tokio-util/tests/compat.rs
Aims to address #5764.
Waiting for a seek operation to complete by calling `poll_complete` before calling `start_seek`.
=> Fix futures_io::AsyncSeek implementaion for Compat

tokio/src/fs/file.rs
If there is an ongoing operation on a file, wait for that to complete before performing the clone in `File::try_clone`. This avoids a race between the ongoing operation and any subsequent operations performed on the clone.
Fixes: #5759
#5759 shows a situation where a file is written to with `write_all`, and once that completes (Poll::Ready), cloned with `try_clone`. The file contents are then read back from the clone. In unlucky situations, this read produces an empty result because the read occurs before the write has completed.
Like most methods on File, the `try_clone` function should wait until any previous asynchronously-completing operations on the file are complete before actually cloning the file.
The failure fixed by this PR appears _very_ difficult to test:
* It is a race …
=> wait for in-flight ops before cloning `File`

tokio/src/util/linked_list.rs
The `drain_filter` method on the internal `LinkedList` type passes a `&mut` reference to the node type. However, the `LinkedList` is intended to be used with nodes that are shared in other ways. For example, `task::Header` is accessible concurrently from multiple threads.
Currently, the only usage of `drain_filter` is in a case where `&mut` access is safe, so this change is to help prevent future bugs and tighten up the safety of internal utilities.
=> io: fix safety of `LinkedList` drain_filter API

tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/tests/rt_threaded.rs
This patch fixes a bug where nesting `block_in_place` with a `block_on` between could lead to a panic. This happened because the nested `block_in_place` would try to acquire a core on return when it should not attempt to do so. The `block_on` between the two nested `block_in_place` altered the thread-local state to lead to the incorrect behavior.
The fix is for each call to `block_in_place` to track if it needs to try to steal a core back.
Fixes #5239
=> rt: fix nesting block_in_place with block_on

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/tests/rt_threaded.rs
This fixes a long-standing bug. The fix isn't worth backporting to LTS releases, but since we just released 1.29.1, I think a patch release is fine here.
=> chore: backport #5837 and prepare v1.29.1 release

.github/workflows/ci.yml, .github/workflows/stress-test.yml
tokio CI is quite slow.
- Use `cargo-nextest` to speedup testing
- Use `cargo-check` instead of `cargo-build` and `cargo test --no-run`.
- Run `cargo-clippy` with `--no-deps`
- Set `CARGO_UNSTABLE_SPARSE_REGISTRY` to `true` so that nightly toolchain would use sparse crates.io registries
- Adjust order of steps to avoid caching crates installed by `taiki-e/install-action@v2`
- Use `Swatinem/rust-cache@v2` in job no-atomic-u64
- Add concurrenty group to cancel outdated CI
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> Speedup CI

tokio/src/runtime/runtime.rs
I saw someone discuss this section in the Tokio Discord, and though that it could use some improvement.
=> runtime: expand on sharing runtime docs

tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/task/harness.rs, tokio/src/runtime/task/list.rs, tokio/src/util/trace.rs
This reduces the amount of LLVM code generated, which is helpful for compilation speed.
A big portion of LLVM code generation for Lemmy server is caused by a few Tokio functions: [cargo llvm-lines output](https://github.com/LemmyNet/lemmy/files/12010680/lineslib-lto.zip)
It would be helpful to reduce this because it contributes to Lemmy's extremely slow compilation.
Split parts of functions into separate functions without unneeded generic parameters: https://nnethercote.github.io/perf-book/compile-times.html#llvm-ir
=> Reduce LLVM code generation

tokio/src/sync/broadcast.rs
=> sync::broadcast: create Sender::new

tokio/src/io/util/async_read_ext.rs
See [this SO question](https://stackoverflow.com/questions/68979882/readread-exact-does-not-fill-buffer).
In most cases when `read_exact` is used the user doesn't know beforehand how many bytes are gonna be read. This leads to code like `Vec::with_capacity(len)` when really what the user wants is `vec![0; len]` (the former has a length of zero so it succeeds with `Ok(0)`).
Change the example to use the `vec!` macro instead of a fixed-sized array. This will make adding a warning obsolete.
=> Use a dynamic buffer in the `AsyncReadExt`'s `read_exact` example

tokio/src/fs/file.rs
I've found myself `std::fs::Files::options()` function really convenient and I accidentally typed it in tokio project. Hey, it would be an easy PR chance, right?
Code is copied from std with minor modifications, including docs explaining its motivation.
=> fs: Add `File::options()` assoc function to mimic std

tokio/src/runtime/park.rs, tokio/src/runtime/tests/mod.rs, tokio/src/sync/tests/notify.rs, tokio/src/util/wake.rs
The `Arc::increment_strong_count` method was stabilized in Rust 1.51, and our MSRV is now new enough to use it.
=> Use `Arc::increment_strong_count` instead of `mem::forget`

tokio/src/runtime/task/core.rs, tokio/src/runtime/task/list.rs
We switch to using a `NonZeroU64` for the `id` field for `OwnedTasks`
and `LocalOwnedTasks` lists. This allows the task header to contain an
`Option<NonZeroU64>` instead of a `u64` with a special meaning for 0.
The size in memory will be the same thanks to Rust's niche optimization,
but this solution is clearer in its intent.
=> rt: use optional non-zero value for task `owner_id`

tokio/src/io/poll_evented.rs
The new mio_unsupported_force_poll_poll behaviour works the same as Windows (using level-triggered APIs to mimic edge-triggered ones) and it depends on intercepting an EAGAIN result to start polling the fd again.  Without this change, short reads don't reregister with the poll Selector and it causes the socket to stall in a read async call forever.
Per #5866, going with the simplest solution of just adding another `cfg!` check alongside the Windows one.
=> poll: Do not clear readiness on short read/writes.

tokio/src/runtime/handle.rs, tokio/src/runtime/id.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/scheduler/current_thread.rs, tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/task/list.rs, tokio/src/task/local.rs, tokio/tests/rt_handle.rs, tokio/tests/rt_threaded.rs
There are a number of cases in which being able to identify a runtime is
useful.
When instrumenting an application, this is particularly true. For
example, we would like to be able to add traces for runtimes so that
tasks can be differentiated (#5792). It would also allow a way to
differentiate runtimes which are have their tasks dumped.
Outside of instrumentation, it may be useful to check whether 2 runtime
handles are pointing to the same runtime.
This change adds an opaque `runtime::Id` struct which serves this
purpose, initially behind the `tokio_unstable` cfg flag. 
The inner value of the ID is taken from the `OwnedTasks` or
`LocalOwnedTasks` struct which every runtime and local set already
has. This will mean that any use of the ID will align with the task
dump feature.
The Id is …
=> rt: add runtime Id

tokio/src/runtime/scheduler/multi_thread_alt/idle.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs
The scheduler uses this map to avoid trying to steal from idle workers.
=> rt(alt): track which workers are idle.

examples/proxy.rs
The `examples/proxy.rs` was created before `copy_bidirectional` https://github.com/tokio-rs/tokio/pull/3572 was added to tokio. In https://github.com/tokio-rs/tokio/pull/2590 the proxy example was updated to close pending connections. By reusing the `copy_bidirectional` the example can be simplified.
Reuse [`copy_bidirectional`](https://docs.rs/tokio/latest/tokio/io/fn.copy_bidirectional.html) in example.
=> example: use copy_bidirectional in proxy.rs

tokio/src/fs/file.rs, tokio/src/io/async_fd.rs, tokio/src/io/stderr.rs, tokio/src/io/stdin.rs, tokio/src/io/stdout.rs, tokio/src/macros/cfg.rs, tokio/src/macros/thread_local.rs, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/socket.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/pipe.rs, tokio/src/net/unix/stream.rs, tokio/src/net/windows/named_pipe.rs, tokio/src/process/mod.rs, tokio/src/process/unix/mod.rs, tokio/src/task/task_local.rs
#5887 bumped MSRV to 1.63, now these cfgs are useless.
Remove unused cfgs:
- tokio_no_const_thread_local
- tokio_no_target_has_atomic
- tokio_no_as_fd
=> Removed unused `tokio_*` cfgs

.github/workflows/ci.yml, tokio/src/loom/std/mutex.rs, tokio/src/macros/cfg.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mutex.rs, tokio/src/sync/notify.rs, tokio/src/sync/once_cell.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs, tokio/src/util/mod.rs, tokio/tests/sync_once_cell.rs, tokio/tests/task_join_set.rs
MSRV is bumped to 1.63 in #5887 , now`Mutex::new` is usable in const context, so these functions should now be always available.
This patch makes these function always available.
Also use `assert!` in const function to ensure correctness instead of silently truncating the value and remove use of cfg `tokio_no_const_mutex_new`.
This PR might resolve #4623
=> Make `{Mutex, Notify, OnceCell, RwLock, Semaphore}::const_new` always available

.github/workflows/ci.yml, .github/workflows/labeler.yml, .github/workflows/loom.yml, .github/workflows/pr-audit.yml, .github/workflows/stress-test.yml, tokio/src/loom/std/parking_lot.rs, tokio/src/macros/cfg.rs, tokio/tests/tcp_connect.rs, tokio/tests/tcp_socket.rs
- Remove duplicate target from cross-test
- Remove needless --test-threads=1 as RUST_TEST_THREADS=1 already specifies it
- Remove --cfg tokio_no_ipv6 as setup-cross-toolchain-action supports it
- Automatically cancel all outdated workflows on PR (currently this is only set for ci.yml)
- Remove --cfg tokio_no_atomic_u64 as tests/builds with --target target-specs/i686-unknown-linux-gnu.json handles these cases
=> Update CI config

tokio/tests/rt_common.rs
This test is flaky in Android's CI and failing 1% of the time.
=> Fix flaky test wake_while_rt_is_dropping

tokio/src/runtime/scheduler/multi_thread/worker.rs
When pulling a batch of tasks from the injection queue, ensure we set the cap to at least one.
=> rt: pop at least one task from inject queue

tokio/src/time/interval.rs, tokio/tests/time_interval.rs
Fixes: #5874
The use case is explained in #5874
It just calls the internal reset on the specified `Instant`.
~~I have added a new field to the `Interval` struct to store the previous period.~~
~~On each tick if previous period is `Some()` it will be restored.~~
~~Integration tests will be added on a later commit.~~
=> implement extra reset variants for Interval

tokio/Cargo.toml, tokio/src/loom/mocked.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/config.rs, tokio/src/runtime/driver.rs, tokio/src/runtime/scheduler/inject/shared.rs, tokio/src/runtime/scheduler/inject/synced.rs, tokio/src/runtime/scheduler/multi_thread_alt/idle.rs, tokio/src/runtime/scheduler/multi_thread_alt/mod.rs, tokio/src/runtime/scheduler/multi_thread_alt/queue.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/src/runtime/tests/loom_multi_thread_alt.rs, tokio/tests/rt_threaded_alt.rs
Expands loom coverage and fixes a number of bugs.
Closes #5888
Depends on: tokio-rs/loom#323
=> rt(alt): fix a number of concurrency bugs

tokio-stream/Cargo.toml, tokio-util/Cargo.toml, tokio/Cargo.toml, tokio/src/time/sleep.rs
Closes #5901 
Hides the documentation for the `Unpin` implementation for `Sleep`.
Not as nice as marking it as `!Unpin`, but at least is less confusing.
Bump the `pin-project-lite` version to the `2.9.11`, which added support to `#[project(!Unpin)]`, in https://github.com/taiki-e/pin-project-lite/pull/76.
Not as nice as showing `!Unpin`, but at least it is less confusing.
=> Hide `Unpin`'s documentation for `Sleep`

tokio/src/doc/os.rs, tokio/src/process/mod.rs, tokio/src/process/unix/mod.rs, tokio/src/process/windows.rs
Fixed #4403 and fixed #5333
`tokio::process::ChildStd*` does not implement `IntoRawFd`/`IntoRawHandle` or any similar method to obtain an owned fd/handle of the child stdin/stdout/stderr.
It makes sense since converting it to a raw fd/handle is fallible operation.
Implement `into_owned_fd` and `into_owned_handle` for these `ChildStd*`, which returns `io::Result<Owned*>` since it is fallible.
I chose to return `OwnedFd`/`OwnedHandle` instead of `RawFd`/`RawHandle` since the msrv has just bumped to 1.63 so we can now use these types and it is much more ergonomic than returning raw ones.
=> process: Impl `{ChildStd*}::into_owned_{fd, handle}`

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
As requested by @Darksonn in #5887
First time doing this for this project so please let me know if if I need to correct something. I went through all of the commits after the v1.29.1 release on June 29 and tried to sort them into the CHANGELOG buckets that made sense but may have misplaced some.
This release bumps the MSRV of Tokio to 1.63. ([#5887])
- tokio: reduce LLVM code generation ([#5859])
- io: support `--cfg mio_unsupported_force_poll_poll` flag ([#5881])
- sync: make `const_new` methods always available ([#5885])
- sync: avoid false sharing in mpsc channel ([#5829])
- rt: pop at least one task from inject queue ([#5908])
- sync: add `broadcast::Sender::new` ([#5824])
- net: implement `UCred` for espidf ([#5868])
- fs: add `File::options()` ([#5869])
- time: implement extra reset …
=> chore: prepare Tokio v1.30.0 release

tokio/src/io/split.rs, tokio/tests/io_split.rs
The current implementation of `AsyncWrite` for `WriteHalf<T>` does not delegate its implementation of `poll_write_vectored` and `is_write_vectored` to the underlying struct. Instead, the default implementation is called, leading to unexpected behaviour.
This PR delegates the implementation `poll_write_vectored` and `is_write_vectored` to the underlying struct, fixing the issue.  
It also adds a test to verify the delegation works as intended.
Fixes #5913.
=> io: delegate poll_write_vectored to inner

tokio/src/runtime/metrics/batch.rs, tokio/src/runtime/metrics/mock.rs, tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/metrics/worker.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/stats.rs, tokio/src/runtime/scheduler/multi_thread_alt/stats.rs, tokio/tests/rt_metrics.rs
Because the runtime uses this value as a tuning heuristic, it can be helpful to get its value. This patch exposes the value as an unstable metric.
=> rt: unstable EWMA poll time metric

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This releases fixes to the alt scheduler, exposes the unstable poll duration metric, and the I/O WriteHalf fix.
=> chore: prepare Tokio v1.31.0 release

tokio-test/src/lib.rs, tokio-test/src/stream_mock.rs, tokio-test/tests/stream_mock.rs
Inroduce a new mock type to tests streams and eventually sinks. Only includes next() and wait() for now.
Basically making a generic Stream mock type https://github.com/tokio-rs/tokio/issues/4106 
Next PR I'd like to add a Sink<T> implementation. Since Sink requires an error type, I think we can do something like this.
```
impl Sink<T> for StreamMock<T> {
// Consume implementation
}
impl <T: Unpin, E: Error> Sink<T> for StreamMock<Result<T,E>> {
type Error = E;
}
```
Main motivation is so we can support splitting the stream mock into a AsyncRead/AsyncWrite.
=> Create StreamMock for testing Streams

tokio/src/process/mod.rs
Stabilise `Command::raw_arg`. Fixes #5929
=> Stabilise Command::raw_arg

tokio/src/sync/broadcast.rs
Fix #5923
Unboundedly looping within `notify_rx` as long as there are still available wakers causes a quadratic slowdown as receivers which are looping receiving from the channel are added. Instead of continually waiting for new wakers, this commit modifies `notify_rx` to stop trying to wake wakers once we've notified a number of wakers greater than or equal to whatever the number of active wakers was when we started notifying.
=> broadcast: Stop notifying after we've woken all wakers

tokio/src/io/async_fd.rs
Fixing or documenting some things I found confusing
- simplify the logic of `try_io` by only checking once whether the error is `WouldBlock`
- document why `AsyncFd` uses an `Option` around its `inner` field.
- remove some `.into()` calls (clearer this way, I think, but also reduced code bloat)
=> io: AsyncFd minor tweaks

tokio/src/runtime/io/scheduled_io.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs
This patch aims to reduce the number of threads that get no-op wakeups.
=> rt(alt): tweak some constants to improve scalability

tokio/src/io/interest.rs, tokio/src/io/ready.rs, tokio/tests/io_async_fd.rs
fixes #5716
The motivation is to await messages arriving in a UdpSocket's error queue. The error queue is a mechanism to asynchronously process errors on a socket. By separating them from the normal queue, error information does not interfere with standard IO, but at the same time better error messages can be given than just a single integer as the result of send/receive.
This potentially has many use cases. My particular one is awaiting when a send timestamp is available.
The solution is to provide `Ready::ERROR`. This is already supported in `mio`, but so far was not exposed in tokio. In combination with `AsyncFd::ready` with some arbitrary interest, this can be used to await error readiness.
One potentially controversial change is that error readiness is reported regardless of …
=> io: add `Ready::ERROR` and report error readiness

tokio/src/io/util/async_read_ext.rs
The documentation implies that BytesMut::with_capacity can be used in protocols that need to read exact numbers of bytes (and where read_exact is too inefficient.) This is incorrect as described in the commit message.
Adjust the documentation.
=> docs: BytesMut::with_capacity does not guarantee exact capacity

tokio/src/runtime/runtime.rs
To get syntax highlights in code docs
Currently:
After adding backticks:
=> docs: added trailing backticks

tokio/src/sync/semaphore.rs
To improve Semaphore examples, as called for in Issue #5933, here is a simple example for limiting access to a File resource.
=> Semaphore example for limiting access to a file

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/once_cell.rs, tokio/src/sync/semaphore.rs
`<OnceCell<T> as From<T>>::from` can be used to construct `OnceCell` from `T` directly, however it isn't available in const.
Add 
```
impl OnceCell {
#[cfg(not(all(loom, test)))]
pub const fn from_value(value: T) -> Self;
}
```
=> sync: Add const fn `OnceCell::from_value`

tokio-test/CHANGELOG.md, tokio-test/Cargo.toml
- deps: fix minimum required version of `async-stream` ([#5347])
- deps: fix minimum required version of `tokio-stream` ([#4376])
- docs: improve `tokio_test::task` docs ([#5132])
- io: fetch actions from mock handle before write ([#5814])
- io: fix wait operation on mock ([#5554])
[#4376]: https://github.com/tokio-rs/tokio/pull/4376
[#5132]: https://github.com/tokio-rs/tokio/pull/5132
[#5347]: https://github.com/tokio-rs/tokio/pull/5347
[#5554]: https://github.com/tokio-rs/tokio/pull/5554
[#5814]: https://github.com/tokio-rs/tokio/pull/5814
=> chore: prepare tokio-test v0.4.3

tokio-util/src/io/copy_to_bytes.rs, tokio-util/src/io/sink_writer.rs, tokio-util/src/io/stream_reader.rs
Implementing feature suggested in issue #5745
Basically what was done is:
- implement Sink for StreamReader<Sink>
- implement Stream for SinkWriterStream>
- implement AsyncRead for SinkWriter<AsyncRead>
- implement Stream for CopyToBytes<Stream>
The implementation is pretty straightforward since the actual work is all demanded to the underlying object, so I thought that introducing new tests would not be really helpful.
=> Enrich StreamReader and SinkWriter

.github/workflows/ci.yml
Currently, Tokio runs cross-compilation checks for the `mips-unknown-linux-gnu` and `mipsel-unknown-linux-musl` target triples. However, Rust has recently demoted these targets from Tier 2 support to Tier 3 (see rust-lang/compiler-team#648). Therefore, MIPS toolchains may not always be available, even in stable releases. This is currently [breaking our CI builds][1], as Rust 1.72.0 does not contain a standard library for `mips-unknown-linux-gnu`.
This branch removes these builds from the cross-compilation check's build matrix. Tokio may still build successfully for MIPS targets, but we can't easily guarantee support when the stable Rust release train may or may not be able to build for MIPS targets.
[1]: https://github.com/tokio-rs/tokio/actions/runs/5970263562/job/16197657405?pr=5947#step …
=> ci: drop MIPS targets from cross-check

tokio/src/sync/mpsc/bounded.rs
This specific issue (data loss because a send got cancelled) has bitten our team a couple of times over the last few months. We've switched to recommending this kind of reserve pattern instead.
Update the documentation to make it clear that data loss can occur if a send is cancelled.
=> sync: improve cancel-safety documentation for mpsc::Sender::send

tokio/src/sync/mod.rs, tokio/src/sync/watch.rs
I found the watch docs as written to be somewhat confusing.
* It wasn't clear to me whether values are marked seen or not at creation/subscribe time.
* The example also confused me a bit, suggesting a while loop when a do-while loop is generally more correct.
* I noticed a potential race with `borrow` that is no longer an issue with `borrow_and_update`.
Update the documentation for the watch module to try and make all this clearer.
=> sync: improve docs for watch channels

tokio/src/fs/file.rs, tokio/src/io/blocking.rs, tokio/tests/fs_file.rs
The `poll_write_vectored` function for `File` currently uses the default implementation in `AsyncWrite`, which only writes the first non-empty buffer in `bufs`. This PR adds proper vectored write support for files.
This implementation copies the maximum permissible data (as determined by the `MAX_BUF` constant) from the buffers to the internal buffer of `File`. All other behavior aligns with the existing `poll_write` method.
Resolves Issue #5949.
=> Implement vectored write functionality for files

tokio-util/src/io/sync_bridge.rs, tokio-util/tests/io_sync_bridge.rs
This keeps us in sync with other I/O wrapper types (e.g. `BufWriter`).
I was working on this change
https://github.com/ostreedev/ostree-rs-ext/pull/527/commits/13455cce4923ac0c3237d3983c2d4044842fb139 and it would have been helpful to be able to call this API so I can return the input stream back to the caller in order to extend its lifetime.
=> SyncIOBridge: Add `into_inner`

tokio-macros/src/entry.rs
At work, we have a crate in our monorepo which is `#![no_std]` for build size reasons. However, we use `tokio` to test that its async functionality is functional in CI for simplicity and leave the other executor for the "real" usage of the library.
In a recent `tokio` update, we started to see this error when compiling its tests:
```
error[E0433]: failed to resolve: could not find `std` in the list of imported crates
--> crypto/crate-name/src/lib.rs:556:5
|
556 |     #[tokio::test]
|     ^^^^^^^^^^^^^^ could not find `std` in the list of imported crates
|
= note: this error originates in the attribute macro `tokio::test` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I was not immediately able to find which commit caused this, but you can observe the cause here: …
=> Use ::core qualified imports instead of ::std inside tokio::test macro

tokio/Cargo.toml
Taskdump documentation is currently not rendered by docs.rs. This PR modifies `package.metadata.docs.r` so that `--cfg tokio_taskdump` is used by docs.rs when building documentation.
Ref. #5638.
=> tokio: render taskdump documentation on docs.rs

tokio/src/process/mod.rs
Documents the fact the `tokio::process::Child::wait` is cancel safe.
Resolves #5976.
=> add cancel-safety documentation for child::wait

README.md, tokio/README.md
List that 1.32.x will be supported until September 2024. The 1.20.x LTS
which is supported until September 2023 has been left, to be removed in
October.
=> chore: list 1.32.x as LTS release

tokio/src/task/local.rs
The location of a spawned task, as shown in tokio console, is taken from
the location set on the tracing span that instruments the task. For this
location to work, there must be unbroken chain of functions instrumented
with `#[track_caller]`.
For `task::spawn_local`, there was a break in this chain and so the
span contained the location of an internal function in tokio.
This change adds the missing `#[track_caller]` attribute. It has been
tested locally as automated tests would really need `tracing-mock` to be
published so we can use it in the tokio tests.
=> task: fix spawn_local source location for console

tokio/src/io/util/mem.rs, tokio/tests/duplex_stream.rs
The `poll_write_vectored` function for `DuplexStream` currently uses the default implementation in `AsyncWrite`, which only writes the first non-empty buffer in `bufs`. This PR adds proper vectored write support for `DuplexStream`.
Instead of only copying the first non-empty buffer, this implementation tries to fill all available space in the internal buffer.
Resolves Issue #5983.
=> implement write_vectored for DuplexStream

tokio-util/src/codec/lines_codec.rs
It is to specify the line ending of `LinesCodec` is `\n`.
=> docs: specify the line ending of LinesCodec

tokio/src/task/spawn.rs
Rename tokio::task::spawn<T> to tokio::task::spawn<F>, to match spawn_local.
I was flipping back and forth between the docs page for [spawn](https://docs.rs/tokio/latest/tokio/task/fn.spawn.html#) and [spawn_local](https://docs.rs/tokio/latest/tokio/task/fn.spawn_local.html#) to understand the differences in which constraints they impose upon their future. I thought it was weird that one is generic over T and one over F.
I think they should match, and F is more descriptive (F for Future).
=> style: Rename spawn<T> to spawn<F>

benches/Cargo.toml, benches/copy.rs, benches/fs.rs, benches/rt_current_thread.rs, benches/rt_multi_threaded.rs, benches/signal.rs, benches/spawn.rs, benches/sync_mpsc.rs, benches/sync_mpsc_oneshot.rs, benches/sync_notify.rs, benches/sync_rwlock.rs, benches/sync_semaphore.rs, benches/sync_watch.rs, benches/time_now.rs
Replaces `bencher` with `criterion`.
Resolves #5979.
=> use criterion

tokio/src/io/interest.rs
=> io: add Interest::remove method

tokio/src/sync/mutex.rs
I can't return a reference to an unsized type in `MutexGuard::map` and `OwnedMutexGuard::map` because of an implicit `Sized` bound in their signature.
Add a `?Sized` bound to the signatures of the two methods. It seems safe at a glance (the mapped guard types already have `?Sized`), but there might be some subtlety somewhere that I overlooked.
=> Add `?Sized` bound for `MutexGuard::map` and `OwnedMutexGuard::map`.

tokio/src/runtime/io/scheduled_io.rs, tokio/src/runtime/task/core.rs, tokio/src/util/cacheline.rs
When reading the tokio source code, I realized it currently uses 32B cache line size for RISC-V, which seems to be not sufficient. (Go uses 32B too, but it's currently known to be too small, see [1])
[1] https://go-review.googlesource.com/c/go/+/526659
Removing all set cache line size of 32B for riscv*, and add reference from kernel that uses 64B cache line size.
=> tokio: fix cache line size for RISC-V

tokio-util/src/sync/reusable_box.rs
Now that MSRV is 1.63 we can remove our `Pending` imlementation.
=> util: replace `sync::reusable_box::Pending` with `std::future::Pending`

tokio/src/sync/mutex.rs, tokio/src/sync/notify.rs, tokio/src/sync/once_cell.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs
The mutex created by `Mutex::const_new()` does not contain the tracing
instrumentation that drives `tokio-console`.
The same is true of `Notify`, `OnceCell` (including `const_new_with()`),
`RwLock`, and `Semaphore`.
This change adds documentation to each of the `const_*` constructors,
explaining that objects created this way will not be instrumented and
therefore will not appear in `tokio-console`. A link to the non-const
variant is provided in each case.
=> sync: document that `const_new()` is not instrumented

tokio/src/runtime/runtime.rs, tokio/src/sync/semaphore.rs
A simple example of limiting request processing using a task-safe semaphore and demonstrating `acquire_owned` for: https://github.com/tokio-rs/tokio/issues/5933
=> Semaphore example using an Arc<Semaphore> for semaphore passing

tokio/src/sync/watch.rs
The `CLOSED_BIT` in the shared state tracks whether the single sender has been dropped.
=> sync::watch::Receiver: Fix code comment

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/io/util/read_until.rs, tokio/src/util/memchr.rs, tokio/src/util/mod.rs
This is a backport of a change from 1.27.0.
- io: use `memchr` from `libc` ([#5960])
[#5960]: https://github.com/tokio-rs/tokio/pull/5960
=> Prepare Tokio v1.20.6

.github/workflows/ci.yml, Cargo.lock, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/future/mod.rs, tokio/src/io/util/read_until.rs, tokio/src/util/memchr.rs, tokio/src/util/mod.rs
Forward ports 1.20.6 changes.
- io: use `memchr` from `libc` ([#5960])
[#5960]: https://github.com/tokio-rs/tokio/pull/5960
=> Prepare Tokio v1.25.2

tokio/src/sync/mutex.rs
The code for dereferencing (*) is on lines 13 and 20.
Fix line number
=> fix incorrect line number in sync::Mutex documentation

tokio/src/sync/semaphore.rs
Implements the token bucket example as listed in #5933.
=> add token bucket example to Semaphore

tokio/src/sync/semaphore.rs
I noticed this after merging the example.
Refs: #5933
=> Reorder semaphore examples

tokio-macros/src/entry.rs, tokio-stream/src/stream_ext/merge.rs, tokio-stream/src/stream_map.rs, tokio-test/src/macros.rs, tokio-util/tests/length_delimited.rs, tokio/src/fs/file.rs, tokio/src/fs/mocks.rs, tokio/src/io/blocking.rs, tokio/src/runtime/handle.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/notify.rs, tokio/src/sync/tests/loom_list.rs, tokio/src/time/error.rs
When we use wildcard `*` in match pattern, it can lead to potential errors.
```rust
enum MyEnum{
TypeA,
TypeB,
TypeC,
}
fn logic(e :MyEnum){
use MyEnum::*;
match e {
TypeA =>  println!("A"),
TypeB =>  println!("B"),
TypeC =>  println!("C"),
}
}
```
If we delete `TypeC`，add add `TypeD`
```
enum MyEnum{
TypeA,
TypeB,
TypeD,
}
fn logic(e :MyEnum){
use MyEnum::*;
match e {
TypeA =>  println!("A"),
TypeB =>  println!("B"),
TypeC =>  println!("C"),
}
}
```
The Rust compiler takes `TypeC` as a named variables,  not a variant of the enum, and the unexpected error occurs.
So we should never use such as `use MyEnum::*;` wildcard in Rust code.
=> tokio: remove wildcard in match pattern

tokio/src/sync/semaphore.rs
This makes the `TokenBucket::close` method into a destructor so you can't forget to kill the task.
Follow up to #5978. I didn't think of this when I reviewed the original PR.
cc @maminrayej 
[Rendered](https://deploy-preview-6032--tokio-rs.netlify.app/tokio/sync/struct.semaphore#rate-limiting-using-a-token-bucket)
=> Make `TokenBucket::close` into a destructor

tokio/src/sync/watch.rs
If the provided closure panics the lock is poisoned.
Adopt the `catch_unwind()` strategy that is already used elsewhere.
=> watch::Receiver::wait_for(): Prevent poisoning of the lock

tokio/src/sync/watch.rs
`SeqCst` is overly restrictive.
Use `Release` (`Sender`: store / single writer) and `Acquire` (`Receiver`: load / multiple readers) memory ordering for a safe handover.
=> `sync::watch`: Use Acquire/Release memory ordering instead of SeqCst

benches/sync_watch.rs
The PR #5464 introduced a new bucket notifier to reduce contention in the `watch` channel. That change was motivated by the benchmark added in #5472. However, this benchmark does not present favorable results for the newer notifier if we compare it with the older solution.
Results with the new notifier:
`contention_resubscribe  time:   [81.507 ms 82.098 ms 82.740 ms]`
Results without it:
`contention_resubscribe  time:   [38.254 ms 38.938 ms 39.618 ms]`
This is most likely due to [sender task not running on a worker thread](https://github.com/tokio-rs/tokio/issues/5403#issuecomment-1432118096).
Change the existing `watch` channel benchmark by moving the benchmarked loop to a spawned task, which will be executed by one of the worker threads. With this change the results are more comparable: …
=> benches: move sender to a spawned task in `watch` benchmark

tokio/src/io/interest.rs
Like in https://github.com/tokio-rs/mio/pull/1694. 
Marking `is_*` methods makes little bit less sense to me but if that's something desirable I'll mark those as well.
=> io: mark Interest::add as must_use

tokio/tests/rt_threaded.rs
=> rt: fix flaky test `test_disable_lifo_slot`

tokio/src/sync/broadcast.rs
=> Document that broadcast capacity is lower bound

tokio-util/tests/udp.rs, tokio/src/net/unix/ucred.rs
This PR allows using tokio lib to target [tier 3 *-apple builds](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-tvos.html):
- Apple tvOS on aarch64
- Apple tvOS Simulator on x86_64
=> Add apple tvos support

tokio/src/sync/semaphore.rs
Add last example to semaphore described at this [issue](https://github.com/tokio-rs/tokio/issues/5933) 
A simple example that prevent several tests from running at the same time, using a static semaphore with one permit.
[Rendered](https://deploy-preview-6038--tokio-rs.netlify.app/tokio/sync/struct.semaphore#prevent-tests-from-running-in-parallel)
=> docs: add semaphore example

tokio/src/sync/semaphore.rs
I noticed a few remaining improvements to the semaphore documentation. Fix them here.
=> Semaphore doc final cleanup

tokio/tests/time_sleep.rs
We've had test failures due to this test being really slow. In the run below, CI later timed out while running some later tests:
```
SLOW [> 60.000s] tokio::time_sleep short_sleeps
SLOW [>120.000s] tokio::time_sleep short_sleeps
PASS [ 147.928s] tokio::time_sleep short_sleeps
------------
Summary [ 238.734s] 1186 tests run: 1186 passed (2 slow), 13 skipped
```
Reducing the number of iterations should help with this.
=> time: reduce iteration count in short_sleeps test

tokio/src/net/unix/pipe.rs, tokio/src/runtime/context.rs, tokio/src/sync/mod.rs
This fixes new documentation warnings in 1.73.0.
```
warning: unused doc comment
--> tokio/src/runtime/context.rs:83:13
|
83 |             /// Tracks the current runtime handle to use when spawning,
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
86 |             current: current::HandleCell::new(),
|             ----------------------------------- rustdoc does not generate documentation for expression fields
|
= help: use `//` for a plain comment
= note: `#[warn(unused_doc_comments)]` on by default
warning: unused doc comment
--> tokio/src/runtime/context.rs:84:13
|
84 |             /// accessing drivers, etc...
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
85 |             #[cfg(feature = "rt")]
86 |             current: current::HandleCell::new(),
| …
```
=> docs: fix new doc warnings in 1.73.0

tokio-util/src/io/sync_bridge.rs
I want to use a type that implements `AsyncSeek` with sync code.
This PR implements `std::io::Seek` for `tokio_util::io::SyncIoBridge`.
=> Implement std::io::Seek for tokio_util::io::SyncIoBridge

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- io: mark `Interest::add` with `#[must_use]` ([#6037])
- runtime: fix cache line size for RISC-V ([#5994])
- sync: prevent lock poisoning in `watch::Receiver::wait_for` ([#6021])
- task: fix `spawn_local` source location ([#5984])
- macros: use `::core` imports instead of `::std` in `tokio::test` ([#5973])
- sync: use Acquire/Release orderings instead of SeqCst in `watch` ([#6018])
- fs: add vectored writes to `tokio::fs::File` ([#5958])
- io: add `Interest::remove` method ([#5906])
- io: add vectored writes to `DuplexStream` ([#5985])
- net: add Apple tvOS support ([#6045])
- sync: add `?Sized` bound to `{MutexGuard,OwnedMutexGuard}::map` ([#5997])
- sync: add `watch::Receiver::mark_unseen` ([#5962], [#6014], [#6017])
- sync: add `watch::Sender::new` ([#5998])
- sync: add const fn …
=> chore: prepare Tokio v1.33.0 release

netlify.toml
This should make reviews of taskdump-related PRs easier before task dumps get stabilized.
=> chore: render taskdump docs in Netlify previews

tokio/src/runtime/io/scheduled_io.rs, tokio/tests/io_async_fd.rs
Trying to perform an IO operation after runtime shutdown currently results in an error, and this is intentional. However, if you perform an IO operation, then shut down the runtime, and then call `clear_readiness`, then this does not trigger that error. Instead, it hits an internal `debug_assert!` codepath.
We fix this by allowing `clear_readiness` after runtime shutdown.
Fixes: #6066
=> io: allow `clear_readiness` after io driver shutdown

README.md, tokio/README.md
Since it's already October 2023, we should drop long-term support for Tokio 1.20.x.
=> chore: move 1.20.x to previous LTS releases

tokio/CHANGELOG.md
Since we did not make a tokio-macros release, #5973 was not part of 1.33.0.
=> tokio: remove #5973 from changelog

tokio/src/net/tcp/stream.rs
This test failed in CI because the port was in use.
=> net: fix flaky doctest for `TcpStream::into_std`

tokio-util/src/task/join_map.rs, tokio-util/src/task/mod.rs, tokio-util/tests/task_join_map.rs
In a library I am developing, I need to know what tasks are contained in a JoinMap.
=> util: add `JoinMap::keys`

tokio/src/task/local.rs, tokio/tests/task_local_set.rs
This fixes: https://github.com/tokio-rs/tokio/issues/5020
If we enter a `LocalSet`, then the `LocalEnterGuard` sets `CURRENT` with it. But the `CURRENT` is being used with both of these two situations:
1. task::spawn_local()
2. being polled
But as we know, `LocalEnterGuard` should be related only with (1). When we schedule it, we should check if it is being polled, or just being entered. So I added a boolean variable to distinguish these situations.
=> tokio: distinguish LocalSet::enter() with being polled

README.md, tokio/README.md
We should mention axum in this list.
Also remove rdbc, because the rdbc project doesn't seem to be maintained anymore.
=> reame: remove rdbc and add axum to related projects

tokio-util/Cargo.toml
For details see #6101 
Closes #6101
=> deps(tokio-util): update hashbrown to 0.14

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- task: add `TaskTracker` ([#6033])
- task: add `JoinMap::keys` ([#6046])
- io: implement `Seek` for `SyncIoBridge` ([#6058])
- deps: update hashbrown to 0.14 ([#6102])
[#6033]: https://github.com/tokio-rs/tokio/pull/6033
[#6046]: https://github.com/tokio-rs/tokio/pull/6046
[#6058]: https://github.com/tokio-rs/tokio/pull/6058
[#6102]: https://github.com/tokio-rs/tokio/pull/6102
=> chore: prepare tokio-util v0.7.10

tokio/tests/rt_common.rs, tokio/tests/task_abort.rs, tokio/tests/task_blocking.rs
These tests only pass if panics are configured to unwind.
Refs: #6109
=> tokio: gate panicking tests with `#[cfg(panic = "unwind")]`

.github/workflows/ci.yml, tokio/tests/tracing-instrumentation/Cargo.toml, tokio/tests/tracing-instrumentation/tests/task.rs
Tokio is instrumented with traces which can be used to analyze the
behavior of the runtime during execution or post-mortem. The
instrumentation is optional. This is where tokio-console collections
information.
There are currently no tests for the instrumentation.
In order to provide more stability to the instrumentation and prepare
for future changes, tests are added to verify the current behavior. The
tests are written using the `tracing-mock` crate. As this crate is still
unreleased, a separate test create has been added under `tokio/tests`
which is outside the workspace. This allows us to pull in both `tracing`
and `tracing-mock` from the tracing repository on GitHub without
affecting the rest of the tokio repository.
Once `tracing-mock` is published on crates.io …
=> task: add tests for tracing instrumentation of tasks

tokio/src/doc/mod.rs
Since the latest nightly, rustdoc has started failing with the following error:
```
error[E0277]: the trait bound `doc::NotDefinedHere: mio::event::Source` is not satisfied
--> tokio/src/net/windows/named_pipe.rs:104:9
|
104 |     io: PollEvented<mio_windows::NamedPipe>,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `mio::event::Source` is not implemented for `doc::NotDefinedHere`
|
= help: the following other types implement trait `mio::event::Source`:
std::boxed::Box<T>
mio::unix::SourceFd<'a>
mio::unix::pipe::Sender
mio::unix::pipe::Receiver
mio::io_source::IoSource<T>
mio::net::TcpListener
mio::net::TcpStream
mio::net::UdpSocket
and 4 others
note: required by a bound in `io::poll_evented::PollEvented`
--> tokio/src/io/poll_evented.rs:65:38
|
65  |     pub(crate) struct …
```
=> ci: fix docs on latest nightly

tokio-stream/src/stream_ext.rs, tokio-stream/src/stream_ext/peekable.rs
Sometimes it's usefull to peek at the first element of a stream, without consuming it. This PR adds the `peekable` method to `StreamExt` to do that. This is akin to:
- https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.peekable
- https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.peekable
=> tokio-stream: add `StreamExt::Peekable` method

tokio-macros/Cargo.toml, tokio-stream/Cargo.toml, tokio-test/Cargo.toml, tokio-util/Cargo.toml
=> chore: update rust-version to 1.63 in all crates

tokio/src/runtime/time/mod.rs
The time driver stores the number of elapsed units of time in a variable and keeps it in sync with the same counter inside the timer wheel. Since the variable is only used to ensure that we poll the timer wheel with monotonic instants, we may as well use the actual counter from the wheel and avoid redundancy.
=> time: remove cached `elapsed` value from driver state

tokio/src/runtime/scheduler/multi_thread/worker.rs
Fixes #6129
I am not an expert on the runtime implementation, but looking at the code it seems like we should reset the start time for processing scheduled tasks when the worker thread unparks. Otherwise it only happens occasionally when calling `Context::maintenance`, which is why the worker busy duration metrics were getting so large.
Using the following program:
```rust
use std::time::Duration;
use tokio::runtime::{Handle, RuntimeMetrics};
fn main() {
tokio::runtime::Builder::new_multi_thread()
.enable_all()
.worker_threads(3)
.build()
.unwrap()
.block_on(async {
let metrics = Handle::current().metrics();
std::thread::spawn(|| track_event_load(metrics));
tokio::spawn(async move {
loop {
tokio::time::sleep(Duration::from_millis(100)).await;
}
});
tokio::signal::ctrl_c().await.unwrap(); …
```
=> Update stats when unparking worker in multi-threaded runtime

tokio/src/runtime/io/driver.rs, tokio/src/runtime/io/scheduled_io.rs
Use a per-resource tick instead of a single global tick counter. This prevents the hang issue described by #6133.
As a follow-up, I would like to increase the number of bits used to track the tick in `ScheduledIo`. Because this change is not necessary to fix the original issue, I am punting.
Fixes: #6133
=> io: fix possible I/O resource hang

tokio/src/runtime/io/scheduled_io.rs
While this is no current evidence that increasing the tick resolution is necessary, since we have available bits, we might as well use them.
This is a follow up to #6134
=> io: increase `ScheduledIo` tick resolution

tokio/src/runtime/context.rs, tokio/tests/rt_common.rs
Fixes a panic when a waker is woken after the thread-local is destroyed.
Closes: #6091
=> runtime: handle missing context on wake

tokio/src/io/util/async_write_ext.rs
=> io: flush in `AsyncWriteExt` examples

tokio/src/task/local.rs
=> task: document cancel safety of `LocalSet::run_until`

tokio/src/runtime/handle.rs
The documentation for the `Handle::dump()` method includes a description
of the Rust flags needed. However, the sample `.cargo/config.toml` file
is incorrect.
The documentation gives the Rust flags as:
```
rustflags = ["--cfg tokio_unstable", "--cfg tokio_taskdump"]
```
However, each command line argument needs to be a separate element in
the array:
```
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]
```
This change corrects that line.
=> docs: fix task dump cargo config example

tokio/src/sync/barrier.rs, tokio/src/sync/mutex.rs, tokio/src/sync/oneshot.rs, tokio/src/sync/rwlock.rs, tokio/src/sync/semaphore.rs, tokio/src/time/interval.rs, tokio/tests/tracing-instrumentation/tests/sync.rs
Most of the context for this PR can be found in [this issue](https://github.com/tokio-rs/tokio/issues/6106).
The `TRACE` `resource_span` that `Mutex` and `RWLock` create when using `new` can keep open their parent for as long as the mutex lives. This pull request changes these spans to have a parent of `None` rather than having a *parent-child* relation ship with the current span.
As mentioned by @davidbarsky in the linked issue, another possibility could be to alter the API and accept a parent span. I'm open to changing this PR although I agree it feels strange when it comes to `tracing`.
Looking for existing tests, I wasn't sure if regression testing this (which would require bringing a tracing subscriber most likely) was necessary here. Open to adding this as well.
=> sync: avoid creating mutex and rwlock resource_span with parent, use None parent instead

tokio/src/util/trace.rs
In Tokio, tasks are optionally instrumented with tracing spans to allow
analysis of the runtime behavior to be performed with tools like
tokio-console.
The span that is created for each task gets currently follows the
default tracing behavior and has a contextual parent attached to it
based on the span that is actual when `tokio::spawn` or similar is
called.
However, in tracing, a span will remain "alive" until all its children
spans are closed. This doesn't match how spawned tasks work. A task may
outlive the context in which is was spawned (and frequently does). This
causes tasks which spawn other - longer living - tasks to appear in
`tokio-console` as having lost their waker when instead they should be
shown as completed (tokio-rs/console#345). It can also cause undesired
behavior for …
=> task: make task span explicit root

tokio-util/src/time/delay_queue.rs
When implementing a cache with item expirations ([example from mini-redis](https://github.com/tokio-rs/mini-redis/blob/9b93f751b3cd0fb84e27ad1f938da8121ce1e83b/src/db.rs#L154-L158)), it's not possible to use `DelayQueue` as a more efficient backing store for the expirations. The reason is, when inserting/removing/modifying a cache entry there needs to be a way to determine whether the ["next expiring time" has changed](https://github.com/tokio-rs/mini-redis/blob/9b93f751b3cd0fb84e27ad1f938da8121ce1e83b/src/db.rs#L175-L178) as a result of the operation. Basically, you'd need an api similar to [`DelayQueue::peek`](https://docs.rs/tokio-util/0.7.10/src/tokio_util/time/delay_queue.rs.html#906) but for the next deadline in the queue. However, currently `DelayQueue` does not expose such an api, …
=> util: add `DelayQueue::deadline`

tokio/src/net/unix/socketaddr.rs
I am using a UnixListener which is connected to from systemd from
and abstract namespace socket, which I would like to have the name of.
Add the as_abstract_namespace function to the wrapper.
I am not sure where to test this, please let me know where to
add a test and I will add one.
=> net: add support for getting abstract namespace from socketaddr

tokio/src/runtime/builder.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/task/abort.rs, tokio/src/runtime/task/error.rs, tokio/src/runtime/task/join.rs, tokio/src/sync/mutex.rs, tokio/src/task/mod.rs
=> runtime: document fairness guarantees and current behavior

tokio-util/tests/udp.rs, tokio/src/net/unix/ucred.rs
This is a sibling PR to #6045. watchOS and tvOS have similar tier status (tier-3) from rustc. I have validated that this change fixes the watchOS build in https://github.com/liveview-native/liveview-native-core/pull/33.
Add `target_os = "watchos"` next to places to where `tvos` occurs.
=> Add Apple watchOS support

tokio/src/runtime/runtime.rs
Closes: https://github.com/tokio-rs/tokio/issues/6188
=> Make tokio `Runtime` be unwind-safe

tokio/src/runtime/task/mod.rs, tokio/src/runtime/task/state.rs, tokio/src/runtime/task/trace/mod.rs, tokio/tests/dump.rs
Fixes #6051. Tremendous thanks to @Darksonn for figuring out the cause, and helping me formulate this fix.
=> runtime: skip notified tasks during taskdumps

tokio/src/loom/std/atomic_u16.rs, tokio/src/loom/std/atomic_u32.rs, tokio/src/loom/std/atomic_usize.rs
=> chore: use relaxed load for `unsync_load`

tokio/src/io/util/async_read_ext.rs, tokio/src/io/util/read_buf.rs
`AsyncReadExt.read_buf` takes both `Self` and its buffer argument by mut ref, yet requires `Sized` for both of them,
disallowing `dyn Trait` for no good reason.
Remove the explicit `Sized` requirement for `Self`, and introduce `?Sized` in relevant places.
See also #6161
=> io: drop the `Sized` requirements from `AsyncReadExt.read_buf`

tokio/src/util/wake_list.rs
I noticed that the safety comments for `WakeList` were lacking, so improve them. Also removes an unnecessary unsafe block.
=> sync: improve safety comments for WakeList

tokio/src/loom/std/atomic_u16.rs, tokio/src/loom/std/atomic_u32.rs, tokio/src/loom/std/atomic_usize.rs
=> chore: use relaxed load for unsync_load 2

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- net: add Apple watchOS support ([#6176])
- io: drop the `Sized` requirements from `AsyncReadExt.read_buf` ([#6169])
- runtime: make `Runtime` unwind safe ([#6189])
- runtime: reduce the lock contention in task spawn ([#6001])
- tokio: update nix dependency to 0.27.1 ([#6190])
- chore: make `--cfg docsrs` work without net feature ([#6166])
- chore: use relaxed load for `unsync_load` on miri ([#6179])
- runtime: handle missing context on wake ([#6148])
- taskdump: fix taskdump cargo config example ([#6150])
- taskdump: skip notified tasks during taskdumps ([#6194])
- tracing: avoid creating resource spans with current parent, use a None parent instead ([#6107])
- tracing: make task span explicit root ([#6158])
- io: flush in `AsyncWriteExt` examples ([#6149])
- runtime: document fairness …
=> chore: prepare Tokio v1.35.0

tokio/src/task/mod.rs
Improve the crate's documentation.
Fix a small typo in the documentation of `tokio::task`.
=> docs: fix typo in `tokio::task` documentation

benches/copy.rs, tokio-macros/src/entry.rs, tokio/CHANGELOG.md, tokio/src/process/mod.rs
Minor spelling coordination between documents.
Standardizes spelling of `behavior`.
All instances modified in-place.
=> typo fixes

Cargo.lock, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- io: add budgeting to `tokio::runtime::io::registration::async_io` ([#6221])
[#6221]: https://github.com/tokio-rs/tokio/pull/6221
=> chore: release v1.25.3

tokio/CHANGELOG.md, tokio/src/runtime/context.rs, tokio/src/runtime/io/registration.rs, tokio/tests/coop_budger.rs
This is part of a LTS release for #6221. Must be merged from the command-line.
=> Merge 'tokio-1.25.3' into 'tokio-1.32.x'

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/context.rs, tokio/src/runtime/io/registration.rs, tokio/tests/coop_budger.rs
This is a forward part of a change that was backported to 1.25.3.
- io: add budgeting to `tokio::runtime::io::registration::async_io` ([#6221])
[#6221]: https://github.com/tokio-rs/tokio/pull/6221
=> Prepare Tokio v1.32.1

tokio/CHANGELOG.md, tokio/src/runtime/io/registration.rs, tokio/tests/coop_budger.rs
This is part of a LTS release for https://github.com/tokio-rs/tokio/pull/6221. Must be merged from the command-line.
=> Merge 'tokio-1.32.1' into 'tokio-1.35.x'

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/io/registration.rs, tokio/tests/coop_budger.rs
This is a forward part of a change that was backported to 1.25.3.
- io: add budgeting to `tokio::runtime::io::registration::async_io` ([#6221])
[#6221]: https://github.com/tokio-rs/tokio/pull/6221
=> Prepare Tokio v1.35.1

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/io/registration.rs, tokio/tests/coop_budger.rs
This is part of a LTS release for https://github.com/tokio-rs/tokio/pull/6221. Must be merged from the command-line.
=> Merge 'tokio-1.35.1' into 'master'

tokio/src/io/join.rs, tokio/src/io/mod.rs, tokio/tests/io_join.rs
Adds a simple `Join` utility to join an `AsyncRead` and `AsyncWrite` into a single value.
I have been writing some async networking code, and ran into this problem a few times. I wrote a similar utility in my code, and figured others may find it useful as well.
=> io: add Join utility

tokio/src/io/util/empty.rs
Fixes: #6233
The standard io `Empty` implements both `Read` and `Write`, so I thought the async version should as well. I thought it would be useful in scenarios that require a single instance to be both `AsyncRead + AsyncWrite`.
The solution implements `AsyncWrite for Empty` and adds a doctest as an example. Much of the documentation is copied from [std::io::empty()](https://doc.rust-lang.org/std/io/fn.empty.html).
=> io: implement `AsyncWrite` for `Empty`

tokio-util/src/either.rs
=> feat: Adding Sink trait impl to Either

benches/rt_current_thread.rs, benches/rt_multi_threaded.rs
Because the name overlaps, criterion confuses these benchmarks when computing regressions.
=> benches: fix benchmarking conflicts

tests-build/tests/fail/macros_type_mismatch.stderr, tokio/src/future/mod.rs
This try to fixes errors occured with the latest 1.75.0 compiler changes.
How to fail can be found [here](https://github.com/tokio-rs/tokio/actions/runs/7355955020).
=> chore: Fixing failures with the latest compilers

tokio/src/io/util/empty.rs, tokio/src/io/util/mod.rs, tokio/src/io/util/repeat.rs, tokio/src/io/util/sink.rs, tokio/tests/io_repeat.rs, tokio/tests/io_sink.rs
Closes https://github.com/tokio-rs/tokio/issues/6249.
`repeat` and `sink` will always succeed without checking the coop budget, so this PR enables them to yield control back to the runtime.
Add a `coop` hook to its implementation. In addition, add instruments for tracing, as previous works have done.
https://github.com/tokio-rs/tokio/pull/6221, https://github.com/tokio-rs/tokio/pull/4478, https://github.com/tokio-rs/tokio/pull/4300,
=> io: make `repeat` and `sink` cooperative

tokio/src/sync/watch.rs, tokio/tests/sync_watch.rs
Closes #6086
`watch::Receiver` now has a method `mark_unchanged` that just sets that receiver's version to the current version
=> Add `mark_unchanged` method to `watch::Receiver`

tokio-stream/src/stream_map.rs, tokio-test/src/stream_mock.rs, tokio-util/src/task/join_map.rs, tokio/src/io/util/flush.rs, tokio/src/runtime/task/core.rs
A few typographic improvements that I came across.
=> chore: typographic improvements

.cargo/audit.toml, tokio/Cargo.toml, tokio/tests/io_poll_aio.rs
This is a test-only dependency.  The main reason for the update is to avoid transitively depending on a Nix version with a CVE.
mio-aio 0.8.0 has a substantially different API than 0.7.0.  Notably, it no longer includes any lio_listio functionality.  So to test Tokio's handling of EVFILT_LIO events we must go low-level and call libc::lio_listio directly.
Supersedes #6260
Eliminate a transitive dev dependency on a Nix version with a CVE.
Update the mio-aio dev dependency to 0.8.0
=> Update mio-aio to 0.8

tokio/src/io/util/copy.rs, tokio/tests/io_copy.rs, tokio/tests/io_copy_bidirectional.rs
close https://github.com/tokio-rs/tokio/issues/6250
Add poll_proceed_and_make_progress to check if it exceeds the budget.
=> io: make copy cooperative

tokio/src/task/join_set.rs, tokio/src/util/idle_notified_set.rs, tokio/tests/task_join_set.rs
This PR implements the `try_join_next` function on `JoinSet`. It also adds a test to make sure the implementation works.
There is also `join_next_with_id` which is unstable. I could also add `try_join_next_with_id` if this implementation is acceptable. Or, it could be added later on when `join_next_with_id` is stable.
Resolves #6277.
=> implement try_join_next

tokio-util/src/time/mod.rs
Closes https://github.com/tokio-rs/tokio/issues/6047
We simply add an extension trait, wrapping the existing `time::timeout` method to reduce duplication.
=> time: add Future::timeout method via FutureExt

.github/workflows/ci.yml, tokio-stream/tests/stream_panic.rs, tokio-util/tests/panic.rs, tokio-util/tests/spawn_pinned.rs, tokio-util/tests/time_delay_queue.rs, tokio/src/runtime/tests/task_combinations.rs, tokio/tests/io_panic.rs, tokio/tests/join_handle_panic.rs, tokio/tests/net_panic.rs, tokio/tests/process_issue_2174.rs, tokio/tests/rt_handle.rs, tokio/tests/rt_panic.rs, tokio/tests/signal_panic.rs, tokio/tests/sync_panic.rs, tokio/tests/task_panic.rs, tokio/tests/time_panic.rs, tokio/tests/time_pause.rs
Verifies that all tests pass with panic=abort by adding a step to CI. Also, gates tests that need unwinding with `#[cfg(panic = "unwind")]`.
Resolves #6109.
=> ci: gate unwind tests and add ci step for tesing with panic=abort

tokio/src/runtime/park.rs
Maybe `get_unpark()` doesn't exist in tokio anymore?
=> chore: Remove old comment 

tokio/tests/macros_test.rs
Context: #6307 
The test `trait_method` was designed to prevent breaking changes for `#[tokio::main]` on trait methods.
However, previous implementation didn't access self so it was unable to catch some case of breaking changes.
Created another method `g(self)` and called it to access `self`.
=> macros: fix trait_method breaking change detection

benches/Cargo.toml, benches/sync_broadcast.rs, tokio/src/sync/broadcast.rs
As stated in #5465, the broadcast channel is subject to contention when the number of consumers is high. This PR tries to alleviate this issue by allowing `Recv::drop` to skip taking a lock if a value is successfully received.
The proposed solution is to make the `queued` variable atomic. This way, `Recv` can atomically determine that the contained waiter is not enqueued for notification, so no synchronization with producers is required.
The PR includes a benchmark that on my machine shows the following results vs master:
```
contention/10           time:   [3.6555 ms 3.6723 ms 3.6895 ms]
change: [+1.6649% +2.3708% +3.0364%] (p = 0.00 < 0.05)
contention/100          time:   [18.266 ms 18.300 ms 18.336 ms]
change: [-13.471% -13.245% -13.032%] (p = 0.00 < 0.05)
contention/500          time: …
```
=> Don't take the tail lock when dropping broadcast channel's `Recv` future

tokio/src/io/async_fd.rs
=> io: clarify `clear_ready` and `clear_ready_matching` documentation

tokio/src/net/tcp/socket.rs
It was decided in the Discord discussion to only support enabling the keep-alive option since it is portable across different platforms.
Resolves #6214.
=> net: expose keepalive option on `TcpSocket`

tokio/src/task/join_set.rs
When using `JoinSet` I usually end up populating it from an iterator, which would be more convenient with `collect`.
Implement `FromIterator`.
(Possibly, spawning each element of the iter is too magical / side-effecty for a `FromIterator` impl though.)
Closes: #6132
=> task: implement `FromIterator` for `JoinSet`

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/unbounded.rs
This sometimes causes confusion because a single line with `tx.downgrade()` doesn't actually downgrade it.
=> Make downgrade must_use

examples/dump.rs, tokio/src/runtime/dump.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/worker/taskdump.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task/trace/mod.rs, tokio/tests/dump.rs
Task `Id`s provide a semi-stable identifier for monitoring task state across task dumps.
Fixes #6313
=> runtime: include task `Id` in taskdumps

tokio/src/sync/batch_semaphore.rs, tokio/src/sync/semaphore.rs, tokio/src/sync/tests/loom_semaphore_batch.rs, tokio/src/sync/tests/semaphore_batch.rs
This PR adds a method to the semaphore that reduces the number of permits.
resolve https://github.com/tokio-rs/tokio/issues/5308.
Implement `forget_permits` that reduces the semaphore's permits by a maximum of `n` and returns the number of permits that were actually reduced.
=> sync: Add `forget_permits` method to semaphore

.github/workflows/ci.yml, CONTRIBUTING.md, benches/copy.rs, benches/rt_multi_threaded.rs, benches/sync_broadcast.rs, examples/custom-executor-tokio-context.rs, stress-test/examples/simple_echo_tcp.rs, tokio-util/src/codec/framed_impl.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs
This updates the CI to use clippy version 1.76 which is aligned with the rust stable version.
=> chore: update CI to clippy 1.76

tokio/src/io/util/async_read_ext.rs
=> io: document cancel safety of `AsyncReadExt`'s primitive read functions

tokio/src/macros/select.rs, tokio/tests/macros_select.rs
Closes #6338
It's the propesed <s>"Alternative 3"</s> "Alternative 5" described in [here](https://github.com/tokio-rs/tokio/issues/6338).
It simply adds a special case for when the `select!` has no branches except for the `else` fallback branch (for the case with and without `biased` mode). It will simply expand to the code in `$else`.
I added 2 tests case too to cover it.
=> macro select no branch else only

tokio/src/runtime/io/driver.rs, tokio/src/runtime/io/registration_set.rs
It is possible for `add_source` to fail when registering a source with the OS and leak the allocated slot in the registration set. This PR removes the allocated slot in the case of a failure in order to prevent this issue.
I could call `registrations.deregister` and let the `io::Driver` remove the slot on its next `turn`. But since the registration failed, and there won't be any event for the provided source, I believe it is safe to remove the entry directly.
=> runtime: fix leaking registration entries when os registration fails

tokio/src/task/task_local.rs, tokio/tests/task_local.rs
Try to resolve https://github.com/tokio-rs/tokio/issues/5743.
This PR adds a method `take_value` to take the task local value of a `TaskLocalFuture`.
The `LocalKey::scope()` function owns the slot value and drops it, but this method will allow you to re-acquire ownership of the slot value.
Implemented method `take_value` for a pinned `TaskLocalFuture`.
Maybe it is possible to provide non-pinned api as well (`pub fn take_value(&mut self) -> Option<T>`), but I'm not sure if it is worth providing both.
=> task: Add `TaskLocalFuture::take_value` method to the `task_local`

.github/workflows/ci.yml
We're seeing this intermittent test failure #6361 on cross-compiled builds.  The errors I've seen are on the test `cross-test-with-parking_lot` for target `aarch64-unknown-linux-gnu`
Here's an example: https://github.com/tokio-rs/tokio/actions/runs/7918173089/job/21616135686#step:7:611
```
2024-02-15T15:26:37.7973513Z thread 'alt_threaded_scheduler_4_threads::panic_in_block_on' panicked at tokio/tests/rt_common.rs:880:29:
2024-02-15T15:26:37.7975804Z explicit panic
2024-02-15T15:26:37.7977671Z stack backtrace:
2024-02-15T15:26:37.7979839Z qemu-aarch64: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
```
The QEMU internal SIGSEGV points to a potential QEMU bug.  This change downgrades QEMU to 7.2 for the cross-compilation builds which is reported to be a more stable version.    
I didn't …
=> ci: downgrade to QEMU 7.2 for cross-compile builds (#6361)

tokio/src/runtime/runtime.rs
This allows people who wish to read about the macro to get to its full documentation in one click instead of two.
=> Add doc link from `Runtime` to `#[tokio::main]`.

.cirrus.yml
I saw the CI job fail due to the older FreeBSD no longer being available.
=> ci: update FreeBSD image to 14

README.md, tokio/README.md
This PR marks the latest release of Tokio as an LTS release, replacing the previous 1.25.x series that has just expired as an LTS.
=> Mark 1.36 as an LTS release

tokio/src/sync/broadcast.rs
Missing period at the end of a docstring sentence.
Add the missing period.
=> Add missing period to docstring for broadcast::Sender::receiver_count

tokio-test/src/task.rs
A task passed to `Spawn` will not be executed unless it is polled, and it would be more helpful to add `must_use` annotation.
=> tokio-test: mark `tokio_test::task::Spawn` as `must_use`

.circleci/config.yml
The ubuntu image currently being used for the circleci ARM test is deprecated
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
We did see a [failing CI test ](https://app.circleci.com/pipelines/github/tokio-rs/tokio/5524/workflows/44c44024-a642-4835-93b4-7ab454397deb/jobs/5297?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary)on PR #6378  during the recent circleci brown out on 4th March 
```
This job was rejected because the image 'ubuntu-2004:202101-01' is [unavailable](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/)
```
Updated circleci to use the default image tag.   
Note this also updates it to use `22.04` rather than `20.04`
=> chore: fix deprecated circleci image

tokio/src/runtime/runtime.rs
=> runtime: make the `enter` example deterministic

tokio/src/sync/tests/loom_watch.rs, tokio/src/sync/watch.rs, tokio/tests/sync_watch.rs
This PR attempt to resolve https://github.com/tokio-rs/tokio/issues/4809.
Currently, watch channel has only one sender but this enable it to be mpmc by adding a `clone` of the sender.
As with the reciever, the `ref_count_tx` field is added to the shared structure to record the number of senders; this counter is incremented by the sender's `clone` method and decremented by the `drop` method.
=> sync: Implement `Clone` for `watch::Sender` 

tokio/src/sync/once_cell.rs
This reorders the functions on `OnceCell` so that they appear in this order: `new`, `const_new`, `new_with`, `const_new_with`. Changing the order improves the documentation, as they appear in the same order there.
I know that the diff doesn't show it that way, but I really did just reorder the methods.
=> sync: reorder const_new before new_with

tokio/src/sync/mod.rs, tokio/src/sync/watch.rs
Follow up to https://github.com/tokio-rs/tokio/pull/6388.
With the above pull request, the watch channel is no longer necessarily a single producer. This PR updates docs that specify single producer.
=> sync: update watch channel docs

tokio-util/src/sync/mpsc.rs, tokio-util/tests/mpsc.rs
In PR #5665, the `'static` bound has been removed on values sent into `PollSender`. One of this bound was remaining on the `PollSender` implementation of `Sink`.
This patch removes the bound and adds some tests on the `Sink` interface for `PollSender`.
=> tokio-util: remove `'static` bound on `impl Sink for PollSender`

tokio/src/io/async_fd.rs, tokio/src/io/mod.rs, tokio/tests/io_async_fd.rs, tokio/tests/io_panic.rs
=> io: implement `try_new` and `try_with_interest` for `AsyncFd`

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml
This release bumps the MSRV of tokio-stream to 1.63.
- docs: fix typo in argument name ([#6389])
- docs: fix typo in peekable docs ([#6130])
- docs: link to latest version of tokio-util docs ([#5694])
- docs: typographic improvements ([#6262])
- stream: add `StreamExt::peekable` ([#6095])
[#5694]: https://github.com/tokio-rs/tokio/pull/5694
[#6095]: https://github.com/tokio-rs/tokio/pull/6095
[#6130]: https://github.com/tokio-rs/tokio/pull/6130
[#6262]: https://github.com/tokio-rs/tokio/pull/6262
[#6389]: https://github.com/tokio-rs/tokio/pull/6389
=> chore: prepare tokio-stream v0.1.15

tokio-test/CHANGELOG.md, tokio-test/Cargo.toml
- task: mark `Spawn` as `#[must_use]` ([#6371])
- test: increase MSRV to 1.63 ([#6126])
- test: update category slug ([#5953])
[#5953]: https://github.com/tokio-rs/tokio/pull/5953
[#6126]: https://github.com/tokio-rs/tokio/pull/6126
[#6371]: https://github.com/tokio-rs/tokio/pull/6371
=> chore: prepare tokio-test v0.4.4

tokio/src/io/split.rs
This PR replaces the spinlock behavior of `poll` functions of `io::ReadHalf` and `io::WriteHalf` with a blocking `Mutex`. Since `poll` functions are supposed to finish quickly, it's okay to use a blocking `Mutex`.
Resolves #6396.
=> io: use Mutex instead of spinlock

CONTRIBUTING.md, tokio/src/runtime/tests/loom_multi_thread_alt.rs
I found out that the guide for running loom tests doesn't work. This PR adds:
* `-C debug_assertions` to `RUSTFLAGS` since there is a `compile_error` that prevents the loom tests in the `runtime` module to run without debug assertions.
* `LOOM_MAX_BRANCHES=10000` to make it consistent with how CI is configured.
* `#![cfg(tokio_unstable)]` to `loom_multi_thread_alt.rs` to gate this test file appropriately.
=> readme: fix the guide for running loom tests

tokio/src/sync/mpsc/block.rs
This PR removes a seemingly stale comment. The comment talks about hypothetically coalescing ready flags, but flags are indeed coalesced into a single atomic.
=> sync: remove stale comment

tokio/src/runtime/builder.rs
This PR documents and enforces the fact that the `unhandled_panic` option is only implemented for the current thread runtime, since it has caused confusion before: #6222.
=> runtime: prevent using unhandled_panic option on multi-thread runtime

benches/sync_mpsc.rs, tokio/src/sync/tests/notify.rs, tokio/src/sync/tests/semaphore_batch.rs, tokio/src/util/markers.rs
Resolves breakage of CI after release of Rust 1.77.
=> chore: fix dead code warning

tokio/src/fs/file.rs, tokio/src/fs/file/tests.rs, tokio/src/fs/mocks.rs, tokio/src/io/blocking.rs, tokio/src/io/stdio_common.rs, tokio/tests/fs_file.rs
https://github.com/tokio-rs/tokio/pull/5397 enhanced performance by updating the `tokio::fs::File`'s MAX_BUF from 16KiB to 2MiB for operations involving `AsyncWrite` / `AsyncRead`. Related to this, it would also be useful to provide an API that allows to customize this default.
This introduce a `set_max_buf_size` to `tokio::fs::File` to customize the maximum buffer size.
If this is not set, the current default of 2MiB will be applied. In the current implementation, this `max_buf_size` will be applicable for both read and write operations.
=> fs: add `set_max_buf_size` to `tokio::fs::File`

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/tests/sync_mpsc_weak.rs
=> sync: expose strong and weak counts of mpsc sender handles

.github/workflows/ci.yml, CONTRIBUTING.md
This PR:
* add discription about benchmarks to contributing.md
* remove stale comments in CI settings.
=> readme: add discription about benchmarks

tokio-util/src/codec/length_delimited.rs, tokio-util/tests/length_delimited.rs
=> util: assert compatibility between `LengthDelimitedCodec` options

tokio/src/sync/mpsc/block.rs, tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/list.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/src/sync/tests/loom_mpsc.rs, tokio/tests/sync_mpsc.rs, tokio/tests/sync_mpsc_weak.rs
Fixes: #4638
Fixes: #6314
Taken from #4638
Adds a new `is_closed` function to both `mpsc::Receivers` that check if the channel is closed and has no remaining messages in the internal buffer.
Since there are two possible ways to close a channel and they lead to different internal states, it was necessary to add two checks, one for each internal state.
=> Add `is_closed`, `is_empty` and `len` to `mpsc::Receiver` and `mpsc::UnboundedReceiver`

tokio/src/sync/rwlock/owned_read_guard.rs, tokio/src/sync/rwlock/owned_write_guard.rs, tokio/src/sync/rwlock/owned_write_guard_mapped.rs
Adds a `rwlock()` method returning a reference to the original `Arc<RwLock>` to the `Owned*` guards.
`Mutex` guards and `Semaphore` permits already have similar methods.
A similar, `rwlock()`, method is added to the `Owned*` guards. The "normal" guards don't actually hold a reference to the original `RwLock` and I don't think that it can be added to them without changing these types' definitions.
=> sync: add  a `rwlock()` method to owned `RwLock` guards

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs, tokio-util/src/lib.rs
Since types in different sub-modules in `tokio-util` implement `Sink`, I decided to put the doc in the top level module.
Resolves #5310.
=> util: add documentation about cancel safety of `SinkExt::send`

tokio-stream/Cargo.toml, tokio-stream/src/lib.rs, tokio-stream/src/poll_fn.rs, tokio-stream/src/stream_map.rs, tokio-stream/tests/stream_stream_map.rs
=> stream: add `next_many` and `poll_next_many` to `StreamMap`

tokio/src/io/util/async_buf_read_ext.rs
=> io: document cancel safety of `AsyncBufReadExt::fill_buf`

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- fs: add `set_max_buf_size` to `tokio::fs::File` ([#6411])
- io: add `try_new` and `try_with_interest` to `AsyncFd` ([#6345])
- sync: add `forget_permits` method to semaphore ([#6331])
- sync: add `is_closed`, `is_empty`, and `len` to mpsc receivers ([#6348])
- sync: add a `rwlock()` method to owned `RwLock` guards ([#6418])
- sync: expose strong and weak counts of mpsc sender handles ([#6405])
- sync: implement `Clone` for `watch::Sender` ([#6388])
- task: add `TaskLocalFuture::take_value` ([#6340])
- task: implement `FromIterator` for `JoinSet` ([#6300])
- io: make `io::split` use a mutex instead of a spinlock ([#6403])
- docs: fix docsrs build without net feature ([#6360])
- macros: allow select with only else branch ([#6339])
- runtime: fix leaking registration entries when os …
=> chore: prepare Tokio v1.37.0

.github/workflows/ci.yml, CONTRIBUTING.md, tokio-util/tests/compat.rs, tokio/src/runtime/signal/mod.rs, tokio/tests/io_async_fd.rs, tokio/tests/rt_common.rs, tokio/tests/task_local_set.rs
This updates the CI to use clippy version 1.77 which is aligned with the rust stable version.
**Ignored Lints**
The following functions accept the `clippy:unused_io_amount` by the virtue that they handle left over IO in that they are purposefully discarding all IO.
* tokio/src/runtime/signal/mod.rs - process
* tokio/tests/io_async_fd.rs - drain
=> chore: update CI to clippy 1.77

tokio-util/src/util/poll_buf.rs
This PR should fix the issue #6429
I added `?Sized` to the trait bounds of the `io` parameter of `tokio_util::io::poll_read_buf` to allow dynamically sized parameters like `&mut (dyn tokio::io::AsyncRead + Unpin)` as well.
Closes #6429
=> Allow dynamically sized types in tokio_util::io::poll_read_buf

tokio-util/Cargo.toml, tokio-util/src/codec/framed_impl.rs, tokio-util/src/lib.rs, tokio-util/src/tracing.rs
I maintain a library that implements the websocket protocol using tokio-util's `FramedRead` for decoding frames. I conduct testing using `cargo-minvers` in CI to ensure that my minimum dependency versions are correct and working as they are intended to.
proc-macro2 is a crate that very, very often breaks with newer rustc versions (most recently, a rustc update broke versions prior to 1.0.60, see [this issue](https://github.com/dtolnay/proc-macro2/issues/398)). tracing-attributes depends on proc-macro2  and regularly has to bump the minimum version to fix their own `cargo-minvers` checks (see [this commit bumping the dependency](https://github.com/tokio-rs/tracing/commit/29f74c52c2535785da52d5b24c90f29be15c3481)).
My issue lies exactly here. tokio-util's codec module depends on tracing, …
=> util: Make tracing optional when codec is enabled

tokio/src/io/join.rs
The Join struct implements the AsyncRead and AsyncWrite interface. This PR implements the AsyncReadBuf interface.
Fixes https://github.com/tokio-rs/tokio/issues/6446
We implement the AsyncReadBuf interface for the Join, if the Reader also implements the AsyncReadBuf interface.
=> io: implement AsyncBufRead for Join

tokio/src/runtime/builder.rs, tokio/src/runtime/scheduler/multi_thread/stats.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/stats.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/tests/rt_panic.rs, tokio/tests/rt_threaded.rs, tokio/tests/rt_threaded_alt.rs
Resolve #5713. Currently specifying 0 or 1 for `global_queue_interval` causes a panic.
This PR:
* Added documentation indicating that setting global_queue_interval to 0 is not allowed and included an assert in the builder.
* Removed the `debug_assert!(next > 1)` that could be triggered when global_queue_interval is set to 1.
* Although it's still unclear whether there is a practical benefit to always prioritize checking the global queue first, but i guess it's probably better than causing a panic in debug builds.
=> runtime: make improvements to `global_queue_interval`

tokio-util/tests/udp.rs, tokio/src/net/unix/ucred.rs
Add the support of Apple VisionOS  [121419](https://github.com/rust-lang/rust/pull/121419)
Add target_os = "visionos"
=> Add Apple visionOS support

tokio/tests/rt_metrics.rs
This test is flaky, so mark it with `#[ignore]` to reduce flakiness of ci.
See #6470 for the issue about fixing the flakiness of the test.
=> Ignore flaky `worker_steal_count` test

tokio/src/task/task_local.rs
From [the docs](https://docs.rs/tokio/1.36.0/tokio/task/struct.LocalKey.html) it is clear one can `LocalKey::get()` a copy of `T`.
I hard a hard time finding how to get a clone of `T` (my `T` is not `Copy`, it's a struct of `Arc`s).
This PR adds a `clone` method alongside the existing `get` method.
=> feat: impl Clone for task_local where T: Clone

CONTRIBUTING.md
As discussed in https://github.com/tokio-rs/tokio/discussions/6469.
- Delete the version of the command that doesn't have `--cfg tokio_unstable`, as proposed by @Darksonn in the link above.
- Add `--open`, as this is most often what one would want. I am interested in feedback whether surrounding this flag in square brackets is self-explanatory enough to indicate that this flag is optional, or if we should just show it without the brackets, or entirely remove `--open`, or mention it in prose only.
- Mention `cargo +nightly docs-rs` with a brief explanation. It is more memorable than the RUSTDOCFLAGS way, and applicable to repos outside of Tokio too.
=> Update CONTRIBUTING.md with recommended commands for building docs

tokio/src/sync/semaphore.rs
Using u32 in the semaphore methods was a design mistake, see #4446. We should not add more methods using u32.
This is not a breaking change since we have not made a release since #6472.
=> sync: use usize instead of u32 for `SemaphorePermit::split`

tokio/src/sync/semaphore.rs
Add code examples for some `SemaphorePermit`'s method to make the method's behavior more clear.
[render view](https://6617c989f1ca34837856b198--cute-flan-7bc085.netlify.app/tokio/sync/struct.semaphorepermit)
=> sync: add examples for `SemaphorePermit`, `OwnedSemaphorePermit`

CONTRIBUTING.md
https://github.com/tokio-rs/tokio/pull/6475\#discussion_r1561492918
=> docs: add --locked to cargo install commands

tokio/src/sync/barrier.rs
=> Document that barriers are not cancel safe

tokio/src/runtime/runtime.rs
reused the comment on Handle::metrics() to help communicate that
they are the same thing.
Resolves: https://github.com/tokio-rs/tokio/issues/6486
I tried to make a doctest but struggled to get Cargo to actually run it.
The --cfg tokio_unstable was able to get the compiler to notice syntax
errors in the cfg_metrics!{} block, but it did not run the doctest.
Rather than commit a non-running doctest, I simply followed suit with
the existing comment on runtime::Handle::metrics.
=> docs: Runtime::metrics() documentation

tokio/src/io/split.rs
`SplitStreamId`s were added in 5bf78d77ada685826b33fd62e69df179f3de8a1c and removed the next day in c7719a2d2962f83854193b4c9131ee275a5a4475, and never made it into a release. Therefore, the documentation for `unsplit()` mentioning “comparing the stream ID” is incorrect (and has been since its introduction in tokio 0.2.10).
Describe the actual method for checking the precondition of `ReadHalf::unsplit()`: calling `ReadHalf::is_pair_of()`.
=> Fix obsolete reference to “stream ID” in `ReadHalf::unsplit()` documentation.

tokio/src/sync/batch_semaphore.rs
This commit adds the instrument code for tasktrace to `Semaphore`'s leaf future.
=> sync: add instrument code to `Semaphore` leaf future

tokio/src/time/mod.rs
Fixes : #6495 
feature list in rust nightly requires `#[cfg_attr(docsrs, doc(cfg(feature = "<feature-name>")))]` whose absence will result into feature requirement not being detected in doc.
=> docs: fix time::{pause,resume} requirement

tokio/src/io/mod.rs, tokio/src/io/util/copy.rs, tokio/src/io/util/copy_bidirectional.rs, tokio/src/io/util/mod.rs
`copy_bidirectional` uses 8Kb buffers under the hood, which isn't configurable. 
New method  `copy_bidirectional_with_sizes` were added which but accepts the `a` -> `b` and `b` -> `a` buffers sizes. This way, a user can pass the desire buffers sizes.
I extracted common `copy_bidirectional` logic into `copy_bidirectional_impl` which `copy_bidirectional` and `copy_bidirectional_with_sizes` uses. 
Fixes: https://github.com/tokio-rs/tokio/issues/6454.
Refs: https://github.com/tokio-rs/tokio/pull/3572.
=> io: add `copy_bidirectional_with_sizes`

tokio-macros/src/entry.rs, tokio-macros/src/lib.rs, tokio/src/lib.rs
The main and main-rt macro functions both have the #[cfg(not(test))] with a comment indicating that its inclusion is a workaround for rust-lang/rust#62127, which has since been resolved. Because rust-analyzer enables test by default, this means that these functions are greyed out when using rust-analyzer in VSCode without configuration changes.
Remove all uses of #[cfg(not(test))] in the tokio-macros crate that are accompanied by comments mentioning rust-lang/rust#62127 as the motivation for usage.
It's possible that the usage in https://github.com/tokio-rs/tokio/blob/8093712604e54a434658e693ca80535d906e26a7/tokio/src/lib.rs#L677 is also unnecessary, since it appears in the context of using main as an identifier. I'm less sure about that one since it doesn't have a comment mentioning …
=> Remove unnecessary uses of #[cfg(not(test))]

.github/workflows/ci.yml, tests-integration/Cargo.toml, tests-integration/tests/macros_main.rs, tests-integration/tests/macros_select.rs, tokio-util/src/task/mod.rs, tokio/src/macros/cfg.rs, tokio/src/runtime/blocking/schedule.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/runtime.rs, tokio/src/runtime/scheduler/inject/shared.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/task/trace/mod.rs, tokio/src/task/mod.rs
Enable `rt-multi-thread` for `wasm32-wasi-preview1-threads` target
=> tokio: enable rt-multi-thread for wasm32-wasi-preview1-threads target

tokio/src/runtime/task/harness.rs
The code that we're removing calls UnsafeCell::with_mut with the argument `std::mem::drop`. This is misleading because the use of `drop` has no effect. `with_mut` takes an argument of type `impl FnOnce(*mut T) -> R`. The argument to the argument function is a pointer. Dropping a pointer has no effect.
The comment above the first instance of this pattern claims that this releases some resource. This is false because the call has no effect. The intention might have been to drop the value behind the pointer. If this did happen, it would be a bug because the resource (`waker`) would be dropped again at the end of the function when the containing object is dropped.
I looked through the history of this code. This code originally called `with_mut` with the argument `|_| ()`. Calling `with_mut` …
=> runtime: remove misleading use of UnsafeCell::with_mut

tokio/src/time/interval.rs, tokio/tests/time_interval.rs
when calling [tokio::time::interval(Duration::MAX)](https://docs.rs/tokio/latest/tokio/time/fn.interval.html) runtime panics with:
```
overflow when adding duration to instant
```
see reproduction [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cf23e831d76f4bd503f1a177b16a9a4a). Panic happens when adding `timeout` to to the `delay` deadline.
This PR addresses the panic by calling [`Instant::checked_add`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.checked_add) falling back to `Instant::far_future()` when it overflows. If needed I can add a test for it and update the documentation mentioning this behaviour.
Thanks!
=> time: do not panic on Interval::poll_tick if the sum of the timeout and period overflow

tokio/src/util/wake_list.rs
https://github.com/tokio-rs/tokio/pull/6517#issuecomment-2081299381 noted that the current implementation of `WakeList::wake_all` is LIFO, while the original pre-`WakeList` implementations were FIFO. The [very first implementation](https://github.com/glebpom/tokio/blob/c0aad94758ae3c9bc71084857d0744cfcff47112/tokio/src/util/wake_list.rs) of `WakeList` was FIFO, but [it also was also unsound](https://github.com/tokio-rs/tokio/pull/4055#pullrequestreview-735985023) in the case the `Waker` panicked, so it was changed to work as it is currently implemented.
This changes `WakeList` to be FIFO by processing `Waker`s in order and using a `DropGuard` to handle panics.
=> util: make `WakeList::wake_all` use FIFO ordering

.github/workflows/ci.yml, tokio/src/process/unix/orphan.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/util/markers.rs
This PR:
* fixes warnings introduced in 1.78.0.
* you can see how it fails, for example, [here](https://github.com/tokio-rs/tokio/actions/runs/8925711536/job/24515130336).
* changes the target name from `wasm32-wasi`, `wasm32-wasi-preview1-threads` to `wasm32-wasip1`, `wasm32-wasip1-threads` in ci. (See also https://github.com/tokio-rs/tokio/issues/6484)
=> chore: fix latest rust-1.78.0 warnings

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs
`mpsc::Sender` has `max_capacity` and `capacity` methods, however `mpsc::Receiver` does not. It may help to have these methods when trying to pre-allocate for `Receiver::recv_many`.
Adds `Receiver::max_capacity` and `Receiver::capacity`.
=> tokio: add `mpsc::Receiver::max_capacity` and `mpsc::Receiver::capacity`

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
This release updates the MSRV to 1.63. ([#6126])
- either: implement `Sink` for `Either` ([#6239])
- time: add `DelayQueue::deadline` ([#6163])
- time: add `FutureExt::timeout` ([#6276])
- codec: assert compatibility between `LengthDelimitedCodec` options ([#6414])
- codec: make tracing feature optional for codecs ([#6434])
- io: add `T: ?Sized` to `tokio_util::io::poll_read_buf` ([#6441])
- sync: remove `'static` bound on `impl Sink for PollSender` ([#6397])
- codec: add examples for `FramedRead` and `FramedWrite` ([#6310])
- codec: document cancel safety of `SinkExt::send` and `StreamExt::next` ([#6417])
[#6126]: https://github.com/tokio-rs/tokio/pull/6126
[#6163]: https://github.com/tokio-rs/tokio/pull/6163
[#6239]: https://github.com/tokio-rs/tokio/pull/6239
[#6276]: …
=> chore: prepare tokio-util v0.7.11

tokio/src/runtime/tests/loom_current_thread/yield_now.rs, tokio/src/runtime/tests/loom_multi_thread/yield_now.rs, tokio/src/runtime/tests/loom_multi_thread_alt/yield_now.rs
This ignores the test that is broken as per #6536.
The current-thread runtime is not susceptible to the problem explained in the bug.
=> Ignore `yield_calls_park_before_scheduling_again` test

tokio/tests/task_builder.rs
Wrapping tests in `mod tests` only makes sense for tests inside `src/`.
=> tests: remove tests module from integration tests

tokio-util/Cargo.toml
Don't enable default features for hashbrown. This means that we no longer use ahash.
Suggested in [#6538 (comment)](https://www.github.com/tokio-rs/tokio/pull/6538#discussion_r1590334134).
=> util: no default features for hashbrown

.cirrus.yml, .github/workflows/ci.yml, target-specs/README.md, target-specs/i686-unknown-linux-gnu.json, tokio-macros/src/lib.rs, tokio-stream/src/lib.rs, tokio-test/src/lib.rs, tokio-util/Cargo.toml, tokio-util/src/codec/length_delimited.rs, tokio-util/src/lib.rs, tokio-util/tests/task_join_map.rs, tokio/src/lib.rs, tokio/src/signal/mod.rs, tokio/src/signal/unix.rs, tokio/tests/_require_full.rs, tokio/tests/dump.rs, tokio/tests/fs_open_options.rs, tokio/tests/macros_select.rs, tokio/tests/rt_basic.rs, tokio/tests/rt_common.rs, tokio/tests/rt_handle.rs, tokio/tests/rt_metrics.rs, tokio/tests/rt_threaded.rs, tokio/tests/rt_threaded_alt.rs, tokio/tests/task_abort.rs, tokio/tests/task_builder.rs, tokio/tests/task_id.rs, tokio/tests/task_join_set.rs, tokio/tests/task_local_set.rs, tokio/tests/task_yield_now.rs
Silence warnings from https://github.com/rust-lang/cargo/pull/13571.
I tried to add a CI step that runs with the lint enabled as well. But it can't be enabled normally because `cargo build` needs to just work for new contributors, and build scripts hurt performance too much.
=> Bump nightly to nightly-2024-05-05

tests-build/tests/fail/macros_invalid_input.rs, tests-build/tests/fail/macros_invalid_input.stderr, tokio-macros/Cargo.toml, tokio-macros/src/entry.rs
Improve compatibility among multiple test proc macros.
1. Add `#[::core::prelude::v1::test]` to the end of test proc macros. This way, proc macros process later can choose to not generate `#[::core::prelude::v1::test]` to avoid duplicated test runs.
2. Forbid `#[::core::prelude::v1::test]` to avoid duplicated test runs as `tokio::test` is transforming an invalid test signature to one accepted by `#[test]`. This is consistent with what we currently treat `#[test]`.
1. frondeus/test-case#143
2. https://github.com/rust-lang/reference/issues/692
3. https://github.com/rust-lang/rust/issues/67839
=> macros: append generated test attribute so others are aware of it

tokio/src/runtime/time/entry.rs
Since the `true_when` field in the `TimerShared` struct actually has no effect,  we should remove the `true_when` field.
It will be a win in memory type size, which reduces the size of `TimerShared` from 72 bytes to 64 bytes. It should be beneficial for memory cache.
=> time: remove the true_when field in TimerShared.

tokio/Cargo.toml, tokio/src/sync/oneshot.rs, tokio/src/sync/tests/loom_oneshot.rs
Related: https://github.com/risingwavelabs/risingwave/issues/6617.
When we use `oneshot::Sender`, it is intuitive to assume that when `tx.send(msg)` returns with `Ok(())`, the `msg` will have been added to the buffer and either will be consumed by the `rx.await`, or dropped along with dropping `rx`, but in either way, `msg` should not be dropped on the `tx` side.
However, in the current implementation, the assumption does not hold. It might happen that, even though `tx.send(msg)` returns with `Ok(())`, the `msg` is still dropped on the sender side.
The current struct of `Sender` is 
```
struct Sender<T> {
inner: Option<Arc<Inner<T>>>,
}
```
In the current implementation, in `tx.send(msg)`, `msg` will be added to `inner`. Before `msg` gets consumed by `rx`, the struct `Inner` holds the …
=> feat(oneshot channel): ensure msg won't be dropped on sender side when send returns ok

tokio/src/util/linked_list.rs
Minor nit, since we no longer should need to use pointer arithmetics since the stabilization of `ptr::addr_of_mut!`.
The SAFETY documentation is a bit odd, since it previously didn't motivate why accessing the field through `UnsafeCell` was OK. However, ~~I'm not sure `UnsafeCell<T>` is even necessary any longer with `addr_of*` since we avoid intermediate references directly over `self`~~. Nevermind! Just needed a refresher.
=> util: Use ptr::addr_of over pointer arithmetics in linked_list

tokio/src/lib.rs
Docs don't build on macOS because of the `compile_error!` warning intended to prevent customers from using task dumps on unsupported platforms.
Add `not(doc)` so that rustdoc doesn't hit the compile failure
=> docs: gate taskdump compiler_error behind not(doc)

benches/time_timeout.rs, tokio-stream/src/wrappers/interval.rs, tokio-util/src/codec/any_delimiter_codec.rs, tokio-util/src/codec/lines_codec.rs, tokio-util/src/time/wheel/mod.rs, tokio/src/runtime/scheduler/multi_thread/stats.rs, tokio/src/runtime/task/state.rs, tokio/src/sync/batch_semaphore.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/rwlock.rs, tokio/tests/sync_broadcast.rs
I improved the code with clippy 1.80 (nightly  2024-05-16). The code compiles, doesn't cause any warnings with clippy 1.77 and 1.80, and all tests succeed. I know you don't like it when people use a newer version of clippy, let alone the current nightly version, but I wanted to contribute and I don't know enough to contribute more.
I'm trying to improve the code of libraries I use and I use Tokio a lot.
Replaced cmp::max(2, cmp::min(...)) with clamp, removed usize imports, replaced std::usize:: and std::u32:: with usize:: and u32:: respectively, moved parentheses to put the future into the blackbox instead of the unit value.
=> Improved the code with clippy 1.80

tokio/src/fs/file.rs
This PR adds support for the recently stabilized `create_new` function to `File` by configuring `OpenOptions` with appropriate flags. The implementation should forward the call to std once MSRV catches up to `1.77`.
Resolves #6557.
=> fs: add `create_new` function to `File`

tokio/src/task/join_set.rs
close https://github.com/tokio-rs/tokio/issues/6565
1. Added the spawn_blocking API to the builder.
2. Added the spawn_blocking_on API to the builder.
=> feat: add spawn_blocking and spawn_blocking_on to the JoinSet builder

tokio/src/runtime/builder.rs, tokio/src/runtime/context.rs, tokio/src/runtime/driver.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/src/runtime/time/entry.rs, tokio/src/runtime/time/mod.rs, tokio/src/runtime/time/tests/mod.rs, tokio/src/util/mod.rs, tokio/src/util/rand.rs
As part of addressing https://github.com/tokio-rs/tokio/issues/6504, this PR attempts to implement a shard approach to improve `timeout` and `sleep` performance in specific scenarios.
When high concurrency, a large number of `timeout`s or `sleep`s are registered to Timer, the global lock contention is very severe. By sharding the lock, this performance issue can be significantly reduced.
- Thread local storage random number generation is used to achieve sharding.
- Because the wheel data structure is a multi-layered linked list, the current shard size is consistent with the number of workers. I hope that the creation of a runtime will not require more time, and the serial lock acquisition in the park method will not take too much time.
=> Using sharded locks instead of a global lock for Timers

tokio/src/process/mod.rs
The code for `output` indicates that only sets `stdout` and `stderr` (as one would expect, IMO), yet the docs for `stdin` indicated that it too would be set. This seems like it was just a simple copy/paste typo, so correct `stdin` to note that it just defaults to `inherit`.
Fixes #6577.
See #6577; the docs for `stdin` seem to disagree with the code for `output`.
Adjust the documentation to match the code.
=> docs: `stdin` is always `inherit` by default

Cargo.toml, tokio/Cargo.toml, tokio/tests/io_async_fd.rs, tokio/tests/io_poll_aio.rs, tokio/tests/net_unix_pipe.rs
Use the latest version of Nix as requested by @fkm3 .
Update Nix to the latest version.  This version uses I/O Safety for most functions.  It also necessitates updating the mio-aio dev dependency.
This PR supersedes #6474 , but it depends on unreleased nix and mio-aio crates.
=> Update nix and mio-aio dev-dependencies to the latest

tokio/src/net/windows/named_pipe.rs
I would like to use windows named pipes as the transport for GRPC with tonic. That requires that the transport implement [Connected](https://docs.rs/tonic/latest/tonic/transport/server/trait.Connected.html), which requires the info struct implement Clone. While a wrapper struct could be used, NamedPipeInfo doesn't seem to have any particular reason not to implement Clone directly.
Add Clone (And a few other useful traits already derived on the members of NamedPipeInfo) to the derive macro.
=> Derive common traits for NamedPipeInfo struct

tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle/metrics.rs, tokio/tests/rt_metrics.rs
Fixes #6550
For the multithreaded scheduler handles, subtract the number of worker threads from the blocking threads count.
=> tokio(metrics): fix blocking_threads count

LICENSE, tokio-macros/LICENSE, tokio-stream/LICENSE, tokio-test/LICENSE, tokio-util/LICENSE, tokio/LICENSE
This removes the copyright year in all the LICENSE files.
It also uses the MIT license text with the wrapping from
https://choosealicense.com/licenses/mit/ rather than the more narrow
wrapped text that was previously used, and adds the explicit "MIT
License" header to each file to make this more obvious.
When I opened the license file, I was unsure if this was MIT licensed or another custom license due to the lack of header and non-standard formatting.
Use a more standard formatted license, and ensure the header states this is an MIT License.
=> docs: Update license year to 2024

tokio/src/net/windows/named_pipe.rs
The previous NamedPipeServer doc example seemed to imply that the return type of `NamedPipeServer::connect()` was a `Future<Result<some_kind_of_client>>>`, however, `connect()` returns a `Future<Result<()>>>`. The following line of code reopening the pipe would shadow the newly connected pipe immediately, making the following spawned task pointless.
Instead, now it binds the original named pipe to a new variable after a client connects, allowing for the subsequent task to be able use the connection.
=> Fix misleading NamedPipeServer example

tokio/src/sync/notify.rs, tokio/src/util/linked_list.rs, tokio/tests/sync_notify.rs
A new notify_one_last_in method is implemented for notifying the most recent waiter, LIFO, instead of the oldest one, FIFO, which is used by the current notify_one method.
As explained here https://github.com/tokio-rs/tokio/issues/6506 the `notify_one_last_in` method provides the user a method for waking up the most recent waiter rather than the oldest one. When using a LIFO strategy we sacrifice waiters that have been waiting longer by first dequeuing the ones that have been in the queue for shorter time, this should provide benefits in situations of contention where LIFO dequeueing should provide a better latency observation compared to the usage of the FIFO.
Ive followed main recommendations for storing the strategy for dequeueing followed by the user as  part of the waiter …
=> Implementation of notify_one_last method

tokio/src/macros/cfg.rs, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/coop.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/io/metrics.rs, tokio/src/runtime/metrics/histogram.rs, tokio/src/runtime/metrics/io.rs, tokio/src/runtime/metrics/mod.rs, tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/metrics/worker.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/runtime.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/inject.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread/queue.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle.rs, tokio/src/runtime/scheduler/multi_thread_alt/queue.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/src/runtime/tests/queue.rs
This PR stabilizes a single metric API to start the process of stabilizing metrics. Future work will continue to stabilize more metrics.
We decided against adding a `metrics` feature and instead metrics will always be available.
I audited the generated docs and the feature gating from docs.rs appears to be correct.
After a bit of fiddling, I ended up restructuring the metrics macros:
- Rename `cfg_metrics` => `cfg_unstable_metrics`: This behaves like `cfg_metrics` behaved previously and is gated on `tokio_unstable`
- `cfg_not_unstable_metrics`: Since metrics needs to swap out with a mock module, I needed a final flag to ensure that I was able to do one or the other.
=> metrics: stabilize `RuntimeMetrics::worker_count`

tokio/src/task/local.rs
Fix a typo I found while reading the doc.
=> docs: fix a typo in doc of LocalSet::run_until

tokio/src/runtime/scheduler/multi_thread/worker.rs
If we heavily call the `spawn_blocking`, there might be no available thread to run the current core. Except the task in the lifo_slot, all tasks in cores can be stolen, so we move the task from the lifo_slot to the run_queue before calling the `spawn_blocking` in the `block_in_place`.
This can prevent the starvation of the task in `lifo_slot` in edge cases.
=> runtime: move the task out of the lifo_slot in block_in_place

tokio/src/sync/mpsc/block.rs, tokio/tests/sync_mpsc.rs
=> sync: fix incorrect is_empty on mpsc block boundaries

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio/Cargo.toml
- macros: make `#[tokio::test]` append `#[test]` at the end of the attribute list ([#6497])
[#6497]: https://github.com/tokio-rs/tokio/pull/6497
=> Prepare tokio-macros v2.3.0

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release marks the beginning of stabilization for runtime metrics. It
stabilizes `RuntimeMetrics::worker_count`. Future releases will continue to
stabilize more metrics.
- fs: add `File::create_new` ([#6573])
- io: add `copy_bidirectional_with_sizes` ([#6500])
- io: implement `AsyncBufRead` for `Join` ([#6449])
- net: add Apple visionOS support ([#6465])
- net: implement `Clone` for `NamedPipeInfo` ([#6586])
- net: support QNX OS ([#6421])
- sync: add `Notify::notify_last` ([#6520])
- sync: add `mpsc::Receiver::{capacity,max_capacity}` ([#6511])
- sync: add `split` method to the semaphore permit ([#6472], [#6478])
- task: add `tokio::task::join_set::Builder::spawn_blocking` ([#6578])
- wasm: support rt-multi-thread with wasm32-wasi-preview1-threads ([#6510])
- macros: make …
=> chore: prepare Tokio v1.38.0

tokio/src/runtime/time/source.rs, tokio/src/runtime/time/tests/mod.rs
The https://github.com/tokio-rs/tokio/pull/5710 tried to fix the panic issue when the instance is very big.
However, the `instant_to_tick` can still calculate a `u64` which is bigger than `MAX_SAFE_MILLIS_DURATION`.
Even if a `u128` successfully try_into a `u64`, we still check whether it is bigger than `MAX_SAFE_MILLIS_DURATION`. If it is greater, we will return `MAX_SAFE_MILLIS_DURATION`.
=> time: fix big time panic issue

tokio-util/src/util/poll_buf.rs, tokio/src/process/mod.rs
Citing from #6523:
> Sometimes I want to access a mutable reference of std::process::Command out of the tokio counterpart, so I can access some unstable functions in std to update Command, but tokio only provides an as_std method returning a shared reference.
I added a method `as_std_mut(&mut self) -> &mut std::process::Command` to `tokio::process::Command` to get mutable access to the inner std command structure.
This closes #6523
=> Added method as_std_mut to tokio::process::Command

.cirrus.yml
Use the newly released FreeBSD 14.1.
FreeBSD 14.0 will soon be EoL.
Use 14.1 in CI.
=> Update FreeBSD CI environment

tokio-test/src/task.rs, tokio-test/tests/task.rs
I have a need to use `Spawn` in conjunction with a `Stream` impl that has a custom `size_hint`, and need to assert on this size hint.
Currently the size hint of the wrapped stream can be accessed via `Deref`, but not by accessing the `Stream` impl on `Spawn` itself (it instead returns the default value of `(0, None)`), which is confusing.
To reduce confusion this pull request adds a `size_hint` override in the `Stream` impl for `Spawn`. This override forwards the `size_hint` invocation to the wrapped stream, allowing its size hint to be accessed directly instead of having it replaced with the default value. A test was added to validate the behavior.
=> test: make `Spawn` forward `size_hint`

tokio/src/io/util/copy.rs
Although this PR was originally related to https://github.com/tokio-rs/tokio/issues/6519#issue-2267067024, it aims now to improve a bit the chances of large write in `io::copy` and `io::copy_bidirectional`.
`tokio::io::copy_bidirectional` and `tokio::io::copy` can, in some circumstances, lead to some non-optimal chances of large write when both writing and reading are pending ([see here](https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/util/copy.rs#L64-L68)). For more information, refer to the issue linked above.
This PR aims to improve this behavior by reading more often.
- Try to read when the buffer is not full
- Reset partially the buffer state as soon as data is fully written
```shell
copy_mem_to_mem         time:   [131.88 µs 133.09 µs 134.48 µs]
change: [-4.3908% -2.6619% …
```
=> io: optimizing the chances of large write in copy_bidirectional and copy

tokio/src/doc/mod.rs, tokio/src/lib.rs
If you enable `--cfg docsrs` with the `fs` feature but without the `net` feature, [tokio docs doesn't docbuild](https://github.com/rune-rs/rune/actions/runs/9225256293/job/25382370737?pr=709).
The `docs::os` module need to be defined if the `fs` feature is enabled since [it's used here](https://github.com/tokio-rs/tokio/blob/cba86cf1b1edea8cd131f168a99953e6e35739d2/tokio/src/fs/file.rs#L913).
I genuinely have no idea if this interferes with #6166 or any of those related issues. Some tests would be nice, but I'm not sure if we want to set them up. Testing feature combinations for the sole benefit of dependent `docsrs` builds seems awkward. We might just prefer having these always being exported with `#[allow(unused)]` to avoid future regressions.
=> docs: fix docsrs builds with the fs feature enabled

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/metrics/worker.rs, tokio/src/util/metric_atomics.rs
https://github.com/tokio-rs/tokio/pull/6556#discussion_r1617778330
Metrics should not use Loom atomics. This clarifies this in code and also gives the opportunity to make a cleaner interface for metrics. We could potentially use this interface in the future to track things like the maximum value etc.
Introduce `MetricAtomicUsize` as the equivalent of `MetricAtomicU64`
=> metrics: create MetricAtomicUsize for usized-metrics

tokio/src/runtime/task/abort.rs, tokio/src/runtime/tests/task.rs
This is a small change so that AbortHandle implements Clone.
The [the module level docs](https://docs.rs/tokio/latest/tokio/task/index.html#cancellation) indicate
> Each task can only have one [JoinHandle](https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html), but it can have more than one [AbortHandle](https://docs.rs/tokio/latest/tokio/task/struct.AbortHandle.html).
Cloning is convenient for `AbortHandle`s given there can be more than one.
The proposed solution is similar to JoinHandle's [`abort_handle`](https://github.com/tokio-rs/tokio/blob/8e15c234c60cf8132c490ccf03dd31738cfeaca8/tokio/src/runtime/task/join.rs#L299) method:
```
impl Clone for AbortHandle {
/// Returns a cloned `AbortHandle` that can be used to remotely abort this task.
fn clone(&self) -> Self { …
```
=> Implement Clone for AbortHandle

tests-build/tests/fail/macros_invalid_input.rs, tests-build/tests/fail/macros_invalid_input.stderr, tokio-macros/src/entry.rs, tokio-macros/src/lib.rs, tokio/tests/macros_test.rs
Allow users to set `unhandled_panic` behavior in those macros directly.
Close #6527.
This PR parses `unhandled_panic` in `tokio-macros`.
=> macros: allow setting `unhandled_panic` behavior in tokio::{main, test}

tokio/src/task/consume_budget.rs, tokio/src/task/mod.rs
This utility seems simple and complete. Stabilizing it avoids the need for workarounds to consuming/reading Tokio's task budgets such as abusing `io::Empty`.
Stabilize `task::consume_budget()`.
=> task: stabilize `consume_budget`

tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle/metrics.rs, tokio/src/runtime/task/list.rs, tokio/src/util/sharded_list.rs, tokio/tests/rt_metrics.rs
https://github.com/tokio-rs/tokio/issues/4073#issuecomment-1643611711
> Metrics like active_tasks_count or injection_queue_depth are fast-moving gauges and even taking a snapshot every few seconds doesn't say much about what's going inside Tokio. It would be better to use two counters: one for additions, one for removals
We're hoping to add a [prometheus exporter for the tokio metrics](https://github.com/neondatabase/neon/pull/5647) information, but a sample rate of 15 seconds will likely miss a lot of task spikes. I could implement some level of eager aggregation, but as the linked comment says, you can still miss some with a sample rate of 500ms. 
In `CountedLinkedList`, replace the `count: usize` with a pair of `u64`s that can only be incremented. One `u64` for added items and one for …
=> feat: add task counter pairs

tokio/src/sync/watch.rs
=> sync: implement Default for watch::Sender

tokio/src/io/read_buf.rs
My first open source PR in a while, let me know what else is needed.
Feature request for #6580.
Implemented as described.
=> Include relevant values in ReadBuf.put_slice() panic message #6580

tokio/src/util/linked_list.rs
To modify the restrictions on the generic L in LinkedList when call `into_guarded`.
I believe that it can help to be less restrictive on the type of `Handle` when turning a linked list into a guarded linked list.
=> rt: modify the type bound of LinkedList when call into_guarded

tokio/src/runtime/time/entry.rs, tokio/src/runtime/time/mod.rs, tokio/src/runtime/time/wheel/level.rs, tokio/src/runtime/time/wheel/mod.rs, tokio/src/util/linked_list.rs
Currently we use a pending linked list to temporarily store the timer entry to be fired. 
If there are a large number of timers that need to be waken at once, then there will be a cache miss issue here.
For synchronizing the state between threads, when we want to modify the state of entries in wheel, we must hold the lock of wheel. However, when we hold a lock, in order to avoid the deadlock issue, we are not allowed wake the walker of entries.
Furthermore, to avoid the issue of the infinite loop, we need to take all of the entries off the slot before processing any of them. And, throughout this process, we always hold the lock.
The main reasons for using a `pending` linked list currently mentioned above.
In addition to supporting random deletion, `slot` linked list only have FIFO …
=> time: avoid traversing entries in the time wheel twice

tokio/src/sync/watch.rs
Align the API with `sync::broadcast::Sender` by adding the missing `fn same_channel()` method.
Now that the `Sender` implements `Clone` this is useful.
Duplicate the `Receivers`s implementation.
=> Add sync::watch::Sender::same_channel()

tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle/metrics.rs, tokio/src/runtime/task/list.rs, tokio/src/util/metric_atomics.rs, tokio/src/util/sharded_list.rs
Follow-up PR to #6114 that uses #6598.
=> metrics: use `MetricAtomic*` for task counters

tokio-util/src/io/stream_reader.rs
This impl had a bound on `StreamReader<S, E>`; this is incorrect because the second generic parameter to `StreamReader` is not an error type; it's a buffer type.
This "passthrough" `Sink` impl is currently unusable because it requires the `Sink` error type be the same as the `StreamReader` buffer type. This seems like it must have been a typo, because that constraint is not useful.
See the example program in #6642 for more details.
Resolve this by removing the constraint on `StreamReader`'s buffer type `B`. It's irrelevant to a `Sink` impl anyway.
Fixes #6642.
=> io: fix trait bounds on `impl Sink for StreamReader`

tokio-util/src/codec/length_delimited.rs
According to [comment](https://github.com/tokio-rs/tokio/issues/6604#issuecomment-2150408931) in #6604, some examples for `length_delimited` do not fit the real behavior. This PR fix the document and add tests to the examples.
Close #6604
Fix the docs.
Swap the order of example 1 and 2 to make it more easier to understand.
=> codec: docs: fix length_delimited doc description and make examples testable

tokio/src/runtime/builder.rs
Fix the grammar in this paragraph, assuming this was supposed to refer to the "panic's error value".
=> runtime: fix typo in unhandled_panic

tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle/metrics.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle/metrics.rs, tokio/src/runtime/task/list.rs, tokio/tests/rt_metrics.rs
The word "active" is the opposite of "idle", but an "idle task" normally refers to a task that is alive but not currently able to make progress. However, idle tasks are included in this counter.
Instead of "active", I propose the name "alive".
=> metrics: rename `num_active_tasks` to `num_alive_tasks`

tokio/src/io/util/empty.rs, tokio/tests/io_util_empty.rs
While porting a test from `std:io` to `tokio::io`, I discovered `AsyncSeek` is not implemented for `tokio::io::Empty`. This was unexpected, as [`std::io::Seek` was implemented for `std::io::Empty` in Rust 1.51.0](https://doc.rust-lang.org/stable/std/io/struct.Empty.html#impl-Seek-for-Empty) (2021-03-25).
This implementation mimics the behavior of [the `Seek` implementation for `std::io::Empty`](https://github.com/rust-lang/rust/blob/036b38ced36b0ed16579f95b4647ba7424f6b1bc/library/std/src/io/util.rs#L81-L94).
=> io: implement `AsyncSeek` for `Empty`

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/chan.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/tests/sync_mpsc_weak.rs
close https://github.com/tokio-rs/tokio/issues/6653
Added `sender_weak_count` and `sender_strong_count` for Receiver and UnboundedReceiver.
=> sync: add sender_weak_count and sender_strong_count for Receiver

tokio/src/task/join_set.rs
The documentation of `JoinSet`'s `try_join_next()` and `try_join_next_with_id()` doesn't say what happens if there are no completed tasks.
`join_next()` waits, but `try_join_next()` appears to return `None` immediately.
Update the docs for both methods.
=> Doc: JoinSet::try_join_next() returns None when no tasks are completed

tokio/src/io/poll_evented.rs
=> Hardcode platform list in short-read optimization

tokio-stream/src/lib.rs, tokio-stream/src/stream_ext.rs, tokio-stream/tests/stream_chain.rs
The StreamExt trait provides the helpful method take, map, and the like on Streams. But the structures themselves (Take, Map, etc.) are not visible outside the crate, as they are not pub use in stream_ext.rs.
Re-exported `pub`licly all the structures in stream_ext.rs except for `Collect`, which is different and should not be exported as stated in its documentation. Re-exported them `pub`licly again in lib.rs.
Added a function in a test with return type `Chain` to show that it can be part of an external function signature.
Closes: #6656
=> Making the Stream adaptor structures public in tokio-stream

tokio/src/process/unix/pidfd_reaper.rs
On my machine, any pidfd reaper test that calls `is_pidfd_available` fails as my kernel version string does not contain a '-'; the code expects there to be one.
Fix the test so that is works regardless on whether the kernel string contains a '-'.
=> tests: pdfd-reaper: fix tests when '-' is absent from kernel version

tokio/src/runtime/time/mod.rs
fixes https://github.com/tokio-rs/tokio/issues/6682
We may encounter the following issue:
- After we calculated that `expiration_time` is `None`, we did not update the `next_wake` immediately. The `next_wake` is now the old value of the previous round of `park_internal` (the value is not `None`). Then we droped the locks.
- When other threads poll a `Sleep`, they find that `when > next_wake` (here `next_wake` is not `None`), so they will not execute `unpark.unpark()`.
While we hold the locks, we calculate and update the `next_wake`.
=> time: update wake_up while holding all the locks of sharded time wheels

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release fixes the bug identified as #6682, which caused timers not to fire when they should.
=> chore: release v1.38.1

tokio/src/runtime/park.rs, tokio/src/runtime/scheduler/multi_thread/park.rs, tokio/src/runtime/tests/loom_multi_thread/yield_now.rs
closes https://github.com/tokio-rs/tokio/issues/6536.
Fixes the failing test outlined in https://github.com/tokio-rs/tokio/issues/6536
Since this is just a Loom-related change, I felt it fine to simply increment the counter if the lock call fails. If a more robust change is desired, please let me know and I will happily do so. It feels like such a change would probably involve attaching the conditionally-compiled Loom counter to some struct, but I haven't looked too deeply into it.
=> 6536 - fix yield_calls_park_before_scheduling_again test

tokio/src/io/stdout.rs
closes #6672.
Add another example for `stdio` that describes a recommended way to use it in a loop to avoid a confusion reported in the above issue.
=> io: update `tokio::io::stdout` documentation

tokio/tests/sync_watch.rs
reciever_is_notified_when_last_sender_is_dropped
↓
receiver_is_notified_when_last_sender_is_dropped
=> sync: update sync_watch.rs

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/runtime.rs, tokio/src/task/builder.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs
Closes [#6673](https://github.com/tokio-rs/tokio/issues/6673).
Like  [#4009](https://github.com/tokio-rs/tokio/pull/4009), this PR adds a size check logic for public apis that accepts user-provided futures so that large futures are not repeatedly passed to the function and exhaust the stack.
Also, this extracts commonly used constant.
=> task: add size check for user-supplied future

README.md, tokio/README.md
Before we increase the MSRV, we tend to make an LTS release. Mark the latest release as LTS to do that.
cc @Thomasdezeeuw
=> chore: make 1.38 an LTS

.github/workflows/ci.yml, README.md, tokio-macros/Cargo.toml, tokio-stream/Cargo.toml, tokio-test/Cargo.toml, tokio-util/Cargo.toml, tokio/Cargo.toml, tokio/README.md
Mio v1 was recently released, and it requires an MSRV of 1.70.0 for various changes that mio is using to get rid of its `SocketAddr` type and instead use the std version. This PR proposes to bump the MSRV of Tokio to 1.70.
The main disadvantage is that debian stable is still at rustc 1.63.
Refs: #6635
=> chore: increase MSRV to 1.70

benches/Cargo.toml, tokio/Cargo.toml, tokio/src/loom/std/mod.rs
Unblocked now that tokio's MSRV is 1.70. I could also update the internal `::loom` function name if you want too.
Closes: #6432
=> chore: replace num_cpus with available_parallelism

tokio/src/runtime/metrics/batch.rs, tokio/src/runtime/metrics/mock.rs, tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/metrics/worker.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/stats.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/stats.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/tests/rt_unstable_metrics.rs
This counts the number of times a worker was parked and unparked. Thus it is odd if the worker is parked and even if the worker is unparked.
See #6353 and discussion in #6370.
A lightweight watchdog can watch the worker statistics and determine that a worker is stuck if its park/unpark count is even (thus it is active) and its poll count does not increase.
=> metrics: add worker_park_unpark_count

tokio/src/runtime/metrics/mock.rs, tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/metrics/worker.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/tests/rt_unstable_metrics.rs
This allows querying the thread id of each worker thread.
Additional information, such as native thread id, can be collected using `runtime::Builder::on_thread_start()` and correlated using the thread id.
See #6353 and discussion in #6370.
Provides thread ids of workers, so that a stuck worker can be correlated to a thread.
=> metrics: add worker thread id

tokio/Cargo.toml, tokio/src/net/unix/socketaddr.rs
Bumps the MSRV to 1.70.
One breaking changes is the removal of mio::net::SocketAddr, replacing it with std::os::unix::net::SocketAddr. The methods on the type should be the same.
For some smaller OS, such as ESP-IDF and Hermit, it can now be compiled without RUSTFLAGS.
=> Update to Mio v1

examples/Cargo.toml, tokio/Cargo.toml
This is the first update to the `windows-sys` crate in 8 months.  https://github.com/microsoft/windows-rs/releases/tag/0.52.0
=> Update `windows-sys` 0.52

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio/Cargo.toml
- msrv: increase MSRV to 1.70 ([#6645])
- macros: allow `unhandled_panic` behavior for `#[tokio::main]` and `#[tokio::test]` ([#6593])
[#6593]: https://github.com/tokio-rs/tokio/pull/6593
[#6645]: https://github.com/tokio-rs/tokio/pull/6645
=> Prepare tokio-macros v2.4.0

tokio/src/future/maybe_done.rs, tokio/src/macros/select.rs, tokio/src/macros/support.rs, tokio/tests/macros_join.rs, tokio/tests/macros_select.rs
=> macros: accept `IntoFuture` args for macros

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- This release bumps the MSRV to 1.70. ([#6645])
- This release upgrades to mio v1. ([#6635])
- This release upgrades to windows-sys v0.52 ([#6154])
- io: implement `AsyncSeek` for `Empty` ([#6663])
- metrics: stabilize `num_alive_tasks` ([#6619], [#6667])
- process: add `Command::as_std_mut` ([#6608])
- sync: add `watch::Sender::same_channel` ([#6637])
- sync: add `{Receiver,UnboundedReceiver}::{sender_strong_count,sender_weak_count}` ([#6661])
- sync: implement `Default` for `watch::Sender` ([#6626])
- task: implement `Clone` for `AbortHandle` ([#6621])
- task: stabilize `consume_budget` ([#6622])
- io: improve panic message of `ReadBuf::put_slice()` ([#6629])
- io: read during write in `copy_bidirectional` and `copy` ([#6532])
- runtime: replace `num_cpus` with `available_parallelism` …
=> Release Tokio v1.39.0

tokio/src/runtime/time/entry.rs, tokio/src/runtime/time/mod.rs, tokio/src/runtime/time/wheel/level.rs, tokio/src/runtime/time/wheel/mod.rs, tokio/src/util/linked_list.rs
This reverts #6584.
Closes: #6714
=> time: revert "time: avoid traversing entries in the time wheel twice"

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release reverts "time: avoid traversing entries in the time wheel twice" because it contains a bug. ([#6715])
[#6715]: https://github.com/tokio-rs/tokio/pull/6715
=> chore: prepare Tokio v1.39.1

.github/workflows/ci.yml
Improve testing for timers (which caused a regression, #6714) by testing Quinn in CI.
Fixes #6717.
=> Run Quinn tests in CI

examples/Cargo.toml, examples/dump.rs, tokio-macros/src/lib.rs, tokio/src/runtime/tests/queue.rs
Fixes ci failures due to the latest rust compiler.
=> chore: fix ci failures

tokio/src/macros/select.rs, tokio/tests/macros_select.rs
In the 1.39.0 release, we merged #6710 which allows the use of `IntoFuture` values with `tokio::select!`. Unfortunately, this resulted in a breaking change where the macro would no longer accept expressions that make use of [temporary lifetime extension](https://doc.rust-lang.org/1.58.1/reference/destructors.html#temporary-lifetime-extension). This PR fixes the breaking change.
Fixes: #6721
=> macros: allow temporary lifetime extension in select

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release fixes a regression where the `select!` macro stopped accepting expressions that make use of temporary lifetime extension. ([#6722])
[#6722]: https://github.com/tokio-rs/tokio/pull/6722
=> chore: prepare Tokio v1.39.2

tokio/src/process/mod.rs
With the recent MSRV bump from 1.63 to 1.70, this can now be stabilized.
The underlying [`std::os::unix::process::CommandExt::process_group()`](https://doc.rust-lang.org/stable/std/os/unix/process/trait.CommandExt.html#tymethod.process_group) was added in Rust 1.64.0.
Also adjust the documentation to match std, explaining why setting process groups may be useful.
=> process: stabilize `Command::process_group`

tokio/src/lib.rs
This may seem like overkill, but we get this problem a lot on Discord.
To enable unstable features in Tokio, passing `--cfg tokio_unstable` to
the compiler is necessary. We document how to do this in a variety of
ways in the main Tokio (lib.rs) documentation.
One way is to add a `[build]` section to the file `.cargo/config.toml`.
Even though this filename is stated in the documentation, it is quite
common that first time users (including this author, some time ago) put
it in their `Cargo.toml` file instead.
This change adds a "warning" section to the documentation to reiterate
the point that this section doesn't go in the cargo manifest
(`Cargo.toml`).
=> docs: reiterate that `[build]` doesn't go in Cargo.toml

tokio/src/sync/batch_semaphore.rs, tokio/src/time/sleep.rs, tokio/tests/tracing-instrumentation/tests/sync.rs, tokio/tests/tracing-instrumentation/tests/time.rs
When instrumenting resources in Tokio, a span is created for each
resource. Previously, all resources inherited the currently active span
as their parent (tracing default). However, this would keep that parent
span alive until the resource (and its span) were dropped. This is often
not correct, as a resource may be created in a task and then sent
elsewhere, while the originating task ends.
This artificial extension of the parent span's lifetime would make it
look like that task was still alive (but idle) in any system reading the
tracing instrumentation in Tokio, for example Tokio Console as reported
in tokio-rs/console#345.
In #6107, most of the existing resource spans were updated to
make them explicit roots, so they have no contextual parent. However,
2. were missed:
- `Sleep`
- …
=> time,sync: make Sleep and BatchSemaphore instrumentation explicit roots

tokio/src/io/util/write_all_buf.rs, tokio/tests/io_write_all_buf.rs
=> io: use vectored io for `write_all_buf` when possible

tokio/src/runtime/task/id.rs, tokio/src/runtime/task/mod.rs
This should make the size slightly smaller when `Id` is wrapped in Option.
It seems that [ThreadId](https://github.com/tokio-rs/tokio/blob/0cbf1a5adae81e8ff86ca6d040aeee67cf888262/tokio/src/runtime/thread_id.rs) does the same thing already. (However, unlike threadId, when it overflows it wraps around without panic to keep the current behavior.)
=> task: use `NonZeroU64` for `task::Id`

tokio/src/future/maybe_done.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/tests/task.rs, tokio/tests/macros_join.rs
As suggested by @ralfjung at https://github.com/rust-lang/miri/issues/3780#issuecomment-2264999042
Initially pushing branch with just tests to ensure that they fail in CI without the fix.
Closes: #6729
=> Prevent niche-optimization on futures to avoid triggering miri

tokio/src/sync/mpsc/error.rs
In the case where you might not care about the specific error produced (or you just want to log it) but want to retrieve the value you sent, these provide a simple way to do that.
These are just convenience methods to retrieve the inner value from these error types. These enums aren't `non_exhaustive`  so I don't think there's a risk of the API changing and invalidating these methods.
Straight forward into_inner method.
=> sync: Add into_inner method on TrySendErrors

tokio/src/runtime/task/join.rs
if the return value of abort_handle is unused then abort will never be called for that JoinHandle
Fixes: #6761
=> must use macro annotation for abort_handle of JoinHandle

tokio/src/macros/select.rs
Closes: #6572
The original PR seems stale. I believe this PR fixes the problem surfaced in the discussion of the original PR.
=> macros: improve documentation for `select!`

tokio/tests/io_async_fd.rs
The `io_async_fd.rs` tests contain a `drain()` function, which currently performs synchronous reads from a UDS socket until it returns `io::ErrorKind::WouldBlock` (i.e., errno `EWOULDBLOCK`/`EAGAIN`). The *intent* behind this function is to ensure that all data has been drained from the UDS socket's buffer...which is what it appears to do...on Linux. On other systems, it appears that an `EWOULDBLOCK` or `EAGAIN` may be returned before enough data has been read from the UDS socket to result in the other end being notified that the socket is now writable. In particular, this appears to be the case on illumos, where the tests using this function hang forever (see [this comment][1] on PR #6769).
To my knowledge, this behavior is still POSIX-compliant --- the reader will still be notified that …
=> tests: handle spurious EWOULDBLOCK in io_async_fd

tokio/tests/uds_stream.rs
Currently, the test `uds_stream::epollhup` expects that a `UdsStream::connect` future to a Unix socket which is closed by the accept side to always fail with `io::ErrorKind::ConnectionReset`. On illumos, and potentially other systems, it instead fails with `io::ErrorKind::ConnectionRefused`.
This was discovered whilst adding an illumos CI job in PR #6769. See: https://github.com/tokio-rs/tokio/pull/6769#issuecomment-2284753794
This commit changes the test to accept either `ConenctionReset` or `ConnectionRefused`. This way, we are more tolerant of different operating systems which may decide to return slightly different errnos here. Both ECONNREFUSED and ECONNRESET seem reasonable to expect in this situation, although arguably, ECONNREFUSED is actually more correct: the acceptor did not …
=> tests: handle ECONNREFUSED in uds_stream::epollhup

tokio/src/sync/mpsc/mod.rs
Fixes: #6754
Documents the current allocation behavior of the mpsc channel as described in the linked issue.
[View rendered documentation.](https://deploy-preview-6773--tokio-rs.netlify.app/tokio/sync/mpsc/index.html#allocation-behavior)
=> sync: document mpsc channel allocation behavior

tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs, tokio/tests/uds_stream.rs
Closes https://github.com/tokio-rs/tokio/issues/6767.
If the beginning of the path is `\0`, we fallback to std's `from_abstract_name`.
=> net: add handling for abstract socket name

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release fixes a regression where the unix socket api stopped accepting
the abstract socket namespace. ([#6772])
[#6772]: https://github.com/tokio-rs/tokio/pull/6772
=> chore: prepare Tokio v1.39.3

tokio-util/src/task/task_tracker.rs
While reading the docs for `TaskTracker` I realized there was a typo in its documentation.
=> util: fix typo in `TaskTracker` docs

tokio/src/io/async_read.rs
As per this discussion:
https://users.rust-lang.org/t/will-tokio-ever-pass-a-readbuf-with-no-capacity-to-poll-read/116124/2
there are two possible reasons why zero bytes were added to the `ReadBuf`, but the docs only discuss one reason.
=> fix explanation of 'zero bytes read' case

tokio/src/io/mod.rs, tokio/src/io/util/mem.rs, tokio/src/io/util/mod.rs
I think that it is unfortunate that the underlying structure backing the `DuplexStream` is not exposed. There are cases where a single direction will suffice, for example, when I have only a single writer and single reader, thus not requiring bidirectionality.
In this patch, I renamed the `Pipe` to the `SimplexStream` for coherence with the already existing `DuplexStream` and made it public
=> Add `SimplexStream` structure

tokio-util/src/task/abort_on_drop.rs, tokio-util/src/task/mod.rs, tokio-util/tests/abort_on_drop.rs
wraps a `JoinHandle`, aborting the task on drop
Refs: #6224
Fixes: #6160
=> Add `AbortOnDropHandle` type

tokio/src/task/join_set.rs, tokio/tests/task_join_set.rs
Adds join_all method to JoinSet. join_all consumes JoinSet and awaits the completion of all tasks on it, returning the results of the tasks in a vector. An error or panic in the task will cause join_all to panic, canceling all other tasks.
Fixes: #6664
The goal of this PR is to add the method join_all to JoinSet in line with the discussion in Fixes: #6664.
join_all method is added, as well as tests for:
1. Success scenario returning tasks in a vector.
2. Failure scenario resulting in a panic and cancelation of other tasks.
=> task: add join_all method to JoinSet

tokio/src/runtime/blocking/schedule.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/config.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/src/runtime/scheduler/multi_thread_alt/handle.rs, tokio/src/runtime/scheduler/multi_thread_alt/worker.rs, tokio/src/runtime/task/core.rs, tokio/src/runtime/task/harness.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task_hooks.rs, tokio/src/runtime/tests/mod.rs, tokio/src/runtime/tests/queue.rs, tokio/src/runtime/tests/task.rs, tokio/src/task/local.rs, tokio/tests/task_hooks.rs
This change implements two hooks for per-task actions, one which is invoked on task spawn, and one which is invoked during task termination.
These hooks initially are only supplied with the task ID (on unstable only), but more information can be added in the future, as the struct used to supply parameters is opaque.
Fixes #3181.
=> rt: implement initial set of task hooks

tokio/src/loom/mocked.rs, tokio/src/loom/std/mutex.rs, tokio/src/runtime/time/mod.rs
#6683 introduced additional allocations to keep the locks of the timer wheel shards alive. #6757 is a request to get rid of those additional allocations. This PR should address this issue.
I wrapped the timer wheel shards in an `RwLock`. With that we can get a `write`-lock in `park_internal` to prevent other threads from accessing the shards. In all other places the `read`-lock can be used for simultaneous access.
Closes #6757
=> time: eliminate timer wheel allocations

tokio/tests/rt_common.rs
Fixes #6765 where the yield_defers_until_park test was hanging on failures.
The test hanged while trying to `drop` the Runtime on failures since:
1. The tasks we spawn at the beginning of the test will never terminate on failures since we never set the `flag` they loop on to `true`, and
2. The tokio Runtime waits till all of the spawned tasks terminate / yield before dropping them on [shutdown](https://docs.rs/tokio/1.39.3/tokio/runtime/struct.Runtime.html#shutdown).
To fix, we set the flag to true on failure cases to guarantee all tasks terminate before returning.
To verify the fix, I looped the test 100k times. Whereas before I always got a hang, afterwards, I never
saw it hang and got the appropriate test failure.
=> rt: fix race in yield_defers_until_park test

tokio-util/Cargo.toml
Like https://github.com/tokio-rs/tokio/pull/1960, but for tokio-util. Makes tokio-util usable in the Playground.
See https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14e34737f9747022fcfaff8428e4eb53 for what happens currently.
=> Tokio-util: Enable the full feature when compiled for the playground

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
This release bumps the MSRV to 1.70. ([#6645])
- sync: Add `run_until_cancelled` to `tokio_util::sync::CancellationToken` ([#6618])
- task: add `AbortOnDropHandle` type ([#6786])
- deps: no default features for hashbrown ([#6541])
- time: wake `DelayQueue` when removing last item ([#6752])
- deps: enable the full feature when compiled for the playground ([#6818])
- task: fix typo in `TaskTracker` docs ([#6792])
[#6645]: https://github.com/tokio-rs/tokio/pull/6645
[#6541]: https://github.com/tokio-rs/tokio/pull/6541
[#6618]: https://github.com/tokio-rs/tokio/pull/6618
[#6752]: https://github.com/tokio-rs/tokio/pull/6752
[#6786]: https://github.com/tokio-rs/tokio/pull/6786
[#6792]: https://github.com/tokio-rs/tokio/pull/6792
[#6818]: https://github.com/tokio-rs/tokio/pull/6818
=> chore: prepare tokio-util 0.7.12

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml
As discussed on Discord. Full changelog (I skipped most of the chores for the changelog):
```
djc-2021 stream-0.1.16-prep tokio-stream $ git log --oneline -20 . 
a9fd3b94 (HEAD -> stream-0.1.16-prep, origin/stream-0.1.16-prep) stream: prepare 0.1.16 release
12b2567b (origin/master, origin/HEAD, master) chore: use `poll_fn` from std (#6810)
11f66f43 chore: replace `ready!` with `std::task::ready!` (#6804)
15cd5146 chore: increase MSRV to 1.70 (#6645)
c8f3539b stream: make stream adapters public (#6658)
3a6fdc05 license: fix formatting and remove year in licenses (#6451)
daa89017 ci: fix new clippy warnings (#6569)
2a0df5fb ci: bump nightly to nightly-2024-05-05 (#6538)
be9328da chore: fix clippy warnings (#6466)
a1acfd8c readme: add readme for tokio-stream (#6456)
4601c847 stream: add …
```
=> stream: prepare 0.1.16 release

tokio/src/loom/mocked.rs, tokio/src/loom/std/mod.rs, tokio/src/loom/std/parking_lot.rs, tokio/src/loom/std/rwlock.rs, tokio/src/runtime/time/mod.rs, tokio/src/sync/broadcast.rs, tokio/src/sync/watch.rs
With #6779 we removed unnecessary allocations from the timerwheel by wrapping it in an `std::sync::RwLock`. Since the `Mutex` used in this part of the project uses an abstraction in `loom::sync::Mutex` to get rid of the poisoning aspects of `std::sync::Mutex` the same should probably be done for the used read-write lock struct.
This commit introduces an abstraction to get rid of the poisoning aspects of `std::sync::RwLock` by introducing a wrapper to the `loom::sync` module similar to `loom::sync::Mutex`.
Refs: #6779
=> loom: add abstraction for RwLock to remove poisoning aspect

tokio/src/sync/notify.rs
To prevent situation as in these "bug" report: https://github.com/tokio-rs/tokio/issues/6827
Add #[must_use] to print warning while compiling or checking
=> sync: add `#[must_use]` to `Notified`

spellcheck.dic, tokio/src/io/async_fd.rs
[Rendered](https://deploy-preview-6821--tokio-rs.netlify.app/tokio/io/unix/struct.asyncfd)
Fixes: #6820
=> io: recommend `OwnedFd` with `AsyncFd`

tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs, tokio/tests/uds_stream.rs
Closes https://github.com/tokio-rs/tokio/issues/6837.
The `from_abstract_name` function from std assumes the name in parameter doesn't have a prefix `\0` (see also the [implementation](https://github.com/rust-lang/rust/blob/5a2dd7d4f3210629e65879aeecbe643ba3b86bb4/library/std/src/os/unix/net/addr.rs#L269-L293) or [a test](https://github.com/rust-lang/rust/blob/16beabe1e17fa1f35a1964609ee589b999386690/library/std/src/os/unix/net/tests.rs#L425) for this function), so we need to trim the leading zero byte from the path provided by the user.
=> net: fix handling of leading zero byte in `from_abstract_name`

tokio/src/net/tcp/socket.rs
The examples were swapped, I also renamed the variable `stream` to `socket` since all the other examples only call it `stream` after a successful `connect` call.
Situation before:
---
Situation after:
=> Docs: Fix swapped examples for `TcpSocket::set_nodelay` and `TcpSocket::nodelay`

tokio/src/macros/try_join.rs
close https://github.com/tokio-rs/tokio/issues/6775
=> macros: render more comprehensible documentation for `try_join!`

tokio/src/sync/mod.rs, tokio/src/sync/mpsc/mod.rs
=> Doc section for sync module on runtime compatibility

tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/runtime.rs, tokio/src/task/builder.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs
In #4009, `task::spawn` was changed to send tasks to the heap to prevent stack overflows in debug mode.
The initial proposal was to do this unconditionally in debug mode:
```rust
if cfg!(debug_assertions) {
```
but based on a suggestion from @Darksonn this was then changed to
```rust
if cfg!(debug_assertions) && std::mem::size_of::<T>() > BOX_FUTURE_THRESHOLD {
```
As detailed in #6057, this creates a bit of a footgun where code works great in debug builds but then fails in release mode. This can be surprisingly hard to track down (https://github.com/tokio-rs/tokio/issues/6057#issuecomment-2331098720).
Instead of only doing this for debug builds only, I propose we change the condition to
```rust
if std::mem::size_of::<T>() > BOX_FUTURE_THRESHOLD {
```
only so that debug and release builds …
=> Always send large futures to heap

tokio/src/net/tcp/socket.rs
There is a punctuation error.
Change “socket hijacking” to "socket hijacking".
=> doc: Fix a symbol issue

spellcheck.dic, tokio/src/runtime/io/driver.rs, tokio/src/runtime/io/mod.rs, tokio/src/runtime/io/registration_set.rs, tokio/src/runtime/io/scheduled_io.rs, tokio/src/util/mod.rs, tokio/src/util/ptr_expose.rs
Miri is being improved to support epoll, which means that we will be able to support a much larger fraction of Tokio's test suite under miri. That is being tracked in #6812. This PR removes our usage of ptr2int2ptr roundtrips when running under miri for better miri compatibility.
cc @RalfJung @tiif
=> Avoid pointer casts in IO driver on miri

tokio/tests/rt_metrics.rs
This makes `injection_queue_depth_multi_thread` fail normally instead of hanging. This change was suggested in #6847, but does not actually fix the flakiness.
cc @jofas
=> metrics: don't hang in injection_queue_depth_multi_thread test

tokio-util/src/task/spawn_pinned.rs, tokio-util/src/time/wheel/mod.rs, tokio/src/signal/unix.rs
There are some places where using a boxed slice instead of Vec is sufficient, allowing for minor space optimization.
=> chore: use boxed slice if possible

tokio/src/net/unix/socketaddr.rs
Implement `From` to convert `tokio::unix::SocketAddr` to and from Rust's `std::os::unix::net::SocketAddr`.
These types were (I'm told) originally separate because `mio` had a distinct `SocketAddr` type.  This patch makes it possible to convert between them more easily.
Fixes: #6864
=> socketaddr: implement conversions for tokio and std unix `SocketAddr`

tokio/src/runtime/coop.rs, tokio/src/sync/watch.rs, tokio/tests/sync_watch.rs
#6839 showed that `sync::watch::Receiver::changed` will not cooperatively yield control back to the runtime which led to it blocking the thread it was running on.
Edit: This is also true for `sync::watch::Receiver::wait_for` and `sync::watch::Sender::closed`
Added cooperative scheduling to `sync::watch::Receiver::changed` by utilizing the `runtime::coop` module.
More specifically I added a new future type that wraps the implementation of `sync::watch::Receiver::changed` and checks if the current task has exceeded its budget before polling the wrapped future.
Closes #6839.
=> sync, coop: apply cooperative scheduling to `sync::watch`

tokio/src/sync/broadcast.rs, tokio/tests/sync_broadcast.rs
Similar to #6846 the function `sync::broadcast::Receiver::recv` utilize cooperative scheduling to prevent that a task could block the runtime. 
I added the usage of `runtime::coop::Coop` that was added in #6846 to the function so that takes part in the coop budget.
Closes #6855.
=> sync, coop: apply cooperative scheduling to sync::broadcast::Receiver

tokio-stream/src/wrappers/broadcast.rs
=> Fix `Stream` link in broadcast docs

tokio-macros/src/entry.rs
Fixes #6869: nightly clippy warns on any `#[tokio::{main,test}]`.
`#[allow(clippy::needless_return)]` to suppress that clippy warning. Ideally clippy should allow it for macro generated code, but we have no idea how long it would take to do that.
Also document the reason why we are using a `return` instead of a tail expression.
Tested to work for `1.83.0-nightly (2bd1e894e 2024-09-26)`
=> macros: suppress clippy::needless_return and add docs

CONTRIBUTING.md
Remove the `-Zmiri-tag-raw-pointers` flag that does not exist anymore, and make docs content consistent with the current ci settings.
=> readme: update miri test flags

tokio-util/Cargo.toml, tokio/Cargo.toml, tokio/src/runtime/blocking/pool.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/runtime.rs, tokio/src/task/builder.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs, tokio/src/util/trace.rs, tokio/tests/tracing-instrumentation/tests/task.rs
In Tokio, the futures for tasks are stored on the stack unless they are
explicitly boxed, either by the user or auto-boxed by Tokio when they
are especially large. Auto-boxing now also occurs in release mode
(since #6826).
Having very large futures can be problematic as it can cause a stack
overflow. In some cases it might be desireable to have smaller futures,
even if they are placed on the heap.
This change adds the size of the future driving an async task or the
function driving a blocking task to the tracing instrumentation. In the
case of a future that is auto-boxed by Tokio, both the final size as well
the original size before boxing is included.
To do this, a new struct `SpawnMeta` gets passed down from where a
future might get boxed to where the instrumentation is added. This …
=> task: add task size to tracing instrumentation

tokio/src/io/async_fd.rs
https://github.com/tokio-rs/tokio/issues/6654
=> doc: document cancellation safety

tokio/src/sync/watch.rs
This makes it possible to check if other senders exist. For example If you are using a Sender as a subscriber to get a Receiver and might want to know if the real sender is still running.
=> sync: add `watch::Sender::sender_count`

tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/task/error.rs, tokio/src/runtime/task/harness.rs, tokio/src/runtime/task_hooks.rs, tokio/src/task/join_set.rs
Follow up https://github.com/tokio-rs/tokio/pull/6793.
=> task: stabilize `task::Id` related apis

tokio/src/runtime/builder.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/local_runtime/mod.rs, tokio/src/runtime/local_runtime/options.rs, tokio/src/runtime/local_runtime/runtime.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/task/list.rs, tokio/src/task/local.rs, tokio/src/util/trace.rs, tokio/tests/rt_local.rs
This change adds LocalRuntime, a new unstable runtime type which cannot be transferred across thread boundaries and supports spawn_local when called from the thread which owns the runtime.
The initial set of docs for this are iffy. Documentation is absent right now at the module level, with the docs for the LocalRuntime struct itself being somewhat duplicative of those for the `Runtime` type. This can probably be addressed later as stabilization nears.
This API has a few interesting implementation details:
- because it was considered beneficial to reuse the same Handle as the normal runtime, it is possible to call spawn_local from a runtime context while on a different thread from the one which drives the runtime and owns it. This forces us to check the thread ID before attempting a local …
=> rt: add LocalRuntime

.github/workflows/ci.yml
When adding words to the dictionary, it can be hard to actually get the en_US.UTF8 locale to work on all platforms. This prints it in CI so you can copy-paste it back.
=> ci: Print out the correct sort order for the dictionary on failure

tokio/src/sync/mpsc/bounded.rs, tokio/src/sync/mpsc/unbounded.rs, tokio/tests/sync_panic.rs
Fixes: #6865
I would like to use an API like `recv_many`, but from a blocking context.
Use crate::future::block_on in a similar fashion to how blocking_recv does it to call the async `recv_many` function.
Tests and docs. I'll complete them once it's clear if this entire change makes sense. Do you think referring to `blocking_recv` and `recv_many` from the docs is fine or should there be more specific docs?
=> sync: add mpsc::Receiver::blocking_recv_many

.cirrus.yml, .github/workflows/ci.yml
Workaround for https://github.com/rust-lang/rust/issues/130677 which has landed in rustc 1.82.0.
=> ci: freeze FreeBSD on rustc 1.81

tokio/src/runtime/metrics/runtime.rs, tokio/tests/rt_metrics.rs
This changes the metric name of `injection_queue_depth` to `global_queue_depth`. Note that this only changes the public facing apis, not all internal codes or comments.
Also, I left the `injection_queue_depth` as a deprecated api.
ref: https://github.com/tokio-rs/tokio/issues/6915
=> metrics: rename `injection_queue_depth` to `global_queue_depth`

tokio/tests/rt_metrics.rs
This closes #6847 by removing the deadlock from the test as discussed in #6876. The changes I made are based on [this suggestion](https://github.com/tokio-rs/tokio/pull/6876#issuecomment-2416665508). I made the blocking tasks block by letting them wait on a message from a `std::mpsc` channel. This is quite convenient IMO, because we can exit the blocking tasks simply by dropping all `Sender`s of the channel.[^1]
[^1]: Unlike the previous implementation that used `Barrier`s for synchronization&mdash;even if the test were to unforeseeably panic&mdash;the blocking tasks would still exit and cause the test to fail early instead of timing out.
=> Fixed deadlock in injection_queue_depth_multi_thread test

tokio/src/runtime/builder.rs, tokio/src/runtime/metrics/runtime.rs, tokio/tests/rt_unstable_metrics.rs
**Note: If this PR does not make the 1.41 release, one more deprecation needs to be added prior to merge**
A consistent bit of feedback I've heard is that the `poll_count_histogram` name is a little confusing since the value customers actually get out of it is `poll_times`.
This renames all public APIs from `poll_count` to `poll_time`. The existing APIs were deprecated with one exception: the newly added `poll_count_histogram_configuration` which hasn't been released yet was simply renamed.
=> metrics: rename `*_poll_count_*` to `*_poll_time_*`

tokio/src/lib.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/mod.rs, tokio/src/runtime/runtime.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task_hooks.rs
Fixes: #6907
Adds doc attribute noting the tokio_unstable requirements for various items
=> runtime: fix stability feature flags for docs

.github/workflows/audit.yml, .github/workflows/pr-audit.yml, benches/Cargo.toml, deny.toml, examples/Cargo.toml, stress-test/Cargo.toml, tests-build/Cargo.toml, tests-integration/Cargo.toml, tokio-stream/Cargo.toml
The rustsec audit check is not working anymore due to a `Cargo.lock` requirement. Update to cargo deny instead.
I'm not completely sure about this configuration. Ideally, we want advisories to result in an issue being opened, rather than in failing CI on random PRs. Thoughts?
=> ci: use cargo deny

.github/workflows/ci.yml
CI failure due to cargo-check-external-types bug: https://github.com/taiki-e/pin-project-lite/issues/86
Use patched version (https://github.com/awslabs/cargo-check-external-types/pull/183).
(Actually it might be better to temporarily disable this check...)
=> ci: use patched version of cargo-check-external-types to fix CI failure

tokio/src/net/mod.rs
Fixes #6935. I nudged rustdoc to show the `net` feature on the re-export by `cfg(inline)`ing the documentation of `UdpSocket`. This works because `net::udp::UdpSocket` is already wrapped in a `cfg_net!`, which is seemingly stripped by rustdoc from the re-exported item.
Here are screenshots from my branch built with
```
RUSTDOCFLAGS="--cfg docsrs --cfg tokio_unstable" RUSTFLAGS="--cfg docsrs --cfg tokio_unstable" cargo +nightly doc --all-features
```
=> Making `net` feature flag show in documentation for net::UdpSocket

tokio/tests/rt_metrics.rs
@Darksonn and @mox692 [discovered a race condition](https://github.com/tokio-rs/tokio/pull/6932#discussion_r1812507881) in the retry logic introduced in #6916 that this PR aims to fix.
In the `global_queue_depth_multi_thread` test, we try to block the two worker threads before spawning more tasks onto the global queue. This allows us to measure the [`RuntimeMetrics::global_queue_depth`](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html#method.global_queue_depth) deterministically, as the two worker threads are blocked and therefore unable to pull any tasks from the global queue. Blocking the two worker threads [might fail](https://github.com/tokio-rs/tokio/pull/6876), in which case one of the tasks from the previous try to block the runtime would remain in the global …
=> Removed race condition from global_queue_depth_multi_thread test

tokio/tests/rt_unstable_metrics.rs
Fixes #6470. Same approach as in #6916 for a similar flaky test that also relies on blocking the runtime. I tried corroborating the validity of this fix by running this test ~250k times successfully on my local machine, but I was unable to hit even a single retry in those runs.
=> Fix for flaky worker_steal_count test

.github/workflows/ci.yml
cargo-check-external-types bug has been fixed and released in 0.1.13.
Context: https://github.com/tokio-rs/tokio/pull/6937
=> ci: update cargo-check-external-types to 0.1.13

CONTRIBUTING.md
A code block in CONTRIBUTING.md has mismatched backticks.
The document is rendered correctly at least on GitHub, but syntax highlighting fails after that point.
Adjust the backticks.
=> docs: fix mismatched backticks in CONTRIBUTING.md

tokio/src/runtime/metrics/histogram.rs, tokio/tests/rt_unstable_metrics.rs
In Tokio 1.41, #6897 refactored histograms and their construction. Unfortunately, this change included a bug where `num_buckets` was not properly preserved when the legacy builder methods were used. This could cause an inconsistency where even if the customer set max buckets, we would still use the default.
**This can result in a runtime panic because the histogram thinks it has `N` buckets, but in reality, it only has 10.**
Fix the bug.
=> metrics: Fix bug where num_buckets became inconsistent

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- metrics: fix bug with wrong number of buckets for the histogram ([#6957])
- net: display `net` requirement for `net::UdpSocket` in docs ([#6938])
- net: fix typo in `TcpStream` internal comment ([#6944])
[#6957]: https://github.com/tokio-rs/tokio/pull/6957
[#6938]: https://github.com/tokio-rs/tokio/pull/6938
[#6944]: https://github.com/tokio-rs/tokio/pull/6944
=> chore: prepare Tokio v1.41.1

.github/workflows/ci.yml, tokio/src/io/mod.rs, tokio/src/lib.rs, tokio/src/net/tcp/socket.rs, tokio/src/net/windows/named_pipe.rs, tokio/src/signal/windows.rs
I believe this fixes #6625 by only building the `io::bsd` module on Unix machines, in accordance with https://github.com/tokio-rs/tokio/issues/6625#issuecomment-2157740211. Putting the `#[cfg(unix)]` outside of the `cfg_aio!` macro felt less intrusive, as the macro is also used in `io::Interest`.[^1] I haven't yet tested this on Windows (or via cross-compilation).
While creating this PR I checked out the build logs from docs.rs and saw that the two [Windows builds](https://docs.rs/crate/tokio/1.41.0/builds/1400277/x86_64-pc-windows-msvc.txt) there are broken as well. I want to replicate how docs.rs builds the docs for Windows and fix them, too, so starting this PR as a draft. 
I wonder if building the docs on Windows would be a good idea to add to CI, to guard against future regressions? …
=> Fix building docs on Windows

tokio/src/io/async_fd.rs, tokio/tests/io_async_fd.rs
This allows to provide APIs like `try_recv()` and `try_send()` in custom types built on top of `AsyncFd`.
Closes #4719.
Custom types built on top of `AsyncFd` may want to provide functions like `try_recv()` and `try_send()`. Currently, I don't think this can be done cleanly, because the `poll_[read|write]_ready()` functions will register the current task to be woken. They use the reserved waker slot, so they would interfere with other users of `poll_{ready,write}_ready()`, such as `AsyncRead` and `AsyncWrite` implementations.
I suppose you currently could poll the future from `{read,write}_ready()` once with a fake waker. But that is quite a hacky workaround, and if the future is not ready, the fake waker would actually be registered only to be removed again directly after the polling. …
=> io: add AsyncFd::try_io() and try_io_mut()

tokio/src/runtime/io/scheduled_io.rs
Removes a redundant checks:
~~1. No need to unpack `readiness`, Since readiness is already positioned at the least significant portion, And `Ready::from_usize` performs internal masking~~
2. Remove `if !existing.will_wake { .. }`, Since `waker.clone_from` already performs this optimization internally.
3. Updated `fn set_readiness()`, to skip calling the closure `f(..)` when possible.
=> io: remove redundant check

.github/workflows/ci.yml, .github/workflows/stress-test.yml
Needed due to https://github.com/rust-lang/rust/issues/133574.
=> ci: pin valgrind on 1.82

tokio-util/src/time/wheel/level.rs
Just browsing through the code I saw this block, `std::array::from_fn` exists since 1.63 and MSRV according to the readme is 1.70 now.
Replace manually created array with `std::array::from_fn`.
=> time: use `array::from_fn` instead of manually creating array

tokio/src/runtime/context.rs, tokio/tests/task_yield_now.rs
Fixes https://github.com/tokio-rs/tokio/issues/6996
The PR makes wake defer only occur in the enter runtime state. this avoid lost wakeup due to defer during exit runtime.
=> runtime: fixed yield_now lost wakeup

tests-build/README.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "fail" to "fails".
Please review the changes and let me know if any additional changes are needed.
=> tests: fix typo in build test instructions

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- io: add `AsyncFd::{try_io, try_io_mut}` ([#6967])
- io: avoid `ptr->ref->ptr` roundtrip in RegistrationSet ([#6929])
- runtime: do not defer `yield_now` inside `block_in_place` ([#6999])
- io: simplify io readiness logic ([#6966])
- net: fix docs for `tokio::net::unix::{pid_t, gid_t, uid_t}` ([#6791])
- time: fix a typo in `Instant` docs ([#6982])
[#6791]: https://github.com/tokio-rs/tokio/pull/6791
[#6929]: https://github.com/tokio-rs/tokio/pull/6929
[#6966]: https://github.com/tokio-rs/tokio/pull/6966
[#6967]: https://github.com/tokio-rs/tokio/pull/6967
[#6982]: https://github.com/tokio-rs/tokio/pull/6982
[#6999]: https://github.com/tokio-rs/tokio/pull/6999
=> chore: prepare Tokio v1.42.0

.cirrus.yml, .github/workflows/ci.yml
This reverts commit 32e0b4325f877d53ddc76818198becad9312159a.
This was frozen due to a bug in 1.82, but 1.83 is now out.
=> Unfreeze FreeBSD from rustc 1.81

tokio-util/src/codec/lines_codec.rs, tokio-util/tests/codecs.rs
LinesCodec is not resetting internal state in `decode_eof` in case there is utf8 decoding error.
This causes the following panic in subsequent `decode` calls: `slice index starts at 8 but ends at 0`
Reset `next_index` at the start of `decode_eof`.
=> codec: fix incorrect handling of invalid utf-8 in `LinesCodec::decode_eof`

.circleci/config.yml, .github/buildomat/README.md, .github/workflows/ci.yml, CONTRIBUTING.md, tokio-util/src/task/spawn_pinned.rs, tokio/src/net/unix/stream.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/task_hooks.rs, tokio/src/task/join_set.rs
Trailing whitespace is generally always wrong. There are a few instances of it in the Tokio repository.
=> ci: detect trailing whitespace

tokio/src/signal/unix.rs, tokio/tests/signal_info.rs
illumos has supported SIGINFO for a long time; see https://github.com/illumos/illumos-gate/commit/19d32b9ab53d17ac6605971e14c45a5281f8d9bb. It is possible to create a signal handler from the constant by hand, but having `SignalKind::info` work is more convenient.
Add `target_os = "illumos"` to the `cfg` for `SignalKind::info`.
=> signal: add SignalKind::info on illumos

tokio/tests/signal_ctrl_c.rs, tokio/tests/signal_info.rs
The oneshot channels don't make any sense here. Tasks in a current-thread runtime will run once the main task yields, which is always after the `fire.send(())` call. Thus, clean up and simplify the tests.
=> signal: remove oneshot channels from tests

tokio-stream/CHANGELOG.md, tokio-stream/Cargo.toml
- deps: fix dev-dependency on tokio-test ([#6931], [#7019])
- stream: fix link on `Peekable` ([#6861])
- sync: fix `Stream` link in broadcast docs ([#6873])
[#6861]: https://github.com/tokio-rs/tokio/pull/6861
[#6873]: https://github.com/tokio-rs/tokio/pull/6873
[#6931]: https://github.com/tokio-rs/tokio/pull/6931
[#7019]: https://github.com/tokio-rs/tokio/pull/7019
Closes: #7019
=> chore: prepare tokio-stream v0.1.17

tokio/src/process/mod.rs
=> process: add `Command::into_std()`

tokio-util/tests/spawn_pinned.rs
This test previously blocked on a miri bug, but now it can run successfully. :tada:
Tracking issue #6812
=> Run spawn_pinned test on miri

spellcheck.dic, tokio/src/runtime/dump.rs, tokio/src/runtime/task/trace/mod.rs
This PR creates structs that allow dumping backtraces in a programmatic format, for example JSON. A JSON serializer is not natively included to avoid creating a Tokio dependency on one, but serialization can be done by customers.
Fixes #6309.
=> allow getting task dump backtraces in a programmatic format

tokio-util/src/either.rs
`Either` currently uses default implementation for `poll_write_vectored ` and `is_write_vectored ` but it would be better to respect the underlying `AsyncWrite` implementation.
=> util: enable `Either` to use underlying `AsyncWrite` implementation

tokio-stream/src/wrappers/broadcast.rs, tokio-stream/src/wrappers/interval.rs, tokio-stream/src/wrappers/lines.rs, tokio-stream/src/wrappers/mpsc_bounded.rs, tokio-stream/src/wrappers/mpsc_unbounded.rs, tokio-stream/src/wrappers/read_dir.rs, tokio-stream/src/wrappers/signal_unix.rs, tokio-stream/src/wrappers/signal_windows.rs, tokio-stream/src/wrappers/split.rs, tokio-stream/src/wrappers/tcp_listener.rs, tokio-stream/src/wrappers/unix_listener.rs
I noticed a question on the discord about one of the stream wrappers, and wrote some sample code to answer it. This extends that to some of the other wrappers.
New doc comment examples in the tokio-stream::wrappers types.
=> stream: add examples to wrapper types

spellcheck.dic, tokio-util/CHANGELOG.md, tokio/CHANGELOG.md, tokio/src/runtime/task/trace/mod.rs
File: spellcheck.dic
Added:
ambient (correct spelling)
Removed:
ambiant (incorrect spelling)
Reason: Corrected the spelling of "ambient" to ensure consistency and accuracy in documentation and code comments.
File: tokio-util/CHANGELOG.md
Changed:
Date format for version 0.7.7 from "February 12, 2023" to "February 12th, 2023" for consistency.
Date format for version 1.41.0 from "Oct 22th, 2024" to "Oct 22nd, 2024" for consistency.
Reason: Standardized date formatting across the changelog to improve readability and maintain consistency.
=> Spelling and Date Format Corrections

tokio/Cargo.toml, tokio/src/signal/unix.rs, tokio/tests/signal_realtime.rs, tokio/tests/support/signal.rs
Completing the work started in #6995 -- the `SIGRTMIN` and `SIGRTMAX` APIs were added for illumos in libc 0.2.168. They were also added for Solaris, but out of caution I don't want to turn this on until someone verifies that realtime signals work as expected there.
Also added a test for realtime signals which can be used while porting to other platforms in the future. The test passes successfully on both Linux and illumos (tested locally).
=> signal: add support for realtime signals on illumos

tokio-util/src/codec/mod.rs
fixing a typo in API documentation
=> codec: fix typo in API documentation

tokio/src/sync/once_cell.rs
Just fixing a couple of typos in `OnceCell`
N/A
=> fix: A couple of typos in `once_cell.rs`

.github/workflows/ci.yml, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/socket.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/stream.rs, tokio/src/process/mod.rs, tokio/src/runtime/runtime.rs
This PR ran doc test with miri in CI. Since doc test couldn't be run through ``cargo miri nextest run``,  it needs to be run separately using ``cargo miri test``. There are 844 successful tests and 72 ignored tests in total. 
Happy new year! 🎉 
Tracked under #6812
=> Run doc tests with miri in ci

tokio/src/sync/watch.rs
I picked #7021 quite randomly and tried to Do The Thing™. The real motivation is that I'm getting started on Rust, want to contribute as I can (here and elsewhere), and learn async Rust. :slightly_smiling_face: 
Added the missing bit to the documentation, plus `Panics` (is it actually needed? no clue) and reworked the doctest.
=> sync: extend documentation for watch::Receiver::wait_for

tokio/src/net/unix/datagram/socket.rs
There is ``socketpair`` in miri, but ``SOCK_DGRAM`` is unsupported. 
Follow up of #7060
=> Fix typo in miri ignore comment

tokio/src/io/util/async_read_ext.rs
I was reading the docs for the method, and in its current state, it read to me as:
> No guarantees are provided about the contents of `buf` when this function is called, implementations cannot rely on [any] ~property~ [of] the contents of `buf` being `true`.
With the inline block formatting on *true*, it makes it seem that you must not rely on `buf` containing the value `true`.
Remove the inline block formatting on *true*, as we are not talking about the boolean value `true` in code.
=> Change `AsyncReadExt::read` docs formatting to clarify requirements

tokio/src/net/udp.rs
The `mio::net::UdpSocket` supports `peek` already, but `tokio::net::UdpSocket` is missing this method.
=> Add `UdpSocket::peek` method

tokio/src/io/read_buf.rs
The documentation for `ReadBuf::uninit` makes it seem as though the passed buffer _must_ be fully uninitialized; however it allows _any_ buffer, a subset of which is fully uninitialized memory.
Note this is more for people like me who are deficient in `unsafe` code; thus the original documentation is likely obvious for those who are well acquainted with `unsafe` code.
State the buffer _may_ be fully uninitialized.
=> Clarify ReadBuf::uninit allows initialized buffers as well

tokio/src/net/tcp/stream.rs
The buffer cannot be possible.
Make it clear that the last buffer that is read from by the method, may have only been partially read.
As a side note, does the method override the buffers' contents? If not, then "consumed" should be replaced with "written".
=> Fix ambiguity in `TcpStream::try_write_vectored` docs

tokio/src/loom/std/atomic_u16.rs, tokio/src/loom/std/atomic_u32.rs, tokio/src/loom/std/atomic_usize.rs
This should be okay now since https://github.com/rust-lang/rust/pull/128778 has been merged.
This reverts #6203 and #6179, and follows-up #6155.
cc @RalfJung
=> chore: use unsync loads for `unsync_load`

.github/workflows/ci.yml
The miri job is our slowest job. Split it into two jobs for parallelism.
cc @tiif
=> ci: split miri jobs into unit and integration tests

tokio/src/runtime/local_runtime/runtime.rs
- Fixes a missing link in the `LocalRuntime::block_on` docs
- Adds link to text that was probably intended to be a link.
=> docs: Fix LocalRuntime doc links

tokio/src/fs/file.rs, tokio/src/io/blocking.rs, tokio/src/io/stderr.rs, tokio/src/io/stdin.rs, tokio/src/io/stdout.rs, tokio/src/process/windows.rs
I've discovered that [`Buf::ensure_capacity_for`](https://github.com/tokio-rs/tokio/blob/970d880ceb473b222a9ddd4b35b934ca68cecb4a/tokio/src/io/blocking.rs#L230) is unsound because it uses `Vec::set_len` to grow the `Vec` past the init area. This violates the documented safety invariants of `Vec::set_len`, which say _The elements at `old_len..new_len` must be initialized_.
This can be tested very easily by adding `for &byte in &self.buf {}` after the `self.buf.set_len` call.
Have reads use the spare capacity of `buf` and `Vec::set_len` afterwards.
=> io: extend `Buf` length only after having read into it

tokio/src/runtime/builder.rs, tokio/src/runtime/metrics/histogram/h2_histogram.rs, tokio/tests/rt_unstable_metrics.rs
Based on feedback #6960, customers want more flexibility in histogram configuration. 
The main change here is allowing precision for an H2 Histgoram to go all the way down to zero—there is not fundamental reason this wasn't possible before, but typically H2 histograms stop at P=2.
I've also added another optimization that truncates the number of buckets based on the requested max_value. This can save space by truncating in the middle of a bucket group.
Along the way and in the process of adding more tests, I found a couple of bugs which are fixed here:
1. The `max_value` in LogHistogramBuilder wasn't precisely respected
2. The `max_value` computed by `LogHistogram` was actually incorrect for some n/p combinations. The new version precisely considers bucket layout instead.
=> metrics: Improve flexibility of H2Histogram Configuration

tokio-macros/CHANGELOG.md, tokio-macros/Cargo.toml, tokio/Cargo.toml
- macros: suppress `clippy::needless_return` in `#[tokio::main]` ([#6874])
[#6874]: https://github.com/tokio-rs/tokio/pull/6874
=> chore: prepare tokio-macros v2.5.0

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- net: add `UdpSocket::peek` methods ([#7068])
- net: add support for Haiku OS ([#7042])
- process: add `Command::into_std()` ([#7014])
- signal: add `SignalKind::info` on illumos ([#6995])
- signal: add support for realtime signals on illumos ([#7029])
- io: don't call `set_len` before initializing vector in `Blocking` ([#7054])
- macros: suppress `clippy::needless_return` in `#[tokio::main]` ([#6874])
- runtime: fix thread parking on WebAssembly ([#7041])
- chore: use unsync loads for `unsync_load` ([#7073])
- io: use `Buf::put_bytes` in `Repeat` read impl ([#7055])
- task: drop the join waker of a task eagerly ([#6986])
- metrics: improve flexibility of H2Histogram Configuration ([#6963])
- taskdump: add accessor methods for backtrace ([#6975])
- io: clarify `ReadBuf::uninit` allows …
=> chore: prepare Tokio v1.43.0

.github/workflows/ci.yml
CI is failing:
```
Run cargo wasi test --test rt_yield --features wasi-rt
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not support target 'wasm32-wasi'; did you mean 'wasm32-wasip1'?
note: you can see a list of supported targets with `rustc --print=target-list`
note: if you are adding support for a new target to rustc itself, see https://rustc-dev-guide.rust-lang.org/building/new-target.html
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
1: rustup::toolchain::distributable::DistributableToolchain::add_component
2: rustup::cli::rustup_mode::target_add
3: rustup::cli::rustup_mode::main
4: rustup_init::main
5: std::sys_common::backtrace::__rust_begin_short_backtrace
6: main
7: <unknown>
8: __libc_start_main
9: <unknown>
error: failed to …
```
=> ci: fix ci error about wasm32-wasip1

tokio/src/process/mod.rs
=> process: add `Command::get_kill_on_drop()`

tokio/src/sync/broadcast.rs
The test's previous iteration could sometimes flake since we didn't await the completion of the first task. Since the tasks only existed to `move` the relevant `rx`'s in, to force a drop, we can omit them entirely and drop the `rx`s via `drop()`. This prevents any scheduling-related flakes.
=> sync: fix sync::broadcast::Sender<T>::closed() doctest

tokio/src/sync/mpsc/chan.rs, tokio/tests/sync_mpsc.rs
This PR updates the `mpsc` to handle panics during the `drop`. Specifically, the `chan::Rx` will continue executing its `drop` even if a panic occurs during the `drop`.
Although this scenario is expected to be rare, there could be edge cases, for example:
* On thread1, [`chan::Rx`](https://github.com/tokio-rs/tokio/blob/435e39001b04f5846d1e9db1b243e6b81982f654/tokio/src/sync/mpsc/chan.rs#L485-L499) is dropped
* On thread1, panic occurs in the middle of the drop
* On thread2, [`chan::Chan`](https://github.com/tokio-rs/tokio/blob/435e39001b04f5846d1e9db1b243e6b81982f654/tokio/src/sync/mpsc/chan.rs#L529-L542) is dropped (resuming from the interrupted element)
* On thread2, panic occurs in the middle of the drop (no double panic since it's in a different thread)
* The program continues with …
=> sync: handle panic during mpsc drop

tokio/src/runtime/io/registration_set.rs
This PR contains a minor clean up regarding the magic number `16` in relation to the `pending_release` buffer capacity.
=> runtime: clean up magic number usage

tests-build/tests/fail/macros_type_mismatch.rs, tests-build/tests/fail/macros_type_mismatch.stderr
When a `?` operator is used in a tokio entry point function (wrapped in
`#[tokio::main]`), which has a Option or Result return type, but where
the function does not actually return that type correctly, currently the
compiler returns two errors instead of just one. The first of which is
incorrect and only exists due to the macro expanding to an async block.
```
cannot use the `?` operator in an async block that returns `()`
```
This commit is a characterization test for this behavior to help show
when it's fixed (or even changed for better / worse)
Annoyed by incorrect error message. "cannot use the `?` operator in an async block that returns `()`". More specifically, when editing code in ways that break the code (by changing return values, or changing the order of things, seeing error …
=> macros: characterization tests for ? operator fail

tokio/src/doc/mod.rs
This PR fixes the warnings that happen when building the docs.
=> docs: fix warnings when building the docs

tokio/src/runtime/dump.rs, tokio/src/runtime/handle.rs, tokio/src/runtime/task/trace/mod.rs, tokio/tests/task_trace_self.rs
There is some desire to make it possible for tasks to trace themselves to discover slow wakeups, something similar to the test I added.
This PR makes some functions public (but unstable) to make that easier.
I currently shared it with someone I'm working with to see whether it helps them debug their "slow task" problems. I'll make this PR less WIP after I get feedback from them.
WIP: actually add docs.
=> make tracing a task public so self-tracing is possible

tokio-util/src/io/sync_bridge.rs
When interacting with resources wrapped in a `SyncIoBridge`, it might be handy to interact with the inner resource.
Implement `get_ref` and `get_mut` on `SyncIoBridge`.
=> io: implemented `get_ref` and `get_mut` for `SyncIoBridge`

tokio/src/fs/file.rs, tokio/tests/fs_file.rs
=> fs: empty reads on File should not start a background read

tokio/src/fs/hard_link.rs, tokio/src/fs/symlink.rs, tokio/src/fs/symlink_dir.rs, tokio/src/fs/symlink_file.rs
Using `src` and `dst` as parameter names in the context of symlinks is confusing, especially in their order.
I usually think from left to right: a symlink points to a target. 
So I assumed that `src` would point to `dst`, but that isn’t the case here.
Align to the standard library and use `original` and `link` as the parameter names.
=> fs: align symlink parameter names with std

tokio/src/process/mod.rs
=> process: add example for reading `Child` stdout

tokio/src/net/udp.rs
Resolves https://github.com/tokio-rs/tokio/issues/7145.
For consistency with std's [`send_to`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.send_to), this PR renames the argument from `target` to `addr` instead of updating the docs.
=> net: rename the argument for `send_to`

tokio/src/process/mod.rs
- there's no good reason to my knowledge to return error in kill of killed process
- `start_kill` is often used in cleanup, which may happen after wait, so better not error there
- this matches behavior of std `Child::kill`
- [decision by libs team](https://github.com/rust-lang/rust/issues/112423#issuecomment-1589851902)
=> Ok on Child::start_kill after wait

tokio/src/lib.rs
Promote the "Feature flags" and "Supported platforms" sections out from under "Examples", as they are not examples. Adjust their subsections accordingly. Expose these subsections via navigation sidebar.
I believe the documentation subheadings under "Examples" might have been nested by mistake. It seems like they were meant to follow "Examples", and I suspect that no one noticed this mistake because the default page styling makes the nesting structure hard to see.
This matters for at least two reasons:
1. Accessibility, e.g. to users of screen readers.
2. The "Sections" navigation menu in the sidebar only renders `#` and `##` headings. The headings "Unstable features", "`WASM` support", and "Unstable `WASM` support" are absent from this menu, and I believe they were meant to be present. …
=> docs: fix nesting of next sections under examples

tokio/src/sync/oneshot.rs, tokio/tests/sync_oneshot.rs
this commit introduces a new method to `tokio::sync::oneshot::Receiver<T>`.
broadly speaking, users of the oneshot channel are encouraged to `.await` the `Receiver<T>` directly, as it will only yield a single value.
users implementing their own `std::future::Future`s directly may instead poll the receiver via `<Receiver<T> as Future<Output = Result<T, RecvError>::poll(..)`. note that the contract of `Future::poll()` states that clients should not poll a future after it has yielded `Poll::Ready(value)`.
this commit provides a way to inspect the state of a receiver, to avoid violating the contact of `Future::poll(..)`, or requiring that a oneshot channel users track this state themselves externally via mechanisms like `futures::future::FusedFuture`, or wrapping the receiver in an …
=> sync: `oneshot::Receiver::is_terminated()`

tokio/src/sync/oneshot.rs, tokio/tests/sync_oneshot.rs
this commit introduces a new method to `tokio::sync::oneshot::Receiver<T>`.
this method returns true if the channel has no messages waiting to be received. this is similar to the existing `tokio::sync::mpsc::Receiver::is_empty()` and `tokio::sync::broadcast::Receiver::is_empty()` methods.
see:
* https://docs.rs/tokio/latest/tokio/sync/broadcast/struct.Receiver.html#method.is_empty
* https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Receiver.html#method.is_empty
* https://github.com/tokio-rs/tokio/pull/7137#discussion_r1940242052
=> sync: `oneshot::Receiver::is_empty()`

tokio/src/io/util/mem.rs
Swap the `reader` and `writer` in the `simplex` documentation test to match the API.
Fixes: #7175
Fixes the [doctest for simplex](https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/util/mem.rs#L185-L209) as discussed in #7175 i.e. the `reader` and `writer` being swapped.
Simple fix for this one - just swap the variables names to match their type in the destructuring.
=> docs(io): swap reader/writer in simplex doc test

tokio-util/Cargo.toml, tokio-util/src/io/mod.rs, tokio-util/src/io/read_arc.rs
This encapsulates a common bit of unsafety.
---
Inspired by having an otherwise completely safe crate in which this was the
only bit of unsafe code. Reading into an uninitialized `Arc` and then
initializing it requires the unsafe `assume_init`.
https://github.com/tokio-rs/tokio/issues/7127
=> Add `tokio_util::io::read_exact_arc` to safely read a new uninitialized `Arc`

tokio/src/runtime/builder.rs
The builder parameter `core_threads` was renamed to `worker_threads` but it wasn't consistently renamed inside the code, what might be confusing.
Renamed `core_threads` local variables to `worker_threads` in `builder.rs`.
=> Consistently use worker_threads instead of core_threads

tokio-util/src/codec/any_delimiter_codec.rs
reserve enough capacity for `chunk` and `self.sequence_writer`
related issue: #7169
=> util: optimize buffer reserve for AnyDelimiterCodec::encode

README.md, tokio/README.md
=> Make 1.43 the next LTS

tokio/src/process/mod.rs
=> docs: fix grammar of the `ChildStdin` struct doc comment

Cargo.toml, tokio/src/net/tcp/listener.rs, tokio/src/net/tcp/stream.rs, tokio/src/net/udp.rs, tokio/src/net/unix/datagram/socket.rs, tokio/src/net/unix/listener.rs, tokio/src/net/unix/stream.rs, tokio/src/util/blocking_check.rs, tokio/src/util/mod.rs, tokio/tests/io_driver.rs, tokio/tests/io_driver_drop.rs, tokio/tests/no_rt.rs, tokio/tests/tcp_peek.rs
See #5595 and #7172.
This adds a debug assertion that checks that a supplied underlying std socket is set to nonblocking mode when constructing a tokio socket object from such an object.
This only works on unix.
=> net: debug_assert on creating a tokio socket from a blocking one

tokio/src/process/mod.rs
```
Child::kill       == std Child::kill + Child::wait
Child::start_kill == std Child::kill
```
As a side note, kill that also waits, is convenient, but also
dangerous, because `wait` may hang in certain cases (NFS, ptrace,
etc).  And different behavior between std and tokio may leads to
bugs when code is mechanically converted from one to another.  Better
name name of this function might be `kill_and_wait`.
CC @maminrayej
=> Clarify Child::kill behavior

.github/workflows/loom.yml
Enable printing in multi-threaded loom tests, as [other tests do](https://github.com/tokio-rs/tokio/blob/e076d21f679a35ae2697165d46d111285d09e3b4/.github/workflows/loom.yml#L71).
=> ci: enable printing in multi thread loom tests

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release changes the `from_std` method on sockets to panic if a blocking socket is provided. We determined this change is not a breaking change as Tokio is not intended to operate using blocking sockets. Doing so results in runtime hangs and should be considered a bug. Accidentally passing a blocking socket to Tokio is one of the most common user mistakes. If this change causes an issue for you, please comment on [#7172].
- coop: add `task::coop` module ([#7116])
- process: add `Command::get_kill_on_drop()` ([#7086])
- sync: add `broadcast::Sender::closed` ([#6685], [#7090])
- sync: add `broadcast::WeakSender` ([#7100])
- sync: add `oneshot::Receiver::is_empty()` ([#7153])
- sync: add `oneshot::Receiver::is_terminated()` ([#7152])
- fs: empty reads on `File` should not start a …
=> chore: prepare Tokio v1.44.0

tokio-util/src/sync/cancellation_token.rs, tokio-util/tests/sync_cancellation_token.rs
Pretty natural addition to match the `cancelled_owned` fn.
```rust
let token = CancellationToken::new();
tokio::spawn(token.run_until_cancelled(my_async_fn())); // doesn't compile
tokio::spawn(async move { // current workaround
token.run_until_cancelled(my_async_fn())).await
});
tokio::spawn(token.run_until_cancelled_owned(my_async_fn())); // compiles, looks nicer
```
Just a carbon copy of the existing fn switching to the appropriate cancellation future.
=> sync: add `CancellationToken::run_until_cancelled_owned`

tokio/src/io/async_buf_read.rs, tokio/src/io/async_read.rs, tokio/src/io/async_seek.rs, tokio/src/io/async_write.rs, tokio/src/util/mod.rs
These bound are not necessary.
=> Do not require `Unpin` for some trait impls

tokio-test/src/io.rs
Introduce `tokio_test::io::Builder::name` to configure name of the mock object, to include in panic messages.
Also show number of remaining actions or action index in some cases to help debugging failed tests.
When using `tokio_test::io::Mock`, it is tricky to debug problems, especially if multiple mocks are used. For example, if it panics with "unexpected write", it is hard to determine which of the mock objects faced the unexpected write and at what position of the scenario.
`Builder` gained `name` method to set make `Mock` remember a string.
Panic messages are adjusted to include that name (if set), also some additional information (like the number of remaining actions) to aid hack-try-print-repeat-based debugging sessions.
Before:
unexpected write
After:
unexpected write (name …
=> test: Helpful panic messages for tokio_test::io

tokio-test/Cargo.toml
I think these dependencies are no longer used in `tokio-test`.
=> test: remove unused dependencies

tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/tests/rt_handle_block_on.rs, tokio/tests/rt_threaded.rs
The defer queue is not drained while in a `block_in_place` context. Pushing tasks to the defer
queue in this state could lead to a deadlock.
Fixes: #7209, #7210
=> rt: skip defer queue in `block_in_place` context

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- rt: skip defer queue in `block_in_place` context ([#7216])
[#7216]: https://github.com/tokio-rs/tokio/pull/7216
=> chore: prepare Tokio v1.44.1

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/scheduler/multi_thread/worker.rs, tokio/tests/rt_handle_block_on.rs, tokio/tests/rt_threaded.rs
This merges the tokio-1.44.x branch back into the master branch.
Since this is a merge commit, it must be merged from the command line. Do not use the github ui.
=> Merge 1.44.1

tokio-util/CHANGELOG.md
- io: add `get_ref` and `get_mut` for `SyncIoBridge` ([#7128])
- io: add `read_exact_arc` ([#7165])
- sync: add `CancellationToken::run_until_cancelled_owned` ([#7081])
- codec: optimize buffer reserve for `AnyDelimiterCodec::encode` ([#7188])
- either: enable `Either` to use underlying `AsyncWrite` implementation ([#7025])
- codec: fix typo in API docs ([#7044])
- util: fix example in `StreamReader` docs ([#7167])
- io: add docs for `SyncIoBridge` with examples and alternatives ([#6815])
- io: clean up buffer casts ([#7142])
- task: run `spawn_pinned` tests with miri ([#7023])
[#6815]: https://github.com/tokio-rs/tokio/pull/6815
[#7023]: https://github.com/tokio-rs/tokio/pull/7023
[#7025]: https://github.com/tokio-rs/tokio/pull/7025
[#7044]: https://github.com/tokio-rs/tokio/pull/7044 …
=> chore: prepare tokio-util v0.7.14

tokio-util/src/task/task_tracker.rs
Makes clear that TaskTracker doesn't abort its tasks on Drop
Fixes: #7222
=> util: explicitly state that TaskTracker does not abort tasks on Drop

tokio-stream/src/pending.rs, tokio/src/runtime/scheduler/inject/rt_multi_thread.rs, tokio/src/util/metric_atomics.rs
remove redundant words in comment
=> chore: remove redundant words in comment

.cirrus.yml, .github/workflows/ci.yml, Cargo.toml, README.md, examples/Cargo.toml, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/tests/queue.rs, tokio/src/sync/broadcast.rs
Forward ports https://github.com/tokio-rs/tokio/pull/7232 to 1.43.x
=> chore: forward port 1.38.x

.github/workflows/ci.yml, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/tests/queue.rs, tokio/src/sync/broadcast.rs
Forward ports https://github.com/tokio-rs/tokio/pull/7232 to 1.44.x
=> chore: forward port 1.43.x

.github/workflows/ci.yml, README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/runtime/tests/queue.rs, tokio/src/sync/broadcast.rs
Forward ports https://github.com/tokio-rs/tokio/pull/7232 to 1.44.x
Note: this PR should be merged in manually to master and not squashed using the PR interface.
=> chore: forward port 1.44.x

tokio/Cargo.toml
This eliminates a duplicate dependency on mio
To develop tokio without building two versions of mio
Use the latest version of mio-aio
=> Update mio-aio dev dependency to 1.0

.cirrus.yml, .github/workflows/ci.yml, Cargo.toml, README.md, examples/Cargo.toml, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md, tokio/src/sync/broadcast.rs
I'm having some trouble importing the fix for [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023.html) into Android due to the libc bump that happened in 1.43.0. Thus, make an additional backport of this fix to the 1.42.x series.
Please see #7232 for more info.
=> Backport #7232 to 1.42.x

tokio/CHANGELOG.md
The release date is april 8th, not 7th.
=> Fix release date of Tokio v1.41.1

tokio/CHANGELOG.md
This merges the history of tokio-1.42.x with the release of v1.42.1 into tokio-1.43.x.
This must be merged with the command-line, and must be merged after #7244.
=> Merge 1.42.1 into 1.43.x

tokio/CHANGELOG.md
This must be merged with the command-line, and must be merged after https://github.com/tokio-rs/tokio/pull/7247.
=> Tokio 1.44.2 fix release date

tokio/src/runtime/handle.rs
This type is used internally by the `Runtime`, which is already marked unwind-safe. This allows using types that contain one or more `Handle`s with the `catch_unwind` function without resorting to `AssertUnwindSafe`.
Related to #4657
=> Mark runtime::Handle as unwind-safe

benches/spawn.rs
Other benchmarks build the runtime via the use of helper functions (for example `benches/sync_semaphore.rs` and `benches/fs.rs`). We could reduce duplicate code by doing the same in `benches/spawn.rs`.
This PR adds helper functions for building single and multi-threaded runtimes in `benches/spawn.rs`.
=> Benches: Add Helper Functions for Building Runtimes to `benches/spawn.rs`

tokio-util/src/task/join_map.rs, tokio-util/tests/task_join_map.rs
#7257. Duplicate map keys abort the original task, but no special handling was taken during `join_next`, such that these aborted tasks would return `None`, even though the join map wasn't empty.
Loop if the task ID is not being tracked in this `JoinMap`.
=> fix #7257 by ignoring tasks with missing map keys

spellcheck.dic, tokio/src/process/mod.rs, tokio/src/process/unix/mod.rs, tokio/src/process/windows.rs
#7238: under Windows, the spawn sometimes has to be configured in a specific way in order to achieve a specific behavior or to stay compatible with some other API. In our case, it is about spawning child processes as PPL when the parent (Rust) process currently runs as PPL.
In the standard library, it is currently supported through the nightly-only [`windows_process_extensions_raw_attribute`](https://doc.rust-lang.org/unstable-book/library-features/windows-process-extensions-raw-attribute.html) feature. It was previously implemented by configuring the `Command` object using its [`raw_attribute`](https://doc.rust-lang.org/1.84.0/std/os/windows/process/trait.CommandExt.html#tymethod.raw_attribute) extension method and then the regular …
=> Feat(process): Implement `Command::spawn_with`

tokio/Cargo.toml, tokio/src/fs/mocks.rs
This eliminates a duplicate dependency on syn
Building mockall-0.11 required tokio to build both syn-1 and syn-2
Update the mockall dev dependency to the latest version.
=> Update the mockall dev dependency to 0.13.0

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- task: properly handle removed entries in `JoinMap` ([#7264])
- deps: update hashbrown to 0.15 ([#7219])
- task: explicitly state that `TaskTracker` does not abort tasks on Drop ([#7223])
[#7219]: https://github.com/tokio-rs/tokio/pull/7219
[#7223]: https://github.com/tokio-rs/tokio/pull/7223
[#7264]: https://github.com/tokio-rs/tokio/pull/7264
=> chore: prepare tokio-util v0.7.15

tokio/src/runtime/metrics/batch.rs, tokio/src/runtime/metrics/runtime.rs, tokio/src/runtime/metrics/worker.rs, tokio/tests/rt_metrics.rs, tokio/tests/rt_unstable_metrics.rs
Further to #6899 , this PR further stabilises 2 more API `worker_unpark_count` and `worker_park_count`.
Move the API impl out of tokio_unstable flag
Ref: https://github.com/tokio-rs/tokio/issues/6546
=> Stabilize worker_park_count and worker_unpark_count

tokio-util/src/compat.rs, tokio-util/src/lib.rs
[Click to view rendered documentation](https://deploy-preview-7279--tokio-rs.netlify.app/tokio_util/compat/index.html)
This PR addresses [tokio-rs/tokio#2775](https://github.com/tokio-rs/tokio/issues/2775), which requested improved documentation and discoverability for the compat I/O layer in tokio-util.
Add and enhance documentation for the `compat` module:
- In `tokio-util/src/lib.rs`  
Add a brief summary and a direct link to the `compat` module docs.
- In `tokio-util/src/compat.rs`  
- Add a detailed explanation of the compatibility layer.  
- Include a compatibility trait matrix.  
Included practical examples:
- Tokio → Futures: Using TcpStream with futures::io::AsyncReadExt.
- Futures → Tokio: Using Cursor with tokio::io::AsyncReadExt.
This is a documentation-only update.
Latest: …
=> docs: Improved docs & examples for ` tokio_util::compat`

tokio/src/time/sleep.rs, tokio/tests/time_sleep.rs
This commit updates the tokio::time::sleep documentation to remove the outdated maximum sleep duration.
This fixes #7301.
=> Update tokio::time::sleep documentation to reflect maximum sleep

.github/workflows/ci.yml
GitHub Actions now supports AArch64 Windows runner (`windows-11-arm`) as public preview
https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
https://github.com/actions/partner-runner-images
Closes #2985
=> ci: Test AArch64 Windows

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- metrics: stabilize `worker_total_busy_duration`, `worker_park_count`, and
`worker_unpark_count` ([#6899], [#7276])
- process: add `Command::spawn_with` ([#7249])
- io: do not require `Unpin` for some trait impls ([#7204])
- rt: mark `runtime::Handle` as unwind safe ([#7230])
- time: revert internal sharding implementation ([#7226])
- rt: remove alt multi-threaded runtime ([#7275])
[#6899]: https://github.com/tokio-rs/tokio/pull/6899
[#7276]: https://github.com/tokio-rs/tokio/pull/7276
[#7249]: https://github.com/tokio-rs/tokio/pull/7249
[#7204]: https://github.com/tokio-rs/tokio/pull/7204
[#7230]: https://github.com/tokio-rs/tokio/pull/7230
[#7226]: https://github.com/tokio-rs/tokio/pull/7226
[#7275]: https://github.com/tokio-rs/tokio/pull/7275
=> chore: prepare Tokio v1.45.0 release

tokio/src/time/clock.rs
This PR just basically removes a dead code, it should not change any functionality, and also no actual performance impact.
https://github.com/tokio-rs/tokio/blob/bdd64cc9d3561115d125584484404e9d1f7d7cca/tokio/src/time/clock.rs#L253-L257
This drop is no longer necessary.
This drop was firstly introduced by #3289 and the next line invokes `panic!`.
In #5434, the original `panic!` was replaced with `return Err`, so dropping it explicitly is no longer necessary.
I didn't face any real issue of this dead code, it just confused me while reading the source.
=> time: remove outdated explicit `drop` call of `Mutex`

tests-build/tests/fail/macros_type_mismatch.stderr
The 1.87 release changed some error messages.
=> Update macros_type_mismatch for Rust 1.87.0

tokio/src/net/tcp/socket.rs
When I read the document of method "recv_buffer_size" I found this issue that this method shoud associate to "set_recv_buffer_size" not "set_send_buffer_size", so I think there is a describtion problem.
change "set_send_buffer_size" -> "set_recv_buffer_size" description that in recv_buffer_size method document
=> docs: socket.rs document of method recv_buffer_size

tokio/src/runtime/builder.rs, tokio/src/runtime/local_runtime/options.rs, tokio/src/runtime/local_runtime/runtime.rs, tokio/tests/async_send_sync.rs, tokio/tests/rt_local.rs
I went through the `LocalRuntime` code and noticed some improvements.
Ref: #6739
=> runtime: various minor `LocalRuntime` improvements

tokio/src/runtime/scheduler/multi_thread/queue.rs
<del>*Blocked by #7339 which fixes the CI failures caused by the new compilation error message of the new stable toolchain.*</del>
`queue::Local<T>` is never been send to another thread (except while shutting down), the `tail` is only updated by the worker thread who owned this local queue, so any change to `tail` is immediately visible to the current thread.
This means the `Acquire` ordering is not required for loading `tail` while operating on the local queue.
Since the lfence is not required for this scenario, the atomic loading was replaced by simple pointer deref.
Because of the following reasons:
* All method on the `Inner<T>` can be implemented in differently way for `Local<T>` and `Steal<T>`
* Adding method like `len_local` or `unsync_len` creates possibilities for incorrect usage …
=> runtime: eliminate unnecessary lfence while operating on `queue::Local<T>`

tokio/src/runtime/time/entry.rs
This PR eliminates the unnecessary `UnsafeCell`  to tighten the risky area.
```bash
$ cargo bench --bench time_timeout
```
I ran the benchmark multiple times and the results were often conflicting, sometimes regressing and sometimes not.
Given that the time scale of the benchmark is in the 10ns range, I don't think this change has a significant performance impact.
`UnsafeCell` always expose the risk of data race, which brings extra mental burden while reading the source.
I drew a complicated flowchart to check data races.
After finish the above chart, I think the `UnsafeCell` is not needed for the current design of timer,
so I opened this PR to make it looks like more safe, and make it more convenient for others.
By the way, the following `unsafe` can also be eliminated by `pin_project`. …
=> time: eliminate `UnsafeCell` around the `TimerShared`

tokio/src/net/tcp/stream.rs, tokio/src/runtime/builder.rs, tokio/src/runtime/metrics/batch.rs, tokio/tests/tcp_shutdown.rs
Fix for https://github.com/tokio-rs/tokio/issues/7319
Time is generally unsupported in WASM. Fix involves removing Instant from metrics handling when WASM is the target family and tokio's time feature is not enabled.
NOTES:
Will iterate with a test to catch this in the future.
=> rt: do not track time-based metrics on wasm32-unknown-unknown

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This fixes a regression on the wasm32-unknown-unknown target, where code that previously did not panic due to calls to `Instant::now()` started failing. This is due to the stabilization of the first time-based metric.
- Disable time-based metrics on wasm32-unknown-unknown ([#7322])
[#7322]: https://github.com/tokio-rs/tokio/pull/7322
=> chore: prepare Tokio v1.45.1

tokio-test/src/task.rs, tokio/src/runtime/park.rs, tokio/src/util/mod.rs, tokio/src/util/wake.rs
Replaces some `RawWakerVTable` instances with `Wake`.
=> chore: use `Wake` more

benches/Cargo.toml, benches/copy.rs, benches/sync_broadcast.rs, benches/sync_watch.rs, examples/Cargo.toml, stress-test/Cargo.toml, tokio/Cargo.toml, tokio/tests/sync_broadcast.rs, tokio/tests/time_pause.rs
Migrate from 0.8.5 to 0.9.1, fix resulting build warnings.
=> Update rand crate to latest version

tokio/src/runtime/local_runtime/runtime.rs, tokio/src/runtime/runtime.rs, tokio/src/runtime/time/entry.rs, tokio/src/runtime/time/mod.rs, tokio/src/runtime/time/tests/mod.rs
Just a few minor improvements while reading the source.
*It would be convenient to enable the 'Hide whitespace' in diff view.*
These `clippy` attributes were introduced by #6808 and it looks like they were forgotten to be removed before merging into master.
***
Follow-up of #7329.
Usually, the `Pin::get_unchecked_mut` can be replaced with `pin_project`, this reduce the unsafe area without sacrificing readability and performance.
*Note: The `#[doc = "..."]` attributes have been replaced with `//` due to the limitation of `pin_project_lite` (ref: https://github.com/taiki-e/pin-project-lite/issues/41).*
***
These comments were introduced by the [initial commit](https://github.com/tokio-rs/tokio/commit/f052f85315936a685f36c99dbceae0de541e0e4e) of #3080, but not be removed in the final version …
=> time&runtime: cumulative minor improvements

.github/workflows/ci.yml, tokio/tests/io_async_fd.rs, tokio/tests/net_unix_pipe.rs
Miri supported ``fcntl`` in https://github.com/rust-lang/miri/issues/4119.
This PR enables tests that use ``fcntl``, and update the rustc version needed for miri to run the tests in CI.
=> Enable some tests to test with miri

tokio/src/sync/mpsc/bounded.rs
Because `OwnedPermit`s can be passed around separate from the `Sender`s they came from,
it can be useful to be able to check that a value sent on one will go to the intended receiver.
There's currently no way to get a reference to, or clone of, the `Sender` from an `OwnedPermit` without sending a message or releasing it, so calling [`Sender::same_channel()`](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.same_channel) from an `OwnedPermit` is impossible.
For context, I'm trying to create an implementation of [`quinn::AsyncUdpSocket`](https://docs.rs/quinn/latest/quinn/trait.AsyncUdpSocket.html) backed by channels to support external transports in a project.
`AsyncUdpSocket::try_send()` just immediately forwards to `Sender::try_send()` and returns `WouldBlock` when …
=> sync: add `same_channel` analogue to `OwnedPermit`

Cargo.toml, tokio/src/net/tcp/socket.rs, tokio/src/net/unix/ucred.rs
Based on https://github.com/tokio-rs/mio/pull/1871
=> net: add cygwin support

benches/Cargo.toml, benches/fs.rs, benches/signal.rs
`#![cfg(unix)]` creates an empty files for non-unix targets, causing rust to complain about a missing `fn main`, but now these benches are instead disabled.
=> benches: properly gate unix benches

tokio/tests/rt_handle_block_on.rs
This adds a regression test that would have caught the bug in #7396.
=> Add test that consumes park token during `block_on`

tokio-util/src/sync/cancellation_token.rs, tokio-util/src/sync/cancellation_token/guard_ref.rs, tokio-util/src/sync/mod.rs
Closes #7406
`CancellationToken::drop_guard()` requires cloning a new `CancellationToken` in most scenarios, which is actually unnecessary. Within the same scope, we can reference the `CancellationToken` in the scope and continue using it in subsequent code. This PR adds a `DropGuardRef` type that contains a borrow of the CancellationToken, thereby avoiding the clone action
like `DropGuard` but contains a reference of `CancellationToken`
```rust
#[derive(Debug)]
pub struct DropGuardRef<'a> {
pub(super) inner: Option<&'a CancellationToken>,
}
```
use `DropGuard`:
```rust
async fn do_some_work(cancel: CancellationToken) {
let _cancel = cancel.clone().drop_guard(); // <=== HERE
loop {
let Some(result) = cancel.run_until_cancelled(some_async_work()).await else {
break;
};
// do something with …
```
=> sync: add `DropGuardRef` for `CancellationToken`

tokio-util/src/sync/cancellation_token.rs, tokio-util/src/sync/cancellation_token/guard.rs, tokio-util/src/sync/cancellation_token/guard_ref.rs
Just found something in the documentation that could be improved.
* Replace `Cancel safety` with `Cancellation safety` to align the term used by [`tokio::select`](https://docs.rs/tokio/latest/tokio/macro.select.html)
* Add some [intra doc links](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html), this not only makes it easier to navigate through the web document, but also allows the IDE to generate better looking and useful hints.
=> sync: improve docs of `tokio_util::sync::CancellationToken`

tokio/src/net/tcp/socket.rs
Update the documentation link for [RawFd] in the TcpSocket docs to point to the correct and up-to-date location in the Rust standard library. This ensures that users are directed to the proper definition of RawFd when reading the documentation.
=> Fix documentation link for RawFd in TcpSocket docs

tokio/src/net/unix/pipe.rs, tokio/tests/net_unix_pipe.rs
I'd like to read from a fifo forever on Android. However, `OpenOptions.read_write()` isn't present on Android.
Tweaked the `cfg` to enable `read_write` on both Linux and Android.
I'm not sure if CI is set up for Android, but I enabled Android for the tests that I saw used read_write as well.
=> net: allow `pipe::OpenOptions::read_write` on Android

tokio/src/net/tcp/socket.rs
Replaced the outdated AsRawFd documentation URL (pointing to std/os/unix/io) with the current, canonical link (https://doc.rust-lang.org/std/os/fd/trait.AsRawFd.html) in the TcpSocket documentation. This ensures that users are directed to the correct and up-to-date Rust standard library documentation for the AsRawFd trait. No functional code changes were made.
=> Update AsRawFd documentation link to current Rust stdlib location

tokio/src/net/unix/socketaddr.rs
`tokio::net::unix::SocketAddr` wraps a `std::os::unix::net::SocketAddr`. The latter implements `Clone`, but the former does not. This can be a bit annoying for certain niche use cases, such as when we want to use the `tokio` version in relation to `axum::extract::connect_info::Connected`. More than that, it simply makes sense to `impl Clone` here if the wrapped inner is already `impl Clone`.
added a `#[derive(Clone)]`.
Closes https://github.com/tokio-rs/tokio/issues/7421.
=> impl Clone for net::unix::SocketAddr

tokio/src/runtime/handle.rs, tokio/src/runtime/scheduler/current_thread/mod.rs, tokio/src/runtime/scheduler/mod.rs, tokio/src/runtime/scheduler/multi_thread/handle.rs, tokio/src/runtime/task/harness.rs, tokio/src/runtime/task/mod.rs, tokio/src/runtime/task_hooks.rs, tokio/src/task/local.rs, tokio/src/task/spawn.rs, tokio/src/util/trace.rs, tokio/tests/task_hooks.rs
Unfortunately, due to an oversight on my part, the capturing of spawn
locations was only tested with the `Runtime::spawn` method, and *not*
with `tokio::spawn`/`tokio::task::spawn`, which is how most tasks are
spawned in Real Life. And, it turned out that because this was not
tested...well, it was broken. Agh. My bad.
Although the whole call chain for spawning tasks using `tokio::spawn`
was correctly annotated with `#[track_caller]`, the location wasn't
propagated correctly because of the `context::with_current(|handle| {
... })` closure that accesses the current runtime. Because the call to
spawn the task occurs inside a closure, the *closure*'s location is
captured instead of the caller. This means any task spawned by
`tokio::spawn` records its location as being in …
=> runtime(unstable): fix task hook spawn locations for `tokio::spawn`

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
This release fixes incorrect spawn locations in runtime task hooks for tasks spawned using `tokio::spawn` rather than `Runtime::spawn`. This issue only effected the spawn location in `TaskMeta::spawned_at`, and did not effect task locations in Tracing events.
- runtime: add `TaskMeta::spawn_location` tracking where a task was spawned ([#7440])
[#7440]: https://github.com/tokio-rs/tokio/pull/7440
=> chore: prepare to release v1.46.1

tokio/src/sync/task/atomic_waker.rs, tokio/src/sync/tests/atomic_waker.rs
The `AtomicWaker` does a read-modify-write operation to release its lock on the state, but this is not necessary.
The only other place `state` can be modified concurrently is through another `fetch_or(WAKING)` in `fn take` (a no-op since the state is already `WAKING`), or through a `compare_exchange(WAITING, REGISTERING)` in `fn register`, however this will always fail as we are currently in `WAKING`. Thus we know with 100% certainty the state is `WAKING` and will remain so, so the `fetch_and(!WAKING)` is equivalent to just storing `WAITING`.
One other reason one might use a read-modify-write operation instead of a simple store is if one is also `Acquire`ing. But here we only use `Release`, so the read portion of the atomic operation is entirely unnecessary.
~~I changed the release  of …
=> sync: improve AtomicWaker::wake performance

tokio/Cargo.toml, tokio/src/task/coop/mod.rs, tokio/tests/async_send_sync.rs
In systems that use the Tokio runtime, it can be useful to integrate non-Tokio resources with the Tokio task budget. This makes it easier to ensure all tasks yield sufficiently. Currently only `consume_budget` is available, but this is impractical when trying to make certain types like `Future` or `Stream` participate in cooperative scheduling.
Closes #7403
Make the existing `cooperative` and `poll_proceed` methods public.
Clarify the documentation of `poll_proceed`.
=> Make cooperative and poll_proceed public

.github/workflows/ci.yml
The upstream issue causing crashes (https://github.com/rust-lang/rust/issues/135867) has been fixed.
=> ci: use ubuntu-24.04-arm instead of ubuntu-22.04-arm

tokio-util/Cargo.toml, tokio-util/src/task/join_map.rs, tokio-util/tests/task_join_map.rs
While rebasing #7075, I noticed the change from #7219 which updates hashbrown, requiring the addition of the `raw-entry` feature. That inspired me to take a look at the actual JoinMap impl and I thought it could be improved by using `HashTable` instead.
Replacing the `tasks_by_key` map with a `HashTable`, we unlock a few benefits:
1. When searching by ID, we don't need to store the id in `tasks_by_key`, since we can fetch the ID from the `AbortHandle`.
2. We don't need to duplicate the `S: BuildHasher`, as we are in-control over the hash-function, we can fetch the existing hasher from `hashes_by_task`.
However, removing the ID from `tasks_by_key` will slow down those lookups (only in `join_next()`), as they now need a vtable lookup, rather than comparing against the id already in the …
=> (tokio-util JoinMap) Remove raw-entry feature in favour of HashTable API.

tokio/CHANGELOG.md
Corrects the pull request reference from #7148 to #7418 in the tokio changelog entry.
The CHANGELOG.md in the tokio crate contains an incorrect PR reference. It currently shows #7148 but should reference #7418. This is a simple documentation fix to ensure the changelog accurately links to the correct pull request.
Changed the PR number from #7148 to #7418 in the tokio/CHANGELOG.md file.
=> changelog: fix incorrect PR number for 1.47.0

tokio/src/sync/set_once.rs
The link to Python's asyncio.Event documentation was pointing to asyncio-event.html which doesn't exist. This corrects it to the proper URL at asyncio-sync.html#asyncio.Event as mentioned in PR #7418.
The documentation contains a broken link to Python's asyncio.Event documentation. 
The current link points to `https://docs.python.org/3/library/asyncio-event.html` 
which returns a 404 error. 
PR #7418 mentioned the correct URL should be 
`https://docs.python.org/3/library/asyncio-sync.html#asyncio.Event`.
Updated the documentation link from the non-existent `asyncio-event.html` to 
the correct `asyncio-sync.html#asyncio.Event`.
=> sync: fix broken link of Python `asyncio.Event` in `SetOnce` docs

tokio/src/runtime/metrics/runtime.rs
https://github.com/tokio-rs/tokio/pull/7449 fixed the generated cfg gates in our rustdocs for runtime metrics. In the interest of reviewability, we avoided reordering the metric methods. 
However this resulted in interwoven groups of cfg-gates and multiple macro declarations per each. This hurts maintainability and readability.
I reorganized the module to group all like-gated methods together.
=> chore(runtime): reorder metrics to be grouped by cfg-gates

spellcheck.dic, tokio/src/net/unix/socketaddr.rs
This adds a Linux-specific `SocketAddr::as_abstract_name()` based on stdlib `SocketAddrExt` trait .
The current MSRV is already 1.70.0, so this is not a breaking change (available since Rust 1.70).
Closes: https://github.com/tokio-rs/tokio/issues/6202
=> net: add `unix::SocketAddr::as_abstract_name`

README.md, tokio/README.md
I'm making the release an LTS until september rather than July to synchronize with the other release that is an LTS until March.
=> tokio: add 1.47 as LTS release

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_write.rs
Fixes #7481 
There is no function to create an instance of `FramedWrite` with a specified capacity in a similar manner that `FramedRead::with_capacity` is currently implemented.
Add `FramedWrite::with_capacity` to create a BytesMut buffer and set backpressure boundary with the specified capacity.
=> codec: add `FramedWrite::with_capacity`

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- process: fix panic from spurious pidfd wakeup ([#7494])
[#7494]: https://github.com/tokio-rs/tokio/pull/7494
=> Prepare Tokio v1.43.2

README.md, tokio/CHANGELOG.md, tokio/Cargo.toml, tokio/README.md
- process: fix panic from spurious pidfd wakeup ([#7494])
- sync: fix broken link of Python `asyncio.Event` in `SetOnce` docs ([#7485])
[#7494]: https://github.com/tokio-rs/tokio/pull/7494
[#7485]: https://github.com/tokio-rs/tokio/pull/7485
=> Prepare Tokio v1.47.1

tokio/src/sync/set_once.rs
I realized that the cancel safety section was missing.
I also removed use of the word "blocking" to avoid confusion with [blocking the thread](https://ryhl.io/blog/async-what-is-blocking/).
=> sync: document cancel safety on `SetOnce::wait`

tokio-util/CHANGELOG.md, tokio-util/Cargo.toml
- codec: add `FramedWrite::with_capacity` ([#7493])
- future: add adapters of `CancellationToken` for `FutureExt` ([#7475])
- sync: add `DropGuardRef` for `CancellationToken` ([#7407])
- task: add `AbortOnDropHandle::detach` ([#7400])
- task: stabilise `JoinMap` ([#7075])
- codec: also apply capacity to read buffer in `Framed::with_capacity` ([#7500])
- sync: make `CancellationToken::run_until_cancelled` biased towards the token ([#7462])
- task: remove raw-entry feature from hashbrown dep ([#7252])
- compat: add more documentation to `tokio_util::compat` ([#7279])
- sync: improve docs of `tokio_util::sync::CancellationToken` ([#7408])
[#7075]: https://github.com/tokio-rs/tokio/pull/7075
[#7252]: https://github.com/tokio-rs/tokio/pull/7252
[#7279]: …
=> Prepare tokio-util v0.7.16

tokio-util/src/task/join_map.rs
#7508. Flaky test due to the task completing prior to the task abortion being observed.
Ensure the task can never complete by using `std::future::pending()`.
=> fix(test): fix flaky joinmap test during abort

tokio/src/process/mod.rs
See https://github.com/tokio-rs/tokio/pull/7249#issuecomment-3146995525, since the `with` closure is only called once, it can be upgraded to `FnOnce` to allow mutation.
Changed `Fn` to `FnOnce` in `Command::spawn_with`
Tested with the following code
```rust
use tokio::process::{Command};
use std::process::Stdio;
#[tokio::main]
async fn main() {
let mut std_io: Option<Stdio> = None;
let hello = Command::new("echo")
.arg("Hello, world!")
.stdout(Stdio::piped())
.spawn_with(|cmd| {
let mut child = cmd.spawn()?;
std_io = child.stdout.take().map(Stdio::from);
Ok(child)
})
.expect("failed echo command");
let reverse = Command::new("rev")
.stdin(std_io.take().unwrap())
.output().await.unwrap();
assert_eq!(reverse.stdout, b"!dlrow ,olleH\n");
}
```
*I don't know all the implications of piping …
=> fix(process): upgrade Command::spawn_with to use FnOnce

.github/workflows/ci.yml
Wasm tests on master have been failing since Rust 1.89.0, so the Rust version is pinned temporarily.
=> ci: pin the rust version for wasm tests

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/loom.yml, .github/workflows/pr-audit.yml, .github/workflows/stress-test.yml, .github/workflows/uring-kernel-version-test.yml
Updates actions/checkout@v4 to actions/checkout@v5 across CI workflows.
Upgrade to actions/checkout@v5 for improved performance and stability.
Reference:
Latest version: https://github.com/actions/checkout/releases/tag/v5.0.0
=> ci: update GitHub actions/checkout to v5

tokio/src/net/tcp/listener.rs
=> net: qualify that `SO_REUSEADDR` is only set on Unix

tokio/src/runtime/task/id.rs
I want to use the id from a `JoinSet` as a key in a `BTreeMap`.
Implement `PartialOrd` and `Ord` for `Id`.
=> Implement `Ord` for `task::Id`

tokio/src/time/timeout.rs
Pull out the tail portion that is invariant for T into a separate function. 
This reduces the size of the built binaries for crates that use Tokio and target minimal code size.
The Rust compiler generates a separate copy of LLVM IR for each instantiation of templated functions. That means that code in a templated function that doesn't depend on the template types can be needlessly duplicated. The tail of `Timeout::poll` is one such function. Pulling the code that doesn't depend on the type `T` out into a separate function lets the compiler emit it once instead of once for each instantiation of `Timeout`.
=> Reduce the generated code size of Timeout<T>::poll

tokio-util/src/codec/framed.rs, tokio-util/src/codec/framed_read.rs, tokio-util/src/codec/framed_write.rs
Implement into_parts for FramedRead and FramedWrite.
Fixes #7472
into_parts() functionality is lacking for FramedRead and FramedWrite
Implement `into_parts()` method for `FramedRead` and `FramedWrite`
=> tokio-uitls: into_parts() for Framed Read/Write

tokio/src/net/tcp/stream.rs, tokio/src/net/unix/stream.rs
I'm writing a wrapper that I want to work for `OwnedReadHalf` _and_ `TcpStream`.
`OwnedReadHalf: AsRef<TcpStream>` already, so this helps.
`TcpStream: AsRef<Self>`
=> net: implement `AsRef<Self>` for `TcpStream` and `UnixStream`

tokio/src/sync/mutex.rs, tokio/src/sync/rwlock.rs
Remove two `unsafe {}` in the code. Blocked until rustc 1.83 MSRV.
=> sync: use `UnsafeCell::get_mut` in `Mutex::get_mut` and `RwLock::get_mut`

tokio-stream/src/wrappers/tcp_listener.rs
The example of TcpListenerStream uses listener1.chain(listener2). This way it will always poll the first listener until it is fully consumed, i.e. closed. Then it will start polling the second listener. It would be better to use `listener1.merge(listener2)` instead. This way both listeners will be polled one after the other.
While here also fix a typo in the constants for LOCALHOST - ipv4_listener actually used Ipv6Addr::LOCALHOST and ipv6_listener - Ipv4Addr::LOCALHOST
The documentation of TcpListenerStream was using the wrong constants. Also the `chain()` method will try to consumer the first Stream fully before polling the second. Using `merge()` would be better because it will poll both listeners one after the other.
Improve the sample in the documentation.
=> stream: improve the the docs of `TcpListenerStream`

tokio/src/process/unix/pidfd_reaper.rs
`uname -r` returns a string that ends with a newline.
4825c444eb29b05c9c0b6f4a4c89475cb2556c65 improved the parsing of the `uname -r` result to handle the case when there is no '-'.
Usually the version string looks like `6.11.0-109019` but 4825c444eb29b05c9c0b6f4a4c89475cb2556c65 explained it could also be just `6.11.0` (this is how it behaves on MacOS!).
Custom kernel builds could even use shorter version like `6.11`. In this case the string returned by `uname -r` will be "6.11\n" and the parse of "11\n" would fail. 
Trimming the `minor` part would keep it working.
=> process: fix unit test for trailing LF in `uname -r`

examples/connect-udp.rs
The connect-udp example reads `n` bytes from the reader but writes the full 1024 bytes buffer to stdout. It should write only the `n` bytes it just read.
Write only `n` bytes to stdout: 
```rust
Bytes::copy_from_slice(&buf[..n])
```
=> examples: fix the write length in the `connect-tcp` example

tokio/src/io/async_fd.rs
e53b92a9939565edb33575fff296804279e5e419 improved the documentation of clear_ready() and clear_ready_matching() methods but made a small copy/paste error - the documentation of clear_ready_matching() talks about `clear_ready()` as `this method`
Fix the typos by replacing `clear_ready` with `clear_ready_matching` where wrong.
=> io: fix typos in the docs of two `AsyncFd` readiness guards

tokio/src/loom/std/parking_lot.rs
bd4ccae184b0359cb88f9ebc2ba157867e1eee0e introduced a wrapper for the RwLock to get rid of poisoning aspects.
By mistake (?!) its try_read/write methods actually delegate to read/write() and this would lead to blocking
Delegate the to try_** methods of the delegate to avoid blocking.
=> loom: loom::std::parking_lot::RwLock try_read/try_write methods block

tokio/src/fs/file.rs
Add a getter for fs::File::max_buf_size.
Requested at https://github.com/tokio-rs/tokio/pull/7593#issuecomment-3269352816 for a cleaner changelog
Add a simple getter for fs::File::max_buf_size field
=> fs: add `File::max_buf_size`

tokio/src/sync/broadcast.rs
The old documentation was "Allocation failure may result in ... an [allocation failure]"
This commit replaces the latter to `[allocation error]` to avoid the recursion in wording.
=> sync: Improve a bit the documentation about allocation failure

tokio-macros/Cargo.toml
The release steps at tokio-macros/Cargo.toml use old version for the Git tag name: 1.x.y
https://github.com/tokio-rs/tokio/blob/f07233f742c02cd84c48b9c6010ed7f4671e0a3a/tokio-macros/Cargo.toml#L6-L7
Change `1.x.y` to `x.y.z` so that it does not become obsolete again when tokio-macros 3.x is released
=> macros: update the example git tag used in the release guide

tokio/src/io/mod.rs, tokio/src/io/util/mod.rs
I want to downcast a `hyper::upgrade::Upgraded`.
This also makes the code consistent with `Take`, and other combinators like those found in `std::iter`
=> io: export Chain for users of AsyncReadExt::chain

tokio/src/net/udp.rs
* On Windows the self.io.peek() method may return an error, not `peek_from`
* poll_peek() does not return the sender address on success. It returns Poll::Ready(Ok(())) indicating no problems during the peek
* A comment mentions `recv` that read the `n` bytes. It is actually self.io.peek()
Fix the typos / copy-paste errors in docs and comments
=> net: Fix copy/paste errors in udp peek methods

tokio/src/runtime/task/id.rs, tokio/src/task/join_set.rs
Fixes: #7553
As discussed in the above issue, we have an implicit guarantee that a task ID is not reused until both the task finishes and its `JoinHandle` is joined on or dropped. User code requires this guarantee to do useful things with the ID, so this PR updates docs to make it more explicit.
I chose the wording "joined on" to cover cases outside of plain `.await`. In particular, joining a task via `&mut JoinHandle` (e.g. `tokio::select!`) counts for all intents and purposes, despite not strictly consuming the `JoinHandle`.
=> task: clarify task ID reuse guarantees

tokio/src/sync/mod.rs, tokio/src/sync/watch.rs
Since `watch` is a multi-producer channel its documentation should talk about many/all Senders.
Update the documentation for Receiver::changed() that RecvError will be returned only when all senders are dropped.
=> sync: improve the docs of `sync::watch`

tokio/src/runtime/builder.rs
If the interval is set to 1 then the schedulers will always execute tasks from the global queue. Tasks from the local queue will be executed only if the global queue is empty.
multi_thread scheduler: https://github.com/tokio-rs/tokio/blob/7127e257a7d7025a5f6a62eb8aab81c2191f5cdb/tokio/src/runtime/scheduler/multi_thread/worker.rs#L806-L813
I think this clarification is needed because of
```
Setting the interval to a smaller value increases the fairness of the scheduler,
/// at the cost of more synchronization overhead.
```
at https://github.com/tokio-rs/tokio/blob/7127e257a7d7025a5f6a62eb8aab81c2191f5cdb/tokio/src/runtime/builder.rs#L980C16-L981C54
With `1` there is no fairness anymore
Add a sentence to the documentation about the special case of `global_queue_interval=1`
=> runtime: clarify the edge case of `Builder::global_queue_interval()`

tokio/src/runtime/task/state.rs
When running with Miri, or dated arch like POWER, load(Acquire) might return old value. 
But in the branch "COMPLETE || NOTIFIED" which returns None directly,  might lead to a deadlock in a race condition.
Example code of deadlock report under Miri can be found in this issue: https://github.com/tokio-rs/tokio/issues/7589
1. In this PR, use additional CAS with the same value to ensure a happen-before relationship. It will not be necessary on x86, but it's the smallest change， chances that waking the waker concurrently or waking the waker after it's complete might be rare.
2. An alternative solution might be changing the load to SeqCst, which will prevent Miri from reading old value,
but I am not sure what will happen when fetch_update_action() go to the branch a second time.
=> waker: Fix weak memory issue in wake_by_ref()

tests-build/tests/fail/macros_type_mismatch.stderr
CI is failing due to the Rust 1.90.0, see <https://github.com/tokio-rs/tokio/actions/runs/17831193133/job/50699935384?pr=7467>.
=> ci: fix compiler output changes in Rust 1.90.0

tokio/src/sync/broadcast.rs, tokio/tests/sync_broadcast.rs
tokio::sync::broadcast::Sender::closed() should return Poll::Ready if there are no receivers for the channel.
A newly created Sender with `Sender::new()` currently returns Poll::Pending although there are no receivers for it.
Initialize Tail::closed with `receivers_count == 0`
=> sync: close the `broadcast::Sender` in `broadcast::Sender::new()`

tokio-util/src/task/join_queue.rs, tokio-util/src/task/mod.rs, tokio-util/tests/task_join_queue.rs
New `tokio_util::task::JoinQueue` structure as FIFO-ordered analog of `tokio::task::JoinSet`.
Issue: #7576
_Edit:_ renamed from `JoinDeque` to `JoinQueue`.
=> task: add `tokio_util::task::JoinQueue`

netlify.toml
See <https://app.netlify.com/projects/tokio-rs/deploys/68d8b0ea0ad8820008da8f26>, I opened a issue to the `lock_api` (<https://github.com/Amanieu/parking_lot/issues/494>).
```
11:53:23 AM: error[E0557]: feature has been removed
11:53:23 AM:   --> /opt/buildhome/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.13/src/lib.rs:89:29
11:53:23 AM:    |
11:53:23 AM: 89 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
11:53:23 AM:    |                             ^^^^^^^^^^^^ feature has been removed
11:53:23 AM:    |
11:53:23 AM:    = note: removed in 1.58.0; see <[https://github.com/rust-lang/rust/pull/138907&gt;](https://github.com/rust-lang/rust/pull/138907%3E) for more information
11:53:23 AM:    = note: merged into `doc_cfg`
11:53:23 AM: For more information about this error, …
```
=> ci: freeze rustc on nightly-2025-01-25 in `netlify.toml`

.cirrus.yml, .github/workflows/ci.yml, tokio-macros/src/lib.rs, tokio/src/lib.rs
The fixup of <https://github.com/tokio-rs/tokio/pull/7621> for better error message. Otherwise, the error message is a bit encrypted.
```bash
$ cargo run
error: failed to select a version for `tokio`.
... required by package `uring-test v0.1.0 (xxxx)`
versions that meet the requirements `*` (locked to 1.47.1) are: 1.47.1
package `uring-test` depends on `tokio` with feature `io-uring` but `tokio` does not have that feature.
A required dependency with that name exists, but only optional dependencies can be used as features.
failed to select a version for `tokio` which could resolve this conflict
```
This is a bit complicated. It seems like it's not worth the complexity, but we still have to do it because we also want to convert `--cfg tokio_taskdump` into a Cargo feature, and taskdump …
=> fs: emit compilation error without `tokio_unstable` for `io-uring`

tokio-util/src/task/task_tracker.rs
This PR uses `with_cancellation_token_owened` inside the `TaskTracker` documentation. This avoids using the `select!` macro. The rationale is one described inside the [`select!` documentation](https://docs.rs/tokio/latest/tokio/macro.select.html#alternatives-from-the-ecosystem) :
> The select! macro is a powerful tool for managing multiple asynchronous branches, enabling tasks to run concurrently within the same thread. However, its use can introduce challenges, particularly around cancellation safety, which can lead to subtle and hard-to-debug errors. For many use cases, ecosystem alternatives may be preferable as they mitigate these concerns by offering clearer syntax, more predictable control flow, and reducing the need to manually handle issues like fuse semantics or cancellation …
=> task: simplify the example of `TaskTracker`

tokio-macros/src/entry.rs
This PR intent to resolve bug mentioned in #7650 
When user explicitly set on clippy lint rule, `clippy::unwrap_in_result`, and use macro `tokyo::main`, they will get error.
An example test program:
```toml
[toolchain]
channel = "nightly"
```
```toml
[package]
name = "tokio-test"
version = "0.1.0"
edition = "2024"
[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["macros", "rt", "rt-multi-thread"] }
[lints.clippy]
unwrap_in_result = "deny
```
```rust
// main.rs
use anyhow::Result;
#[tokio::main]
async fn main() -> Result<()> {
println!("Hello, world!");
Ok(())
}
```
Than, run command `cargo clippy`:
```terminal
error: `expect` used in a function that returns a `Result`
--> src/main.rs:7:5
|
7 |     Ok(())
|     ^^^^^^
|
note: in this function signature
--> …
```
=> macros: suppress `clippy::unwrap_in_result` in `#[tokio::main]`

tokio/src/sync/mpsc/unbounded.rs
While trying to understand how the send for unbounded channel works, I wasn't sure why an unbounded channel never requires any form of waiting. I found a similar explanation in the sync's mod.rs that explains it well, so I was wondering if it's worth adding it also within the send docs.
Adds explanation on why an unbounded channel never requires any form of waiting.
=> sync: improve unbounded send method docs
